### ISSUE TITLE
Wamo Pro controller support

### ISSUE THREAD

**Issue by jaimie-van-santen** [moonlight-stream/moonlight-android#10]
Hey,

At the moment Limelight seems to detect a controller and lets steam detect it as xinput based controller according to settings. Tho, the left stick seems to function the right one, dpad, y/b/a/x/(any other button) and triggers don't work. Pushing B or Y for example triggers android's back function and kills Limelight. 

I have the controller connected in gamepad mode. Games like Asphalt 8 and Death trigger 2 detect it automatically and seems to work perfectly for those.

Love the progress so far and liking Limelight! If there's anything i could do to help I would do so gladly! Thanks!

Cheers

**Comment by mrb113** [comment]
Closing since this is over a year old and didn't get any traction. If this is still an issue, please reactivate and tag Cameron.

**Comment by whise** [comment]
There should be an option to allow to remap controllers... I have a Nintendo pro controller, top end controller and it's not supported. Please add this feature
