### ISSUE TITLE
Grouping games, games folders

### ISSUE THREAD

**Issue by Daviid-P** [moonlight-stream/moonlight-android#1001]
I'm not sure how the app gets the games data, would it be possible to group games in folders?

Like Action folder, Visual Novel folder, Puzzle folder.

I see creating folders on `AppData/Local/NVIDIA Corporation/Shield Apps` doesn't work, but I don't know if it's because Moonlight ignores them or if it's because it doesn't even get that data.

**Comment by cgutman** [comment]
It’s because we don’t get the data. The app list XML is just a flat list of all apps.

**Comment by DaviidC** [comment]
> It’s because we don’t get the data. The app list XML is just a flat list of all apps.

Damn, that sucks.
Another good suggestion I think would be to move the launched session to the top, that way if you have a lot of games you don't have to scroll to find it.

Something like this?
https://i.imgur.com/AiC6SeT.png
