### ISSUE TITLE
Support streaming from "wide" phones/Native Full-Screen fix

### ISSUE THREAD

**Issue by Foxyz1302** [moonlight-stream/moonlight-android#1003]
People have said that it's impossible to fix that but I found a way to connect to pc __desktop__ with full resolution, which involves:
1. Connect to pc with Moonlight with a "working" resolution (Like 1920x1080)
2. Switch resolution to the "wide" one (In my case 2400x1080), it will work but will be squished
3. Disconnect and go to settings without Quitting the session
4. Switch to "Native Full-Screen"
5. Go back to the desktop.

And with that I have moonlight running the __desktop__ on my phone's native res completely fine, which lets me use the desktop and play games in borderless/windowed.

So I was wondering if it's possible to somehow automatize this process? Because it's extremely obnoxious with the fact that you need to start Nvidia control panel which takes some time to actually appear.

**Comment by austinarchibald** [comment]
+1 for this. Missing out on real estate on my iPhone 15 Pro Max with the thick black edges on the sides.

**Comment by cgutman** [comment]
@austinarchibald This is the Android bug tracker, but that feature is coming in the next iOS release.
