### ISSUE TITLE
High latency on Philips Android TV

### ISSUE THREAD

**Issue by PhilippGrulich** [moonlight-stream/moonlight-android#101]
Hey guys,

I really like your app and it works perfectly on my Nexus 5.

I also have a new Philips Android TV (PUS7100) and it would be great if it works on that as smooth as on the nexus.

When I use hardware decoding on the philips tv i usually get a latency between 400-500ms which is way to slow. But the video which is displayed is smooth.
If I use software decoding I get a latency about 40ms but the video is stocking and this message is displayed: "Your device is processing A\V data to slow".

I think the TV use this soc :
http://www.donaldsleviejr.com/files/samples/Product%20Brief%20-%20Microprocessor.pdf
with 1GB RAM.

How can I help to improve this situation?

Philipp

**Comment by cgutman** [comment]
Please report results with these 2 builds

BS - https://onedrive.live.com/redir?resid=C15BF9770619F56!160583&authkey=!AHzhBwAokhZhw_A&ithint=file%2capk
CB - https://onedrive.live.com/redir?resid=C15BF9770619F56!160582&authkey=!AFI8zrHGkl2nsqc&ithint=file%2capk

**Comment by Fuechslein** [comment]
Hi,

I had the same problem as Philipp but on the PUS9809. Tried both your builds: CB doesnt change much but BS gives me around 100ms with 720p@60 no matter what bandwidth. 720p@30 gives me around 170ms. 1080p is still >400ms.

BS build is a real improvement over the official build! If you could optimize it a little further and squeeze out some more performance I'd be more than happy (:

**Comment by cgutman** [comment]
Here are 4 more builds to try:

https://onedrive.live.com/redir?resid=C15BF9770619F56!160592&authkey=!AAyWLrvde30wDXA&ithint=file%2capk
https://onedrive.live.com/redir?resid=C15BF9770619F56!160593&authkey=!APrLuvmFDf0P52k&ithint=file%2capk
https://onedrive.live.com/redir?resid=C15BF9770619F56!160590&authkey=!AF2f_6jTVXJov_M&ithint=file%2capk
https://onedrive.live.com/redir?resid=C15BF9770619F56!160591&authkey=!AE0Zd-SKPftJLHk&ithint=file%2capk

**Comment by Fuechslein** [comment]
Thank you for the quick response!

I will try them as soon and report back, as soon as I'm back home again. If any of those perform even better than the BS build before, you have saved me from spending 200 bucks on the Shield console!

On another note, can you explain why I have a lower latency at 60fps compared to 30fps? Shouldnt it be easier to decode a 30fps stream as opposed to a 60fps stream?

**Comment by Fuechslein** [comment]
Finally had time to test them. 1,2 and 4 perform about the same as bs with build 4 having a slight advantage of about 3-4 ms. Build 3 is worse than any version I tested, including the original release.

Looks like I cant really break the magical 100ms barrier :P If you have another build I could try, then I gladly will, otherwise thanks for your effort! :)
