### ISSUE TITLE
Moonlight is streaming at 1280x720 instead of the selected 2560x1600

### ISSUE THREAD

**Issue by sofakng** [moonlight-stream/moonlight-android#1012]
**Describe the bug**
I've selected "Native (2560x1600)" resolution in Moonlight but when it connects to the host it's only streaming at 1280x720.  The Moonlight overlay says it's 2560x1600 but it's really only 1280x720 (as verified in the Windows Display Settings, etc).

**Steps to reproduce**
n/a

**Screenshots**
If applicable, add screenshots to help explain your problem. If the issue is related to video glitching or poor quality, please include screenshots.

**Affected games**
All games including desktop streaming (mstsc.exe).

**Other Moonlight clients**
- Does the issue occur when using Moonlight on PC or iOS?  I'm using moonlight-qt on my Macbook Pro M1.

**Moonlight settings (please complete the following information)**
- Have any settings been adjusted from defaults?  No
- If so, which settings have been changed?  No
- Does the problem still occur after reverting settings back to default?  n/a

**Gamepad-related issues (please complete if problem is gamepad-related)**
- Do you have any gamepads connected to your host PC directly?
- If gamepad input is not working, does it work if you use Moonlight's on-screen controls?
- Does the problem still remain if you stream the desktop and use https://html5gamepad.com to test your gamepad?
  - Instructions for streaming the desktop can be found here: https://github.com/moonlight-stream/moonlight-docs/wiki/Setup-Guide

**Device details (please complete the following information)**
 - MacBook M1 Pro running MacOS Big Sur v11.3

**Server PC details (please complete the following information)**
 - OS: Windows 10 20H2
 - GeForce Experience version: 3.23.0.74
 - Nvidia GPU driver: 496.13
 - Antivirus and firewall software: Windows Defender and Windows Firewall

**Additional context**
n/a

**Comment by Czahrien** [comment]
Hello there,

I ran into this post when researching the same problem when using moonlight-qt on my M1 Macbook Pro as well and I found my answer on the FAQ - https://github.com/moonlight-stream/moonlight-docs/wiki/Frequently-Asked-Questions#why-does-my-host-pc-resolution-change-to-720p-when-i-start-streaming

Long story short after I was into the game I was trying to play I set the game to fullscreen 2560x1600 and it looked great!

For issues with moonlight-qt I think you normally would want to create an issue at  https://github.com/moonlight-stream/moonlight-qt/issues/

Hope this helps!

**Comment by sofakng** [comment]
Thanks for the reply!

I think that solution works but not all games allow you to set the resolution and "fullscreen" just uses the desktop resolution.
