### ISSUE TITLE
motion controls using SDL controller API

### ISSUE THREAD

**Issue by manaboy** [moonlight-stream/moonlight-android#1013]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

Just wondering, been playing the Cemu wiiu emulator on my pc and was using moonlight on my android phone with ipege controller to mimic the WiiU gamepad, touch works and everything however, there is no way to translate motion from the smartphone internal motion sensing

**Comment by MABlosfeld** [comment]
I'm thinking about the possibility of adding a part of the FREEPIU IMU source code inside the MOONLIGHT source code. I installed ANDROID STUDIO, I'm studying tutorials but the lack of knowledge is making the work difficult.

**Comment by MABlosfeld** [comment]
We already have everything we need, freepie to transmit track movements to opentrack and moonlight android to receive streaming from nvidia shield.

**Comment by MABlosfeld** [comment]
Freepie works fine but when I start Moonlight the data transmission turns off by itself.

**Comment by kunal52** [comment]
@MABlosfeld Have you implement it?

**Comment by MABlosfeld** [comment]
I have installed the APP game launcher from samsung on my smartphone, in the settings I found an overlay option, I disabled this option and now the freepie IMU app doesn't close.

**Comment by kunal52** [comment]
I didn't find any FreePIE app. Could you please share the link and guide on how you done it?

**Comment by MABlosfeld** [comment]
the FREEPIE IMU apk comes with the OPENTRACK (https://github.com/opentrack/opentrack/releases) installation, after installing it, search here (?:\opentrack\doc\contrib\freepie-udp\FreePIE_IMU_Android9.apk) connect your cell phone to your pc and transfer the file and run the installation.
