### ISSUE TITLE
Connection Terminated Automatically when streaming over the Internet and I touch the screen

### ISSUE THREAD

**Issue by yhxkry** [moonlight-stream/moonlight-android#1017]
**Describe the bug**

When I am streaming on the same network, everything is fine.

When streaming **over the Internet**, I can connect to my PC successfully. However, then if I move the mouse by touching screen for a second, the connection will be terminated automatically!  

Error information is  "Connection Terminated  ///  The connection was terminated"

If I don't touch the screen, the connection will last normally.

Real-time stream performance information shows my network is OK.

All the ports（including TCP and UDP) are forwarding properly.

I have tried use 497.09 NVIDIA driver or 472.12. NVIDIA driver, but the trouble still continues.

**Other Moonlight clients**
- Does the issue occur when using Moonlight on PC or iOS?
- YES, I try on a laptop over the Internet, this trouble still here..... mouse moves and connection terminated. **Besides，on laptop I also try clicking keyboard instead of moving mouse, and again connection terminated.**

**Moonlight settings (please complete the following information)**
- Have any settings been adjusted from defaults?
- If so, which settings have been changed?
- Does the problem still occur after reverting settings back to default?

**Device details**
 - Android version: [Android 11]
 - Device model: I have tried on servels phones of different brands.

**Server PC details (please complete the following information)**
 - OS: [Windows 10 21H2]
 - GeForce Experience version: [3.24.0.123]
 - Nvidia GPU driver: [497.09]
 - Antivirus and firewall software: Windows Defender and Windows Firewall]

**Comment by cgutman** [comment]
I tried with the same software versions and couldn't reproduce the issue.

Please post the logs from your host PC in the `C:\ProgramData\NVIDIA Corporation\NvStream` folder after the bug occurs.

**Comment by yhxkry** [comment]
> I tried with the same software versions and couldn't reproduce the issue.
> 
> Please post the logs from your host PC in the `C:\ProgramData\NVIDIA Corporation\NvStream` folder after the bug occurs.

hello , u find anything wrong?

**Comment by cgutman** [comment]
```
#7(E)[2021-12-02 16:16:40,699]=00:16:40={8752}<NvscStreamingSes> Client has not responded in 10008 ms, triggering disconnection
```
It appears that the connection from the client is interrupted. I have seen this happen if there is too much traffic between the host and client for the network connection to handle.

Can you perform a speed test on your host PC's Internet connection and your client's Internet connection?

**Comment by yhxkry** [comment]
Do you mean that you hope me to perform a speed test **between** my PC and client ?  How to perform this ?......

Actually ,  I tried using Windows' Remote Desktop to control my PC over the Internet  and  Remote Desktop works well. 

So in this case, I turn to thinking about if there is any problem with my Router (OpenWrt) in terms of UDP. Maybe firewall setting prevents it from connection.

Then I test all the UDP ports and  they can be connected successfully.  So....still no idea.

**Comment by yhxkry** [comment]
> ```
> #7(E)[2021-12-02 16:16:40,699]=00:16:40={8752}<NvscStreamingSes> Client has not responded in 10008 ms, triggering disconnection
> ```
> 
> It appears that the connection from the client is interrupted. I have seen this happen if there is too much traffic between the host and client for the network connection to handle.
> 
> Can you perform a speed test on your host PC's Internet connection and your client's Internet connection?

hi ,any advice?
