### ISSUE TITLE
Prefix validation code in AddComputerManually.java prevents me from adding reachable hosts on other VLANs

### ISSUE THREAD

**Issue by telnetdoogie** [moonlight-stream/moonlight-android#1018]
If you have a host on a separate VLAN (in my case, my client (TV) is on `192.168.30.x`, and my host (PC) is on `192.168.1.x`) the following lines in [https://github.com/moonlight-stream/moonlight-android/blob/d3f2284791928f44e72937ea8fe116d50a88701f/app/src/main/java/com/limelight/preferences/AddComputerManually.java](AddComputerManually.java) prevent an otherwise reachable host from being added manually:

```
// We have a site-local address. Look for a matching local interface.
for (NetworkInterface iface : Collections.list(NetworkInterface.getNetworkInterfaces())) {
    for (InterfaceAddress addr : iface.getInterfaceAddresses()) {
        if (!(addr.getAddress() instanceof Inet4Address) || !addr.getAddress().isSiteLocalAddress()) {
            // Skip non-site-local or non-IPv4 addresses
            continue;
        }

        byte[] targetAddrBytes = targetAddress.getAddress();
        byte[] ifaceAddrBytes = addr.getAddress().getAddress();

        // Compare prefix to ensure it's the same
        boolean addressMatches = true;
        for (int i = 0; i < addr.getNetworkPrefixLength(); i++) {
            if ((ifaceAddrBytes[i / 8] & (1 << (i % 8))) != (targetAddrBytes[i / 8] & (1 << (i % 8)))) {
                addressMatches = false;
                break;
            }
        }

        if (addressMatches) {
            return false;
        }
    }
}
```
...Although I understand why this was added, the notion that "if a machine isn't on the same subnet as my current interface" does not mean that the machine is not still local nor reachable, especially when they're both in the RFC1918 local network range.
A 192.168.1.1 may be defined at the interface to be 192.168.1/24, however the private address space for this block is actually 192.168/16. 

My suggestion is to either remove that block of code, or add additional conditions such that if current address is 10/8, only the `10.` is tested, if the current address is 172.16.0.0/12, only 172.16 - 172.31 is evaluated, and if the current address is 192.168/16, only the 192.168 is tested. 

Perhaps better yet would be to ask users to make sure the host is pingable from the client, and use Inet4Address.isReachable() in the case when the addresses are local?

@cgutman tagged here

**Comment by telnetdoogie** [comment]
additional idea would be to change the bounds of the loop from addr.getNetworkPrefixLength() to a prefix length suitable for the specific RFC1918 space that the current address occupies.

**Comment by cgutman** [comment]
`isWrongSubnetSiteLocalAddress()` is only called in the case where attempting to add the PC has already failed, so it doesn't prevent the actual process of adding the PC from working. It is simply used to (usually) display a more relevant error message to the user when it does fail.

https://github.com/moonlight-stream/moonlight-android/blob/da45cba2ff985aed6660531d1e7c1127fd126787/app/src/main/java/com/limelight/preferences/AddComputerManually.java#L117-L119

You are correct that machines on a different RFC1918 subnet are not necessarily unreachable depending on your network topology and it can be misleading when the check produces a false positive. I think it's a net positive, since the majority of users putting a non-on-link RFC1918 address are indeed making a mistake. I'm not sure if/how we can fix it to be smarter when that configuration is actually expected.

**Comment by telnetdoogie** [comment]
that makes a ton of sense, @cgutman . Thanks for that clarification, I hadn't seen that flow where the code was called.

Just for fun, I started playing with the validation code anyways and assuming the original prefix loop and if statement are correct, I put this together. Probably a waste of time and definitely unneeded based on that flow, but oh well. I had fun anyways :) :

```
private boolean isWrongSubnetSiteLocalAddress(String address) {
        try {
            InetAddress targetAddress = InetAddress.getByName(address);
            if (!(targetAddress instanceof Inet4Address) || !targetAddress.isSiteLocalAddress()) {
                return false;
            }

            List<NetworkInterface> interfaces = Collections.list(NetworkInterface.getNetworkInterfaces());
            List<InetAddress> localInterfaceAddresses = new ArrayList<>();

            // The address provided is site-local. Look for a compatible local interface.
            for (NetworkInterface localInterface : interfaces) {
                List<InterfaceAddress> interfaceAddresses = localInterface.getInterfaceAddresses();
                localInterfaceAddresses.addAll(localInterface.getInterfaceAddresses().stream()
                        .map(InterfaceAddress::getAddress)
                        .filter(addr -> addr.isSiteLocalAddress() || addr instanceof Inet4Address).collect(Collectors.toList()));
            }

            // We have a site-local address. Look for a matching local interface.
            for (InetAddress localAddress : localInterfaceAddresses) {

                byte[] thisAddress = localAddress.getAddress();
                short prefixLength;

                byte firstByte = thisAddress[0];
                switch (firstByte) {
                    case (byte) 192:
                        prefixLength = 16;
                        break;
                    case (byte) 172:
                        prefixLength = 12;
                        break;
                    default:
                        prefixLength = 8;
                        break;
                }

                byte[] targetAddrBytes = targetAddress.getAddress();
                byte[] ifaceAddrBytes = localAddress.getAddress();

                // Compare prefix to ensure it's the same
                boolean addressMatches = true;
                for (int i = 0; i < prefixLength; i++) {
                    if ((ifaceAddrBytes[i / 8] & (1 << (i % 8))) != (targetAddrBytes[i / 8] & (1 << (i % 8)))) {
                        addressMatches = false;
                        break;
                    }
                }
                if (addressMatches) {
                    return false;
                }
            }

            // Couldn't find a matching interface
            return true;

        } catch (Exception e) {
            // Catch all exceptions because some broken Android devices
            // will throw an NPE from inside getNetworkInterfaces().
            e.printStackTrace();
            return false;
        }
    }
```

...not even sure if you can use the streams code in Android. Thanks so much for the clarification @cgutman ! I'll close the issue
