### ISSUE TITLE
S Pen Support

### ISSUE THREAD

**Issue by BetaLeaf** [moonlight-stream/moonlight-android#102]
I have 2 Problems.

1. S Pen will not function at all in your app. All input from the S Pen is seemly ignored.
2. No option to change mouse move mode. If S Pen support is implemented with the SDKs, user's may need an option so they can properly use the S Pen, without having to drag across the screen to move the mouse. The S Pen grants the user extreme accuracy and in games where buttons are very small, the very accurate S Pen helps a lot.

Here's some resources to get you started: http://developer.samsung.com/s-pen-sdk/technical-docs/S-Pen-SDK-2-3-Tutorial

**Comment by cgutman** [comment]
Please check if problem #1 is fixed in this build - https://onedrive.live.com/redir?resid=C15BF9770619F56!160581&authkey=!AEPt2nmqcFLH9gs&ithint=file%2capk

**Comment by BetaLeaf** [comment]
Thank you. #1 is fixed. Now if we can get #2 working. currently, moving the s pen moves the mouse relative to where it was previously. The idea is to allow the user to click and drag exactly where the s pen touches the screen.
Again, Thank you for your work. If its also not too much trouble I am curious how you got #1 working?

**Comment by cgutman** [comment]
I really would like to add #2 but the GameStream protocol doesn't let me send absolute coordinates to the PC. I can only send relative movements, hence you get the trackpad-style behavior. I hope Nvidia adds this to the server in a later update.

The commit that fixed it was this one: 87a9ca43183b02348714ea71f7642d8a67d6838a
I stopped checking for the exact sources before handling the input event. This was brittle and breaks if an unknown source is used (or a new source as is the case for Bluetooth stylus devices in Android Marshmallow).

**Comment by BetaLeaf** [comment]
Ah ok. Thanks for your help.

**Comment by cgutman** [comment]
This is finally supported now that the appropriate protocol has been figured out :confetti_ball: 

https://github.com/moonlight-stream/moonlight-android/commit/c3b81554f43301a7e37a1d6bf743df9ff3f3ae0f
