### ISSUE TITLE
Allow streaming from a PC in a different subnet. Moonlight forces to use the internet for no reason...

### ISSUE THREAD

**Issue by rkkoszewski** [moonlight-stream/moonlight-android#1022]
**Is your feature request related to a problem? Please describe.**
I'm using 2 subnets in my network, I have my PC in one of them, and my Tablet in the other one. Trying to stream via Moonlight from the tablet yields an error saying: The address doesn't look right. You must use your router's public IP address for streaming over the internet.

Why is this limitation set? UDP works perfectly fine across subnets (Unless broadcast is needed). Could the limitation be disabled by any way?

**Comment by cgutman** [comment]
That check isn't the problem. It only serves to try to provide a more useful error when the connection has _already failed_. See #1018

I just need to change the message so it's more obvious that having the wrong address _might_ be the problem, but it is not necessarily the problem.
