### ISSUE TITLE
Galaxy Tab S7 with Keyboard Cover mouse not working

### ISSUE THREAD

**Issue by 89jd** [moonlight-stream/moonlight-android#1029]
**Describe the bug**
On a Samsung Galaxy Tab S7 with keyboard cover, the trackpad isn't moving the mouse. I can click the trackpad and it works as expected, and actually if I move the cursor with the trackpad before I click it, it moves to where I moved it too. I am not convinced it is moving it before hand though, as I can't seem to see any hover animations or anything on Windows. Also, touchscreen mouse control works as expected

**Steps to reproduce**
Use Moonlight with Keyboard Cover

**Screenshots**
N/A

**Affected games**
N/A

**Other Moonlight clients**
- Does the issue occur when using Moonlight on PC or iOS?
Android

**Moonlight settings (please complete the following information)**
- No

**Gamepad-related issues (please complete if problem is gamepad-related)**
- No

**Device details (please complete the following information)**
 - Android version: [e.g. Android 10] Android 11
 - Device model: [e.g. Samsung Galaxy S21] Samsung Galaxy Tab S7

**Server PC details (please complete the following information)**
 N/A

**Additional context**
Anything else you think may be relevant to the issue or special about your specific setup.

**Comment by cgutman** [comment]
We discussed this with Samsung and this is not supported by the hardware.

Their response is here:
https://ideas.moonlight-stream.org/posts/41/support-samsung-s7-keyboard-cover-touchpad

**Comment by 89jd** [comment]
I understand why you hav closed the ticket. Would there be a way to show the cursor on moonlight?

Other remote desktop apps, seem to work with it. 

The issue is only that th cursor doesn't show on windows until I click. 

Feels like there might be a bit a workaround that could be done?

**Comment by himekifee** [comment]
It actually worked once for me but was affected by #1028. The second time it just did not show the cursor. Will investigate further when I have some time.
