### ISSUE TITLE
Stylus appears offset

### ISSUE THREAD

**Issue by lisyclover** [moonlight-stream/moonlight-android#1031]
It used to support stylus, but now it is not supported, there is an offset。Phone z fold3,android12.Latest software version

**Comment by montana013** [comment]
Same issue with my galaxy tab s7 i thinks it s android 12 issue not moonlight

**Comment by chancemon** [comment]
Same issue with Tab S7+ following update to Android 12.

**Comment by djxxjd** [comment]
i have the same problem

**Comment by cgutman** [comment]
Is this still affecting you on Moonlight v10.1 or later?

**Comment by lisyclover** [comment]
> 
The new version has fixed this problem, thank you

**Comment by lisyclover** [comment]
fix
