### ISSUE TITLE
Connection terminated issue

### ISSUE THREAD

**Issue by watermelon915** [moonlight-stream/moonlight-android#1032]
When i use moonlight connecting my computer,it can be connected,But it will disconnect in three to five seconds.Whether it's public network or LAN

**Comment by watermelon915** [comment]
[NvStreamerCurrent.log](https://github.com/moonlight-stream/moonlight-android/files/7878784/NvStreamerCurrent.log)
[NvStreamerOld.log](https://github.com/moonlight-stream/moonlight-android/files/7878785/NvStreamerOld.log)

**Comment by watermelon915** [comment]
> [NvStreamerCurrent.log](https://github.com/moonlight-stream/moonlight-android/files/7878784/NvStreamerCurrent.log) [NvStreamerOld.log](https://github.com/moonlight-stream/moonlight-android/files/7878785/NvStreamerOld.log)



This is my log file

**Comment by cgutman** [comment]
It looks like the encoder hang issue. Try updating to GeForce Experience 3.25.0.84 and see if that resolves the problem.

**Comment by cgutman** [comment]
Duplicate of https://github.com/moonlight-stream/nvidia-gamestream-issues/issues/27
