### ISSUE TITLE
Virtual Gamepad not working simultaneously with touch screen

### ISSUE THREAD

**Issue by K11MCH1** [moonlight-stream/moonlight-android#1034]
The Gamepad on-screen layout takes input priority over touch screen input.

This may be a bug, but also a request if it's not...

I have it currently set up as so the right Analog stick of the Gamepad on-screen layout is very tiny to make space to use touch screen input for camera panning in 1st and 3rd person games. (Like you would for example in PUBG or Call of Duty Mobile etc..)

But simultaneous input does not seem to work if the Gamepad layout is touched first.
However, it only works if the screen is touched first and then the Gamepad.

Fixing/adding this would be a great and a necessary step to improve Moonlight's ergonomy in gameplay styles. As many gamers are moving from Gamepad gaming to touch with Finger sleeves for 1st and 3rd person games, since they offer way better aiming accuracy than Gamepads.
Another better way might be to add a Touch screen layout similar to mobile games.

Thanks.

**Comment by cgutman** [comment]
Fixed in v10.1
