### ISSUE TITLE
RTSP Handshake fails after updating driver

### ISSUE THREAD

**Issue by occhep** [moonlight-stream/moonlight-android#1035]
Hello there I was using Moonlight to stream PC on android for some time without issues. But after the game ready driver update (2 days ago) from Geforce Experience the app can no longer connect to my PC; it always shows RTSP handshake failed. I followed the troubleshooting guide, even turned off firewall, nothing works. Can you please look into this? I think others who updated the driver might also experience this problem. I'm using the lastest versions of GeForce Experience and Moonlight.

**Comment by cgutman** [comment]
I'm consolidating these into https://github.com/moonlight-stream/nvidia-gamestream-issues/issues/32

Let's discuss there.
