### ISSUE TITLE
启用HDR功能不起作用

### ISSUE THREAD

**Issue by YABIJIU** [moonlight-stream/moonlight-android#1038]
GOD of WAR 4 SUPPORT HDR,BUT MOONLIGHT SAYS NO.
IF game use  WINDOW MODE,the screen is colorful。BUT BORDLESS MODE IS dusky。
Sometime bordless mode is colorful too，I dont know why HDR shows unstable.

**Comment by YABIJIU** [comment]
![e6b5a844565a78f65aca091d64a08d8](https://user-images.githubusercontent.com/62825205/151690496-22456496-195a-4207-ab53-2fea01f011e1.jpg)
BORDLESS MODE
![b450bc1ddee6f94bcbc780767679b6b](https://user-images.githubusercontent.com/62825205/151690500-3050a16d-60c9-4245-8512-e613e3943927.jpg)
WINDOW MODE

**Comment by YABIJIU** [comment]
bordless mode always like having some fogs over the screen.but today it became normal for a while.So I thought it is can be solve.

**Comment by cgutman** [comment]
God of War is an DXGI/OS HDR game which requires an HDR compatible display or EDID emulator on the host for the in-game HDR option to appear. See https://github.com/moonlight-stream/moonlight-docs/wiki/Setup-Guide#additional-requirements-for-hdr-streaming for additional details and requirements for HDR streaming.
