### ISSUE TITLE
RokuTV errors - No manifest

### ISSUE THREAD

**Issue by parkesto** [moonlight-stream/moonlight-android#1043]
Attempting to sideload on my RokuTV gives this error.

Any ideas?

![Screenshot_20220212-220300_Chrome](https://user-images.githubusercontent.com/49406827/153736491-0a23ac1b-bb54-4278-8432-c8c14693df8a.jpg)

**Comment by cgutman** [comment]
Roku isn't an Android device, so this is not expected to work.
