### ISSUE TITLE
Why my xboxones controller doesn't work on my TCL TV?

### ISSUE THREAD

**Issue by battleboy-cxx** [moonlight-stream/moonlight-android#1058]
**Why my xboxones controller doesn't work on my TCL TV** 
It's ok when I trying to stream to other platform (like my macbook, iphone...), and it perform well with a low lag. But when I trying to stream it on my tv. The video and audio can be welly streamed but when I was trying to using my xbox controller to play games, it just didn't work. I bind my xbox controller and my TCL tv via blue tooth. I can control the tv using my controller, but when inside the stream mode, I can see pic and hear the sound of the game, but I can't control. Also, I tried my bluetooth keyboard, and it doesnt work either. I guess it just cant stream the control sighnal to the original pc properly. How to fix it?

**Comment by cgutman** [comment]
If neither a bluetooth keyboard nor a bluetooth controller works with your TCL TV, it seems likely it doesn't support Bluetooth input devices. That isn't something we can fix.
