### ISSUE TITLE
Add Support for 4K/higher resolution

### ISSUE THREAD

**Issue by pkonecki** [moonlight-stream/moonlight-android#106]
Since 15 Oct. 2015 NVidia Geforce Experience supports 4K streaming.
http://www.geforce.com/whats-new/articles/geforce-experience-beta-update-introduces-new-gamestream-and-streaming-features

Would it be possible to add support for 4K (and or 1440p) streaming to moonlight? It would be especially useful for users with 1440p screens for use in VR headsets (cardboard etc...)

**Comment by cgutman** [comment]
Awesome, I'll check it out and see what I can do.

**Comment by pkonecki** [comment]
Apparently you need a Maxwell 2 gen GTX card (970-980) and an Android Shield TV.
Maybe you can make NVidia streaming server believe moonlight is an Android Shield Tablet or something.

**Comment by cgutman** [comment]
The Shield Android TV limitation doesn't apply; the whole point of Moonlight is for it to work if the hardware itself can support it. Devices that can do it will be able to.

The Maxwell restriction will apply though. I was able to stream 4K to my laptop using a test build of Moonlight-PC and it works as expected. I would like to test what happens if the hardware doesn't support it.

A Wireshark packet capture of Shield TV streaming 4K would be useful if anyone has a Shield and a 4K TV.

**Comment by likelyeatenbyagrue** [comment]
Will 5.1 audio work as well? Getting rid of 2 channel sound would be epic.

**Comment by cgutman** [comment]
Yes, 5.1 is in the works. I'm hoping to have something working today (possibly pushed to the beta channel of Moonlight).

@likelyeatenbyagrue What Android device are you streaming to?

**Comment by likelyeatenbyagrue** [comment]
Running moonlight embedded on raspberry pi 2.

**Comment by cgutman** [comment]
A build with 4K and 5.1 support is out on the beta channel of the Play Store.

**Comment by lastblade** [comment]
Gutman, can you add 1440p too ?
4k is too heavy for my machine and 1080p is below the native resolution of my screen :)

**Comment by Xeenice** [comment]
I have tested 1440p resolution and it works with the below specified patch only if your machine supports 1440p resolution. Note: if your monitor does not support this resolution you can just disconnect video cable and you get a standart monitor with video card supported resolutions.

Patch:
https://github.com/Xeenice/moonlight-android/commit/3ab3646bdee71523292a719912d2c97ae7c07f38.patch

**Comment by lastblade** [comment]
thanks

**Comment by olijf** [comment]
Would it be possible to use custom resolutions? On my nexus 9 which has a 4:3 ratio I would like to be able to use full screen natively instead of stretched.

**Comment by tartooth** [comment]
Sorry for being noobish, but where can I access the beta? Do you have to invite?

Cheers

**Comment by Zaine6** [comment]
Has it been explained how to apply that patch above? Also for 3440 x 1440 is it as simple as modifying the numbers in that file?

Thanks

**Comment by cgutman** [comment]
4K support is released. Adding other resolutions is a separate issue that will be addressed once 4K support makes it to GFE's production release.

**Comment by iaomw** [comment]
I saw the 4k option, but I want to play on MacBook Pro at 2880*1800.
