### ISSUE TITLE
Can recent mtk soc like 8100 enable low-latency decoding？

### ISSUE THREAD

**Issue by Xiar4119** [moonlight-stream/moonlight-android#1060]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by cgutman** [comment]
I'm not sure. If it's running Android 11 or later, [FEATURE_LowLatency](https://developer.android.com/reference/kotlin/android/media/MediaCodecInfo.CodecCapabilities#feature_lowlatency) may be supported. It will depend on the device.

**Comment by Xiar4119** [comment]
Never mind, I just bought another mobile phone with snapdragon 870 and it works well
