### ISSUE TITLE
how to connect moonlightstreaming from pc to laptop

### ISSUE THREAD

**Issue by hitmanraza** [moonlight-stream/moonlight-android#107]
plz tell me how to connect moonlight streaming from pc to laptop. which software should install on laptop.
my pc is perfectly working with android moonlight streaming. but how to connect with other pc on same network. which software required on client pc.???

**Comment by mrb113** [comment]
You should use Moonlight PC
https://github.com/moonlight-stream/moonlight-pc/releases
