### ISSUE TITLE
Connectivity Issues with Dual SIM Enabled Device

### ISSUE THREAD

**Issue by awitte585** [moonlight-stream/moonlight-android#1070]
On the Galaxy S22 Ultra, and presumably other dual SIM enabled Galaxy devices, the app seems to think the host PC is offline when dual SIM is enabled and connected over mobile data. After disabling one of the SIM cards and reloading the app or changing to wi-fi (either on or off the same network as the host PC) there's no issues discovering or connecting to the host PC in the app. It didn't seem to matter which SIM was set to primary for mobile data and each SIM is from a different carrier. So far there hasn't been any other app on the device, game streaming or otherwise, that exhibit this behavior.

**Other Moonlight clients**
- Did not seem to happen with the Moonlight app using a Pixel device with dual SIM dual standby enabled using mobile data, so it could be something specifically related to Samsung Galaxy devices. 

**Device details (please complete the following information)**
 - Android version: Android 12
 - One UI version: 4.1
 - Android Security patch level: May 1, 2022
 - Device model: Samsung Galaxy S22 Ultra (North American carrier unlocked model)
 - Baseband version: S908U1UEU2AVDC
 - Build number: SP1A.210812.016.S908U1UEU2AVDC

**Server PC details (please complete the following information)**
 - OS: Windows 10 Pro 21H2
 - RTX Experience version: 1.3.0.5
 - Nvidia GPU driver: 512.59
 - Antivirus and firewall software: Windows Defender and Windows Firewall

**Comment by cgutman** [comment]
This sounds strange. Are you able to get `logcat` logs from your phone while Moonlight is trying to connect?

**Comment by awitte585** [comment]
I agree, it's a strange one. One thing I forgot to mention, if I load the app with both SIMs enabled and toggle airplane mode on and off, it will detect the host and allow you to connect for about 20 seconds or so before it disconnects and shows offline again. I can definitely try to capture a log for you. Is there an email address I can send it to? I prefer not to post it here.

**Comment by cgutman** [comment]
Sure, you can use cameron@moonlight-stream.org

**Comment by cgutman** [comment]
We chatted over email and I made some improvements in v10.1 to help address this. Ultimately, it does seem like an OS bug (even Android's own captive portal detection had connections timing out after 10 seconds).

I think we've covered this the best we can given the OS behavior here.
