### ISSUE TITLE
Moonlight stopped working all of a sudden

### ISSUE THREAD

**Issue by NickHatBoecker** [moonlight-stream/moonlight-android#1071]
**Describe the bug**

All of a sudden Moonlight stopped working for me with my gamepad. Only the left joystick seems to be struck. For example in Fall guys, which I played for weeks via Moonlight, I can't walk anymore. All other buttons/joysticks are working fine.

When opening the Moonlight app, without starting a game or connecting to a computer, the left joystick is acting weird. For example in the game list view, when pushing the joystick to the right, it's like I clicked on a specific game in the list. So I get the dialog if I want to hide this game, show details etc. instead of just selecting the next game to the right. Left joystick works just fine in any other App than Moonlight.

Tried to reinstall moonlight, restarted console and PC. Nothing worked. Everything was working fine a few days ago.

In Fall guys for example I can see that, as soon as I move the left joystick, all mouse controls are shown. So I guess moonlight thinks it's a mouse? And as soon as I press a gamepad button, the gamepad controls are shown again.

**Steps to reproduce**
Just start the app and try to use the left joystick. It can't be used to select anything.

**Affected games**
- Tried with Fall guys via Steam (when in a match every button works, except the left joystick, so I can't walk in game)
- but the problem already exists without starting any game

**Moonlight settings (please complete the following information)**
- Reverted Settings and the problem still occurs

**Gamepad-related issues (please complete if problem is gamepad-related)**
- Do you have any gamepads connected to your host PC directly? **No**
- If gamepad input is not working, does it work if you use Moonlight's on-screen controls? **Yes**
- Does the problem still remain if you stream the desktop and use https://html5gamepad.com to test your gamepad?
    - html5gamepad.com **Works**
    - but same problem with streaming the desktop
    - also not working in Moonlight app without connecting to a PC
- also in all other apps the left joysticks works (for example Emulators like Dolphin or Citra)

**Device details (please complete the following information)**
 - Android version: Android 10
 - Device model: AYN Odin Base
 - Moonlight Version 10

**Server PC details (please complete the following information)**
 - OS: Windows 10
 - GeForce Experience version: 3.25.1.27
 - Nvidia GPU driver: NVIDIA GeForce RTX 2060, 512.77
 - Antivirus and firewall software: Nothing (Windows Firewall deactivated)

**Comment by cgutman** [comment]
That's quite odd. Moonlight doesn't have any special controller handling for UI navigation. It just uses Android's built-in support for navigating with a controller or remote. We haven't released a new build of Moonlight for Android since March, so it wouldn't be a new change on our side.

The behavior you describe sounds like there's some kind of special gamepad profile that's getting loaded for Moonlight specifically. Is there a gamepad mapper/profile app installed on your AYN Odin (maybe installed by default)? If that was updated with new profiles, it could explain why it broke without any changes from Moonlight.

**Comment by NickHatBoecker** [comment]
omg....I can't believe it. It was the "Floating icon" setting. I used the key mapper feature in an android game and thought it would be only for this specific app. That seemed to interfere with Moonlight. Thanks for bringing up the "mapper" topic!!
