### ISSUE TITLE
Adjust stick deadzones - Playing with non-Xbox/Dualshock controllers might add some unintended little dead zones 

### ISSUE THREAD

**Issue by lyndonguitar** [moonlight-stream/moonlight-android#1075]
**Is your feature request related to a problem? Please describe.**
Playing with non-Xbox controllers might cause some unintended dead zones which hampers the experience in shooters. I have a Razer Kishi with me and using it on my Android Phone for Moonlight streaming. However, I noticed that when using Moonlight, there is an added bit of unwanted deadzone (very slight but very impactful in shooter games). This "added deadzone" does not exist when using gamepad tester on android, nor using an alternative streaming option like Steam Remote Play or Parsec

**How to reproduce the Issue**
1. Use Razer Kishi on Client
2. Connect to Server via Moonlight
3. Use a gamepad tester. 
4. Move the analog stick ever so slightly, the Server won't register the input until passing a certain hardcoded deadzone.

To confirm that this is an issue
1. Use Razer Kishi on Client
2. Connect to Server via Steam Remote play or alternative (e.g. Parsec)
3. Use a gamepad tester. 
4. Move the analog stick ever so slightly, the server is recognizing the little movements, without any added deadzone.
^You can also skip step 2. and just run a tester app native on the Client.

This isn't a problem with Xbox or Dualshock controllers as I guess the hardcoded Deadzones are well calibrated and configured for these controller types, whereas for controllers like the Razer Kishi, it isn't.

**Describe the solution you'd like**
Allow us to adjust the deadzones. A bit of google searching has led me [into this code which If I understand correctly, hardcodes a 7% deadzone for the controllers.](https://github.com/moonlight-stream/moonlight-android/blob/master/app/src/main/java/com/limelight/binding/input/ControllerHandler.java#L67)  I hope we can adjust this to a desired value via the client(e.g. 0% to 25%), to improve responsiveness or eliminate drifting.

**Describe alternatives you've considered**
Use Steam Remote Play or Parsec

**Unrelated Additional Request**
[An option to simulate Home or PS button](https://github.com/moonlight-stream/moonlight-android/issues/854)

**Comment by vqsxd** [comment]
Please remove this 7% deadzone from iOS Moonlight because its a crazy big deal on here and I can't find a workaround
