### ISSUE TITLE
Feature Request: Option to prevent Android from utilizing controller home button during stream

### ISSUE THREAD

**Issue by teconmoon** [moonlight-stream/moonlight-android#1076]
**Is your feature request related to a problem? Please describe.**
I'm transitioning from a Windows Thin Client to a Shield TV Pro (2019) for game streaming through Moonlight, as my old Windows Thin Client isn't powerful enough for 4K. I normally use the home button for multiple server-side actions, such as overlays and other server-side hotkeys. Currently with the Shield TV Pro, when pressing the home button on my controller, Android goes back to the home screen instead of passing through the home button to the server.

**Describe the solution you'd like**
When I press the home button on my controller during a stream, I would like that to be passed through to the server instead of going back to the client's home menu.

**Describe alternatives you've considered**
Enabling the option to **Override native Xbox gamepad support** does allow compatible controllers to pass through the home button, with the caveat that the stream can no longer be exited with the LB + RB + Start + Select hotkey, and once the stream is over, the controller is no longer usable by the OS until it is unplugged and plugged back in. (In my case, using a DS3 controller with an old USB XInput adapter to achieve rumble support)

I'm sure I can re-design a lot of my server-side functions to use alternative hotkeys, I would just rather avoid doing so if at all possible.

**Additional context**
I'm not sure if this issue is unique to a specific version of Android, or the NVIDIA Shield specifically. I don't recall this occurring the last time I tested using the app directly from a Sony Google TV, but I am not currently able to test that scenario.

**Comment by cgutman** [comment]
Unfortunately it is not possible for applications to capture the home button. Android prohibits that since it could be used maliciously.
