### ISSUE TITLE
Android Doesnt work with last Geforce Experience BETA error 536

### ISSUE THREAD

**Issue by marcspc** [moonlight-stream/moonlight-android#108]
android client updated from google play

GeForce_Experience_Beta_v2.7.3.0

I was testing new gamestream http://www.nvidia.es/object/gfe-beta-es.html and can't use moonlight anymore

**Comment by ZILosoft** [comment]
same issue..

**Comment by tomekszy** [comment]
I have the same problem, but I use normal graphics driver, not beta. The full error information is "Cannot launch the game since server display not support - error 536". Please advise

**Comment by khades** [comment]
i got it with custon resolution like 1024x600 enabled, check if pc can run resolution you're trying launch moonlight with
