### ISSUE TITLE
What the relation with SunshineStream ?

### ISSUE THREAD

**Issue by licaon-kter** [moonlight-stream/moonlight-android#1080]
ref: https://github.com/SunshineStream

Eg. For F-Droid we could drop the NonFreeNet AntiFeature if one could just connect to a hosted SunshineStream server.

Also we could explain that, besides nVidia proprietary stuff, this connects to a FOSS server too.

**Comment by cgutman** [comment]
Yep, Moonlight supports connecting to Sunshine, in addition to GeForce Experience. If that's sufficient to drop the NonFreeNet anti-feature, that sounds great to me.
