### ISSUE TITLE
Ok to stream pc but game streaming dont work 

### ISSUE THREAD

**Issue by nattyduber** [moonlight-stream/moonlight-android#1085]
Hi

Before i used Moonlight streaming on a desktop with i7 6700+gtx1080 and all work fine
Now im on a desktop Lenovo légion 5 with ryzen 5 and rtx 3070
And i have paired m'y laptop on Android TV or m'y phone
Internet hosting tool Saïd that all are ok

But when i want to connect to m'y pc .. rtsp etc load , no problème .. but when i want to launch a game there are this screen..

![Screenshot_20220614-234348_Moonlight](https://user-images.githubusercontent.com/66644184/173694432-90d704f5-2c11-4e47-94d9-56d9bfbf5f59.jpg)

I use fiber connections.. 2gb connections..
With or without allm or hardware accelation.. its the same problèm.. they Say ''poor connections please have a better connection'' ..

How to solve it!?
.
On a Galaxy z fold 3 or NVIDIA Shield TV 2019

Thanks

**Comment by nattyduber** [comment]
Up

**Comment by nattyduber** [comment]
Any reply?

**Comment by cgutman** [comment]
Are your devices connected over 5 GHz WiFi? What resolution, frame rate, and bitrate do you have Moonlight set to use?

**Comment by nattyduber** [comment]
I have wifi 6e or wifi 6 (on m'y légion 5 or on m'y z fold 3)
Résolution : native (for fold) or 1080p
120 fps. All m'y displays are 120fps..smartphone or légion or Android tv ..
And i have never change bitrate .. because i have a 2gbs connexion in m'y box..

**Comment by cgutman** [comment]
When you mention 2Gbps, are you referring to the speed of your Internet connection or your WiFi link speed?

Are you streaming while connected the same network as your laptop or are you trying to stream over the Internet from some other location?

**Comment by nattyduber** [comment]
2gps its the speed of m'y internet connexion ..
Stream over the internet or on the same network = same problem

**Comment by nattyduber** [comment]
I'have an other pc for example with a GTX 1080 which is ok to stream but since i have but this laptop i cant stream via Moonlight.. but m'y first pc (with GTX 1080) is deleted from moonlight

**Comment by nattyduber** [comment]
Any news ?
Same problèm on ethernet network...

**Comment by cgutman** [comment]
Both are connected to the same Ethernet switch on the same network?

**Comment by nattyduber** [comment]
Yes same ..

**Comment by nattyduber** [comment]
Always same problèm ..

**Comment by nattyduber** [comment]
Hey cgutman , any solution?

**Comment by cgutman** [comment]
Does your new PC have a 2.5 Gb Ethernet adapter installed? If so, is it connected at 2.5Gb?

**Comment by nattyduber** [comment]
I use wifi, no ethernet ^^
And its légion 5 15ac h6h so i dont know if it have 2.5gb ethernet adaptater preinstalled

**Comment by nattyduber** [comment]
For information , if i stream a video via VLC its ok, it dont freeze..

It freeze only with games..

**Comment by cgutman** [comment]
Can you check that you have "hardware accelerated GPU scheduling" disabled on your host PC? That can cause the video to freeze when streaming.

**Comment by nattyduber** [comment]
Already disabled. Nothing change

**Comment by nattyduber** [comment]
Retested now without hardware accelrator.. nothing change...

**Comment by cgutman** [comment]
You mentioned that you tried streaming to a laptop. Can you get the logs from the Moonlight PC client? That will have much more detail than Android can provide.

**Comment by nattyduber** [comment]
How Can i create log ? ^^

**Comment by cgutman** [comment]
- On Windows, `Moonlight-###.log` files can be found in `%TEMP%`. Simply type that into the File Explorer path field to navigate there.
- On macOS, `Moonlight-###.log` files can be found in `/tmp`. In Finder, press Cmd+Shift+G, then type `/tmp` to navigate there.
- On Linux with the Flatpak, logs print to the terminal when running with the command: `flatpak run com.moonlight_stream.Moonlight`
- On Linux with the Snap, logs print to the terminal when running with the command: `moonlight`

**Comment by nattyduber** [comment]
I'm sorry, i dont found any logfile , 
i dont have moonlight client, i just want to stream from my laptop, to an android tv (nvidia shield) or to my phone (z fold 3 from samsung)
on my laptop there are only internet hosting tool ^^

**Comment by nattyduber** [comment]
Any Idea ?

**Comment by nattyduber** [comment]
Please ?😁

**Comment by nattyduber** [comment]
So?

**Comment by cgutman** [comment]
I'm really not sure. I can't say why your old PC worked and your new one doesn't. It seems likely to be hardware or drivers because the same GeForce Experience version works on your other PC.

You'll probably need to try eliminating factors (try a different WiFi network, different WiFi adapter, Ethernet, etc).

This issue tracker isn't really designed for technical support. If you need further help, I suggest following up on the Discord server where there are many volunteers helping the community.
