### ISSUE TITLE
Mouse pointer not hidden on Fire TV/Firestick

### ISSUE THREAD

**Issue by Sidd065** [moonlight-stream/moonlight-android#1088]
The default mouse pointer (a large circle) is not hidden and looks like this when streaming to a Fire TV with a physical mouse connected.

![issue](https://user-images.githubusercontent.com/78248734/175661547-b02cd108-c44c-45f6-a1be-ff517029df18.jpg)

This can reproduced by connecting a mouse via a micro USB Y Splitter, Bluetooth or using an app called "Mouse Toggle on FireStick" that lets you use your remote as a mouse.

I'm using a Fire Stick Gen 2 but afaik the issue should affect every firestick.

The documentation says it can be customized but I'm not sure to what extent https://developer.amazon.com/docs/fire-tv/customize-mouse-pointer.html
According to an xda developers thread, an app called Wukong TV Remote is able to change the pointer to a small white dot so its probably possible to hide it.

**Comment by cgutman** [comment]
> I'm using a Fire Stick Gen 2 but afaik the issue should affect every firestick.

Just to confirm, you're talking about [this device](https://developer.amazon.com/docs/fire-tv/device-specifications-fire-tv-streaming-media-player.html?v=ftvstickgen2)?

If so, I think the trouble is that it's running Fire OS 5. Fire OS 6 contains Android Nougat's support for custom mouse cursors and Fire OS 7 supports Android Oreo's support for pointer capture. Moonlight can use both of those techniques to hide the cursor on more modern Fire TV devices.

> According to an xda developers thread, an app called Wukong TV Remote is able to change the pointer to a small white dot so its probably possible to hide it.

I wonder if they are using private APIs to do so. Do you have a link to the thread?

**Comment by Sidd065** [comment]
> If so, I think the trouble is that it's running Fire OS 5. Fire OS 6 contains Android Nougat's support for custom mouse cursors and Fire OS 7 supports Android Oreo's support for pointer capture. Moonlight can use both of those techniques to hide the cursor on more modern Fire TV devices (basically anything after the Fire TV Stick Gen 2).

Yep you nailed it. I'm now using a firestick lite and the pointer is hidden.
> I wonder if they are using private APIs to do so. Do you have a link to the thread?

Sorry I can't find that thread now, all the search results are about people trying the emulate a mouse or using a USB mouse
