### ISSUE TITLE
Devices are not pairing with PC

### ISSUE THREAD

**Issue by shudack** [moonlight-stream/moonlight-android#1092]
Hello, I can't pair any android devices to Moonlight Android (Nvidia Shield Pro and Galaxy S9+).
After I typed the pin, appear the toaster message with the "PC not paired". I tried in Nvidia Shield Pro and Galaxy S9+ without success.
I recorded screen of my phone (Galaxy S9+) to reproduce what happens.

https://imgur.com/a/mYU3I7P

GeForce Experience: 3.25.1.27
PC: Win10 21H2
Android 10: Galaxy S9+
Android 11: Nvidia Shield Pro

**Comment by cgutman** [comment]
Probably a duplicate of https://github.com/moonlight-stream/nvidia-gamestream-issues/issues/30

**Comment by shudack** [comment]
Fixed with workaround: https://github.com/moonlight-stream/nvidia-gamestream-issues/issues/30#issuecomment-1172924002

Thank you!
