### ISSUE TITLE
30fps Streaming and Enabling Frame Pacing Causes Significant Input Latency

### ISSUE THREAD

**Issue by Nonary** [moonlight-stream/moonlight-android#1096]
**Describe the bug**
When setting the android version of Moonlight to 30fps and applying **any form** of frame pacing, it causes a significant increase in input latency, often not even showing up in the performance stats. 

**Steps to reproduce**
Play any game that is locked to 30fps
Set Moonlight to stream at 30fps
Apply any other frame pacing option other than "Prefer Lowest Latency"
Play for a few minutes, often it starts off fine and gets progressively worse.
Observe **significant** impact, of 40-100ms of increased input latency.

**Other Moonlight clients**
I have tested this on Mac, PC and IOS Clients... they do not have this issue. 
It is only the android client of Moonlight that appears to cause the massive amounts of input lag from what I have seen.

**Moonlight settings (please complete the following information)**
- Have any settings been adjusted from defaults? I've used default settings, does not matter.
- If so, which settings have been changed? N/A
- Does the problem still occur after reverting settings back to default? N/A

**Device details (please complete the following information)**
 - Android version:  Android 11
 - Device model: NVIDIA SHIELD PRO 2019

**Server PC details (please complete the following information)**
 - OS: Windows 10
 - GeForce Experience version: 3.25.1.27
 - Nvidia GPU driver: 516.59
 - Antivirus and firewall software: Windows Defender and Windows Firewall

**Additional context**
I can run 60fps streams without issues, so it's not connection related. Even without frame pacing 60fps streams run much better than the 30fps streams.

In general, it appears 30fps streaming on the Android Client has a lot of frame pacing issues compared to other clients; tested with my Kindle Fire and NVIDIA Shield. [Turning off frame pacing yields much better latency, but it has much more judder compared to other clients]

Obviously applying any form of VSYNC will add some latency, usually one frame (33ms in the case of 30fps) but this appears to be causing 2 or 3 frames of input lag. This issue also happens on Sunshine, so I suspect it is more client sided related than host related.

Also, when using Native GameStream the performance on 30fps is much better with very little frame pacing issues, with some hiccups here and there. So, I suspect it is using some type of vsync that is effective without much input lag, with some flaws, but not sure.

If I had to guess, perhaps there is something weird going on specifically when streaming at 30fps that causes the vsync to be much more aggressive than typical. Meaning, maybe its not the frame pacing code that is causing the issue, but the frame handling instead? This would explain why the latency is fine with lowest latency but overall the judder is significantly worse than typical

**Comment by cgutman** [comment]
Hmm, the pacing options are really quite different. When operating well below the display refresh rate, the pacing logic for "Prefer lowest latency", "Balanced with FPS limit", and "Prefer smoothest video" is more or less identical ("Balanced with FPS limit" and "Prefer smoothest video" are literally identical in those conditions). I don't think it's the pacing logic itself causing this.

The only place where "Prefer lowest latency" is special is in the selection of refresh rates. When using other pacing modes, Moonlight will always use a refresh rate that is an exact match with your stream frame rate if one exists. However, in lowest latency mode, it will pick the highest refresh rate at the given resolution.

I wonder if your TV exposes a 30 Hz mode that is causing Moonlight to perform poorly for some reason. Can you see if your TV is switching to a sub-60 Hz mode when you start streaming under those conditions?

**Comment by Nonary** [comment]
> Hmm, the pacing options are really quite different. When operating well below the display refresh rate, the pacing logic for "Prefer lowest latency", "Balanced with FPS limit", and "Prefer smoothest video" is more or less identical ("Balanced with FPS limit" and "Prefer smoothest video" are literally identical in those conditions). I don't think it's the pacing logic itself causing this.
> 
> The only place where "Prefer lowest latency" is special is in the selection of refresh rates. When using other pacing modes, Moonlight will always use a refresh rate that is an exact match with your stream frame rate if one exists. However, in lowest latency mode, it will pick the highest refresh rate at the given resolution.
> 
> I wonder if your TV exposes a 30 Hz mode that is causing Moonlight to perform poorly for some reason. Can you see if your TV is switching to a sub-60 Hz mode when you start streaming under those conditions?

It is going to 30hz, there is a feature called match frame rate on the shield and I don't know how to forcefully turn it off. Apparently applications can cause the TV to change the refresh rate, but it has to be coded into the application it doesn't just work on its own. So I suppose Moonlight is doing something to cause that, not sure.

 I've confirmed that the native  game stream does not change the refresh rate.

**Comment by Nonary** [comment]
Based off my observations I don't think its the frame pacing logic either. I just don't know why that even when using the lowest latency, there is much worse judder than other clients that are also running at 60hz (with 30fps). The frame pacing is definitely doing its job, there isn't much judder, but the input lag is very high.... perhaps because it has to work extra hard for some reason on 30fps specifically on the android client? 

To rule my display out, I used a usb-c to HDMI adapter from my iPad and despite it being in 4:3 there wasn't any problems with judder with frame pacing at 30fps like it was on my shield.

**Comment by Nonary** [comment]
Interestingly enough, if I do use Sunshine it causes the stream incoming rate to match my games frame rate. So even if I pick 60fps on Moonlight, it will lock at 30fps because my game is locked at 30. And the frame pacing is almost perfect when it is doing this, about as good as native gamestream (with a few hiccups). 

The difference in this case is the display is still running at 60hz because Moonlight is configured for 60fps and not 30fps. I am not sure if frame pacing is taking effect in this scenario, since it usually runs near perfect even with frame pacing disabled.

**Comment by Nonary** [comment]
So did more testing with Sunshine, and it does not really observe this issue. So I am not really sure if this is a bug per-se with the Android Client directly... up to you to consider that. But my theory is that because Sunshine has the ability to match the streaming frame rate with the rendering frame rate, it allows Moonlight to handle the frame pacing much better.

Even when doing 30fps stream and frame pacing set to smoothest, it does not add that much latency compared to GFE. 

When it comes to streaming with GFE, for some reason even when games run at 30fps it tends to stream them at 58-61fps instead of a perfect 60, which causes judder no matter what unless you set the stream to 30fps. Sunshine doesn't seem to have this issue, it will match the frame rate of the game exactly to the stream rate. (Which implies that it might support variable refresh rate but don't have any displays capable of doing that just yet at least for streaming)

I can't really explain why it works so much better on other clients, so there has to be something unique just with Android that makes it stick out more, perhaps it forcing 30hz is probably the main cause, but with Sunshine it still does that and doesn't run into massive input latency.

**Comment by Nonary** [comment]
Ok, so I believe this will be my final update. Your suspicion is most likely accurate, the issue really only happens when my TV get forced to 30hz mode. If I run the TV in modes that do not have official supported options (like 1080p 30hz), it will not forcefully change my TV to 30hz and works perfectly.

So if there was a way to tell Moonlight not to try to force my display to the same HZ, it would basically fix my problem.

**Comment by Nonary** [comment]
@cgutman I have fixed this issue on my own by adding a new option in configuration to disable changing of refresh rate. I was just wondering what sort of polish do I need to do in order to open a pull request for it I guess?

**Comment by cgutman** [comment]
Fixed by #1099
