### ISSUE TITLE
The cursor position is inaccurate when it points to the position you want to type

### ISSUE THREAD

**Issue by ericsyj** [moonlight-stream/moonlight-android#1097]
When I want to edit a position, I have to move the mouse pointer slightly to the right of it and then click the mouse to move the cursor to that position correctly. This problem occurs on both Android and IOS clients.

**Comment by cgutman** [comment]
Are you referring to the I-beam cursor?

**Comment by ericsyj** [comment]
> 

yep

**Comment by ericsyj** [comment]
> Are you referring to the I-beam cursor?

yep

**Comment by peerobo** [comment]
https://www.nvidia.com/en-us/geforce/forums/shield-tv/9/433782/cursor-alignment-issues-in-geforce-experience-sinc/3117651/
It was a known issue of gamestream.

**Comment by ericsyj** [comment]
@peerobo so this issue has existed for more than a year, when will it be repaired? I don't seem to see any new progress in this link.

**Comment by peerobo** [comment]
> @peerobo so this issue has existed for more than a year, when will it be repaired? I don't seem to see any new progress in this link.

We can't do anything because gamestream is maintained by nVidia.

**Comment by ericsyj** [comment]
it's already been fixed.
