### ISSUE TITLE
Motorola Xoom

### ISSUE THREAD

**Issue by neukyhm** [moonlight-stream/moonlight-android#110]
The app works fine on iOS but it is not compatible with Motorola Xoom, which is something I don't understand since it has nvidia graphics.

**Comment by cgutman** [comment]
Is your Xoom running Android 4.1?

**Comment by neukyhm** [comment]
Nope, It's running Android 4.0.4, which is the most updated official version for this tablet.

**Comment by cgutman** [comment]
Android 4.1 is required for Moonlight to work. Is your Xoom a carrier variant? Motorola published an official 4.1.2 update for Xoom.

https://motorola-global-portal.custhelp.com/app/answers/detail/a_id/90636

**Comment by neukyhm** [comment]
My device is a Motorola Xoom Wifi, and I can't update to that official version because it seems that only US users can. F**k. xd.
