### ISSUE TITLE
Xbox360 controller Wired/Wireless not recognized on S6 edge

### ISSUE THREAD

**Issue by DeXtmL** [moonlight-stream/moonlight-android#111]
Basically the GUIDE button flashes constantly when connected to phone(all 4 LEDs flash. Setup: wired version: OTG to phone;  Wireless version: connect receiver to phone).
No game recognizes any gamepad at all.

Phone: Samsung Galaxy S6 edge non-root

**Comment by xila76** [comment]
same issue with a classical "no-name" cheap USB gamepad with same phone... (same on Nexus 7 too)

**Comment by cgutman** [comment]
Fixed by built-in Xbox controller driver.

**Comment by nejcob** [comment]
@cgutman How do you install those drivers exactly? Googled myself to death. I want to use my xbox 360 wired controller with a usb otg adapter on a samsung galaxy s6. 
Hope you can help me.

**Comment by cgutman** [comment]
The drivers are included in Moonlight and only work while Moonlight is streaming.
