### ISSUE TITLE
Unable to connect with none default port range on host

### ISSUE THREAD

**Issue by wezel** [moonlight-stream/moonlight-android#1115]
**Describe the bug**
Android app can't connect with a linux sunshine host when the port range is changed within sunshine.
- Host is not detected.
- Directly connecting to the host by giving ip and port does not work.
- Changing the range of a previously linked host makes the host inaccessible.

I did run a test without the default port range and the app did connect fine to the host machine.

**Steps to reproduce**
- Have a host system with linux and sunshine installed.
- change the port range to some other arbitrary number.
- try to connect to the host by giving the ip and port.

**Affected games**
Not applicable since it's impossible to make a connection 

**Other Moonlight clients**
- The issue does not exist on moonlight for pc. My moonlight on pc is able to directly connect to the host when I give it the IP and new port. (w.x.y.z:port)

**Moonlight settings (please complete the following information)**
Everything on the client end is default.
Sunshine host has the port range changed as mentioned before.

**Device details (please complete the following information)**
 - Android version:  10
 - Device model: Pixel (1)

**Server PC details (please complete the following information)**
 - OS: Pop!_OS
 - Sunshine: v0.14.0
 - AMD gpu.

**Comment by cgutman** [comment]
Yeah this is expected. Non-default port ranges are only currently supported in the Moonlight Qt client.

**Comment by wezel** [comment]
Ah okay thanks. In that case sorry for marking it as a bug. Are there any plans to add it to the android version in the near future?

**Comment by qinchanggen** [comment]
就是说moonlight Android 无法通过改变ip和端口号进行非默认的端口连接吗
