### ISSUE TITLE
Activity memory leak caused by anonymous threads

### ISSUE THREAD

**Issue by cuixiaoyiyi** [moonlight-stream/moonlight-android#1116]
An anonymous inner class will hold a reference to the this pointer of the outer class and will not be released until the thread ends.

[This](https://github.com/moonlight-stream/moonlight-android/blob/master/app/src/main/java/com/limelight/PcView.java#L396) and [this](https://github.com/moonlight-stream/moonlight-android/blob/master/app/src/main/java/com/limelight/Game.java#L1689) will hold the Activity and prevent its timely release.

**Comment by cgutman** [comment]
Both of those are fine because they are short-lived threads
