### ISSUE TITLE
can't see mouse pointer on android phone

### ISSUE THREAD

**Issue by pontetraje** [moonlight-stream/moonlight-android#112]
when I stream mi desktop on mobile and control it with the touch screen or the game pad, i cant see the pointer on desktop, in some games neither, and in others i see 2 pointers, the windows one, and the game stiled one.. how can i fix that? i have the rooted version on a  rooted meizu mx5, maybe there is some option that i cant found.. tell me please, and thx for the work!

**Comment by mrb113** [comment]
This is an issue in Windows, not Moonlight.
