### ISSUE TITLE
HEVC does not work on MITV since version 10.3

### ISSUE THREAD

**Issue by loseheaven** [moonlight-stream/moonlight-android#1122]
**Describe the bug**
I have always force used HEVC encoding to reduce the amount of data transmission, but after upgrading the moonlight client in the past two days, I found that the client was stuck at the first frame of the connection and no longer refreshed. I tried various versions and found that it started from version 10.3, and it was normal when 10.2

**Steps to reproduce**
Set to force the use of hevc

**Other Moonlight clients**
- Does the issue occur when using Moonlight on PC or iOS?
No，It's normal on my android phone

**Moonlight settings (please complete the following information)**
- Have any settings been adjusted from defaults?
- If so, which settings have been changed?
Set to force the use of hevc
- Does the problem still occur after reverting settings back to default?
No, it can be work if not use hevc

**Device details (please complete the following information)**
 - Android version:  Android 6.0.1
 - Device model: MITV4-ANSM0

**Server PC details (please complete the following information)**
 - OS:  Windows 10 1909
 - GeForce Experience version:  3.25.1.27
 - Nvidia GPU driver: 472.12
 - Antivirus and firewall software:  360 Security Guard

**Comment by cgutman** [comment]
Are you able to get logcat logs from your device when attempting to stream?

**Comment by loseheaven** [comment]
> Are you able to get logcat logs from your device when attempting to stream?

[logcat.txt](https://github.com/moonlight-stream/moonlight-android/files/9487035/logcat.txt)

![hevc](https://user-images.githubusercontent.com/1579140/188369557-f346842f-df02-4653-98fd-4b0534bb2914.jpg)
