### ISSUE TITLE
Touch the screen to move the mouse

### ISSUE THREAD

**Issue by hhyacg** [moonlight-stream/moonlight-android#1129]
In the new version, there is a pause when moving the mouse with the touch screen.The is Bug？

**Comment by cgutman** [comment]
Can you describe the issue in more detail (and possibly provide a video)? I do not see a pause when moving the mouse with the touchscreen when I test it here.

**Comment by hhyacg** [comment]
Sorry, I found out that in the new version, the streaming screen is 16:9 (1920×1080), but the resolution of the display device is 2400×1080, so the black screen parts on both sides cannot be touched.

**Comment by hhyacg** [comment]
> Can you describe the issue in more detail (and possibly provide a video)? I do not see a pause when moving the mouse with the touchscreen when I test it here.

Sorry, I found out that in the new version, the streaming screen is 16:9 (1920×1080), but the resolution of the display device is 2400×1080, so the black screen parts on both sides cannot be touched.

**Comment by hhyacg** [comment]
> Can you describe the issue in more detail (and possibly provide a video)? I do not see a pause when moving the mouse with the touchscreen when I test it here.

Click or swipe from the black part, the mouse cursor does not move, but swiping on the display part can pass through the black part without interrupting the swipe operation.

**Comment by cgutman** [comment]
Thanks for the info. Are you using the on-screen gamepad too?

**Comment by hhyacg** [comment]
> 

No, I don't use an on-screen gamepad.  I use streaming to generally play text adventure games, sorry

**Comment by cgutman** [comment]
Please try this build and let me know if it's working as expected now: https://drive.google.com/file/d/11358WoOLVtcvpedVkKPnSoVBJeULSk3k/view?usp=sharing

**Comment by hhyacg** [comment]
> Please try this build and let me know if it's working as expected now: https://drive.google.com/file/d/11358WoOLVtcvpedVkKPnSoVBJeULSk3k/view?usp=sharing

Thanks for the rework, but sorry, I have to wait until I get home from work today before I can test it for you.

**Comment by hhyacg** [comment]
> Please try this build and let me know if it's working as expected now: https://drive.google.com/file/d/11358WoOLVtcvpedVkKPnSoVBJeULSk3k/view?usp=sharing

Good！he can operate on the black part.
