### ISSUE TITLE
1.8.3 crashes when streaming should start on old devices, 1.8.1 fine

### ISSUE THREAD

**Issue by geekycow** [moonlight-stream/moonlight-android#1132]
Moonlight Root 1.8.3 crashes when streaming would normally start.  1.8.1 works fine.

Wikipad[Wikipad](https://en.wikipedia.org/wiki/Gamevice#Wikipad)  WPT005  Android 4.2.2  kernel 3.1.10-g653c2c7 

PS I know this is a terribly old Android version and hardware but this a classic, perfect platform for Moonlight use, being a handheld tablet with built in XBox style controls in the style of Steam Deck / Switch.

**Comment by geekycow** [comment]
1280 x 800
Nvidia Tegra 3
1Gb RAM

**Comment by geekycow** [comment]
This is still on GFE 3.25.1.27.  Windows 10.

**Comment by MKxiao233** [comment]
Me too have this problem at my old tablet. It worked fine until this update. 
Samsung Galaxy Note 8.0
Android 4.4.2 kernel3.0.31-3300977
1280 x 800
Exynos 4412
2Gb RAM

**Comment by MKxiao233** [comment]
> Me too have this problem at my old tablet. It worked fine until this update. Samsung Galaxy Note 8.0 Android 4.4.2 kernel3.0.31-3300977 1280 x 800 Exynos 4412 2Gb RAM

btw using v10.8.4

**Comment by cgutman** [comment]
Can you provide logcat logs from your device?

**Comment by geekycow** [comment]
Sure.  Attached.  Hopefully I've appropriately redacted sensitive info.

The point where the crash happens is at time 01:38 (I timed my button presses to make it easier to find the relevant points in the logs.)

Whether or not you're able to fix this:  thank you so much for your work on this to date, Moonlight on Android has enabled me, and I'm sure many others too, a fab Steam-Deck-like gaming experience for years on what's now ancient hardware.  I can't possibly complain!

[device_info.txt](https://github.com/moonlight-stream/moonlight-android/files/9691460/device_info.txt)
[logcat-moonlight-1.8.4.log](https://github.com/moonlight-stream/moonlight-android/files/9691461/logcat-moonlight-1.8.4.log)

**Comment by cgutman** [comment]
It seems to be due to a bug in the compiler in the Android Gradle Plugin version 7.3.0. I was able to reproduce it in the emulator and reverting to 7.2.2 fixes it.

**Comment by cgutman** [comment]
Here is a fixed build that should work for you: https://drive.google.com/file/d/1SnYfVORE1uIG1PZCX46x-i8UOQyHthNZ/view?usp=sharing
