### ISSUE TITLE
BT.709 and full color range by default

### ISSUE THREAD

**Issue by skbeh** [moonlight-stream/moonlight-android#1138]
Nowadays, almost all clients are using BT.709 and full color range, and the network usage should be acceptable.
Maybe compatibility of color range was a thing when the library was created, but now every modern TV is capable to show contents with full RGB range.
I think it is time to change the defaults.
#https://github.com/moonlight-stream/moonlight-common-c/issues/71

**Comment by cgutman** [comment]
I decided to default to Rec 709, but leave color range at limited.

Unlike Rec 709 vs Rec 601, full range video content is in the minority compared to limited range content, so there's a good chance that decoders aren't well tested for this type of content. These types of decoder compatibility issues seem to show up constantly on Android devices, so I don't want to push our luck and risk completely breaking certain decoders.

**Comment by skbeh** [comment]
@cgutman Maybe it would be better to add an option to let the users to choose whether to use full range or limited range.

**Comment by cgutman** [comment]
Added in a6c8db6c2cbc3517e2a3163850c2230bde68057b
