### ISSUE TITLE
Steam controller.

### ISSUE THREAD

**Issue by olijf** [moonlight-stream/moonlight-android#114]
I would love it if I could use my steam controller with it. Seems the steam controller uses some proprietary protocol because it does not work as an input device... Guess valve put something to disable 3rd party toying.
Hope you can help me out.

**Comment by andyosier** [comment]
I would also like to be able to use my Steam Controller, but with it connected to the PC. This is so that I can use the profiles for the controller. I doubt they would work if the controller was connected directly to the Android TV. I'm going to try renaming the Nvidia DLL as mentioned in the Setup Guide. I'll report back if that works or not.

**Comment by koriwi** [comment]
@andyosier did it work ? I read something on reddit, that you have to rename/remove the xinput.dll.
FYI:https://github.com/ValveSoftware/steamlink-sdk

**Comment by andyosier** [comment]
Yes, it did work! I did the following, from the Setup Guide:

"You'll need to rename the DLL that Nvidia is using to send controller input so it won't be used anymore. On 32-bit and 64-bit Windows, rename rxinput.dll to rxinput.dll.old on in C:\Program Files\NVIDIA Corporation\NvStreamSrv. On 64-bit versions, there's another copy of the DLL in C:\Program Files (x86)\NVIDIA Corporation\NvStreamSrv which you'll want to rename. You may have to do the renaming again if GFE does an update, but it should allow you to use your controller normally on games that only support 1 controller."

I only tried this with the Steam Controller in single player. I didn't try playing with the Android TV controller.

**Comment by koriwi** [comment]
I'll try that right now. Thank you for sharing this.
