### ISSUE TITLE
Cant connect host device through ipv6 in v10.10 but v10.9 can still work

### ISSUE THREAD

**Issue by Bakuteria-Ocha** [moonlight-stream/moonlight-android#1152]
**READ ME FIRST!**
If you're here because something basic is not working (like gamepad input, video, or similar), it's probably something specific to your setup, so make sure you've gone through the Troubleshooting Guide first: https://github.com/moonlight-stream/moonlight-docs/wiki/Troubleshooting

If you still have trouble with basic functionality after following the guide, join our Discord server where there are many other volunteers who can help (or direct you back here if it looks like a Moonlight bug after all). https://moonlight-stream.org/discord

**Describe the bug**

**Steps to reproduce**
Any special steps that are required for the bug to appear.

**Screenshots**
If applicable, add screenshots to help explain your problem. If the issue is related to video glitching or poor quality, please include screenshots.

**Affected games**
List the games you've tried that exhibit the issue. To see if the issue is game-specific, try streaming Steam Big Picture with Moonlight and see if the issue persists there.

**Other Moonlight clients**
- Does the issue occur when using Moonlight on PC or iOS?

**No. ios and pc client is ok**

**Moonlight settings (please complete the following information)**
- Have any settings been adjusted from defaults?
No.
- If so, which settings have been changed?
- Does the problem still occur after reverting settings back to default?
Yes.

**Gamepad-related issues (please complete if problem is gamepad-related)**
- Do you have any gamepads connected to your host PC directly?
- If gamepad input is not working, does it work if you use Moonlight's on-screen controls?
- Does the problem still remain if you stream the desktop and use https://html5gamepad.com to test your gamepad?
  - Instructions for streaming the desktop can be found here: https://github.com/moonlight-stream/moonlight-docs/wiki/Setup-Guide

**Device details (please complete the following information)**
 - Android version: Android 12
 - Device model: Xiaomi 11 pro

**Server PC details (please complete the following information)**
 - OS: Windows 11 21h2
 - GeForce Experience version: [e.g. 3.16.0.140]
 - Nvidia GPU driver: [e.g. 417.35]
 - Antivirus and firewall software:  Windows Defender and Windows Firewall has been turned off

**Additional context**
Anything else you think may be relevant to the issue or special about your specific setup.

**Comment by cgutman** [comment]
Can you provide a little more detail about how exactly you're using IPv6 with Moonlight?

Are you using an IPv6 address directly or are you using a hostname/DNS that resolves to an IPv6 address?

Are you typing that address on the Add PC page or was it an address that was already saved in Moonlight prior to your upgrade to v10.10?

**Comment by Bakuteria-Ocha** [comment]
> Can you provide a little more detail about how exactly you're using IPv6 with Moonlight?
> 
> Are you using an IPv6 address directly or are you using a hostname/DNS that resolves to an IPv6 address?
> 
> Are you typing that address on the Add PC page or was it an address that was already saved in Moonlight prior to your upgrade to v10.10?

I use the v6 address directly and no matter I add pc directly in new version or updated from the old version with the saved address it cant work and shows
![Screenshot_2022-12-01-09-23-29-070_com.limelight.root-edit.jpg](https://user-images.githubusercontent.com/57496324/204943773-1fde4411-93bc-48ac-8f27-22baec5019b5.jpg)

**Comment by ericsyj** [comment]
same issue.

**Comment by ericsyj** [comment]
In fact, the v10.10 cannot perform remote streaming through a pure ipv6 address. If the manually added address is in the form without [], such as 240e:: 1, the prompt like @Bakuteria-Ocha will appear. If you enter an address with [], such as [240e:: 1], you can add it normally, but the domain name resolution error will occur when establishing a connection.
![微信图片_20221201212233](https://user-images.githubusercontent.com/97294040/205063709-95f0fccb-b7ca-4302-8ef5-abaf58816c64.jpg)
However, if you manually add and then connect a domain name that points to an ipv6 address, there is no problem. Therefore, this might be because the format of the ipv6 address entered in this version has changed (you must use [] to wrap the ipv6 address), and when the pure ipv6 address is entered, the domain name resolution is not skipped, resulting in a connection failure.

**Comment by Bakuteria-Ocha** [comment]
> In fact, the v10.10 cannot perform remote streaming through a pure ipv6 address. If the manually added address is in the form without [], such as 240e:: 1, the prompt like @Bakuteria-Ocha will appear. If you enter an address with [], such as [240e:: 1], you can add it normally, but the domain name resolution error will occur when establishing a connection.
> ![微信图片_20221201212233](https://user-images.githubusercontent.com/97294040/205063709-95f0fccb-b7ca-4302-8ef5-abaf58816c64.jpg)
> However, if you manually add and then connect a domain name that points to an ipv6 address, there is no problem. Therefore, this might be because the format of the ipv6 address entered in this version has changed (you must use [] to wrap the ipv6 address), and when the pure ipv6 address is entered, the domain name resolution is not skipped, resulting in a connection failure.

ture dude.
connect successfully with []

**Comment by cgutman** [comment]
Fix released in v10.11.
