### ISSUE TITLE
DualShock 4 vibration working on Android Tablet but not Android TV

### ISSUE THREAD

**Issue by khoanguyen-3fc** [moonlight-stream/moonlight-android#1156]
**Non-working Device details**
 - Android version: Android 10
 - Device model: Sony XR X90J

**Working Device details**
 - Android version: Android 10
 - Device model: Samsung Galaxy Tab S4

**Comment by cgutman** [comment]
This is likely due to an older Linux kernel on your Android TV. Can you report the Linux kernel version of each device? It should be visible in your device settings.

**Comment by khoanguyen-3fc** [comment]
Which Linux kernel version should it support vibration?

I just check it, but my TV Android kernel is newer (4.19.75) than tablet (4.4.205-22915538).
![X90J](https://user-images.githubusercontent.com/16377833/207385309-29a6c073-618c-4450-8082-835969884444.jpg)
![TabS4](https://user-images.githubusercontent.com/16377833/207385322-139ba98d-6a80-4d72-957d-f1b469d1f6d9.jpg)

**Comment by cgutman** [comment]
Hmm, perhaps the Android TV kernel doesn't have the `hid-sony` driver enabled?

We just use built-in Android support for controller rumble. You can try something like https://html5gamepad.com on your devices and see if it can rumble the controller.

**Comment by khoanguyen-3fc** [comment]
> You can try something like https://html5gamepad.com/ on your devices and see if it can rumble the controller.

I can't test that on my TV, but

> Hmm, perhaps the Android TV kernel doesn't have the `hid-sony` driver enabled?

I get it, maybe that, thanks so much.

Irrelevant, but maybe useful to someone else, Logitech F710 vibration work on my TV if I enable "Override native Xbox gamepad support"
