### ISSUE TITLE
Nvidia is shutting down Gamestream in February 2023. What will happen with Moonlight ?

### ISSUE THREAD

**Issue by Kristijan1001** [moonlight-stream/moonlight-android#1159]
https://nvidia.custhelp.com/app/answers/detail/a_id/5436

What’s happening to Gamestream?
 

Starting in mid-February, a planned update to the NVIDIA Games app will begin rolling out to SHIELD owners. With this update, the GameStream feature will no longer be available in app. SHIELD users can continue to use GameStream until that time.
 

How can I stream from my PC to my SHIELD after Gamestream becomes unavailable?

 SHIELD owners can  use [Steam Link](https://store.steampowered.com/app/353380/Steam_Link/) to stream games from their PC to SHIELD. Steam Link supports 4K streaming and allows streaming to many devices, including PCs, phones, and tablets. Gamers can also stream PC games from the cloud to their SHIELD TV using NVIDIA’s [GeForce NOW](https://www.nvidia.com/en-us/geforce-now/) service.
 

What happens if I don’t update the NVIDIA Games app?

Gamestream may continue to work for a time, but will no longer be supported and eventually will stop working. All other services supported by NVIDIA Games, including GeForce NOW, will require an app update to continue working. 
 

Where can I download Steam Link?

Steam Link requires Steam installed on your gaming PC, and the Steam Link app installed on your SHIELD TV. To learn more, visit the [Steam Link](https://store.steampowered.com/app/353380/Steam_Link/) page.
 

Can I still use NVIDIA Share with Steam Link?

Yes, NVIDIA Share will still work with Steam Link

**Comment by toxicrecker** [comment]
use this: https://github.com/LizardByte/Sunshine
> It is an open source implementation of NVIDIA's GameStream, as used by the NVIDIA Shield.

**Comment by Kev506** [comment]
I use Gamestream on my PC with moonlight on my Google TV, I've disabled GeForce experience updates. Hoping that's enough to keep it working.

Haven't tried sunshine, checked on GitHub seems to have a lot of issues.

**Comment by cgutman** [comment]
We have an FAQ page regarding the announcement here: https://github.com/moonlight-stream/moonlight-docs/wiki/NVIDIA-GameStream-End-Of-Service-Announcement-FAQ

For general discussion, please use the Discord server: https://moonlight-stream.org/discord
