### ISSUE TITLE
Amazon Fire TV - Xbox One Controller

### ISSUE THREAD

**Issue by miketweaver** [moonlight-stream/moonlight-android#116]
I am unable to get the Xbox One controller wired working with the Fire TV. When I plug the controller in, it blinks for a little bit, and then the white power light goes off. I'm able to use other controllers (borrowed for testing) but I've had zero success with the Xbox One via a wired connection. 

I have v3.1.13, downloaded from the Amazon App store. I am able to get the controller working on my Nexus 5 just fine via an OTA cable. 

With the Fire TV2 root just opening up, if I need to root the device to fix it, I have no issues with that.

**Comment by memerboy88** [comment]
Having the same problem with the xbox one controller causing my Note 5 to crash and reboot.

**Comment by cgutman** [comment]
@memerboy88 There's a firmware bug on the Note 5 and S6 Edge+ that causes a device crash when using the USB host APIs built into Android. I've reported the issue to Samsung and I'm waiting to hear back from them.

@miketweaver I looked into this issue tonight and it appears that the USB host API for requesting permission to connect to a USB device (critical for the driver to connect) is broken on the Fire TV 2. It tries to show the system permission dialog but can't for some reason. I reported the issue on Amazon's developer forum.

**Comment by memerboy88** [comment]
@cgutman good to know xd thanks

**Comment by miketweaver** [comment]
@cgutman Awesome. Lets hope someone at Amazon can help. 
In the meantime, maybe we could look at a work around? These people seem to have a similar issue and were able to bypass the prompt for rooted devices.

http://stackoverflow.com/questions/13726583/bypass-android-usb-host-permission-confirmation-dialog

If that's not the best way, do you know a way of injecting this driver into android itself?

**Comment by miketweaver** [comment]
While Amazon works on this, those that have root access can use this workaround. I compiled a kernel module that allows the Xbox One Controller to function. Just follow the steps on this forum post and you'll be good:
http://forum.xda-developers.com/fire-tv/development/ftv2-kernel-module-xbox-one-controller-t3272578
