### ISSUE TITLE
video DECODER crashes , since recently (ca. 12/2022) (firestick 4k max)

### ISSUE THREAD

**Issue by Ulf3000** [moonlight-stream/moonlight-android#1165]
**Describe the bug**
Since recently the video decoder crashes on my firestick 4k max 

only the first frame is transferred and then the image freezes.
audio continues to stream just fine !!! so its not a network problem ! 

i only get german error but it says translated "videodecoder crashed because incompatility  of your devices video decoder"

before it worked really nice , so i think maybe its an update to either geforce experience or the amazon fire os (both are out of my control so i cant really downgrade them)

**Other Moonlight clients**
- streaming to moonlight client on my laptop works

**Moonlight settings (please complete the following information)**
ive tried all settings , hevc , different bitrates, etc.

**Device details (please complete the following information)**
 amazon firestick 4k max

**Server PC details (please complete the following information)**
 - win10 (most recent update)
 - GeForce Experience version: [e.g. 3.26.0.160]
 - Nvidia GPU driver: [e.g. 511.23]
 - Antivirus and firewall software: all disabled 

**Additional context**
I can only guess that a recent update for firestick would have messed with the decoder drivers

**Comment by Ulf3000** [comment]
ok this can be closed , seems like installing the newest version from the store fixed it.

**Comment by Vladishun** [comment]
Thanks for confirming the update fixed it. I wasn't able to update from the app store on my Firestick but after uninstalling the app and installing the latest version Moonlight is working again.

**Comment by Ulf3000** [comment]
> Thanks for confirming the update fixed it. I wasn't able to update from the app store on my Firestick but after uninstalling the app and installing the latest version Moonlight is working again.

exactly the same process for me , i first had to uninstall and then reinstall from the amazon store
