### ISSUE TITLE
2 host of same network in 1 client over internet issue.

### ISSUE THREAD

**Issue by sudhanshugairola** [moonlight-stream/moonlight-android#1175]
Hi,
I noticed a issue while adding 2 host pc which is on same network  i notice it work good in local network, but when I move to over internet then 1st one pc connected only while 2nd host pc not added on moonlight client by chance sometime it added 2nd host but later only 1st one connected and 2nd pc up his hand and not connecting even I'm putting right pin. Both pc on same host show different name but while connecting only one worked on over the internet.

**Comment by cgutman** [comment]
Yes, this is a limitation of the automatic port forwarding option on the [Setup Guide](https://github.com/moonlight-stream/moonlight-docs/wiki/Setup-Guide#automatic-configuration-recommended-for-most-users).

For support for multiple hosts behind a single Internet connection, you'll need to use one of the other options, such as ZeroTier/TailScale VPNs or IPv6. Sunshine will eventually support this use case without IPv6/VPN requirement with its dynamic port support, but it doesn't yet.
