### ISSUE TITLE
Chromebook android client audio crackling.

### ISSUE THREAD

**Issue by ulmeck** [moonlight-stream/moonlight-android#1181]
**Describe the bug**
On my Lenovo Duet 5 Chromebook, I use the android client, which had previously been working flawlessly. Recently, however, all audio crackles, regardless of the streaming rate. On my phone, on the same network, it works fine. This is under both GFE and Sunshine streaming

**Steps to reproduce**
Any streaming with audio is affected.

**Screenshots**

**Affected games**
Marvel Midnight Suns, Yakuza 0, Outer Wilds. All games that I have tested.

**Other Moonlight clients**
works great on my other android phone.

**Moonlight settings (please complete the following information)**
- Have any settings been adjusted from defaults?  None, although I've tried many combinations of audio settings
- If so, which settings have been changed? N/A
- Does the problem still occur after reverting settings back to default? Yes

**Gamepad-related issues (please complete if problem is gamepad-related)**
- Do you have any gamepads connected to your host PC directly?
- If gamepad input is not working, does it work if you use Moonlight's on-screen controls?
- Does the problem still remain if you stream the desktop and use https://html5gamepad.com to test your gamepad?
  - Instructions for streaming the desktop can be found here: https://github.com/moonlight-stream/moonlight-docs/wiki/Setup-Guide

**Device details (please complete the following information)**
 - Android version: Latest ChromeOS (Android 9)
 - Device model: Lenovo Duet 5

**Server PC details (please complete the following information)**
 - OS: Windows 10
 - GeForce Experience version: 3.27.0.112 and Sunshine (latest version)
 - Nvidia GPU driver: 528.49
 - Antivirus and firewall software: Disabled
  
**Additional context**
It PROBABLY has something to do with the android emulation that the Chromebook does, but this did work perfectly a few months back when I played the entirety of Persona 4 on this chromebook with no issues.

**Comment by cgutman** [comment]
Hmm, there haven't been any audio changes in the Moonlight code for 7 months. Any chance this is network-related or caused by a ChromeOS update?

You may also try enabling the system equalizer support checkbox which can disable low latency mode which smooths over some audio underruns.

**Comment by ulmeck** [comment]
To be honest, I don't' know exactly when it started. Looks like I finished Persona 4 in late 2021, and I hadn't started using Moonlight again until the beginning of this year. It could be a chromeos/android (android 9, btw) update. I did a powerwash to put it back to factory with no affect.

Tried the equalizer support with no consistent success, same for 5.1 and 7.1 support. All other android apps work properly with audio, including steamlink. I have two other chromebooks I can try and see if there's a difference.  Works fine with my Motorola phone (android 11).

I'll report back with the info on the other two chromebooks.

**Comment by ulmeck** [comment]
Did more digging. It's related to the video resolution. 720p, no issues. 1080p and the audio drops out like crazy.

Went back to v9.9 and it was there at that time too, so it isn't recent.

FPS doesn't affect the problem, Both 30 and 60 fps are fine in 720, crackly in 1080.
CPU never breaks 25% on the chromebook (Qualcomm 7180 CPU, 8 core), and Moonlight decode rates are the same for both 1080 and 720.

I'm at a loss, but I'm willling to look at anything.

**Comment by ulmeck** [comment]
I'm going to close this. After the last chromebook system update, it seems to have disappeared and working okay. Still not sure what the deal was.
