### ISSUE TITLE
Mouse issue

### ISSUE THREAD

**Issue by badruby** [moonlight-stream/moonlight-android#119]
In all my games i cant use the mouse över the display edges. My device is a rooted Nexus 6p with root granted in su . also get popup each time strean Starting saying it got root acess. Ribbing latest 3,1,1,3 and my mouse is razor deathadder . any idea?

**Comment by junpei0824** [comment]
me too.
My device is Android 6.0 running on rooted nexus6.
I think that this issue happen only in Android 6.0.
On Lollipop, the function taking the control of mouse worked successfully.

**Comment by badruby** [comment]
Oh, ok. So we pretty much have to wait for a fix then ill guess

**Comment by junpei0824** [comment]
Android 6.0 has some difference about security and permission system from
Android 5.1 and before.
It may causes the this problem.

2015年12月14日(月) 21:44 badruby <notifications@github.com>:

> Oh, ok. So we pretty much have to wait for a fix then ill guess
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/moonlight-stream/moonlight-android/issues/119#issuecomment-164427739>
> .
>
-- 

Junpei Kishi

**Comment by cgutman** [comment]
This should be fixed since v4.0.2. If it's not, please comment on issue #140
