### ISSUE TITLE
Blank Screen when using over LTE

### ISSUE THREAD

**Issue by charmon1984** [moonlight-stream/moonlight-android#120]
I know this subject has been brought up before, but all the fixes I have found on the internet is not working. Moonlight works fine over my wifi at home, but when I try to connect to my pc over my phones internet I get a blank screen. I can see all my games and can click on any of them to start up. I can hear the game going but I can't see anything. When sitting in front of my computer I can move my mouse around with my phone also. I used to be able to play games over my phones internet. I'm not sure why I can't anymore.

Things I've tried:

Tripple checked my port forwarding on my router and my firewall. 
Turned off my firewall.
Deleted Gefore Experience and reinstalled.
Reinstalled my nvidia drivers.
Downloaded moonlight and tried it on my wifes phone. 
Turned down resolution and bitrate all the way.
Installed Windows 10 and tried gamestream.

Nothing has worked. Any help would be greatly appreciated.

**Comment by forgedp** [comment]
Check your port forwarding ip.
Worked for me.

**Comment by iceman2k** [comment]
Maybe it's not a network problem.

If you turn off the monitor that connected with the **display port** cable.
Then your PC don't recognize that monitor.

Here is the my solutions.
1. Change your cable to a HDMI or DVI.
2. Turn on your monitor always.
3. Plug a additional HDMI cable (Your pc and monitor linked with 2 cables.)

I hope this can help you.
