### ISSUE TITLE
No video displayed on android device (when nvidia surround enabled)

### ISSUE THREAD

**Issue by xila76** [moonlight-stream/moonlight-android#121]
I've good gamer computer configuration running Win8.1 pro x64 with : 
2 GTX 970 (MSI gaming 4G) in SLI
3 screens 1920x1080 in 144Hz (iiyama)
i7 4790k and 16Go RAM and 500Go SSD
Geforce experience 2.5.15.54 (tried too with the last version but issue is same...)
Geforce driver 359.06

I tried the non root version of moonlight on two devices (nexus 7 2013 and galaxy S6 edge) but it does not work ! I can hear sound, control of the mouse on the PC from the android device but it's all ! No way to have video displayed on android device

I tried to uninstall teamviewer in first way after reading troubleshooting page in wiki, I dont see any software installed named "Displaylink", I've tried to uninstall/re-install all the nvidia software but the problem still remain...

Could you help me ?

Moonlight is for me a good way to try the "Nvidia Gamestream" feature before any buy of specific device for...

**Comment by xila76** [comment]
ok i now well advanced I have a picture on my android but I have to manually change the settings for my graphics card by disabling Nvidia Surround (display on 3 screens as if it were just one) or even when my essay disabling SLI

my questions are the following:

moonlight is compatible with SLI? with nvidia surround?

**Comment by xila76** [comment]
Ok I've test with SLI enable in "Optimize performance" mode it's working very well but disable 2 of 3 screens... :-1: 

It's possible to have a trick or integration of feature somewhere for solve this ?
Because for now if I want to play on phone/tablet I need to switch on PC first for disable Nvidia Surround... in this way it's not thinkable to play from internet... if I need after wake on lan/wan to connect first for disable nvidia surround where this parameter is not available in RDP... and teamviewer need to be close before launch MoonLight...

Someone has the same problem as me ? (nvidia surround)

**Comment by xila76** [comment]
Other problem my cheap usb controller and otg cable seems to work in Android (can move under home screen, launch apps with button) but in game with moonlight only directionnal stick and joystick work, no one button work... someone could help me with this problem??

**Comment by xila76** [comment]
No one has the same problem ? i'm the only one to have nvidia surround on triple screen?

**Comment by evildog1** [comment]
sorry, i don't have triple screen, so i can't help you. i tested Moonlight on my phone Z3 compact and my low end tablet Denver TAD-10023 and both runs very smooth with audio.

**Comment by xila76** [comment]
it works for me too, but only if I manually deactivated by being physically in front of the PC and nvidia surround it is really impossible to imagine playing over the WAN (with wake on lan PC) until this problem is not solved ... for those who like me is the default nvidia surround function activated at the launch of PC

**Comment by evildog1** [comment]
oh ok. contact the developer via email for help.

Btw, PS3 controller works fine on my Z3 compact with native PS3 controller support, but it does not work on my tablet with normal Android 4.1.1 AOSP version, even i have paired my controller with an app with root access.

**Comment by cgutman** [comment]
I don't think I can do anything. It seems like an issue with GFE's server.
