### ISSUE TITLE
[Issue]: Moonlight stream disconnection when using brush tool in Adobe Photoshop and Lightroom Classic

### ISSUE THREAD

**Issue by jessybell** [moonlight-stream/moonlight-android#1211]
### Describe the bug
When using the brush tool in Adobe Photoshop and Lightroom Classic, the Moonlight stream will disconnect without an error message if the brush diameter reaches a certain size. The error occurs once the brush is hovered over the canvas. The stream can be resumed by lowering the brush size on the host PC, but will crash instantly again if the brush tool diameter size isn't reduced. If the brush size is reduced in time, without hovering over the canvas, the stream will resume without any problem.

This issue occurs when using Moonlight to connect from a Windows PC to a Samsung Galaxy Tablet.

_More detailed information:_

At 100% zoom, the brush causes the stream to crash at size 228px. If I zoom in to 200%, the stream crashes at 125px. However, I didn't test the exact number, I would guess it's actually 128px. 

### Steps to reproduce

1.     Open Adobe Photoshop or Lightroom Classic on a Windows PC.
2.     Connect the Windows PC to a Samsung Galaxy Tablet using Moonlight.
3.     Select the brush tool and increase the brush diameter until the stream disconnects.
4.     Lower the brush diameter and the stream can be resumed without issue.

### _> ### The error will not occur until you hover the brush tool over your canvas (white area in this instance)_

At 100% Zoom, I can increase my brush size to 228px before Moonlight disconnects. 

### Affected games

- Adobe Photoshop version 24.4.1
- Adobe Photoshop Lightroom Classic 12.3 Release (Camera Raw 15.3) 
_I did not do repeat testing on the exact brush sizes for Lightroom. It is the same error, with brush enlargement after a certain size._

### Other Moonlight clients

PC

### Moonlight adjusted settings

Yes

### Moonlight adjusted settings (please complete the following information)

Lowered Refresh rate. 
Adjusted Resolution on host PC.

### Moonlight default settings

Yes

### Gamepad-related connection issue

No

### Gamepad-related input issue

No

### Gamepad-related streaming issue

No

### Android version

Android version 13, One UI version 5.1

### Device model

Samsung SM P613 Galaxy Tab S6 Lite 

### Server PC OS version

Microsoft Windows 10 Pro, Version 10.0.19045 Build 19045

### Server PC GeForce Experience version

3.27.0.112

### Server PC Nvidia GPU driver version

531.61

### Server PC antivirus and firewall software

Windows Defender and Windows Firewall. 

### Screenshots

![image](https://github.com/moonlight-stream/moonlight-android/assets/112842152/f92cd306-3654-4ebf-bd6b-6b2cdf395980)

### Additional context

This is not the first report of this issue I've seen. 

    The issue occurs regardless of the type of brush being used.
    The issue occurs regardless of whether the firewall is enabled or disabled.
    The issue occurs regardless of the version of the GeForce driver being used.
    GeForce Experimental Features are disabled.
    The issue occurs whether a bluetooth mouse or non-bluetooth tablet pen is being used.
    The Moonlight Android App was downloaded from Google Play.
    No other issues whatsoever, Adobe programs run smoothly and happily on my PC without crashing.

**More Computer Specs:**

-  Intel Core i5-6600K CPU
-  NVIDIA GeForce RTX 3070 GPU 
-  WiFi 6 (both devices) 
-  Direct X 12.0
-  GeForce Driver is "Studio Driver"

**Comment by cgutman** [comment]
This is a bug in GeForce Experience which will not be fixed because Nvidia has dropped official support for GameStream. The open-source [Sunshine](https://github.com/LizardByte/Sunshine) host works fine.
