### ISSUE TITLE
[Issue]: Change the default port of the Android client to the specified port I want

### ISSUE THREAD

**Issue by qinchanggen** [moonlight-stream/moonlight-android#1216]
### Describe the bug

When I added an IP, I specified the port number I wanted and also changed the corresponding port number during pairing. However, an exception error was reported during pairing, stating "java. net. SocketTimeoutException: failed to connect to/116.2118.6170 (port 36012) from/192.168.31.98 (port 48064) after 5000ms"

### Steps to reproduce

Manually add an IP, change the port number, and click pairing

### Affected games

Any device pairing failed

### Other Moonlight clients

PC

### Moonlight adjusted settings

Yes

### Moonlight adjusted settings (please complete the following information)

no

### Moonlight default settings

Yes

### Gamepad-related connection issue

Yes

### Gamepad-related input issue

Yes

### Gamepad-related streaming issue

Yes

### Android version

Android 10

### Device model

vivo X21

### Server PC OS version

WIN 10

### Server PC GeForce Experience version

3.16.0.140

### Server PC Nvidia GPU driver version

417.35

### Server PC antivirus and firewall software

电脑管家

**Comment by cgutman** [comment]
I suspect this is an issue with your setup rather than a bug in Moonlight. Specifying alternate ports via the Add PC option in the form `hostname:port` or `ipaddress:port` is supported (and you can even see in your debug toast that it tried to use the port you asked it to use rather than the default 47989).
