### ISSUE TITLE
[Feature request]: Add sPen config

### ISSUE THREAD

**Issue by Elaski6573** [moonlight-stream/moonlight-android#1218]
### Is your feature request related to a problem? Please describe.

Using moonlight with sPen is very comfortable but there are some problem like double click is very hard.
I think it can be fixed with adding settings for sPen.

### Describe the solution you'd like

Add config settings for sPen.
*Defalut of sPen for Moonlight
     Touch : left click (MB1)
     Air Command(sPen button) : right click (MB2)
     Hovering : mouse pointer move

### Describe alternatives you've considered

Settings Example
> **1. Click settings**
1. Left / Right click reverse
2. Long touch to active as right click 
         _*This feature disabled when no.4 setting enabled._
3. Long Air Command
    3-1) Long air command key setting (Default : disabled) - if no,1 setting is active, short air command became Left click. There is no effect to long air command
         _*This feature disabled when no.4 setting enabled._
4. Block screen touch
    4-1) Add Long air command
         _*Short air command act as right click(MB2), long air command act as left click(MB1)_
         _If you want to use short air command as left click, then active no.1 setting_
5. Long touch(or Air Command) time config
         _*can choose of length of long touch_

> **2. sPen trackpad setting**
- can use sPen like trackpad or touch screen

Air Command Menu can be disabled from android settings.

**Comment by cgutman** [comment]
Going to close this as fixed now that stylus passthrough is implemented.
