### ISSUE TITLE
custom resolutions / framerate

### ISSUE THREAD

**Issue by lastblade** [moonlight-stream/moonlight-android#122]
is this possible at least at the beta releases ?
not everyone who have standards displays :)

**Comment by xila76** [comment]
what's your resolution/framerate settings ? for me doesn't work if nvidia surround 2D it enabled but if i disable it it's work very well...

**Comment by r0tt0r** [comment]
Hi, i found a very simple but really helpful hack to this. My gaming system only has a display attached allowing 1024x768 connected per vga cable. When setting to 1080p i get the error that server display does not support it.

After digging thorugh it was related to the edid of the monitor does not allow other resolutions beeing set.

On VGA do:
http://nookkin.com/articles/how-tos-and-guides/allowing-any-screen-resolution-on-vista.ndoc

and after a reboot i can set in moonlight to the higher resolutions settings

**Comment by muffinmannameistaken** [comment]
I currently have a tab s2 is there a way to stream to it natively?  It has a unusual resolution of 2048x1538 and what i tried so far is set my desktop resolution to the tablet resolution and inside moonlight check on stretch screen , this sort of works. Splashtop supports this resolution but its performance is terrible
