### ISSUE TITLE
[Issue]: PC mouse cursors are all black no colors..

### ISSUE THREAD

**Issue by ruthan** [moonlight-stream/moonlight-android#1225]
### Describe the bug

Hello,
im using Windows 10 64bit and all Diablo 1 256 colors mouse custom cursors and they are all black after moonlight connects, all other colors are fine..  
  So its pretty hard to navigate in Steam, which have pretty dark skin.

  

  

### Steps to reproduce

Set some custom 256 colors on cursor within Windows 10 - *.cur / ani files, connect on phone with Moonlight, select Steam..

### Affected games

All desktop.. with games im using controller and in games, games are mostly using there old cursors so they are fine..

### Other Moonlight clients

PC

### Moonlight adjusted settings

Yes

### Moonlight adjusted settings (please complete the following information)

Nothing about cursors..

### Moonlight default settings

Yes

### Gamepad-related connection issue

No

### Gamepad-related input issue

No

### Gamepad-related streaming issue

No

### Android version

12

### Device model

Sony Xperia 10 III

### Server PC OS version

Windows 10 22H2

### Server PC GeForce Experience version

lastest

### Server PC Nvidia GPU driver version

lastest

### Server PC antivirus and firewall software

Avira

**Comment by ruthan** [comment]
Cursor examples..
[Cursors.zip](https://github.com/moonlight-stream/moonlight-android/files/11857511/Cursors.zip)

**Comment by cgutman** [comment]
This is a host-side issue because the mouse is encoded into the video stream. Are you hosting with Sunshine or GeForce Experience?

If it's Sunshine, you should file an issue on Sunshine. If it's GeForce Experience, that's discontinued by Nvidia, so they will not fix it.

**Comment by ruthan** [comment]
Geforce experience, im looking to Nvidia drivers notes, probably in every release.. and Geforce experience is part of it and never saw any note about that it ends.
  As user i cant say, why is broken, so i hoped that you can fix it..
