### ISSUE TITLE
[Feature request]: Android virtual keyboard for input

### ISSUE THREAD

**Issue by ruthan** [moonlight-stream/moonlight-android#1242]
### Is your feature request related to a problem? Please describe.

Well i googled, but not find hints how to use virtual keyboard for writing or gamepad for writing on Android, where i dont have keyboard.. online games needs some input.. 

### Describe the solution you'd like

Some gamepad key short to slow virtual keyboard on screen, so Steam like gamepad writing gui on through analog sticks..

### Describe alternatives you've considered

I dont know any..

**Comment by cgutman** [comment]
You can use a 3 finger tap to bring up the keyboard. We'll have a more discoverable solution for this in the future, but it is documented at https://github.com/moonlight-stream/moonlight-docs/wiki/Setup-Guide#keyboardmousegamepad-input-options
