### ISSUE TITLE
[Issue]: G cloud vibrates for a long time and will get stuck

### ISSUE THREAD

**Issue by 137615** [moonlight-stream/moonlight-android#1252]
### Describe the bug

G cloud in the stream if the game triggered vibration for a long time (about 20 ~ 40s) will cause the vibration to get stuck (this problem is triggered by probability), must to lock the screen to end the vibration

### Steps to reproduce

The bug is probabilistic, and the G Cloud can easily trigger and get stuck when the game triggers a long shake

### Affected games

Beyond: Two Souls

### Other Moonlight clients

PC

### Moonlight adjusted settings

Yes

### Moonlight adjusted settings (please complete the following information)

didn't turn on the simulated vibration

### Moonlight default settings

Yes

### Gamepad-related connection issue

Yes

### Gamepad-related input issue

Yes

### Gamepad-related streaming issue

Yes

### Android version

11

### Device model

G Cloud

### Server PC OS version

windows 11

### Server PC GeForce Experience version

Sunshine used

### Server PC Nvidia GPU driver version

537.34

### Server PC antivirus and firewall software

Huorong Internet Security

**Comment by cgutman** [comment]
Can you attach an `adb logcat` log from your device after you trigger the bug?

**Comment by cgutman** [comment]
You can also try with https://github.com/moonlight-stream/moonlight-android/commit/978a879c43127a0215b38960fd5250dabdbaa4e7 and see if that fix helps.

**Comment by 137615** [comment]
This should be useful, tested for two hours without getting stuck again
