### ISSUE TITLE
[Issue]: Gyro Emulation not working for reWASD/Steam Input

### ISSUE THREAD

**Issue by MaestroLiendre** [moonlight-stream/moonlight-android#1258]
### Describe the bug

Hey there! So I finally tried the beta with the gyro and works amazing, I've tried with my Logitech G Cloud and my Poco F3 + Gamesir x2 Pro and they both respond, but for some reason reWASD (a remapping software) seems to not be able to pick up the gyro inputs.

So I leave a video showing the controller where the gyro it's mapped to the mouse, so moving the gyro should move the mouse, but it doesn't, Everything else it's detected, just gyro it's not. Next to it is VSCview which it's actually showing that the gyro it's being picked up (and very precisely actually).

I don't know if gyro does send some "virtual signal" that reWASD it's not able to pick up, but VSCview does. It would be amazing if that could be fixed, as reWASD opens a world of possibilities with remapping.

Edit: Just tested on Steam, and steam input doesn't detect either the gyro.

Thanks a lot.

### Steps to reproduce

Gyro it's detected by the PC, but not by reWASD software.

### Affected games

reWASD Software.

### Other Moonlight clients

PC

### Moonlight adjusted settings

Yes

### Moonlight adjusted settings (please complete the following information)

"emulate gamepad motion sensor support"

### Moonlight default settings

Yes

### Gamepad-related connection issue

Yes

### Gamepad-related input issue

Yes

### Gamepad-related streaming issue

Yes

### Android version

Android 11/13

### Device model

Logitech G Cloud / Poco F3

### Server PC OS version

Windows 11

### Server PC GeForce Experience version

Sunshine Latest Nigthly

### Server PC Nvidia GPU driver version

537.42

### Server PC antivirus and firewall software

None

### Screenshots

https://github.com/moonlight-stream/moonlight-android/assets/147051719/e0cdd97c-2d29-4f2e-ba0f-47f7a8d5c58f

**Comment by MaestroLiendre** [comment]
I think the conflict might be that reWASD "don't communicate" with vigembus, they have "hidgamemap.sys".

**Comment by cgutman** [comment]
Can you move this to the [Sunshine issue tracker](https://github.com/LizardByte/Sunshine/issues)? Since the gyro input is reaching the host successfully, it's not a client-side issue.

**Comment by MaestroLiendre** [comment]
Sure I will! Thanks for the reply.

**Comment by cgutman** [comment]
This was fixed in Sunshine.
