### ISSUE TITLE
[Issue]: Trackpad Scrolling not working on Samsung Tab S9 Ultra

### ISSUE THREAD

**Issue by hot22shot** [moonlight-stream/moonlight-android#1259]
### Describe the bug

Hi,

I'm using a Samsung Tab S9 Ultra with the keyboard/trackpad also from Samsung.
Left/Right click is OK with the trackpad but Scrolling is not available.

I also tried from Dex with the same results.

### Steps to reproduce

No special steps

### Affected games

All of them

### Other Moonlight clients

PC

### Moonlight adjusted settings

Yes

### Moonlight adjusted settings (please complete the following information)

I adjusted the resolution to a custom one to fit my tablet (2960*1820)

### Moonlight default settings

Yes

### Gamepad-related connection issue

Yes

### Gamepad-related input issue

Yes

### Gamepad-related streaming issue

Yes

### Android version

Android 13

### Device model

Samsung Galaxy Tab S9 Ultra

### Server PC OS version

Windows 11

### Server PC GeForce Experience version

Latest version

### Server PC Nvidia GPU driver version

Latest version

### Server PC antivirus and firewall software

Windows Defender

**Comment by hot22shot** [comment]
I got the right click working by tinkering with the client options, but still no luck with scrolling.

**Comment by hot22shot** [comment]
I kind of forgot to write that I'm not using GFE but Sunshine 0.20

**Comment by hot22shot** [comment]
Tested with Sunshine 0.21 and latest moonlight-android and I still had the same issue.
I also tested with a bluetooth mouse and foud no issue.

**Comment by hot22shot** [comment]
Seems to be the same issue as it is also solved by using a true mouse.
And I could reproduce the issue with Microsoft RDP client.

**Comment by Buddelbubi** [comment]
Same on Samsung Tab S8 Ultra. Pretty annoying. Would be cool if we could get a fix.

**Comment by hot22shot** [comment]
The issue is coming from Samsung : the scrolling on the touchpad is just emulating a finger swipe, not a mouse wheel.
That is why there is no issue while using a real mouse.

I don't think we'll have a fix from Samsung anytime soon as the issue has been going on since the Tab S6 at least.

Although some Android apps seem to manage to compensate for this.
For example the official RDP client from MS has the same issue but other RDP client does not.
Read this thread about the Tab S6/S7 : https://r1.community.samsung.com/t5/tablets/tab-s6-keyboard-right-click-does-not-work-in-microsoft-rd-client/td-p/3554184

So for moonlight-android, it would need specific development to translate the gesture sent by the trackpad to the correct one.
I don't know what it would cost in time and effort to implement, maybe equal to the configuration of a specific controller ?

**Comment by ClassicOldSong** [comment]
Hey guys, here I have a version that may get scrolling on Samsung devices with DeX working: https://github.com/ClassicOldSong/moonlight-android/releases/tag/v12.1-noir-240802

I can't help with RDP though but at least it should work on moonlight now.

**Comment by ClassicOldSong** [comment]
The issue is partially from Samsung and partially from Android's janky event system, and @hot22shot was very close to get the problem solved actually!

**Comment by hot22shot** [comment]
Just had a look at your fork, there are some nice features, thank your for that 👍🏻
