### ISSUE TITLE
[Issue]: Controller sticks get stuck

### ISSUE THREAD

**Issue by Pevtrick** [moonlight-stream/moonlight-android#1260]
### Describe the bug

After seeing that the smartphone's gyroscope can now be passed to the host, I switched the host software from GeForce Experience to Sunshine. Unfortunately, the experience was not so good, as the controller sticks frequently got stuck. The problem also occurs when I turn off the new gyroscope feature. By stuck I mean that, for example, a left movement of the stick continues to be triggered even though the stick is already back in its original position. I don't know if it's Sunshine or Moonlight, but I can pretty much rule out that it's a stick drift of the controller.

### Steps to reproduce

Start a stream and use the controller in a supported application.

### Affected games

All that I have tested.

### Android version

Android 14

### Device model

Google Pixel 7 Pro

### Server PC OS version

Windows 11 Pro 22H2

### Server PC Sunshine version

0.21.0

**Comment by Mothamoz** [comment]
Experiencing the same issue

**Comment by Mothamoz** [comment]
I'm taking a wild guess but perhaps the below has something to do with it? If I recall correctly it did not happen for me using 0.20 stable and it started somewhere in the nightly release cycle. This is a shot in the dark, but who knows

![image](https://github.com/moonlight-stream/moonlight-android/assets/91319736/b7ada7fe-1d12-47dc-a3a9-30870588da3c)

**Comment by cgutman** [comment]
If you press a button on the controller when the sticks are stuck, do they snap back to the centered position?

**Comment by Mothamoz** [comment]
> If you press a button on the controller when the sticks are stuck, do they snap back to the centered position?

If you move the stick that's stuck in any direction it centers again

**Comment by cgutman** [comment]
Does this build fix the issue? https://drive.google.com/file/d/1B5eIsOZcdQLdU0fDjTw7bk4XVpSmxZrA/view?usp=sharing

**Comment by Pevtrick** [comment]
Hi @cgutman . Thank you, that build fixed it for me.

**Comment by cgutman** [comment]
Fixed by 3a89dbf4ab859c00a75c39c28fc49e594e705281
