### ISSUE TITLE
[Issue]: When using touch mode, sometimes clicking the mouse mouse will stay in place and click

### ISSUE THREAD

**Issue by 1399702039** [moonlight-stream/moonlight-android#1261]
### Describe the bug

When using touch mode, sometimes clicking the mouse mouse will stay in place and click, will not follow the finger movement, you must drag the mouse mouse to follow the finger movement, and the joystick will sometimes get stuck, on the Android 13 tablet the mouse movement direction is reversed, the device is Lenovo Xiaoxin padpro12.7

### Steps to reproduce

no

### Affected games

dnf

### Other Moonlight clients

PC

### Moonlight adjusted settings

No

### Moonlight adjusted settings (please complete the following information)

no

### Moonlight default settings

Yes

### Gamepad-related connection issue

Yes

### Gamepad-related input issue

Yes

### Gamepad-related streaming issue

Yes

### Android version

13

### Device model

xiaoxin pad pro 12.7

### Server PC OS version

win112h22

### Server PC GeForce Experience version

sunshine 0.21

### Server PC Nvidia GPU driver version

amd 23.10.1

### Server PC antivirus and firewall software

no

**Comment by cgutman** [comment]
I think this was the same bug that caused the stuck analog sticks which was fixed in v12.0.1.
