### ISSUE TITLE
Enormous latency on AYN Odin Pro with 12.0

### ISSUE THREAD

**Issue by HollyCeuin** [moonlight-stream/moonlight-android#1262]
### Describe the bug

Under 12.0, with the same settings, and no indication of any problem with decode or network latency, after a couple of minutes the input latency will go extremely out of sync, very quickly. This manifests as stuck directions on the analogue sticks, delayed inputs, all while the video and audio continue in real-time. 

### Steps to reproduce

Install Moonlight 12.0 on the Odin, stream anything for a few minutes. The settings I was using were 1080/60/35mbps under HEVC both times. I had tried improving my network, downgrading sunshine and only downgrading Moonlight to the previous version solved this. 

### Affected games

All

### Other Moonlight clients

PC

### Moonlight adjusted settings

Yes

### Moonlight adjusted settings (please complete the following information)

1080p, 60fps, balanced latency, 35mbps. Everything else can be set to default and it still occurs. 

### Moonlight default settings

Yes

### Gamepad-related connection issue

No

### Gamepad-related input issue

No

### Gamepad-related streaming issue

Yes

### Android version

10

### Device model

AYN Odin Pro

### Server PC OS version

Windows 11 Pro, 22H2

### Server PC GeForce Experience version

Sunshine v0.21.0

### Server PC Nvidia GPU driver version

N/A, AMD 23.9.3

### Server PC antivirus and firewall software

Windows Defender/Firewall

**Comment by cgutman** [comment]
I suspect this is the same underlying bug as #1260. v12.0.1 is rolling out on the Play Store with a fix for this. You can enroll in the public beta on the Play Store or just wait until it reaches your device normally.

**Comment by HollyCeuin** [comment]
Yeah that describes it perfectly, sounds the same. Thank you for the quick fix.
