### ISSUE TITLE
[Issue]: Nvidia shield ps4 gyro

### ISSUE THREAD

**Issue by trololol91** [moonlight-stream/moonlight-android#1264]
### Describe the bug

I need clarification on support for ps4/ps5 controller on Nvidia Shield. I’m trying to get gyro to work but it doesn’t seem to. 

In 12.0.0 change log it mentioned ps4/ps5 support but also mention it only works on Android 12 and later. 

The current version Nvidia Shield is 11 does this mean ps4/ps5 motion sensor is not supported. 

### Steps to reproduce

Setup:
- Sunshine latest to enable DS4 input
- Moonlight latest
- Nvidia shield latest
- DS4 controller connected to Nvidia shield

Steps:
1. Run Moonlight
2. Connect to PC with sunshine
3. Open big picture
4. Start game
5. Enable gyro on game

Actual Result:
- No movement

Expected Result:
- should move 

### Affected games

Generally all games

### Other Moonlight clients

PC

### Moonlight adjusted settings

Yes

### Moonlight adjusted settings (please complete the following information)

Disabled Xbox 350/One USB gamepad driver
Disabled Override native Xbox gamepad support

### Moonlight default settings

Yes

### Gamepad-related connection issue

No

### Gamepad-related input issue

Yes

### Gamepad-related streaming issue

Yes

### Android version

Android 11

### Device model

Nvidia Shield Pro 2019

### Server PC OS version

Windows 10

### Server PC GeForce Experience version

Sunshine 12.1

### Server PC Nvidia GPU driver version

Latest

### Server PC antivirus and firewall software

Eset

**Comment by cgutman** [comment]
> The current version Nvidia Shield is 11 does this mean ps4/ps5 motion sensor is not supported.

Yes, [the API for input device motion sensors](https://developer.android.com/reference/android/view/InputDevice#getSensorManager()) was introduced in API level 31, which is Android 12.

**Comment by trololol91** [comment]
Cool! Thanks for letting me know!


Sent from Yahoo Mail for iPhone


On Saturday, October 21, 2023, 6:36 AM, Cameron Gutman ***@***.***> wrote:





The current version Nvidia Shield is 11 does this mean ps4/ps5 motion sensor is not supported.


Yes, the API for input device motion sensors was introduced in API level 31, which is Android 12.
