### ISSUE TITLE
[Issue]: Switching screens doesn't work after client update

### ISSUE THREAD

**Issue by nhilerion** [moonlight-stream/moonlight-android#1268]
### Describe the bug

I am streaming via sunshine. Using the ctrl + shift + alt + F1-F3 key combinations worked for a while, but after i updated the client, it doesn't work anymore.

### Steps to reproduce

Have at least 2 monitors.
Stream with sunshine.
Connect from android.
Use the key combination: Ctrl + Alt + Shift + F1 or F2
Nothing happens.

### Affected games

I am streaming the desktop.

### Other Moonlight clients

PC

### Moonlight adjusted settings

No

### Moonlight adjusted settings (please complete the following information)

.

### Moonlight default settings

Yes

### Gamepad-related connection issue

No

### Gamepad-related input issue

No

### Gamepad-related streaming issue

No

### Android version

Android 10 / Android 13

### Device model

Huawei P30 / Lenovo Tab M9

### Server PC OS version

Windows 10 22H2

### Server PC GeForce Experience version

Sunshine ver: 0.21.0

### Server PC Nvidia GPU driver version

-

### Server PC antivirus and firewall software

Windows Defender & Windows Firewall

### Additional context

The key combination works while using a pc client.

**Comment by nhilerion** [comment]
I just installed 11.0 from F-droid and it works in that version. I still have 12.0.2 on my tablet and the combo doesn't work.

**Comment by cgutman** [comment]
Fixed by 41429073763bc6c81b6135aed4323f2c2204cc49
