### ISSUE TITLE
The Connection was terminated

### ISSUE THREAD

**Issue by AsOo2k** [moonlight-stream/moonlight-android#127]
hey guys,
to my Problem erverytime i try to start a game from my Andriod Device, Nvidia starts and just as the game starts popping up my connection is terminated. This happens with every game.
Maybe Iam just plain stupid but i can't figure out whats going wrong.Both devices are in the same network. Tried it with an ethernet cable and on wifi. 
Nvidia GE 2.8.121
Thanks in advance asoo

**Comment by Dayto123beast** [comment]
In moonlight try playing a game again. If it still doesnt work remove the pc in the first screen. Does the Pc reshow up?

**Comment by AsOo2k** [comment]
hey,
removed the PC several times, it does not show up immediately, i have to restart the app or add the IP address

**Comment by Dayto123beast** [comment]
Alright  try using a differnt version of GE.  The newer versions have caused that for me. I recommend 
2.5.11.45. After switching have had zero issues

**Comment by AsOo2k** [comment]
hey i did what you told me.
GE wants to update directly to 2.8.....
In the Moonlight app theres only steam available and i get the rtsp handshake Failed Error 500 if i try to launch it.
Thank you for helping btw ;)

**Comment by godwisper** [comment]
I have same problem. On shield hub I get an error and on moonlight connection terminated. Tried as well 2.5.11.45 and got same error on handshake....

**Comment by starzander** [comment]
I have the same problem. I get the same error on all devices I try with (android Nexus 5 and Raspberry Pi) so it seems it must either be on the host PC or on the network, perhaps the router. I use an ASUS RT-N66U. Even though it is over a local network I've tried opening all relevant ports, but to no avail.  I have tried all above mentioned versions of GFE, including the latest beta version. I've uninstalled both GFE and the GeForce drivers several times, but still nothing. It always ends with a failed 500 error with the RTSP handshake. 
I turned off the firewall both on the PC and the router. No change. The Nvidia Streamer Service is running along with all the other Nvidia services.

This is driving me nuts! Where is the fault? It doesn't seem to be in GFE at least, as no version seems to be working. But it being a 500 error, it could be pretty much anything. But the pairing always works, it always finds the list of games it can start and it manages to start the game (or steam) without issues so the connection between devices works. It's something in the RTSP protocol itself.

I'm open to try anything at this point.

My PC specs are as follows:

ASUS ZenBook
Windows 8.1 64-bit
Intel Core i5-4210U CPU 1.70GHz 2.40GHz
6GB RAM
Nvidia Geforce 840M

**Comment by haints** [comment]
I just had this happen to me, and solved it by using a System Restore point going back several days.

It is either a Windows update problem or a Geforce Experience problem. I'm guessing the latter.

**Comment by godwisper** [comment]
you can try this:
http://forum.xda-developers.com/showpost.php?p=63335126&postcount=163

for me it did not work and when I opened the log file I found that my card still gets not supported.

#1(E)[2015-12-29 09:52:57,065]{000017A4}<NvEnc5VideoEncod> Could not open CUDA encoding session (NV_ENC_ERR_UNSUPPORTED_DEVICE).
#2(E)[2015-12-29 09:52:57,067]{000017A4}<ModularVideoProv> Could not start the video encoder.
#3(E)[2015-12-29 09:52:57,068]{000017A4}<RtspHandshake>    Not able to grab frame.

I gave up on this.

**Comment by starzander** [comment]
That didn't work for me either. Where do you find the log with these error messages? I would love to see more about what my card is telling me.

**Comment by starzander** [comment]
Just tested streaming a video file over RTSP from my PC to my phone using VLC, and that worked just fine, so there's nothing wrong with the base protocol itself. I will be testing a few more versions of GFE, to see if there could be a working one. I'll post again later.

**Comment by starzander** [comment]
Hmm, maybe my card isn't supported either. When reading the Moonlight requirements it says "GeForce Experience 2.2.2+ with a GTX 600/700/900 desktop or mobile GPU" so that doesn't include the 800-series, and I have 840M. Why isn't the 800-series supported in Moonlight?

**Comment by starzander** [comment]
Silly me. Here I am trying for days to make this work, and even though my GFE says to me that my GPU supports Gamestream, it does not. I have Geforce 840M, but not Geforce GTX 840M. The GTX bit is key here.

This made me think though... Since everything works up until the actual streaming is supposed to start, and RTSP-streaming itself works just fine, shouldn't you be able to at least stream the video and audio of the game, but maybe connect the controller locally to the PC instead of the receiving device? That way nothing needs to be sent back over the stream, you just need to receive it which shouldn't be a problem. Right? Or am I completely off my gourd?

**Comment by godwisper** [comment]
if you have optimus try disabling it from bios. I tried all sorts of GFE and drivers..even ones for windows 8.1. Been struggling for almost a week full and I cannot get past this. You find the logs in 

C:\ProgramData\NVIDIA Corporation\NvStream

You might need to enable to see hidden files to see the folder program data

**Comment by sanakess** [comment]
I have a solution! u need to restart streaming services in win+r services.msc
![image](https://cloud.githubusercontent.com/assets/20173417/16392926/10c35b04-3cb7-11e6-9397-c3289289f369.png)

**Comment by abc9987** [comment]
From ly log of NVStream:

[...]
16:55:41,207]{000025CC} Capture thread started. Desktop name is 'Default'.
16:55:41,207]{000025CC} Reallocating frame to 2560 x 1440 ARGB.
16:55:41,207]{000025CC} Allocating 2560 x 1440 frame with pitch 10240 and ARGB format (14400 Ki
16:55:41,208]{000025CC} Reserving 30400 KiB of memory.
16:55:41,211]{000025CC} **Failed to grab frame as it is protected content.**
16:55:41,211]{000025CC} Failed to grab frame: -4 (NVFBC_ERROR_PROTECTED_CONTENT).
16:55:41,211]{000025CC} Failed to capture frame 0.
16:55:41,211]{000025CC} Finished with status STATUS_GRAB_ERROR after capturing 0 frames
16:55:41,211]{000025CC} Dropped 0 frames (0.000%)
16:55:41,220]{00002450} Network RTP Sink: PING received from the ...
16:55:41,220]{00002450} Network RTP Sink: updated remote address from ... to ...
16:55:41,220]{00002450} NvAudCapAudioSourceX::reset
16:55:41,220]{00002450} Resetting audio source
16:55:41,705]{00000A84} **Unable to get a frame for 500 ms, timeout at 50000 ms**
16:55:41,707]{0000297C} **Capture thread finished, will now quit.**
16:55:41,707]{0000297C} Failed to grab video frame
16:55:41,707]{0000297C} Received termination reason 0x8103
16:55:41,707]{0000297C} Started to wait on audio thread finish
16:55:41,712]{00002450} Will now signal the stop event
16:55:41,712]{00002168} Requesting async stop for all video streamer threads
16:55:41,712]{00002168} Waiting on video streamers to stop
16:55:41,712]{0000297C} Completed wait on audio thread finish
16:55:41,712]{0000297C} Setting channel back to default stereo
16:55:41,712]{0000297C} Closing internal socket
16:55:41,712]{0000297C} Stopped audio session 0x000000000044C1C0
16:55:41,712]{0000297C} Failed to grab and send frame: 0
16:55:41,712]{0000297C} Perform video streaming is done. Actual frames 0. Frame number 0
16:55:41,712]{0000297C} Stopping Fbc5FrameProvider.
16:55:41,712]{0000297C} Stopped.
16:55:41,712]{0000297C} Deinitializing Fbc5FrameProvider.
16:55:41,712]{0000297C} Destroying FBC object.
16:55:41,726]{0000297C} Unloading FBC library
16:55:41,726]{0000297C} Deinitialized.
16:55:41,726]{0000297C} Flushing encoder.
16:55:41,732]{0000297C} Stopped NvEnc5VideoEncoder.
16:55:41,732]{0000297C} Deinitialized NvEnc5VideoEncoder.
16:55:41,742]{0000297C} Deinitialized CUDA context for adapter 0.
16:55:41,748]{0000297C} Deinitialized context for adapter 0
16:55:41,748]{0000297C} De-initialized video pipeline for adapter 0.
16:55:41,748]{0000297C} Stopping the video sender thread ascynchronously
16:55:42,205]{00000A84} Unable to get a frame for 1000 ms, timeout at 50000 ms
16:55:42,205]{00000A84} Will now exit the video sender thread
16:55:42,205]{00000A84} Video sender thread function done
16:55:42,205]{00000A84} Video sender thread cleanup
16:55:42,205]{0000297C} Closing internal socket
16:55:42,205]{0000297C} Closed video stream UDP connection
16:55:42,205]{0000297C} Stopped the video sender thread.
16:55:42,205]{0000297C} Video stream ended abnormally
16:55:42,205]{00002168} Waiting for video streamer threads to stop
16:55:42,205]{00002168} Starting teardown

Why is that stream protected?
