### ISSUE TITLE
failed to connect..

### ISSUE THREAD

**Issue by brimaster20000** [moonlight-stream/moonlight-android#128]
i get an error failed to connect to /"my ip address" (port 47984) after 3000ms
i have my ports forwarded everything is running on my computer and im on wifi at my home.

**Comment by OOPMan** [comment]
Same for me. Port 47984 is also no longer accessible directly on the hosting machine.

**Comment by brimaster20000** [comment]
It just happens randomly i have to restart my pc two or three times for it to connect.

**Comment by OOPMan** [comment]
I found reverting to GFE 2.5 fixed this.
