### ISSUE TITLE
[Issue]: Can't hide remote cursor with key combination

### ISSUE THREAD

**Issue by joshbirnholz** [moonlight-stream/moonlight-android#1284]
### Describe the bug

I used to be able to hide the remote cursor by pressing a key combination (I think it was control+alt+shift+C) on a connected USB keyboard, however this no longer works.

### Steps to reproduce

- Connect a USB keyboard to my Android device
- Start a stream
- Press Control+alt+shift+C
- Nothing happens, when I would have expected the remote cursor to disappear.

### Affected games

Desktop, CEMU

### Other Moonlight clients

PC

### Moonlight adjusted settings

Yes

### Moonlight adjusted settings (please complete the following information)

default monitor, gamepad type (Dualshock 4)

### Moonlight default settings

Yes

### Gamepad-related connection issue

No

### Gamepad-related input issue

No

### Gamepad-related streaming issue

Yes

### Android version

Android 11

### Device model

Logitech G Cloud

### Server PC OS version

Windows 11 Home 22H2

### Server PC GeForce Experience version

3.27.0.120

### Server PC Nvidia GPU driver version

546.17

### Server PC antivirus and firewall software

Windows Defender, Windows Firewall

**Comment by cgutman** [comment]
Fixed by 41429073763bc6c81b6135aed4323f2c2204cc49
