### ISSUE TITLE
Requesting new features for Moonlight app

### ISSUE THREAD

**Issue by ghost** [moonlight-stream/moonlight-android#129]
Hi

I'm requesting those features that i want to have:
- On-screen xbox controller buttons for peoples who don't have any controllers. Can move buttons freely, and resize the buttons
- Windows 8/10 touch support. I need it for games that support touch, such as Heroes and Titans. I don't like move the cursor, click, move, click...
- A floating switcher that i can switch between trackpad mode and touch mode
- A floating button that i can open the on-screen keyboard.
- Auto hide status bar/soft keys for tablets, so it become full-screen

**Comment by tfurlong** [comment]
I'd like to second the request for Windows 8/10 touch support.  I may be able to put some programming resources towards that capability.  Can someone point me in the right direction to look in the code?
