### ISSUE TITLE
failed to connect with my 920m

### ISSUE THREAD

**Issue by godwisper** [moonlight-stream/moonlight-android#131]
on my acer E5-573G with 920m am getting this error

#7(I)[2015-12-26 13:00:23,959]{00001AE8} Started provider.
#8(E)[2015-12-26 13:00:23,962]{00001AE8} Failed to open CUDA encoding session (NV_ENC_ERR_UNSUPPORTED_DEVICE).
#9(I)[2015-12-26 13:00:23,962]{00001AE8} Error starting encoder.
#0(E)[2015-12-26 13:00:23,962]{00001AE8} Failed to start: Failed to start the video encoder.
#1(I)[2015-12-26 13:00:24,009]{00001AE8} Deinitialized CUDA context for adapter 0.
#2(I)[2015-12-26 13:00:24,010]{00001AE8} Deinitialized context for adapter 0
#3(I)[2015-12-26 13:00:24,010]{00001AE8} Stopping FbcFrameProvider.
#4(I)[2015-12-26 13:00:24,010]{00001AE8} Stopped.
#5(I)[2015-12-26 13:00:24,010]{00001AE8} Deinitializing FbcFrameProvider.
#6(I)[2015-12-26 13:00:24,010]{00001AE8} Destroying FBC object.

I did try this:
http://forum.xda-developers.com/show...&postcount=163

but same problem persist

**Comment by cgutman** [comment]
Unsupported hardware isn't something that should be filed as a bug report here. You can use the forum to discuss that.
