### ISSUE TITLE
Keyboard arrow keys stop working in game 

### ISSUE THREAD

**Issue by thegoob12** [moonlight-stream/moonlight-android#132]
Hi guys,
Sorry if this is the wrong place to ask but I wasn't sure where else to look. 
Basically I've tried it out on several steam games and on several Bluetooth keyboards and I get the same issue where the arrow keys will not work in any game, they work fine on the steam app and every other key works in the games.

Thanks for any help you can give me.

**Comment by cgutman** [comment]
This is fixed in recent GFE versions.
