### ISSUE TITLE
Virtual Controller WIP

### ISSUE THREAD

**Issue by ruqqq** [moonlight-stream/moonlight-android#134]
I've forked @hop3l3ss awesome virtual controller implementation and merged moonlight-android master branch as of v4.0.2: https://github.com/ruqqq/limelight-android

It's working wonderfully except:

1. No configurable size for controller buttons
2. No configurable positions for controller buttons
3. Analog sticks are a bit wonky (perhaps deadzone issue?)
4. Should have option to use whole screen as right analog stick?

Seems like @hop3l3ss has stopped working on it since Feb. :( Posting it as an issue here to call for help to finish the virtual controller implementation and once completed and polished, to send a PR to this repo.

I believe virtual controller is a high priority need. Makes Moonlight a whole lot more usable imo.

**Comment by hop3l3ss** [comment]
Hi ruqqq, 
Well I stopped contributing to it because it seems that no one was really interested in it ;-). 

Except your 4. point I have already fixed this issues on my local branch, I will clean up it and push it afterwards. 

The next what I wanted to add are configuration files to save the current layout as loadable profile.

Greetings

**Comment by cgutman** [comment]
Sorry for dropping the ball on those PRs. It was a lot of code change and I never took the time to do a thorough review until it was already full of merge conflicts with the latest changes. If you can get the changes into another PR, I'll do the review. Let's get a toggle in settings and ship it.

**Comment by ruqqq** [comment]
@hop3l3ss Nice work! Can't wait to play with them. Will be more than glad to test them and fix any minor issues if any.

**Comment by cgutman** [comment]
The PR was merged to master, however there are still bugs. See https://github.com/moonlight-stream/moonlight-android/pull/52#issuecomment-169577930
