### ISSUE TITLE
Stopped working on Sony TV.

### ISSUE THREAD

**Issue by Diggidy** [moonlight-stream/moonlight-android#135]
As the title says, it stopped working. I was using wi-fi on the TV, switched over to wired LAN and it seamed to stop working around this time. I have also updated my GTX 970 Turbo drivers. No game works now, the app freezes on the first screen of any game. I am also getting A/V errors as well, which I wasnt getting before. I reduced the resolution to 720p and still getting errors now. 

I tried going back to wi-fi but that didnt work, I have not tried to rollback the drivers yet. 

TV: Sony xbr55x810c
Video Card: GTX 970 Turbo
GeForce Experience Drivers: 2.9.0.48
Geforce Drivers: 361.43

**Comment by cgutman** [comment]
Heh, funny that you filed this just now. I just pushed a build v4.0.3 that should fix this issue.

**Comment by Diggidy** [comment]
cool, did you publish to Android TV yet?

**Comment by cgutman** [comment]
Yeah, it should roll out through Google Play soon. You can try checking for updates manually in the Play Store.

**Comment by Diggidy** [comment]
Ok, ill test and report back.

**Comment by Diggidy** [comment]
yes it worked, thank you.
The 4k is a bit choppy but im guessing that is the TV's fault.

**Comment by cgutman** [comment]
Good to hear it's fixed.
