### ISSUE TITLE
Occasional stutters, lag, "reduce bitrate message", otherwise handles well over 80mbps just fine

### ISSUE THREAD

**Issue by NullVoxPopuli** [moonlight-stream/moonlight-android#1367]
### Describe the bug

This is a WIP issue, as I'm still collecting information, I just wanted to have a place that didn't pollute other issues' situations while I figure out what's been going on with my situation.

----------------------

Originally commented on: https://github.com/moonlight-stream/moonlight-android/issues/79

Of note, moonlight is running on Ubuntu Linux, 24.04. I did not have any lagging on 23.10 and prior.

I've tried all solutions here (see below), and nothing has helped. What's goofy is I have buttery smooth streaming at 45-80+mbps (though, I keep this lower, because I don't want to tempt the stability anything -- I _do_ have smooth (but slow) streaming and then stutters at 150mbps, so that's def too high) -- and I only have a 4fps slide for maybe 10s every 2-5 minutes. FPS on the host machine (shown via nvidia overlay) never drops belong my streaming refresh rate max (60fps in this case today)

So, this interval stutters is kinda telling me that _either_,
- I have some background job hogging my network at some interval (maybe windows defender? idk)
- something else I don't yet understand

--------

Update:

things I've tried so far
- turning real time protection off for windows defender, no impact
- reducing the streaming bitrate to < 10mbps, no impact
- reducing the display resolution on the host PC to <= 1080p, no impact (host PC has a 4080, and no perf issues)
- reducing the LAN speed to 100mbps, no impact

-----------

Related Docs:
- https://github.com/moonlight-stream/moonlight-docs/wiki/Troubleshooting#video-is-choppy-or-laggy

Related issues:
- https://github.com/moonlight-stream/moonlight-android/issues/374
- https://github.com/moonlight-stream/moonlight-android/issues/89
- https://github.com/moonlight-stream/moonlight-android/issues/79
- https://github.com/LizardByte/Sunshine/issues/2189
- https://github.com/LizardByte/Sunshine/issues/1223

### Steps to reproduce

still figuring these out

### Affected games

n/a, all streaming is affected

### Other Moonlight clients

PC

### Moonlight adjusted settings

Yes

### Moonlight adjusted settings (please complete the following information)

![image](https://github.com/moonlight-stream/moonlight-android/assets/199018/1b999a2a-6961-415d-809d-759fe0a8abbf)

### Moonlight default settings

No

### Gamepad-related connection issue

No

### Gamepad-related input issue

No

### Gamepad-related streaming issue

No

### Android version

n/a

### Device model

Framework AMD 13, AMD Ryzen 5 7640U w/ Radeon 760M Graphics @ 12x 4.971GHz

### Server PC OS version

Windows 11

### Server PC GeForce Experience version

3.28.0.412

### Server PC Nvidia GPU driver version

555.99

### Server PC antivirus and firewall software

Windows Defender and Windows Firewall

### Screenshots

n/a

### Relevant log output

```Shell
wip
```

### Additional context

wip

**Comment by NullVoxPopuli** [comment]
The host PC has 0 issues, lag -- though, I don't know if the problem is with Sunshine or Moonshine.

Here are what the stats look like when streaming is smooth
![image](https://github.com/moonlight-stream/moonlight-android/assets/199018/a23e9046-a800-459e-9207-0277eb8aae6f)

And then when I get the slow connection rate
![image](https://github.com/moonlight-stream/moonlight-android/assets/199018/a29ba4a6-4e70-448b-8191-e58c476af001)


actualling, according to these logs, it looks like maybe Sunshine is having an issue. hmm

**Comment by NullVoxPopuli** [comment]
I'm starting to wonder if this is stemming from the last sunshine upgrade: 0.23.1
I wonder what I had before :thinking:

**Comment by NullVoxPopuli** [comment]
Also, apologies for opening this issue on moonlight-android.

can a maintainer move the issue to sunshine?

**Comment by NullVoxPopuli** [comment]
I updated Sunshine to v2024.609.234340, and the problem persists :thinking:

**Comment by NullVoxPopuli** [comment]
One thing I've noticed is that (during the frame rate drop) the frame rate client side is far below what the performance stats are saying it is. I experienced < 3fps, but the perf stats report up to 23fps (network, decode, and render). This observation was noticed at 4mbps.

**Comment by NullVoxPopuli** [comment]
Switching from Nvidia NVENC and the AMD encoder seems to also show no improvement.

**Comment by NullVoxPopuli** [comment]
I also tried switching to Geforce Gamestream (they brought it back?) 
and the problem _also_ still persists.... so... _not_ a sunshine issue then?
maybe it really is my laptop / decoding. hmm

**Comment by NullVoxPopuli** [comment]
so maybe this issue should move to moonlight-qt?

**Comment by NullVoxPopuli** [comment]
That was a lie, I forgot to turn off wifi when trying. There is 0 problem when wired, so _def not_ a software problem.

It's entirely a problem with my laptop's wifi.

**Comment by shovas** [comment]
Where can I find the latest troubleshooting for this exact issue?

I'm still experiencing these issues in Feb 2025 on a wired PC to Shield over a gigabit lan setup with the exact symptoms described. i7 12700KF w/3080.

I would say 80%+ frames are 60hz/60fps but occassionally there are multi-second slowdowns that look terrible.

I've tried playing the game locally and do not experience these slowdowns, it only happens when streaming.

**Comment by NullVoxPopuli** [comment]
In my case it was either a driver issue or hardware issue (with the specific wifi card).

Here is my evidence:
https://community.frame.work/t/responded-mt7922-poor-performance-fedora-6-7-7-200-fc39-x86-64/46817/3?u=nullvoxpopuli

Linked from a similar thread:
https://community.frame.work/t/intermittentent-wifi-connection-performance-problems-with-amd-13-first-gen-amd/53814?u=nullvoxpopuli
