### ISSUE TITLE
Simultaneously using wireless and wired Xbox 360 controllers?

### ISSUE THREAD

**Issue by Leuthil** [moonlight-stream/moonlight-android#137]
I am running Moonlight on a Nexus Player and my wireless Xbox 360 controllers worked perfectly with the wireless adapter connected through OTG. Just the other day my friend brought 2 wired Xbox 360 controllers and they seemed to be fighting over input slots with the wireless ones. Has anyone else tried this? In other words, if I started a stream with the wired controllers plugged in I would be able to use them but then the wireless ones wouldn't work (or some of them). It seemed like Moonlight would detect the maximum amount of controllers from either wireless or wired (I had 3 wireless and 2 wired all connected so it showed a max of 3). If I had my 3 wireless connected and started the stream, then connected the 2 wireless, neither wireless could control. If I had the wired already plugged in before starting the stream then the 2 wired controllers would give input but only 1 wireless controller would give input as the third. I didn't have a chance to test for too long to get all of the exact behaviour. I'm sure I'm not the only one to have tried this before?

**Comment by Leuthil** [comment]
So I did more testing and realized that this issue is not because of a mixture of controllers but instead just maxed at 3 controllers. I had 4 wireless xbox controllers all synced and it would only ever detect 3 at a time. I thought it was picking up my nexus remote or Bluetooth keyboard as the fourth controller so I unpaired everything but still no luck. Really not sure what else to try at this point. Is there any way to debug this?

**Comment by cgutman** [comment]
What game are you testing with?

**Comment by Leuthil** [comment]
I have tried in Steam Big Picture at first with Gang Beasts and Rocket League. Then I tried just Rocket League directly but the same issue. If I go to Steam Big Picture it showed 4 controllers so I had the idea to unpair things but it didn't fix. Now it only shows 3 in Steam Big Picture. I feel as if something is taking up the last input but I'm not sure what else it could be. Perhaps it's my FLIRC device?

**Comment by Leuthil** [comment]
OK I just tried disconnecting my FLIRC and it's the same thing. One out of the four randomly isn't connected when I restart into Steam and it only shows 3 connected XInput controllers.

**Comment by cgutman** [comment]
Does Steam accurately reflect the number of active controllers when fewer than 3 controllers are plugged into the Nexus Player?

Can you collect ADB logcat logs while trying to use 4 controllers?

**Comment by Leuthil** [comment]
Hmm I don't have root so I don't think I can do ADB logcat logs but I can do a bit more testing on my own to see if I can give a bit more clues as to what's really going on. I appreciate the quick responses.

**Comment by Leuthil** [comment]
I just tested going into Steam with no controllers only by using my remote and it still showed 3 controllers (XInput Controllers) in Steam Big Picture.

**Comment by cgutman** [comment]
Fixed by https://github.com/moonlight-stream/moonlight-common/commit/c65dc3379a69d1cd8fde4fd60636cb1afa17038f
