### ISSUE TITLE
Change Quick Setup guide

### ISSUE THREAD

**Issue by KalleDK** [moonlight-stream/moonlight-android#139]
https://github.com/moonlight-stream/moonlight-android/wiki/Setup-Guide#quick-setup-instructions

Preferences now only have SHIELD menu and a Allow this PC to stream checkbox

![image](https://cloud.githubusercontent.com/assets/574334/12122563/2e4e230c-b3dc-11e5-9031-558cdcfc5164.png)

**Comment by cgutman** [comment]
Done, thanks.
