### ISSUE TITLE
[Issue]: Frame rate not correctly applied on multiple devices

### ISSUE THREAD

**Issue by ClassicOldSong** [moonlight-stream/moonlight-android#1390]
### Describe the bug

Frame rate settings are not applied with only `setFrameRate` calls on some devices (e.g. ColorOS ons like 1+), need to use the `preferredDisplayModeId` to make it actually functional.

### Steps to reproduce

1. Enable show FPS option in Developer Mode
2. Set higher refreshrate than 60fps on some devices (like a ColorOS one)
3. Start the stream
4. The frame rate shown on the top left of screen is still 60

### Affected games

ANY

### Other Moonlight clients

PC

### Moonlight adjusted settings

No

### Moonlight adjusted settings (please complete the following information)

-

### Moonlight default settings

Yes

### Gamepad-related connection issue

Yes

### Gamepad-related input issue

Yes

### Gamepad-related streaming issue

Yes

### Android version

Andorid 14

### Device model

OnePlus Pad Pro

### Server PC OS version

Windows 23H2

### Server PC GeForce Experience version

-

### Server PC Nvidia GPU driver version

-

### Server PC antivirus and firewall software

-

**Comment by ClassicOldSong** [comment]
Fixed in https://github.com/ClassicOldSong/moonlight-android/releases/tag/v12.1-240715-NIOR

Will submit PR later

**Comment by ClassicOldSong** [comment]
Another issue about frame rate lockdown is that, when the app has `isGame="true"` or `appCategory="game"` in the `AndroidManifest.xml`, some modified Android "OSes", mostly by Chinese vendors, will check if the "game" is in its white list to enable high refresh rate, otherwise the "game" app will be forced at 60 fps unless "Disable Dynamic Refresh Rate" is enabled in the Developer Options. Normal non-game apps are allowed with high refresh rate by default, which is hilarious.

I guess this won't be wanted in the main repo, so I'll just keep the modification to my own fork. But the information is worth sharing.

**Comment by moi952** [comment]
@ClassicOldSong Do you think you can get profile management to work?
I'm not a java developer, I tried to merge with the new code and make it work but it doesn't work

https://github.com/moonlight-stream/moonlight-android/pull/919

I throw a bottle into the sea :)

**Comment by ClassicOldSong** [comment]
@moi952  The menu is already there, with much more features added

The profile feature is a bit complicated and I'll look into it in the future(if the main repo still remains silent)

**Comment by moi952** [comment]
> @moi952 The menu is already there, with much more features added
> 
> The profile feature is a bit complicated and I'll look into it in the future(if the main repo still remains silent)

Ah okay I didn't know, great :)

I tried tapping to add the profiles but it's too complicated for me.
Moonlight-android moves very little unlike sunshine or even moonlight-qt, it's a bit of a shame because I use it on nvidia shield and there are features that will be quite practical.

**Comment by ClassicOldSong** [comment]
Closing this issue since "you fixed the issue you opened doesn't necessarily mean others have the same issue", "you fixed your problem but might break every else" and "Either be patient or go away".

What a drama in the discord server!

Getting kicked for helping people out when the main project has no updates and no message about updates for months.

Sure, I'll go away, no more PRs to help people actually in need and I still wish good luck to you.
