### ISSUE TITLE
Logitech F310 not detected as xbox controller

### ISSUE THREAD

**Issue by Whezolor** [moonlight-stream/moonlight-android#141]
I have tried many different options and searched around quiet a bit, but I have not found any way to make my android device detect the F310. I am using an OTG cable with the slider on gamepad set on xinput.

**Comment by SirSharpest** [comment]
What tablet are you using and does your tablet support OTG?

**Comment by Whezolor** [comment]
I am using the "Lenovo 2 8" 16 android tablet (model #ZA030046US)" running kitkat. As far as I can see from a few apps, the tablet does support OTG and even detects the gamepad in certain instances - but it refuses to take any input from the actual gamepad.

**Comment by cgutman** [comment]
This should be fixed in v4.5.1. Please confirm.

**Comment by Whezolor** [comment]
It works, thank you!
