### ISSUE TITLE
Don't work correct hardware decoder

### ISSUE THREAD

**Issue by dan83sama** [moonlight-stream/moonlight-android#142]
Hi, I bought a new phone, Doogee X5 it have mtk6580(quad 1.3,android 5.1, mali400), in olders revision works fine in software decoder(in hardware decoder it does not work correctly, show screen,mouse works, but with high latency 200ms).
In newer revisions only works in hardware mode(suppose),with corresponding high latency.

Attached logcat
http://www49.zippyshare.com/v/kmlQivsi/file.html

and my other issue
https://github.com/moonlight-stream/moonlight-android/issues/48

Finally can compile old versions, but now gfe 2.1.1 seem dont work in windows 10, try new versions moonlight and follows the same error in hardware mode dont start(fails to start the image).Look the commits its only 4 days from 2.5.3.1 to 2.5.4,and it is possible the error are in the sps?? or find safe decoder???,are only 4 commits (others I don't believe):

https://github.com/moonlight-stream/moonlight-android/commit/5fdd9b773c933c691dc732b1891d39f0053f95ee
https://github.com/moonlight-stream/moonlight-android/commit/c02e1ed006a7bd90a066a7f76434bc83a52b535f
https://github.com/moonlight-stream/moonlight-android/commit/ae298fbc518963c73300c6c06e0ca95633e719a7
https://github.com/moonlight-stream/moonlight-android/commit/b5e585834d2021ec11ce9ac69f9eaa30219b85a9

if you need anything, let me know

**Comment by cgutman** [comment]
Are you still experiencing this issue?

**Comment by dan83sama** [comment]
Yes, it stays the same.

new logcat
http://www24.zippyshare.com/v/EbQdnQq7/file.html

feature this part

05-31 16:36:53.682 I/com.limelight.LimeLog(17002): OpenGL ES version: 131072
05-31 16:36:53.684 I/com.limelight.LimeLog(17002): Skipping blacklisted decoder: OMX.google.opus.decoder
05-31 16:36:53.684 I/com.limelight.LimeLog(17002): Examining decoder capabilities of OMX.MTK.VIDEO.DECODER.AVC
05-31 16:36:53.744 E/SensorService(911): activeConnections...
05-31 16:36:53.749 I/com.limelight.LimeLog(17002): Decoder OMX.MTK.VIDEO.DECODER.AVC supports required profile
05-31 16:36:53.749 I/com.limelight.LimeLog(17002): Selected AVC decoder: OMX.MTK.VIDEO.DECODER.AVC
05-31 16:36:53.749 I/com.limelight.LimeLog(17002): Skipping blacklisted decoder: OMX.google.opus.decoder
05-31 16:36:53.749 I/com.limelight.LimeLog(17002): Examining decoder capabilities of OMX.MTK.VIDEO.DECODER.HEVC
05-31 16:36:53.751 I/com.limelight.LimeLog(17002): Found HEVC decoder, but it's not whitelisted - OMX.MTK.VIDEO.DECODER.HEVC
05-31 16:36:53.751 I/com.limelight.LimeLog(17002): No HEVC decoder found
05-31 16:36:53.800 E/SensorService(911): activeConnections...
05-31 16:36:53.804 I/com.limelight.LimeLog(17002): Stream has compatible aspect ratio with output display
