### ISSUE TITLE
Input lag on Shield TV @ 20 ms?

### ISSUE THREAD

**Issue by Zaine6** [moonlight-stream/moonlight-android#143]
Hi,
I have seen moonlight be responsive but in the current state gamestream is infact running flawlessly and in moonlight I am experiencing delay/lack of responsiveness on the controls. 

Please note that when I exit out I see 20 ms on the screen, not sure if there is a better way to check this live? I have seen this go down to 5ms and at that time the game was running perfect but have not been able to reproduce.
- Shield TV 
- Latest beta version of everything
- SLI TITAN X
- 4K TV & 21:9 Monitor

**Comment by Fidelix** [comment]
How's your network connection?
