### ISSUE TITLE
High video latency on Fire TV 2015 (~50ms)

### ISSUE THREAD

**Issue by drsnugglesx** [moonlight-stream/moonlight-android#144]
I'm experiencing very high latency when using moonlight (no matter which version) with Fire TV 2015, no matter if using LAN or Wifi. Is this a solvable issue on moonlights side?

**Comment by FabianAlbrecht** [comment]
Same for me. I'm getting a lag of about half a second on my Amazon FireTV (2015). Doesn't matter if connected by wire or wifi. I also tested with the Moonlight Chrome-plugin on my laptop without any lag. So it seems to be a FireTV problem. Maybe it's the same problem as here: #170

**Comment by chrisipa** [comment]
+1
