### ISSUE TITLE
[v4.0.4] Audio lag on Nexus6(Android 6.0)

### ISSUE THREAD

**Issue by junpei0824** [moonlight-stream/moonlight-android#145]
Video streaming is OK, but audio streaming is lagged and fragmentary.

The game which I played is world of tanks.
GFE is 2.8.1.21 latest now.
GPU is 660Ti.
PC's OS is windows 10.
My Android is Android 6.0 running on nexus 6.
Moonlight is v4.0.4 for Rooted Devices.

Who does know how to fix this issue?

**Comment by FuNK3Y** [comment]
I had the same problem with a nexus 7. GFE is the culprit here, just upgrade to 2.9.1.22
