### ISSUE TITLE
Audio stops after driver & GFE update

### ISSUE THREAD

**Issue by darrennoble** [moonlight-stream/moonlight-android#147]
I updated to driver version 361.43 and GFE version 2.8.1.21 and now when I start streaming from my desktop the audio will stop somewhere between a few seconds or a few minutes of streaming.  And a couple of times when I started the stream there wasn't audio at all.  If I disconnect and reconnect it starts working again.

I have experienced a similar issue with the desktop app as well, except when the issue occurs the app crashes with a stack trace.  It appears that the new GFE is sending unexpected values in the studio stream or a corrupt audio stream.  https://github.com/moonlight-stream/moonlight-pc/issues/146

**Comment by darrennoble** [comment]
If it makes a difference, my phone is a Nexus 6P.

My desktop is one I built a few years ago (except for the upgraded video card).  It has an overclocked i5 2500k, 16 GB RAM, Gigabyte GTX 970 WindForce 4GB, 120 GB SSD for Windows 10, and two 1TB drives in a raid 0.

**Comment by darrennoble** [comment]
It looks like this was an issue with GFE.  I installed GFE beta 2.10.0.60 and the problem went away.

**Comment by darrennoble** [comment]
I'm having this issue again with moonlight 4.5.3 so I updated moonlight to 4.5.5 and GFE to 2.11.1.2 and the problem still persists.

**Comment by cgutman** [comment]
Are you still having this problem with latest Moonlight and GFE?
