### ISSUE TITLE
Connection terminated.

### ISSUE THREAD

**Issue by DonderFourteen** [moonlight-stream/moonlight-android#148]
I can connect my tablet to my computer. But every time I try to play a game it says connection terminated. 

How can I fix this?

**Comment by MonthOLDpickle** [comment]
I am getting the same thing. I can get steam running, launch the game and I even get to main menu. Then connection terminated.

**Comment by hikto** [comment]
Sorry if I'm bumping this issue but I'm also getting this issue right when I launch anything like for example if I launch steam in big picture mode has it currently is I get "connection Terminated" instantly
