### ISSUE TITLE
my phone wont connect to my pc

### ISSUE THREAD

**Issue by DrMichu** [moonlight-stream/moonlight-android#149]
hi, moonlight isn't connecting to my pc i tried everything but nothing works. pls help me

**Comment by newapojim** [comment]
Having exactly hte same issue on my Note 4... tried everything ... disabled my firewall, port forwarded all the numbers on my router and firewalls, reinstalled GFE, any help please....

**Comment by cgutman** [comment]
Reopen if you still have this issues with the latest GFE and Moonlight.
