### ISSUE TITLE
Black Screen on galaxy s6 With Latest GFE and Nvidia Drivers. Will not work if TV is not on....

### ISSUE THREAD

**Issue by CrazedBuffoon** [moonlight-stream/moonlight-android#150]
First of all let me tell you this app is THE BEST!!! :D But unfortunately now out of nowhere I need to have my surround sound receiver on in order to see anything on my Galaxy S6... Normally in the past if I shut off my receiver and tv and open up limelight it would stream the desktop to my phone via the Generic pnp monitor option. Now, If I turn my receiver off i get no picture on my phone... it connects fine but is just a black screen. My current set up is a GTX 980 ti connected to a surround sound receiver via HDMI which is then run to my LG TV. I normally wouldnt care but I cannot play games when Im away from home because I need to be home to physically turn on my receiver :( PLEASE HELP ME it used to work like a charm. I jsut want to be able to wake my PC up again and play games even if my TV or surround sound is off. I beg anyone for help this actually has me very depressed :/

**Comment by cgutman** [comment]
This change happened in GFE 2.8 if I remember correctly. You could try downgrading to 2.7 via an older GFE installer.

**Comment by CrazedBuffoon** [comment]
Dude! Your awesome for even replying man! Thanks a bunch I'll try that. If you ever decide to make it a purchasable app I'll gladly support you, your the best!


Sent from my T-Mobile 4G LTE Device-------- Original message --------From: Cameron Gutman <notifications@github.com> Date: 1/18/2016  2:49 PM  (GMT-05:00) To: moonlight-stream/moonlight-android <moonlight-android@noreply.github.com> Cc: CrazedBuffoon <truesonofliberty@aol.com> Subject: Re: [moonlight-android] Black Screen on galaxy s6 With Latest GFE and
  Nvidia Drivers. Will not work if TV is not on.... (#150) 
This change happened in GFE 2.8 if I remember correctly. You could try downgrading to 2.7 via an older GFE installer.
