### ISSUE TITLE
Compatibility problem with Geforce Experience v2.9.1.22

### ISSUE THREAD

**Issue by cdlt** [moonlight-stream/moonlight-android#151]
Moonlight client dont work with gamestream server  and Geforce Experience v2.9.1.22 installed. 
Gamestream server  with Geforce Experience v2.5.15.46 works correctly.
Tested with moonlight in raspberry and android cellphone.
How can I fix this?

**Comment by cgutman** [comment]
You'll have to be more specific about what the exact error is. It's working for me and many others using GFE 2.9.1.

**Comment by cdlt** [comment]
My apologies. 
Upgrading to the latest version of moonlight solved the problem
Geforce Experience v2.9.1.22 not work with moonlight-embedded_2.1.1-1_armhf and old apk of Android plataform.
Geforce Experience v2.9.1.22  works properly with moonlight-embedded_2.1.2-1wheezy1_armhf and newest apk in Android plataform.
Thank you very much
