### ISSUE TITLE
Nexus 7 will not connect.

### ISSUE THREAD

**Issue by jhuang277** [moonlight-stream/moonlight-android#152]
Hello. 

I'm trying to get Moonlight to connect with my GeForce Experience, but it just will not. At first, the app found my PC and displayed the pin on my android device when I tried to connect, but my PC was not prompted to enter a pin. Now, after reinstalling GeForce Experience, the Moonlight app on my Nexus 7 can't find the PC over my network. I have tried all the troubleshooting procedures and still no luck. I have also tried it with my phone as well, which had the same result. If anyone could provide any assistance, that would be great.

Note: I have tripled checked that all drivers are up to date, as well as reinstalled GeForce Experience and the android app.

Devices:
Nexus 7
iPhone 6s

PC Specs: 
Intel i5-4690
NVIDIA GeForce GTX 770
8 GB RAM
Windows 10

**Comment by cgutman** [comment]
Reopen if you still have this issue with the latest GFE and Moonlight.
