### ISSUE TITLE
Forge TV and Mouse/Keyboard use

### ISSUE THREAD

**Issue by gladius678** [moonlight-stream/moonlight-android#153]
Hey guys,

Forgive the potentially dumb questions (I'm a bit new to this).

I have a mouse/keyboard setup with my forge TV (android OS).

I downloaded moonlight for rooted devices in hopes of removing the double cursor problem.  It hasnt worked, and after further reading it appears I need to 'root' my razer forge tv box?  

Is this possible or recommended?  Im just trying to play diablo 3 on my TV in the living room.

Sorry for dumb questions and thanks for any help you can provide!

**Comment by cgutman** [comment]
Yes, you need to root your Forge to get rid of the double cursor issue.
