### ISSUE TITLE
Request: Hide "Onscreen Gamepad Overlay " option (but not turn off virtual gamepad touch control)

### ISSUE THREAD

**Issue by Michigunskiy** [moonlight-stream/moonlight-android#154]
First of all i want to say huge thanks to all developers of this cool project!
Implementation of "virtual Touch gamepad" - works like a charm as real gamepad.

Please add "hide virtual gamepad touch overlay" function in onscreen gamepad settings menu or something like this, to make vector overlay full transparent after use key-to-touch mapping tool.

I make temporary solution by changed strings in VirtualControllerElement.java to make onscreen gamepad full transparent :

private int normalColor = 0xF0888888;
protected int pressedColor = 0xF00000FF;

to

private int normalColor = 0x00FFFFFF;
protected int pressedColor = 0x00FFFFFF;

It makes gamepad overlay not visible ingame.
After i go in "Entering configuration mode" and use keymapper tool to map bult-in physical buttons and sticks on my device. Then save profile for moonlight.

**Comment by paymok** [comment]
May I know is this feature possible add to current moonlight build on play store? I'm also having the same problem reported from OP. Got a bluetooth controller which works with overlay tools but not moonlight itself. I can easily map my controller buttons from overlay tools to manipulate these virtual keypad in mooblight, but it would be great if these virtual keypad can be hidden so they won't block the screen
