### ISSUE TITLE
Sony kdl 55w809c pc streaming gtx970

### ISSUE THREAD

**Issue by RGH06** [moonlight-stream/moonlight-android#159]
Hello supportive people,

Moonlight streaming i installes from google play store worked but with 2 mouse cursor. Then i delete moonlight from play store. Reinstalled from apitoide still double cursor. Then i found on this forum a solution: root apk from moonlight on one drive account. Games started good also playable but still double cursor. Settings in moonlight i have selected and then not selected apair as one device option. This does not make any changes for the double cursor.

I have a sony kdl 55w809c tv (android tv) and a gigabyte gtx970 with geforce experience and steam. Boot steam in moonlight will not work.

**Comment by RGH06** [comment]
Also the cursor will block me in game. I cannot look full around. i can look till cursor hits the side lines of screen. Maybe 20 degrees left 20 degrees right. When game playing i see cursor just like in menu of android tv.

**Comment by flechter** [comment]
I have exactly the same problem on my sony KD65X9005, it's a shame because it's impossible to play any game.

**Comment by RGH06** [comment]
Its horrible, :( gaming is no fun anymore with problem of cursor. I can set 100mbps with 34ms and 44ms latency, is this good enough?

**Comment by cgutman** [comment]
Are your devices actually rooted? You need root to use the root-only features of Moonlight for Rooted devices?

**Comment by RGH06** [comment]
How can i see device is rooted?

**Comment by cgutman** [comment]
You should have received a root access prompt (you'd know it if you saw it) when starting a stream. It's likely that you're not rooted. There may be a guide out there telling you how to root your TV, but that's beyond the scope of the issue here. If the issue persists after rooting, re-open this.

**Comment by RGH06** [comment]
I not go to root my tv because of warrenty. 
Only option is then buy a geforce shield tv settop box?

**Comment by cgutman** [comment]
You could buy and root a more developer-friendly device like the Nexus Player where doing such will not void your warranty. You could also just pair a Bluetooth gamepad to your TV and use that for gaming with Moonlight.

**Comment by RGH06** [comment]
Thanks you saved me a lot of searching further. Logitech i called to say i need wifi keyboard and mouse. In that case streaming with moonlight will work good? Because cod mw3 need keyboard and mouse for optimal gaming experience.

**Comment by RGH06** [comment]
http://www.tomshardware.co.uk/forum/id-1780894/bluetooth-gaming-mouse-keyboard.html

This will work also? Because of the bleutooth connection?

**Comment by cgutman** [comment]
If your computer isn't too far away from your TV, you can connect your keyboard and mouse to your PC directly (wirelessly) then not have to worry about the Android limitations. See if MW3 works if you play it with your PC keyboard and mouse while streaming it to your TV.

**Comment by RGH06** [comment]
Yeah indeed i know but pc upstairs not going trought floors. I can add every game to geforce experience thats not the problem. Only the double cursor. Must be a way to program into script. I am web developer do not know about program development. Else i would write script by myself. Tv have 2 gb ram and x1 cpu that would not be a problem i guess. Because i can do 100 mbps with 34/44 ms lag latency. Added ports for cod mw3 even thats not needed i guess only when goes tru internet... Thats what i read.
