### ISSUE TITLE
Unable To Connect To The specified Computer

### ISSUE THREAD

**Issue by Ianc666** [moonlight-stream/moonlight-android#160]
I am getting the "Unable To Connect To The specified Computer" when ever I try to connected to my PC. I have tried uninstalling and reinstalling both Geforce experience and moonlight. I am unable to find host on Ipad either. Ihave latest geforce experience beta 2.10.1.2. I have setup all port forwarding, I have tried disconnecting my windows firewall. And have ched that the Nvdia streaming service is running. Any ideas what else I can do?

**Comment by cgutman** [comment]
Reopen if this still happens with the latest GFE and Moonlight.
