### ISSUE TITLE
Black screen, failed to connect after 3000ms

### ISSUE THREAD

**Issue by hervedumoulinarc** [moonlight-stream/moonlight-android#161]
![screenshot 11](https://cloud.githubusercontent.com/assets/13695640/12842489/76973a8e-cbf3-11e5-9c4f-2d90df753a4c.png)
I use Moonlight 3.1.13 for software decoding on droid4x emulator.
Any help will be welcome. :)

**Comment by hervedumoulinarc** [comment]
Sometimes it launch on my x360 spectre instead of surface pro.

**Comment by cgutman** [comment]
Software decoding is no longer supported on Android. If you want to stream on PC, try Moonlight PC - https://github.com/moonlight-stream/moonlight-pc/releases
