### ISSUE TITLE
Nexus 6 H.264 playback

### ISSUE THREAD

**Issue by michal4132** [moonlight-stream/moonlight-android#163]
I get message:

"This device or ROM doesn't support hardware accelerated H.264 playback"
(Nexus 6 running stock 6.0, Moonlight Android v4.5.2)

**Comment by cgutman** [comment]
That seems very weird. Can you download the AIDA64 app and screenshot the Codecs page? You might need multiple screeenshots to get the full page.

**Comment by michal4132** [comment]
![screenshot_20160211-194455](https://cloud.githubusercontent.com/assets/5612283/12986582/5330c51a-d0f8-11e5-8f42-4f43d8e9afd3.png)
![screenshot_20160211-194511](https://cloud.githubusercontent.com/assets/5612283/12986583/53326a1e-d0f8-11e5-90ca-65002ef96490.png)

**Comment by cgutman** [comment]
Your ROM seems to be screwed up. It's missing all Qualcomm hardware decoders, although the encoders are there. You probably aren't getting hardware accelerated video decoding on any apps on your phone.

You're missing at least:
OMX.qcom.video.decoder.avc (which is what Moonlight needs)
OMX.qcom.video.decoder.avc.secure
OMX.qcom.video.decoder.mpeg4
OMX.qcom.video.decoder.h263
OMX.qcom.video.decoder.vp8
OMX.qcom.video.decoder.hevc (which Moonlight uses if you have a GTX 900-series card)

That means you aren't getting hardware acceleration for H.264/AVC, H.265/HEVC, MP4, H.263, and VP8 videos.

Is your device rooted?

**Comment by michal4132** [comment]
Yes

**Comment by cgutman** [comment]
Did you modify anything on your system partition? (particularly media_codecs.xml). And you're sure that you're not running a custom ROM?

**Comment by michal4132** [comment]
![screenshot_20160211-205620](https://cloud.githubusercontent.com/assets/5612283/12988672/113bb4a8-d102-11e5-9fb3-ccaaaf2dda67.png)
I forgot about kernel

**Comment by michal4132** [comment]
I did not change media_codecs files

**Comment by cgutman** [comment]
Something you flashed on your phone changed media_codecs.xml from the stock file located here: https://android.googlesource.com/device/moto/shamu/+/android-6.0.1_r16/media_codecs.xml

I also see that your ROM is several months out of date (current is 6.0.1 MMB29Q) and the kernel you flashed predates the official release of Marshmallow by several months. This can cause ROM and kernel incompatibilities that break applications (one of which being Moonlight, likely Neflix, and YouTube aren't running well or at all).

If you want to use Moonlight, you'll probably need to flash Google's factory image for your phone. I don't think what you have going on easily fixable without reflashing the whole device.

**Comment by michal4132** [comment]
In my media_codecs.xml exist OMX.qcom.video.decoder.avc and others
[media_codecs.xml.txt](https://github.com/moonlight-stream/moonlight-android/files/127069/media_codecs.xml.txt)

**Comment by cgutman** [comment]
Interesting, those must be getting filtered out somewhere because AIDA64 and Moonlight can't see them (probably all other apps too). I assume you've tried rebooting your phone?

**Comment by michal4132** [comment]
Yes

**Comment by michal4132** [comment]
I'm downloading stock 6.0.1

**Comment by cgutman** [comment]
If you want to keep your data, make sure you remove the -w from the flashing script.

**Comment by michal4132** [comment]
Thanks
