### ISSUE TITLE
Moonlight won't quit after exiting a game.

### ISSUE THREAD

**Issue by keem85** [moonlight-stream/moonlight-android#165]
I am using Moonlight-Embedded on Raspbian.. I run this command when running a game:
"moonlight stream <IP> -1080 -60fps -controller.map -app GTA5" This is an example.

But when I quit my games, the moonlight is still running.. I want moonlight to do a "moonlight quit <ip>".. Are there any commands to add to the .sh script in order for it to shut down when the game ends?

**Comment by cgutman** [comment]
This bug belongs on the Moonlight Embedded project if you're still having the issue.
