### ISSUE TITLE
New version

### ISSUE THREAD

**Issue by sage87** [moonlight-stream/moonlight-android#168]
Unable to complete RSTP, or connection terminated immediately.
New version of moonlight on iOS seemed to have started the problem, so updated GFE. Now having problem on android.

**Comment by sage87** [comment]
Okay. I think it was caused by controller drivers for Kinoconsole that I reinstalled around the same time. Reinstalled moonlight on iPad and GFE on the PC, managed to get it all working again.

**Comment by djrockgt** [comment]
What version of GFE and moonlight are you on? I had the same errors as soon as I updated GFE to 2.11. Had to roll back to 2.10 in order to get Android and iPad to stream again.

**Comment by cgutman** [comment]
Fixed in v4.5.4 on Android. iOS version is pending review.
