### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by lateforwork1000** [moonlight-stream/moonlight-android#169]
hay I'm having troubles building this app I'm currently using Androidstudio 1.5.1 and its is giving me this error 

 Execution failed for task ':app:ndkBuild'.
 A problem occurred starting process 'command 'null\ndk-build.cmd'' 

is there a way that I can fix this ? 
thanks

**Comment by cgutman** [comment]
You need to set the 'ndk.dir' variable in your local.properties file.

**Comment by lateforwork1000** [comment]
ok I downloaded the ndk files 
and this is what i tried 

ndk.dir=C\:\\android\\ndk
ndk.dir=C\:\\Users\\desktop\\AppData\\Local\\Android\\ndk
ndk.dir=C\:\\Programs Files\\android\\ndk


Am i doing this correct ?

**Comment by cgutman** [comment]
You need to set the path to the location where the NDK was extracted.

**Comment by lateforwork1000** [comment]
omg thank you

**Comment by muffinmannameistaken** [comment]
would it be possible to add mouse forward and back buttons?

**Comment by ahmedNY** [comment]
i had the sam problem on my mac os x 10.11, android studio 1.5.1
my local.properties
`ndk.dir=/Users/ahmed/Library/Android/sdk/ndk-bundle
sdk.dir=/Users/ahmed/Library/Android/sdk`

I installed ndk using SDK Manager

**Comment by ahmedNY** [comment]
I successfully build the app on MAC the problem was enet files which are located on app/src/main/jni/jnienet/enet where missing and not cloned because they are git submodules !!! using the following commands fixed the problem
`git submodule update --init --recursive`
