### ISSUE TITLE
Motherboard fried with this app on Samsung S6e

### ISSUE THREAD

**Issue by DeXtmL** [moonlight-stream/moonlight-android#172]
This may not sound like a bug, but I do have fried two Galaxy S6 Edge s after using this app for sometime (20~40min per session).  Their damage diagnostics are the same: motherboard fried. 

I didn't get any temperature warning or feel the device is too hot to held at all. This is strange, because when I play some demanding games, those devices work just fine; and the temperature was higher.

Might be worthy to take a look and warn users about this.

(My other handsets dont suffer from this problem, only on S6e)

**Comment by OOPMan** [comment]
I don't though you have enough evidence to lay the blame on Moonlight here.

**Comment by indykoning** [comment]
i think this is impossible to do, if you have a modified kernel or OS it might be possible but not with a simple app. does your OS have something allong the lines of performance mode?
