### ISSUE TITLE
Not able to stream to Android tablet @ 2160p

### ISSUE THREAD

**Issue by RtooDtu** [moonlight-stream/moonlight-android#173]
Getting this error,

"Your PC does not have a supported GPU or GFE for 4k streaming. The stream will be 1080p"

My GPU is a 980Ti and my desktop native resolution is 3840x2160

**Comment by cgutman** [comment]
You need to be running the GFE Beta to stream in 4K. It should now work with the latest GFE beta 2.11 and Moonlight Android v4.5.4.
