### ISSUE TITLE
Failed to start RTSP handshake (Failed to receive ENet packet)

### ISSUE THREAD

**Issue by pushokwhite** [moonlight-stream/moonlight-android#174]
Hello. After clicking on every app in my computer I'm getting such error. Below is a copy from NvStreamer.log. My GFE version is 2.11.1.2 and Moonlight is latest also. Could you please help me with this bug?

#3(I)[2016-03-08 09:58:23,824]{00000EFC} Received ServerType
#4(I)[2016-03-08 09:58:23,825]{00000EFC} Received ServerSetConfig
#5(I)[2016-03-08 09:58:23,825]{00000EFC} 	Require initial refresh before capture => True
#6(I)[2016-03-08 09:58:23,825]{00000EFC} Received ServerSetConfig
#7(I)[2016-03-08 09:58:23,825]{00000EFC} 	Stream outside session => True
#8(I)[2016-03-08 09:58:23,825]{00000EFC} Received session lock state as = Unlocked
#9(I)[2016-03-08 09:58:23,825]{00000EFC} ServerSetEncryptionKey (encoded): 5228...8DE6 [32]
#0(I)[2016-03-08 09:58:23,825]{00000EFC} ServerSetEncryptionKey: 5228...8DE6 [32]
#1(I)[2016-03-08 09:58:23,825]{00000EFC} ServerSetEncryptionKey (key ID): 1091355260
#2(I)[2016-03-08 09:58:23,825]{00000EFC} Received ServerListenForIncomingStreams
#3(E)[2016-03-08 09:58:23,846]{00000EFC} Failed to begin network capture
#4(I)[2016-03-08 09:58:23,846]{00000EFC} Received ServerGetConfig
#5(I)[2016-03-08 09:58:23,847]{00000EFC} Recevied audio channel info from Svc: Channels[2], Mask[0x3]
#6(I)[2016-03-08 09:58:23,847]{00000EFC} Surround: Set Channels in CAD as = 2
#7(I)[2016-03-08 09:58:23,865]{00000EFC} Received ServerDetermineRtspExternalPort -0
#8(I)[2016-03-08 09:58:23,865]{00000EFC} Processed ServerDetermineRtspExternalPort. Got port 48010
#9(I)[2016-03-08 09:58:23,935]{00000EC4} Run: received connect to client connection
#0(I)[2016-03-08 09:58:23,935]{00000EC4} Enet Message Connection Impl: on connect
#1(I)[2016-03-08 09:58:23,937]{00001B98} Handling OPTIONS: ...
#2(I)[2016-03-08 09:58:23,937]{00001B98} Got client header version: 
#3(I)[2016-03-08 09:58:23,937]{00001B98} RtspHandshake::onRtspOptions: handling request: 1
#4(I)[2016-03-08 09:58:23,945]{00001B98} Handling DESCRIBE: ...
#5(I)[2016-03-08 09:58:23,945]{00001B98} Handling DESCRIBE for host ... in delegate ...
#6(I)[2016-03-08 09:58:23,945]{00001B98} RtspHandshake::onRtspDescribe: handling request: 2
#7(E)[2016-03-08 09:58:23,945]{00001B98} Request for redundant CSeq 2 detected
#8(I)[2016-03-08 09:58:23,946]{00001B98} Response code for DESCRIBE: 200
#9(I)[2016-03-08 09:58:24,959]{00000EC4} Run: received disconnect
#0(I)[2016-03-08 09:58:24,959]{00000EC4} Run: dispatching disconnect
#1(I)[2016-03-08 09:58:24,959]{00000EC4} Enet Message Connection Impl: on disconnect

**Comment by Loft23** [comment]
I'm having the same issue.

**Comment by cgutman** [comment]
@Loft23 Can you upload a zip of your "C:\ProgramData\NVIDIA Corporation" folder?

C:\ProgramData is a hidden folder so you may need to turn on hidden folders to see it.

@pushokwhite That "Request for redundant CSeq 2 detected" line is interesting. I definitely don't see that on my machines. Can you run Wireshark on your NVIDIA PC and collect a packet capture while trying to stream with Moonlight?

**Comment by cgutman** [comment]
@Loft23 @pushokwhite Can you try this build and tell me if it works? https://www.dropbox.com/s/9lw1ebebrc9y0nl/moonlight-rtsp-test.apk?dl=0

**Comment by pushokwhite** [comment]
@cgutman I've checked a minute ago, it works like a charm now. Thank you very much ;)
If you still need a packet capture I'll do it tomorrow.
