### ISSUE TITLE
I see steam app , but i have not steam app in nvidia gamestream list

### ISSUE THREAD

**Issue by rampage47** [moonlight-stream/moonlight-android#175]
hi guyz
when i launch moonlight, then i see "steam" and other games. i dont add steam in gamestream list. 
I try to check C:\Users\<Your User Name>\AppData\Local\NVIDIA Corporation\Shield Apps (i cant find steam app here)

i try to reinstall gfe (its does not work);

**Comment by cgutman** [comment]
Try adding the directory that Steam is installed in to the list of game directories to search in GeForce Experience preferences.
