### ISSUE TITLE
with the new app update i cant do the trick that stream the Desktop 

### ISSUE THREAD

**Issue by ikaromoon** [moonlight-stream/moonlight-android#176]
doesnt work anymore if i launch "C:\WINDOWS\System32\mstsc.exe"

**Comment by ikaromoon** [comment]
when i start "C:\WINDOWS\System32\mstsc.exe" on cell with moonlight the screen on cell go black and after 2 sec the stream is closed, anyone can help me?

**Comment by cgutman** [comment]
Does this still happen on the latest GFE update?

**Comment by mrb113** [comment]
Closing - please reopen if still occurring
