### ISSUE TITLE
Gamepad remapping

### ISSUE THREAD

**Issue by ahmedNY** [moonlight-stream/moonlight-android#180]
hi, i just installed moonlight on my android tv topbox, and it worked so smooth. I had 4 controller that i used to play multiplayer games with family and friends, the controllers are generic (Chinese) USB controllers , and i used x360ce to emulate XBOX360 controller.
the 4 direction key is the only key that correctly mapped on moonlight, how to manually map controllers key to XBOX360 as x360ce? do moonlight support 4 controllers?

**Comment by Gershy13** [comment]
Same issue...
