### ISSUE TITLE
still android double mouse issue, with rooted Huawei P8 and moonlight (root)

### ISSUE THREAD

**Issue by soreight** [moonlight-stream/moonlight-android#182]
I rooted my Huawei and still have double mouse, even with the moonlight (root) apk from Google Play store

**Comment by soreight** [comment]
ok. found out, i also have issues with su-binary update. Maybe i have to fix this first. Could it be part of my Problem? I have no other male functions,

**Comment by cgutman** [comment]
Reopen if fixing root access doesn't solve it.
