### ISSUE TITLE
Controller not mapped properly

### ISSUE THREAD

**Issue by Gershy13** [moonlight-stream/moonlight-android#184]
I got a new generic PS3 controller, which is wired, so i dont have that bluetooth issue. But it isnt mapped properly.. only the D Pad works fine... all other buttons either do nothing, or press a different button...

Help?

**Comment by ahmedNY** [comment]
hi,  I think you should had a rooted android and [Sixaxis Controller App](https://play.google.com/store/apps/details?id=com.dancingpixelstudios.sixaxiscontroller&hl=enl) installed  and configured to make the PS3 controller work properly

**Comment by Gershy13** [comment]
its not a real ps3 controller... and my phone isnt rooted... and i dont wanna root it..
its a cheap fake ps3 controller....
