### ISSUE TITLE
No Gamepad Detected on PC

### ISSUE THREAD

**Issue by pico69** [moonlight-stream/moonlight-android#186]
Hi,

I have this message (No Gamepad Detected) when I'm trying to set gamepad settings.
It is not detecting my gamepads.
Not working for Moga Hero Power on bluetooth or for PS2 controller on USB.

Please note that moga hero power is working on android phone.

Regards,
Remi

**Comment by StrikerMan780** [comment]
Getting the same problem.

**Comment by cgutman** [comment]
Is the gamepad connected to your PC or your Android device?

**Comment by StrikerMan780** [comment]
I'm using an NVidia Shield, XBox Controller emulation is not working. When connecting to stream, it doesn't create an XBox controller device or anything on the system, so games don't detect a controller whatsoever.

**Comment by pico69** [comment]
In my case I'm streaming from PC (nvidia geforce experience) to PC (moonlight) Win 10.
All tested gamepads are connected to pc and they are detected by windows system but not by moonlight application.
