### ISSUE TITLE
[FireTV 2] Double cursor ans mouse acceleration?

### ISSUE THREAD

**Issue by blogpirat** [moonlight-stream/moonlight-android#188]
hey dude, im using your (official) firetv app moonlight v4.5.5 and have an issue with games using my mouse connected to the firetv (USB). a second cursor (round) appears and both cursors uses different speed. it seems like mouse acceleration is active (but disabled in windows). this wouldnt be a problem, but there is an invisible wall the cursor couldnt move any further. there some other closed issues matching to my problem: https://github.com/moonlight-stream/moonlight-android/issues/77 but they referring to the android version, not for firetv. 

should i root my firetv?

thank u for the great app by the way ;)

regards
blogpirat

**Comment by genmatrix** [comment]
I believe your problem is what the rooted version addresses. You'll need to be rooted for that version.
