### ISSUE TITLE
Incorrect PIN on pair

### ISSUE THREAD

**Issue by nreck** [moonlight-stream/moonlight-android#189]
When I try to pair my Android device (Samsung S7) with my PC, it says "Incorrect PIN". I have tried to reinstall Nvidia experience, but it didn't help. What do I do?

**Comment by cgutman** [comment]
This is an incompatibility with the new GFE released today. I'll need to figure out what they changed and release a fix.

**Comment by ellisgeek** [comment]
Aah crap and I just upgraded... guess I'll revert?

**Comment by cgutman** [comment]
Fixed in v4.5.6

**Comment by Yellsalott** [comment]
I'm having the same problem, always getting an incorrect pin message back on my Nvidia tablet. Is there any type of work around. With the threats Nvidia throws out about voiding the warrenty if I root my shield, I'm kinda stuck

**Comment by cgutman** [comment]
@Yellsalott Make sure you've updated Moonlight to v4.5.6 via the Play Store.

**Comment by Anthino** [comment]
will the Moonlight app on the apple app store be getting an update to fix this as well?

**Comment by cgutman** [comment]
Yes, we hope to have an update submitted to Apple for review today.

**Comment by Anthino** [comment]
ah yes the apple review process, I really appreciate you supporting this there.

**Comment by Yellsalott** [comment]
Its working now!!! Even BETTER than the game stream the Nvidia hub has.
I'm a happy happy camper. 

    On Thursday, March 31, 2016 8:16 AM, Anthino <notifications@github.com> wrote:
 

 ah yes the apple review process, I really appreciate you supporting this there.—

**Comment by Anthino** [comment]
any way for me to revert GFE to a version I can use while I wait for the IOS update?

**Comment by cgutman** [comment]
@Anthino The iOS update just went live. In the future, you should file iOS bugs on the iOS project https://github.com/moonlight-stream/moonlight-ios instead.

**Comment by Anthino** [comment]
Will do. Im new to GitHub so I wasn't aware it was as organized. Thanks for all the help tho.
