### ISSUE TITLE
This versione of GFE is not currently supported [GFE 2.11.2.46]

### ISSUE THREAD

**Issue by ikaromoon** [moonlight-stream/moonlight-android#190]
![screenshot_20160328-225855](https://cloud.githubusercontent.com/assets/17787858/14090150/007f3ae4-f539-11e5-86a3-b12cf7152e78.png)
![screenshot_20160328-225900](https://cloud.githubusercontent.com/assets/17787858/14090154/05fc65a0-f539-11e5-82aa-80ab04a6a3ce.png)

**Comment by cgutman** [comment]
Fixed in v4.5.6
