### ISSUE TITLE
Sorry for my request , I try put a Gyroscope Compass and Orientation to mouse move same VR device 

### ISSUE THREAD

**Issue by millomoji** [moonlight-stream/moonlight-android#195]
I am new programming with like games vr but be poor and I do not want to disturb you for my request, I try to learning put a Gyroscope Compass and Orientation to mouse move same VR device but it very hard for me ,it always great application but if you have time please help add this future thank you.

**Comment by millomoji** [comment]
I try to swap  Orentation code on touch and test , but i can't run test it tell me this below on Android Studio
Error:Execution failed for task ':app:ndkBuild'.
> A problem occurred starting process 'command 'null\ndk-build.cmd''
How to fig it.

**Comment by cgutman** [comment]
You'll need to download the Android NDK, extract it, and set the ndk.dir variable in your local.properties to point to the NDK directory.

**Comment by millomoji** [comment]
Thank you very much for you help.
and i test agian, but it error 1.
Error:Execution failed for task ':app:ndkBuild'.
> Process 'command 'C:\Users\CDFG\AppData\Local\Android\android-ndk-r11c\ndk-build.cmd'' finished with non-zero exit value 2
thank you.

**Comment by cgutman** [comment]
Can you paste the full output? That error isn't very helpful.

**Comment by millomoji** [comment]
i find solve this [link ](http://stackoverflow.com/questions/28816126/execution-failed-for-task-appcompiledebugndk-when-trying-to-compile-android)
but can't solve .
This all output Thank you.
Information:Gradle tasks [:app:assembleNonRootDebug]
:app:preBuild UP-TO-DATE
:app:preNonRootDebugBuild UP-TO-DATE
:app:checkNonRootDebugManifest
:app:prepareNonRootDebugDependencies
:app:compileNonRootDebugAidl UP-TO-DATE
:app:compileNonRootDebugRenderscript UP-TO-DATE
:app:generateNonRootDebugBuildConfig UP-TO-DATE
:app:generateNonRootDebugAssets UP-TO-DATE
:app:mergeNonRootDebugAssets UP-TO-DATE
:app:generateNonRootDebugResValues UP-TO-DATE
:app:generateNonRootDebugResources UP-TO-DATE
:app:mergeNonRootDebugResources UP-TO-DATE
:app:processNonRootDebugManifest UP-TO-DATE
:app:processNonRootDebugResources UP-TO-DATE
:app:generateNonRootDebugSources UP-TO-DATE
:app:ndkBuild
[armeabi-v7a] Compile thumb  : evdev_reader <= evdev_reader.c
[armeabi-v7a] Executable     : libevdev_reader.so
[armeabi-v7a] Install        : libevdev_reader.so => src/main/jniLibs/armeabi-v7a/libevdev_reader.so
[armeabi-v7a] Compile thumb  : jnienet <= jnienet.c
src/main/jni/jnienet/jnienet.c:1:23: fatal error: enet/enet.h: No such file or directory
 #include "enet/enet.h"
                       ^
compilation terminated.
make: *** [build/intermediates/ndk/obj/local/armeabi-v7a/objs/jnienet/jnienet.o] Error 1
:app:ndkBuild FAILED
Error:Execution failed for task ':app:ndkBuild'.
> Process 'command 'C:\Users\CDFG\AppData\Local\Android\sdk1\ndk-bundle\ndk-build.cmd'' finished with non-zero exit value 2
Information:BUILD FAILED
Information:Total time: 1.195 secs
Information:1 error
Information:0 warnings
Information:See complete output in console

**Comment by millomoji** [comment]
this console thank you.

Executing tasks: [:app:assembleNonRootDebug]

Configuration on demand is an incubating feature.
Incremental java compilation is an incubating feature.
:app:preBuild UP-TO-DATE
:app:preNonRootDebugBuild UP-TO-DATE
:app:checkNonRootDebugManifest
:app:prepareNonRootDebugDependencies
:app:compileNonRootDebugAidl UP-TO-DATE
:app:compileNonRootDebugRenderscript UP-TO-DATE
:app:generateNonRootDebugBuildConfig UP-TO-DATE
:app:generateNonRootDebugAssets UP-TO-DATE
:app:mergeNonRootDebugAssets UP-TO-DATE
:app:generateNonRootDebugResValues UP-TO-DATE
:app:generateNonRootDebugResources UP-TO-DATE
:app:mergeNonRootDebugResources UP-TO-DATE
:app:processNonRootDebugManifest UP-TO-DATE
:app:processNonRootDebugResources UP-TO-DATE
:app:generateNonRootDebugSources UP-TO-DATE
:app:ndkBuild
[armeabi-v7a] Install        : libevdev_reader.so => src/main/jniLibs/armeabi-v7a/libevdev_reader.so
[armeabi-v7a] Compile thumb  : jnienet <= jnienet.c

src/main/jni/jnienet/jnienet.c:1:23: fatal error: enet/enet.h: No such file or directory
 #include "enet/enet.h"
                       ^
compilation terminated.
make: *** [build/intermediates/ndk/obj/local/armeabi-v7a/objs/jnienet/jnienet.o] Error 1

:app:ndkBuild FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:ndkBuild'.
> Process 'command 'C:\Users\CDFG\AppData\Local\Android\sdk1\ndk-bundle\ndk-build.cmd'' finished with non-zero exit value 2

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 1.302 secs

**Comment by millomoji** [comment]
Thank you for help.
I complete build .
When download Zip file , it not include file in net folder .
Thank you.
