### ISSUE TITLE
Rtsp handshaking 404 issue since 28th March geforce experience update

### ISSUE THREAD

**Issue by jscoys** [moonlight-stream/moonlight-android#196]
Hi guys,

I'm pretty sure you know that since the 28th, following a geforce experience update, we are no longer able to use moonlight to stream games. We've got a 404 error when the rtsp handshake is tried. Seems that GFE changed it, so you have to adapt yours?

For those that updated to the latest GFE like I did, here is the link to the latest WORKING version of GFE.

http://us.download.nvidia.com/GFE/GFEClient/2.9.1.35/GeForce_Experience_v2.9.1.35.exe

RTSP Setup Request failed 404.
Failed to start RTSP handshake with latest GFE. Please help!﻿

**Comment by cgutman** [comment]
Make sure you've updated to Moonlight Android v4.5.6. This has support for the latest GFE.

**Comment by aletepe** [comment]
For me it is still failig. It seems like GFE devs released several times in a short period of time, because the desktop version of GFE that I have is v2.11.2.55. I'm using moonlight for android v4.5.6 from the amazon app store.

**Comment by cgutman** [comment]
Try updating to GFE 2.11.2.65. http://us.download.nvidia.com/GFE/GFEClient/2.11.2.65/GeForce_Experience_v2.11.2.65.exe

**Comment by cmz1675** [comment]
Are all Platforms upgraded? Like Rasberry Pi/Repository edition?

**Comment by cgutman** [comment]
Everything is updated now.
