### ISSUE TITLE
RTSP Handshake Failed: 403 error only when trying to stream 4k

### ISSUE THREAD

**Issue by Diabolacal** [moonlight-stream/moonlight-android#197]
Hi Guys

Was tearing my hair out with this last night thinking I had a network/port issue when I was getting this error, dropped the stream on the device to 1080p and it worked fine.

So some details;

Geforce Experience 2.11.2.55
Operating System:	Windows 10 Pro, 64-bit
DirectX version:	12.0 
GPU processor:		GeForce GTX 680
Driver version:		364.72
Direct3D API version:	12
Direct3D feature level:	11_0
Dedicated video memory:	4096 MB GDDR5

Streaming to a BlackBerry Priv running moonlight 4.5.6 over wifi, doing a standard internet speedtest from the priv gives a speed well in excess of 100 Mbit/s

Handshake error occurs on any 4k option selected 30fps and 60fps, dropping to 1080p immediately resolves

any help appreciated

**Comment by cgutman** [comment]
Yes, that's the error code when 4K is requested but not supported by GFE or the PC's GPU. I tried to write checks that would catch it and switch back to 1080p, but I could never manage to get it robust enough to survive more than a couple GFE updates.

You can try updating to the beta GFE which may have working 4K streaming on your setup.

**Comment by Diabolacal** [comment]
Ah nice, cheers for the reply.

So basically try the beta and if that doesnt work I guess I could try some older versions of GFE as well?

**Comment by cgutman** [comment]
I doubt older versions would work in 4K if the beta doesn't. I'm not aware of any 4K regressions in the current version of GFE.

**Comment by Diabolacal** [comment]
GFE Beta worked a treat - many thanks!
