### ISSUE TITLE
No cursor on Moonlight stream when there is no mouse plugged into the PC.

### ISSUE THREAD

**Issue by aoisoraa** [moonlight-stream/moonlight-android#198]
In the past, even if I had no mouse plugged in, the cursor would appear on the desktop stream handled by Moonlight.

Could you please look into this? Thank you very much. I depend on your program very much and I need the cursor haha.

To reproduce, put computer to sleep. Unplug mouse, wake on LAN and then launch the stream. When the Moonlight stream loads, you are able to move the cursor but the actual visual cursor will be on the screen. It is missing and makes operating the desktop difficult.

If you plug in a mouse, then the cursor reappears. You can keep plugging and unplugging the mouse to the PC and the issue will happen every single time. The cursor on the stream will disappear.

Could you possibly make Moonlight take control of the cursor as well since it appears as a sound device as well?

**Comment by cgutman** [comment]
Unfortunately this seems to have happened a few GeForce Experience updates ago. I found that turning on Mouse Keys on the host PC will force a cursor to display.

**Comment by aoisoraa** [comment]
I don't have a numpad so that solution doesn't work for me. Do you know which version of GFE it was still working on? I'll just downgrade to that one. Thanks.

**Comment by jmarianski** [comment]
Isn't that a Windows 10 thing? My mouse seems to disappear when I have no mouse plugged in.

**Comment by cgutman** [comment]
It's an OS change in all versions of Windows after Win8.
