### ISSUE TITLE
Connection Terminated on App

### ISSUE THREAD

**Issue by Croanoation** [moonlight-stream/moonlight-android#199]
Hello, I recently installed the Moonlight stream app on my Samsung Galaxy s6, I have managed to pair it to my computer, and it seems to launch steam when I choose it in the app but after a couple seconds after the rtsp handshake, the connection is terminated

**Comment by cgutman** [comment]
Can you try uninstalling GeForce Experience on your PC and downloading the latest installer from geforce.com?

**Comment by Croanoation** [comment]
That worked like a charm, Thank you so much! :+1:
