### ISSUE TITLE
Starting audio stream...Segmentation fault

### ISSUE THREAD

**Issue by acranglesim** [moonlight-stream/moonlight-android#200]
Installed via package on Rpi Jessie
ssh onto Rpi, run moonlight stream -1080 -30fps -app Steam
Initializing platform...done
Resolving host name...done
Starting RTSP handshake...done
Initializing control stream...done
Initializing video stream...done
Initializing audio stream...done
Initializing input stream...done
Starting control stream...done
Starting video stream...done
Starting audio stream...Segmentation fault

Tried a clean install of nvidia drivers, still no luck, any ideas?

**Comment by cgutman** [comment]
This isn't the right project to file issues against for Moonlight Embedded. This is the Android project. File your bug on https://github.com/irtimmer/moonlight-embedded
