### ISSUE TITLE
compile help

### ISSUE THREAD

**Issue by muffinmannameistaken** [moonlight-stream/moonlight-android#202]
hay I'm having some problems compiling I get this error when doing so

Error:Execution failed for task ':app:ndkBuild'.
> Process 'command 'C:\Users\thiscomputer\Downloads\android-ndk-r10e\ndk-build.cmd'' finished with non-zero exit value 2

any ideas how to fix this ?

**Comment by ahmedNY** [comment]
make sure you have android NDK installed. and make sure you had fetched enet which is located on moonlight-android/app/src/main/jni/jnienet/enet
you cat fetch enet by executing 
`git submodule update --init --recursive `

**Comment by muffinmannameistaken** [comment]
ok, ndk files are installed i can rebuild the older versions moonlight but not the newer one, when i go to moonlight-android/app/src/main/jni/jnienet/enet not sure what to do next

**Comment by muffinmannameistaken** [comment]
o nvm the enet files are not included

**Comment by ahmedNY** [comment]
"enet" is 3rd party library in which moonlight depends on, make sure enet files does exist before compiling the app, if enet doesn't exist try execute `git submodule update --init --recursive` in the root directory of the app to download enet files
