### ISSUE TITLE
Regarding Sony ATVs

### ISSUE THREAD

**Issue by pwnerdreamz** [moonlight-stream/moonlight-android#204]
Hi, I own a Sony Android TV and the latency on the high side(30-50ms).There is almost 0 latency due to network since i use ethernet. Also I use the h.264 decoder because the h.265 is "broken". Is there any way to fix the h.265 decoder because I am able to watch HEVC content on the default video player(Sony's one) or minimize the latency on the AVC decoder? I can post logcats and any information that you may need.

**Comment by Kaan88** [comment]
For me the hevc works on 720p and 4k but crashes on 1080p, both 30 and 60 fps. Any ideas?

**Comment by cgutman** [comment]
Fixed in v5.6.1
