### ISSUE TITLE
Moonlight on iPhone 6 can't find my PC

### ISSUE THREAD

**Issue by FitzcairnHS** [moonlight-stream/moonlight-android#206]
Hi,

Above all i checked all the tutorial setup guide instruction and the troubleshooting issues to try to resolve the problem by myself and it didnt work.

So, i have i an iPhone 6, a PC with GTX 980, the last NVIDIA and GFE drivers up to date.

I checked the NVIDIA services are all UP.

I checked my IPCONFIG

But Moonlight don't find my PC and if i add the IP HOST manually it can't find host neither.

I have to mention that the SHIELD tab in GFE says i'm connected and ready to stream BUT if go in the preferences tab there is no SHIELD option but only Generalites/Jeux/Shadowplay (i have a french version).

Any advices ?

Thanks !

PS : I just bought a HOMIDO Headset VR and want to play my game stream with Moonlight. I tried with KINOVR but it's full of pixels that's awful.

**Comment by jeid64** [comment]
What is your GFE version? Also, the iOS bug tracker is here. https://github.com/moonlight-stream/moonlight-ios

**Comment by cgutman** [comment]
Please move this to the iOS bug tracker if this is still a problem.
