### ISSUE TITLE
Wake on lan not working

### ISSUE THREAD

**Issue by miguelans** [moonlight-stream/moonlight-android#207]
The wake on lan feature is not working and seems a problem with moonlight because with another app it works ok. What details do you need? I'm using a oneplus one with oxygen os and the app that is working is called Wake On Lan from Mike Webb.

**Comment by cgutman** [comment]
Are you trying to wake from the Internet or from your local network?

**Comment by miguelans** [comment]
Local network!

**Comment by miguelans** [comment]
Awesome work,  by the way!  :)

**Comment by cgutman** [comment]
Fixed by https://github.com/moonlight-stream/moonlight-common/commit/8c0af98ae102b7f0fe18554ec5f9496e94b83ade
