### ISSUE TITLE
Android 6.0.1 N910C codec issue

### ISSUE THREAD

**Issue by spider2077** [moonlight-stream/moonlight-android#208]
OMX.qcom.video.decoder.avc 
OMX.qcom.video.decoder.avc.secure
OMX.qcom.video.decoder.mpeg4
OMX.qcom.video.decoder.h263
OMX.qcom.video.decoder.vp8
OMX.qcom.video.decoder.hevc

none of this codecs are preasent int the 6.0.1 update for the note 4 is there any way to fix this without reverting to 5.1.1

**Comment by cgutman** [comment]
Can you download the AIDA64 app and post sceenshots of all of the codecs on your codecs page? You may need to upload multiple screenshots to get them all.

**Comment by cgutman** [comment]
Reopen if this hasn't been resolved.
