### ISSUE TITLE
Mouse input not working on 4.5.7+

### ISSUE THREAD

**Issue by DakuTree** [moonlight-stream/moonlight-android#209]
After updating to Moonlight 4.5.7 I've been unable use the mouse. The cursor won't move & clicking also won't work.
The bug seems to a problem with older android versions. I tested on a device running 6.0 and it runs fine, but on a device running 4.4 the problem occurs.
Reverting to 4.5.6 seems to fix the issue.

**Comment by cgutman** [comment]
This is fixed in 4.5.7.2. Thanks for reporting.
