### ISSUE TITLE
I've got an error code 521

### ISSUE THREAD

**Issue by Banora** [moonlight-stream/moonlight-android#210]
I can pair my samsung note 5 to my pc and also able to view my games list. But when i try to run it it gives me this error gfe error: streaming session has failed due to a streaming error (error code 521)
Any help is appreciated. 
Thanks in advance.

**Comment by Stealch** [comment]
I have same problem: GFE Error: Streaming session has failed due to a streaming error. (Error code 521) on android and pc. Game list are visible on both devices, but that is all... all services on powerfull PC is running, pair succesfull. The devices are in same network, no firewall, no NAT.
