### ISSUE TITLE
Connection terminated

### ISSUE THREAD

**Issue by davidgamer1** [moonlight-stream/moonlight-android#211]
I always see this error, please help me :(

I checked requirments and everything was ok and idk it wont work still :(

**Comment by indykoning** [comment]
same here, to go more indepth: the pc showed up automatically, when i try to launch any game it shows the shield bakground on the pc, starts up game, quickly after that closes it again and on my phone give the notification "connection terminated"

**Comment by Guastaferro98** [comment]
Hi,
I have the same issue: when I try to start a game, it appears a black screen with the notification ''connection terminated'' on my android phone.
I have rooted version, GE 2.11.3.5 and 800M series.
But 800M GF series is supported?

**Comment by Wolvman92** [comment]
Same thing here. Non-rooted S6 Edge. Just can't launch a single app without it hitting "connection terminated" right after it loads the audio portion.
