### ISSUE TITLE
Emulate a touch mouse on PC, instead of just moving the cursor around manually?

### ISSUE THREAD

**Issue by Kornstalx** [moonlight-stream/moonlight-android#212]
Other apps like Teamviewer allow touch-emulation when remoting into a PC, so that when clicking with your finger the cursor on PC is instantly moved to the position and clicked. Moonlight doesn't do this. It has gestures for other mouse buttons and keyboard (triple finger press), but nothing for instantly popping the cursor to where you press your finger.

I like to play games that involve moving cards or puzzle pieces, and it's frustratingly difficult to do so having to manually scroll a mouse cursor around on the tablet.

Is there any way to remedy this? Perhaps some touch-driver on the PC that translates presses from the tablet to mouse actions on the computer? I've found other streaming apps that have such functionality but they don't use nVidia's protocol (which is incredibly faster).

**Comment by jeid64** [comment]
Sadly, nvidia only support relative mouse inputs, not absolute like you're requesting. 

I have a branch of moonlight-android that hackily "supports" absolute input by keeping track of the delta, but the mouse can become desynced, so you have to "reset" it by going to 0,0 sometimes. I mostly use it for Hearthstone. I don't think it's a good idea for Moonlight-android to officially have absolute inputs as it's always going to be buggy.

**Comment by BetaLeaf** [comment]
Very neat @jeid64. Where can I find a compiled APK using your fork?

**Comment by JoydeepMallick** [comment]
Is there any possibility of getting absolute input. I notice compared to other remote desktop softwares moonlight feels extremely smooth on slower wifi connections too just the issue is the point mouse feature, which will come in handy more for photoshop which I sometimes try to use to draw curve lines by hand which are tough by mouse or pen tool.
