### ISSUE TITLE
RTSP handshake Problem

### ISSUE THREAD

**Issue by Manfre98** [moonlight-stream/moonlight-android#217]
Hello, I'm Marco, 

Before all my problems i wan't to say sorry for my English; English isn't my first language. 

What i have done so far:
- Checked UPD port 48010 in my windows firewall. The port is by default open for nvstreamer.exe and is named on the firewall "SHIELD Streaming NvStreamer UDP Exception".
- Check if the nvidia services are running.
- Try uninstalling the driver and reinstall them using the "clean install".
- Setting up my Nexus 6 with moonlight-android.
- Disabled the firewall.

Information about my stuff:
- Windows 7 Professional 64-bit (wired connected).
- NVidia Geforce Experience version: 2.11.2.67
- Moonlight version: 4.6.7.2
- Graphic Card: Nvidia GeForce GTX 970 (driver: 364.72).

It's all ok...
![screenshot_20160426-203919](https://cloud.githubusercontent.com/assets/18686229/14832915/cff264ac-0bfc-11e6-8b82-d67208a48076.png)

Until this happens:
![screenshot_20160426-203941](https://cloud.githubusercontent.com/assets/18686229/14832989/2c94e130-0bfd-11e6-870c-1caaf7978c87.png)

Followed by this:
![screenshot_20160426-222200](https://cloud.githubusercontent.com/assets/18686229/14833045/8e098790-0bfd-11e6-8777-f1d2fad4becd.png)

Has anybody an idea?
Please help me.

**Comment by cgutman** [comment]
Does this still happen on the latest GFE and Moonlight versions?

**Comment by Wully616** [comment]
I'm getting the same problem here. Trying to stream in my local network, I get the "Unable to connect to UDP port 48010" error, when trying to stream from my Windows 10 Machine.

It looks like its something specific to Windows 10. As it worked streaming with the same driver and geforce experience versions as below on my girlfriends Windows 7 x64 machine with a GTX 660Ti in the same local network.


Details:

GPU: GTX 970
OS: Windows 10 Pro x64
Nvidia Drivers: 368.39
Nvidia Geforce Experience: 2.11.3.5
Mobile: Oneplus One
Moonlight: 4.5.10


I've checked the following too:

- Disabled Windows Firewalls, Private and public.

- Check if the nvidia services are running.

- Try uninstalling the driver and reinstall them using the "clean install".

**Comment by cgutman** [comment]
Do you have any anti-virus or other security software (even disabled)?

**Comment by Wully616** [comment]
No antivirus other that Windows Defender. I've tried disabling it and tried again but no change.

**Comment by Wully616** [comment]
I set up an adhoc wifi network on my windows 10 machine and connected to that with my android phone and was able to connect and stream without the UDP error.

It looks like it may be something to do with my motherboards network adapter or the drivers.
For anyone curious its a Killer E2200 Gigabit Ethernet Controller. It's an on motherboard adapter. My motherboard is a Gigabyte G1 Sniper M5.

I'm going to try and wipe the network drivers completely and reinstall them to see if it fixes it somehow.

**Comment by S-Gr4y** [comment]
I have the same issue and the same ethernet controller. I plugged in an USB ethernet dongle, disabled the motherboard one and it worked.
It's a bit sad I've to use such a trick to use this awesome software, I wonder what's the real isssue with killer network software?

**Comment by CoREse** [comment]
Same issue here. I shut my shadowsocks down in my phone, it is solved.
