### ISSUE TITLE
Enable usage of controller that is on server PC rather a controller paired to the streaming client?

### ISSUE THREAD

**Issue by jack-fin** [moonlight-stream/moonlight-android#218]
I am not sure if this is possible but I have a feature request.

I really like using the Steam Controller. With some DLL changes it is possible to use the Steam Controller on a Shield TV. However, those DLL changes end up breaking surround sound. Part of this setup involves using an application called VirtualHere which essentially makes it so that you can have the Steam Controllers USB connection, while plugged into the Android device really be paired to the streaming PC.

If Moonlight could have an option to "use controller connected to server PC" or something similar it should be possible to stream a game without needing to make DLL changes, forcing the included controller to not be used as player 1, and having a side effect of breaking surround sound. This would make it possible to stream surround sound audio using Moonlight.

**Comment by CodeGiver123** [comment]
I guess a way to ask this which would make more sense is the option to not have Gamestream bind a Shield controller or other input device to controller 1 automatically. That is the root of this problem, that Gamestream force binds a controller.

**Comment by MichaelMKenny** [comment]
Try renaming rxinput.dll in C:\Program Files\NVIDIA Corporation\NvStreamSrv to something like rxinput.dll.old on your host machine.

**Comment by CodeGiver123** [comment]
That does work for disabling the binding of Shield controller. It has the side effect of breaking surround sound though, I am hoping that it'd be possible to have surround sound, while having Gamestream not bind any controllers automatically.
