### ISSUE TITLE
Double mouse issue on root

### ISSUE THREAD

**Issue by extremeGEgaming** [moonlight-stream/moonlight-android#221]
I got the root version of the app (4.5.7) and I still got double cursors showing up. I am currently running android 5.1.1 rooted (kingroot) on a xperia z2. I tested it with many mouses (since some with side buttons are also seen as keyboards by android), but to no avail. It's disturbing since I can't move the cursor continuously, being blocked by the edge of the screen.

**Comment by extremeGEgaming** [comment]
I suppose the scale is wrong since the position of the two cursours doesn't align

**Comment by cgutman** [comment]
If you're still having this issue, it means Moonlight isn't able to get root access on your device. Do you get a root access prompt when streaming?

**Comment by extremeGEgaming** [comment]
Yes, I allowed it through the prompt and is set to be always allowed

**Comment by extremeGEgaming** [comment]
I also tried usb via ethernet tunnel to workaround the problem, but coincidentally that doesn't work either. I'm not sure if the fault is in my usb host or not, if the way you capture the raw mouse feedback from the usb is the same, the problem could be linked.
