### ISSUE TITLE
Failed to start RTSP handshake - Failed to receive ENet packet / Works Perfectly over WIFI

### ISSUE THREAD

**Issue by BSSGamesBond** [moonlight-stream/moonlight-android#222]
It works perfectly over wifi, I just cant seem to get it to work over internet.

I opened all the necessary ports, I can even see all the apps but it fails...

I noticed another thread ( which is closed ) with the same problem, there was a apk on a dropbox that must have worked for that person.
I tried it but it gives me that "incorrect pin number" problem..

Can anyone help?

**Comment by extremeGEgaming** [comment]
Maybe your internet provider/your switch blocks those certain ports or you have a pppoe connection?

**Comment by vrxiaochouyu** [comment]
i have same issue！but it happend in sometimes. i must restart some times to handshake.
can you tell me some way to solution？
