### ISSUE TITLE
Side by Side Image [Request]

### ISSUE THREAD

**Issue by milagem** [moonlight-stream/moonlight-android#223]
Please implement side by side image option, something like this:

![maxresdefault](https://drive.google.com/uc?export=view&id=0BzJeSNfi2mJjUUNMT0liNzIwUzg)

With image repeated side by side is  possible use software/games in a virtual reality headset. 
Thanks.

**Comment by kashban** [comment]
+1

Basicly it is working with TriDef on the PC but the image aspect ratio is off because the width of the single image isn't cut into half. Unfortunately there seems to be no way to tell TriDef to sort that out, so perhaps Moonlight can do something about it.

**Comment by kamuikun42** [comment]
+1

Please add support to process the image from the PC - be it 2D or half side-by-side 3D, and display it on the phone in side-by-side for HMDs (such as the Google Cardboard compatible HMDs, or anything really, no need for head-tracking or lense deformation - though this would be great!), with options to adjust the scale and separation (or using the cardboard API that take care of that I suppose).

I'm currently watching 3D movies from my PC using Stereoscopic Player (Windows) that do just that, but it would be awesome to have the full Windows desktop support in any apps and games in both 2D and 3D.
