### ISSUE TITLE
Video working but audio is on PC and no controller input

### ISSUE THREAD

**Issue by kuckles1** [moonlight-stream/moonlight-android#224]
Hello,

So I'm having an issue with my Ouya. I will start a game with Moonlight (Steam or any other game) and it all loads fine. The video is displayed on the Ouya but the sound is on my PC and the Ouya controller will not respond. The mouse touchpad on the controller does function, however. Once in a while Moonlight will function perfectly but 99% of the time it does not. I have not been able to replicate the actions to make it work. It used to work flawlessly but after an update, I believe, I started to have these issues.

**Comment by cgutman** [comment]
Can you try reinstalling GeForce Experience?
