### ISSUE TITLE
Unable to connect, check port and firewall.

### ISSUE THREAD

**Issue by ShawNMusliM** [moonlight-stream/moonlight-android#228]
I am unable to connect to my PC. I have reinstalled/rebooted both my computer and my android. Reinstalled moonlight. Tried to connect manually with my local IP address. Tried connecting through my external IP address. Made sure my experience was up to date. Made sure I had compatible games. Made sure the box to allow game streaming was checked. Deleted my anti virus and turned off my firewall.

This just doesnt work for me.

**Comment by cgutman** [comment]
What GPU is in your computer? Can you check if 'NVIDIA Streamer Service' is running in Task Manager?

**Comment by ShawNMusliM** [comment]
I have checked that NVSteamservice is running and it is. My GPU is a 750.

**Comment by ShawNMusliM** [comment]
I am having issues with moonlight, remotr, konito, and steams in home streaming. Not sure what is going on. Hoping someone can help me.

**Comment by cgutman** [comment]
What do you get if you try to access this page in your PC's web browser: http://127.0.0.1:47989/serverinfo

**Comment by ShawNMusliM** [comment]
<?xml version="1.0" encoding="UTF-16"?><root protocol_version="0.1" query="serverinfo" status_code="200" status_message="OK"><AuthenticationType>1</AuthenticationType><ConnectionState></ConnectionState><CurrentClient>1</CurrentClient><ExternalIP>104.181.159.106</ExternalIP><GfeVersion>2.11.3.5</GfeVersion><HttpsPort>47984</HttpsPort><LocalIP>127.0.0.1</LocalIP><LocalIPs><Address>192.168.1.73</Address></LocalIPs><MaxLumaPixelsH264>529711328</MaxLumaPixelsH264><MaxLumaPixelsHEVC>125337600</MaxLumaPixelsHEVC><Mode>0</Mode><PairStatus>0</PairStatus><ServerCapability>55</ServerCapability><ServerCodecModeSupport>65539</ServerCodecModeSupport><ServerColorSpaceSupport>2</ServerColorSpaceSupport><SupportedDisplayMode><DisplayMode><Height>2160</Height><RefreshRate>60</RefreshRate><Width>3840</Width></DisplayMode><DisplayMode><Height>2160</Height><RefreshRate>30</RefreshRate><Width>3840</Width></DisplayMode><DisplayMode><Height>1080</Height><RefreshRate>60</RefreshRate><Width>1920</Width></DisplayMode><DisplayMode><Height>1080</Height><RefreshRate>30</RefreshRate><Width>1920</Width></DisplayMode><DisplayMode><Height>720</Height><RefreshRate>60</RefreshRate><Width>1280</Width></DisplayMode><DisplayMode><Height>720</Height><RefreshRate>30</RefreshRate><Width>1280</Width></DisplayMode></SupportedDisplayMode><accountId></accountId><appversion>7.1.280.3</appversion><currentgame>0</currentgame><gamelistid>bff47d182b57919d98d931dd56df6ebc</gamelistid><gputype>GeForce GTX 750 Ti</gputype><hostname>ABDURRAHMAN-PC</hostname><mac>00:00:00:00:00:00</mac><numofapps>4</numofapps><resyncSuccessful>0</resyncSuccessful><state>MJOLNIR_STATE_SERVER_AVAILABLE</state><uniqueid>65f3fe29-35eb-45fc-a884-6cbf14f7b9a1</uniqueid></root>

**Comment by cgutman** [comment]
Ok, do you get that same page if you access it like: http://192.168.1.73:47989/serverinfo in your PC's browser? If so, try it in your phone's browser too.

**Comment by ShawNMusliM** [comment]
<?xml version="1.0" encoding="UTF-16"?><root protocol_version="0.1" query="serverinfo" status_code="200" status_message="OK"><AuthenticationType>1</AuthenticationType><ConnectionState></ConnectionState><CurrentClient>1</CurrentClient><ExternalIP>104.181.159.106</ExternalIP><GfeVersion>2.11.3.5</GfeVersion><HttpsPort>47984</HttpsPort><LocalIP>192.168.1.73</LocalIP><LocalIPs><Address>192.168.1.73</Address></LocalIPs><MaxLumaPixelsH264>529711328</MaxLumaPixelsH264><MaxLumaPixelsHEVC>125337600</MaxLumaPixelsHEVC><Mode>0</Mode><PairStatus>0</PairStatus><ServerCapability>55</ServerCapability><ServerCodecModeSupport>65539</ServerCodecModeSupport><ServerColorSpaceSupport>2</ServerColorSpaceSupport><SupportedDisplayMode><DisplayMode><Height>2160</Height><RefreshRate>60</RefreshRate><Width>3840</Width></DisplayMode><DisplayMode><Height>2160</Height><RefreshRate>30</RefreshRate><Width>3840</Width></DisplayMode><DisplayMode><Height>1080</Height><RefreshRate>60</RefreshRate><Width>1920</Width></DisplayMode><DisplayMode><Height>1080</Height><RefreshRate>30</RefreshRate><Width>1920</Width></DisplayMode><DisplayMode><Height>720</Height><RefreshRate>60</RefreshRate><Width>1280</Width></DisplayMode><DisplayMode><Height>720</Height><RefreshRate>30</RefreshRate><Width>1280</Width></DisplayMode></SupportedDisplayMode><accountId></accountId><appversion>7.1.280.3</appversion><currentgame>0</currentgame><gamelistid>bff47d182b57919d98d931dd56df6ebc</gamelistid><gputype>GeForce GTX 750 Ti</gputype><hostname>ABDURRAHMAN-PC</hostname><mac>44:8A:5B:81:13:BB</mac><numofapps>4</numofapps><resyncSuccessful>0</resyncSuccessful><state>MJOLNIR_STATE_SERVER_AVAILABLE</state><uniqueid>65f3fe29-35eb-45fc-a884-6cbf14f7b9a1</uniqueid></root>

**Comment by cgutman** [comment]
Does that work last URL work on your phone too (on the same network as your PC)?

**Comment by ShawNMusliM** [comment]
Yes it works.

**Comment by ShawNMusliM** [comment]
Man this app looked so promising >.< I thought I was actually going to be able to play ds2 at work with a bluetooth connected xbox 360 controller on my android >.<

**Comment by ShawNMusliM** [comment]
Ok... idk what just happened but now I see my pc.

**Comment by ShawNMusliM** [comment]
Did that link do nething? Looks to me like all it did was show me my specs.

**Comment by cgutman** [comment]
It's one of the pages that Moonlight accesses in order to determine if your PC is "online". Are you able to pair and stream now that you see your PC?

**Comment by ShawNMusliM** [comment]
Yup. No problem.

**Comment by ShawNMusliM** [comment]
I still dont understand what fixed it though.

**Comment by ShawNMusliM** [comment]
Next is figuring out how to do this over my data while not connected to my local router.

**Comment by cgutman** [comment]
The setup guide has information on the ports you'll need to forward: https://github.com/moonlight-stream/moonlight-android/wiki/Setup-Guide#streaming-over-the-internet

**Comment by ShawNMusliM** [comment]
Do you know why going to those two links solved my issue?

**Comment by ShawNMusliM** [comment]
Will I have to do something similar when I attempt to connect via my data plan?

**Comment by cgutman** [comment]
Probably not. I'm not sure why it's working now and it wasn't before. GeForce Experience is a complicated piece of software and sometimes weird interactions happen with other settings/software.

**Comment by ShawNMusliM** [comment]
Gotcha, thanks alot.

**Comment by ShawNMusliM** [comment]
Any chance you have a link on how to use an xbox360 controller with this app on android?

**Comment by cgutman** [comment]
Is it plugged into your computer or your phone?

**Comment by ShawNMusliM** [comment]
Im bluetooth to my phone.

**Comment by ShawNMusliM** [comment]
I guess im going to have to buy a usb wap thing to do that.

**Comment by ShawNMusliM** [comment]
My goal is to take my wireless xbox controller and my phone to work and remote into my desktop to play ds2.

**Comment by cgutman** [comment]
Assuming your phone supports USB OTG, you'll need a USB OTG adapter and an Xbox 360 wireless receiver (preferably an official Microsoft one). Alternatively, you could get a Bluetooth controller made for Android devices.
