### ISSUE TITLE
Unable to connect to the specified computer

### ISSUE THREAD

**Issue by lahesis333** [moonlight-stream/moonlight-android#234]
Please, help! I can not connect my phone to a computer. The moonlight appears the error message "Unable to connect to the specified computer. Make sure the required ports are allowed through the firewall". A week ago, I was able to connect the phone to a computer. I created a rule in the eset antivirus at the correct address and it worked. But now I can not connect again. I tried to create a rule in the firewall, but it does not help. Updating drivers and nvidia experience no result (((updated moonlight program does not help ... What could be the reason? What am I doing wrong? If you connect program FreePie IMU through wi-fi or cable so good. Telephone and immediately finds a computer connected. And a moonlight does not want to. Please do not pass by the help!

**Comment by LuizFeitosa** [comment]
I'm having the same problem.

**Comment by cgutman** [comment]
Can you see if "NVIDIA Streaming Service" is running on your computer?

Try accessing http://127.0.0.1:47989/serverinfo from your PC. If that works, also try accessing http://<your PC IP address>:47989/serverinfo from your Android device.

**Comment by evildog1** [comment]
I have the same problem. I cleared data from Moonlight and it works again.

**Comment by SuperLaserX** [comment]
cgutman: When I try to go to http://localhost:47989 I get no connection. I'm running the latest 2.11.4.0 GFE. I was trying another version of moonlight that tried to connect in the 47k port range, but nothing is binding there. Did something change? Do I need to tweak a setting? I can't even use a local copy of moonlight to connect to myself.

**Comment by TheCaptainClown** [comment]
I think i just randomly solved the problem, lets see....
I opened the Services window through the Task Manager (im running windows 10) and scrolled down to 
NVIDIA Streamer Network Service (with the description: Network service for SHIELD streaming) then right click restart , and it worked for me. Feel free to try :)

**Comment by Lusid90** [comment]
Install this driver "368.39-desktop-win10-64bit-international-whql"

**Comment by leannecrow** [comment]
I was having the same issue and I had a feeling not being on the same gateway might be messing it up. So I grabbed another router lying around, connected that with the PC on LAN cable and phone via Wifi. Presto it worked.

Before my desktop computer was connected on Wifi via Android tethering using a spare phone and the device I wanted to stream on was connected as well but to the router. The android tethering was some how creating it's own gateway address and would be seen as on an independent network.

That's how I resolved this issue just now .

**Comment by Lukestifire** [comment]
I've never been able to connect it over the internet. If I'm on the same network, my phone connects fine, nothing over mobile data though. 

I've set up all the port forwards and static ip. I reinstalled everything twice. I turned off my firewall. Is there anything I can do to get this to work?

**Comment by tzhouhc** [comment]
My issue with it was due to Windows Firewall blocking the port, where "nc -z <desktop ip> 47989" failed. 
By adding an Inbound Rule to Windows Firewall with custom settings, where I allowed any connection from within the subnet range of 192.168.0.0/24, I was able to get it to work. This is for Windows 10, and I'm not sure if this will fix other's issues, just putting this out here.

**Comment by LordoftheFunk** [comment]
Signed up here specifically to thank tzhouhc for this, i couldnt find what was blocking this (and a couple of other apps im fooling around with) literally the second i added that rule to my firewall the pc popped up on my phone. 

Cheers for that.

**Comment by spidy2356** [comment]
on moonlight my pc shows offline, I configured using sunshine. whenever I click on "send wake-on-lan request" it says "unable;e to wake up because there is no stored mac address"

what should I do now?

**Comment by arnav2404** [comment]
I am Using Dragon Technologies 707GR1 Router and have add total 8 ports in port forwarding of 4 TCP (HTTPS, HTTP, Web, RTSP)(47984, 47989, 47900, 48010) and 4 UDP (Control, Video, Audio and Mic)(47999, 47998, 48000, 48002) i have also added the local IP in DMZ and have put new rules in Firewall for these ports in Inbouned and Outbouned separately and finally added the application rule also, but even after all this setting i am getting this error now i don't know what to do, I was hoping that i can play games even when i was in different city but it seems impossible 😔
![inbouned](https://github.com/user-attachments/assets/7b528104-4c8f-4f41-bbbd-4749301ebf31)
![outbouned](https://github.com/user-attachments/assets/327f85e4-1df4-4353-a32e-e92542abc9b8)
![Screenshot 2024-12-18 200840](https://github.com/user-attachments/assets/065fa577-83f0-4e5e-b933-a79d828bc403)
![Screenshot 2024-12-18 201021](https://github.com/user-attachments/assets/d904a062-056f-4b70-9b00-c7ee0a511964)
