### ISSUE TITLE
compiling help

### ISSUE THREAD

**Issue by muffinmannameistaken** [moonlight-stream/moonlight-android#236]
when I try and compile I get this error 

Error:Execution failed for task ':app:compileNonRootDebugJavaWithJavac'.

> compileSdkVersion 'android-24' requires JDK 1.8 or later to compile.

I'm still able to compile the older versions of moonlight. 
any ideas how to fix this? thanks

**Comment by cgutman** [comment]
You need to update the JDK installed on your PC to Java 8.

**Comment by muffinmannameistaken** [comment]
ok i tried to update to 8 i think i did or i just got a bad install 
this is where i got downloaded java 8 
http://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html

I still have the same problem after install, Iv also updated to Android studios 2.1 
any ideas ?

**Comment by extremeGEgaming** [comment]
Check if the environment variables are correctly set.
