### ISSUE TITLE
Connection Terminated after connecting controller.

### ISSUE THREAD

**Issue by SpaceDoge** [moonlight-stream/moonlight-android#237]
Streaming works flawlessly until I connect a PS3 Gamepad through the "Sixaxis Controller" app, where I get the "Connection has been terminated" error.. I am running android 6.0.1 with the rooted moonlight installed.

**Comment by OOPMan** [comment]
I seem to be getting this error too although I am using an XBox 360 controller connected to my PC.

**Comment by sanakess** [comment]
I have a solution! u need to restart streaming services in win+r services.msc
