### ISSUE TITLE
Nyko Playpad Pro double input

### ISSUE THREAD

**Issue by duox7142** [moonlight-stream/moonlight-android#238]
My Nyko bluetooth controller seems to have both the D Pad and the thumbstick inputs mapped to the thumbstick, making for difficult selections and mapping conflicts. Controller is in HID mode. How can I go about remapping this controller's inputs?

**Comment by cgutman** [comment]
You can fix that with a firmware update for your controller from Nyko's website: http://nyko.com/products/playpad-pro

**Comment by duox7142** [comment]
Thanks, firmware update did fix it!
