### ISSUE TITLE
Wireless Xbox 360 controller not working if the dongle is connected to the pc

### ISSUE THREAD

**Issue by MilkJugArmadillo** [moonlight-stream/moonlight-android#239]
So I'm trying to stream to an android device, but because I can't connect the 360 controller to the device as of right now, so I have the 360 connected to the PC it's being streamed from. It's very close to the dongle, so that isn't the problem. 360 controller works fine when I'm not streaming, so I'm very confused. Keyboard and mouse also works fine when I'm streaming. Help please

**Comment by cgutman** [comment]
There's an extra step to use a controller on your PC instead of your Android device. https://github.com/moonlight-stream/moonlight-docs/wiki/Setup-Guide#using-a-gamepad-connected-to-the-pc-instead-of-the-streaming-device

**Comment by Direcka** [comment]
Not working for me ie....

![2016-10-12 1](https://cloud.githubusercontent.com/assets/14356883/19318800/639d6d1e-90aa-11e6-8f43-acd97577bc45.png)
