### ISSUE TITLE
1080p 60fps wired connection on both, minimal lag

### ISSUE THREAD

**Issue by Kekskruemel** [moonlight-stream/moonlight-android#24]
Hi,

Tablet and PC are both wired.

I run a speed test an the result was ~250 mbit transfer rate to the pc and 0.2 ms

If i stream at 1080p 30fps all is fine. If I run at 1080p 60 fps there is a ~1 second lag.

Device is a samsung galaxy tab pro 10.1 so performace should be ok.

Is this a know "issue" or normal.
Because if I stream with my nvidia shield in big picture mode with 1080p 60fps I can't see any lag.

Thx & Greetings

Nils

**Comment by mrb113** [comment]
Closing since this is old - please reopen if you're still seeing this.
