### ISSUE TITLE
Device Pairs, but Doesn't Detect Games

### ISSUE THREAD

**Issue by Nikko112** [moonlight-stream/moonlight-android#240]
Howdy. I have run through all the troubleshooting and I am now having the issue that I can pair my device with my pc just fine, but when I open my pc on my device, no apps are displayed.

The first time I ran moonlight I could open steam, tried opening Counter Strike and it crashed. I uninstalled Razer Synapse and now I have no games being detected at all.

I am using an LGG4, I have an i7 CPU and the GTX970 overclocked GPU.

I ultimately want to set up the poor man's oculus, with minimal outlay.

**Comment by cgutman** [comment]
Sometimes this bug happens with GeForce Experience. Try uninstalling GFE, rebooting your PC, then reinstalling GFE and scanning for games again.

**Comment by Nikko112** [comment]
Fantastic, reinstalling GeForce and rebooting worked like a charm.
