### ISSUE TITLE
ps2 controller

### ISSUE THREAD

**Issue by seseneitor** [moonlight-stream/moonlight-android#241]
Hello. First all I want to tahnk you for the app. I was having some troubles using the shield hub app to streaming online, but with this one everything works perfect.

I was trying to use my old ps2 controller as i usually do in my computer, but was imposible. The only buttons which works was the arrow, the left stick and the right one with the directions changed (when you move it to the right, the game move down, etc...) the rest of the buttons did nothing. I try remaping tools and so on, but some of them ask for root and others don´t allow me to make the right joystick works right.

I hope if someone has a solution.

I use the gamepadtest app to test if the controller send inputs, and i leave here the codes:

cross= 190
Square = 191
triangle = 188
circle = 189
arrow up = Hat Y: -1
arrow down = Hat Y: 1
Arrow Left = hat x: -1
Arrow right = hat x: +1
Left Joystick to left = X: -1
Left Joystick to up =  Y: -1
Right Joystick to Left = Rz: -1
Right Joystick to Up = Z: -1
R1= 195
R2= 193
R3= 199
L1= 194
L2= 192
L3= 198
Select= 196
Start= 197

**Comment by JC144** [comment]
6 years later, have you found a solution? I have the exact same issue.

**Comment by seseneitor** [comment]
> 6 years later, have you found a solution? I have the exact same issue.

Yes, I actually buy a Bluetooth Xbox controller and leave the ps2 one apart....

**Comment by JC144** [comment]
Nooooo! I forked the project, I was ambitious and thought I could do the mapping by myself. It wasn't the issue.

Thank you for your quick answer after all of this time.

Have a good day :)
