### ISSUE TITLE
Connection aborted in mstsc related to media player classic

### ISSUE THREAD

**Issue by MemoChou** [moonlight-stream/moonlight-android#242]
When i was using media player classic with moonlight stream, if i pressed alt+enter for full video screen, the connection got aborted but if i pressed double click for full video screen, it worked like normal.
That's the issue and i hope moonlight stream can fix this.

**Comment by extremeGEgaming** [comment]
I think this is an issue with nvidia backend/nvstreamsvc, I am also experiencing a problem with the session getting stuck and I can't open certain apps from the host machine for some reason, until I end all the nvidia backend services.
