### ISSUE TITLE
Connection terminated after starting audio/video stream or rtsp handshake

### ISSUE THREAD

**Issue by Detinator10** [moonlight-stream/moonlight-android#245]
It was working fine earlier today, but then my graphics card crashed and now moonlight doesn't work. It says connection terminated after starting the audio or video stream or staring the rtsp handshake. Any help is appreciated

**Comment by cgutman** [comment]
Have you tried rebooting your PC?

**Comment by Detinator10** [comment]
Yep, I have done that multiple times. Just realized that I have kino console installed on my computer though, so I will uninstall that and see if it works

**Comment by Detinator10** [comment]
So, it turns out kino console was the problem. I've uninstalled it and now it works.
