### ISSUE TITLE
TV Box latency ~80ms

### ISSUE THREAD

**Issue by shamanGOD** [moonlight-stream/moonlight-android#246]
Greetings!
Facing big latency on tv box (~80ms). Tried changing resolution and bitrate. But latency the same on all settings. Also tried moonlight for my laptop (using both, chrome plug-in and java execution file) but latency was even bigger.
The thing about decoding codec. my tv box should support decoding h265 up to 4k.( I think so), but moonlight can`t start video stream with forced h265 codec.
Everything connected via ethernet cables to Xiaomi MIwifi 3 router(padavan firmware).

My hardware:
Host pc: i5 2500; gtx 770; 8gb ram
TV box mqx pro;  CPU = Amlogic s905; GPU = Mali-450 MP; 1gb ram; android 5.1
Laptop; intel celeron 10007U with intel hd1000. :(
ping to tvbox=2ms

Using latest moonlight app for rooted devices.

P.S I have not tried different moonlight app versions.

**Comment by txchen** [comment]
@shamanGOD I am curious that why did you close this? Is it solved?

**Comment by shamanGOD** [comment]
@txchen Just had a feeling that this is the best tv box can do.
