### ISSUE TITLE
1440p 60FPS support

### ISSUE THREAD

**Issue by GeForstner** [moonlight-stream/moonlight-android#247]
Hey there, I am really enjoying VR with moonlight on my LG G3. I would be awesome, if i could stream the native Resolution of my phone(2560x1440). I installed the GeForce expierience Beta but still there is no 1440p option in the moonlight-app.

**Comment by GeForstner** [comment]
why isn't anybody responding? Is moonlight dead? BTW i got a 1080p Monitor if this helps. 4k works but the performance is poor.

**Comment by cgutman** [comment]
It's not dead. GFE doesn't correctly support 1440p streaming resolution on a 1080p monitor.

**Comment by GeForstner** [comment]
Ok thanks. Please let me know when there is a solution. Keep up the good work

**Comment by GeForstner** [comment]
Today I got myself a 2k monitor to finally play in 2560x1440 but I still don't have that option on my G3!!! Am I missing something? (4k is way to laggy)
Please respont as soon as possible.
