### ISSUE TITLE
Pairing time out

### ISSUE THREAD

**Issue by ramok2k** [moonlight-stream/moonlight-android#250]
Hello! I recently got my One Plus 3 and was trying to pair it. The pair box appears and input the code but nothing happens. Sometimes it says 'timeout'. I tried restarting everything but had no luck.

Is this related to the new Geforce update?

**Comment by SoniczeroG** [comment]
Same issue here, are you on the latest beta too?

**Comment by ramok2k** [comment]
Not sure, I got the latest one from the Play Store (root version).

**Comment by SoniczeroG** [comment]
Sorry I meant the Geforce beta.

**Comment by ramok2k** [comment]
Yes, I'm on the latest one.

**Comment by SoniczeroG** [comment]
Me too. When I downgrade pairing works, but it's a hassle to keep reinstalling just to pair.

**Comment by ramok2k** [comment]
Have you tried pairing to the original Geforce Experience and then updated to the new one? I'm guessing the pairing authentication should carry and hopefully work.

**Comment by SoniczeroG** [comment]
The paired devices stay, but pairing with new devices still doesn't work.

**Comment by ramok2k** [comment]
Oh, well at least that's something. Granted there needs to be a better way to authenticate with the new version and hopefully the devs are on it.

**Comment by cgutman** [comment]
I have not seen that behavior on GFE Beta 3.0.2.196 locally. Can you confirm what version of GFE you have installed?

I did have an issue upgrading from GFE 2.11.4 to 3.0+ which broke GameStream. You could try uninstalling the GFE Beta and reinstalling it from the Beta installer on Nvidia's website. That fixed my GameStream issue.

**Comment by ramok2k** [comment]
I'm using version GFE Beta 3.0.2.196

**Comment by cody151** [comment]
any help ?moonlight not working
