### ISSUE TITLE
Unable to pair, no prompt on PC

### ISSUE THREAD

**Issue by Vysarat** [moonlight-stream/moonlight-android#254]
I just installed Moonlight, and I'm trying to pair it to my PC for the first time. The problem is when I select the PC on my phone the app shows me a dialog with a PIN, but I don't see a pairing pop-up on my PC. After about ten seconds the pairing dialog on the phone disappears and it says "Pairing failed".

I've tried both the root and non-root versions of the app, tried rebooting both devices, tried disabling the Windows firewall, nothing helps.
I'm using GeForce Experience 2.11.4.0 on Windows 8.1, and Android 5.1.1 on a Galaxy S5.

**Comment by greybaron** [comment]
I also have the exact same problem, although I am using the newest iOS app version. Pincode in the Moonlight app only pops up for about 1 second and then disappears without any error, no reaction on PC whatsoever.

I'm using GeForce Experience 2.11.4.0 on Windows 10, and iOS 9.3.3 on an iPhone 6.

**Comment by greybaron** [comment]
**UPDATE**
On the new GeForce Experience 3.x BETA it works flawless.

**Comment by Vysarat** [comment]
No such luck for me. Same problem with the Beta.

**Comment by greybaron** [comment]
You mean that the PIN code entry doesn't show up? Because that started working for me, but streaming still is impossible to do because of a black screen.

**Comment by Vysarat** [comment]
The PIN prompt still doesn't show up for me.

**Comment by Darkcloud1987** [comment]
Yeah I have the same

**Comment by victormendoza621** [comment]
Pin box is not showing up on my windows 10 alienware 17 r3 after trying to pair from my note 7 6.0.1.  Any fixes?

**Comment by mgibbonsjr** [comment]
Same thing happening here. Moonlight is finding my computer but the pin popup is not occurring. I have reinstalled GFE a few times and updated to GFE 3 beta as greybaron did but it did not resolve the issue on my Windows 10 i7 GTX 970. Also made sure the notification icon is present.

**Comment by greybaron** [comment]
Actually, if anyone is interested, it was like this for me:
1. newest official GFE -> taskbar symbol was there, but no pin code popup.
2. installed latest beta 3.x -> was able to pair and connect, but black screen.
3. downgraded back to latest public release 2.x the same day, had to repair, pin code popup appeared just fine and everything went smoothly, weird. Try to reinstall GeForce Experience but REMOVING all user data (when downgrading beta-> public release it automatically did it I suppose) and I have no problem since then, and am happily streaming regularly. OSes:
Windows 10 x64 WITHOUT anniversary update
-Ethernet 100mbit
iOS 9.3.3 iPhone 6
WiFi 2.4 GHz, WiFi n

**Comment by victormendoza621** [comment]
Any1 find a fix? I tried your fix greybaron and it didnt work for me.

**Comment by mgibbonsjr** [comment]
Hey guys. I'm not sure if this is the same issue everyone else is having, but one of the steps I was missing was within NVIDIA Control Panel. I was checking the option to display GPU Activity Icon in Notification Area and confusing it for Show Notification Tray Icon which actually wasn't an option. 

If this is your issue also, head over to Reddit and review Thomohawk's post which solved my issue. 

https://www.reddit.com/r/StreamTheater/comments/4ywc7f/help_with_pairing/?st=isenj2xf&sh=545ca17a

**Comment by victormendoza621** [comment]
This worked for me.  I have an alienware as well.  I heard that makes a difference.  TY for your help!!

**Comment by rainabba** [comment]
Same here. ON GFE 3.2.2, the computer is seen, but when I try to show app list, I get "Not paired with Computer" and no prompt on my PC. reinstalled GFE even.

**Comment by indexftw** [comment]
Confirmed working when enabling the "Notification" menu in the nvidia panel.

**Comment by Rjj18** [comment]
All those steps didin´t work for me.
Using Windows 10.
