### ISSUE TITLE
Nothing but stuttering on Android. Mostly perfectly smooth on iOS.

### ISSUE THREAD

**Issue by PhantomLiberty** [moonlight-stream/moonlight-android#255]
I have a Galaxy S7 and an iPad 3 both with moonlight installed. On Android, the stream stutters as if it's dropping frames for 2-3 seconds at a time every 5 seconds or so. The same happens on every setting from 720p/30fps to 4k/60fps (which runs great btw despite the stuttering) with H.264 and H.265. iPad is generally so much smoother than the Android version. Playback is very smooth at 1080p/60fps with minimal issues but is still very playable. Both are connected to a 5ghz 802.11ac signal from about 7 feet away when playing and my base PC has a wired connection. 

Anyone help would be awesome. I don't know what else I could do to troubleshoot and see why the android version is underperforming. Maybe it's a known bug or something? I have no idea.

Galaxy S7 running 6.0.1 Marshmallow  |  iPad 3 running  iOS v9.3.2

**Comment by marcmy** [comment]
Same here, terrible stuttering with any setting. Device is on 5Ghz, PC is wired, Ethernet adapter is set to 1.0Gbps Full. Don't have an iPad to compare. My device is a Samsung Galaxy Tab 10.1 (SM-T520) running CM13 nightly.

**Comment by cgutman** [comment]
Sometimes location services can cause this kind of stuttering since it's starting WiFi scans in the background. Can you try turning off location services (and maybe killing other apps in the background)?

**Comment by marcmy** [comment]
Thanks for the reply. I've turned off location on my device and also
disabled "network notification" under advanced wi-fi settings (to hopefully
prevent it from scanning for public networks), but the stutter is still
there. Bluetooth is off as well. I'm sitting about 3 feet away from the
router.

**Comment by PhantomLiberty** [comment]
I've tried pretty much everything I could find through Google searching and the issues are still there. I usually wire my PS3 controller from my PC to make sure there is absolutely 0 interference and it is still choppy. Every service that could potentially interfere is turned off. The only thing I could think of is either the Android app sucks or my cell signal to the tower is interfering which I don't think can be disabled. Wifi signal is reporting 700+ mbps at all times yet it seems to stutter or drop large amounts of frames in the same way/amount on every setting from 4k60fps 100 bitrate to 720p30fps 1 bitrate.

**Comment by marcmy** [comment]
Wouldn't be your cell signal cause it's happening on my tablet too (Wi-Fi
only). I haven't tried wiring the controller through my PC as that would
defeat the purpose of the app for me; I plan to use it when I'm away from
my computer only.

**Comment by marcmy** [comment]
Anyways the stutter isn't absolutely terrible it's just an annoyance for me
because I'm used to it being buttery smooth on the PC. Hopefully there's a
fix but if not it won't but if it not it won't be the end of the world.

**Comment by PhantomLiberty** [comment]
I only wish my performance was tolerable. 15% of the time it's smooth 60fps and 85% of the time with the dropped frames it feels like 20-30fps. I have a phone mount for my controller and playing on my iPad is so awkward. I just wish it worked well on Android as it does on iOS. :\

**Comment by diagonali** [comment]
Having a similar issue on my Shield Android TV, video stuttering quite a lot but still playable audio is perfect. Using a GTX 1060 and playing Rise of the Tomb Raider. Often starts out ultra smooth, then during gameplay can get very choppy, then can get smooth again, seems weirdly intermittent. Perfectly smooth locally on computer and running a ethernet cable all the way to my Shield TV. Still hoping for H.265 decode on the Shield TV(!) although I know it's not a priority and may not resolve this issue. Not sure what could be causing stuttering. Tried lowering and increasing the bitrate but no luck. Happy to provide logs if needed/possible.

**Comment by XaivierX** [comment]
Hey all.

I've been having stuttering issues as well.  I had a Samsung Galaxy Note 3 (rooted), and performance was smooth.  I just upgraded to the Galaxy Note 7 (not rooted) and I'm experiencing a quarter second freeze / stutter every few 2/3? Seconds.  It's not random, it freezes like clockwork. 

After doing a bunch of testing, I realized that the 'Beacon Service' appears to be the culprit.   After I kill that Service, things improve dramatically. 

How did I kill the service?  Under 'Developer Options' under Settings, go to 'Running Services'.

From there the Beacon Service should be there.  If not, it should appear after a few seconds.   It appears to start and stop itself on a timer.  If you can manage to click it, you can stop it completely,  at least until the next boot.

I have an optimal setup at my home so there should be zero stutters or lag.  Killing this service appears to help quite a bit, if not completely.   I'd like a bit more fluidity past what this fix gives, but that's probably me being picky.

Heck I'd expect sub 10 millisecond decoding performance on this phone but seems to stay at 16-19ms instead, though probably not related to the stutter at all.

I hope this helps and possibly leads to a permanent solution!

**Comment by XaivierX** [comment]
PS, This stutter doesn't seem to be unique to Moonlight.   I tried Remotr, hoping for better performance but I ran into the same stutter issue. Just an FYI.

**Comment by PhantomLiberty** [comment]
Managed to fix my crazy stuttering. My phone is rooted and wasn't boosting CPU clocks constantly, something specific to the root method. I use govtuner and the Kernal Auditor app so whenever I play I make the clock speed stay high without dropping for no reason. But I still get stutter though. I think it's just an issue with NVIDIA's gamestream. It seems like the stream frame rate doesn't sync up with the device it's streaming to. Smooth for a second followed up with microstuttering for 2 or 3 seconds. I've seen numerous threads elsewhere that have the same issue. Pretty sure it's up to NVIDIA to fix it and unfortunately it seems like this issue has been present for at least a year.

**Comment by shivito1** [comment]
Please tell me this can be fixed. My note9 is having issues on LAN but works fine over LTE. Any help would be awesome.

**Comment by Barabbo** [comment]
Experience of a shuttering every second on my galaxy tab 7 + Xbox 360.controller. if I fix this I unsubscribe my Xbox live gold
