### ISSUE TITLE
Root input switch causes mousepad and touchscreen to stop responding (TF300T)

### ISSUE THREAD

**Issue by netcoder1** [moonlight-stream/moonlight-android#26]
Limelight (Root) v2.5.6
Asus Transformer Pad TF300T
Android 4.2.1

On app start, mousepad and touchscreen works exactly like the non-rooted version. Triggering the root switch (Ctrl-Shift-Z) causes the both the mousepad and the touchscreen in app (system bar is not affected) to stop responding entirely until session ispaused and resumed to its non-rooted state. Physical keyboard still works. Toggling the mousepad on and off on the keyboard doesn't fix the issue.

Will be happy to provide more info/debug if you can point me as where to dig it up.

**Comment by cgutman** [comment]
Re-open if this is still an issue after the root mouse capture rewrite in 4.0.2.
