### ISSUE TITLE
no matter what i do, still no nvidia icon in system tray!

### ISSUE THREAD

**Issue by zombie9143** [moonlight-stream/moonlight-android#262]

**Comment by evildog1** [comment]
You can reinstall Geforce Experience on your PC and it will work again

**Comment by Neverest** [comment]
Same for me, I don't even get the PIN tray that pop up when trying to pair devices.

**Comment by evildog1** [comment]
Try launch Geforce Experience. Sometime it does not launch

**Comment by Neverest** [comment]
Just tried it. Didn't work.

**Comment by Neverest** [comment]
Ok, managed to get it now. Checked the Geforce Expierence forums, and it seems that Dell asked Nvidia to not show that setting on Dell & Alienware PC's if this [forum post](https://forums.geforce.com/default/topic/949442/geforce-experience/system-tray-icon-gone/post/4923734/#4923734) is correct. Mine is an Alienware Alpha that had the tray dissappear so I can belive it.

The solution shown in [post 41](https://forums.geforce.com/default/topic/949442/geforce-experience/system-tray-icon-gone/post/4953120/#4953120) fixed it. Go into your registry files and on HKEY_LOCAL_MACHINE\SOFTWARE\NVIDIA Corporation\NVTray change "showinsedona" from 0 to 1 to fix it. 

After that, I went to Nvidia Control Panel and in Desktop tab check Show Notification Tray. That should fix it, and make you pair.
