### ISSUE TITLE
Cannot connect using LTE, works fine with wifi (same network as PC)

### ISSUE THREAD

**Issue by thorowitzm** [moonlight-stream/moonlight-android#263]
For clarification, I have had it work fine via LTE, about 2 weeks ago.
But after moving my home, it doesn't work on LTE now.
There was no changes made, my notebook PC is the same, internet provider is the same, android phone is the same, everything is the same.
I tried the following : 
1. Wiping moonlight app data from my phone and re-installing the app.
2. Updating GeForce experience on my PC
3. Enabling the ports (10 of them) at my windows firewall
4. Re-booting phone and PC several times

Thinking that LTE streaming worked fine without doing the above things 2 weeks ago, I can't find the problem.
Everything in the setup guide (https://github.com/moonlight-stream/moonlight-docs/wiki/Setup-Guide) is done perfectly, and double-checked.

It still works fine in wifi (same network as PC, through wireless router) but the moment I switch to LTE, the app cannot connect to my PC.
(After entering my PC in the app in wifi environment, then turn wifi off, and select a game, an error message shows something about port 47984)

Please someone help me.. it's getting really frusturating...

**Comment by The3DLink** [comment]
I'm assuming your IP address has changed due to your move. Have you updated your Moonlight settings? If your router supports it, try setting up/connecting via VPN.
