### ISSUE TITLE
need "Landscape (flipped)" screen orientation fix

### ISSUE THREAD

**Issue by MadSpin** [moonlight-stream/moonlight-android#265]
Hey,

(Windows 10 streaming to Android)

I have my primary monitor on an arm mount and have it flipped upside down landscape. When I stream in moonlight the stream is "upside down" even though the video looks "right side up" on the screen. I have to manually set my display options to "landscape" on the monitor whenever I want to use moonlight streaming. 

It's not too big a deal but I wanted to bring it to the developers attention in case you guys weren't aware of it.  Maybe some code could be written to account for screen orientation in the future.

Thanks for this amazing project/program.

**Comment by cgutman** [comment]
This is probably something Nvidia will need to fix on their end, if they haven't already.
