### ISSUE TITLE
No audio in certain games on android client. Pc still has sound.

### ISSUE THREAD

**Issue by EnderGotGame** [moonlight-stream/moonlight-android#266]
When playing games such as doom 2016 and no mans sky, I get no game audio on my client android. However the host pc has game audio. When I play the Witcher 3 or fallout 4 I have sound on both. I am running Windows 10 with a gtx970 and a samsung galaxy edge 7. Please help.
Thanks!

**Comment by scoobyd00** [comment]
Try this fix on your PC. 
It worked for me.

Create a DWORD value in "HKLM\Software\NVIDIA Corporation\NvStreamSrv" called "CoreAudioDetour" Set to decimal 0. 
Reboot your machine (or restart NvStreamSvc).
