### ISSUE TITLE
High decode latency Minix Neo U1

### ISSUE THREAD

**Issue by txusramone** [moonlight-stream/moonlight-android#269]
Hi

I have:
HOST:
i7-4790
16gb ram
gtx960
gigabyte ethernet (1-3 ms to tvbox)

tvbox
minix neo u1
cpu: AMLogic S905 Cortex-A53 Quad Core
gpu: Mali-450MP5
gigabyte ethernet (1-3ms to host)

I have > 100 ms hardware decode latency with:
720p 30fps
1mbs

I tried h.265 and no h.265 with same result
I tried gfe beta and no beta with same result

Can my tvbox run correctly moonlight with games?

Waht can i do? any idea?

Sorry for my english

Thx!!

**Comment by dan83sama** [comment]
Use older app (need install old gfe also) and select software decoder.
I guess is the same error https://github.com/moonlight-stream/moonlight-android/issues/142

**Comment by txusramone** [comment]
Many Thx :)

Have U idea what a version i need? There are many versions

https://github.com/moonlight-stream/moonlight-android/releases

**Comment by dan83sama** [comment]
moonlight 3.1.13
gfe 2.8

**Comment by Kernotmdl** [comment]
Hi, I do have the same Issue with an MXIII-S box. It does have the same CPU as Minix Neo U1.
AMLogic S905.
I tried older versions as suggested by dan83sama but it works just ok at 720p.

**Comment by cgutman** [comment]
I have some APKs for you to test on your AMLogic devices. Let me know if any of them improve performance.

https://1drv.ms/u/s!AlafYXCXvxUMifMfRkQo3DSrnTq60w
https://1drv.ms/u/s!AlafYXCXvxUMifMgsViVx3LdgmUTXA
https://1drv.ms/u/s!AlafYXCXvxUMifMeXBxVx1xj959Scg

**Comment by dan83sama** [comment]
I tested these apks in my device https://github.com/moonlight-stream/moonlight-android/issues/142 , and still the same, if you need logs let me know.

**Comment by Kernotmdl** [comment]
Hi!
Just tried them and those are the results all at 720p 60, 1Gb Ethernet and with H265.
1st BS: Gives about 72ms.
2nd CONST: Gives about 270ms.
3rd NOLEVEL: Gives about 340ms.

Just want to clarify that my box is not a Amlogic S905, it is a Amlogic S812.
With a Note 4 over 5Ghz wifi I get about 15ms on 1080p 60.

**Comment by FuzzyYetiX** [comment]
Thought I'd chime in here as I have the exact same box (Minix U1)

My host specs are:

i7 2600K
32GB RAM
EVGA 1060 GTX SC
Wired connection from PC to router and wired from Minix U1 to router as well.

I'm running an Apple Airport Extreme 4th Gen which at first was thinking was the cause since it's a bit older, but I'm not too sure. But yeah, same 100ms delay. I also tried installing older software both for Moonlight and GFE, but GFE couldn't detect my GPU which is needed to enable the streaming feature. So I'm running the latest Moonlight and latest GFE so it's at least detected.

I'm not as knowledgeable as you guys on here, but can try to troubleshoot if needed. I did try all the links that cgutman posted but all of them gave me a black screen when attempting to stream anything.

**Comment by chrirauch** [comment]
Hi

I have a xiaomi mi box with the same processor & graphics chip and I'm facing the same issues. Quality looks good but the lag seems to be pretty consistent regardless of resolution and framerate

HOST
I5 6600K
Geforce gtx 970
...

Client: Xiaomi Mi Box 
Processor	Quad-core Cortex-A53 2.0GHz
GPU	Mali 450 750MHz

**Comment by joh9** [comment]
> I have some APKs for you to test on your AMLogic devices. Let me know if any of them improve performance


Hey,
first: thank you cgutman for your excellent work and donating time on moonlight!!!

Host:
Chipset: i5-4200M
GPU: GTX 850M
Client:
Chipset: Amlogic S905 Quad Core Cortex-A53 at 2.0GHz
GPU: Penta-Core Mali-450 at 600MHz+
All Devices are wired via Ethernet.

AMlogic Android Box works with latency, but my Pi2 is running perfect.

Test:
Moonlight Android v4.8.3: Gives about 83ms.
1st BS: Gives about 90ms.
2nd CONST: Gives about 310ms.
3rd NOLEVEL: Gives about 380ms.


Have you some root-apks to test, too?


> dan83sama commented on 25 Aug 2016
moonlight 3.1.13
gfe 2.8

Not tested

**Comment by joh9** [comment]
Second Question: should the Problem get from the HDMI output?

**Comment by kkdeperro** [comment]
Hello my setup is:

Mi Box Android TV with AC router

PC: 
i7 3770K 
16Gb RAM
GTX 680

and when i change decoder options to always use H.265, when exits moonlight and shows de decoder latency always shows H.264 68ms, why if change to H.265 always shows H.264? 

it's for my setup?

Thanks!
