### ISSUE TITLE
Starting Control Connection Failed

### ISSUE THREAD

**Issue by Snicker56** [moonlight-stream/moonlight-android#27]
Whenever I try to initiate a game using Limelight, it starts up and comes up with this error. The game runs, but I cannot use the game. This recently happened after I started using the remote version of the app. I've tried it on both Rooted and Unrooted versions, and no difference. I'm using the latest version of GeForce Experience and have tried wiping it and re-downloading with not effect to the error.

**Comment by mrb113** [comment]
This issue is a year old - closing due to staleness. If you still experience this, then please reopen with more information about your configuration.
