### ISSUE TITLE
Xbox One Controller - Buttons messed up.

### ISSUE THREAD

**Issue by DrBob17** [moonlight-stream/moonlight-android#272]
Hello, i'm using moonlight v4.7 and a Samsung Galaxy Note 4, i connected my xbox one controller through a otg cable micro usb to usb, it works with some games, but some the mapping seems to be all messed up, i don't mind changing it, but some of the buttons aren't even recognized  such as l3 - r3, the whole right stick is substitute with the lt - rt buttons. 
also  x y a b buttons are mixed up x is a and so on.
i wonder if anyone else has this problem

**Comment by cgutman** [comment]
Did you get a USB access prompt when Moonlight started streaming? With the Xbox controller plugged in, can you install the AIDA64 app, go to the Devices tab, and screenshot the USB device portion?

**Comment by DrBob17** [comment]
![screenshot_2016-09-08-18-21-11](https://cloud.githubusercontent.com/assets/21373471/18372395/4a89959c-75f1-11e6-951c-780a2b94464d.png)
![screenshot_2016-09-08-18-21-08](https://cloud.githubusercontent.com/assets/21373471/18372397/5057ba58-75f1-11e6-8e09-58b344030ae9.png)

This one you mean ?

**Comment by cgutman** [comment]
You should capture a screenshot with your Xbox One controller's USB Device info in picture

**Comment by DrBob17** [comment]
![screenshot_2016-09-09-00-03-39](https://cloud.githubusercontent.com/assets/21373471/18378293/fa3b9844-7620-11e6-9eb3-558cd25424b6.png)

This is it
