### ISSUE TITLE
403 error?

### ISSUE THREAD

**Issue by muffinmannameistaken** [moonlight-stream/moonlight-android#273]
I'm getting this error 403 RTSP announcement request failure, I updated Geforce to 3.0.5.22

**Comment by cgutman** [comment]
Can you zip and upload the logs in "C:\ProgramData\NVIDIA Corporation\NvStream"?

**Comment by muffinmannameistaken** [comment]
[NvStreamerCurrent.zip](https://github.com/moonlight-stream/moonlight-android/files/464574/NvStreamerCurrent.zip)


Is this what you are talking about ?

**Comment by cgutman** [comment]
It looks like that file is corrupt. Can you zip the whole NvStream folder?
