### ISSUE TITLE
can resolution support 1680*1050 ?

### ISSUE THREAD

**Issue by yebr** [moonlight-stream/moonlight-android#274]
my PC is 22inch 16:10 and resolution is 1680x1050.
moonlight-android client only support 720P, 1080P and 2K.
it make the screen distortion and blurred.
can you add new resolution support 1680x1050 with pixel to pixel ?

**Comment by megapro17** [comment]
Also, i need 1336x768 standart notebook resolution

**Comment by megapro17** [comment]
Also, add 1336x768 please.

**Comment by soetdjur** [comment]
I'm amazed about the bad support from the moonlight devs here. I'd also love a feature to change specific resolutions. I'd love a 1440p settings.

**Comment by cgutman** [comment]
We have responded to similar requests on nearly all of the Moonlight projects. It's simply not possible to do this reliably now. Recent GeForce Experience versions fail to stream at all when a resolution is requested that the display cannot be set to.

**Comment by t184256** [comment]
> It's simply not possible to do this reliably now.
Why don't you add a custom resolution option with a corresponding warning? Would be very nice.
