### ISSUE TITLE
Stopped Working when updated to Geforce Experience 3.0

### ISSUE THREAD

**Issue by seanocali** [moonlight-stream/moonlight-android#275]
I use an Amazon Fire TV Stick.  Moonlight worked flawlessly.  With the new GFE 3.0 updated, Moonlight crashed twice while browsing games.  Third time I loaded a game but I got audio but no video.

**Comment by cgutman** [comment]
The crash during game browsing is probably due to changes in Moonlight v4.7's UI updates. Some games seem to have this black screen issue with GFE 3.0 even on Shield devices. Have you tried Steam  Big Picture or other games?

**Comment by scoobyd00** [comment]
Also having issues with the Fire Tv 2. Getting sound but a blank screen. Ive tried uninstalling and reinstalling drivers but no difference.

Downgraded geforce experience and its working again so looks like there may be an issue with 3.0

**Comment by seanocali** [comment]
I have not tried Steam and I have not tried other hardware sorry.

**Comment by tbhozie** [comment]
Yeah, not working for me either, tried re-installing drivers and GFE. Still just shows a black screen, but the audio does work. 

This is on a Amazon Fire Box
