### ISSUE TITLE
requesting save layout feature and scale improvement in virtual gamepad

### ISSUE THREAD

**Issue by sizzflair97** [moonlight-stream/moonlight-android#276]
replacing every buttons at each session is quite difficult job. would it be possible to save layouts for each game? and button scaling improvements is also required. buttons in left side can't be scaled appropriately.

**Comment by cgutman** [comment]
Save layout is already done. Scaling isn't yet.

**Comment by zeebiedeebie** [comment]
Anxiously awaiting scaling and positioning fixes. Requesting coordinate-based repositioning of each control.
