### ISSUE TITLE
Right joystik not work and Screen edge problem for mouse

### ISSUE THREAD

**Issue by greatyong** [moonlight-stream/moonlight-android#277]
Phone : Somy Z2 D6503 running on Android ver. 6.0.1
Pairing controller : Dualshock 4 over wireless and logitech unifying receiver for keyboard and mouse.
PC game : Rainbow six siege
Moonlight : ver. 4.7

Not sure why and problem only in this game. But

1. DS4 right joystik does not work for aming.. nor touch input for right joystik not work for aiming.

And

2. All keyboard keys and mouse functions work fine but Mouse does not go over screen edge. 

Could somebody help?

**Comment by cgutman** [comment]
The joystick issue is likely GameStream not being fully compatible with streaming Rainbow Six Siege.

The mouse issue is a limitation of the Android mouse API. If you have a rooted device, you can try downloading Moonlight for Rooted Devices on the Play Store and that should solve the mouse issue.

**Comment by greatyong** [comment]
Thanks for the commnets. I have no-rooted device. I will try to use moonlight chrome version.
