### ISSUE TITLE
In what circumstances can the bitrate reset to the default value?

### ISSUE THREAD

**Issue by rfgamaral** [moonlight-stream/moonlight-android#278]
Sorry if this is not the appropriate place for this but I have a question that's basically what the title states.

From time to time I check my bitrate setting on the Moonlight app only to find out that it was - somehow - reset to 20mbps. I didn't do it myself. I normally have this value way between 50mbps and 80mbps (still trying to find a balance between quality and lag).

So, in what circumstances can this setting change by itself?

Could this be a bug?

**Comment by cgutman** [comment]
The bitrate will change if the resolution/FPS settings are adjusted. It shouldn't change on its own under any other circumstance. I don't totally like that it works that way, but I think it's necessary to prevent users from ending up with bitrates that are far too high or low for their selected resolution.

**Comment by rfgamaral** [comment]
I never change the resolution/FPS and sometimes the bitrate changes back to the default. Weird.
