### ISSUE TITLE
RTSP error. Streaming doesn't work for me. Sorry if repost.

### ISSUE THREAD

**Issue by GhostlierCrib** [moonlight-stream/moonlight-android#280]
First of all, I'm sorry if this issue was posted before (probably was), but after the brief research I did, I either didn't find anything or it wasn't helpful enough. I just want to say that I'm not that experienced with coding (still studying) and stuff like that so I can't understand the error. So basically every time I want to stream a game I get the following error message : 
Failed to start RTSP handshake 
RTSP DESCRIBE request failed : 500

What I tried to fix it was: 
1. To reinstall both the NVidia drivers and the NVidia experience itself
2. To install the previous 2.x.x version NVidia experience 
3. Tried the Android app on different device (still not working) 
Nothing Worked...

The phone pairs ok with my PC and I can see all the games - not a problem here, but whenever I try to play a game (not matter steam or not) I get the error above. From what I've read I'm starting to think that the new 3.x.x NVidia experience doesn't support third-party streaming services like moonlight (Is that correct? Sorry if I'm stupid) 
I again apologize if the same topic was already discussed but I couldn't find anything that would help me.

**Comment by cgutman** [comment]
Can you zip and upload the contents of your "C:\ProgramData\NVIDIA Corporation\NvStream" folder?

C:\ProgramData is a hidden folder so you may need to enable hidden files and folders to see it.

**Comment by GhostlierCrib** [comment]
Thanks for the fast reply!
Here you go

**Comment by GhostlierCrib** [comment]
Thanks for the fast reply! 
Unfortunately I'm having trouble with uploading the archive to this site even though its a .zip file I still get the "Unfortunately, we don’t support that file type. Try again" error message. I'm using WinRAR if that matters. What am I doing wrong?

**Comment by cgutman** [comment]
Do you have a Dropbox or Google Drive or something that you could just share a link with?

**Comment by GhostlierCrib** [comment]
Here's a google drive link 
https://drive.google.com/file/d/0B8AmmoVAOR5TSzlPS0prdDVNem8/view?usp=sharing

**Comment by cgutman** [comment]
OK, it looks like your hardware doesn't support GameStream. I see a bunch of NV_ENC_ERR_UNSUPPORTED_DEVICE errors. Does GeForce Experience claim your PC is compatible with GameStream?

**Comment by GhostlierCrib** [comment]
GeForce Experience says that my computer is ready to stream.

**Comment by GhostlierCrib** [comment]
![gamestream](https://cloud.githubusercontent.com/assets/22243797/18601282/aa0f2a66-7c6a-11e6-8e03-2e12da6d000d.png)
Here's a picture if that helps

**Comment by GhostlierCrib** [comment]
![nvidia](https://cloud.githubusercontent.com/assets/22243797/18601393/411a5a52-7c6b-11e6-907e-fe03e3732b40.png)

**Comment by GhostlierCrib** [comment]
So is there anything I can do? Or Its just a problem with my hardware (if so why does Nvidia say its ok to stream)? Is my Android the problem? (I tried both my phone and tablet)

**Comment by GhostlierCrib** [comment]
So a quick update after today's NVidia updates : I'm still not able to stream however sometimes the error message is different. I'm still getting the "Failed to start RTSP handshake RTSP DESCRIBE request failed : 500" but every 3rd or so time (or sometimes when I just resume the stream) I'm getting a "Failed to start RTSP handshake unable to connect to UDP port 48010". Any fix or I should just give up?

**Comment by cgutman** [comment]
You may try the hack that allows you to stream with an unsupported GPU. I have no idea whether it still works with GFE 3.0.

Here are some forum posts that may help:
http://forum.xda-developers.com/showpost.php?p=63335126&postcount=163
http://forum.xda-developers.com/showpost.php?p=58700543&postcount=132
