### ISSUE TITLE
4K GFE or GPU not supported problem, 2.11.4.1 version of GFE running

### ISSUE THREAD

**Issue by AydinUK** [moonlight-stream/moonlight-android#281]
Hi there,

I'm able to run 1080p 60fps over wifi however 4k 30 - 60 fps defaults back to 1080p.

My PC monitor is an Acer 4k. I also tried it with a non-4k monitor, 3440 x 1440 but the same thing happens. My GPU is a 980Ti and my GFE version is 2.11.4.1

The phone is a Samsung S6 which has a native res of 2560 x 1440.

Any suggestions? 

Thank you

**Comment by cgutman** [comment]
You'll need to update to GFE 3.0 in order to use 4K.

**Comment by AydinUK** [comment]
Thank you very much kind sir! It has worked brilliantly :+1:
