### ISSUE TITLE
Can stream with audio but no video

### ISSUE THREAD

**Issue by jmauss** [moonlight-stream/moonlight-android#284]
Currently using Nvidia Geforce Experience 3 with a 1070. I can pair and control the computer through my nexus 6p fine, but when the stream starts I get audio but no video. I have tried everything in the troubleshooting guide (reinstalling GFE, turning firewall off, rebooting devices) with no luck. Any help?

EDIT: Also not working on Pixel C Tablet

**Comment by cgutman** [comment]
This is currently a known compatibility issue with GFE 3.0.7. NVIDIA seems to have changed the packet format of the video stream, so Moonlight can't currently decode it. I'm going to try to look into this tonight.

**Comment by jmauss** [comment]
Thanks for the quick update, glad to know its already a known issue. Decided to give this a try today, so I suppose I can wait a bit longer.

**Comment by cgutman** [comment]
A fixed build is updated to the Play Store and should be live in a few hours. If you want you can grab the APK from https://github.com/moonlight-stream/moonlight-android/releases/tag/v4.7.2 and confirm it's fixed.

**Comment by vonkoda** [comment]
Will it be released to the Amazon store soon too (for Fire TV devices)?  Same issue here.

**Comment by cgutman** [comment]
It should be live on the Amazon store too. What version of Moonlight does your Fire TV have installed?
