### ISSUE TITLE
4K TV and 1080p Monitor

### ISSUE THREAD

**Issue by Xnome** [moonlight-stream/moonlight-android#288]
Sorry if it is a dumb question. but I am about to invest in a GTX 1080 for this very sole purpose. I have a 4k android TV on which I stream my games using Moonlight. 

so, my question is if I buy a GTX 1080 can I stream 4k to my TV using the option in setting for 4k 60fps even though my PC monitor isn't 4K? how will the resolution work? I don't want it just to upscale but pure 4K. I hope someone can help me. I don't want to just buy the card and realize that I need to buy a 4k monitor too!

Thanks for your help. I appreciate it.

**Comment by muffinmannameistaken** [comment]
it will work just fine i stream everything to my tablet and it has a 2k display, my computer monitor is and old school with a res of 1600x900, i barely use it now, also nvidia cards have DSR.

**Comment by djarcas** [comment]
If you add a custom resolution to your PC, it'll downsample it so it's visible on the 1080p screen, but the streaming should work just fine streaming 4k
