### ISSUE TITLE
All streamed games are automatically optimized

### ISSUE THREAD

**Issue by merschdawg06** [moonlight-stream/moonlight-android#289]
After upgrading to the new GFE I started experiencing an issue where both Gamestream and Moonlight will automatically optimize my games even when the option is unchecked in Gamestream/Moonlight.  For example, it will force lower graphical settings in games like GTA V when you stream it to a Shield TV.  Below is a link to the Nvidia forums with people experiencing the same issue.  Is this something that Moonlight can fix or is it an issue on Nvidia's side?  Tried reinstalling everything and it hasn't helped.

https://forums.geforce.com/default/topic/969888/shield-hub/all-games-automatically-quot-optimize-quot-when-streaming-from-my-pc/

**Comment by cgutman** [comment]
This is a bug on Nvidia's side. They know about it. - https://forums.geforce.com/default/topic/971499/gamestream/gamestream-settings-game-optimization-problem-/
