### ISSUE TITLE
Moonlight can't see PC

### ISSUE THREAD

**Issue by Xanatos55** [moonlight-stream/moonlight-android#290]
Recently I left my home on 10/5 before I left everything was working fine I moonlight could play all my games everything was working. When I got back on 10/11 now moonlight can't see my PC at all. I tried searching for it from the IP and it doesn't see it still. My computer was not touched the entire time I was gone. Is there anything I can do to make it work again?

**Comment by KiddoProgrammer1015** [comment]
I have the exact problem.. Used to work..
