### ISSUE TITLE
Repeated "Poor network connection" while streaming

### ISSUE THREAD

**Issue by joesaiditstrue** [moonlight-stream/moonlight-android#292]
Lowering quality doesn't seem to matter.  Connection was wireless 802.11ac,  changing to ethernet didn't solve the issue

Windows 10 x64, Latest GFE, and nv driver, 980 ti gpu/Intel 3770k/16GB.  games are installed on an ssd.

**Comment by soetdjur** [comment]
Hello Joe!

I'm having the same problem, but my poor network connection problem ends when I lower the bitrate to 70mbps or less. I've also tried with a USB 3.1 tether and that gave similar results as wifi.

I suggest you try USB Tethering and see if it helps your speed. Also, make sure you force h.265 decoder in the moonlight settings.

**Comment by laurentquark** [comment]
hi, how to use USB Tethering instead of wifi connection ? thank's
