### ISSUE TITLE
Pixel C + Android 7.0 = No H265

### ISSUE THREAD

**Issue by DaTraSX** [moonlight-stream/moonlight-android#293]
Hey Foaks,

Been playin with Moonlight for a Long time on my Nexus 6P and wanted to try it Out with my new Pixel C.
But sadly, Moonlight is Not able to Play with h265 enabled.

Thing is that the SoC, the Tegra X1 should definitly Support it?
Or am I wrong? Would be Happy if someone could Check this Out?

**Comment by cgutman** [comment]
You're correct that the Tegra X1 supports H265. However, the default H265 bitstream causes a massive unplayable video delay on Tegra X1, so it has been blacklisted until I find an H265 processing library that allows me to modify the stream to improve performance.

**Comment by DaTraSX** [comment]
Aw man, thanks for the quick answer!

Really hope you'll find a way, as I was so eager too stream my games on a nice big screen. Thought the X1 SoC would be ideal for this...

Good luck mate, keeping fingers crossed!

**Comment by MichaelReineke** [comment]
I actually bought a Pixel C at launch primarily for using it with Moonlight; was immediately disappointed, but you can't blame me for assuming it's X1 would offer epic H.265 streaming latency, plus it supports 2x2 MIMO 5GHz AC.  I have an Xbox One S controller connected to it via Bluetooth...  Just waiting for support.

I hope you'll be able to add support at some point.

**Comment by genmatrix** [comment]
Anyway to make use a different profile? No idea if this is useful or possible but I took a screenshot of the codecs AIDA64 on the pixel c 7.1.1. https://drive.google.com/file/d/0B7aP6ykFh7PdQlFvMWxDVkMzY1k/view?usp=drivesdk

**Comment by NizarOukhchi** [comment]
I'm planning to buy a pixel c in order to use it with moonlight stream, it still playable with h264 or i should drop the idea ?

**Comment by DaTraSX** [comment]
Hey, it's been quite a while since I opened this ticket.
Did something change in the meantime?

Thank you :)

**Comment by cgutman** [comment]
Improved in v5.6.1. It's now playable with H.265 but the latency is 2 frames higher than H.264.
