### ISSUE TITLE
Controller Issue. Help required.

### ISSUE THREAD

**Issue by Xnome** [moonlight-stream/moonlight-android#295]
Hello. I enjoy this app and is one of the reasons I have gotten back to gaming.

I have a Sony Android TV, so I have installed the moonlight Android app, and I can stream my games just fine. In the past I have played Mirrors Edge, though, the PS4 keymapping was all weird and wrong; it was playable. Currently, I am playing Mafia III, I agree that they have very bad controller support. However, when I go to controller presets it shows blank, and it is missing some keys, which makes the game unplayable. I do have the option in settings of moonlight ticked, to use the Xbox controller driver.

However, I tried connecting my controller to PC with a USB wire and used DS4 by windows and voila! It worked just fine with all keymapping and all button prompt. The only problem is that my PC is in the other room and I don't have a big wire and the USB range is very low. Is there something I can do  so that PS4 controller will show all the keymap correctly? I thought of Sixaxis, but it requires root and rooting my TV is sadly, not an option.

I hope the good people are here might be able to help me out, somehow. I hope I can play this game on my Android TV from my couch!

**Comment by cgutman** [comment]
So to clarify, you're saying that the default button mappings of the PS4 controller aren't correct? Can you navigate around the Steam Big Picture UI and just confirm that the mappings are indeed wrong?

After you do that, try this APK and see if the mappings are correct with it: https://www.dropbox.com/s/l9bd0v3r0z9f4f2/sony-ds4-test.apk?dl=0

**Comment by t184256** [comment]
> The only problem is that my PC is in the other room and I don't have a big wire and the USB range is very low.
Sorry for being irrelevant to Moonlight, but... just connect your DS4 to PC over bluetooth, bypassing Moonlight. If that solves the problem for you, why not?
