### ISSUE TITLE
Xbox 360 pad on Nexus Player, DPAD inoperable

### ISSUE THREAD

**Issue by cr08** [moonlight-stream/moonlight-android#296]
Subject TL;DR. Got my Razer Onza controller and it all works great (even lights up the player 1 spot on the controller correctly). Sticks, triggers, and buttons all map correctly save for the d-pad.  Doesn't detect at all. I can go in the controller mapping in my games to try and set the d-pad and don't get any response. Any thoughts?

**Comment by cgutman** [comment]
This should be fixed in v4.7.3
