### ISSUE TITLE
Is Nougat supported? Streaming is hopeless won't work..

### ISSUE THREAD

**Issue by KiddoProgrammer1015** [moonlight-stream/moonlight-android#297]
I messed with the firewall opened all ports and just the recommend ports. I uninstalled and reinstalled rebooting each time because I heard that 3.0 had some issues... I do have a nexus 6P with the new Nougat os so that couldn't be the issue? Could someone link me to the 2.0 experience download to see if that would help thanks..

**Comment by cgutman** [comment]
Nougat is supported. What happens when you try to stream?

**Comment by KiddoProgrammer1015** [comment]
It doesn't stream at all I can't get up or nothing to connect at all and I filled all the wiki process added recommended ports to firewall and clean installed GeForce experience.. should I clean install all of Nvidia?

**Comment by cgutman** [comment]
Clean install with the latest 375.70 drivers which come with a newer version of GeForce Experience.
