### ISSUE TITLE
Cannot stream with DS4

### ISSUE THREAD

**Issue by Dark360x** [moonlight-stream/moonlight-android#298]
so I have a really weird problem. I have oneplus3 and sixaxis controller app

so moonlight works flawlessly without a controller and with DS3 controller.

But when I use DS4 I cannot use moonlight, every time I connect it gives my all kinds of error starting from port 47984 and ssl error.
notice I use bluetooth for ds3 and ds4
does anyone know how to fix this issue

**Comment by cgutman** [comment]
Are you using a 5 GHz wireless network? It sounds like Bluetooth may be interfering.

**Comment by Dark360x** [comment]
No I'm not 
one thing to note that with my galaxy s3 both controller "ds3 and ds4" works great with moonlight 
the problem is when I use moonlight with oneplus 3 and sixaxis controller to pair the DS4
