### ISSUE TITLE
Stuck at Nvidia Gamestream startup screen

### ISSUE THREAD

**Issue by powerbuoy** [moonlight-stream/moonlight-android#30]
I realise this isn't a problem with the Limelight app, but I've already tried the Nvidia support and unsurprisingly they didn't help. 

I can connect just fine to my GTX680 powered PC and get a list of games / apps. But whenever I try to launch a game it just gets stuck at the "NVIDIA Gamestream" startup screen. I've tried waiting several minutes and the computer seems to do some work (HD makes noise and lights are flashing) but nothing happens. 

Anyone else have this issue?

**Comment by cgutman** [comment]
Re-open if this is still an issue.

**Comment by ThaDoc** [comment]
I seem to have the same problem. Desktop stream works but when I launch a game it hangs on de loading screen. No error output. I tried on both my phone and tablet, same issue.
