### ISSUE TITLE
"Connection Terminated" issue (GFE 3.1.0.48)

### ISSUE THREAD

**Issue by ghost** [moonlight-stream/moonlight-android#300]
Moonlight won't stream anymore. It just say "Connection Terminated" issue even it passed through. It also happen on Moonlight Chrome v0.61 as well but it auto closes without any errors. I uninstalled GFE, ran CCleaner, reboot PC and installed GFE but still not working.

Anyone have the same problem?

Message logs:

```
Starting - (name of games/apps)
Starting RTSP handshake
Starting control connection
Starting video stream
Starting audio stream
```

Catlog:
[2016-10-25-14-13-27.txt](https://github.com/moonlight-stream/moonlight-android/files/550533/2016-10-25-14-13-27.txt)

Screenshot:
![screenshot_2016-10-25-12-01-40](https://cloud.githubusercontent.com/assets/8687585/19682633/cc196c36-9aae-11e6-8f15-7cfe23b83397.png)

**Comment by towfiqi** [comment]
Same Issue here..

**Comment by cgutman** [comment]
@towfiqi Please zip the logs in your C:\ProgramData\NVIDIA Corporation\NvStream folder and post a link here.

C:\ProgramData is hidden so you may need to enable hidden files to see it.

**Comment by towfiqi** [comment]
Many thanks for quick reply. Please check the attachment.


[NvStreamerCurrent.txt](https://github.com/moonlight-stream/moonlight-android/files/557831/NvStreamerCurrent.txt)
[NvStreamerOld.txt](https://github.com/moonlight-stream/moonlight-android/files/557832/NvStreamerOld.txt)

**Comment by cgutman** [comment]
Hmm, this is an error I've never seen before. It looks like GameStream is aborting the stream because there's DRM-protected video content being displayed. Try closing any background applications and try streaming again.

#3(W)[2016-10-28 07:42:57,208]{00008038}<Fbc6FrameProvide> Failed to grab frame as it is protected content.
#4(E)[2016-10-28 07:42:57,208]{00008038}<Fbc6FrameProvide> Failed to grab frame: -4 (NVFBC_ERROR_PROTECTED_CONTENT).
#5(E)[2016-10-28 07:42:57,208]{00008038}<CaptureThread>    Failed to capture frame 0.
#6(I)[2016-10-28 07:42:57,208]{00008038}<CaptureThread>    Finished with status STATUS_GRAB_ERROR after capturing 0 frames

**Comment by evildog1** [comment]
@towfiqi try download GFE 3.1.0.52 http://us.download.nvidia.com/GFE/GFEClient/3.1.0.52/GeForce_Experience_v3.1.0.52.exe

**Comment by xchannels** [comment]
I have the same problem. I'm using GFE 3.1.0.52. It is happen on GFE 2.x.x too, so i guess it's Moonlight issues.

**Comment by cgutman** [comment]
@xchannels These types of issues are almost always software interactions with GeForce Experience on your PC and not an issue specific to Moonlight. Make sure you don't have any software that may interfere with it: https://github.com/moonlight-stream/moonlight-docs/wiki/Troubleshooting#known-application-compatibility-issues

If that doesn't solve it, please post the NVIDIA logs I asked for above and I'll take a look through them.

**Comment by towfiqi** [comment]
Guys. Thanks for your input. I resolved the issue by installing the latest version of GFE. Also try closing all the programs that are running in the background from windows taskbar.

**Comment by evildog1** [comment]
Good to know that you resolved the issue

@cgutman
Here are the following remote softwares that doesn't affect GFE
- Chrome Remote Desktop
- Remotr
- Splashtop 2
