### ISSUE TITLE
HTC One M9 - No h.265 decoder found

### ISSUE THREAD

**Issue by The3DLink** [moonlight-stream/moonlight-android#305]
Phone is an HTC One M9 (Snapdragon 810). Aida64 shows there's an HVEC decoder present, but I'm getting the "no h.265 decoder found' message. Streaming from a GTX 1060.

**Comment by The3DLink** [comment]
Ok, looked into things a little further. Seems I'm missing "OMX.qcom.video.decoder.hevc", but I seem to have a different HVEC decoder present "OMX.google.video.decoder.hevc".

I'm running the HTC developer ROM, Android 6.0 version

**Comment by cgutman** [comment]
The Google HEVC decoder is a software-only decoder. Moonlight will only use hardware decoders like OMX.qcom.video.decoder.hevc. You'll need to figure out why that codec is missing.

**Comment by The3DLink** [comment]
Thank you for the reply and for all the work you've put into Moonlight. 

After some heavy searching I found someone else with a similar issue. I don't know why it's missing (along with some other hardware decoder codecs, too). I've been trying to figure out a way to manually add it to my .ect/media_codecs.xml file, but anytime I edit it - I lose *all* of my codecs. 

I'm going to try to flash an updated version of the developer ROM/Firmware in hopes that it'll fix it. I'll update this issue with the results, in case others run into the same problem.
