### ISSUE TITLE
Can't get 5.1 audio on my i68G box (lollipop 5.1.1) while game streaming from Win7x64 PC

### ISSUE THREAD

**Issue by veggy432** [moonlight-stream/moonlight-android#306]
Hello,
I've just discovered this wonderful project and it's working fine for me, my setup is Win7x64 pc with GTX760 which I'm using to stream to an android TV box i68G (with lollipop 5.1.1) connected to yamaha home theater as well.
while I can stream any game or even the desktop on the android box with good quality I can't in any case get the 5.1 audio to the android box (and then in turn to my home theater system), now the Kodi app on android works fine on 5.1 output (i can check right on the home theater display it shows 5.1 channels), when I'm using games or remote desktop I can only receive 2.0 channel input from pc...
I've enabled the 5.1 option on moonlight app (root version), but it makes no difference, 
any help is greatly appreciated since streaming games is just missing good audio to be perfect!!
thanks a lot
greetings, Giulio.

**Comment by cgutman** [comment]
When you stream 5.1 using Kodi, are you streaming Dolby surround sound or 5.1 PCM?

**Comment by veggy432** [comment]
with kodi depends on what audio track is the movie file, sometimes I have DTS 5.1 or some other times It's Dolby digital 5.1, that's in the "signal info" on the yamaha home theater, also I have the option "enable dolby digital transcoding" active in Kodi.
any help greatly appreciated, I can submit more tech info if required

**Comment by sdestan** [comment]
have you solved your problem ?
