### ISSUE TITLE
Streaming the Entire Desktop

### ISSUE THREAD

**Issue by Xnome** [moonlight-stream/moonlight-android#307]
Can someone walk me through how to setup Remote Desktop for Moonlight?

C:\windows\system32\mstsc.exe 

First of all, I can't seem to find this directory through Nvidia Gamestream. the last mstsc.exe.

Secondly, I just pasted the link on the Directory and then Remote Desktop Pops up. I enter my Host Computer name and it says "your computer could not connect because you already have a console session in progress" I don't recall any other remote desktop session except this being in progress.

Am i suppose to entire the Host PC name in the Remote Desktop or my Android Name? Btw i want to stream it to my Android TV. I can stream it the normal way just way fine.

All the help would be greatly appreciated.

**Comment by cgutman** [comment]
Did you try to add it using the 'Games' tab in GeForce Experience or the 'Shield' tab?

**Comment by Xnome** [comment]
Yes. If i go to the "Games" Tab in GeFroce and try to navigate, i can only go till C:\windows\system32. It doesn't show mstsc.exe

However, if i try to paste the C:\windows\system32\mstsc.exe in the Directory when the window pops up after i press add in the Games section of Geforce, the Remote Desktop pops up and then when i put my HOST PC name, the error i mentioned above. i.e. "your computer could not connect because you already have a console session in progress"

**Comment by cgutman** [comment]
You should use the Shield tab instead to add mstsc.exe for streaming.

**Comment by Xnome** [comment]
Oh alright! I'll try that. Thank you. Btw did the new update break something? My PC is showing offline mode. Nothing seems to wake it up. tried multiple restarts and uninstalled the Moonlight app and now its stuck on searching for PC
