### ISSUE TITLE
Multiasking while Streaming

### ISSUE THREAD

**Issue by leannecrow** [moonlight-stream/moonlight-android#310]
I just got it working and played a little Crysis 3. **Cool stuff**

But one thing I noticed off the bat was that the computer completely dedicates to the Nvidia Gamestream. I had imagined I could both stream the game on the phone and have the ability to do things on the computer. 

So that way, I could work on the machine while someone else could be streaming game off the computer. Is this possible with some sort of work around? 

~~Another thing I wanted to do is as Moonlight has support for 4k, I wanted to test it out and see if my graphic card can handle it (how bad it can handle :P) My phone is Nexus 6 so like 1440p and my monitor is 1080p. Is there someway to send upscaled version of the game to the device?~~ _http://www.neogaf.com/forum/showthread.php?t=509076_

With my brief experience with "Nvidia Shield", it seems to be virtual desktop with Nvidia badge on it.

**Comment by t184256** [comment]
Why did you close it?

**Comment by leannecrow** [comment]
Turns out it's not possible. Nvidia Shield behaves in the same way I 
thought it didn't.
