### ISSUE TITLE
OTG Mouse support issue

### ISSUE THREAD

**Issue by iceman2k** [moonlight-stream/moonlight-android#312]
Hello. I'm very thank you about this app.

I have a mouse right click issue. Left click is fine.
But when I try right click, just flash another mouse cursor and anything happen in the games.
It feels like the android OS intercept that input.

My device is LG V20 with android 7.0.
GFE/Driver and Moonlight is lateset version.
OTG Connected with the Logitec unifying dongle.

Please check this.

Thank you again for this great app!

**Comment by evildog1** [comment]
You need a rooted device to support right click

**Comment by cgutman** [comment]
Should be fixed
