### ISSUE TITLE
my app close before video streaming process

### ISSUE THREAD

**Issue by DayanVp** [moonlight-stream/moonlight-android#313]
Hello, excuse me for my bad english.
I have the next problema, I have downloded the app from the play store and I have tested that connecting my phone and pc. It works correctly. So, I decided download the source code for Android. The compilation process is successful but when I try run a game my app crash. I would like if there is some solution for that or what is the reason why it does not work. I wait your big help.
Thank you.

![screenshot_2016-12-09-19-37-00](https://cloud.githubusercontent.com/assets/19496105/21069459/229ff1a8-be48-11e6-8128-feda8edd7d97.png)

**Comment by evildog1** [comment]
A logcat is the best way to find the errors of your app
https://developer.android.com/studio/command-line/logcat.html
