### ISSUE TITLE
Touchscreen right drag? 

### ISSUE THREAD

**Issue by JuliusCaius** [moonlight-stream/moonlight-android#314]
There's a touch gesture for left button dragging, but none for right button dragging. Could this be implemented?

**Comment by evildog1** [comment]
Press 2 fingers on the screen at the same time for right click.
You can do the same with trackpad on any newer laptop and macbook

**Comment by JuliusCaius** [comment]
What you describe with two fingers makes a right CLICK (after releasing the fingers), but not a right DRAG (when keeping the two fingers on the screen, it actually behaves like a left drag). There's currently no right DRAG implemented, as far as I know.

**Comment by evildog1** [comment]
Sorry, never heard of right drag.

**Comment by MT76** [comment]
Found this when looking for the answer for this question. Is right drag already implemented? If so, how to do it?
