### ISSUE TITLE
Add isgame flag for better performance

### ISSUE THREAD

**Issue by ksya** [moonlight-stream/moonlight-android#315]
I have a Sony TV and it automatically adjust it's settings when a game is started. Moonlight is not advertised as a game and thus these changes aren't adjusted automatically. It is very easy to do this, just add: " android:isGame="true" " to the androidmanifest application tag.

I have rebuild the apk myself, but for future official versions I like this tag enabled! Thanks!

**Comment by cgutman** [comment]
Interesting. Can you describe what the settings changed are? Or some documentation that suggests games are treated differently?

**Comment by ksya** [comment]
These are settings a TV would normally do by setting it in "Game mode". It turns all image enhancement settings off to lower the response time. I see great difference with my build and the standard build.

Since the Sony TV is based on Android TV, it also sees that a game is different from a normal app and thus activates this "Game mode", but only if it is marked as so. This can be done using the android:isgame flag in de AndroidManifest.xml: https://developer.android.com/training/tv/games/index.html#manifest

**Comment by cgutman** [comment]
Fixed in v4.8.3

**Comment by diogosena** [comment]
this isgame flag, is breaking HDR in sony tvs
