### ISSUE TITLE
Send separate left and right codes for ALT SHIFT and CTRL on a keyboard

### ISSUE THREAD

**Issue by georgcmef** [moonlight-stream/moonlight-android#318]
I am just wondering if there is a way to differentiate between the left and right modifiers for gamestream?
I mainly want to use it for Starcitizen, the game has different functions depending on what modifier keys are pressed.

Thank you.

**Comment by maidik** [comment]
Yes! I have this same issue. It appears to be the same on all platforms. Anyone even acknowledged this yet?

**Comment by cgutman** [comment]
We know about it. It's a limitation of the GameStream protocol that it has no way to send different left and right modifiers.

**Comment by cgutman** [comment]
Actually my response was complete BS. GameStream does support sending separate left and right modifiers, in fact Moonlight Chrome already does. Doing this for Android should be trivial.

**Comment by cgutman** [comment]
Fixed
