### ISSUE TITLE
Big Picture Mode recognizes 4 controller, instead of one (newest Steam beta)

### ISSUE THREAD

**Issue by M0rr1s0n** [moonlight-stream/moonlight-android#321]
The newest Steam beta update added the support of Steam controller configuration for X-Input devices (see here [Steam Client Beta Update - Jan 5th](http://steamcommunity.com/groups/SteamClientBeta#announcements)) When starting Steam Picture Mode via Moonlight, Steam identifies 4 generic USB controller instead of just one, even when changing the corresponding entry in the options menu (disable multi controller support).
This makes it difficult to navigate BPM at all, because every button press on the Shield Controller launches 4 actions at the same time.
This does not happen in the official Shield Hub app.

**Comment by cgutman** [comment]
I can't reproduce this issue running Moonlight Android v4.8.3, the Jan 5 Steam Beta update, and GeForce Experience 3.2.2.49.

Steam does show 4 controllers (which has been the case for years and is merely a cosmetic issue). The input issue with 4 actions does not reproduce for me.

What version of GeForce Experience are you using?

**Comment by M0rr1s0n** [comment]
I use the same setup (ML 4.8.3 and GE 3.2.2.49). Under "Base configuration" in BPM, did you set any custom settings for navigating the Big Picture Mode?

**Comment by cgutman** [comment]
I did eventually get it to happen on the Jan 5 update. However, I can't get this issue to happen on the Jan 10 Steam Beta update. Can you try again and see if it still happens after you update? 

If so, can you tell me which controller configuration checkboxes you have checked?

**Comment by M0rr1s0n** [comment]
I just got the update, will try later when my Shield Tablet is running! Thanks for staying on this, I will report back!

**Comment by M0rr1s0n** [comment]
Ok, I tried it a few times today and it now works for me as well! Also now the Shield Controller is recognized as a Xbox 360 controller via Steam and not "just" as an X-Input device. At least for me!
So the issue was probably on Steams end and Moonlight works fine as ever :)

**Comment by nileplumb** [comment]
https://github.com/moonlight-stream/moonlight-ios/issues/264
https://github.com/xyzz/vita-moonlight/issues/81

Having this issue still 
![screenshot 2017-01-16 10 02 56](https://cloud.githubusercontent.com/assets/12138502/21978631/534d5f68-dbd3-11e6-81f9-afeb6486e860.png)

**Comment by M0rr1s0n** [comment]
Actually now and then, the problem still occurs for me. I rolled back to Steam Non-Beta, but it didn't help wit this :/

**Comment by nileplumb** [comment]
I'm noticing latest geforce and latest steam beta appears to have fixed this currently

GeForce 3.4.0.70
Driver 378.66
Steam Beta Feb 22
