### ISSUE TITLE
Error 521

### ISSUE THREAD

**Issue by Arukkese** [moonlight-stream/moonlight-android#334]
GFE error: Streaming session has failed to a streaming error (Error code: 521)
GFE version 3.3.0.95
Before I update normal use
Error 521 occurs after updating to 3.3.0.95
I do not know what this is
Please answer

**Comment by Arukkese** [comment]
In fact the game can be displayed, but no icons
Error 521 will occur when you open any game
I think this should not be a problem with GFE
Before can be used very well, now I am confused

**Comment by cgutman** [comment]
Please try with the GFE hotfix: https://nvidia.custhelp.com/app/answers/detail/a_id/4397

**Comment by seelenfrieden** [comment]
THANKS! This hs fixed my issue depending on issue gfe error 521
