### ISSUE TITLE
Streamed Game Thumbnails No Longer Showing

### ISSUE THREAD

**Issue by MrScruff300** [moonlight-stream/moonlight-android#335]
Using Moonlight on Nexus 7 have latest version available through Play Store. Recently the thumbnails for my streamed games have disappeared, just get a swirling blue circle then nothing. Games still stream when selected.

**Comment by MrScruff300** [comment]
As an update to this issue, I managed to fix the issue by rolling back Geforce Experience version to v2.11.4.0 as soon as I synced moonlight on my Nexus with this version the game thumbnails appeared in the hub screen. As soon as I updated Geforce Experience to the newest version v 3.3.0.95 and reopened moonlight on my Nexus same old issue thumbnails do not load on gamestream games. If I add my own games and thumbnails through GFE they do appear, it's just the games that moonlight automatically recognises. Seems to be something broken between moonlight and latest GFE, is it possible to fix this? Thanks

**Comment by thw0rted** [comment]
I have the same issue. I'm streaming to Android (Nexus 5) and Fire TV Stick from GFE 3.3.0.95.  Both show cover art only for custom added games. Maybe something changed in a recent GFE update?

**Comment by cgutman** [comment]
It's a bug in GFE 3.3. I've provided a workaround here: https://forum.xda-developers.com/showpost.php?p=70764732&postcount=3789

**Comment by thw0rted** [comment]
Wow, that was quick! If Nvidia doesn't fix this soon, maybe put a note with this fix in the Moonlight docs?

**Comment by MrScruff300** [comment]
Awesome! Thanks for the workaround working great now :)!
