### ISSUE TITLE
Controller acting odd (Moga 000353)

### ISSUE THREAD

**Issue by parabolee** [moonlight-stream/moonlight-android#336]
So for some reason when I use my Moga controller with Moonlight on my Samsung Galaxy Tab A 10.1 it often acts strange. It seems to work perfectly in some game, like Dishonored 2 seems to have no issues at all. But when I try and play Watch Dogs 2 it acts like the left trigger is being held down all the time. Witcher 3 is even stranger as it acts like the face button are also pressing some keyboard buttons and the in game ui keeps switchjng back and forth between keyboard and gamepad. Fallout 4 constantly runs forward and to the left.

As you can see, the oddest thing is that all the issues are so different. 

Steam big screen acts funny too, often acting like it is getting  multiple inputs at once. I habe multiple controller support turned off.

What is the best controller to use for Moonlight on Android. I would love to use a DS4 but I don't really want to root this tablet.

Thanks

**Comment by cgutman** [comment]
Try disabling the "Xbox Configuration Support" and "Generic Gamepad Configuration Support" options in Steam Big Picture settings under "Controller Settings". These can cause problems when using Moonlight.

**Comment by parabolee** [comment]
Great, that seems to have done the trick. Thanks!
