### ISSUE TITLE
Host can only stream once

### ISSUE THREAD

**Issue by jackjt8** [moonlight-stream/moonlight-android#337]
Host:
i7-6700hq 2.6GHz, 16GB 2133MHz ddr4, GTX 960m 2G

Clients:
Nexus 7 (2013) & Nexus 5

Issue: First stream works fine minus the Microstutter Problem which was outlined nicely by #214. The issue I'm noticing is that once I exit the first application and move to a second application it refuses to connect with GFE error: Streaming session has failed to a streaming error (Error code: 521). The only solution I can find is to restart the host PC.

[NvStreamerCurrent.txt](https://github.com/moonlight-stream/moonlight-android/files/753263/NvStreamerCurrent.txt)

[DxDiag.txt](https://github.com/moonlight-stream/moonlight-android/files/753266/DxDiag.txt)

**Comment by cgutman** [comment]
Try this GFE hotfix: https://nvidia.custhelp.com/app/answers/detail/a_id/4397
