### ISSUE TITLE
PC not found even after disabling firewall - port listening only on local host could be a coulprit

### ISSUE THREAD

**Issue by fmatyas** [moonlight-stream/moonlight-android#339]
Dear community,

I am getting tired of trying ot resolve the issue on my local network. There is a porblem with the newest version of Nvidia driver and GeForece Experinece  (GeForce_Experience_v3.3.0.95) and my PC. 
I am running a Win 10 wiht GTX 1060 6GB, before the updates everything worked, but I even after rolling back the GeForce experience to 2.* or 3.2* I cannot get a Moonlight to discover the PC.
I ask for help..
I have tried accessing: **http://127.0.0.1:47989/serverinfo** and **http://192.168.2.102:47989/serverinfo** and I get promising promt on the locasl machine:

> <?xml version="1.0" encoding="UTF-16"?><root protocol_version="0.1" query="serverinfo" status_code="200" status_message="OK"><AuthenticationType>1</AuthenticationType><ConnectionState></ConnectionState><CurrentClient>1</CurrentClient><ExternalIP></ExternalIP><GfeVersion>3.2.0.96</GfeVersion><GsVersion>gs_03_50_21453947</GsVersion><HttpsPort>47984</HttpsPort><LocalIP>192.168.2.102</LocalIP><LocalIPs><Address>192.168.2.102</Address></LocalIPs><MaxLumaPixelsH264>538181568</MaxLumaPixelsH264><MaxLumaPixelsHEVC>359669952</MaxLumaPixelsHEVC><Mode>0</Mode><PairStatus>0</PairStatus><ServerCapability>823</ServerCapability><ServerCodecModeSupport>69379</ServerCodecModeSupport><ServerColorSpaceSupport>2</ServerColorSpaceSupport><SupportedDisplayMode><DisplayMode><Height>2160</Height><RefreshRate>60</RefreshRate><Width>3840</Width></DisplayMode><DisplayMode><Height>2160</Height><RefreshRate>30</RefreshRate><Width>3840</Width></DisplayMode><DisplayMode><Height>1080</Height><RefreshRate>60</RefreshRate><Width>1920</Width></DisplayMode><DisplayMode><Height>1080</Height><RefreshRate>30</RefreshRate><Width>1920</Width></DisplayMode><DisplayMode><Height>720</Height><RefreshRate>60</RefreshRate><Width>1280</Width></DisplayMode><DisplayMode><Height>720</Height><RefreshRate>30</RefreshRate><Width>1280</Width></DisplayMode></SupportedDisplayMode><accountId>72C4EAF25E6C2EC81B4322A1EE4CBB0D3D4364924F39402529E1062D8A12ADCE</accountId><appversion>7.1.350.0</appversion><currentgame>0</currentgame><gamelistid>75f5f96a5f7abe43c2f55368511d9091</gamelistid><gputype>GeForce GTX 1060 6GB</gputype><hostname>FARKAS-PC</hostname><mac>9C:5C:8E:B2:3E:6B</mac><numofapps>10</numofapps><resyncSuccessful>0</resyncSuccessful><state>MJOLNIR_STATE_SERVER_AVAILABLE</state><uniqueid>e61f3965-5e18-41f1-b829-f9d85133ae22</uniqueid></root>

but I fail to access it over the home WLAN network. 
Running **>netstat -a -n -b**
I get the following:

[nvcontainer.exe]
  TCP    127.0.0.1:49747        0.0.0.0:0              LISTENING
 [NVIDIA Web Helper.exe]
  TCP    127.0.0.1:49747        127.0.0.1:49783        ESTABLISHED
 [NVIDIA Web Helper.exe]
  TCP    127.0.0.1:49783        127.0.0.1:49747        ESTABLISHED
 [NVIDIA Share.exe]
  TCP    127.0.0.1:50911        0.0.0.0:0              LISTENING
 [ss_conn_service.exe]
  TCP    127.0.0.1:65000        0.0.0.0:0              LISTENING
 [nvcontainer.exe]
  TCP    127.0.0.1:65001        0.0.0.0:0              LISTENING
 [nvcontainer.exe]
  TCP    127.0.0.1:65001        127.0.0.1:49740        ESTABLISHED
 [nvcontainer.exe]
  TCP    192.168.2.102:139      0.0.0.0:0              LISTENING
 Can not obtain ownership information
  TCP    192.168.2.102:49798    8.36.120.11:443        CLOSE_WAIT
 [NVIDIA Share.exe]
  TCP    192.168.2.102:49799    40.77.229.36:443       ESTABLISHED
....

 [nvtray.exe]
  UDP    127.0.0.1:48202        *:*
 [nvspcaps64.exe]
  UDP    127.0.0.1:48203        *:*
 [NVIDIA Web Helper.exe]
  UDP    127.0.0.1:48204        *:*
 [NvStreamUserAgent.exe]
  UDP    127.0.0.1:49665        *:*
 [nvcontainer.exe]
  UDP    127.0.0.1:49666        *:*
 [nvcontainer.exe]
  UDP    127.0.0.1:49669        *:*
 [nvcontainer.exe]
  UDP    127.0.0.1:49670        *:*
 [nvcontainer.exe]
  UDP    127.0.0.1:52921        *:*
 [nvcontainer.exe]
  UDP    127.0.0.1:54183        *:*
 [NvStreamUserAgent.exe]
  UDP    127.0.0.1:58564        *:*
 [NvStreamUserAgent.exe]
  UDP    127.0.0.1:58565        *:*
 [NvStreamUserAgent.exe]
  UDP    127.0.0.1:58567        *:*
 [NvStreamUserAgent.exe]
  UDP    127.0.0.1:58568        *:*
 [NvStreamUserAgent.exe]
  UDP    127.0.0.1:58569        *:*
 [NvStreamUserAgent.exe]
  UDP    127.0.0.1:58574        *:*
 [NvStreamUserAgent.exe]
  UDP    127.0.0.1:58575        *:*
 [NvStreamUserAgent.exe]
  UDP    127.0.0.1:59280        *:*
 [NvStreamUserAgent.exe]
  UDP    127.0.0.1:60442        *:*
 [NVIDIA Web Helper.exe]
  UDP    127.0.0.1:60446        *:*
 [nvcontainer.exe]
  UDP    127.0.0.1:60447        *:*
 [NVIDIA Web Helper.exe]
  UDP    127.0.0.1:60448        *:*
 [NVIDIA Web Helper.exe]
  UDP    127.0.0.1:60449        *:*
 [nvcontainer.exe]
  UDP    127.0.0.1:60450        *:*
 [nvcontainer.exe]
  UDP    127.0.0.1:60451        *:*
 [NVIDIA Web Helper.exe]
  UDP    127.0.0.1:60452        *:*
 [nvcontainer.exe]
  UDP    127.0.0.1:60888        *:*
 [nvspcaps64.exe]
  UDP    127.0.0.1:61562        *:*

If I read it correctly it means that the ports are only open locally, and listen only to the localhost.
I wish to access it over the home network but it fails, I hate to admit but the Speedport Smart Router I have from the German Telekom does not allow for UPnP port forwarding (as it is tailored towards the needs of the regular ??? user).. 
I am connecting to the home network from the PC with an ASUS USB AC55 5Ghz wireless adapter, that is quite stable in speed and access. The android devices tried so far are SGS5 with Marshmallow, Note 4 with Marshmallow and a Note 10.1 2014 with Lollipop.

I would be happy if someone could provide guidance on how to get Game Streaming running!

Best wishes from Germany!

**Comment by Trasen** [comment]
Had similar issues while VM machines where installed, that it binds to one of the abstract network interfaces, not recognizing the default one.

Please check if you're having the same issues with a fresh install/ fresh service start-up file.

Please keep us updated about this.

Best regards
