### ISSUE TITLE
Full screen doesn't  work

### ISSUE THREAD

**Issue by BluTree** [moonlight-stream/moonlight-android#344]
When I launch a game in fullscreen mode (and not in "borderless windowed"), the screen on my mobile is stuck until I do something for prevent the game to be in foreground. For example, when I do the alt-tab and when the interface of the alt-tab appears, i see my game running (on my mobile screen) but when I return to the game, my screen becomes again stucked. The Binding of Isaac : Rebirth do that and i have no way to change how the game is displayed

**Comment by alexwitter** [comment]
Discovered a work around, while fullscreen CTL+ALT+DEL and open "Task Manager" and then close it. should now been streaming what full screen.
