### ISSUE TITLE
Error 544

### ISSUE THREAD

**Issue by aztectornado** [moonlight-stream/moonlight-android#346]
When attempting to start any game from both my devices using GFE latest, it fails to start the app chosen, and displays an error reading "GFE error: Failed to configure streamer (Error 544)"

Tried rolling back GFE to version 2.11.4.0 because I saw it solved a few other issues, but then I got error code 521, which was cited in issue #334 and suggested using hotfix 3.3.0.100 . Using GFE 3.3.0.100 resulted again in the 544 error.

(Chrome ver. of Moonlight also gets a black screen with no sound for around 20~ seconds before noiselessly closing without a given error.)

Devices used: "LG Gpad" VK810 4G (rooted), "LG 4G" VS985 4G (not rooted)
Android versions: 5.0.2 (rooted), 6.0 (not rooted), respectively

GFE versions: 3.3.0.95, 3.3.0.100, 2.11.4.0
GPU: GTX 1060 6GB
Driver version: 378.66 (updated this today, was getting error before that. Can't remember previous ver.)
CPU: Intel i5-6500 @ 3.20ghz
RAM: 8GB

**Comment by cgutman** [comment]
Do you have any anti-virus or firewall products installed on your host PC?

**Comment by aztectornado** [comment]
None. This rig is self built and less than a month old; I haven't installed any protection on it.

**Comment by GhoulMonkey** [comment]
I'm having the same issue. Started happening about a week ago...

**Comment by aztectornado** [comment]
Later had issues with my directx installation; couldn't solve that either so I just reinstalled windows' partition on my SSD and started from the top. 

Seems to be working now, so-... _shrug?_

**Comment by Sparko75** [comment]
You have to downgrade to Geforce game ready driver 378.66 i had the same issue and now it is working

**Comment by aztectornado** [comment]
Er-... I was on that version @Sparko75. Re-read the original post.
