### ISSUE TITLE
Virtual Monitor Android Fork

### ISSUE THREAD

**Issue by plj5003** [moonlight-stream/moonlight-android#350]
Wanted to point out this guys fork. Tested and obviously needs some TLC to nail but wow, the app works pretty well even in this shape. Would be a game changer if this could somehow be merged! Maybe assess the feasibility? Thanks.

Reddit: https://goo.gl/awVOfi
github fork: https://goo.gl/26dEPr

Edit: Biggest issue I can detect is the controller functionality.   Doesn't seem to work both with Xbox one Bluetooth controller to Google Pixel or Wireless Xbox one controller with dongle to host PC

Edit 2: Pull request created.   Check it out! https://goo.gl/cq1M1w

**Comment by JasonS7notG5** [comment]
Equivalent to Samsung users with Gear VR: https://www.reddit.com/r/StreamTheater/

**Comment by plj5003** [comment]
Poking around - seems like that utilizes Gear/Oculus code to implement, which won't be avail for daydream.   Interesting find however.

**Comment by plj5003** [comment]
Looks like the guy that created the fork is trying to clean up some of the outstanding issues.   Anyone curious or who wants to help him:

Reddit: https://goo.gl/awVOfi
github fork: https://goo.gl/26dEPr

**Comment by plj5003** [comment]
Obv this is an enhancement request

**Comment by plj5003** [comment]
The guys fork now works perfect.  Check it out and perhaps consider merging it?

https://goo.gl/awVOfi
