### ISSUE TITLE
Hide games within Moonlight app?

### ISSUE THREAD

**Issue by JasonS7notG5** [moonlight-stream/moonlight-android#351]
I wanted to ask if it is possible to make a hide games option? I can hide them in GeForce Experience but they still show up in Moonlight and I guess also on the original Shield because of NVIDIA logic... this occurs since GeForce Experience 3.0. Could you make a simple option to hide games within Moonlight, for example by long pressing on the game and having a pop-up window saying 'hide this game'? I only want games showing in Moonlight which make sense playing them with a controller. I cant play StarCraft 2 with a controller or many other Blizzard games for example. Older games dont even have controller support. Some even gets displayed two times. I think this 'feature' would be helpful for many people and (without knowing how to write code) I think building such option would be easy enough for experienced programmers like you. I would be glad if you could add this if you have time and feel like making this possible. Thanks.

**Comment by ash-of-time** [comment]
Is any changes in that case?

**Comment by Alkanov** [comment]
Yeah same here I would love to see a hide option

**Comment by Goodix33** [comment]
It would be very nice to have such option in Moonlight. I have 3 times the same game showed on GeForce experience. Just 1 is working and even if I hide the 2 other in Nvidia interface they continue to show up in moonlight
