### ISSUE TITLE
Hardware for Moonlight

### ISSUE THREAD

**Issue by andyleet** [moonlight-stream/moonlight-android#352]
Im searching for new hardware to stream with moonlight on my tv. 
At the moment i use Amazon Fire TV stick but I have some issues with it.

1. I can stream with 720 @60 fps max 
2. Fire TV Stick got only H264 encoder
3. Wlan is a Problem

What should i buy ? Fire TV Box maybe or something else?

Thx

Andy

**Comment by FabianAlbrecht** [comment]
At the moment I can't recommend the Fire TV (non-stick) for moonlight streaming as there are some problems with the latency (see #144 and #170). I hope that there will be a fix in the future.

**Comment by jmseaton** [comment]
I have both FireTV and Nexus Player, the FireTV I get 35ms latency h265, the Nexus Player, is 10ms h264.  If you can find a Nexus Player cheap, try that.
