### ISSUE TITLE
Some game covers do not appear in Moonlight (root)

### ISSUE THREAD

**Issue by hugolima10** [moonlight-stream/moonlight-android#354]
Some game covers do not appear in Moonlight (root) 

When I add in GeForce Experience the cover of the game appears but gets duplicated without one continues without image of the cover.

It seems that when Moonlight searches the cover automatically it does not appear.

How do I fix this?

[http://www.hugo.com.br/moonlight/tela_1.jpg](http://www.hugo.com.br/moonlight/tela_1.jpg)

Thank`s Hugo

**Comment by JasonS7notG5** [comment]
https://forum.xda-developers.com/showthread.php?p=70764732#post70764732

**Comment by hugolima10** [comment]
Perfect. Thank`s Hugo
