### ISSUE TITLE
DualShock controller > Xbox icons ?

### ISSUE THREAD

**Issue by ghost** [moonlight-stream/moonlight-android#359]
Hello,

Like many I use Moonlight to stream my games on my Sony TV (Android). I've paired my PS4 controller to my TV and it works fine. However, the controls displayed in each of the games correspond to the Xbox keys (A, E etc.) and not to the PS4 DualShock controls. What is the solution to display the PS4 controls, a file to modify or do I have to memorize the controls of a controller I do not have ?

Thanks for helping !

**Comment by JasonS7notG5** [comment]
Most if not all PC games do have Xbox controller support but not PlayStation/DualShock support. When you connect your PS4 controller with Moonlight it will 'convert' it to an Xbox controller so you can play your PC games with a controller. If Moonlight would not 'convert' it you would not be able to play with a controller.

PlayStation button layout -> Xbox button layout
X -> A
O -> B
Square -> X
Triangle -> Y
R1 -> RB
R2 -> RT
L1 -> LB
L2 -> LT

**Comment by CorB3n** [comment]
Yes I am aware of that, It could be easier to buy Xbox Controller but my Android TV doesn't accept it, only DS4.
I just wanted to know if it was possible to change layout ingame icons for default DS4 controller instead of x360 one's. Or do I have to listen every Xbox touch :)

Thanks.

**Comment by JasonS7notG5** [comment]
Moonlight does not handle the button symbols in your PC games, so no you can not change it to PlayStation button symbols. Those are handled per game and are not easy to change/replace (if it is even possible which I dont think so) with PlayStation symbols.

**Comment by CorB3n** [comment]
Ok, thanks for your reply. I'll buy Xiaomi Controller witch works with Android TVs & have same controls as Xbox controller !

**Comment by cleever** [comment]
Why this issue still opened?

Like @JasonS7notG5 said, Moonlight does not change any in-game symbol.
First of all, the game developers must support this, by including different symbol assets in their games.

There only a few games that change the symbols depending on the input on PC.

Xbox controller works pretty well on a Sony Android TV. You only need a Wireless Receiver that you can connect it to a USB port from TV. Excluding the fact that vibration doesn't work and the controller keeps his light flashing.

**Comment by thw0rted** [comment]
There are definitely some PC games (and for that matter Steam Big Picture Mode) that detect what kind of controller is detected and respond with the correct symbols.  Does Moonlight set / emulate this information correctly for its virtual controller?  I can't try right now to confirm, but I think the answer is that it does not.  Maybe that's why it's still open -- to see if it's possible to emulate the actual controller type, at least for Dualshock 3 / 4.
