### ISSUE TITLE
Using Moonlight with wired connection via usb.

### ISSUE THREAD

**Issue by BetaLeaf** [moonlight-stream/moonlight-android#362]
This is not an issue but I felt it should be mentioned. 

I have a Desktop I built with portability in mind. I used to have a TV Mounted to the side panel of my tower, but decided that was too heavy and decided to use a tablet instead. You can connect any tablet that supports USB Tethering to a Window's computer and use your tablet as a monitor as well. One benefit is that there is almost no latency at all and the other is a tablet is really lightweight. I'm using an Nvidia Shield Tablet K1 on Windows 10. The specific case I'm using has strong magnets that let me hang the tablet off the side panel. Unfortunately, this does not work at all with Shield HUB included on this tablet. Also, this is not limited to just tablets, a phone works nicely in a pinch as well. I would recommend connecting your input devices directly to the computer, not the tablet.

As a prerequisite, you will need to install the necessary drivers to get USB Tethering to work. Google will help you find the correct drivers for your Android device and version of Windows. You will also need a video terminator (dummy plug). It's basically just fakes a connection to a monitor to trick the GPU into remaining turned on and activated. You can buy an HDMI Terminator for about $10 on Amazon. For DisplayPort, you can use a HDMI to DisplayPort adapter and use an HDMI Terminator. For DVI-I or DVI-D, you can use a DVI-I to VGA adapter and use a VGA Terminator. If you are so technically inclined, you can build a VGA Terminator yourself. [Guide](http://www.geeks3d.com/20091230/vga-hack-how-to-make-a-vga-dummy-plug/). Otherwise, they run for about $13 on Amazon. 

1. Connect the tablet via the usb cable.
2. Start the USB Tether.
3. Start Moonlight. It should be able to detect your computer automatically so manually entering the IP is not needed.
    * If it cannot find it, manually enter the IP of the USB Tether adapter on your Windows PC. 
4. Start a connection using the Desktop (See [Setup Guide - Using Moonlight to stream your entire desktop](https://github.com/moonlight-stream/moonlight-docs/wiki/Setup-Guide#using-moonlight-to-stream-your-entire-desktop))
5. Plug in your port terminator and leave it plugged in for the duration of your session.
    * This isn't necessary if you just want to clone your monitor to your Android device. It is only required if you want to use your Android device as the only display on your computer. 

Congrats, you are now using your phone or tablet as a monitor.

**Comment by sivert-io** [comment]
Would like to confirm that this still works in 2025 😄🎊

Edit: Oh and instead of a dummy HDMI/DP, you can instead use https://github.com/VirtualDrivers/Virtual-Display-Driver if you want to extend your display 🧑‍🍳

There is a slightly older tutorial here that shows how to set it up in Sunshine https://youtu.be/Mysv3ZIFeJs
