### ISSUE TITLE
Amlogic (Mini M8S 2) strange behaviour.

### ISSUE THREAD

**Issue by Trasen** [moonlight-stream/moonlight-android#363]
Hey,

I've been struggling with microstuttering/ framedrops even on "decent" frames (around 30-35ms). This all the way down on 1 mbit in 720p, same issues with no change in frames.

However, last night i pushed the bandwith to 25-35 1080p 60fps (playing around with the lever), and even though there is no difference on the render delay, i no longer experience the same amount of micro-stuttering, i would even call it playable.

Everything running on wire and on a local network.

Any idea what might cause this?

Best regards,

**Comment by Ghotikk** [comment]
Try to open the ports in your router

**Comment by Trasen** [comment]
What good would opening ports on a local network do? There's nothing blocking the transmission, it's definitely a rendering (decoder) bug.

**Comment by Trasen** [comment]
I might add that i solved the microstutters by re-installing my Nvidia drivers with Driver Sweeper. I also installed a new Rom on the box, which seem to have improved the frametime on lower bandwith streams.
