### ISSUE TITLE
Dualshock 4 Controller not working on Galaxy S7 over bluetooth

### ISSUE THREAD

**Issue by mystic3423** [moonlight-stream/moonlight-android#364]
Hey all, hope you guys are doing fine.
Has anyone successfully used a Dualshock 4 controller with moonlight over Bluetooth? I got it working with an OTG cable but I want to try and get Bluetooth working so I could have the ability to charge my phone while using the app. Rooting my phone isn't an option. If there isn't a way to connect a Dualshock 4 controller then is there any other controller that could connect wireless and also be used with moonlight?

**Comment by Trasen** [comment]
Hey,

The Dualshock 4 is pairable by default on Android. Just press and hold the Power-button and 'Select' at the same time, until the light flickers very fast - when it does, go to bluetooth devices on your phone and it should show up as a pairable device.

The functionality however is not ideal, which is why it's recommended using Sixaxis tool (Root) to make it a proper controller.

But try this and then running it through Moonlight with Xinput active, should work as it's intended. Please me/ us know if it works.

Best regards,

**Comment by mystic3423** [comment]
I'm able to pair the controller but there is no input on my device like when I'm connected with an OTG. I believe this to be something with samsung just not wanting to have certain controllers be used on their phones because it had worked on other android phones for me. One thing i haven't tried is the Xinput being active. Not exactly sure what setting that is suppose to be though.

**Comment by Trasen** [comment]
Hey again Mystic,

That's very strange, just earlier today i paired my Samsung A5 2017 with the PS4 controller and it worked fine, the key-mapping is just messed up.

 It's possible that this is a restriction in Android 7 > / Nougat, if you by any chanse is running this on your phone (i would assume that you have it, but i'm not sure how the rollout table has been for the S7).

Xinput was a flimsy expression, i meant that "Xbox 360/ One Controller driver" should be ticked in the settings of moonlight - to make sure that the input  mappings are correct, at least for Moonlight.

But if you are running Nougat, that would most likely be the culprit. Got no solution at hand for that, if you're not running the latest Android on it then tell me. Might simply be the operating system simply doesn't understand that it's a controller, and that you need to set it up through Bluetooth to manually be recognized as a "Input device".

Looking forward to your response,

Best regards.

**Comment by mystic3423** [comment]
Hey Transen,

Thanks again for your advice. I do have "Xbox 360/One Controller drive" checked. No input is working at all. I don't think the restriction is nougat because when my S7 was running Marshmallow I had the same issues with Bluetooth. Also, in Marshmallow i wasn't even able to to get the controller working with an otg cable, but in nougat using an otg cable with my DS4 works perfectly fine, correct button mappings and everything. It is recognized as an input device also, as it connect as a wireless controller but the input doesn't work at all. If it's worth mentioning the controller doesn't work on the home screen if it's connected over bluetooth but it does when connected with an OTG.

**Comment by Trasen** [comment]
Hey again Mystic,

I have digged in on the issue you've been having with the Sixaxis controller on the S7 and i can confirm that this is an issue all over. Seems like a permission problem in the firmware, no i dea why Samsung would choose to exclude the support on their flag-ship phone, and none of the other.

I would urge you to contact Samsung and ask why this is the case, because i agree, it shoulnd't be nessesarry to root the phone just to make a device work.

Best regards!

**Comment by CertifiedSammy** [comment]
Connecting your PS4 controller to your android via bluetooth works. 

Link to source on how to: https://www.techsng.com/2017/06/connect-use-ps4-controller-android.html

However, most android games doesn't work with the controller. Personally, only Asphalt 8 seem to have worked for me thus far. I hear there are quite a handful of other games that can be played using the controller though.

**Comment by CAGEDDAWG** [comment]
Hey everyone, I also own the s7 and am having the exact same issues as mystic! However, when plugged in through otg, the controller does not have the correct mappings. I see this must be a common issue and have no idea how to solve this. I'll try to keep looking and keep informed as to what is going on behind the issue.

**Comment by cgutman** [comment]
Weird, Moonlight has special mappings for the DualShock 4. I just tried a DS4 connected via BT and USB on my Pixel 2 XL, S8, and Nexus 6P and it was mapped properly on all devices.

What model number are your DualShock 4 gamepads?

**Comment by ecoceres** [comment]
Hi Mystic could you solve this issue?

**Comment by hamidahmadi313** [comment]
I also have this problem.
The ps4 joystick is connected but not working!!
My device is galexy a5 2017

**Comment by hovaleo2** [comment]
I have been trying to connect my PS4 controller to my Samsung Galaxy S10 5G running snapdragon 855. It shows connected but nothing works.  Neither on the screen or any games on my mobile. Please can anyone help me with directives on how to fix this.? Thanks

**Comment by mohamed5aled** [comment]
I have tha same problem my phone is oppo f5

**Comment by amadrid09** [comment]
I have the Galaxy S10 5G n it connects to bluetooth but there isn't any input either. I'm runnin the Android Version 9 (Pie)
What's your input Trasen?
