### ISSUE TITLE
FireTV - Moonlight keeps exiting Fullscreen Mode during Game

### ISSUE THREAD

**Issue by MrCso** [moonlight-stream/moonlight-android#367]
No matter what game I stream to my FireTV, moonlight at some point exits the games´ fullscreen mode and displays it in a window with heavy stuttering. In order to bring it back to full screen, I have to activate the mouse mode and click into the game´s window. Happens with every game. 

Geforce 850m
FireTV 1st gen
4K panasonic TV

Any ideas what might be causing this issue?

**Comment by Trasen** [comment]
Hello MrCso,

This doesn't sound like an issue with moonlight, if anthing it's possible that it's a Nvidia problem. Could you try to run the game in fullscreen windowed mode?

Best regards.

**Comment by Trasen** [comment]
Did you try this?

**Comment by Trasen** [comment]
Also : The 850m is a very weak card. Exactly what games are you trying to play using Moonlight?
