### ISSUE TITLE
Unable to connect to the specified computer. Make sure the required ports are allowed through the firewall.

### ISSUE THREAD

**Issue by fefemess** [moonlight-stream/moonlight-android#368]
Hi everyone, as i wrote in the title i get this error "Unable to connect to the specified computer. Make sure the required ports are allowed through the firewall." when i try to connect to my pc using moonlight from my phone. Please someone help me.

**Comment by Trasen** [comment]
Hello @fefemess,

Could you explain how you've set everything up at home? We're after all talking about something as tempremental as networking.

In what manner are you trying to connect? Are you connected to WIFI or are you using the 3G on your phone? Is it possible that you have several routers at home?

A custom firewall installed on your computer? What antivirus are you running? A firewall on the device it-self?

Best regards.

**Comment by Gamer9** [comment]
Hello, I have found that (at least with GeForce Experience v3.5.0.70) that in W10 you need to enable 'Make this PC discoverable' to make a connection with Moonlight. This does not seem necessary with W7 but instead, after any restart, you need to load up the GeForce Experience application (not just leave it running in the background) to initially make a connection. May be worth a try. Hope this helps. Regards, Islam.

**Comment by fefemess** [comment]
Ok, I'm using wifi and i have only one router. The ports used by gamestream are open, my network is set on private (i spent 2 hours trying to change it, thinking that was the problem but no)
I don't have a custom firewall and i'm using avast
I tried to open geforce experience while connecting but nothing
Other ideas?

**Comment by fefemess** [comment]
Problem was with a bug in the router firmware that didn't allow ports to be forwarded.
If you're using the TimHUB be aware that it doesn't work.

**Comment by arnav2404** [comment]
I am Using Dragon Technologies 707GR1 Router and have add total 8 ports in port forwarding of 4 TCP (HTTPS, HTTP, Web, RTSP)(47984, 47989, 47900, 48010) and 4 UDP (Control, Video, Audio and Mic)(47999, 47998, 48000, 48002) i have also added the local IP in DMZ and have put new rules in Firewall for these ports in Inbouned and Outbouned separately and finally added the application rule also, but even after all this setting i am getting this error now i don't know what to do, I was hoping that i can play games even when i was in different city but it seems impossible 😔 
![inbouned](https://github.com/user-attachments/assets/7f6cf13b-ae78-43a7-ae87-acb512f03509)
![outbouned](https://github.com/user-attachments/assets/3de5c61d-22b1-4d1c-9a5f-ae319920f3fd)
![Screenshot 2024-12-18 200840](https://github.com/user-attachments/assets/3a28df4b-2000-4406-ac4f-05a42f38b218)
![Screenshot 2024-12-18 201021](https://github.com/user-attachments/assets/3c6049c5-4a08-4628-9461-4314b8f02a1b)
