### ISSUE TITLE
Modifier keys and Mouse click aren't working anymore.

### ISSUE THREAD

**Issue by Slayer418** [moonlight-stream/moonlight-android#378]
Shift, Ctrl, Alt doesn't work with mouse anymore and it's quite annoying for the game I'm playing.
Shift still capitalize when you type tho.

I can say It was working last time I used moonlight (last month) and I think I installed an update for GFE during that time.

**Comment by cgutman** [comment]
See https://github.com/moonlight-stream/moonlight-chrome/issues/223

**Comment by Slayer418** [comment]
Thanks for the quick reply and sorry, I'm not really used to github so I couldn't figure how to search thru issues posted. Let's wait for the next GFE update I guess...

**Comment by cgutman** [comment]
No problem. This issue is fixed in GFE Beta 3.6 now. https://github.com/moonlight-stream/moonlight-chrome/issues/223#issuecomment-299237750
