### ISSUE TITLE
games/steam didn't start

### ISSUE THREAD

**Issue by Mahmoud-Asem** [moonlight-stream/moonlight-android#382]
I tried everything. uninstalled gfe- ddu- Everything about Nvidia. then installed it again. but the problem is still there. it connects. it pairs. it detects the game. but when I open the game from the Android app. it says "establishing connection. starting steam" then it opens the game on my pc but I don't see it on my Android app. and sometimes it ceashes

**Comment by Trasen** [comment]
Hello,

Do you have a different Android device you could try it on?

Sounds as if it's a codec issue, can you specify the settings you're using? Is this happening with only when you try to stream steam?

Also please specify what Android device you're using.

Best regards.

**Comment by Mahmoud-Asem** [comment]
I have Samsung Galaxy note 4 with a custom ROM. I didn't try any other devices. I tried the default settings and tried (1080 60fps - 1mps)

**Comment by Mahmoud-Asem** [comment]
I tried another phone and it works. what should I do for it to work on my first phone? would the original rom help or is it the problem with my hardware?

**Comment by Trasen** [comment]
Hello again,

You wrote that you're trying to stream 1080p 60fps with the 1mbit/sec, this is not possible.

Please set the bitrate to at least 15-25mbit and it should work as intended. Also make sure you're codec is set to 'never use h265 codec'. That should do it :)
