### ISSUE TITLE
Is there a "view only" mode/can I deactivate controlling via Android app?

### ISSUE THREAD

**Issue by dnn1s** [moonlight-stream/moonlight-android#383]
Is it possible to have my Android device in a "view only" mode? Basically, I want to play on my PC but want the screen to be visible on a tablet/smartphone. I just tried Rocket League, but using the controller attached to my computer I can only join a party as player 2. This might not exactly be an "issue" with the application, but I couldn't find a dedicated support forum for this kind of question.

**Comment by thw0rted** [comment]
There are [instructions in the docs](https://github.com/moonlight-stream/moonlight-docs/wiki/Setup-Guide#using-a-gamepad-connected-to-the-pc-instead-of-the-streaming-device) for using your PC-connected gamepad as player 1.
