### ISSUE TITLE
Issue with Samsung phones and IPEGA controller

### ISSUE THREAD

**Issue by joeyenfield** [moonlight-stream/moonlight-android#385]
Hey, 
 I have been having an issue with my iPega PG-9068 Tomahawk controller not working correctly on my Samsung phones. It never seemed to capture the inputs correctly when I went into a game. When I pressed the B button it was just exiting the games, thinking that the back button had been pressed on my phone. 

Tested 

-S3[Cyanogenmod 12 - Android 5.0.0] - **Failed**
-S4[Cyanogenmod 13 - Android 6.0.1]  - **Failed**
-S6[Official Samsung - Android 7.0 ]  - **Failed**
-Nexus 10 [ Official - Android 5.1.1] - Worked

I checked out the code and have a patch that i've put together. 

Just logging this so that if anyone else has this issue.

**Comment by Wully616** [comment]
Exact same problem here, controller mappings not working properly, B button acts like the back button.
Controllers: iPega 9025 and iPega 9055
Phone: Oneplus One
ROM: Lineage OS 14.1-20170508-NIGHTLY-bacon

**Comment by JesusBlacklock** [comment]
I'm experiencing the same using a Phone joy Controller on a Samsung Galaxy Note 4 Stock 6.0.1 as well as a Samsung Tab tablet (I don't have it on me, so I am unsure what the software is). The controller previously worked as expected with both of these devices. The controller is detected as an external keyboard, but that is how it was detected previously when it worked.

**Comment by cgutman** [comment]
Fixed by https://github.com/moonlight-stream/moonlight-android/commit/043c9a978e50363e8f2cc0838174c2b55fd33c4b
