### ISSUE TITLE
Bug: Black screen, audio only with latest drivers

### ISSUE THREAD

**Issue by iamrizzle** [moonlight-stream/moonlight-android#391]
After installing the latest GeForce driver, as soon as a game loads (Doom, for example), I can only hear audio, there is no video. I can still interact with the menus using onscreen game pad (You can hear the menu sound feedback). 

GeForce Experience: 3.6.0.74
Driver: 382.05

I have tried reinstalling GFE, reinstalling Windows. Reverting to driver 379.92 fixes the issue.

Thanks for your time!

**Comment by NightHammer1000** [comment]
same here

**Comment by NightHammer1000** [comment]
Was able to find out whats going on. Problem only occures if no Monitor is Connected to the Streaming Maschine. Or in my case: My SmartTV is turned of wich disconnects the Plug and Play Monitor from Windows.

**Comment by MopheusDG** [comment]
Driver: 382.53
GFE: 3.7.0.81

I have a similar problem but it's only happening with OpenGL games (Amnesia, SOMA, Etc...) are not streaming anymore, just black screen with sound. Is it possible ?

**Comment by Trasen** [comment]
Could you guys try setting the games to Borderless Window? At least the ones that supports it - and report back with the result? :)

**Comment by MopheusDG** [comment]
Sure Trasen, been busy this days but will test today and get back to report.

**Comment by MopheusDG** [comment]
Ok, I tested "Amnesia: The Dark Descent" and "SOMA". In both cases it only works when in Window mode (I'm streaming the Windows Desktop). If I switch to No Borders or Full-Screen, I just get 1 frame and then nothing else, just stuck on that frame on my Moonlight stream. I used to play both of this games in Full-Screen via Moonlight on the past so it's something recent that changed, last time I tried any of this games was 4 months ago I think and they were working fine.

Let me know if you need more info or testing.

**Comment by MopheusDG** [comment]
Also I've noticed that Fire TV Stick get's a little HOT when using HEVC (I didn't test x264 temperature yet), but after 1 hour playing, I saw 85C via Kodi. Maybe there's a better way to monitor the stick temp but need to investigate a little to do it, probably via ADB...

**Comment by hammelion** [comment]
385.69 Driver - still the same problem

**Comment by Neltherion** [comment]
I've got the same problem... 

Latest Nvidia driver and Moonlight and having a black screen which can register input (Mouse movement and clicks).

The games all run on the Nvidia Card (and not the integrated graphics) and I'm running GFE on a laptop so there is no way to "Connect the HDMI cable from GPU to Monitor".
