### ISSUE TITLE
Option to save virtual controller layout?

### ISSUE THREAD

**Issue by hypnopt** [moonlight-stream/moonlight-android#392]
I've been trying to save the layout of the virtual controller, essentially I only wanted the two joysticks to show up, would be great if there's a simple fix for it or simply an option to save the layout.

Thanks for this amazing app btw!

**Comment by daedalus87m** [comment]
Would like this too! Also while at it, there is some weird behavior with resizing buttons. They only become smaller if you drag them to the bottom or right edge of the screen, and if you drag them anywhere away from those edges, they become whole again (basically, you can only have small buttons on bottom or right edge). 

If this was fixed, then it would be rly awesome :)
