### ISSUE TITLE
Samsung Galaxy S8 Plus Resolution?

### ISSUE THREAD

**Issue by angrycrab** [moonlight-stream/moonlight-android#393]
Is It possible to customize the resolution settings In moonlight to match the phones native resolution of 2960 x 1440 ?

And what If I choose to stream at 4K will It downscale automatically to the phones native resolution?

**Comment by Trasen** [comment]
Hey,

No you can not, atm the Nvidia game stream only have 'standard resolutions.

It will downscale similarly to a video renderer fitting it's content to the display.

It's something you see how it works when you try it, not sure why you're opening a issue for it :S

Best regards.
