### ISSUE TITLE
Samsung Galaxy S7 Edge still suffering from micro stutters

### ISSUE THREAD

**Issue by JasonS7notG5** [moonlight-stream/moonlight-android#395]
Reinstalled NVIDIA drivers and GeForce Experience (after cleaning with Displayer Driver Uninstaller), reinstalled the "new" Moonlight (after stopping the app to run, deleting cache and data) and still the S7 edge suffers from the same old micro stutters problem. Tested with USB tethering and WiFi 5GHz and 2.4GHz.

https://play.google.com/store/apps/details?id=com.limelight

> - Rewrote the streaming core to unify code with other Moonlight clients
> - Significant improvement to streaming over wireless connections from the new streaming core
> - Fix several common hangs and crashes

Didn't made any difference...

Do the devs work on fixing this or not? I mean a high end device like the S7 (edge) should perform significantly better than old pre-Android 6.0 low-mid class devices...

**Comment by JasonS7notG5** [comment]
Latency doesnt matter if it is lower than 16ms. It is a known problem where all devices with Android 6.0+ have micro stutters. The devs still didn't fixed it.

**Comment by Trasen** [comment]
#374

**Comment by JasonS7notG5** [comment]
Anyone having the same problems, try this build from cgutman (Moonlight dev)

https://github.com/moonlight-stream/moonlight-android/issues/349#issuecomment-304767594

This fixed the micro stutters. At least I think it did (_thats what counts in the end, subjectively thinking it did improve_) :P
