### ISSUE TITLE
Poor performance using bluetooth controller

### ISSUE THREAD

**Issue by rnk247** [moonlight-stream/moonlight-android#397]
Hi:

I'm experiencing poor performance while using a Nexus 7 (2012 - tilapia) and any bluetooth controller. I can stream 720p60 and play using the mouse and keyboard from the host (for testing purpose of course) and the stream runs fine. As soon as I connect a bluetooth controller, an Ipega PG-9037 paired via the system bluetooth interface, stream becomes choppy and crawls to a halt after a few seconds (720p30 manages but with multiple hiccups). Tested too with a DualShock 4 paired with SixAxis Controller app and getting the same performance decrease.

If I connect the DualShock 4 via otg it works perfectly fine and can manage 720p60 with no major problems.

Not experiencing any of this on a Nexus 5 (same controllers, same network, same host PC). Is this a limitation of the device or is there anything else at play here? Would like to be able to use the controller wirelessly so I could charge the device while playing (also, otg with the DualShock 4 seems to drain the battery dry).

Android version 5.1 (rooted). Tried factory reset: same thing.

Any ideas? Thanks.

Edit: forgot to mention. Watching the host PC monitor everything is running fine and at high framerates, seems like a client render problem. Using GTX 1080 with latest drivers and Gamestream enabled in GFE (obviously).

**Comment by thw0rted** [comment]
I don't have links handy but if you read the XDA thread a little (I know, it's enormous) you'll see a lot of people having similar issues.  I don't think there's a crowdsource list of affected devices yet, but basically some devices have one antenna that the 802.11 and Bluetooth share -- using Bluetooth causes a serious degradation of WiFi signal quality, to the point where the stream is more or less unplayable.  You've already found the suggested workaround yourself (OTG), the only other option is to connect the controller directly to your PC (assuming it's close enough) or try a different device.

Good luck!

**Comment by rnk247** [comment]
That just confirms I can't do anything then. Thanks! I'll try using the controller connected directly to the host PC if I can use it between rooms (not likely), else I'll have to use it via OTG but it seems to take a massive hit on battery usage (I'm not sure if the DualShock 4 is charging off the tablet even though it doesn't have the orange light on).

**Comment by thw0rted** [comment]
At least if you're at home, you could see about getting a long USB extension cable (they're pretty cheap on Monoprice) and pairing your controller to a USB bluetooth adapter?  I did something like this for my home theater setup and had pretty good results.

**Comment by rnk247** [comment]
It's for use at home. Got the Sony PC Adapter. I don't know what range that has, hope I can get it to work across one room. If not, I don't think it would be worth the hassle. I would just use the Nexus 5.
