### ISSUE TITLE
build help

### ISSUE THREAD

**Issue by muffinmannameistaken** [moonlight-stream/moonlight-android#398]
I'v been having this problem when I to build moonlight 

Error:Project :app declares a dependency from configuration 'debugCompile' to configuration 'debug' which is not declared in the descriptor for project :moonlight-common.

I do not under stand, can anyone help me with this ?

**Comment by cgutman** [comment]
Did you forget `git submodule update --init --recursive`?

**Comment by muffinmannameistaken** [comment]
I downloaded moonlight sources from here and I'm using Android studio to edit, where does this go
git submodule update --init --recursive?

**Comment by cgutman** [comment]
If you just downloaded the zip, I don't think you'll be able to build that. You need a Git client and to clone the repo via Git, so you can run `git submodule update --init --recursive` to get the other sources.

**Comment by muffinmannameistaken** [comment]
ok did all that updated some stuff but i ran in to this problem 

Error:Artifact 'com.android.tools.build:builder-test-api:0.13.2:builder-test-api.jar' not found.

**Comment by muffinmannameistaken** [comment]
solved the problem, I deleted everything and started fresh, I'm still not sure why I was getting that error but deleting everything seems to work.
