### ISSUE TITLE
powerful rockchip3399 but only 1080p/h264

### ISSUE THREAD

**Issue by grizli21** [moonlight-stream/moonlight-android#399]
Hi,

As an intensive user of moonlight i first wanted to thanks developer for the great work you have done. 

That being said, I recently changed my box for a yundoo y8 because of it's powerful rk3399.
While i know that the SOC is not yet commonly used, there are 2 things i wanted to share.

While 720p and 1080p are fine, the 4k/30fps and 4k/60fps are not working at all. Screen stay black.
Got freezed screen when i put the H265 forced mode whereas it is fine with h264.

About my setup:
Card inno3d GTX 1080
GFE 3.7.0.68 and experimental is activated
Yundoo Y8 on android 6.01
Moonlight android client 5.1.1

Would be happy to give you more informations.
Regards
Nicolas

**Comment by cgutman** [comment]
I don't fully understand what you say is working and what is not.

720 and 1080p are fine with both H264 and H265?
4K/30 and 4K/60 are broken on both H264 and H265?

In what configuration does the screen freeze and what configuration does it stay black?

**Comment by grizli21** [comment]
Hi cgutman,

H265 is broken whatever resolution is selected,the screen is frozen.
4k resolution (h264) is also broken, the screen stay black.

Only current are working:
720p   30fps h264 - 11ms
720p   60fps h264 - 11ms
1080p 30fps h264 - 16ms
1080p 60fps h264 - 17ms

Thanks for answered.

**Comment by cgutman** [comment]
Are your PC and Android device connected via Ethernet to your router?

Can you try installing this older version and trying H265? https://github.com/moonlight-stream/moonlight-android/releases/tag/v4.8.4

**Comment by grizli21** [comment]
Everything is wired in gigabit lan and having stable bandwidth.

Tried the older 4.8.4 and is having the same behavior as 5.1.1 .
I don't know if it help but i noticed cursor was moving in h265 a fraction of millisecond before freezing.
Then when i escaped moonlight, i got that pop-up "blablab latency 2ms - h265".

My gess is a yundoo y8 firmware/codec related problem, any idea ?

**Comment by cgutman** [comment]
Can you try this 4K H.264 on this build? https://drive.google.com/open?id=0B_5O1xNt8Q9lUUYxNDNQek02Rmc

I think I'll need some logs from your device to diagnose these issues. Does your device have a Micro-B connector or any other way to connect it to a computer? If not, is there some way to activate ADB debugging on it?

**Comment by grizli21** [comment]
Hi,
`Can you try this 4K H.264 on this build? https://drive.google.com/open?id=0B_5O1xNt8Q9lUUYxNDNQek02Rmc`
This build has same behavior as others.

I have made some debug log for you. Here they are
[android-debug-1080p60-h264-working.log](https://www.dropbox.com/s/m85zybsp4e3hicl/android-debug-1080p60-h264-working.log)
[android-debug-4k60-h264-noworking.log](https://www.dropbox.com/s/6bh7zywh25vtgw8/android-debug-4k60-h264-noworking.log)
[android-debug1080p60-h265-noworking.log](https://www.dropbox.com/s/30rs6wy3y7j4puw/android-debug1080p60-h265-noworking.log)

**Comment by grizli21** [comment]
Note that for debugging purpose, i move the box upstairs so wifi is on and monitor is 1920*1080 limited.

**Comment by redlinejoes** [comment]
You are connecting a1080p display and trying to steam 4K it sounds like which is not possible. According to Nvidia GeForce experience the only way to steam 4K is if you have a 4K monitor hooked up to the server. Do you have a 4K monitor? That 1080p monitor shouldn't allow 4K streams.
