### ISSUE TITLE
RTSP Handshake failure. No error code.

### ISSUE THREAD

**Issue by Gloppy16** [moonlight-stream/moonlight-android#404]
When I try to start and app through moonlight, the app will start on the host computer but the rtsp handshake will fail. I am trying to connect while on the same network.
    I am using an s8 running android 7. I have uninstalled and reinstalled both moonlight and the GeForce experience. I have completely disabled my firewalls as well as port forwarded everything. The device won't show up when I'm off the network.
    I also had this working on my computer before but I had to completely wipe the old image and put a new one on.
    One last thing, I was using stream theater with some success but It would stop working frequently. It might have something to so with the rtsp handshake but I really don't know.

**Comment by phsyron** [comment]
Can confirm on a Note tablet. Maybe a Samsung thing? Works fine from my pixel

**Comment by Gloppy16** [comment]
I don't have one. I just remembered I have another old android phone I can try though. It work before maybe it will work again.

**Comment by Gloppy16** [comment]
Nope, didn't work.

**Comment by Gloppy16** [comment]
Randomly started working again. Probably due to an update or something.
