### ISSUE TITLE
After closing a stream, computer stutters

### ISSUE THREAD

**Issue by lynkfox** [moonlight-stream/moonlight-android#409]
After using Moonlight on my samsung galaxy tab S2 (in which everything works great!) when I close out of the app - either by backing out, using the close all apps button (or the x on that same screen) or by exiting from, say Steam Big Picture and stopping the stream, my computer's input is extremely unresponsive. 

Moving the mouse will cause it to stutter across the screen, jumping inches at a time.  any keyboard inputs take seconds to show up. Nothing responds in a timely manner. a Restart is the only thing I've found to fix this.

My power button is hooked up to initiate a shut down through windows 7, so immediately after touching the power button things close and all stuttering stops, as whatever process is causing it has been forcefully stopped.

Specs:
Windows 7
GTX1060 6g
32g Ram
Tab S2 w Android 7.0
GeForce Experience 3.7.0.81

I've fiddled with settings all across Moonlight, but nothing has changed the effect.

This could very well be an issue with Shield streaming, but I do not have a shield capable device to stream with outside of using Moonlight.

**Comment by cgutman** [comment]
Sounds like a possible driver bug. Do you see excess CPU usage in Task Manager or anything like that?

**Comment by lynkfox** [comment]
Yep, there is a CPU spike right after i shut down the stream. I had the resource manager open, and I also saw the  disk acess go through the roof as well, but b/sec and active time. It all dropped down to normal after about 30 seconds, but the stuttering did not go away. No one task was using up all the cpu - svchost got up to 25% of cupusuage at one point, so did Steam.exe and chrome. Random other things would pop up in the teens and then back down, nothing stayed up there long. CPU graphs and disk graphs went back down to normal, but the stuttering remained.
