### ISSUE TITLE
Can't Connect Over Internet

### ISSUE THREAD

**Issue by sgbakernz** [moonlight-stream/moonlight-android#415]
So I'm going away for a few days soon, and thought it would be cool to be able to play some of my PC games while away, so I've got Moonlight setup on both my iPad Pro 9.7 and my S7 Edge, but I just cant seem to get it working when they're connected to any network other than the one my PC is connected to.

I've port forwarded all the ports on the website on my router, but whenever I switch to LTE or my secondary WiFi network and enter my PC's local IPv4 address, it continuously gives me the message "Unable to connect to the specified computer. Make sure the required ports are allowed through the firewall." 

Ideas?

**Comment by thw0rted** [comment]
Can you access your router's management page using your public IP address (assuming you can {briefly} enable WAN access...) from the outside?  The first step would be to rule out any inbound traffic restrictions that your ISP might impose.  Once you're sure you can reach your home network at all, you can move on to the next step.

**Comment by Owerlords** [comment]
try v4.8.2 it works for me and the never ones dont on my android tablet
