### ISSUE TITLE
Unable to connect with Samsung Galaxy Tab 2

### ISSUE THREAD

**Issue by baalo91** [moonlight-stream/moonlight-android#416]
It seems that my (old) Samsung Galaxy Tab 2 can not find my PC (even from outside the network via port forwarding).

It is already working perfectly with my Samsung Galaxy S6 and my laptop (Chrome) in and outside of the local network, so I do not think it has anything to do with the network-setup.

I tested following versions on my tablet: 5.1, 4.8.3, 4.8.2

When I try to add the pc manually (also inside and outside of the local network) it says it is unable to connect to the computer.

Device:
Samsung Galaxy Tab 2
Android 4.2.2
Model: GT-P5100

.. And thank you very much for your time and this application!! I love it!!!!

**Comment by Owerlords** [comment]
Has it ever worked? i had the problem on the nevest updates on my android taplet but then installed 4.8.2 and it started working again like it should.

But my phone Samsung Note3 it works with the nevest updates

**Comment by baalo91** [comment]
No it was my first test with the tablet but I solved the issue now!

The problem was an update for my AntiVirus Software (AVG Free Edition) which I have installed a day before or so. That seemed to cause the problem (also for my phone at some point).

When I deactivate it, moonlight works with the tablet flawlessly!
