### ISSUE TITLE
Please help me! Android device not pairing.

### ISSUE THREAD

**Issue by andrich54** [moonlight-stream/moonlight-android#42]
I can't tell you the frustration I've gone through and the lack of any help I had found via google on this issue. I downloaded Limelight PC v0.5.8 (Beta) and the android App (Galaxy S5). The PC is paired to my computer via IP address. The problem is my phone. It won't find my PC. It's on the same network and I've type in the IP address several times to the point where it started getting frustrating. Yes I have beta drivers going on Steam and yes my drivers are all updated on my Nvidia GEforce. And I also do have an Nvidia graphics card. I just can't get the Android phone to pair with the PC. Please help me. 

(I put in my IP Address and it says unable to connect to specific computer. Make sure the required ports are allowed on your firewal" My firewall is off.....

**Comment by simonrail** [comment]
i also have this frustrating problem.. why cant it be simple.. 
i got a nexus 7 tablet and got it works. (i got free limelight by googleplay)

My GFE was not setup to stream at the beginning (even if i was at lastest update). Just to be sure to check into "myRigs" ( in GeForce Exp ) to complete the installation. 

then re-check your steam for the beta thing and restart steam to be sure. 

at last, i force-open port on my avast firewall AND window basic firewall. even if is not enabled.
http://www.dummies.com/how-to/content/how-to-open-a-port-in-the-windows-7-firewall.html

i opened those ( that i found for steam and limelight )
TCP 35043, 47984, 47989, 47995, 47996, 48010
and
UDP 47998, 47999, 48000

restart your computer ! 

goodluck ;)

**Comment by andrich54** [comment]
It still does not work =( Can you give me a step by step process maybe? So I can do it all over again. I opened the ports on my computer and router.

**Comment by cgutman** [comment]
Re-open if this is still an issue.

**Comment by muffinmannameistaken** [comment]
i now have this problem all ports are now open and i had it working just fine a min ago iv also tried turning on and off fire wall and still nothing.

**Comment by shaneamndos** [comment]
I have this exact problem with the samsung s6! firewall is down and nothing. I have tried port forwarding some ports but im on the same network so this shouldn't be a problem.

**Comment by towfiqi** [comment]
Same thing happening here. Did any of guys solved the issue?

**Comment by mhvuze** [comment]
Same problem here. It detects my brothers PC but not mine. Same network, same router, no matter if Firewall is off.
