### ISSUE TITLE
Getting back to android home screen

### ISSUE THREAD

**Issue by wishfm** [moonlight-stream/moonlight-android#423]
Hi. I have a issue after im done playing the game.

Im using an Android TVBox and works great but every time i quit the game im currently playing the Windows desktop appears and i cant go back to android home screen.

What i do now is, i go to the streaming PC, open geforce experiences and click "Remove all devices" under the Shield Option. This way, it disconnects my android tvbox and i can resume the stuff i was doing before playing the game.

Is there an android shortcut or hotkey that i can press that disconnect me from the the Geforce Gamestream ?

Thanks!

**Comment by cgutman** [comment]
Which game? Quitting the games I've tried is working okay for me and causes Moonlight to disconnect.

**Comment by wishfm** [comment]
I only tried 2 games. "The Legend of Heroes - Trails in the Sky Second Chapter" and "Children of Zodiarcs".
In both games the same thing happens.

**Comment by thw0rted** [comment]
I'm just curious, does the TVBox not have a "home" and/or "back" button on whatever controller / remote ships with it?  Do those buttons not work in this case?

**Comment by wishfm** [comment]
Good idea. I never used the remote control that came with it. From the get go, i always used the Air Mouse i bought the same day. Today, one year later, i found the remote control inside the old TVBox box, bought 2 AAA bateries and tested it. When i press the home button using the remote control, yes, it brings me back to the home screen. At least for now, it solves my problem...

Thank you!

**Comment by thw0rted** [comment]
Possibly of interest: I didn't see "Home" mentioned on [this list of keyboard shortcuts](https://www.howtogeek.com/175267/the-htg-guide-to-using-a-bluetooth-keyboard-with-your-android-device/) but [this XDA thread](https://forum.xda-developers.com/shield-tv/help/keyboard-shortcuts-t3416943) says "Start + Enter" -- I think they mean WIN+Enter.  (I assume you have a keyboard in addition to the air mouse?)

**Comment by wishfm** [comment]
Nice, thanks, but that didnt work because when i leave the game im stuck inside the Windows Desktop and the Windows take over the Air Mouse, meaning, when i press WIN+ENTER, the key combinations executes inside the Windows, not inside Android...

**Comment by thw0rted** [comment]
Sounds like @cgutman  maybe needs to make sure that combination gets passed to the OS? Not sure how one could test this without hands on an Android TV, though...

**Comment by cgutman** [comment]
The expected behavior is that the game exits, GeForce Experience tears down the streaming session, Moonlight receives a disconnection event from the PC (or the connection times out), then Moonlight kicks out of the streaming session and displays the "Connection Terminated" dialog.
