### ISSUE TITLE
moonlight android - mouse right click

### ISSUE THREAD

**Issue by i9duya** [moonlight-stream/moonlight-android#424]
i'm using bluetooth keyboard/mouse.
and scancode available keyboard App works on moonlight very well.

but moonlight BACK to menu when mouse right click.
it's like seem to handle Android OS level.

OTG Mouse has same problem.
https://github.com/moonlight-stream/moonlight-android/issues/312

but MICROSOFT REMOTE DESKTOP app is mouse right click works very well. ( no require rooting )
i think it can solve in app level.

**Comment by Alec123445** [comment]
Yeah i have this problem on Oreo and can't fix it on Oneplus 5t. Its quite annoying because everything else works exceptionally well.

**Comment by cgutman** [comment]
Should be fixed now.

@i9duya was your device running Android 8.0 Oreo?

**Comment by jgonyea** [comment]
Oneplus 5
Android Oxygen OS 8.1

**Comment by ccuono** [comment]
Rock64
Android 8.1
Moonlight 5.10.3

Right click initially works, then turns to back button. It's so weird! I just want it to behave as a right click like it starts out being...

**Comment by cgutman** [comment]
Fixed in v6.0

**Comment by i9duya** [comment]
-_-)b
