### ISSUE TITLE
Connecting via DDNS works only once

### ISSUE THREAD

**Issue by bruwozniak** [moonlight-stream/moonlight-android#425]
I am using the moonlight app on Android (Nvidia Shield tablet) to stream from a server with a DDNS alias.
When I add the hostname for the first time, it works (for the most part). But after the IP changes, it can't connect to the machine.
Adding the same hostname again works, but is very annoying.
Moonlight on macOS works all the time.
Any ideas? I suppose the android client resolves the hostname once and saves only the IP?

**Comment by T0LL0** [comment]
I have the same problem. I am using moonlight chrome extension and android app. Chrome extension works forever with my hostname, but android app doesn't.

**Comment by cgutman** [comment]
This is fixed in Moonlight Android v5.2
