### ISSUE TITLE
Mouse cursor disappears at 4k hi-dpi(over 250%)

### ISSUE THREAD

**Issue by Sonofdemoc** [moonlight-stream/moonlight-android#426]
In a 4K display (host)
I mainly use it as a remote app
Of course, I enjoy games, but this problem is not related to games.

if dpi scaling exceeds 250% on the desktop, mouse cursor disappears from the mobile phone
It is not related to transmission quality or transmission resolution.
I've searched for a solution to this problem, but nothing was specifically discovered.

The version is the micro-stuttering fix version you provided

Thank you for reading

**Comment by cgutman** [comment]
Hmm, that seems like a bug in the GeForce Experience desktop capture code.

**Comment by Stormwind99** [comment]
May be related to https://aka.ms/AA21z7d

**Comment by Stormwind99** [comment]
I still experience this issue - if I use Moonlight to a Windows 10 PC with a 4k display and 200% UI scaling, the mouse cursor will disappear.  A workaround is to use keyboard shortcuts to open the Display Settings window, switch UI scaling to 175% or below (and the mouse cursor reappears), then switch back to 200% UI scaling.

**Comment by mikecli** [comment]
Mouse cursor >= 5 seems to be another fix.
You just have to deal with a comically large mouse pointer. Which I suppose makes sense if you're on large UI scaling anyway.
