### ISSUE TITLE
Feature request Chromecast

### ISSUE THREAD

**Issue by sigboe** [moonlight-stream/moonlight-android#427]
Let me just start out and say that I do not know if this is feasible, in regards to latency, or other unexpected road blockers.

I imagine the user having connected a gamepad, or mouse and keyboard, or even on screen buttons on the phone. Like already implemented, the phone would create and authenticate the session and provide input to the computer. Maybe the phone could have the option to stream the audio, though I imagine that it could be problematic either having audio sync up to the picture or it could give some latency. 

As I understand the chromecast API without reading through everything, the phone or device would give the chromecast a stream and associated information for the session. So for example, I log into netflix on my phone, and my phone gives my chromecast a login session and instructions to stream the content. 

This figure shows how I imagine it could work.
![chromecast](https://user-images.githubusercontent.com/2087930/29248568-5935a3c6-801b-11e7-9914-2a33ca615ad2.png)

I just think, if this is possible, it would be a great way to use this app. Some people just have a chromecast at home, or some people have a chromecast for traveling. Thanks for reading this suggestion.

**Comment by fpsb0b306** [comment]
I too would love to see this.

**Comment by thw0rted** [comment]
So, the controller input goes from the phone to the PC, then the video goes from the PC to the Chromecast?  In theory that should be possible but it might require a different server-side architecture, since this isn't how GameStream works natively.

**Comment by sigboe** [comment]
@thw0rted I didn't think about that, maybe an optional helper app could be installed on the host.

**Comment by romulof** [comment]
Would be nice to have this even with the controller connected to the host.
Unless you have a big house, bluetooth signal can travel though 1 or 2 rooms.

**Comment by LucasPicoli** [comment]
This would be very nice. I'm pretty sure most people (me included) would be okay with the caveat of only streaming video and letting the host handle controls.
