### ISSUE TITLE
New Icon for Moonlight Android

### ISSUE THREAD

**Issue by phantom-playR** [moonlight-stream/moonlight-android#428]
Hello, I just saw the new adaptive icon for Android, and if you want, you can use design I've done for the iOS version : 
https://github.com/moonlight-stream/moonlight-ios/issues/93

I tried to see how it can look an Adnroid Studio : 

![capture](https://user-images.githubusercontent.com/4344835/29279842-741ad8b0-8119-11e7-9a1d-f7dc424776fc.PNG)

Files if you want them : https://mega.nz/#F!kxwQnJaB!dmuehJ1d--sCcwN7bzuEFg

Or maybe something like that : 
![screenshot_20170815-123220_01](https://user-images.githubusercontent.com/4344835/29312547-302f0fd4-81b6-11e7-9a34-4877262d3d1f.png)

**Comment by cgutman** [comment]
I think we'll standardize on the simpler Android/Chrome icon going forward. It has more recognition across platforms than the iOS icon. Thanks for the contribution though.
