### ISSUE TITLE
[Feature Request] On Screen Controller?

### ISSUE THREAD

**Issue by weihan1102** [moonlight-stream/moonlight-android#43]
First, Thanks for the Awesome app.
And sorry if this is not the right place to post feature request.
But it will be awesome if Limelight can have a On Screen Controllers.
That means we can play games without a physical controller.
It might me a bit silly for playing games like Farcry4 with a touch screen, but i think it will works well with "lighter" games.

**Comment by Nargajuna** [comment]
it's not a real solution, but you can use Gamekeyboard to generate onscreen buttons and map them.

**Comment by cgutman** [comment]
An on-screen controller has been added in master.
