### ISSUE TITLE
Xbox 360 back button conflicts with Android

### ISSUE THREAD

**Issue by nhatku811** [moonlight-stream/moonlight-android#432]
Whenever I press the back button, it jumps right back to android UI. Middle xbox button has the same error. Please help. I'm running Android 7.1.2 on Mi5

**Comment by BluTree** [comment]
I relaunch the topic. I have the same error. I tried many things to block this : disable the back and recent applications buttons when in Moonlight but that's not correcting the problem. I'm on OnePlus 3 but I think this happens with most of all phones. Also I'm using a Xbox One Wireless controller.

**Comment by nhatku811** [comment]
The only way to solve this is bt using usb/bt joycenter, to override the main gamepad driver with its custom one I guess.

**Comment by nhatku811** [comment]
But I have to wire my xbox one controller to my phone, and wirelessly connect it via bluetooth is not supported by the app.
