### ISSUE TITLE
AirTV: Bad framerate and high decoder latency

### ISSUE THREAD

**Issue by ghost** [moonlight-stream/moonlight-android#434]
Hi there, I bought an AirTV device mostly for Sling TV and other video streaming (works great for all that stuff) and decided to try my hand at using GeForce Experience paired with Moonlight off the cuff.

Initial setup was absurdly easy, but I have struggled getting this to perform well. When I try to launch a game, or even just Steam, the framerate is somewhat poor (definitely not 60 fps) and the latency also isn't good. When I press the home button, the popup states that the "Hardware decoder latency" is around 100ms.

Here are my PC Specs:
CPU: Intel Core i7-3930K @ 3.20GHz
GPU: GEFORCE GTX 770
RAM: 16 GB
HDD: 120GB SSD

Not sure if they will be useful, but here are the supposed AirTV device specs:
http://www.slatedroid.com/topic/111186-airtv-specs/

It would be cool if I could get this going, but not a total loss if the device just can't decode the video stream fast enough. Not sure if there are any logs I can provide to make this easier to troubleshoot.

Thanks for working on this project and thanks for reading!

**Comment by thw0rted** [comment]
Is it possible to connect the device over ethernet instead of wifi?  It can be helpful to eliminate network latency as a source of lag before you start looking at the device hardware or OS.

**Comment by teconmoon** [comment]
Both devices are connected over Ethernet already

**Comment by teconmoon** [comment]
I was able to use the Moonlight iOS App over wifi with basically zero latency, so I think network issues can be ruled out. Not sure if there's a way to get the AirTV to decode the incoming stream with less latency.
