### ISSUE TITLE
ports forwarded but PC still ofline?

### ISSUE THREAD

**Issue by chrislightsaber** [moonlight-stream/moonlight-android#435]
ive deleted all the app that i have that might conflict with moonlight and port forwarded all the ports (yes there correct), yet whenever i leave my home wifi my PC appears offline. any help? ive already uninstalled and reinstalled gefore, i do have shield streaming enabled (and can even stream but only on my home wifi)
all help is appreciated
thanks in advance!

**Comment by muffinmannameistaken** [comment]
try and adding your pc manually put in you external ip  you have to do this everytime you leave your home if not restart your router

**Comment by chrislightsaber** [comment]
i have added the computer to my host list, but it appears offline whenever i leave the home or switch internet, i will try restarting my router though as i had not tried before, but the ports are open ( theres a device to test if there open)

**Comment by chrislightsaber** [comment]
the restart didnt work :/ any other suggestions?

**Comment by chrislightsaber** [comment]
i found the answer in another section.

https://github.com/moonlight-stream/moonlight-ios/issues/140

I had this problem as well, but I found out it's a bug. Remove the host from your list and pair it again from another network with hosts IP address (with 4G like I did, for example). Now you can play your games via home network AND via Internet. ;)

**Comment by chrislightsaber** [comment]
basically i have to logon from a different wifi, and cant logon to the wifi that my pc uses or else it resets to (offline) when i leave
this is a bug that i hope is fixed soon

**Comment by cgutman** [comment]
This should be fixed in Moonlight Android v5.2
