### ISSUE TITLE
Connecting to Moonlight over the internet (different wi-fi) vs LTE

### ISSUE THREAD

**Issue by bavg3** [moonlight-stream/moonlight-android#439]
Need some help:

I followed all of the port forwarding info I could find for my modem, but had to piece it all together from various sources. My host PC is in Denver, and I am currently in Seattle. I *can* connect to my PC when I'm on my phone's LTE hotspot, but when I change to the hotel Wi-Fi the PC isn't able to connect. Thoughts? I've tried Ethernet hotel internet, Wi-Fi- hotel internet, Using a portable Wi-Fi- router, & LTE hotspot; only one that works is the LTE hotspot. I even tried it at the Denver airport which did not work either. Being I'm able to connect from my LTE, wouldn't that mean I did the port forwarding correctly?

Any and all help would be greatly appreciated. I used IPv6 if that makes a difference.

**Comment by cgutman** [comment]
If you're streaming over IPv6, your hotel may not provide a IPv6 connection.
