### ISSUE TITLE
Controller Input Is Not Detected

### ISSUE THREAD

**Issue by StygianHawk** [moonlight-stream/moonlight-android#44]
I use a Nexus 7 2013 running Lollipop (5.0.1) (Non-rooted) and an OTG cable to connect to a PS3 controller/ Xbox 360 wireless receiver. The controllers work on the android interface and work on when directly connected to the PC.  When streaming using limelight the controllers are still connected to the device but input is not detected by the PC.  Touchscreen input is still detected and still works as mouse.

**Comment by D3add3d** [comment]
Confirming this issue, Nexus 7 2013, wired Microsoft Xbox 360 controller, using latestMoonlight version from Google Play and latest GFE

**Comment by cgutman** [comment]
Did you try in several games?

**Comment by D3add3d** [comment]
I tried it with The Crew(Uplay), Battlefield 4(Origin), The Witcher 3(GOG Galaxy) and Portal 2(Steam) - none worked... but in the meantime I rebooted my N7 and PC and now everything is working great except from my router not keeping up(it should handle up to 300Mbps with no problem but 20Mbps seems to lag from time to time)

PS: I think you should investigate why did I had to reboot my devices for it to start working
