### ISSUE TITLE
Build help

### ISSUE THREAD

**Issue by muffinmannameistaken** [moonlight-stream/moonlight-android#440]
I'v been running into this problem when trying  to build moonlight with Android studio, "Could not find com.android.tools.build:gradle:3.0.0.-beta5". 
Any way that I can fix this ? 
thanks

**Comment by cgutman** [comment]
You're probably on the stable release of Android Studio. Moonlight currently only builds on the with Android Studio 3.0 Beta 5.

**Comment by muffinmannameistaken** [comment]
cool thanks
