### ISSUE TITLE
Is the micro-stuttering still not fixed with Android 6.0+ on WiFi (not Ethernet)?

### ISSUE THREAD

**Issue by JasonS7notG5** [moonlight-stream/moonlight-android#441]
See title. This problem is still there with the newest Moonlight 5.2 and new Windows 10 install, newest GeForce Experience etc.

The APK which "fixed" the micro-stuttering introduced more latency / input lag. Have you guys not looked at it again and found a "fix for the fixed version"? I mean it's the same apparently on the Shield when connected via WiFi and like every other Android 6.0 and newer version device. I only read that only when connected via Ethernet the micro stutters will not occur. But that's not a solution nor even a possibility for smartphones.

**Comment by cgutman** [comment]
Nope, still not fixed.

**Comment by JasonS7notG5** [comment]
Will it ever get fixed? Have you guys worked on it after that "APK fixed version" or put it on hold since then? This is more of a critical "feature" which must be adressed before new features and other stuff, at least that's my opinion.

**Comment by JasonS7notG5** [comment]
@cgutman Have you looked at anything frame-rate video decoder related stuff? This could be something less related to total frame-rate but **frame-times** instead. Bad frame-times (_jumping up and down, instead of constant 16.7ms_) makes some 60FPS games especially on consoles feel like 60FPS games (_input_) BUT the **video does not look like proper 60FPS** (= _micro stutters_). This may be related to this Moonlight problem.

**Comment by saiotek** [comment]
Is it possible to get the microstutters fix into master as an option? Default could be disabled...
