### ISSUE TITLE
Mouse not scaling properly

### ISSUE THREAD

**Issue by discojon** [moonlight-stream/moonlight-android#443]
I am using Moonlight with my Galaxy N8.  Everything is working perfectly other that the mouse i have hooked to the phone (via DEX Station) isn't scaling properly to the remote PC.  I can move the mouse the fill width of the mousepad and it will barely move on the Remote PC.  The "local" mouse hooked to the phone moves properly and works properly with other VNC applications.

**Comment by cgutman** [comment]
This is a limitation of Android 7.1 and earlier and the GameStream protocol's mouse support. The GameStream protocol only supports receiving mouse cursor deltas, but Android (prior to Oreo) only supports reporting the absolute position of the mouse. Moonlight extrapolates deltas out of those absolute positions, but it's still limited by the bounds of the window.

If your device is rooted or you are willing to root it, you can use the version of Moonlight called "Moonlight for Rooted Devices" which uses root to be able to capture the mouse and avoid this issue.

Moonlight also has support for the new [Pointer Capture API](https://developer.android.com/preview/features/pointer-capture.html) in Android 8.0 Oreo, which works without requiring root. When your Note 8 gets updated to Oreo, Moonlight mouse capture will just work.

**Comment by discojon** [comment]
Thanks. I'll just hold out for Oreo as root isn't yet available.
