### ISSUE TITLE
GFE error: Nvstreamer initialization failed as encoder not supported (error 569)

### ISSUE THREAD

**Issue by Peppernose145** [moonlight-stream/moonlight-android#446]
I can't connect because of this error. I whitelisted my phone's IP and GFE in the firewall (COMODO Internet Security), My phone (Samsung Galaxy S7) is connected to 5Ghz Wi-Fi, and my computer is connected by wire to the same router. System specs are: 
GPU: GTX 750 Ti 1gb
CPU: AMD Athlon II X4
MB: Asus M5A78L-M Plus
RAM: 8gb

Any help would be appreciated.

**Comment by dvdjg** [comment]
I have the same issue.  System specs are:
GPU: GTX 750 Ti 1gb (I bough this just for stream because mu old GTX 560 lacks hardware encoder)
CPU: Intel Xeon Quad Core
MB: Gigabyte EP35
RAM: 6gb

**Comment by cgutman** [comment]
Can you upload your logs from C:\ProgramData\NVIDIA Corporation\NvStream and link here? ProgramData is hidden so you may need to enable hidden files to see it.

**Comment by dvdjg** [comment]
Of course!


#1(I)[2017-11-02 21:29:59,295]=22:29:59={000022F0}<NvStreamer>       Custom Ctrl+C handler successfully set.
#2(D)[2017-11-02 21:29:59,298]=22:29:59={000022F0}<Utils>            The CPU doesn't support XSAVE and AVX (PF_XSAVE_ENABLED)
#3(I)[2017-11-02 21:29:59,300]=22:29:59={000022F0}<Utils>            Disabled AVX instructions using _set_FMA3_enable(0)
#4(I)[2017-11-02 21:29:59,301]=22:29:59={000022F0}<NvStreamer>       PID 8952
#5(I)[2017-11-02 21:29:59,301]=22:29:59={000022F0}<NvStreamer>       Streaming Process ID: 0
#6(D)[2017-11-02 21:29:59,302]=22:29:59={000022F0}<VersionDump>      Version Information:
#7(D)[2017-11-02 21:29:59,303]=22:29:59={000022F0}<VersionDump>      Name: NvStreamer
#8(D)[2017-11-02 21:29:59,303]=22:29:59={000022F0}<VersionDump>      Major: 1
#9(D)[2017-11-02 21:29:59,303]=22:29:59={000022F0}<VersionDump>      Minor: 1
#0(D)[2017-11-02 21:29:59,303]=22:29:59={000022F0}<VersionDump>      User Name: builder
#1(D)[2017-11-02 21:29:59,303]=22:29:59={000022F0}<VersionDump>      Host Name: WIN7-H03-23
#2(D)[2017-11-02 21:29:59,303]=22:29:59={000022F0}<VersionDump>      Build DateTime: Tue, 10 Oct 2017 01:45:08
#3(D)[2017-11-02 21:29:59,303]=22:29:59={000022F0}<VersionDump>      Build Configuration: release
#4(D)[2017-11-02 21:29:59,303]=22:29:59={000022F0}<VersionDump>      Build Version: 1.1.2296.2627
#5(D)[2017-11-02 21:29:59,303]=22:29:59={000022F0}<VersionDump>      P4 Clientspec: unknown
#6(I)[2017-11-02 21:29:59,303]=22:29:59={000022F0}<VersionDump>      P4 Changelist: 22962627
#7(D)[2017-11-02 21:29:59,303]=22:29:59={000022F0}<VersionDump>      DVS Build: 1
#8(D)[2017-11-02 21:29:59,303]=22:29:59={000022F0}<VersionDump>      DVS Branch: gcomp/rel/gs_04_02
#9(D)[2017-11-02 21:29:59,303]=22:29:59={000022F0}<VersionDump>      DVS OS: WindowsMisc
#0(D)[2017-11-02 21:29:59,303]=22:29:59={000022F0}<VersionDump>      DVS Component: gs_04_02 Release Windows Mjolnir NvStreamer
#1(D)[2017-11-02 21:29:59,303]=22:29:59={000022F0}<VersionDump>      DVS IsVirtual: false
#2(D)[2017-11-02 21:29:59,303]=22:29:59={000022F0}<VersionDump>      DVS P4HWChangelist: 39465154
#3(D)[2017-11-02 21:29:59,303]=22:29:59={000022F0}<VersionDump>      DVS P4SWChangelist: 22962627
#4(D)[2017-11-02 21:29:59,303]=22:29:59={000022F0}<VersionDump>      DVS P4VirtualChangelist: 22962627
#5(D)[2017-11-02 21:29:59,303]=22:29:59={000022F0}<VersionDump>      DVS SubmittedByUserName: amcauley
#6(I)[2017-11-02 21:29:59,303]=22:29:59={000022F0}<SignalingContain> Creating a MB SCI Thread
#7(D)[2017-11-02 21:29:59,311]=22:29:59={000022F0}<NvThread>         Started native thread: BusMessageProcessingThread (thread id: 00002FC0)
#8(I)[2017-11-02 21:29:59,311]=22:29:59={000022F0}<SignalingContain> SCI Thread creation done
#9(I)[2017-11-02 21:29:59,311]=22:29:59={000022F0}<NvStreamerState>  Enumerating network adapters on this system
#0(D)[2017-11-02 21:29:59,313]=22:29:59={00002FC0}<SciMb>            SciMb worker thread starting.
#1(D)[2017-11-02 21:29:59,322]=22:29:59={000022F0}<NvNetworkWin32>   Enumerate Adapters: found adapter {6A7BC25D-B47E-495D-AADD-EC730B08C96E} - Ethernet
#2(D)[2017-11-02 21:29:59,322]=22:29:59={000022F0}<NvNetworkWin32>   Network Query Parameter: 000000E18195F0E0 - 1, 000000E18195EF00, 32, 0000000000000000
#3(D)[2017-11-02 21:29:59,322]=22:29:59={000022F0}<NvNetworkWin32>   Network Query Parameter: 000000E18195F0E0 - 2, 000000E18195EF00, 32, 0000000000000000
#4(I)[2017-11-02 21:29:59,323]=22:29:59={000022F0}<NvStreamerState>  --- 00:1D:7D:09:6E:D0: 192.168.1.41 / fe80::7cb4:e260:b5ce:b45b%7
#5(D)[2017-11-02 21:29:59,323]=22:29:59={000022F0}<NvNetworkWin32>   Enumerate Adapters: found adapter {136FC9E1-72BA-47CA-B037-E3B62F8CBA82} - VMware Network Adapter VMnet1
#6(D)[2017-11-02 21:29:59,323]=22:29:59={000022F0}<NvNetworkWin32>   Network Query Parameter: 000000E18195F0E0 - 1, 000000E18195EF00, 32, 0000000000000000
#7(D)[2017-11-02 21:29:59,323]=22:29:59={000022F0}<NvNetworkWin32>   Network Query Parameter: 000000E18195F0E0 - 2, 000000E18195EF00, 32, 0000000000000000
#8(I)[2017-11-02 21:29:59,323]=22:29:59={000022F0}<NvStreamerState>  --- 00:50:56:C0:00:01: 192.168.81.1 / fe80::9590:8159:890f:2ea9%2
#9(D)[2017-11-02 21:29:59,323]=22:29:59={000022F0}<NvNetworkWin32>   Enumerate Adapters: found adapter {41C371BB-918A-4F0C-BADF-6B5FC23B527A} - VMware Network Adapter VMnet8
#0(D)[2017-11-02 21:29:59,323]=22:29:59={000022F0}<NvNetworkWin32>   Network Query Parameter: 000000E18195F0E0 - 1, 000000E18195EF00, 32, 0000000000000000
#1(D)[2017-11-02 21:29:59,323]=22:29:59={000022F0}<NvNetworkWin32>   Network Query Parameter: 000000E18195F0E0 - 2, 000000E18195EF00, 32, 0000000000000000
#2(I)[2017-11-02 21:29:59,323]=22:29:59={000022F0}<NvStreamerState>  --- 00:50:56:C0:00:08: 192.168.31.1 / fe80::a9c9:26db:443a:4899%5
#3(D)[2017-11-02 21:29:59,323]=22:29:59={000022F0}<NvNetworkWin32>   Enumerate Adapters: found adapter {811AE1F1-BEF8-11E7-8D77-806E6F6E6963} - Loopback Pseudo-Interface 1
#4(I)[2017-11-02 21:29:59,329]=22:29:59={000022F0}<NvStreamerState>  Building head list
#5(I)[2017-11-02 21:29:59,337]=22:29:59={00002FC4}<SciMb>            SCI:SciNvStreamer has connected to MessageBus
#6(I)[2017-11-02 21:29:59,337]=22:29:59={00002FC4}<SciMb>            SSAU:StreamerController is present on MessageBus.
#7(I)[2017-11-02 21:29:59,370]=22:29:59={000022F0}<NvEncUtil>        Computing SPS/PPS headers.
#8(I)[2017-11-02 21:29:59,374]=22:29:59={000022F0}<FbcUtil>          Loaded library from 'C:\WINDOWS\system32\NvFBC64.dll'
#9(I)[2017-11-02 21:29:59,694]=22:29:59={000022F0}<AdapterContext>   Initialized context for adapter 0: 1920 x 1080 @ 60.0 Hz
#0(I)[2017-11-02 21:29:59,694]=22:29:59={000022F0}<AdapterContext>   Driver version is 388.0, branch is r387_90.
#1(I)[2017-11-02 21:29:59,695]=22:29:59={000022F0}<AdapterContext>   System is NOT co-proc.
#2(D)[2017-11-02 21:29:59,818]=22:29:59={000022F0}<AdapterContext>   GPU memory usage: used = 210.889844, free = 813.110156 MB, total = 1024.000000 MB
#3(I)[2017-11-02 21:29:59,819]=22:29:59={000022F0}<AdapterContext>   Initialized CUDA for device 'GeForce GTX 750 Ti' (SM 2.1) in compute mode 'CU_COMPUTEMODE_DEFAULT'.
#4(I)[2017-11-02 21:29:59,852]=22:29:59={000022F0}<GPUInfo>          GPU's = {
#5(I)[2017-11-02 21:29:59,852]=22:29:59={000022F0}<GPUInfo>          	{
#6(I)[2017-11-02 21:29:59,852]=22:29:59={000022F0}<GPUInfo>          	FriendlyName=GeForce GTX 750 Ti
#7(D)[2017-11-02 21:29:59,852]=22:29:59={000022F0}<GPUInfo>          	Is GPU in local Game Streaming Whitelist=1
#8(I)[2017-11-02 21:29:59,852]=22:29:59={000022F0}<GPUInfo>          	}
#9(I)[2017-11-02 21:29:59,852]=22:29:59={000022F0}<GPUInfo>          }
#0(I)[2017-11-02 21:29:59,852]=22:29:59={000022F0}<GPUInfo>          Nvidia GPU count: 1, Non Nvidia GPU count: 0
#1(I)[2017-11-02 21:29:59,852]=22:29:59={000022F0}<ServerMiscUtils>  Found a match at [5]
#2(D)[2017-11-02 21:29:59,852]=22:29:59={000022F0}<VideoEncoder>     Creating NvEnc7VideoEncoder.
#3(I)[2017-11-02 21:29:59,852]=22:29:59={000022F0}<VideoEncoder>     Initializing NvEnc7VideoEncoder.
#4(I)[2017-11-02 21:29:59,852]=22:29:59={000022F0}<NvEnc7VideoEncod> Using NvEnc header version 0.7.
#5(E)[2017-11-02 21:29:59,853]=22:29:59={000022F0}<NvEnc7VideoEncod> Device 'GeForce GTX 750 Ti' does not support NvEnc.
#6(E)[2017-11-02 21:29:59,853]=22:29:59={000022F0}<NvEncUtil>        Failed to initialize encoder for RTSP SPS/PPS header generation.
#7(D)[2017-11-02 21:29:59,854]=22:29:59={000022F0}<VideoEncoder>     Destroying NvEnc7VideoEncoder.
#8(D)[2017-11-02 21:29:59,854]=22:29:59={000022F0}<AdapterContext>   GPU memory usage: used = 210.889844, free = 813.110156 MB, total = 1024.000000 MB
#9(I)[2017-11-02 21:29:59,891]=22:29:59={000022F0}<AdapterContext>   Deinitialized CUDA context for adapter 0.
#0(I)[2017-11-02 21:29:59,959]=22:29:59={000022F0}<AdapterContext>   Deinitialized context for adapter 0
#1(E)[2017-11-02 21:29:59,959]=22:29:59={000022F0}<NvEncUtil>        Error computing SPS/PPS headers.
#2(E)[2017-11-02 21:29:59,959]=22:29:59={000022F0}<NvStreamer>       NvEncodeAPI Not Supported
#3(I)[2017-11-02 21:29:59,959]=22:29:59={000022F0}<NvStreamer>       NvEnc initialization failure
#4(I)[2017-11-02 21:29:59,959]=22:29:59={000022F0}<cryptoutils>      SHA-256 input in hex: 66656534386634392D626437302D343830642D386338322D616334646239383130656439 [72]
#5(I)[2017-11-02 21:29:59,960]=22:29:59={000022F0}<cryptoutils>      SHA-256 Hash in hex: C10784D54CEF381D73C174FCCFE80947666A9530D23721D55D64D525DC1DE191 [64]
#6(I)[2017-11-02 21:29:59,960]=22:29:59={000022F0}<NvStreamer>       Send event for StreamerInitFailure with SERVER_TERMINATED_ENCODER_NOT_SUPPORTED
#7(I)[2017-11-02 21:29:59,960]=22:29:59={000022F0}<SciBase>          Sent event StreamerInitFailure: SERVER_TERMINATED_ENCODER_NOT_SUPPORTED
#8(I)[2017-11-02 21:29:59,960]=22:29:59={000022F0}<SciMb>            Stopping SciMb
#9(D)[2017-11-02 21:29:59,960]=22:29:59={000022F0}<NvThread>         About to destroy native thread: BusMessageProcessingThread (thread id: 00002FC0)
#0(D)[2017-11-02 21:29:59,960]=22:29:59={00002FC0}<SciMb>            SciMb worker thread quitting.
#1(D)[2017-11-02 21:29:59,960]=22:29:59={00002FC0}<NvThread>         Completed thread function for native thread: BusMessageProcessingThread (thread id: 00002FC0)
#2(D)[2017-11-02 21:29:59,960]=22:29:59={000022F0}<NvThread>         Destroyed native thread: BusMessageProcessingThread (thread id: 00002FC0)
#3(I)[2017-11-02 21:29:59,960]=22:29:59={000022F0}<SciMb>            SciMb Stopped
#4(I)[2017-11-02 21:29:59,960]=22:29:59={000022F0}<SignalingContain> Terminated the SCI thread

**Comment by dvdjg** [comment]
It says 
> Device 'GeForce GTX 750 Ti' does not support NvEnc.

GPU-Z: [http://gpuz.techpowerup.com/17/11/02/gyv.png](url)

**Comment by cgutman** [comment]
> #3(I)[2017-11-02 21:29:59,819]=22:29:59={000022F0} Initialized CUDA for device 'GeForce GTX 750 Ti' (SM 2.1) in compute mode 'CU_COMPUTEMODE_DEFAULT'.

This is especially interesting. As luck would have it, I also have a GTX 750 Ti in a test machine of mine, and the correct Shader Model for it is 5.0, not 2.1. 2.1 is actually the SM of the 560 Ti, probably no coincidence there...

I'd suggest trying DDU - https://forums.geforce.com/default/topic/878345/geforce-experience/-nvidia-driver-and-geforce-experience-errors-try-this-first-ddu-device-driver-uninstaller-03-19-2017/

**Comment by dvdjg** [comment]
Thanks foryour interest. I follow your suggestion but it didn't work. After clean the drivers by using DDU, and resintall them, it continues saying:
`#3(I)[2017-11-07 21:08:06,841]=22:08:06={00001A18}<AdapterContext>   Initialized CUDA for device 'GeForce GTX 750 Ti' (SM 2.1) in compute mode 'CU_COMPUTEMODE_DEFAULT'.`
