### ISSUE TITLE
Moonlight App gets stuck at windows 10 log in screen

### ISSUE THREAD

**Issue by Jose1703** [moonlight-stream/moonlight-android#447]
Hello, im not sure if anyone else has had this issue but I could not find any resource to help troubleshoot. Searching on google did not provide anything useful.

Essentially, everything about moonlight works perfectly except when i touch any app to start from moonlight it gets stuck on the windows 10 log in screen. On android, i can bring up the keyboard but even entering the correct password will not be accepted by windows. On ios, there is nothing more you can do. Either way, I cant get past the windows 10 log in and therefore cannot use moonlight without manually unlocking my computer first, which kind of defeats the purpose. I noticed that if I remove the password from the PC or simply leave it logged in then the app works perfectly. This is very much not preferable however because it is not safe practice. Any ideas? Thanks in advance!!

**Comment by denisb411** [comment]
I would like to know if there's a way forward for this problem.

**Comment by thw0rted** [comment]
When I have problems like this with Steam Link (similar setup), I connect in with TeamViewer to do the stuff that Steam is locked out of doing.  For example, if I have a UAC / Administrator privileges prompt pop up, Steam Link control input stops working, and I have to remote in with TeamViewer, click the dialog, then I can go back to using the Steam controller.  Moonlight probably works the same way?

**Comment by denisb411** [comment]
@thw0rted I thought of doing this but seems that TeamViewer disable game streaming when it is executing. Didn't try with rdp tho.
Soon I will try and get back for a report.

**Comment by thw0rted** [comment]
Maybe turn off the TeamViewer feature that locks the system on disconnect, remote in and unlock, then connect with GameStream?  If you're worried about security, though -- if your PC is in a shared space and you can't leave it unlocked most of the time -- then remember that GameStream doesn't lock out the host system's local input/output devices, so anybody walking by could take control of your system and kick you out.

**Comment by adamneveu** [comment]
Yeah this still seems to be an issue.
Also on the Chromecast with Google TV too.

Had anyone figured out why the login screen gets stuck?

Mine also is black no video on the lock screen so I punch in the password and can bypass but sometimes I type it wrong and lock myself out for a while
