### ISSUE TITLE
lag when using bluetooth controller

### ISSUE THREAD

**Issue by XBAQMX** [moonlight-stream/moonlight-android#450]
hi, hope someone can help me, I'm having lots of lag that end up crashing the steaming when im using my pair of joy-cons from my nintendo switch, everything works good until I press a button of the remote, thats when the lag starts, i move the game with the pc keyboard and the streaming goes well it only lags and crash when im using the joy-cons. I connected the joy-cons to my android device.

**Comment by thw0rted** [comment]
Have you seen [the docs about Bluetooth-related lag](https://github.com/moonlight-stream/moonlight-docs/wiki/Troubleshooting#bluetooth-related-streaming-issues) yet?

**Comment by XBAQMX** [comment]
ok so it looks like its my phone, ill try it on other one, thanks for the help.
