### ISSUE TITLE
GPD xD XBox Controller not detected anymore 

### ISSUE THREAD

**Issue by greensouth** [moonlight-stream/moonlight-android#454]
Since a couple of months ago, when I launch moonlight, this android console which has a built in xbox controller driver, isn't working anymore. Before, everything worked flawlessly. I have done no update on the system, but moonlight app itself and GeForce Experience+Drivers on the PC side.

Not detected from Steam. Tried all the controller options available on Moonlight. And I don't know if it's an app issue or if GeForce Experience broke something.

Any advise on this??

Thanks in advance!

**Comment by cgutman** [comment]
I believe this was a Steam/GFE compatibility issue. See https://forums.geforce.com/default/topic/1020979/gamestream/controller-not-detected-by-steam/2/

**Comment by greensouth** [comment]
WOW, thank you dude, I thought it was a problem on my side, it’s nice to know that it isn’t.

I will follow that thread to see if someone develop a solution.

Thanks!
