### ISSUE TITLE
RTSP Handshake Failed

### ISSUE THREAD

**Issue by Hobbinss** [moonlight-stream/moonlight-android#455]
All of my ports are forwarded correctly and i can see all of my games. When i try to stream a game outside of my home network my computer will start the game but my Galaxy S8 will get "Failed to start RTSP handshake. There is no error code or anything. 
[NvStreamerCurrent.log](https://github.com/moonlight-stream/moonlight-android/files/1374164/NvStreamerCurrent.log)

**Comment by Hobbinss** [comment]
![20171018_073614](https://user-images.githubusercontent.com/32694536/31725402-23f05bd8-b3d9-11e7-9e6f-7b250eeedd18.jpg)

**Comment by dmwilson220** [comment]
Having the same issue, no RSTP handshake. Fails every time I try to connect, no error log. Double checked my connection settings, everything matches what @Hobbinss has as well. Only difference is I also have port 5353 available for UDP.

**Comment by cgutman** [comment]
Not sure how I missed the reply to this one but as I suspected port 48010 is forwarded as TCP not UDP as per the setup guide.

**Comment by dmwilson220** [comment]
@cgutman Thanks for the quick reply. I just changed port 48010 over to UDP, still having the same issue. It just fails at RTSP with no error code. I tried reinstalling GeForce Experience and the driver as well, no luck.

I just looked at the setup guide, it looks like I have way more ports open than are listed there. Should I remove those and just go with what's stated in your guide?

**Comment by cgutman** [comment]
Yeah, try narrowing down to what's in the guide then screenshot if it's still not working and I'll take a look.

**Comment by Hobbinss** [comment]
Changing port 48010 to UDP from TCP worked for me. Thank you very much.  Can't believe i missed that. I checked them like 5 times haha

**Comment by dmwilson220** [comment]
@cgutman Ok, so I've set it back up only using the ports listed in the setup guide, still getting the same issue. I've attached the log and screenshots. I have an eero system, so unfortunately the only access is through their app, so I had to screenshot each port to show what it was set too.

[NvStreamerCurrent.log](https://github.com/moonlight-stream/moonlight-android/files/1408366/NvStreamerCurrent.log)
![screenshot_20171023-142553](https://user-images.githubusercontent.com/26948997/31906468-2b2ce040-b7ff-11e7-9e40-c0d98006cd9c.png)
![screenshot_20171023-142600](https://user-images.githubusercontent.com/26948997/31906469-2b4537c6-b7ff-11e7-90eb-9393d3e5e705.png)
![screenshot_20171023-142606](https://user-images.githubusercontent.com/26948997/31906470-2b5c244a-b7ff-11e7-9d63-32a70974e5d3.png)
![screenshot_20171023-142611](https://user-images.githubusercontent.com/26948997/31906471-2b7658ce-b7ff-11e7-8c3e-8cedc852db96.png)
![screenshot_20171023-142616](https://user-images.githubusercontent.com/26948997/31906473-2b8daaa6-b7ff-11e7-914a-d9f8dffbf54a.png)
![screenshot_20171023-142620](https://user-images.githubusercontent.com/26948997/31906474-2bba835a-b7ff-11e7-8f89-33b6c1c00ab1.png)

**Comment by isnortflour** [comment]
Some isp's block these types of things. Grab a free vpn to see if that's your issue. My net10 phone runs on at&t network and no matter what i tried i couldn't get past the handshake until i connected to my vpn and then the handshake completed every time after. Although i didn't have the speed to play it i had enough to load the game and enter training mode which confirmed the isp being at fault.
