### ISSUE TITLE
Can't stream in NAT

### ISSUE THREAD

**Issue by XBAQMX** [moonlight-stream/moonlight-android#457]
Hi, hope someone can help me, I'm having troubles trying to stream over the internet, I've  discover that all of my devices in home have the same IPv4, that's couse my ISP use NAT to distribute the Public IP on many clients, I don't know what to do to get an working IP to put on the client.

**Comment by cgutman** [comment]
Are you sure your ISP is implementing the NAT themselves (sharing the same public IP address for multiple independent homes) and you're not referring to NAT in the router (sharing the same IP address to multiple devices in the same home)?

**Comment by XBAQMX** [comment]
hi, thanks for the help, im not pretty sure if is just in my home or in multiple independent homes, I read that my ISP is running out of IPs and sometimes they use same IPs in multiple houses, is there a way for me to check which case is it to be sure?

**Comment by thw0rted** [comment]
Figure out what network device directly connects to your ISP -- if you have cable, it might be a router connected to a cable modem or a combined modem/router.  (It can get more complicated in some situations, like if you have DSL.)  Log into this device (credentials should be on the sticker, if you haven't changed them) and you should be able to find what IP your ISP assigned to you.

If it's in a [private subnet](https://www.arin.net/knowledge/address_filters.html) then your ISP must be doing NAT upstream where you have no control over it -- it may not be "proper" NAT, but rather IPv4 tunneling over IPv6, where you're assigned an IPv6 address but not a "real" IPv4.  Another thing you can check is to search "what is my IP" on Google, and check if it matches the address your router says you've been assigned.

If you only have a public IPv6 address, I'm not sure whether Moonlight will work or not -- I haven't had occasion to try it, personally.

**Comment by XBAQMX** [comment]
OK I checked the ip my modem/router is getting on WAN information settings, an it is completely different to the ip im getting on whatismyip.com 
(https://user-images.githubusercontent.com/32533148/31506755-fda405e6-af3d-11e7-9ce8-7049cdf4015e.png)

**Comment by colin-foster-in-advantage** [comment]
The IP that is showing is a private address, not a public one. 10.X.Y.Z is in the private zone.

https://www.arin.net/knowledge/address_filters.html

As thw0rted said, your ISP is probably doing some magic - not sure how much you'll be able to do. I'll just say good luck!

Lastly, you might want to scramble your MAC addresses when posting. That's typically something you don't want to share.

**Comment by cgutman** [comment]
If they are using carrier grade NAT, they should at least have the decency to give you IPv6 so you can have at least *some* public IP address. Can you see if you can enable IPv6 in your router settings (or it may already be enabled)? Once that's enabled, try http://test-ipv6.com/ to see if you have IPv6 connectivity.

**Comment by XBAQMX** [comment]
thanks for the help @cgutman in fact i do have a configuration on my modem to IPv6 is just that i dont know how to do it, i need the MAC of the cumputer which i can get easily on Windows but it also ask me for an interface ID, i dont know what it is i already tried to put something random but it didnt work. any ideas how to configure it.

(https://user-images.githubusercontent.com/32533148/31553260-80b00db0-afff-11e7-8f44-5d20eea60642.jpg)

**Comment by cgutman** [comment]
Do your PCs already have IPv6 connectivity?
