### ISSUE TITLE
h.265 not found?

### ISSUE THREAD

**Issue by muffinmannameistaken** [moonlight-stream/moonlight-android#458]
Is this a bug? my phone does have support for H.265 but moonlight cannot fined it. I had previous build of moonlight work just fine but the latest does not seem to work.

**Comment by cgutman** [comment]
Well what kind of phone is it?

**Comment by muffinmannameistaken** [comment]
lg stylo 3

**Comment by cgutman** [comment]
This behavior is by design. On Qualcomm chipsets, we prefer H.264 with reference picture invalidation over H.265 without it. You can still force it enabled using the settings.

**Comment by muffinmannameistaken** [comment]
Oh, okay I see but I did try what you said and force it on but I still get the same error.

**Comment by cgutman** [comment]
If you are still seeing this on the latest version of Moonlight, I'll need some extra info about your hardware.

Download the AIDA64 app from the Play Store, then send me screenshots (multiple if needed to get the whole page) of the Display tab and the Codecs tab.

**Comment by muffinmannameistaken** [comment]
Okey i broke my lg phone so I'm using my back up phone that i got last year, h.265 use to work on it but it stop working around October updates of last year, i still do have all the old files and they still do work. 

i have pictures of the old moonlight build and h.265 still works on it but not anymore.

![img_20180214_191201 1](https://user-images.githubusercontent.com/7789466/36240263-0239fa5c-11bd-11e8-859f-8ec59736eaca.jpg)

![img_20180214_191220 1](https://user-images.githubusercontent.com/7789466/36240272-118ae71e-11bd-11e8-8b44-0ae9011e970f.jpg)

![img_20180214_191227 1](https://user-images.githubusercontent.com/7789466/36240274-166912ce-11bd-11e8-8626-0d85307a116d.jpg)


![img_20180214_191237 1](https://user-images.githubusercontent.com/7789466/36240277-1bbde2b8-11bd-11e8-9059-31ecfc65884d.jpg)

![img_20180214_191251 1](https://user-images.githubusercontent.com/7789466/36240279-2008d774-11bd-11e8-8478-284d68e3558d.jpg)

![img_20180214_191306 1](https://user-images.githubusercontent.com/7789466/36240285-24c67654-11bd-11e8-9e09-d4c9c63b5da8.jpg)

![img_20180214_191315 1](https://user-images.githubusercontent.com/7789466/36240287-28894fb4-11bd-11e8-84c1-468e21f4937a.jpg)

![img_20180214_191349 1](https://user-images.githubusercontent.com/7789466/36240292-2c5e676e-11bd-11e8-8e68-9192cbde3ed2.jpg)


![img_20180214_191445 1](https://user-images.githubusercontent.com/7789466/36240297-31606a64-11bd-11e8-8c2a-373f2ff6560b.jpg)

![img_20180214_191754 1](https://user-images.githubusercontent.com/7789466/36240302-36b4afb6-11bd-11e8-85be-38ba81179663.jpg)

**Comment by muffinmannameistaken** [comment]
i fix my phone but will it be possible if i could re-enable h.265 in my own builds? i just need to know where to make the changes

**Comment by cgutman** [comment]
Okay, so it's not working for you because you have an Adreno 300-series GPU. Some devices I tested had serious issues with the HEVC stream (sometimes causing permanent loss of decoding functionality until a device reboot), so I blacklisted the Qualcomm decoder on Adreno parts prior to the 400-series.

You can comment out the line that blacklists the decoder here: https://github.com/moonlight-stream/moonlight-android/blob/master/app/src/main/java/com/limelight/binding/video/MediaCodecHelper.java#L259

**Comment by muffinmannameistaken** [comment]
alright thanks got it to work again. Hay are you still going to add support for other resolutions? I haven't had any problems that anyone has complain about ever sent i started.
