### ISSUE TITLE
Start button doesn't work in some games

### ISSUE THREAD

**Issue by illum1nerdi** [moonlight-stream/moonlight-android#46]
Some games don't recognize the "start" button when pressed on the controller. The button works fine in other games using the exact same controller(s).  This issue occurs whether or not the game is booted/run through Steam or directly via the Limelight games list.

Currently known games to have this issue:

The Wolf Among Us
How to Survive
Dark Matter

Controllers that have this issue:

Madcatz CTRLR
Google Gamepad (with "home" button remapped to "button_start" via a hack to the keylayout file)
Xbox 360 Controller via wireless dongle

**Comment by illum1nerdi** [comment]
Apparently this might be a known issue with certain games and GFE?  I don't have a SHIELD to test it using any of the official NVidia stuff, but I read on the Nvidia GFE forums someone mentioned how certain games don't work for them via Gamestream.  One of the posts that really caught my eye was one regarding Elite: Dangerous not working at one point and then suddenly working, and the poster specifically mentioned the Start button as working, as if this was uncommon for Gamestream games sometimes?

I'm trying to find correlative evidence or documentation here, but so far I've come up with little as of yet.  I'll deep dive on the GFE forums later to see if anyone else has run into this problem on some games and whether or not this is a problem with Limelight or with GFE/Gamestream itself?

**Comment by cgutman** [comment]
I would guess that it's a GFE-compatibility issue, but I'll leave this open until someone can confirm.

**Comment by ketkul** [comment]
I think that probably the GFE problem. Trying to mount dualshock3 to my xperia z1. And it also have this kind of issues. Eg. Final Fantasy XIII2. But on other games its work completely fine

**Comment by ketkul** [comment]
Also not working on Final Fantasy XIII. Damn square-enix and its optimization. Its quite pointless since start button needed to bring save menu.

**Comment by cgutman** [comment]
This is a GFE issue (if it still exists). Closing the issue on Moonlight.
