### ISSUE TITLE
Error code: 599

### ISSUE THREAD

**Issue by elestopa** [moonlight-stream/moonlight-android#460]
When I try to close the session (mstsc.exe) it says: 
"This session wasn't started by this device, so it cannot be quit. End streaming on the original device or the PC itself. (Error code: 599)"

When the game.exe is open, I can exit it and log back in with my device.

Not only does it fail with mstsc.exe, this happens with all games. Moonlight opens the game.exe on my PC, but can not close it, giving me error 599.

I think the problem is when I install the latest GFE Beta (Allow experimental features).
If I do not activate this function, this does not happen and works correctly and allows me to close the applications with my device.

I checked it.

I did a clean uninstall with DDU, reboot, and CCleaner. Then it worked again.

Now I have discovered that it is not necessary to use DDU, just uninstall GFE and use CCleaner, cleaning files and registry. Now, without activate "experimental features" it works correctly.

Edit:

New official update 3.10.0.95, the same error still occurs.

**Comment by cgutman** [comment]
Confirmed. I don't know how I missed this when I tested the update in beta.

**Comment by cgutman** [comment]
Fixed in v5.2.1
