### ISSUE TITLE
Can you provide instructions on how to modify code to apply the stuttering fix?

### ISSUE THREAD

**Issue by chicozeb** [moonlight-stream/moonlight-android#461]
Hi. Can you provide instructions on how to change the code of moonlight to apply the microstuttering fix? Some people complain about latency, but I'm having a very good experience with android tv and Ethernet.

Since i don't want to bother you to post a modified version with the fix everytime you release a new build, i thought that maybe you can tell me what changes are necessary to the source code, so i can do that myself and compile the apk.

I don't have much experience with programming, but maybe with your help i can do this.

Thanks.

**Comment by saiotek** [comment]
https://github.com/moonlight-stream/moonlight-android/commit/91261f95209409adaf43e15d0a5c27299f9e2fa1

this should be the microstuttering fix... (there is a branch frame-pacing)

**Comment by chicozeb** [comment]
Thanks! I'll check it out.

**Comment by chicozeb** [comment]
I'm having difficulties creating the apk. I'm using android studio beta, it downloads everything, i have ndk installed but it gives me an gradle error that cannot find dependencies(and something else that i don't recall exactly).

I've installed the git bash, but gives me an error when i use the git submodule update --init --recursive command, that it's not a git repository...

I'm using windows 10. 

I'm a bit lost here...

**Comment by saiotek** [comment]
@cgutman can you build version v5.2.1 with the microstuttering fix?

**Comment by cgutman** [comment]
yeah, here - https://drive.google.com/open?id=0B_5O1xNt8Q9lUEZtbFNkT3c2RWs

I'm going to just include an advanced option for it in the next build.

**Comment by chicozeb** [comment]
Great! Thanks! Good work, by the way. :)

**Comment by cgutman** [comment]
Fixed
