### ISSUE TITLE
resolutions?

### ISSUE THREAD

**Issue by muffinmannameistaken** [moonlight-stream/moonlight-android#462]
Hay would it be possible for you to add support for other resolutions to the main build? you no longer need Geforce beta or experimetal features enable to get them to work. Here's the code that I'v been using.

[moonlight.txt](https://github.com/moonlight-stream/moonlight-android/files/1397139/moonlight.txt)
If you don't know the locations to make the changes i can it in the .txt

**Comment by muffinmannameistaken** [comment]
hello?

**Comment by cgutman** [comment]
Yep, I've got it. I have on my to-do list to go back and test unsupported resolutions.

**Comment by muffinmannameistaken** [comment]
Awesome! thanks!

**Comment by muffinmannameistaken** [comment]
hay are you still going to adding support for other resolutions ?

**Comment by cgutman** [comment]
Yes, I'm working on other fixes at the moment but it's on the list.

**Comment by JamesBelchamber** [comment]
Hey, so is this possible now? I saw that this has been a long-requested feature but previously the answer was that it wouldn't work. I have a 3:2 Pixelbook and I'd love to get this working without reverting to 16:9 with the horrible chunky borders.

Happy to start hacking away on a PR if so :)
