### ISSUE TITLE
Stream freeze h.265

### ISSUE THREAD

**Issue by Creazawolf** [moonlight-stream/moonlight-android#464]
This app is Amazing.  I use it with my phone and my raspberry pi all the time. I have an Android box aswell with a Amlogic 912 chip and I can stream and play 4k without any problems. But whenever I force h265 decoding the stream freezes after 1 second. This is not the case with h264, but there I get 110ms.. My phone is better at recieving the stream comparing with my Android box which considering the power of the chip is really weird.

Anyway, does anybody know why the stream freezes After 1 second on h265?

Love your work guys, thank you.

**Comment by cgutman** [comment]
Does it freeze with H.265 at 1080p or 720p?

**Comment by Creazawolf** [comment]
Both, same with both FPS settings.

**Comment by apoklyps3** [comment]
I was thinking on getting an S912 tv box too for the moonlight, but everything above 30ms delay is a deal breaker.
110ms? jeeze 
:(

**Comment by Creazawolf** [comment]
Usually they are great devices for Android gaming and other media related activities. But for Moonlight.. No, Sorry. Not yet!

**Comment by Creazawolf** [comment]
UPDATE!

I get sound but video still freeze

**Comment by apoklyps3** [comment]
true shame. the box seems powerfull enough...

**Comment by cgutman** [comment]
Fixed in v5.6.1
