### ISSUE TITLE
Dualshock 4 Controller Trigger Issue

### ISSUE THREAD

**Issue by jtran2795** [moonlight-stream/moonlight-android#465]
I've noticed that Android captures L2/R2 of the Dualshock 4 as button inputs 104, 105, and separate trigger axes for each trigger. I believe this causes an issue in which two L2 or R2 signals can be when using a trigger, which affects some games.

On a Sony Xperia X, using a Dualshock 4 connected by Bluetooth. This might be an issue exclusive to Sony phones due to the Dualshock 4 software built in.

**Comment by cgutman** [comment]
Should be fixed in the next release
