### ISSUE TITLE
Can only stream with host device monitor switched on 

### ISSUE THREAD

**Issue by bdodd135** [moonlight-stream/moonlight-android#466]
Hi loving the app it's revolutionised how I play games day to day.

Just something I'd like some help with, and if this is more widespread, then hey, maybe we could help some others along the way.!

I have this issue where I can only stream to an android device when the host device (my pc) has it's monitor switched on, now turning the monitor off results in around 1-2 seconds of the video content getting through (which I'm guessing is just due to latency) and then the video stream stops completely in its tracks (no black screen just frozen video, however audio maintains throughout any of the following test including the one just described.

Test 1. Starting a stream with the monitor off results in a stopped video stream with audio, however turning on the monitor during this brings the stream of video alive on the recieving device .

Test 2. Starting a stream with the monitor on works as normal, turning this off results with the issue in question (frozen video with audio) and turning back on it is fine, repeating the switch off of the monitor, eventually maintains a constant stream without the monitor having to stay on which is strange, as if it's a way for the gpu to realise which is the primary display.

Test 3. Having any custom Nvidia control panel graphics settings (AA, V-sync technologies ect), causes the stream to never work without the monitor on, this also exists out of the running game and causes it to minimise which is a strange side effect.

Test 4. Unplugging the monitor fom the gpu and rebooting the pc has the same condition as if I started a stream with the monitor just simply turned off.... No visual but sound is fine.

Some useful info below;

Host machine
GTX 1050ti using display port to a HP zr24w
Windows 10
Latest GameReady drivers and beta version of GeForce experience

Stream recieving devices
Hudl2
Sony Xperia M4 Aqua
Sony Bravia KDX8305C
Latest versions of moonlight on all (but this fault have been ongoing with previous iterations of the app)

-
If you need anything else or have any diagnostics you want trying out let me know as I'd love to get this working flawlessly at some point!

**Comment by cgutman** [comment]
Yeah, this is a limitation of GameStream at the moment unfortunately. I believe NVIDIA is investigating making the display optional but for now it's required. For my test machine, I got one of these to fake a display for GameStream - https://www.amazon.com/fit-Headless-GS-resolution-emulator-game-streaming/dp/B01EK05WTY/

**Comment by muffinmannameistaken** [comment]
i know this is a old post but iv been using xdisplay to fake a monitor input so that i can run my desktop/laptop with out a display.
