### ISSUE TITLE
Extreme mouse desync

### ISSUE THREAD

**Issue by Cur** [moonlight-stream/moonlight-android#468]
This makes games unplayable. It would be bearable if when i move my mouse to the corner of the screen that it kept going but it's blocked at the border so you cant continue moving the mouse that's lagging behind.

Starting with my mouse from my home PC in the centre of the screen, and the mouse overlay from android in the centre, i can move the android mouse all the way to the border and it's only moved 1CM from the center of the screen.

Not using the Rooted. There has to be a way to have the mouse sync better so it's at least somewhat usable??

Video showing how severe the issue is: https://youtu.be/CJtmM8QB6m0

**Comment by genmatrix** [comment]
What version of Android are you using?

**Comment by Cur** [comment]
About section shows:
Android Verision 6.0
Security patch level 5 May 2017
Kernel version 3.18.19

Attempting to update shows no updates.

**Comment by cgutman** [comment]
This is a limitation of Android prior to 8.0 Oreo. There was no way to capture the mouse pointer without root access. The rooted version can capture the mouse on earlier versions of Android.

Without mouse capture, there's no way to keep the host and client mouse in sync due to how the GameStream protocol operates.

**Comment by bdefore** [comment]
i'm experiencing the inverse problem on an asus chromebook flip running the android play version. the on-screen mouse moves much farther than my movements on the touch screen. it may be unrelated, but the cursor also moves relative to the motion following first touch - it does not reposition to where the first touch is before moving.

**Comment by bdefore** [comment]
related issue: https://github.com/moonlight-stream/moonlight-android/issues/443

**Comment by r3dcat** [comment]
I am experiencing the same issue mouse pointers out of sync
Using rooted android 7.1.2 with moonlight root 5.5
Was not seeing this issue on my old media player running rooted android 4
Any suggestions?

**Comment by cgutman** [comment]
@r3dcat how did you root your device? I think it may depend on the 'su' implementation whether or not you see the bug.

**Comment by cgutman** [comment]
Are you running the root version of Moonlight?

**Comment by r3dcat** [comment]
"Using rooted android 7.1.2 with moonlight root 5.5"
Yes I am running the latest root version of Moonlight :)

**Comment by cgutman** [comment]
Ah sorry. Did you get a root access prompt when your first tried to stream? Does Moonlight appear in the list of root-approved apps in your root management app?

**Comment by r3dcat** [comment]
Ok issue fixed for me now. I re flashed an updated 7.1.2 rom in my case M8S_PRO-V0928_Nano-20171116.img and installed SuperSU correctly through recovery menu. Then installed and ran Moonlight root and this time all was as it should be :) mouse in sync :)

**Comment by Cur** [comment]
Got a new device, this time rootable.  Rooted.  Installed Moonlight for rooted devices and im in loooove!  exactly like im sitting infront of my home pc!       thanks guys :D
