### ISSUE TITLE
Screen on streaming device is black when PC first wakes

### ISSUE THREAD

**Issue by SpyMachine** [moonlight-stream/moonlight-android#470]
Hi,

So I have an unusual problem that I just started running into. I'm trying to have a setup where I can wake my computer with a controller from downstairs (this is working) and then connect to moonlight to stream games (so I don't have to run back and forth from upstairs to start playing games.

The issue is, for whatever reason, when I try to do this, I get a black screen (but with audio). I've tried using the Android app on a phone and on my Android TV with same results. It was working no problem before when I would start my computer manually, but something about waking it without touching the keyboard or mouse or something is making this happen. The other reason I think this, is because on my phone, I can tap the screen and the display will pop up. Unfortunately, nothing I try to do on the TV seems to be able to do that. 

Any ideas? Thanks!

**Comment by SpyMachine** [comment]
Uploading a logcat...hope that's helpful. Let me know if there's anything else I can provide. I also realized that I do not have this problem on an LG Nexus 5X but am seeing it on my LG v30 and Sony Bravia TV.

[logcat.txt](https://github.com/moonlight-stream/moonlight-android/files/1444229/logcat.txt)

**Comment by cgutman** [comment]
Very strange. Can you upload your server logs from C:\ProgramData\NVIDIA Corporation\NvStream?
