### ISSUE TITLE
how to use moonlight without closing the Firewall？

### ISSUE THREAD

**Issue by lianyanjiajia** [moonlight-stream/moonlight-android#472]
My system is Windows 10 1709.Now I can only use the moonlight with closing the Firewall.I want to now how I can use moonlight without closing the Firewall.

**Comment by cgutman** [comment]
You can probably fix it by changing your network profile to Private mode.

Here's some instructions for Win10: https://tinkertry.com/how-to-change-windows-10-network-type-from-public-to-private
and Win7: http://www.dummies.com/computers/operating-systems/windows-7/how-to-change-a-network-type-in-windows-7/

**Comment by Juheebus** [comment]
Follow these steps:

https://github.com/moonlight-stream/moonlight-docs/issues/69
