### ISSUE TITLE
No video and audio over Internet (Chrome v0.7.4)

### ISSUE THREAD

**Issue by TheDestron** [moonlight-stream/moonlight-android#473]
Streaming inside my network works like a charm. But as soon as I try it over the internet, the application launches but there's just a black screen without audio and the connection closes again. I've checked my port forwarding, it's set up like it should be. Also, streaming on the android app works just great inside and outside my network, so it's somehow an issue with the chrome version of moonlight. How could I solve this?

Ps: I'm on GFE version 3.10.0.95, driver version 388.13.

**Comment by cgutman** [comment]
Did you test Chrome and Android on the same Internet connection? Your outside Internet connection might be blocking the ports that Moonlight requires to work. This is fairly common in some corporate, school, or public WiFi networks.

**Comment by TheDestron** [comment]
Yes I did just that, phone through mobile internet (works), laptop via phone's hotspot (doesn't) and both again at a friends house throug his Wifi, same scenario.
