### ISSUE TITLE
App still won't find my PC

### ISSUE THREAD

**Issue by ElSturge** [moonlight-stream/moonlight-android#476]
I have updated everything possible, the app, GFE, Nvidia Drivers, Windows, everything. The app was working fine about a week ago and all of a sudden it just stopped. The only changes i have made to my PC have been made after the app stopped working. I have tried literally everything i can think of and every suggestion i have seen online, and nothing is working for me. 
Any ideas?

**Comment by nhatku811** [comment]
I have the same problem too. Weird thing is that nvstreamsvc is not present in my computer's services.You should check them out and see if it was installed

**Comment by Slayer418** [comment]
NvStreamSvc doesn't exist anymre. The relevant services are  **NVIDIA LocalSystem Container** and **NVIDIA NetworkService Container**, make sure these are running (Btw it's normal if NetworkService start type is Manual).

**Comment by ElSturge** [comment]
Yeah, both of those services are installed and running, i have even tried restarting them both. Both before and after reinstalling GFE

**Comment by Slayer418** [comment]
One thing I did that I just remembered, I cleared the Shield Devices.
https://i.imgur.com/5ChiYGL.jpg
https://i.imgur.com/agugW7i.jpg

**Comment by ElSturge** [comment]
Yeah I have tried that also. Even after cleaning and reinstalling all nvidia drivers

**Comment by Slayer418** [comment]
Doos http://127.0.0.1:47989/serverinfo page show XML?

**Comment by ElSturge** [comment]
I'm not on my computer at the moment but I'm sure it did last time I checked, showed me lots of code. Assuming far as i could tell, it was successful

**Comment by Slayer418** [comment]
hmm I guess my issue wasn't the same as yours then. I was getting a blank page and now I get the XML.

**Comment by Slayer418** [comment]
Is ShadowPlay working?

**Comment by ElSturge** [comment]
I have tried everything I can think of, uninstalled and reinstalled all relevant applications and drivers, setup Port Forwarding (even though I had it working over Local WiFi before which doesn't require port forwarding). All services that need to be running are. I have tried with and without my firewall active. Nothing has worked so far

**Comment by Slayer418** [comment]
Yeah but is the Alt+Z Overlay working and recording too?

**Comment by ElSturge** [comment]
I believe so, I can't check until I finish work later on, but I think it was the last time I checked

**Comment by ElSturge** [comment]
But I'm pretty sure I recorded a video of my desktop yesterday using it, had to enable Desktop Recording

**Comment by Slayer418** [comment]
Hmm well I guess all is left to do is eradicate anything GFE related. Use [Registry Workshop](http://www.torchsoft.com/en/download.html) for the Reg keys
and [Everything](https://www.voidtools.com/downloads/) to find the files.

**Comment by nhatku811** [comment]
Are you running Windows 10 Fall Update? My problem occurs after I update to 1709, so it could be windows-related. I've surfed the gfe forum and saw others having the same issue.

**Comment by ElSturge** [comment]
Will have to try that Slayer.

And I believe it happened before the 1709 update, but I have since updated to the 1709 update

**Comment by Slayer418** [comment]
On my side I'm still running Win7, don't want to hear anything about the trash we call Win10.  So many things getting broken randomly by Updates and drivers not working properly. For exemple my brother can't even get Optical 5.1 sound to work due to a problem with Win10.

**Comment by ElSturge** [comment]
Would connecting my PC to my router via ethernet make any difference? I didn't have to before

**Comment by nhatku811** [comment]
they're the same

**Comment by ElSturge** [comment]
Ahh right, I hope i can get it to work soon. Will try what Slayer said and will keep you posted

**Comment by AkitoFire** [comment]
Hello,
I have also some kind of problem with Moonlight and/or Nvidia GameStream.
It doesn't work, I can't even connect to my pc.
http://127.0.0.1:47989/serverinfo
doesn't show me XML code and is blank.
I have Windows10 ver 1709.

**Comment by ElSturge** [comment]
I have contacted the creator and from what he told me, it's something on nvidia's side (at least that's what it is for me)

**Comment by nhatku811** [comment]
Try this alternative meanwhile: https://forums.geforce.com/default/topic/1026955/gamestream/geforce-experience-update-3-10-0-95-feedback-thread/2/
I haven't tested it yet bc i'm away from home

**Comment by AkitoFire** [comment]
Hey,
thank you very much for your answers :)
So, after I reinstalled GFE I tested Moonlights Chrome Browser Version and it worked and recognised my PC after seconds.
I will test it now with my smartphone.
Thank you very much!!

**Comment by nhatku811** [comment]
weird cos I can't get it working with my Android. Haven't got any other PCs to try.

**Comment by ElSturge** [comment]
Im gonna try the steps listed here "http://nvidia.custhelp.com/app/answers/detail/a_id/4581/kw/Gamestream/session/L3RpbWUvMTUxMDc1Mjc1Ny9zaWQvZlVTdyU3RSU3RUtGdXpJel9MZjg5cHpXMiU3RThfR0pPWVVVcFJnTmJqdFpGVFBTJTdFVXhWRUNXcl91JTdFSmtIQUlpQnpYSlRwUk5Wb0N5c191Y0d2N21qc3dpTTNkdUJwVnNsOUZNVkFlMjJNeXBjN2NCSTEwR0VXSjBvWnNBUSUyMSUyMQ%3D%3D"
And if they still don't work, im gonna contact nvidia for further help. I think it could be a problem with the 1709 Win10 update and the latest version of GeForce Experience

**Comment by ElSturge** [comment]
Just downloaded the latest drivers, I'll see if they're any better

**Comment by ElSturge** [comment]
Installed the latest drivers, allowed nvcontainer and nvstreamsvc through the Windows Defender Firewall and all is now working well. Thank God

**Comment by Slayer418** [comment]
Glad you got it working again, good gaming mate.
