### ISSUE TITLE
Moonlight only shows the GeForce Experience screen

### ISSUE THREAD

**Issue by zeelee91** [moonlight-stream/moonlight-android#478]
Hi. When I run Moonlight most times I seem to be stuck on the GeForce Experience screen, even if the target .exe is being run. Sometimes, there is a switch but not often. Could anyone advise what is happening please? Thanks!

**Comment by zeelee91** [comment]
Sorry, just realised that there is a similar issue reported below my question.

**Comment by Sagasev** [comment]
Hi Zeelee, I am the guy who posted before the same problem as you.

Can you elaborate more how can I stream the games with your method?
Is it working for you then?
