### ISSUE TITLE
Last work in hardware decoding in version 2.5.3.1

### ISSUE THREAD

**Issue by dan83sama** [moonlight-stream/moonlight-android#48]
Hi, after test and test, expose my problem:
My tablet : 
ARM Cortex A5
Mali-400MP

The last version works hardware decoding is 2.5.3.1 with GFE 2.1.1, the post version works all in software decoding.

Put two logcats:

Works hardware decoding,version 2.5.3.1-GFE 2.1.1
http://pastebin.com/UV0yRcca

Not works hardware decoding.version 2.5.4(nonroot)-GFE 2.1.1
http://pastebin.com/MifJYr0m

**Comment by cgutman** [comment]
Were you forcing hardware decoding on these builds or using auto-select decoder?

**Comment by dan83sama** [comment]
Forcing hardware decoding

**Comment by dan83sama** [comment]
Some tutorial how to compile old versions?(to check precisely the commit where failure), the last with gradle is easy.

**Comment by cgutman** [comment]
The builds before Gradle used an Eclipse project.

**Comment by dan83sama** [comment]
I could not compile with eclipse:
636 errors
Description	Resource	Path	Location	Type Activity cannot be resolved to a type	Connection.java	/Limelight/src/com/limelight	line 31	Java Problem

and more,with gradle is easy.
I wanted try one to one commits to find the error, its only 4 days from 2.5.3.1 to 2.5.4.
Thanks anyway
