### ISSUE TITLE
h265 not working on rockchip 3399 

### ISSUE THREAD

**Issue by grizli21** [moonlight-stream/moonlight-android#481]
Hi all,

Is there a way i could make the hevc working on my yundoo y8 unit ?
If i force the h265 then the screen is freezing after a second.
It is not related to the last moonlight/gfe because it didn't worked with previous versions as well.

It happens whatever resolution is choosen.
Could rockchip hevc codec be in backlist?

my setup:
Yundoo y8
android 7.1.2
moonlight root 5.5

Windows 10
gfe 3.11.0.73 gtx 1080
lan gigabit

Best regards
Nicolas

**Comment by cgutman** [comment]
Your decoder isn't blacklisted but it seems like it doesn't like the H.265 stream that GameStream is sending it. I have a Fire TV 3 that does the same thing. I've put a few hours into trying to figure out what's going wrong but as far as I can tell the decoder just locks up and stops accepting new data. It doesn't look like anything I'm doing wrong with how I'm submitting the data to the decoder or anything and no error messages appear in the logcat that would explain why the decoder hung.

**Comment by grizli21** [comment]
Hi Cameron,
Good news, H265 is working !

I 'm not sure it is related to moonlight 5.6.1 but there is now no freeze anymore in h265 as long as i choose low range bitrate (<= 30mbps).
Delay is even lower and very smooth too.
It has to be forced to be effective.
1080p/60fps at 25mbps give me around 10/8ms input lag. Just perfect for my taste.

Also testing that has been done wired and wirelessly, seems like  high bitrate are not working anymore whatever codec is selected,(stuttering then freeze).

Anyway really happy, thanks you so much.

**Comment by cgutman** [comment]
Fixed in v5.6.1
