### ISSUE TITLE
After streaming, the joystick control loses its vibration function

### ISSUE THREAD

**Issue by shinobiz** [moonlight-stream/moonlight-android#484]
I use the XBOX ONE S joystick control to the Android box, streaming can play steam game, but lost vibration, this problem can be improved in the future?

**Comment by cgutman** [comment]
I believe you're saying that vibration is not supported while streaming. Moonlight does not support joystick vibration yet.

**Comment by shinobiz** [comment]
Yes, will the future increase vibration? Or is it impossible?

**Comment by cgutman** [comment]
It is possible. GameStream supports vibration but Moonlight doesn't yet.

**Comment by shinobiz** [comment]
Okay, thank you
