### ISSUE TITLE
Stuttering or app crash on H.265 - Philips 55PUS6501/12

### ISSUE THREAD

**Issue by qualityghost** [moonlight-stream/moonlight-android#486]
Hi,
with the last Moonlight update v. 5.6 my TV has issues with streaming in H.265: for 1080p app crashes and decoder crash notification displays after restart, for 2160p streaming stutters every 1 second and looks like gameplay with 5 FPS (streaming latency around 30-35ms for 2160p@60/30Mbit). For H.264 nothing change, even for 1080p@60/20MBit gameplay is smoother. 
And the other thing is that HDR streaming (I have been waiting for this feature long time 👍) is not detected by my TV. I have tested that with ME: Andromeda. My TV supports HDR10, Dolby Vision is not supported. Moonlight doesn't report any errors but when HDR is on in Moonlight and in game settings then everything is too bright. When HDR is off in game settings then streaming looks normal as for SDR. When I switch between HDR on/off TV doesn't recognize that. Normally when HDR source is available the TV displays tooltip with information about this.

GFE: version 3.11.0.73
GPU: GTX 1070 drivers version: 388.31
TV: Philips 55PUS6501/12 android version: 7.1.2

**Comment by cgutman** [comment]
Thanks for reporting this crash. I've seen it in the crash reports and now I can finally get to the bottom of it.

Can you try the following APKs and tell me if they have the H.265 crashing/stuttering or not?
https://drive.google.com/file/d/10M_37kjhw1NVv09lPYHmqbUfn1gvMsPk/view?usp=sharing
https://drive.google.com/file/d/1QcLSI-vG90_bTDLAx9w4k4cOrlRVlMFE/view?usp=sharing (if #1 works, you don't need to try this one)

**Comment by qualityghost** [comment]
Hi Cameron,
thank you for a quick response!

I did some quick tests and the first APK works fine with H.265: For 1080p@60 or 2160p@60 no crashing or stuttering. HDR is now detected by my TV but only with 2160p selected in Moonlight and game settings, also not all TV settings are available for this mode e.g. "Perfect Motion". This setting is available in Netflix or pre-defined 'Computer' mode which can be used during connection between TV and computer by HDMI cable. When I find more time I will do more tests and let you know about the results. Anyway good job! 👍

**Comment by qualityghost** [comment]
I tested the app with many settings and I can say that it works very well. As I mentioned before HDR is detected by my TV only when I choose 2160p in Moonlight settings and with that stream setting I can change game resolution in game settings at 1080p or 1440p and TV still displays in HDR mode. Previously I could experience HDR only with 2160p selected on both, TV and the app. (I don't know the reason why it is possible now. Maybe because of TV software update which I did today but I don't think so.)  That solution allows my also to achieve 60FPS by my computer and keeps decoding latency around 20-35 ms with bandwidth set on 30Mbits.  

By the way I would like propose new feature: FPS counter. I do not know if somebody mentioned about this in other post but Shield TV has that feature and would be wonderful if Moonlight also had this option.

Best regards
Piotr

**Comment by cgutman** [comment]
Fixed in v5.6.1.

Thanks for testing so quickly. I added the feature request to my list.
