### ISSUE TITLE
10% GPU Usage on IDLE

### ISSUE THREAD

**Issue by ronferri** [moonlight-stream/moonlight-android#488]
Hello,

I streamed the Desktop from my gaming laptop which has an Nvidia GTX1070 to the TV and noticed the GPU was under 10%-12% load on idle. As soon I disconnect the stream, GPU usage goes back to 0%. Of course the framrates while gaming on TV also decreased by 10% compared to playing on the laptop screen.

Is this an unavoidable GPU tax that I have to pay when streaming to TV?

**Comment by cgutman** [comment]
I assume you're looking at the new Task Manager GPU stats in Windows 10 Fall Creators Update.

It tries to sum up GPU usage into a single number, but the truth is that the GPU has several parts that can all operate independently. The GPU video encoding silicon is separate from the main core that runs your game. They should only minimally reduce each other's performance (~1%) when used together. Part of the reason for that design is exactly to avoid a performance hit when encoding your game like GameStream does.

**Comment by ronferri** [comment]
I see, thanks.

Actually I am monitoring the GPU usage using MSI Afterburner and MSI Dragon Center. GPU usage is at 10% once the stream starts in Power Saving Mode (Downclocked VRAM), but when I switch to high performance mode, GPU usage is at 2% on IDLE.

I still witnessed a decline of 4-7fps while streaming The Witcher 3 on the TV compared to playing it locally on the laptop screen. Either The Witcher 3 is using the encoding engine of the GPU or the split between the main core and the encoding ailicon is not optimized in Moonlight. I am mot an expert but just observing.

I assume there is no way to avoid this performance hit while streaming on the TV?

**Comment by cgutman** [comment]
Interesting, that's higher than I'd expect. None of the Moonlight code is directly running on your PC. It's just activating the GameStream functionality built-in to GeForce Experience.

Try toggling the option in Moonlight that allows GeForce Experience to optimize game settings and see if that fixes it. It will change your game settings while you stream to make it more "optimal" for streaming by default. Depending on your initial settings, it may actually make performance worse.

**Comment by ronferri** [comment]
Geforce experience cannot optimize mstsc.exe which I use to stream the desktop.
