### ISSUE TITLE
Performance on Odroid C1 is very poor

### ISSUE THREAD

**Issue by crazyquark** [moonlight-stream/moonlight-android#49]
Hello guys,

I just tried limelight-stream on Android (installed from Google Play Store) and the performance is awful.
Most likely because video decoding is done in software instead of using the included h.264 hardware codec.
(I am running the latest official Android offered for Odroid - 4.4.2)
The GUI moves very slowly and I keep getting a notification that A/V processing is very slow.

What do you guys think?
This is the board: http://www.hardkernel.com/main/products/prdt_info.php

**Comment by dan83sama** [comment]
Try this:
version 2.5.3.1 Limelight and version GFE 2.1.1 possibly it is the same error https://github.com/limelight-stream/limelight-android/issues/48

**Comment by cgutman** [comment]
Try forcing hardware decoding.

**Comment by crazyquark** [comment]
OK, I will try and report back.

**Comment by crazyquark** [comment]
With force hardware encoding I can almost get games to playable settings by reducing resolution to 720p and target FPS 30.
Still it stutters and gives warnings about high packet loss?
I am on a wired ethernet connection. Is there any way I can collect logs from limelight?

**Comment by cgutman** [comment]
Please retry on 4.0.2 or later and re-open if it's still a problem.
