### ISSUE TITLE
Issue enabling HDR with a Sony Bravia x900E

### ISSUE THREAD

**Issue by horaciobp** [moonlight-stream/moonlight-android#490]
Hello,

I've installed the app on my android TV (Sony x900e) and enabled all the settings on the moonlight client side (H.265, HDR on). But for some reason HDR can't be enabled and the only two Video modes that I have on the TV is: Game Mode or Graphics Mode.
On the netflix app I have no problem enabling HDR, my suspicious is that Netflix is a video app while Moonlight is a game app (don't know how sony/Android TV is handling that).
Thanks

**Comment by cgutman** [comment]
What game are you using to test HDR? Is HDR also enabled in game?

**Comment by horaciobp** [comment]
Battlefield 1. Yes it is, it's working when I use the computer directly.

**Comment by cgutman** [comment]
Try setting the stream to 4k resolution in Moonlight. Some TVs will only engage HDR at 4K.

**Comment by horaciobp** [comment]
Yes  it is. For some reason the TV doesn't show all the image mode options
when moonlight is open.

Em 5 de dez de 2017 12:53 AM, "Cameron Gutman" <notifications@github.com>
escreveu:

**Comment by cgutman** [comment]
What OS, Nvidia driver version, and GeForce Experience version are you running?

**Comment by horaciobp** [comment]
I'm using a GTX 1080Ti
Everything except HDR is working perfectly in the App. 
Windows 10 Home - build 1703
GeForce Experience - 3.11.0.73
Drivers:  388.13

**Comment by geneccx** [comment]
I think this is a limitation of the TV - I have the same TV and while I can turn on HDR in the game settings and from Moonlight, the TV hides HDR mode when it detects anything running as a game.

**Comment by Kaan88** [comment]
The tv works fine in game mode with hdr, I've played movies and games in game mode with my laptop.

**Comment by horaciobp** [comment]
Same thing with me, when I plug the PC directly in the TV, I have no issues. I think the problem is when running android gaming apps (in this case Moonlight), not sure how Sony is handling that.

**Comment by Kaan88** [comment]
I don't even understand how it's supposed to work. The games don't see an hdr capable display when I start them with moonlight.

**Comment by geneccx** [comment]
I believe HDMI inputs cause the TV to go into a different game mode. When you open a native Android game, the picture menu is labeled as Apps (game), which is what removes the HDR setting and auto detection. I've had limited success by setting isGame to false in the manifest (this allows the TV to go into HDR mode), but I'm probably doing something wrong at the compilation step, because if I try to set moonlight to stream above 1080p the picture goes crazy. HDR works, though.

**Comment by horaciobp** [comment]
Do you have to root the TV in order to install the compiled version with the manifest change?

**Comment by geneccx** [comment]
No, you don't.

Anyway, after further testing and doing a full rebuild and setting isGame to false, I was able to successfully enable HDR and stream at 4k60 at 40Mbps.

My GTX 1080 can barely handle Destiny 2 at that resolution though, only getting ~50fps with lowish settings.

**Comment by horaciobp** [comment]
I can try that during the weekend, I can get more than 60fps with Destiny 2 at 4k. I will try on Battlefield 1 as well. If you have a small guide on how to compile and setup would be great.
Thanks

**Comment by JasonConrad** [comment]
You should make sure you're using HDMI 2.0a or later cable.  HDR signals are tricky, they carry metadata which lets the TV know how to decode everything.  That's probably why some people aren't having any issues.

**Comment by geneccx** [comment]
There are no HDMI cables involved here. The TV itself uses Android TV as an operating system and runs Moonlight natively.

**Comment by JasonConrad** [comment]
Ah.  Sorry.  I've never actually heard of Moonlight, I'm just researching HDR myself and trying to get .mp4s to play correctly on my bravia xbr 750 with ffmpeg x265.  Transfer functions, color primaries, matrices, maxfall values, and master display values seem to be important, but I still haven't quite pinned down the secret recipe yet.  Best of luck!

**Comment by leeson865** [comment]
So Moonlight will enable me to stream 4k/HDR games over gigabit network to my HDR TV even if my native PC monitor doesn't support HDR?

**Comment by cgutman** [comment]
Yes, you should be able to enable the experimental HDR option in settings as long as your device runs Nougat or later, has an HEVC Main10 decoder, and the display supports HDR10

**Comment by leeson865** [comment]
So a Samsung Galaxy S8? I can't find HDR in the Moonlight settings.

**Comment by cgutman** [comment]
Is it the Qualcomm or Exynos variant?

**Comment by leeson865** [comment]
Exynos

**Comment by cgutman** [comment]
I just tried Moonlight on an Exynos Galaxy S8 via Samsung Remote Test Lab. It seems HDR is indeed not supported on this variant. It doesn't advertise its display as being capable of any HDR modes, nor does it advertise that its Exynos HEVC codec can decode the HEVCMain10HDR10 profile required by the Android documentation for HEVC HDR - https://source.android.com/devices/tech/display/hdr

In contrast, my Snapdragon S8 does report its display is capable of HDR10 and the Snapdragon video decoder advertises support for HEVCMain10HDR10. These make the HDR option appear in Moonlight.

**Comment by leeson865** [comment]
Thanks for testing. That's odd. HDR in youtube is definitely working on my Exynos S8.

**Comment by 90Ninety** [comment]
@horaciobp How is the Moonlight App working on your TV otherwise? I cannot get it to run at anything over 480p on mine ( 49X8307C) for some reason

**Comment by horaciobp** [comment]
Hi @90Ninety, it's working fine, I haven't been using much lately, but when both the TV and the PC are on an ethernet cable I can get 4k@60fps with no problems.

**Comment by diogosena** [comment]
This issue still present, ans is caused by isgame flag

**Comment by DrewNeilson** [comment]
> Ah. Sorry. I've never actually heard of Moonlight, I'm just researching HDR myself and trying to get .mp4s to play correctly on my bravia xbr 750 with ffmpeg x265. Transfer functions, color primaries, matrices, maxfall values, and master display values seem to be important, but I still haven't quite pinned down the secret recipe yet. Best of luck!

Have you found out those things--"transfer functions, color primaries, matrices, maxfall values, and master display values"--for your XBR 750? If so, how? I have an XBR X900E and I'm looking for that information. It might be different for my set, but I found your message while searching for that information. I'd like to know how you got that information for yours.
