### ISSUE TITLE
"Flicker Effect" on some games makes them unplayable

### ISSUE THREAD

**Issue by Cur** [moonlight-stream/moonlight-android#491]
So far the main culprit for theses appear to be games that have a launcher.

I think you've tried to bypass it by launching the game directly,  however in some cases the launcher still opens with the game and then you're in for an epileptic fit at random intervals when this happens.

It will start with playing the game - then you get alt tabbed out (i assume?  As you go from being active in the game to viewing your desktop)  and once you click back into the game it's flicker heaven.

Sometimes you're just running around and it starts up then stops 20sec later.

Its sporadic with when it will start.  But you cant stop it without closing out of the stream / app and going back in from scratch.  

https://youtu.be/XB4GS71d4Ns

Note when testing was on 5.21  and upgraded to 5.6.1 and the issue persisted.  Had to close / open 4 times before the flickering would stop,  only for it to tab and start doing it again 5min later :(

Another note -  i let it keep flickering and it gradually  changed from in game graphics to the desktop background over a 2min period.  Once it had reached majority of desktop background the screen stops flickering entirely and im getting a crystal clear picture of my desktop.  

The cursor and noise however is coming from in the game (mouse cursor is in game cursor)  and nothing i click reacts.   So the input and audio is  still coming from the game, but the video is uh..  misbehaving.

Specific games / Launcher this will happen with hat i have noticed thus far:

Battle.net launcher and any game in it's library.
Dreadnaught Game / Launcher.

Update*  When WoW Legion was added to the launcher it linked straight to the EXE file.  This opened with different settings than launching the game via the launcher.   I noticed it was set to "Fullscreen" under video settings and at a 1024x768 resolution.   I changed this to Fullscreen (Windowed Mode)   and did get some initial flicker during the loading screen,  but have been playing the last 30min flicker-free.

**Comment by cgutman** [comment]
Looks like this issue - https://forums.geforce.com/default/topic/1022778/gamestream/flickering-with-gamestreaming-on-new-windows-builds-/1/

NVIDIA is working on a fix, but it seems from the last comment, it may be related to having multiple monitors connected?

**Comment by Cur** [comment]
Ahh yep.  That would be it.  I have 3 monitors XD  Hopefully they get it sorted soon. thanks heaps!

**Comment by jsembdner** [comment]
The hint that multiple monitors cause this issue seems to be true for me.
A workaround is to deactivate the other monitors except your main one under Windows. After that I had no issues with flickering anymore.
