### ISSUE TITLE
Manual FPS change

### ISSUE THREAD

**Issue by Nuke142** [moonlight-stream/moonlight-android#492]
Hello.
Please add FPS manual change or 50FPS selector.
I use Android app with my TV Box. Problem is i have jitters and absolutelly not smooth gameplay because tv can use 24hz and 50hz and moonlight can do stream only 30 or 60fps. This is absolutelly #1 problem when we talk about gameplay smooth.
Please contact me if you need more information (nuke142@gmail.com) i know what i talking about.

**Comment by saiotek** [comment]
@cgutman in theory just changing the config.fps in PreferenceConfiguration.java and creating a new resolution with that fps on the host pc would do? Or is GFE restricting that?

I think my Z3 Tablet ist using 59fps vsync only, so if i change the 60 to 59 in the config streaming will be 59. If i change the resolution to 59 on the host pc, than all use 59?

**Comment by saiotek** [comment]
@Nuke142 perhaps you want to check #349 i've linked a moonlight build with 50hz selector for testing.
