### ISSUE TITLE
Just a quick reminder that micro-stuttering is still there

### ISSUE THREAD

**Issue by JasonS7notG5** [moonlight-stream/moonlight-android#493]
Title.

_Newer versions of Moonlight have the "never drop frames" option but like it tells you in the info, it eliminates the micro-stuttering **BUT ALSO** increases latency. That is even worse than micro-stuttering because it makes most games unplayable._

**Comment by JasonS7notG5** [comment]
@geneccx did I hurt your feelings or why did you downvote me? If you think micro stutters are fixed you are wrong. Just have a look at the most commented thread:

https://github.com/moonlight-stream/moonlight-android/issues/349

**Comment by saiotek** [comment]
The never drop frames option reduces the micro stuttering, but for example in GTA5 if you look on a street with many driving cars you can see minor stuttering... on my tv everything is smooth.

On android 5 the micro stuttering is no problem? So if i downgrade my z3 tablet from 6 to 5.1 it should be smooth? 

Input lag is not a problem i use the controller with windows not with moonlight.

**Comment by saiotek** [comment]
My S8 (Exynos) has no stuttering with the fix in GTA 5, on my Z3 Tablet (6.0.1) with the fix there's minor stuttering left. Z1 Xperia phone with 5.1.1 and without the fix no stuttering...

**Comment by jamaalsawyerd** [comment]
I have a Nexus 7 2013 with Android 7 based LineageOS 14.1 

Despite 12ms latency on 720p 60fps there is micro-stuttering that occurs.

With the "never drop frames" option on it is super smooth but the latency doubles to 24ms and a very slight input lag is detectable.

It hurts to be so close to streaming Titanfall 2 in bed. Hopefully there is a fix at some point! Would be awesome since they don't make shield portable or k1 anymore.

**Comment by saiotek** [comment]
After i switched back to 5.1.1 on my z3 tablet the big micro stuttering is gone. But like before with 6.0.1 and the fix theres another type of stuttering.

If i set the fps in riva tunner to 59 i have the same stuttering on my tv. I used the app maxfps on some of my devices and on all of them i get 60 fps, only my z3 tablet shows 59 fps...

Is it possible to set the stream to 1080p59?
Or is there amything i can do that the tablet and the stream are both in sync?
