### ISSUE TITLE
Not Finding Host PC

### ISSUE THREAD

**Issue by tpzillmer** [moonlight-stream/moonlight-android#494]
I cannot find the host PC on Moonlight iOS. 

Gamestream is enabled, they are on the same network (phone connected via 5ghz wifi and host PC connected via ethernet). 

Any idea? I have researched similar previous issues. People mention having nvstreamer.exe running, which I don't see, but I was told that it is under container now. When I try to run it myself, I get an error regarding missing .dll's.

**Comment by boxintense** [comment]
I can confirm this problem as well, although I've just updated my driver to 388.59 and still cannot connect. I can confirm that HELO package to all required ports are accepted, and ICMP between the android devices and my windows 10 pro 64 bit 1709 PC are fine. PC is connected via ethernet. Android is 802.11n 5 GHz.

Have done everything as instructed in the Troubleshooting section, including rebooting PC and Android device, re-installation of GeForce Experience. To be safe, I've also tried adding legacy TCP ports and performing HELO check on them, still to no avail.

Any advise is greatly appreciated.

**Comment by Atemu** [comment]
Can anyone test if it works with earlier deiver and GFE versions?

**Comment by tpzillmer** [comment]
I tested an earlier driver but not earlier GFE version

**Comment by mkopera2** [comment]
I had this issue as well and then I tried using [IPv6](https://github.com/moonlight-stream/moonlight-docs/wiki/Setup-Guide#ipv6-certain-isps-only) instead of IPv4 and I was able to connect and stream flawlessly.

**Comment by tpzillmer** [comment]
Unfortunately I don't have IPv6

**Comment by Atemu** [comment]
This only applies for connecting outside of the network, the problem is that it doesn't work even when you're inside the same network and IPV6 doesn't help here unfortunately.
