### ISSUE TITLE
Shield Tv can't find PC, other Devices like Smartphone connecting to PC

### ISSUE THREAD

**Issue by Koray22** [moonlight-stream/moonlight-android#495]
Its really strange but Moonlight on my Nvidia Shield Tv can't find my PC. But my Smartphone recognizes my PC immediently. 

Any help :(?

**Comment by Koray22** [comment]
Why nobody can help me on that issue? If you guys need more information, i'll give you.

**Comment by cgutman** [comment]
Are both devices connected via WiFi?

**Comment by Koray22** [comment]
The Host PC is connected via Ethernet Cable, Nvidia Shield TV is connected via Wi-Fi, but i also tested it with Ethernet, same result :/

My OnePlus 3 with Android Oreo finds my PC easily, and non-android Devices also.

All drivers and Software are up to date.

**Comment by Koray22** [comment]
Btw both devices are in the same home network

**Comment by cgutman** [comment]
Can you add the PC by using the Add PC button in Moonlight and typing the IP address of your PC?

**Comment by Koray22** [comment]
No, it says "Unable to connect to the specified computer. Make sure the required ports are allowed through the firewall."

**Comment by Koray22** [comment]
Alright, I See no one can help me.

**Comment by Xiller** [comment]
*sry 4 my engl*

you say: on your onePlus 3 with moonlight it works?  "find my PC" -> some people think with "find" in network and not with moonlight.

If Moonlight on your phone works and with fireTV not, you should reinstall it. And maybe turn off your firewall on pc, maybe you blocked onetime (without intension) the fireTV. Aaand if nothing work, you should install Kodi or something else and try to connect to your PC. Because i think it is not a moonlight problem.

hope some hint help you

**Comment by Koray22** [comment]
Dude, I'm using a Nvidia Shield TV 🙄.

The Firewall is not the issue, my Laptop can connect to my Host PC via Moonlight and stream it perfectly. There is an issue with my Shield TV.

I see there are no more good tips and ideas left, so guys can close this issue.

**Comment by Xiller** [comment]
Oops sorry. i was in FireTV mode, but you can read my text (and hints) with ShieldTV instead of firetv. But as you self say: "There is an issue with my Shield TV" not Moonlight. 
Better help in Nvidia Forum ;) good luck!

**Comment by cgutman** [comment]
Yeah, this issue is highly peculiar. Are you sure the Shield is not somehow on a different network segment than the PC or other devices that can stream?

**Comment by Koray22** [comment]
Yeah I'm pretty sure. Anyway, i contacted the Nvidia Customer Care, hope they can help me.
