### ISSUE TITLE
Resolution not matching correctly. 

### ISSUE THREAD

**Issue by slamanna212** [moonlight-stream/moonlight-android#496]
Setup: Windows 10 Pro PC with GTX 760 streaming to a Mi Box. PC resolution is 1600 x 900 and the TV's Resolution is 1920 x 1080

**How it used to work and how i want it to work:** I would start either Steam or the game itself in moonlight, My desktop resolution would switch to 1920 x 1080. It would of course look weird on my desktop but the entire display was shown on my TV in full 1080P HD. 

**Whats happening right now:** If i launch steam, it shows in 1600 x 900 and says this in the resolution settings:
![Steam Display settings](https://i.imgur.com/nFd8CsZ.png)

If i launch the game through steam or through moonlight directly, the game is in 1080P but the right and bottom edges are severely cut off. It looks like its still showing at 1600 x 900 and just not showing the extra pixels of 1080P

Geforce Experence, Nvidia Drivers, Windows 10, and Moonlight are all updated to their newest releases. I cant pinpoint the exact time things went wrong, but everything worked as expected a week ago. The game I have been trying is Prey (2017). 

I also tried Rocket League, and it wouldnt even start if i was streaming Steam. I get this error:

![rocketleagueerror](https://i.imgur.com/9OIKzqj.png)

**Comment by Atemu** [comment]
Try creating a 1080p 60Hz custom resolution for your monitor that scales down to the native res
