### ISSUE TITLE
Any way to make moonlight autoconnect to last server connected and start big picture mode steam on startup or through tasker?

### ISSUE THREAD

**Issue by vrokolos** [moonlight-stream/moonlight-android#498]

**Comment by thw0rted** [comment]
A simpler suggestion might be to allow the creation of direct-launch shortcuts on the home screen.  Something like, connect to a server, long-press one game (or in this case, Steam), and get a menu option to "add to home screen".  Then, touching the shortcut would launch Moonlight, connect to the relevant server, and run the specified application.

Would that be practical, @cgutman ?  I've only done a tiny bit of Android development but I don't *think* it would be a ton of work.

**Comment by vrokolos** [comment]
I think there is something like that in the code but I can't do shortcuts on my android TV :(
