### ISSUE TITLE
HEVC decoding with X96 mini ( Amlogic )

### ISSUE THREAD

**Issue by MrMybal** [moonlight-stream/moonlight-android#500]
Hello, I use moonlight (root) 5.6.1 with a mini x96 (s905w amlogic with HEVC decode) under android 7.1.2, but impossible to use the codec h265.
Moonlight always uses h264 with a latency of over 100ms.
Is it possible to force the use of h265 (I test all the possible configuration in the application)

Host: win 10, 660ti gtx, GFE 3.11.0.73, GFG 388.71, ethernet connection
Client: x96 mini, s905w, CPU: ARM Cortex-A53, GPU: Mali-450MP, Amlogic \ HEVC driver on aida64 ( not found h265 Google \ Driver)

**Comment by cgutman** [comment]
Did you set H.265 to "Always use H.265" in Moonlight settings?

**Comment by MrMybal** [comment]
I tested with all available options, it still uses h264.
I am going to retry a further test, but I would like to know if there is an .ini file to force the use of HEVC?

**Comment by MrMybal** [comment]
I tested the new version of moonlight 5.6.2, but it still does not work, it only uses h264 (test with 720p60 and 1080p60).
Here is my HEVC driver,

OMV.amlogic.hevc.decoder.awesome

I would like to know if there is a searchable log in the android version?

**Comment by JasonS7notG5** [comment]
Your Mini X96 can decode HEVC but your GTX 660 Ti cant encode in HEVC, only in H.264. Thats why it doesnt work.

**Comment by MrMybal** [comment]
ok thank you.

do you have an array of graphics cards and their encoding codecs?

**Comment by JasonS7notG5** [comment]
GTX 950, 960, 970, 980, 980 Ti, Titan X
GTX 1050, 1050 Ti, 1060, 1070, 1080, 1080 Ti, Titan X (Pascal), Titan Xp
