### ISSUE TITLE
version 5.6.2 issues with Shield TV 2017

### ISSUE THREAD

**Issue by Michoko92** [moonlight-stream/moonlight-android#501]
Hi,

First, let me thank you for this wonderful app! Moonlight is just awesome!

I usually use the native NVidia streaming solution on my Shield TV, but for some reason, I had some micro-stuttering with it and Nier Automata. With Moonlight, this same stuttering is almost non-existent, so I use it to play this great game.

My setup:
- Streaming over 5GHz Wifi
- 30 MBps bitrate
- Never drop frames activated (else I get horrible stuttering)

However, yesterday I upgraded to the latest version (5.6.2), and now the streaming has some big hiccups (like if at some points, the streaming was almost freezing and was trying to catch up). I tried to reduce the bitrate to 20 MBps, but it still happens. I reverted back to 5.6.1, and everything works fine again. The frame decoding latency also went from the usual 5ms to 10+ms.

Just wanted to report this. Hopefully it will be useful. Cheers (and happy new year ;)) !

**Comment by cgutman** [comment]
This should be fixed by ffb35b2cdd9f8cc3524b9d41a8ea3a1c54e11a54 in Moonlight Android v5.6.3. Let me know if you still have the issue.

**Comment by Michoko92** [comment]
It seems to be fixed indeed, thank you very much Cameron! 🥇

**Comment by Michoko92** [comment]
Oddly enough 5.6.5 seems to have reintroduced this issue. Sorry :(
