### ISSUE TITLE
no moonlight app (ios, android tv) can find my pc

### ISSUE THREAD

**Issue by tunikb** [moonlight-stream/moonlight-android#502]
I have a gtx1070 in my pc, geforce experience up to date, game stream enabled in the shield tab, forwarded all the ports necessary, read through a million forum posts with similar issues and am stranded and completely exhausted. 

is it still an issue i can't find the nvidia streamer service in my processes and or services.msc?
do i need to enable experimental updates for gfe? because i can't, if i do, it just circles until infinity.

is there anything else i can do, PLEASE?! i so desperately want to use this beautiful piece of software.

**Comment by sevansup** [comment]
Seems to be an issue caused by Fall Creators Update or something. Basically, executables aren't being properly added to the Windows Firewall. I was able to fix this by following a user's advice on the Nvidia forums:

![image](https://user-images.githubusercontent.com/9912581/34503300-c78e6d2a-efd4-11e7-95f6-b8596667e1a3.png)

**Comment by tunikb** [comment]
I tried even with a completely disabled firewall. So I guess, that won't be the problem itself. Thank you for the advice anyway 👍 

I have tried for another couple of hours, but I just reached a dead end. very sad, since I was looking forward to this a lot, after the steam link out of the box experience was terrible for me. anyway, It's just not working properly yet.

**Comment by tunikb** [comment]
i just continued doing it, because i wanted it so bad and for no apparent reason at some point it just worked. not gonna jinx it by trying to find out why... :) thanks anyway!
