### ISSUE TITLE
FireTV client is corrupt, cannot install. 

### ISSUE THREAD

**Issue by nwpappas** [moonlight-stream/moonlight-android#503]
When trying to install the client on the latest FireTV I get the following error:

Install Failure
Moonlight Gaming Streaming has been corrupted and cannot be installed.

I've tried rebooting the FireTV and attempted the install several more times. All with the same results.

**Comment by cgutman** [comment]
Thanks, this should be fixed by 7fafb8e0ff31962e5be92075daa2cc4d51d8a838 in v5.6.3
