### ISSUE TITLE
Latency improve for note 8 (probably also others similar samsung monsters)

### ISSUE THREAD

**Issue by Mrt-68** [moonlight-stream/moonlight-android#504]
Hello all,

I wasn't know if this is an issue or not but I just wanted to share with you a trick that can improve your stream performance on gear vr compatible devices.

If you enable the developper mode in your gear vr service, you have the low persistance mod which is activated. This low persistance mod improved my latency on 1080p 60fps from 9ms to 3ms. Additionally for info, 4k 60fps setting is gone from 20ms to 9ms (I am using usb thethering and sometime ac wifi 5ghz). Which is better than the newest Nvidia shield who have 10ms... 

Hope this will help you.

**Comment by JasonS7notG5** [comment]
Tested this out on my S7 edge (Exynos variant) and it didnt made any difference. I tested it with WiFi 5GHz and H.264 codec. The screen flickers when turning on developer mode in Gear VR Service.

**Comment by Mrt-68** [comment]
I tested with and without developper mode for check the latency numbers but nothing change, I wasn't really right about this latency improve methode.

For explain it better and in the right way, the latency measurement stay the same (hardware decoding measurements from pc to image) but this high persistance mode for eliminate the flickering gives some delay between the screen and our eyes. So activating the low persistance mode with developper mode improves the smoothness of the image from screen and eyes. Exactly the same aim of gear vr when it activates automatically.

I was trying lot of thing like using:
An edited apk of moonlight for matching the refresh rate of pc screen, moonlight app in resolution refresh rate to the phone screen refresh rate.. (Apk was downloaded from one of the issues here in this forum)
Also I was trying to jump between usb thethering drivers (olds and news), wifi ac 5ghz channels.. 
And lastly I was trying the performance mode and some other modes on my phone..

So I think I had a combination of an adapted setting which improved this much my latency numbers as mentioned above in my other comment, which is I think I already lost. I should give it a new try and keep a note of the settings to see what is really improving the latency.
