### ISSUE TITLE
Failed to start RTSP Handshake.

### ISSUE THREAD

**Issue by Killallways** [moonlight-stream/moonlight-android#508]
I have looked for a while for this and i havent found a solution, i have tried to connect from same wifi and data and it has not worked, i port fowarded and i closed razor synapse to see if it would fix it and it didnt, i tried to connect a Samsung S7 and an IPhone 6s and no luck, anyone have an idea to get this fixed?

**Comment by qualityghost** [comment]
@Killallways Have you installed the latest nvidia drivers 390.65? If yes then downgrade them to previous version 388.71. I'm not sure if it is required but you can also downgrade your GeForce Experience to the previous version. Remember to check option "Perform clean install" during new installation.

**Comment by Killallways** [comment]
@qualityghost I just got back home and tried it and it is working fine, i do not know why it wasnt working but at least it is now, although i still cant get the streaming over the internet to work, i have port fowarded and used the commands for firewall to let the ports through.

**Comment by cgutman** [comment]
If you're using GeForce Experience v3.12, make sure you have the Moonlight v5.6.3 update installed which fixes streaming from the new GFE version.

**Comment by qualityghost** [comment]
I confirm. Last version of Moonlight v5.6.3 and GFE v3.12 connect without issue with "RTSP Handshake".

**Comment by Killallways** [comment]
Just updated it, my router stopped working for a few days and it just came back online. trying now

**Comment by Tapwated** [comment]
I'm having this same problem but exclusively with the SBS version of Moonlight. Latest patch of the app works fine, but whenever I try using the Side-By-Side version to play games in VR I get stuck at the handshake, Is this any relevant to the discussion? Also, is this a problem on my end or just a compatibility issue between the SDS version and GFE v3.12?

**Comment by cgutman** [comment]
@Tapwated It sounds like that port needs to be updated with the changes to support GFE 3.12.
