### ISSUE TITLE
Moonlight crashes on 5GHz network While Gamestream works fine

### ISSUE THREAD

**Issue by ronferri** [moonlight-stream/moonlight-android#511]
Host: Windows 10 Laptop with GTX1070 and latest Geforce Experience
Client: Nvidia Shield TV with Moonlight 5.6.3
Problem: On 5GHz wireless network, Moonlight starts the selected app from the list, starts RTSP, but fails to stream anything on the TV and crashes with "connection terminated" few seconds later. Moonlight still works fine on 2.4GHz network but at poor quality. 5GHz had been working perfectly for many weeks.

Nvidia Gamestream still works fine on both network bands.

**Comment by robbiered** [comment]
Do you happen to have a Chromecast? They had an issues DDoSing your router.  My wifi went to crap because of it.

**Comment by ronferri** [comment]
Thanks. I dont have the chromecast hardware but i do have nvidia shield TV which might have chromecast functionality. I will unplug it and try moonlight again on my phone.
