### ISSUE TITLE
Android 6. Latency lags. Only 1mbps works well

### ISSUE THREAD

**Issue by olegkhorev** [moonlight-stream/moonlight-android#512]
Hello,

I have 3 devices - Android 4, 5 and 6. Only 4 works well on 10mbps, but it's very old tablet with bad display which I want to replace. I bought today Android 6 device with good display but it works only in 1mbps or I see bad lags if higher.

Wondering what it can be. I checked speed and it's over 15mbps from device to Wi-Fi router.

So if 4th Android works well - I have no idea why 6th with better device does not work good.

Regards,
Oleg

**Comment by olegkhorev** [comment]
I tried without bluetooth. I tried near to Wi-Fi router. I tried without GPS(location).

My PC connected through LAN to Wi-Fi.

And again - Android 4.x on low power tablet works fine.

**Comment by olegkhorev** [comment]
I think Wi-Fi connection is slow. I tried YouTube video - and it's slow too. Sorry it's new tablet - so was not able to check all.

**Comment by olegkhorev** [comment]
Hm. I found how to import wi-fi. But Moonlight still lags the same. I see video from PC very clear. So streaming is good on 10mbps. But using gamepad (iPega) - it is lagging.

**Comment by JasonS7notG5** [comment]
Do you have "never drop frames" option enabled? If yes disable it and then test. You also may want to look at this [thread ](https://github.com/moonlight-stream/moonlight-android/issues/349#issuecomment-356144921)here,

**Comment by olegkhorev** [comment]
"Never drop frames" option is disabled by default - I was not enabling it. I will look on your topic tomorrow(it's night here).

**Comment by olegkhorev** [comment]
I have tried that. I think video was enough fine and before. But when I am using Gamepad iPega - it lags. I press button and it takes a second to respond. It is good when I am in Moonlight games list menu. But not in game. I see video lags just a little but it should be ok - but not for gamepad.

**Comment by olegkhorev** [comment]
I bought another cheap Android 4 device - seems it's not Android 4. Not sure, may be device power.

Let's just see if anyone can help.

**Comment by cgutman** [comment]
Do all of these devices have 5GHz WiFi? Many low cost devices don't have 5GHz WiFi and that causes interference issues in crowded areas.

**Comment by olegkhorev** [comment]
I am on Android 4 old device, about 2 years already  and with bad device - it has only 2.4Hz - but it works well.

So no of my devices has 5Hz. But thank you for advice. I also saw it's a better Wi-Fi with 5Hz. Strange just I connect even iPhone with 2.4hz and all is fine. And some other devices all are on 2.4Hz - I am not using iPhone for moonlight of course, it's just too small for it - just telling you.

I think it's device power, not Wi-Fi as I use check internet speed for example - it says 15-20Mbps. But even on 5Mbps on Moonlight lags.

**Comment by olegkhorev** [comment]
Also I think it is not 5Ghz issue - because even near with WiFi router - it works bad.
