### ISSUE TITLE
Any idea what could block Internet streaming on a network?

### ISSUE THREAD

**Issue by Slayer418** [moonlight-stream/moonlight-android#514]
I'm currently trying to start a streaming session over the internet from my office to my home PC. My setup has been in place for years and it definitely is working (just tested again on LTE) but on my office network, it 
 doesn't work. My PC with all its games are showing, the pairing worked, but whenever I try to launch something I get "Failed to start RTSP".

Any idea what is happening here (Windows Firewall is disabled btw)?

EDIT: I don't know if teamviewer uses RTSP but it is working.

**Comment by Slayer418** [comment]
I guess RTSP port is being blocked at some point on the network. Port 80 is open, would it be possible to change the port used by Moonlight for RTSP?

**Comment by cgutman** [comment]
This sounds like it's possibly an RTSP port forwarding issue related to GeForce Experience v3.12. Can you double check that you have TCP 48010 forwarded correctly (UDP 48010 was used by GFE v3.11 and earlier)?

**Comment by Slayer418** [comment]
My 48010 has been set to both UPD and TCP since I don't know when. My stream is working perfectly on my mobile data so the issue isn't from my home side.

**Comment by cgutman** [comment]
That's pretty peculiar. I would expect that any network that allows TCP 47989 and TCP 47984 (required for detecting the PC is online and pairing) to also allow TCP 48010 used by RTSP.

**Comment by Slayer418** [comment]
Hmm that's really weird indeed, could the proxy on the network detect whenever a port is used for RTSP stream and block it?

**Comment by cgutman** [comment]
If your company has a firewall, I guess it could inspect that traffic and discard it. You could try downgrading your PC to GFE v3.11 and see if that allows it to work again (since RTSP is done over UDP on that version).

**Comment by Slayer418** [comment]
Why did they change for TCP, isn't UPD better for streaming?

**Comment by cgutman** [comment]
RTSP is only done in the beginning to negotiate the stream parameters, so it's not latency-sensitive. The video, audio, and input data is all over UDP.

**Comment by Slayer418** [comment]
Oh I see, well thanks for replying. I guess i'm screwed.

**Comment by Slayer418** [comment]
I want to add that if I start the stream using mobile data and switch to Office WIFI without tabbing out of moonlight (without interupting the stream) the image freeze but it doesn't crash/disconnect.

**Comment by Slayer418** [comment]
Back at it again, my issue is still not fixed and I went into some tracing with Wireshark. UDP seems to not be blocked or atleast not for TeamViewer. I have found that no UDP packets is being traced by Wireshark when trying to use Moonlight.  Would it be possible to use TeamViewer ports  (since those would appear to be unfiltered) with Moonlight?

**Comment by Slayer418** [comment]
Found the name of what is blocking, WatchGuard HTTP Proxy which filter rtsp:// link. Now gotta find a solution

**Comment by Slayer418** [comment]
> I want to add that if I start the stream using mobile data and switch to Office WIFI without tabbing out of moonlight (without interupting the stream) the image freeze but it doesn't crash/disconnect.

I found out that when I do this, Input is still working as I still control the mouse and keyboard but have no audio and video. Wireshark shows a continuous stream of UDP packets still being sent by NvStreamer to my mobile internet IP (Eventho I'm on the WIFI connection). What I'd need is a way to inform NvStreamer that there is a new IP to use  without interupting the stream and having to go throught another RTSP handshake or, in a perfect world, a way to skip the RTSP handshake, forcing the stream to use preset parameters or Idk.
