### ISSUE TITLE
error 524 and 599

### ISSUE THREAD

**Issue by muffinmannameistaken** [moonlight-stream/moonlight-android#518]
I'm getting this error 524 "cannot resume game that hasn't been started"?  and I get a another error when trying to close the current running game error 599 "this session was not started by this device...." even tho I started the game with the same and only device. I'm seeing these errors after I put my pc into sleep mode then waking it up.

**Comment by cgutman** [comment]
This is known since GFE 3.11 if you launch a stream but don't log into the PC, then disconnect and try to reconnect.

**Comment by muffinmannameistaken** [comment]
kk, i did also notice it does happen to when i switch audio outputs like wire speakers to Bluetooth headphones (connected to the laptop) i can get moonlight to start back up again but i have to manually stop the process inside task-manager.
