### ISSUE TITLE
1440p support

### ISSUE THREAD

**Issue by apollon01** [moonlight-stream/moonlight-android#519]
Hello Moonlight team,

I am using your application and it is truly great :-) Thank you.

Is supporting 1440p something that you are considering for Moonlight?

I was searching a bit around and found that some time ago there were talks about it for Android and now Chrome supports it. Just curious since there is a good wealth of 1440p smartphones. Streaming at 1080p does not use fully the HW potential and at 4k is not efficient (and a bit too much to handle too).

I would appreciate your feedback on this.
Thank you.
Kind regards,

Milan

**Comment by muffinmannameistaken** [comment]
https://forum.xda-developers.com/nvidia-shield/general/moonlight-custom-resolutions-t3428451

**Comment by apollon01** [comment]
Thanks, I was not aware of that.

Milan
