### ISSUE TITLE
Not connecting

### ISSUE THREAD

**Issue by gb2111** [moonlight-stream/moonlight-android#520]
Hi,
I am not able to connect either auto or manually form android to pc.
tried:
- change firewall rules
- disable firewall
- can't find NVIDIA Streaming Service which supposed to be I think.

PC - NVIDIA 1070, Android on Samsung S7.

Any help to troubleshoot appreciated.
Greg

**Comment by HarleyVR** [comment]
Hi,
Try to write your IP Address :
> Open cmd and write ipconfig
> Take the ipv4 adress IP
> Write it in Moonlight when you try to add a new computer
