### ISSUE TITLE
TalesRunner - Unable to click

### ISSUE THREAD

**Issue by U-siro** [moonlight-stream/moonlight-android#522]
It works at all but I can't click anything on game.
So I manually suspend xtrap.xt then works but It's not easy, Please fix it!

**Comment by U-siro** [comment]
.

**Comment by U-siro** [comment]
.

**Comment by cgutman** [comment]
You should report this on Nvidia's GameStream forum if it still happens on the latest GeForce Experience version. This isn't a bug in Moonlight itself.

**Comment by U-siro** [comment]
Thanks!
