### ISSUE TITLE
USB over IP integration for "native" support for Steam Controller, racing wheels, flight sticks etc

### ISSUE THREAD

**Issue by JasonS7notG5** [moonlight-stream/moonlight-android#524]
Especially users with a Steam Controller would profit from this (streaming via internet). The Steam Controller is superior to the other XInput / Xbox controllers. Other devices like racing wheels and flight sticks would also work but I guess not many would use these with smartphones, maybe on tablets. You already have an app called "[USB/IP Server](https://play.google.com/store/apps/details?id=org.cgutman.usbipserverforandroid&hl=de)". I know you guys want to keep Moonlight as clean as possible with GameStream only but I think a direct implementation of this inside Moonlight would really help many.

Edit: It would even give non Android 8.0+ users keyboard and mouse functionality without root!

**Comment by BETEP-ok** [comment]
Thumbs up here

Highly demanded feature for all platforms: rpi/Android/Windows 

That’s the whole point of this app- to have a powerful gaming PC to be loud somewhere in the attic (or in the basement in my case) and use my beloved controller wherever I want.

**Comment by samgalactic2** [comment]
And this would presumably fix the issue of keyboard input being interpreted as android, and enable non-standard button presses?

**Comment by OgierM** [comment]
Yup, would be a very nice feature

**Comment by eslam-allam** [comment]
can we possibly revive this issue? It would be a pretty cool feature that would enable so many controllers to be used. E.g. my 8bitdo ultimate 2 controller shows as an xbox one controller which makes all the extra buttons unusable.
