### ISSUE TITLE
Screen refresh rate and bandwidth

### ISSUE THREAD

**Issue by Mbit555** [moonlight-stream/moonlight-android#525]
Hello!
Is it possible to configure the application for streaming for phones with a refresh rate of 90 / 120Hz? It is also interested in the transmission speed, by default it is limited to 100 megabit, is it possible to stream with the setting of this parameter in 200/300 megabit? Or is it all the limitations of nvidia and in your application it does not change?

**Comment by JoeJoeyMa** [comment]
I guess only 100 megabit,Because the application same nvidia,You can download the app from nvidia.If you need fast speed,The final solution is wired connection
