### ISSUE TITLE
New user, unable to connect client

### ISSUE THREAD

**Issue by Verbanderbog** [moonlight-stream/moonlight-android#527]
Hi everyone, having a lot of trouble getting started.  Moonlight does not automatically find my PC and manually adding returns a pop-up which says "Unable to connect to the specified computer. Make sure the required ports are allowed through the firewall." 

First, here are my specs.  The client is on my Note 8 which is not jailbroken.  The phone is connected to my network via 5ghz wifi. My PC is also connected via 5ghz wifi, running Win10, and has a 980ti.  I'm currently running GFE v3.12.0.84 with driver v390.77 (which was updated in the process of troubleshooting; the previous version was 388.something). I do not have additional virus detecting software or firewall software

Here's what I've done to try to fix the problem and in roughly this order:

- Ensured Gamestream is on in GFE
- Manually entered my PC's local IP (which has been reserved on my router to 10.0.0.253)
- Used the commands found in the setup guide to add an exception for Gamestream to the firewall.  These were run with admin privileges and returned "Ok." when run.
- Completely disabled my firewall
- Updated Nvidia drivers
- Disconnected my client/phone from the network, port forwarding and attempting to connect via my external IP
- Uninstalled Razer Synapse and Razer Kraken software (APO Helper)
- Reinstalled Moonlight
- Rebooted both my phone and PC

**Comment by cgutman** [comment]
Do you get a page of text when you go to http://127.0.0.1:47989/serverinfo on your GameStream PC?

**Comment by Verbanderbog** [comment]
I do not.

**Comment by cgutman** [comment]
Interesting, so that means GameStream isn't properly running on your PC.

Can you try doing a clean uninstall and reinstall of the latest GeForce Experience?

**Comment by Verbanderbog** [comment]
This was indeed the correct solution.
