### ISSUE TITLE
Controller Emulation

### ISSUE THREAD

**Issue by genmatrix** [moonlight-stream/moonlight-android#529]
I probably picked a bad title for this but I've noticed that Destiny 2 it prompts GFE to "install" an emulated controller only while playing Destiny 2. Is there any way to have Moonlight do this for all games? I have a very specific use case and it's super exciting but it only works if you have Destiny 2 installed.

**Comment by genmatrix** [comment]
@cgutman Would you know anything about what I am describing? 

I want to say GFE creates an XInput device. A cool side effect is that, when launching Destiny 2, the Xbox App recognizes input from this device when steaming. Essentially letting me play my Xbox One from anywhere as well.

**Comment by cgutman** [comment]
Yes, I know about this. It's driven by GFE's app profiles that specify some games get a "real" controller. I'm not sure how to force it on for games that don't official have profiles that dictate it.

**Comment by genmatrix** [comment]
Ah, I see, I appreciate the insight! If you ever do run into a way to spoof it for other games, that'd be sweet. Closing this issue.
