### ISSUE TITLE
Samsung S7,S8,Note8 SMB/CIFS Super slow

### ISSUE THREAD

**Issue by JoeJoeyMa** [moonlight-stream/moonlight-android#530]
Is there any improvement now?I'm trying to download a few app use SMB2.0 

At present is to be used in GeForce Experienced GameStream, 5G WIFI is extremely slow, screen projection 1080P/60ghz will appear Caton, don't know what the situation . Have anyone found out that the problem has been solved?
https://us.community.samsung.com/t5/Galaxy-S8-Questions-and-Answers/S8-broken-SMB-over-WIFI-with-extremely-slow-speeds/td-p/102969

https://us.community.samsung.com/t5/Galaxy-S-Phones/S7-Edge-Nougat-update-broke-SMB-CIFS-streaming/td-p/78036

https://us.community.samsung.com/t5/Galaxy-Note-8-Questions-and/Note-8-SMB-slow-FTP-and-USB-speeds-and-Dex-questions-Disgusting/td-p/177680

**Comment by cgutman** [comment]
This doesn't seem related to Moonlight.
