### ISSUE TITLE
Xbox One Controller button mapping problem

### ISSUE THREAD

**Issue by muffinmannameistaken** [moonlight-stream/moonlight-android#531]
hay I got a xbox one controller for my tablet and i notice that some games the buttons are mix up and some others the sticks are not working properly, looking left would all so look down and the opposite if looking right. It seem to only effect moonlight not my laptop/destop. is there a fix for this ?

**Comment by cgutman** [comment]
Is it connected via USB or Bluetooth?

**Comment by muffinmannameistaken** [comment]
Both and it also effects the on screen touch controller. I also tried on 2 different computers still the same problem.

**Comment by cgutman** [comment]
What games have you tried and what version of GeForce Experience are you running?

**Comment by muffinmannameistaken** [comment]
gta 5 the "A" button sprints and changes the camera, Space Engineers and any of the Tales series games the look stick seem to be broken(as stated above).

**Comment by muffinmannameistaken** [comment]
I'm still having same problem with h.265 not working on my phone i tried forcing it on but i still get the same error "h.265 encoder not found".

**Comment by cgutman** [comment]
I tested GTA V using the on-screen controls in Moonlight and A does just what it should - it sprints.

If the controls are correct in any game or Steam, it's an issue with the software on your machine (possibly Steam controller mapping) interfering with GameStream or simply a game compatibility issue with GameStream that Nvidia will need to fix.

I commented on the H.265 issue regarding your issue.
