### ISSUE TITLE
Moonlight - VR 

### ISSUE THREAD

**Issue by HarleyVR** [moonlight-stream/moonlight-android#533]
Hello,

I use tridef to play 3D games on my PC. Then thanks to Moonlight, I put my VR headset on my Nexus 5 to play with.

However, for better comfort, I ask you to improve Moonlight for:
1 - When you move your head, it moves the mouse on the screen
2 - Ability to mute the sound of the phone
3 - Change the display of the screen so that it is adaptable to VR lenses.

Thanks and good luck :)

**Comment by Flova** [comment]
You are looking fir Trinus VR ; )

**Comment by HarleyVR** [comment]
Yes Trinus VR is a very good software. With that we can use head to move mouse but lens didn't work when we use Moonlight with it :( 
So when we play at video-game with it, we can't see all the game's screen (HUD for example).

**Comment by HarleyVR** [comment]
It seems that monstrobishi have already done something like that : 
https://github.com/monstrobishi/moonlight-android/releases/tag/v1.1

But it's doesn't work anymore (issue with port due to the version)
