### ISSUE TITLE
Lag peaks on each resolution setting

### ISSUE THREAD

**Issue by Oxford89** [moonlight-stream/moonlight-android#534]
Hello everyone! 

I've been using Moonlight (Root version) for a couple of days now. It was actually one reason for me to upgrade my internet and buy a tablet. 

- Internet connection (Fibre): Max 65 Mbps down, 23 Mbps up. 
- Tablet: Samsung Galaxy Tab A6 (2016), Nougat, Wifi Dual Band a/c
- PC GPU: Nvidia GTX 1050 (all drivers are up to date)

My PC is connected via ethernet and my tablet via Wifi (5 Ghz) and I get speeds of about 35 Mbps down and 20 Mbps up on my tablet. 

However - I can change the bitrate as low as I want and also switch between also resolution settings @Moonlight-stream and I always get the same sort of lag. Bluetooth is disabed, Location as well. A DS4 controller is connected via OTG. 

The lags I'm getting are normally not caused by lots of action on my screen - I can just stand around, doing nothing and get these massive lags randomly, which last for about 5-10 seconds. This happens every 5-10 minutes. 

I was wondering if anyone else had a similar problem or if there's any fix that might work out? Or is my internet speed not enough?

**Comment by cgutman** [comment]
Does the lag still occur when streaming 30 FPS?

Does the image freeze or stutter or just gain delay while still remaining smooth?

Does this older version make the problem go away? https://github.com/moonlight-stream/moonlight-android/releases/tag/v5.6.4

**Comment by Oxford89** [comment]
Hey cgutman,

I just tried the rooted version of the old app. The lag peaks didn't go away but I had the feeling that they happend less often. Even on 1080p@30FPS (I tried different resolutions again). 

It might be worth mentioning, that the controls on my PC won't respond for a second as well. 

So a lag normally looks like this:
- Image gets very slow 
- Audio cuts off randomly, sometimes I hear some crackle 
- While the image on the tablet speeds up to sync with the PC, the controls on the PC won't respond anymore and are working with the last input (e.g. character keeps running on PC, even if I don't do anything. This only happens, while the tablet is trying to get in sync again).

If you have any other good idea - let me know! Anyway - thanks again for your help so far!

Ox

**Comment by Oxford89** [comment]
**FIXED**

The speed of my connection via ethernet was always very strong but I used a Powerline to get this done. I found a long ethernet cable and tried to connect it directly to my router which fixed the random lags. 

Thanks again for your help! Hope some else finds this helpful at some point.

Ox
