### ISSUE TITLE
 The game starts but does not show

### ISSUE THREAD

**Issue by brunotjsp** [moonlight-stream/moonlight-android#535]
Hello, I'm sorry if my English is not clear, I'm using a translator.

I used Moonlight on Raspberry and it worked fine. But it's been around for a month that it does not work anymore.

I start the game by rasp, it opens on the pc. but on my tv nothing appears. I formatted the Rasp I changed from recalbox to batocera and it did not work.

I also tried using the previous drive of the video card.

thank you

**Comment by brunotjsp** [comment]
Somebody?

**Comment by cgutman** [comment]
This bug tracker is for Moonlight for Android. You should file any Moonlight Embedded bugs on that project page: https://github.com/irtimmer/moonlight-embedded
