### ISSUE TITLE
GFE error: Nvstreamer initalization failed as encoder dll load failed (Error code: 566)

### ISSUE THREAD

**Issue by zansbang** [moonlight-stream/moonlight-android#539]
when i start game then show this error:
GFE error: Nvstreamer initalization failed as encoder dll load failed (Error code: 566) .

below is C:\ProgramData\NVIDIA Corporation\NvStream log:

#1(I)[2018-02-25 15:18:27,396]=23:18:27={00000950}<NvStreamer>       Custom Ctrl+C handler successfully set.
#2(D)[2018-02-25 15:18:27,396]=23:18:27={00000950}<Utils>            The CPU supports AVX (GetEnabledXStateFeatures)
#3(D)[2018-02-25 15:18:27,396]=23:18:27={00000950}<Utils>            No need to apply the _set_FMA3_enable(0) patch
#4(I)[2018-02-25 15:18:27,396]=23:18:27={00000950}<NvStreamer>       PID 12044
#5(I)[2018-02-25 15:18:27,396]=23:18:27={00000950}<NvStreamer>       Streaming Process ID: 0
#6(D)[2018-02-25 15:18:27,396]=23:18:27={00000950}<VersionDump>      Version Information:
#7(D)[2018-02-25 15:18:27,397]=23:18:27={00000950}<VersionDump>      Name: NvStreamer
#8(D)[2018-02-25 15:18:27,397]=23:18:27={00000950}<VersionDump>      Major: 1
#9(D)[2018-02-25 15:18:27,397]=23:18:27={00000950}<VersionDump>      Minor: 1
#0(D)[2018-02-25 15:18:27,397]=23:18:27={00000950}<VersionDump>      User Name: builder
#1(D)[2018-02-25 15:18:27,397]=23:18:27={00000950}<VersionDump>      Host Name: WIN7-H02-22
#2(D)[2018-02-25 15:18:27,397]=23:18:27={00000950}<VersionDump>      Build DateTime: Fri, 15 Dec 2017 18:53:37
#3(D)[2018-02-25 15:18:27,397]=23:18:27={00000950}<VersionDump>      Build Configuration: release
#4(D)[2018-02-25 15:18:27,397]=23:18:27={00000950}<VersionDump>      Build Version: 1.1.2328.7129
#5(D)[2018-02-25 15:18:27,397]=23:18:27={00000950}<VersionDump>      P4 Clientspec: unknown
#6(I)[2018-02-25 15:18:27,397]=23:18:27={00000950}<VersionDump>      P4 Changelist: 23287129
#7(D)[2018-02-25 15:18:27,397]=23:18:27={00000950}<VersionDump>      DVS Build: 1
#8(D)[2018-02-25 15:18:27,397]=23:18:27={00000950}<VersionDump>      DVS Branch: gcomp/rel/gs_04_04
#9(D)[2018-02-25 15:18:27,397]=23:18:27={00000950}<VersionDump>      DVS OS: WindowsMisc
#0(D)[2018-02-25 15:18:27,397]=23:18:27={00000950}<VersionDump>      DVS Component: gs_04_04 Release Windows Mjolnir NvStreamer
#1(D)[2018-02-25 15:18:27,397]=23:18:27={00000950}<VersionDump>      DVS IsVirtual: false
#2(D)[2018-02-25 15:18:27,397]=23:18:27={00000950}<VersionDump>      DVS P4HWChangelist: 40042391
#3(D)[2018-02-25 15:18:27,397]=23:18:27={00000950}<VersionDump>      DVS P4SWChangelist: 23287129
#4(D)[2018-02-25 15:18:27,397]=23:18:27={00000950}<VersionDump>      DVS P4VirtualChangelist: 23287129
#5(D)[2018-02-25 15:18:27,397]=23:18:27={00000950}<VersionDump>      DVS SubmittedByUserName: dongyangz
#6(I)[2018-02-25 15:18:27,397]=23:18:27={00000950}<NvStreamerState>  Enumerating network adapters on this system
#7(D)[2018-02-25 15:18:27,404]=23:18:27={00000950}<NvNetworkWin32>   Enumerate Adapters: found adapter {35C25B59-6143-4AA3-BDA0-7C931DFEE237} - vEthernet (DockerNAT)
#8(D)[2018-02-25 15:18:27,404]=23:18:27={00000950}<NvNetworkWin32>   Network Query Parameter: 000000B518D6F610 - 1, 000000B518D6F430, 32, 0000000000000000
#9(D)[2018-02-25 15:18:27,408]=23:18:27={00000950}<NvNetworkWin32>   Network Query Parameter: 000000B518D6F610 - 2, 000000B518D6F430, 32, 0000000000000000
#0(I)[2018-02-25 15:18:27,408]=23:18:27={00000950}<NvStreamerState>  --- 00:15:5D:01:64:08: 10.0.75.1 / fe80::1d0b:28f0:c6fc:7f35%7
#1(D)[2018-02-25 15:18:27,408]=23:18:27={00000950}<NvNetworkWin32>   Enumerate Adapters: found adapter {BFF0C2A4-7DFE-44E0-B7BC-3426FF14E46E} - vEthernet (
#2(D)[2018-02-25 15:18:27,408]=23:18:27={00000950}<NvNetworkWin32>   Network Query Parameter: 000000B518D6F610 - 1, 000000B518D6F430, 32, 0000000000000000
#3(D)[2018-02-25 15:18:27,408]=23:18:27={00000950}<NvNetworkWin32>   Network Query Parameter: 000000B518D6F610 - 2, 000000B518D6F430, 32, 0000000000000000
#4(I)[2018-02-25 15:18:27,408]=23:18:27={00000950}<NvStreamerState>  --- A2:15:FD:46:0D:10: 172.21.143.193 / fe80::8892:6cfe:bcfb:6d1a%17
#5(D)[2018-02-25 15:18:27,408]=23:18:27={00000950}<NvNetworkWin32>   Enumerate Adapters: found adapter {86A3AF06-1910-4CC0-95E6-111D42CA1507} - WLAN
#6(D)[2018-02-25 15:18:27,408]=23:18:27={00000950}<NvNetworkWin32>   Network Query Parameter: 000000B518D6F610 - 1, 000000B518D6F430, 32, 0000000000000000
#7(D)[2018-02-25 15:18:27,408]=23:18:27={00000950}<NvNetworkWin32>   Network Query Parameter: 000000B518D6F610 - 2, 000000B518D6F430, 32, 0000000000000000
#8(I)[2018-02-25 15:18:27,408]=23:18:27={00000950}<NvStreamerState>  --- 48:5A:B6:19:77:1F: 192.168.1.2 / fe80::fc4f:c954:a808:4f8b%13
#9(D)[2018-02-25 15:18:27,408]=23:18:27={00000950}<NvNetworkWin32>   Enumerate Adapters: found adapter {0D397524-062C-11E8-848A-806E6F6E6963} - Loopback Pseudo-Interface 1
#0(I)[2018-02-25 15:18:27,414]=23:18:27={00000950}<NvStreamerState>  Building head list
#1(I)[2018-02-25 15:18:27,461]=23:18:27={00000950}<Utils>            Adapter vendor id: 0x10de, device name: \\.\DISPLAY1
#2(I)[2018-02-25 15:18:27,461]=23:18:27={00000950}<SignalingContain> Creating a MB SCI Thread
#3(W)[2018-02-25 15:18:27,463]=23:18:27={00000950}<CommonDataStore>  Failed to get GA_TRACKING_ID
#4(W)[2018-02-25 15:18:27,463]=23:18:27={00000950}<CommonDataStore>  Failed to get GA_TRACKING_ID
#5(D)[2018-02-25 15:18:27,471]=23:18:27={00000950}<NvThread>         Started native thread: BusMessageProcessingThread (thread id: 000047FC)
#6(D)[2018-02-25 15:18:27,471]=23:18:27={000047FC}<SciMb>            SciMb worker thread starting.
#7(I)[2018-02-25 15:18:27,473]=23:18:27={00000950}<SignalingContain> SCI Thread creation done
#8(I)[2018-02-25 15:18:27,474]=23:18:27={00000950}<NvEncUtil>        Computing SPS/PPS headers.
#9(I)[2018-02-25 15:18:27,475]=23:18:27={00002B28}<SciMb>            SCI:SciNvStreamer has connected to MessageBus
#0(I)[2018-02-25 15:18:27,475]=23:18:27={00002B28}<SciMb>            SSAU:StreamerController is present on MessageBus.
#1(I)[2018-02-25 15:18:27,481]=23:18:27={00000950}<FbcUtil>          Loaded library from 'C:\Windows\system32\NvFBC64.dll'
#2(I)[2018-02-25 15:18:31,608]=23:18:31={00000950}<AdapterContext>   Initialized context for adapter 0: 1920 x 1080 @ 60.0 Hz
#3(I)[2018-02-25 15:18:31,608]=23:18:31={00000950}<AdapterContext>   Driver version is 390.65, branch is r390_63.
#4(I)[2018-02-25 15:18:31,608]=23:18:31={00000950}<AdapterContext>   System is co-proc.
#5(D)[2018-02-25 15:18:31,883]=23:18:31={00000950}<AdapterContext>   GPU memory usage: used = 1060.827344, free = 5083.172656 MB, total = 6144.000000 MB
#6(I)[2018-02-25 15:18:31,883]=23:18:31={00000950}<AdapterContext>   Initialized CUDA for device 'GeForce GTX 1060' (SM 6.1) in compute mode 'CU_COMPUTEMODE_DEFAULT'.
#7(I)[2018-02-25 15:18:31,896]=23:18:31={00000950}<GPUInfo>          GPU's = {
#8(I)[2018-02-25 15:18:31,896]=23:18:31={00000950}<GPUInfo>          	{
#9(I)[2018-02-25 15:18:31,896]=23:18:31={00000950}<GPUInfo>          	FriendlyName=GeForce GTX 1060
#0(D)[2018-02-25 15:18:31,896]=23:18:31={00000950}<GPUInfo>          	Is GPU in local Game Streaming Whitelist=1
#1(I)[2018-02-25 15:18:31,896]=23:18:31={00000950}<GPUInfo>          	}
#2(I)[2018-02-25 15:18:31,896]=23:18:31={00000950}<GPUInfo>          	{
#3(I)[2018-02-25 15:18:31,896]=23:18:31={00000950}<GPUInfo>          	FriendlyName=INTEL(R) HD GRAPHICS 4600
#4(D)[2018-02-25 15:18:31,896]=23:18:31={00000950}<GPUInfo>          	Is GPU in local Game Streaming Whitelist=0
#5(I)[2018-02-25 15:18:31,896]=23:18:31={00000950}<GPUInfo>          	}
#6(I)[2018-02-25 15:18:31,896]=23:18:31={00000950}<GPUInfo>          }
#7(I)[2018-02-25 15:18:31,896]=23:18:31={00000950}<GPUInfo>          Nvidia GPU count: 1, Non Nvidia GPU count: 1
#8(I)[2018-02-25 15:18:31,896]=23:18:31={00000950}<ServerMiscUtils>  Found a match at [13]
#9(D)[2018-02-25 15:18:31,896]=23:18:31={00000950}<VideoEncoder>     Creating NvEnc7VideoEncoder.
#0(I)[2018-02-25 15:18:31,896]=23:18:31={00000950}<VideoEncoder>     Initializing NvEnc7VideoEncoder.
#1(I)[2018-02-25 15:18:31,896]=23:18:31={00000950}<NvEnc7VideoEncod> Using NvEnc header version 0.7.
#2(E)[2018-02-25 15:18:31,898]=23:18:31={00000950}<NvEnc7VideoEncod> Failed to load NvEnc DLL from 'nvEncodeAPI64.dll'.
#3(E)[2018-02-25 15:18:31,898]=23:18:31={00000950}<NvEncUtil>        Failed to initialize encoder for RTSP SPS/PPS header generation.
#4(D)[2018-02-25 15:18:31,898]=23:18:31={00000950}<AdapterContext>   GPU memory usage: used = 1060.827344, free = 5083.172656 MB, total = 6144.000000 MB
#5(I)[2018-02-25 15:18:31,915]=23:18:31={00000950}<AdapterContext>   Deinitialized CUDA context for adapter 0.
#6(I)[2018-02-25 15:18:31,927]=23:18:31={00000950}<AdapterContext>   Deinitialized context for adapter 0
#7(D)[2018-02-25 15:18:31,927]=23:18:31={00000950}<VideoEncoder>     Destroying NvEnc7VideoEncoder.
#8(E)[2018-02-25 15:18:31,927]=23:18:31={00000950}<NvEncUtil>        Error computing SPS/PPS headers.
#9(E)[2018-02-25 15:18:31,927]=23:18:31={00000950}<NvStreamer>       NvEncodeAPI Not Supported
#0(I)[2018-02-25 15:18:31,927]=23:18:31={00000950}<NvStreamer>       NvEnc initialization failure
#1(I)[2018-02-25 15:18:31,928]=23:18:31={00000950}<NvStreamer>       Send event for StreamerInitFailure with SERVER_TERMINATED_ENCODER_DLL_LOAD_FAILED
#2(I)[2018-02-25 15:18:31,928]=23:18:31={00000950}<SciBase>          Sent event StreamerInitFailure: SERVER_TERMINATED_ENCODER_DLL_LOAD_FAILED
#3(I)[2018-02-25 15:18:31,928]=23:18:31={00000950}<SciMb>            Stopping SciMb
#4(D)[2018-02-25 15:18:31,928]=23:18:31={00000950}<NvThread>         About to destroy native thread: BusMessageProcessingThread (thread id: 000047FC)
#5(D)[2018-02-25 15:18:31,928]=23:18:31={000047FC}<SciMb>            SciMb worker thread quitting.
#6(D)[2018-02-25 15:18:31,928]=23:18:31={000047FC}<NvThread>         Completed thread function for native thread: BusMessageProcessingThread (thread id: 000047FC)
#7(D)[2018-02-25 15:18:31,928]=23:18:31={00000950}<NvThread>         Destroyed native thread: BusMessageProcessingThread (thread id: 000047FC)
#8(I)[2018-02-25 15:18:31,928]=23:18:31={00000950}<SciMb>            SciMb Stopped
#9(I)[2018-02-25 15:18:31,928]=23:18:31={00000950}<SignalingContain> Terminated the SCI thread

**Comment by deeptuuk** [comment]
i meet the same problem, could you tell me how to solve now? thanks
