### ISSUE TITLE
android tv box (amlogic s912) latency

### ISSUE THREAD

**Issue by nLLIeHu4ka** [moonlight-stream/moonlight-android#541]
hi.. i have android tv box ugoos am3 amlogic s912... bad work on all android tv box (amlogic 905x, 912)..many guys write on forum same problems ..big ms decoding and microlags. very big hardware decoding... 120 ms on h264.. and 40 ms on h265... in all resolutuion with 30 60 fps with differet bitrate ... no reason.. on my old snapdragon 410 20 ms on h264... but amlogic more powerfull than my snapdragon... 

guys, its possible reduce latency on android tv? thx

**Comment by HewellP** [comment]
Better, we continuo at this post https://github.com/moonlight-stream/moonlight-android/issues/347 and close this issue
