### ISSUE TITLE
v5.7 crash upon entering settings

### ISSUE THREAD

**Issue by Peppermintje** [moonlight-stream/moonlight-android#543]
v5.7 crash upon entering settings.
v5.6.7 works fine.
Android device = Samsung Tab S 8.4 (2560x1600).
Reinstalling (and delete date/cache doesn't solve the issue.

**Comment by cgutman** [comment]
Thanks for this report. It was quite an interesting bug.

The Dutch translation was the only translation where the translator included a copy of the resolutions list in their translation. That copy of the resolution list didn't get updated when I added 360p, so the preferences crashed trying to update the list.

**Comment by cgutman** [comment]
Fix released in v5.7.1

**Comment by Peppermintje** [comment]
Thanx for the quick fix!
