### ISSUE TITLE
Streaming throw 4g

### ISSUE THREAD

**Issue by Mrt-68** [moonlight-stream/moonlight-android#544]
Hello,

Do you know any link of explanation/tutoriel for setting up the 4g streaming? I have seen any of them and what is linked in the moonlight app is just not working.

Thanks..

**Comment by cgutman** [comment]
4G streaming is no different than any other configuration for streaming over the Internet.

https://github.com/moonlight-stream/moonlight-docs/wiki/Setup-Guide#streaming-over-the-internet

What happens when you follow those steps?

**Comment by Mrt-68** [comment]
I tried to put in udp tdp allows in, I found my ip adress and all other info but i can't even see any connection between app and my pc when using 4g
Fyi, my firewall is disabled also..

**Comment by Mrt-68** [comment]
I found this link for who is having issue for 
4g streaming.

https://youtu.be/DLv_Wi52Pgg

My problem is solved now, I was trying to allow tcp and udp in my second router. What I was supposed to is to put these ports in my main router which I did now and it works.

Thanks for your answer :)
