### ISSUE TITLE
Can I disable gamepad passthrough?

### ISSUE THREAD

**Issue by vrokolos** [moonlight-stream/moonlight-android#549]
I've got a steam controller connected directly to my PC and whenever I play some games with moonlight it isn't recognized. Can I make moonlight stop messing with my gamepads? I think it's because of a remote-gamepad-2in1 I've got connected to my TV. But I don't want to use that at all.

**Comment by thw0rted** [comment]
Did you already follow [the instructions in the manual](https://github.com/moonlight-stream/moonlight-docs/wiki/Setup-Guide#using-a-gamepad-connected-to-the-pc-instead-of-the-streaming-device)?
