### ISSUE TITLE
Controller 1 registers as two players

### ISSUE THREAD

**Issue by rmehta1987** [moonlight-stream/moonlight-android#550]
Not sure if this a Moonlight issue or a Steam issue. For some reason controller 1, no matter what, will register as two players. For example, in Castle Crashers, if you use the main-game pad that you entered moonlight with, it will auto-select two characters for you. This bug seems to happen randomly, it goes away sometimes, but then comes back and I have no idea how to fix it. I have been reading around and it maybe an issue with xinput controls, but not exactly sure. Anyone have any ideas?

Edit:

Another thing to note, I have noticed this happens in games when "selection button" is the same as the start button. For example, in "Sega All Stars Racing Transformed" to join the game you must press the start button and from then you use "A" to select your maps and everything else. If you are controller 1 and press the start button on the main screen, it will register you as both player 1 and player 2.

**Comment by serge-sb** [comment]
I have the same issue. My gaming device is GPD XD, I've tried different settings (XBox/PS gamepad mode in GPD system settings), tried checking and unchecking 'multiple controllers' in Moonlight app setting. Nothing helps. Also, I double what @rmehta1987 said: sometimes - quite rarely - everything works ok. I'm playing LEGO Pirates of Carribean - usually the game detects my input as both two controllers, so both characters are controlled like there are two inputs doubled as one.

What helps: I've also got the F710 dongle connected to my PC. When I disconnect it, and restart the game, then most of the times it helps. But rebooting (still F710 dongle detached) brokes again the game input.

**Comment by serge-sb** [comment]
Ok, I did a bit of testing and it seems that this is a Steam issue.

So. In case your controller doubles the controls to #1 and #2 (and maybe more) controllers, then open Steam settings - Controller Settings - and uncheck "Xbox Configuration Support". Steam app restart is required, PC reboot is highly recommended. Moonlight restart - I think - is optional.

Any Moonlight settings do not affect this issue, nor GPD XD's gamepad system app settings do. Also, you may have any other controllers support checked in Steam Controller Settings if you need them. Only "Xbox Configuration Support" seems to affect this.

@rmehta1987 could you please try this?

**Comment by rmehta1987** [comment]
@serge-sb Yes!  This seems to reduce the issue.  I wonder if this is because moonlights internal driver for the Xbox controller works.  This, however, prevents us from changing controller configurations.
