### ISSUE TITLE
Android Tablets

### ISSUE THREAD

**Issue by Vahn84** [moonlight-stream/moonlight-android#551]
Hi guys,

Firs of all i have to excuse myself for opening an issue here...this is not really an issue...but i don't really know where to ask for some advices and some discussions i found in the internet are too old to be acceptable.

I first used moonlight with an ipad air 2 (2048x1536) and a 2k monitor, and it was good enough to make me hope for a better experience. Black bars were too big, i was forced to use an xbox wireless controller (paired with my pc) and i had occasional lags and stutters. 

Time has passed and i turned back to a 1080p monitor, and i still want to play pc games on a tablet (the nintendo switch ruined my life xD ). 

The fact is that i don't know which tablet i should buy. I want a solid experience without spending too much cash. I'll surely buy an ipega 9023 to play more comfortably without the hassle of using a "separate" device

Moonlight is an awesome project but i feel that the wiki should be updated every now and then with a list of devices suggested to people who maybe do not know where to start from

I want an android tablets, mainly because every ipad has a 4:3 ratio and i hate those black bars. I didn't know there weren't android tablet with 16:9 ratio but i think i can accept a 16:10 aspect ratio tablet (I think i read somewhere that the android build of moonlight has an option to fill the screen, is that true? )

Anyway...which tablet should i buy to obtain the most flawless and solid experience i can ? 

Given my 1080p monitor...should i buy a 1920x1200 tablet or a 1280x800 one? I have a wifi abgn ac capable router...should i watch for an ac capable tablet or an N capable one is ok? Should i go with an hd 1280x800 tablet and play 720p to get the most flawless experience possible?

Please help me...i can't really decide which one i should buy. I'm surfing the web, watching videos and reviews but i didn't really find something more specific to fullfill my need of answers. 

I do not want to spend more than 250€, mostly because every tablet that exceeds that range ships with a 2k display that i think would be useless in my case (and also because i have a nitendo switch and i don't want to spend too much money on something so "similar" in terms of gaming style)

Thanks and sorry for the long post!

**Comment by muffinmannameistaken** [comment]
i would suggest the tab s2 8" it sells for around 250$ U.S it does have a 2048x1536 resolution but i modded moonlight to support the resolution. Iv been requesting the author to see if he would add support for other resolution. ill be updating my version soon.

**Comment by Vahn84** [comment]
HI @muffinmannameistaken 

thanks for your reply. I'm worried about the fact that i will stream a 1080p signal to a bigger resolution tablet. Wouldn't it mean that i will have low quality images? Would it affect in any way the load on the wifi signal?

Here in Italy i can find the S2 at 300€, more or less. 

I can afford the money but i need to be sure that it will be the perfect solution. I don't want low quality images. Is it a 5:3 aspect ratio? Are there any black bars on the S2?

**Comment by thw0rted** [comment]
Like you, I want to play every game on the Switch forever.  Keep in mind that the screen there is only 6.2" / 720p, so if you're happy with that, it might make sense to just get a 7" tablet or even an older / lower-end 6.X" phone.  Then again, I play Switch almost exclusively with the controllers attached -- if you're going to play in "tabletop mode" then certainly a bigger display would make more sense.

**Comment by Vahn84** [comment]
hi @thw0rted thanks for your advice. In fact, I'm just looking at the nvidia shield k1 that has a 7 inches display with a 1920x1200 resolution (16:10). Like you I play exclusively with controllers attached, so I think it's better to look at 7/8" screen then a 10" one. 

Is the nvidia shield k1 a good option? I'm trying to find it of second hand cause I know that has been discontinued from nvidia.

Other options are 

- Lenovo tab 4 plus 8" - 1920x1200 - 16:10 (300€)
- Huawei MediaPad M3 Lite 8" - 1920x1200 - 16:10 (249€)

I would like to spend less money, cause I already own an iPad Air 2, so this tablet would be used 99% of the time to stream games from my pc. 

if I can find an nvidia shield k1 at max 150€ would that be the way to go?

**Comment by thw0rted** [comment]
I hear really great things about the whole Shield line, and have seriously considered one myself.  I haven't actually used it though, so I'm not sure how much help I could be.  A nice side effect of buying an nvidia-branded device is that you could use their native Gamestream client instead of Moonlight.  (Although, again, I haven't actually owned one so I haven't had the opportunity to use that either...)

**Comment by thw0rted** [comment]
If you're willing to spend 250EUR for a good Moonlight tablet, for a little extra you could think about buying a second Switch and keeping it on an older firmware, then running Linux on it.  I'd be surprised if anybody has Moonlight running on it right now, but I'd also be surprised if it's very hard to get it working.

This sounds *amazing* and I'd be super excited to try it myself, but the homebrew / custom firmware community isn't quite there yet.  Still, something to think about...

**Comment by Vahn84** [comment]
Hi @thw0rted 

i ended up buying the nvidia shield k1. I found it on ebay of second hand at 140€. 

At that price i could have bought not much in reality. There were the huawei T3 8 and the amazon fire hd 8 at 30€ less...but those are really low power tablets. The K1 is still one of the most powerful tablet out there. 

I will surely test both the official nvidia gamestream and moonlight, but i think i'll go with moonlight that has better customization and it actually use the same protocol so i don't expect much of a difference

**Comment by EasyGitHub99** [comment]
@Vahn84 This is a late reply, but for anyone on this journey like me just now:
ALLDOCUBE iPlay10 Tablet, 10.6 inch Tablet PC, 1920x1080 IPS Screen, 5Ghz + 2.4Ghz Wifi
I got it on Amazon for $100 just now, I'll receive it in two days, so I haven't had a chance to test it. 

But with the IPEGA PG-9083 tablet controllers (supports up to 11") my total cost was $150 including $3.99 faster shipping.

Been using Moonlight on my Note 8 (6.3" in screen), with an xbox controller with a $10 phone holder clip on attachment, and it works amazingly except for some xbox controller disconnection issues every now and then. But Its kind of hard to play because I need the little phone screen right in my face, and the angle of holder and the controller aren't right and make it hard to comfortably hold the screen close enough while playing.

If I get any reply's here I'll update with my review of the 1080p tablet & Ipega pg-9083

**Comment by adcar** [comment]
> @Vahn84 This is a late reply, but for anyone on this journey like me just now: ALLDOCUBE iPlay10 Tablet, 10.6 inch Tablet PC, 1920x1080 IPS Screen, 5Ghz + 2.4Ghz Wifi I got it on Amazon for $100 just now, I'll receive it in two days, so I haven't had a chance to test it.
> 
> But with the IPEGA PG-9083 tablet controllers (supports up to 11") my total cost was $150 including $3.99 faster shipping.
> 
> Been using Moonlight on my Note 8 (6.3" in screen), with an xbox controller with a $10 phone holder clip on attachment, and it works amazingly except for some xbox controller disconnection issues every now and then. But Its kind of hard to play because I need the little phone screen right in my face, and the angle of holder and the controller aren't right and make it hard to comfortably hold the screen close enough while playing.
> 
> If I get any reply's here I'll update with my review of the 1080p tablet & Ipega pg-9083

How'd this end up working out for you? was thinking of something similar with those ipega controllers but haven't decided on a tablet

**Comment by tristan-k** [comment]
@adcar Don't buy a Huawei Mediapad M5 8.4 because moonlight seems to have [issues](https://github.com/moonlight-stream/moonlight-android/issues/928#issuecomment-981160307) with the [video decoders](https://github.com/moonlight-stream/moonlight-android/issues/558) on this device.

**Comment by adcar** [comment]
@tristan-k Oh okay thanks for the heads-up
