### ISSUE TITLE
Bluetooth keyboard WASD movement

### ISSUE THREAD

**Issue by ltbosox** [moonlight-stream/moonlight-android#552]
I've searched around and all I can find on the topic is dated to 2016. My issue is with the BT keyboard where movement keys, WASD, are still acting as key presses rather than being held down for movement. When I press and hold the "W" key, to move forward, it either does nothing or slightly jumps forward. Same with the other movement keys. Is there anything in the works to fix this or is it a dead issue with no fix in sight?

I'm on a Note 8 streaming over LTE. Are there keyboards that one could buy that do work via plugging in someway or something else?

**Comment by cgutman** [comment]
It wasn't a dead issue then, it was Nvidia's bug and fixed by a new version of GeForce Experience.

I don't see this behavior in Borderlands 2 with the current beta GFE. What game do you see this in?

**Comment by ltbosox** [comment]
Ark: Survival Evolved.

I'm updated to current as far as I know. The keyboard I have isn't name brand or anything. I wonder if it's an issue with that specific keyboard.

**Comment by cgutman** [comment]
Can you try a few other games and see if it's a game-specific compatibility issue?

**Comment by ltbosox** [comment]
Yeah, I'll try more tomorrow and update.

**Comment by ltbosox** [comment]
**Update**
I've tried the following 3 games with the same result:
Ark
Minecraft
Call of Duty: Black Ops 2

I got a USB-C to standard USB connector and hooked up a Logitech keyboard and mouse combo dongle and got the same result with the keyboard movement.

**Comment by cgutman** [comment]
Thanks, are you running GeForce Experience 3.13 (released yesterday) or some other version?

**Comment by ltbosox** [comment]
Most likely one older version. I will check later tonight and then update. Thanks for your help man.

**Comment by ltbosox** [comment]
Just got the update. I tried on the new version and still the same result. Can you suggest any free games that you have been able to verify work that I can download and try?

**Comment by cgutman** [comment]
If you stream your desktop and open notepad inside Moonlight, does holding down a key cause the letter to repeat? It does for me on a couple of devices I've tried.

Instructions to stream your desktop are here: https://github.com/moonlight-stream/moonlight-docs/wiki/Setup-Guide#using-moonlight-to-stream-your-entire-desktop

**Comment by ltbosox** [comment]
Yes and no. If I were to press down a single key, it will display once, wait about half a second, then repeat in quick succession. If I were to press a key then transition quickly to another key press, such as you would when using the wasd keys for direction control, it would sometime work the same but also sometimes it would only display once.

I tested both ways in game and got the same result, no movement or stuttered slight movement. 

I tested the keyboard hooked directly to my pc and it works as it should. I also tested the keyboard while connected to my phone but in desktop viewing mode with a game running. It wouldn't even register anything.

**Comment by legocraftmation** [comment]
I am having the same problem. In rocket league or any other game my car or player would move forward for a millisecond and just stop whenever I clicked on w a s or d.

**Comment by cgutman** [comment]
I'm still unable to reproduce the issue. I'm testing on a Nexus 9 running Android 7.1.1.

I tested the following games:
Borderlands 2
Dragon Age: Inquisition
The Witcher 3: Wild Hunt
Rocket League (which did repro for @legocraftmation but works for me just fine)
Minecraft: Windows 10 Edition (I did see the issue, but only on the menus and it also occurs when not using Moonlight. In game, WASD works fine)

Maybe it has to do with the Android device or PC. What Android devices are you using and what OS version on them? What OS is running on your PC?

Are you able to reproduce the issue if you try another Moonlight client like https://github.com/moonlight-stream/moonlight-chrome/releases ?

**Comment by Waaaaghhhh** [comment]
I'm having this issue as well. A keyboard hooked up to my Android device via USB OTG does not allow me to use WASD in game. I am able to type on something like Notepad with no issues. Pressing and holding W in Notepad does work and the letter would be entered, followed by a pause, and then repeating.

But in game this does not work. 

I'm using a Oneplus 6 on Android 8.1 Oreo

**Comment by ltbosox** [comment]
My issue was never resolved. I just gave up. I haven't tried recently (within 4-5 months) but apparently it wasn't fixed.

**Comment by kedirakevo** [comment]
> My issue was never resolved. I just gave up. I haven't tried recently (within 4-5 months) but apparently it wasn't fixed.

Me too, I'm facing this issue. I used 2 devceis... Xiaomi Mi 6 and Xiao Mi Mi Pad 4... both gave the same issue regardless BT or wired... but I can move just fine using arrow keys, and in game chat wasd workings normally while texting
