### ISSUE TITLE
Bluetooth mouse right click causes cursor to jump

### ISSUE THREAD

**Issue by Peppernose145** [moonlight-stream/moonlight-android#554]
Whenever I right click, the mouse cursor jumps either up or down.

Device: Samsung Galaxy Tab S3, running Android N official ROM.
Mouse: Microsoft Mobile Mouse 3600

To replicate: Using a Bluetooth mouse, connect to PC with mstsc.exe, and right click anywhere.

**Comment by cgutman** [comment]
Of course after I see it with my own eyes, then try to reproduce it to debug, it stops happening...

**Comment by Peppernose145** [comment]
Additional info: This bug is present on at least the non-root version (The only version I can use on my current device), and the cursor jump appears to happen if the Android cursor is over the display from the PC, and not if the Android cursor is over the black bars

**Comment by cgutman** [comment]
Finally figured it out. Turns out it was a spurious event from the OS with the wrong coordinates. Now we ignore that.

**Comment by Peppernose145** [comment]
Good
