### ISSUE TITLE
Steaming to Sony Bravia with Android KD-49X8307C Unplayable 

### ISSUE THREAD

**Issue by 90Ninety** [moonlight-stream/moonlight-android#556]
Sony Bravia with Android KD-49X8307C

The streaming to the  Sony Android  TV from PC is unplayable , the games wont load fully and often end up crashing . I have tried all of the video config options  but, makes no difference . I guess this is something to do with the MeidaTek chipset not decoding?

Works perfect when streaming to My Huawei P10 lite , with snapdragon

**Comment by cgutman** [comment]
OK, I've got a few more specific questions.

What do you mean exactly when you say "the games wont load fully"? They don't load on your PC or they load but Moonlight can't connect? Or something else completely?

When you say "crashing" do you mean Moonlight says "Connection Terminated" or the app actually crashes and displays a "Moonlight has stopped" dialog? When it doesn't crash, is the video laggy or stuttering? Does the audio sound fine during the video issues?

Did you try 30 FPS? Did you try streaming 60 FPS with the "Never drop frames" checkbox checked?

**Comment by 90Ninety** [comment]
Hi 
Same issue as this thread here [https://github.com/moonlight-stream/moonlight-android/issues/316](url) I added to this that I have the same issue , the first few frames load on Moonlight client , then a garbled mess ( I hear the audio fine ) 
Game runs fine on Host PC 

Moonlight crashes when forcing the 265 codec , otherwise , the frames just garble or stop rendering .  I tried all options - I have not  yet found stability

**Comment by cgutman** [comment]
Ok thanks. What version of GeForce Experience is running on your PC?

**Comment by 90Ninety** [comment]
> Ok thanks. What version of GeForce Experience is running on your PC?

I am running 3.13.1.30 . I just tried re-installing , no difference .
![image](https://user-images.githubusercontent.com/3172911/37688404-da5279e2-2c97-11e8-9371-edec5c1ed605.png)

**Comment by 90Ninety** [comment]
Why is the issue closed , I dont remember closing it?

**Comment by 90Ninety** [comment]
Bump , I accidently closed and now re-opened

**Comment by 90Ninety** [comment]
Well I persevered with some more experimental testing , I was actually able to get the game running on the Moonlight client but only  within the lowest (420 or 320p / 60hz  I think )  resolution . 

I noticed that when selecting higher resolution the initial game intros load  but , when the actual game starts , the frames stop rendering on the client , which usually results in a black screen .  

This is frustrating especially as there are others in the thread above who are able to run moonlight on a cheaper inferior Phillips Android Smart TV - even at 4K  .

**Comment by 90Ninety** [comment]
Not sure why but , the thread link above is causing a loopback to this thread

**Comment by 90Ninety** [comment]
> Do you still have the issue if you run this older version of Moonlight? https://github.com/moonlight-stream/moonlight-android/releases/tag/v5.6.3

To be honest I have not tried side-loading apps with this Smart TV set yet, as I have not had to  but , will give it a try later and see how I get on .

**Comment by 90Ninety** [comment]
Ok today I had a chance to install the older version ( v5.6.3) Unfortunately this made no difference , still same issue : game starts , intros load then start to chop , then black screen/garble

**Comment by 90Ninety** [comment]
@cgutman 
Is this an issue with just Bravia Android ?

**Comment by 90Ninety** [comment]
@cgutman An Update: 

I decided to connect the Android TV ( as a temporary Measure ) to the WiFi ; low and behold, all games load up and stream just fine . 

I am really confused why the Wifi Is giving better performance - I guess there are some bugs on the Ethernet card on the TV
