### ISSUE TITLE
High latency on Huawei Mediapad M5

### ISSUE THREAD

**Issue by AtlasOne89** [moonlight-stream/moonlight-android#558]
Hello guys,
I got my Mediapad M5 yesterday and it has a decoding latency around 50ms with both - h264 and h265.
I already tried different resolution/fps targets and bitrates but this doesn't change much. The latency is always around 50ms. This device should reach better values or am I wrong? Even my 3 year old LG G4 phone reaches 11ms under the same conditions.

Setup Client:
Huawei Mediapad M5
Andoid 8.0 Oreo
Moonlight v5.7.2
720p/60 10MBit

Setup Host:
GTX 1080Ti
Geforce Experience 3.13.1.30

The tab is directly connected to the host-pc via wifi (the host provides a hotspot)
2,4GHz full signal

Is there something other I could try to get a better latency?

**Comment by cgutman** [comment]
Can you try each of these APKs and tell me which of them (if any) perform better than the official version?
https://drive.google.com/open?id=1Q82huGcjnttcDi_xlgRavg4AgJztPsiC
https://drive.google.com/open?id=1F6Ej4LtKJr855ca5dRF2QeG8pKQiyo1f
https://drive.google.com/open?id=1pkPh69pb_bL5c_C9VuzMhXB6I_4_K37P

**Comment by AtlasOne89** [comment]
@cgutman 
Thank you, I really appreciate your help.
I tested all APKs including the playstore version right now and unfortunately they all produced the same results: 48ms for both h264 and h265 in 720p/60.
Is it normal to get the exact same latency regardless of h264 or h265?

**Comment by sjohnsox** [comment]
Very similar issue with ASUS Zenpad 3s 10. My Pixel XL 2 can hit 8ms, the Zenpad can hit 48ms on 264, 24ms on 265.  Have tried a hard reset on tablet, double checked power settings, disabled apps, etc... I can't get it any lower than 24ms, lowering bitrate doesn't help.

**Comment by sjohnsox** [comment]
Adding to this, I wonder if it has to do with Mediatek devices in general causing the latency to "cap out" so to speak. Right now the floor seems to be 48ms on 264, 24ms on 265... Would love to get that lower.

**Comment by RaouleMenard** [comment]
Is there any recent improvements on latency for the Huawei Mediapad M5?
I'm really interested in getting this tablet for its size and small bezels, but I hope Moonlight works well on it, or else it is a deal breaker for me.
Thanks!

**Comment by tranceonline** [comment]
Have the same issue with my Huawei Mate 10 Pro.
Seems to have to do with the Huawei Chipset. I think it's the HiSilicone think which gives problems.

**Comment by tristan-k** [comment]
I'm also [struggeling](https://github.com/moonlight-stream/moonlight-android/issues/928#issuecomment-981160307) with a Huawei Mediapad M5. The decode latency is unusally high (44ms).
