### ISSUE TITLE
Controlling mouse with gamepad

### ISSUE THREAD

**Issue by tijmenvn** [moonlight-stream/moonlight-android#56]
I have a nexus player and have connected a xbox 360 controller to it. The problem I have, is when there's a certain login screen (star citizen, elite dangerous, war thunder). Then i can't control the mouse. I remember my nvidia shield having a option to control the mouse with the joystick when both start+select buttons are pressed, and back to controller mode when these buttons are pressed again, maybe a handy feature to put in the next version?

**Comment by cgutman** [comment]
This is implemented with a long press on Start.

**Comment by ubeogesh** [comment]
good that you've implemented long pressing start, but it has a slight conflict with 8bitdo SN30 pro controller. On it, long pressing start *turns off the controller*. Luckily, to turn off i need to hold it a little bit longer, so there's a small window of long press where i switch to mouse mode and don't turn it off, but it's quite inconvenient

Please lets us change the button
