### ISSUE TITLE
Video stuttering, choppy/distorted audio on HTC U11 over WiFi only

### ISSUE THREAD

**Issue by dkr88** [moonlight-stream/moonlight-android#563]
Wondering if anyone can provide some insight or debugging steps:

Basically, my HTC U11 (Android 8.0) exhibits very bad video stuttering and choppy/distorted audio when streaming over WiFi - no matter what bit rate I select. If I use a USB ethernet adapter, it's perfectly fine. Also works perfectly fine over LTE with a VPN.

The kicker is: Nexus 5X, Moto E (!), Surface 4 (Chrome plugin) all stream perfectly fine on the same AC1900 WiFi network. WiFi bandwidth/latency is not an issue. Internet speed tests on the U11 max out my 175Mbps connection with 3ms latency.

I've tried forcing "performance mode" in Android developer settings, but that doesn't help. Also tried forcing x265 and not, same result. Any suggestions or steps I could take to get to the cause of the issue?

**Comment by 90Ninety** [comment]
Try setting your host  machine to 100mbps full duplex . Worked for me on some devices that weren't performing well

**Comment by dkr88** [comment]
Gave up on trouble shooting and factory reset the phone - somehow that fixed the issue, even after restoring all previous apps. So presumably it was an Android issue and not a Moonlight issue.
