### ISSUE TITLE
Question: Is there any options to enable VR view? (SBS)

### ISSUE THREAD

**Issue by MardariG** [moonlight-stream/moonlight-android#565]

**Comment by cgutman** [comment]
Nothing officially in Moonlight, but VRidge does have support for using Moonlight as a streaming client. We're not associated with VRidge at all though.

https://riftcat.com/vridge

**Comment by MardariG** [comment]
I've overrided StreamView with other SBS implementation so it is working just  fine. Thanks for awesome project.

**Comment by zediiiii** [comment]
Will you share which sbs implementation you are using?

**Comment by MardariG** [comment]
> Will you share which sbs implementation you are using?

https://github.com/MardariG/moonlight-android

**Comment by zediiiii** [comment]
I tried this one https://github.com/alandao/moonlight-android, and it uses a lovely implementation of Google Carboard that allows me to adjust VR settings (IPD etc), but the stream is blank. 

This second fork does work (https://github.com/monstrobishi/moonlight-android) but you have to install an old version of GFE or you'll get an RTSP handshake error. Unfortunately, you can't adjust IPD or any other VR settings on the second one, so with my note 8, that's a bust too.

I'm building the MardariG fork now.

**Comment by zediiiii** [comment]
Well, I've put a bunch of time into getting that fork to build. I tried various gradle versions, various versions of moonlight-common, importing over top of present moonlight-common, fudging around with values. On to find a working copy of Tridef I suppose.

**Comment by MardariG** [comment]
did you follow the building steps from readme?
```
Run ‘git submodule update --init --recursive’ from within moonlight-android/
```

**Comment by zediiiii** [comment]
Thanks for your help. Cloning the repo yeilds a "submodule points to a commit which does not exist" error - ie, it can't access the moonlight-common pointer referenced.

In version 5.6.5 (downloaded manually), I added the google() repo to the build.gradle, updated to gradle tools 3.3.1 (so that it will work with the present ndk), and manually dropped in the requested version of moonlight-common. The resulting APK doesn't have SBS support though.

**Comment by nk33** [comment]
Quick question....

So the way i played games in 3d/vr was to use moonlight with tridef to make the games SBS, then stream that to my phone using moonlight , put the phone in standard google cardboard headset - then off i go....i could also use trinus to add head tracking...

.....now i have an oculus quest for VR. i have sideloaded Moonlight Go and use that to stream from my pc to my quest to play games in 2D theatre mode - however how can i get the Quest to see the tridef stream as an sbs stream and stream it to me in vr? (ie without it showing me just 2 screens next to eachother)

**Comment by jphein** [comment]
Can we open this issue again? I haven't been able to find anyway to stream moonlight in SBS mode. I would really love this feature.

**Comment by jphein** [comment]
> Nothing officially in Moonlight, but VRidge does have support for using Moonlight as a streaming client. We're not associated with VRidge at all though.
> 
> https://riftcat.com/vridge

Riftcat does not allow you to use Moonlight with their Gamewarp service.  The service that allows you to play non VR games using SBS.

**Comment by zediiiii** [comment]
To implement SBS, you could use the existing Google Cardboard SDK for all the heavy lifting for the SBS implementation, IPD settings, and other device-specific measurements etc.

Other options for now

Tridef is dead as far as I know. Some people have found success on that route.

Trinus Cardboard does this passably well nowadays (not using moonlight), but it requires some fiddling or matching other people's setups to get the right lens distortion, ipd, zoom, etc for non-native SBS.
https://www.trinusvirtualreality.com/trinus-cardboard/
I get around 20-40 ms lag on my wireless AC router plugged in to my computer.

![image](https://user-images.githubusercontent.com/8075910/80054155-c1a8f080-84db-11ea-8fbe-b9b2a0ea35be.png)

**Comment by zediiiii** [comment]
I booted up the new Vridge stuff, and it seems they have a better implementation than Trinus nowadays. I didn't test latency, but for what it's worth, you can even play steam games without the gamewarp service in SBS in the big picture mode without launching steamVR.

**Comment by jphein** [comment]
> I booted up the new Vridge stuff, and it seems they have a better implementation than Trinus nowadays. I didn't test latency, but for what it's worth, you can even play steam games without the gamewarp service in SBS in the big picture mode.

How do you stream Steam games using Vridge in SBS mode without using Gamewarp?
Are you suing Vridge 2.0 or Classic?

**Comment by zediiiii** [comment]
@jphein You need Riftcat and steamVR installed on your desktop.

![image](https://user-images.githubusercontent.com/8075910/80057556-17819680-84e4-11ea-9266-9aa0313606a2.png)

Then just open steam and launch a steam native game, or launch the game through your steamVR room. That part is a bit finicky.

**Comment by jphein** [comment]
Vridge is great, but I'd really like to be able to use Moonlight for streaming in SBS mode. It's just so much better quality and performance than any other type of streaming I've tried.
