### ISSUE TITLE
Nvidia Shield stream freezes when above 50Mbits

### ISSUE THREAD

**Issue by ahnernoch** [moonlight-stream/moonlight-android#566]
Hello,

when I am using Gamestream set to 100mbit I can stream without any problems. No freezes, no artefacts. My connection is about 120mbit (Wifi). Checked with iPerf. When using Moonlight and set anything above 50mbit, in-game the stream is almost freezing.

Anybody can help me or has the same problem?

Thanks in advance....

**Comment by Alec123445** [comment]
I don't know why your setting the speed above 50Mbit. Anything above 30 for 1080p 60 is kinda overkill.

**Comment by ahnernoch** [comment]
So you saying there are no benifits in quality going over 30mbit when streaming 1080p? Even not when streaming in 264x only? I tried before already to find any information about this but could not find anything about it.

**Comment by Alec123445** [comment]
I find it imperceptible. 50 max really.
