### ISSUE TITLE
Xbox One Streaming with Moonlight

### ISSUE THREAD

**Issue by whiskeytangofx** [moonlight-stream/moonlight-android#567]
Hey guys,

Just wanted to ask a quick question before I drop $50 on an Xbox controller....

I have Moonlight set up and configured and it works rather well. My question is that if I connect a bluetooth Xbox One controller on the remote PC, would the Xbox app on my home PC recognize there's a controller present?  Does Moonlight pass that through back to the home PC?

I do have Moonlight configured to stream my home PC with what I remember to be some sort of usage of Microsoft's RDP app/protocol.

**EDIT** - My apologies if this should be in a different thread, but I am looking at doing this from either the Android variety of Moonlight or the Chrome variety, or both.

**Comment by Alec123445** [comment]
Yes it should work.

**Comment by whiskeytangofx** [comment]
Thanks!  While it worked for Steam and a couple of other apps, it doesn't seem to be working with mstsc.exe.

mstsc.exe seems to be unable to see the controller when streaming it through Moonlight.  I do have it connected through bluetooth on my Fire 10 HD tablet.

Some suggestions have been to update firmware on the controller (in the process of trying that) or plugging the controller in via USB.  Don't know if it's just my tablet, but when I use a USB OTG adapter to plug in the Xbox One controller, it causes my tablet to constantly reboot.

I'll do some more troubleshooting and post back.

**Comment by whiskeytangofx** [comment]
So, I changed some settings in Remote Desktop to allow pass-through to my home PC and I can move the mouse pointer around now and even "click" with the controller buttons, but the Xbox app doesn't recognize there being a controller hooked up.

I am just going to leave it at it might never work the way I want it to, but if anyone has any ideas feel free!  Thanks guys, this is a great app and a great community!

**Comment by Alec123445** [comment]
in moonlight settings on android. scroll down. there should be a setting for moonlight overrides android drivers and check it.

**Comment by whiskeytangofx** [comment]
I gave that a try as either checked or unchecked and it didn't seem to make a difference with my setup. I could launch the mstsc.exe app, it would show my desktop, I could start Xbox streaming with the controller, but would still get the message from the app saying there wasn't a controller connected to the PC.

I do have one of those wireless USB 360 adapters laying around at home.  I think I'm going to try plugging that in tonight to the desktop, try streaming again, and see if that makes a difference.  Enough of a trigger for the Xbox app to say "Yeah, you're good"

**Comment by whiskeytangofx** [comment]
Right now I have the following checked:

"Multiple controller support"
"Xbox 360/One controller driver"
"Override Android controller support"

**Comment by Alec123445** [comment]
Why would you want to. You can just stream the steam app through moonlight. It should show up as a game.

**Comment by whiskeytangofx** [comment]
Just to play my Xbox games on the go.  Seems Microsoft really locks it down and limits what you can use to control the console.  Don't think they want people playing shooters with mouse+KB against people with gamepads.

I was playing TF2 earlier with Steam and the controller on my tablet and it was surprisingly good. I mean, I was going up against guys with mouse+KB, so was getting stomped a couple of times!

**Comment by Alec123445** [comment]
ahh i see. Well i don't think that would work. If you could it would require quite a lot of janking. Heres an form post with people working on it. I havent read that far to see if they got it to work but here it is.
https://forums.geforce.com/default/topic/907230/gamestream/xbox-one-game-streaming-without-capture-card-to-shield-devices-/1/

**Comment by Alec123445** [comment]
https://forums.geforce.com/default/topic/907230/gamestream/xbox-one-game-streaming-without-capture-card-to-shield-devices-/post/4862353/#4862353

**Comment by Alec123445** [comment]
The second link is to the particular post in that forum thread that explains how to do it. Read that post and the next few and your should be able to do it.

**Comment by genmatrix** [comment]
Loading a game that uses a virtualized controller (like Destiny 2) then just never launching the game and switching to the Xbox app will allow to stream the Xbox from the Xbox app and the controller to work.
