### ISSUE TITLE
Mouse and keyboard button difficulties

### ISSUE THREAD

**Issue by samgalactic2** [moonlight-stream/moonlight-android#569]
Got oreo Moonlight to work with mouse and keyboard, but the keyboard input is being recognised as android input and the side/top mouse buttons don't work. I guess this is because the phone doesn't know how to interperet the input except as an android physical keyboard/mouse setup, but is there any way we can trick the phone into bypassing the input and sending all of it directly to the pc?

I altered the escape key layout to make that work properly on the pc (and not go back to the game selection screen on the phone) but the rest of the layout seems unable to be modified in this way.

**Comment by cgutman** [comment]
Not sure what you mean by "the keyboard input is being recognised as android input". Buttons other than Left/Middle/Right aren't supported by GameStream, so we don't send them.
