### ISSUE TITLE
RTSP Error 552 /Analys WireShark

### ISSUE THREAD

**Issue by iLeViiSxL** [moonlight-stream/moonlight-android#575]
Hello,

I wanted to install moonlight. So I activated the shield mode on my host computer, I opened the ports of my firewall and my internet box (UDP and TCP). I made myself on the client side to be on. I can see the list of my games but can not connect error RTSP 552,400 ...

I opened wireshark to scan the network and on both machines I see UDP packets and some TCP packet arrive on port 48010. But I still can not play.

If anyone could help me? thank you very much

**Comment by cgutman** [comment]
Can you upload logs from C:\ProgramData\NVIDIA Corporation\NvStream?
