### ISSUE TITLE
Can we adjust transparency and size of on-screen gamepad overlay?

### ISSUE THREAD

**Issue by Zuboskalik** [moonlight-stream/moonlight-android#576]
1. Can we make on-screen gamepad overlay transparent (%'s like most of the mobile emulators)? with Alpha close to 100% most of the games are almost unplayable bc of huge buttons on  the screen

2. Size? I can move element with config mode enabled, but they're change their size only when I move them to the bottom of screen - and revert back to "normal" size when I move them back

![Screenshot attached](https://user-images.githubusercontent.com/38207204/39547459-1df81cf6-4e71-11e8-8244-fdc095312bad.png)

**Comment by owenwalker92** [comment]
Multiple requests for this have been made.

Being able to modify scale/opacity of buttons would be great.

Even just being able to scale them from the left and top and not just the right and bottom sides of screen would be a huge improvement
