### ISSUE TITLE
No 5.1/Surround on NVIDIA Shield

### ISSUE THREAD

**Issue by MalhavocTheLich** [moonlight-stream/moonlight-android#577]
I know that there could be issues having 5.1 if you connect the Shield to the TV, and then the TV to the Audio Receiver, that's why I connected the Shield to the Receiver, and then to the TV.

Both Plex and Gamestreaming on Shield give me 5.1 audio this way. But Moonlight does not: it's not even plain stereo.. it gives me front, left, right, but no rear channels. And of course I enabled the 5.1 option in Moonlight.

Anybody else with this issue? Am I doing something wrong, or is there an issue with the current NVIDIA software (btw, both Shield and my NVIDIA drivers are up to date)?

**Comment by cgutman** [comment]
Which games have you tried?

**Comment by MalhavocTheLich** [comment]
Three things, all working in 5.1 using NVIDIA Gamestream:

- Witcher 3
- Remote Desktop, and opening a .mpg movie file with a 5.1 test video
- Steam Big Picture, and using its mini browser to go to this site and play the 5.1 audio test: https://www2.iis.fraunhofer.de/AAC/multichannel.html

As said, all the above work with NVIDIA Shield gamestreaming, but none works with Moonlight

**Comment by cgutman** [comment]
Ok, something definitely seems broken then. Does your receiver believe it's receiving a 5.1 signal when using Moonlight?

**Comment by MalhavocTheLich** [comment]
During streaming the audio is PCM, so it's hard to understand what my receiver believes it is, since with PCM it does not clearly states if it's 5.1 or what else.

Anyway, it seems like with the latest update the problem is no more. So, thread closed :)

**Comment by cgutman** [comment]
GFE 3.14 or a Moonlight update?

**Comment by MalhavocTheLich** [comment]
Did both, so I can't really guess which put things right, sorry

**Comment by cgutman** [comment]
Thanks, it was probably GFE 3.14. The Moonlight code for audio hasn't changed in a while.

**Comment by dongioia** [comment]
Hi, I have the same issue.
My setup is:
Server: laptop connected to my lan by wire, cpu intel core i7 7th gen, geforce gtx 1060 and the latest gaming drivers from nvidia.
Client: android box running lineage 16 android tv (android pie), connected by wire and audio output over hdmi connected to an AV receiver.
The android box is fully capable to output 5.1 or 7.1 audio streams (tested with kodi and vlc).
I checked the surround option in the moonlight config panel and enable dolby 5.1 output in my games, but still I got a stereo output.
Except this issue, the gaming experience is great.

**Comment by pogi1979** [comment]
Hi
I have the same issue.
When Nvidia Shield pro 2019 -> LG OLED GX -> 5.1 Harman Citation bar + Sub + surround satellites then I have 5.1 through Netflix, but haven't through Moonlight.
When Nvidia Shield pro 2019 -> 5.1 Harman Citation bar + Sub + surround satellites -> LG OLED GX then I have 5.1 dolby through Netflix and through Moonlight.

**Comment by cgutman** [comment]
The GameStream protocol supports transporting stereo, 5.1, and 7.1 LPCM surround sound. If your receiver/TV/soundbar requires Dolby Digital, AC3, or another non-LPCM format for surround sound, it will not work with Moonlight.
