### ISSUE TITLE
Android not showing gamestream PCs over internet

### ISSUE THREAD

**Issue by zarko-b** [moonlight-stream/moonlight-android#579]
Hi,
I have two PCs that have gamestream enabled that are on the same LAN. The android moonlight app shows them all fine and dandy when my android device is connected on the same LAN.

The problem is that I can't access one of them when I try to connect to them from outside of that LAN. I've port forwarded all the ports that are shown in this wiki https://github.com/moonlight-stream/moonlight-docs/wiki/Setup-Guide#streaming-over-the-internet for both the PCs.

If I have only one PC port forwarded and streaming, then it shows fine, but when I do the same for both of them only one shows as available.

What could be the cause of this problem?

Thanks.

**Comment by muffinmannameistaken** [comment]
As right now the latest version of geforce is broken you have to down grade to 10.0.30 to stream over internet.

**Comment by cgutman** [comment]
@muffinmannameistaken what gives you that idea? Latest GFE (3.13.1.30) works fine for streaming with Moonlight. Any issues are related to your particular setup.

**Comment by cgutman** [comment]
For the issue in this ticket, the limitation of port forwarding is that you can only forward each port once. If you read further on that page you cited, it mentions this restriction and using IPv6 to work around it.

If you have IPv6 available, I'd recommend that approach (I use it personally). Otherwise, you'll need to use a VPN to correct to your own home network remotely.

**Comment by muffinmannameistaken** [comment]
i keep getting error "RTSP failure" when trying to connect to my pc over the internet what works for me is just to down grade to 10.0.x.x i have no issues with it. Also my gaming pc is in a sub-network?(network with in a network) at home.

**Comment by cgutman** [comment]
@muffinmannameistaken make sure you added the new RTSP port 48010 **TCP** (old one was UDP) to your port forwarding configuration, firewall, etc.

**Comment by muffinmannameistaken** [comment]
unfortunately still not working I also rested my pc, Android studios does not like spaces in names :/ but 10.0.x still works and this is abit off track I can also get steam link to work over internet.( I use it as a usb hub for non rooted devices) my router is Netgear N300.
