### ISSUE TITLE
Automatically launch Steam when Limelight is started

### ISSUE THREAD

**Issue by SeeDborg** [moonlight-stream/moonlight-android#58]
Would it be possible to set a PC to automatically connect and launch Steam ?
I'd like to make a Steam Box out of an Ouya console !
Thanks.

**Comment by mrb113** [comment]
We don't have a guide for this and I don't entirely understand your scenario, but you may be able to play around with a scheduled task on a PC. 
https://msdn.microsoft.com/en-us/library/windows/desktop/aa383614(v=vs.85).aspx
