### ISSUE TITLE
Any patch for NVIDIA?

### ISSUE THREAD

**Issue by TheFinalHawk** [moonlight-stream/moonlight-android#581]
Currently, NVIDIA released a new driver update which completely screwed over the moonlight application. Anyone know when this will be fixed? Also, where can I keep up to date on when it gets patched?

**Comment by cgutman** [comment]
There are no known incompatibilities with the latest GFE (3.13.1.30) or the latest driver (397.64). I just streamed from my test box without any issues.

What versions are you running and what specific issue are you seeing?

**Comment by TheFinalHawk** [comment]
Sorry, for some reason it wouldnt detect my computer after the recent driver update. After uninstalling then reinstalling, it fixed the issue.
