### ISSUE TITLE
moonlight on Sony kd-xe65-9305 - Android TV - assassins creed syndicate does not start

### ISSUE THREAD

**Issue by rumplstielz** [moonlight-stream/moonlight-android#587]
Hello Girls/Guys,
first of all: great work so far!

Now to my problem:
I installed moonlight on my android TV. It detects my PC (gigabyte aourus nvidia 1080Ti ).
The games can be launched from the TV with the remote.
Then I discovered, that assassins creed syndicate won't launch.
The game is in uplay, but watchdogs, also in uplay, starts.

So I am at the end of my knowledge and hope you can help maybe? (Searched in Dr. Google since hours, tried different settings for the PC graphics (also single monitor setup, as I normally use dual monitor). Nothing helped.

br,
Kurt

**Comment by Jorys-Paulin** [comment]
@rumplstielz Do you get somewhat of a white screen on your host's screen?

**Comment by rumplstielz** [comment]
Thanks for the fast reply. Nothing. The host screen shows the same as the client screen: my desktop and the launching icon of assassins creed syndicate. As it does with other games: shows the desktop and then shows that the game is launching. But in this case: the assassins creed overlay logo just sits there and nothing happens. Do you need a screenshot?

**Comment by Jorys-Paulin** [comment]
@rumplstielz I had an issue with Steam streaming where the launch logo would disepear and open up a blank window with nothing else. Screenshot might help. Also check for file integrity on Steam/Uplay.

**Comment by rumplstielz** [comment]
I will attach a screenshot. Already checked the file integrity. The game just launches from uplay on the PC without any issue, but when starting with moonlight on the TV, the desktop appears, as it does with other games, the logo sits there and nothing happens. 
![ac_synd_moonlight_logo](https://user-images.githubusercontent.com/29253868/40838714-bc5a1b02-659f-11e8-909c-cf333edfecfc.jpg)

**Comment by Jorys-Paulin** [comment]
@rumplstielz Maybe it is related to that game only? Can you try with another AC game, see if it's the engine causing problems?

**Comment by Jorys-Paulin** [comment]
@rumplstielz I just tested on my own computer and phone, the game launches as expected, I just get disconnected for some reason...

**Comment by rumplstielz** [comment]
Just tried AC Origings, same picture...

**Comment by rumplstielz** [comment]
Also just tried with my tablet real quick: same picture...

**Comment by rumplstielz** [comment]
Are there any logs or whatever I can examine, so that I will come to the core of the problem? What I also discovered is, that as soon as I tried to launch the game with moonlight, then aborting the session (so that my PC comes back to "normal" desktop behaviour), the game won't launch from nvidia experience anymore. But this, IMHO, could also be, because there might be some processes hanging around still, but I do not know.

**Comment by Jorys-Paulin** [comment]
@rumplstielz Try launching it from steam, and steam pig picture, see if there's any difference between launching from GFE

**Comment by rumplstielz** [comment]
I will try... so I have to add it to steam, right?

**Comment by Jorys-Paulin** [comment]
@rumplstielz Just try to launch it another way as via GFE, to see if GFE is the problem.

**Comment by rumplstielz** [comment]
ok, trying to sum it up:
added C:\Program Files (x86)\Ubisoft\Ubisoft Game Launcher\games\Assassin's Creed Syndicate\ACS.exe to steam 
--> game started

added the same to GFE: 
--> same behaviour as before: logo there, no game.

added uplay game launcher to steam and started the game from there: 
--> same behaviour as before: logo there, no game.

When ending steam, I can not control it anymore with the controller, but I think this is because the uplay app launches after the game ends.

Strange...

I now have additional question: 
--> Will the game be displayed in 4k on my 4k TV with moonlight, if launched with steam in big picture mode?

**Comment by Jorys-Paulin** [comment]
@rumplstielz GFE overrides display settings, so I don't really know

**Comment by rumplstielz** [comment]
I mean, I can set it to 4k in the game settings though... but I am still curious, why the start of the game is not working from GFE...

**Comment by Jorys-Paulin** [comment]
@rumplstielz Maybe because it is launching directly without going through steam or Uplay...

**Comment by rumplstielz** [comment]
@Jorys-Paulin : maybe, but watchdogs also uses uplay to launch. But this works from GFE...

**Comment by Jorys-Paulin** [comment]
@rumplstielz So maybe it has to do with the engine...

**Comment by rumplstielz** [comment]
How can we get a clue, what caused it?

**Comment by Jorys-Paulin** [comment]
@rumplstielz I don't honestly know...

**Comment by castlenon** [comment]
Same here, AC Origins shows logo and won't start. Also, Batman Arkham Knight keep stuck on loading whenever I launch it from Moonlight...

**Comment by muffinmannameistaken** [comment]
if you are still having this problem or the games is not launching it's  because of latest Geforce it might be bugged, there has been posted about this a few time on there forums, i myself cannot get Overwatch to start. to fix this try downloading the older version of Geforce.
