### ISSUE TITLE
Stream not stretching to fit/fill full device screen (Samsung Galaxy S9+)

### ISSUE THREAD

**Issue by MKindy** [moonlight-stream/moonlight-android#588]
I'm attempting to stream my desktop (using the mstsc.exe trick) and, while it functions, leaving the display at 2560x1600 results in tiny screen elements that are entirely too hard to read.  I set down the resolution of my desktop to 1280x768, keeping the 16:10 ratio, and I set Moonlight's own settings to 720p30hz, but when I stream over Moonlight, the desktop just fills the upper quarter-ish of my screen (see attached screenshot).

Maybe I'm missing something obvious, but how can I remedy this, if at all?  I already tried setting the native resolution of the TouchWiz OS to 1440x720, but the problem persists (???).  The setting for "Stretch video to full-screen" is also enabled.

![moonlight-quarter-res](https://user-images.githubusercontent.com/1372854/40865029-f8a97230-65bb-11e8-9807-08c2daf820c6.png)

**Comment by muffinmannameistaken** [comment]
are you using nvidia control panel to change resolution? or windows?(right click and display settings).

**Comment by MKindy** [comment]
Awesome -- I had used the Windows control panel, but using the nVidia control panel caused the resolution to come through Moonlight properly!  Not only that, it let me set the resolution to 1480 x 720 to match the S9+'s bizarre 37:18 ratio.

Thanks!
