### ISSUE TITLE
Failed to start RTSP handshake

### ISSUE THREAD

**Issue by lynx31** [moonlight-stream/moonlight-android#589]
I can no longer connect to my PC via any android device running Moonlight, even over a local network (seems to be connected to the latest Geforce experience update). Getting the "failed to start RTSP handshake" error message every time. Happy to provide any longs required

Tried turning off windows defender (the only firewall that's being used) and reinstalling the latest GFE again

Update: A rollback to GFE 3.13 from 3.14 has removed the issue for me

**Comment by cgutman** [comment]
Yep, hopefully Nvidia can resolve this in a GFE update.
