### ISSUE TITLE
Disable Xinput from client possible? 

### ISSUE THREAD

**Issue by georgcmef** [moonlight-stream/moonlight-android#59]
Hello I use limelight on multiple platforms (Android, IOS and Pi). I connect my controller directly to my PC to play my games via limelight. Some games run into a problem where the emulated Xinput controller from limelight takes priority over every other controller that is connected to my computer, making them not function. 

I fixed one game from having this error by stopping \NVIDIA Corporation\NvStreamSrv\rxinput.dll from executing. This has not fixed the problem for any other of my games. Please help, Thank you

**Comment by cgutman** [comment]
There's no way to prevent the Xinput takeover since it happens on GFE's side without input from Moonlight. The rxinput.dll hack is the best we have.
