### ISSUE TITLE
RTSP Handshake Error 552

### ISSUE THREAD

**Issue by DemonICOLI** [moonlight-stream/moonlight-android#590]
Hey, 

I've this error when I try to start any game or app for stream, in both iOS and Android so far. 

Here is the Log File.

PD: Sorry for My English
PD2: I'm trying to do Streaming in my local network

[NvStreamerCurrent.log](https://github.com/moonlight-stream/moonlight-android/files/2065424/NvStreamerCurrent.log)

**Comment by lynx31** [comment]
Try rolling back to GFE 3.13 if you're on 3.14 currently

**Comment by DemonICOLI** [comment]
Can confirm that both 3.13.0.85 and 3.13.1.30 work, is an issue with 3.14.0.139

**Comment by acornwall** [comment]
The issue resolved itself for me by updating my GeForce Game Ready Driver to version 398.11 (the latest version at the time). I found this to be a better solution than downgrading to 3.13.1.30, because after a reboot, the GFE was forcing me to update back to 3.14.
