### ISSUE TITLE
PS4 Controller and Samsung Galaxy Tab A

### ISSUE THREAD

**Issue by Justintime2010** [moonlight-stream/moonlight-android#591]
Hello.

Just recently, I got myself a new tablet and I wanted to play my emulator games or other apps that are compatible with the PS4 Controller. I did the steps to connect the controller and was successful since it was paired as "Wireless Controller". However, for some reason the tablet is not responding to the controller buttons. The Text Input is enabled (it wouldn't connect if it wasn't), but it didn't fix anything. My previous tablet did not have this issue before.

For example, when I press left or right on the d-pad or joystick, an icon on screen should have been highlighted. If I am in a folder and I press X, it should take me back to the previous page. If I press Square, it opens up whatever icon I select.

None of this has worked. If anyone have a similar device model and have figured out the issue on how to get the controller to work, can you please let me know? I don't want to go back to using a keyboard again. :(

**Comment by Jorys-Paulin** [comment]
@Justintime2010 If the app doesn't have native controller support, then they could only emulate a mouse with the pad or joystick plus a button, that would work I guess, but it won't replace a proper mouse.

**Comment by thw0rted** [comment]
@Justintime2010 it doesn't sound like this is a Moonlight issue. If your controller won't register for the system level (navigating the home screen, etc) then you might have more luck solving the problem on android.stackexchange or XDA Forums.

**Comment by Justintime2010** [comment]
Well, I hope I can get a solution soon. I don't really want to be sent on a wild goose chase because of an issue like this. I mean, it's compatible since it is paired and the controller works because I tested it on my PlayStation. I just don't understand why the tablet isn't reacting to the buttons, not even when I play on MupenPlus 64 or Gameloft's Modern Combat.

**Comment by thw0rted** [comment]
Do you have another Bluetooth controller to test with?  Alternately, do you have a USB OTG adapter to plug in a wired controller?  If I were in your situation, I would try those things to see if it's particular to your device / OS.  Have you tried searching for your specific device model on the XDA forums to see if it's a known issue?

**Comment by Justintime2010** [comment]
@thw0rted 
I have tried using another PS4 Controller that I use mainly for my PlayStation and got the same results. I don't have a USB OTG Cable, unfortunately, and I seriously doubt there is one for my SM-T380 (that's the model number of the tablet) because it uses an entirely different cable to charge it than what my old tablet use. Here is the link to said cable: https://goo.gl/images/eEDrrU

**Comment by Justintime2010** [comment]
@thw0rted 

I have tried it with my new PS4 Controller that I use mainly for my PlayStation and got the same results. I don't have a USB OTG Cable and I doubt they would have one specifically for my SM-T380 because my tablet uses an entirely different cable to charge it instead of the ones I had for my old one. Here is the link to the new cable: https://goo.gl/images/eEDrrU

I did go on the XDA Forums and I have not found any threads on this problem. Either I'm not looking hard enough, or no-one has made a post about it yet.

**Comment by thw0rted** [comment]
It sounds like your tablet has a standard USB-C port, so an OTG cable like [the first hit when I googled "usb-c otg"](https://www.amazon.com/ELUCTO-Adapter-Macbook-Samsung-Motorola/dp/B00ZWN64RS) should work as long as the device supports OTG, which [this random page](http://phonedb.net/index.php?m=device&id=12463&c=samsung_sm-t380_galaxy_tab_a_8.0_2017_wifi__galaxy_tab_a2_8.0__samsung_t380) says it does.  Do you have a USB controller to try it with?  You could use the USB connection on the Dualshock 4 but if I were you I'd prefer to test a "normal" USB HID controller.

**Comment by Justintime2010** [comment]
@thw0rted 

I don't, sorry.
