### ISSUE TITLE
Tablet status bar and soft key navigation bar removal?

### ISSUE THREAD

**Issue by upwn** [moonlight-stream/moonlight-android#592]
I recently purchased an 10" android 7.1 tablet so that I could use moonlight and gamestream. I try to stream FPS games to my tablet and when I try to look up or down using my mouse the mouse reaches the top or bottom of the tablet screen, and often I click the back button accidentally and drop connection. 

I am using an Acer Iconia one b3 a40fhd. I have scoured the internet looking for solutions and some of them have pay walls, or involve rooting. I have tried a couple of solutions and they only hide the nav bar. When moving the mouse over it it still appears and interupts gameplay. 

So hopefully you know what i'm talking about. I'd love to get this working. Need to adios that nav bar. Can anyone help?

**Comment by cgutman** [comment]
This is a limitation of Android prior to 8.0. There's no way to lock the mouse visit cursor without root access.

**Comment by upwn** [comment]
I have been told rooting will void my warranty and return eligibility. I just got this acer tablet and there's a 90 day return window. Looks like the Iconia b3 a40 won't be receiving an Oreo update.

So if I return my device and get something that has or will recieve an Oreo upgrade (like the Samsung tab S3) then this up/down limitation can be solved by locking the mouse visit cursor? I don't know what that means yet. Is that easy to do with Oreo?



On Jun 10, 2018 9:15 PM, Cameron Gutman <notifications@github.com> wrote:

This is a limitation of Android prior to 8.0. There's no way to lock the mouse visit cursor without root access.

**Comment by cgutman** [comment]
Yes, if you get a tablet running Oreo, mouse pointer capture will just work automatically without any additional steps.
