### ISSUE TITLE
Can not stream if monitor if off

### ISSUE THREAD

**Issue by Emdrag13** [moonlight-stream/moonlight-android#593]
I got moonlight set up with the latest GeForce software and driver update and using it on my S8 but when trying to stream over the internet/or my own via wifi the screen will be black because my monitor display is off. When the monitor display is on I see my desktop with no issue.

If I get on the stream while the monitor off it will be black then  I turn the monitor on it will display connection issue but if I reconnect I see my desktop no issue. If I am on my desktop and I turn my display off it will disconnect with connection error, getting back into the stream (Monitor display still off) I would get that black screen again on my phone.

Conclusion: Can not stream unless the monitor display is on
How can I fix this cause it kills the purpose of remote streaming if my monitor has to be on and I'm trying to play games away from home? (let's be eco-friendly)

Ps more flexibility on the touchpad controls please moonlight devs if your reading this
thank you

**Comment by Emdrag13** [comment]
Can I save myself 10$ lol and change the window registry or something to stop preventing Window from cutting the feed for moonlight when the monitor off I mean like other streaming apps like Remotr work perfectly but moonlight has better streaming so I want to keep using it. If not I guess I'll look up video on how this dummy display works

**Comment by graffic** [comment]
So I found the following software solution for headless streaming.

I installed Chrome Remote Desktop https://remotedesktop.google.com/ and connected to my computer. Then I start Moonlight and everything works.
