### ISSUE TITLE
Mapping controls

### ISSUE THREAD

**Issue by minnux** [moonlight-stream/moonlight-android#594]
I'd like to play some keyboard only games streaming from my pc to my phone, is there a way to map the moonlight controls to keyboard keys?

**Comment by thw0rted** [comment]
I haven't tried it but if you use Moonlight to launch Steam in Big Picture Mode, under Settings -> Controllers, there's an option to enable key remapping for Xbox controllers (which is what Moonlight emulates).  Then, you could place a control for e.g. the "A" button on the touchscreen, and map the "A" button in Steam to the space bar (or whatever) in your game.  I believe it uses the same interface they developed for Steam Controllers.

(If you try this, let me know how it goes!)

**Comment by minnux** [comment]
Ok it works. I guess that solves it then.
