### ISSUE TITLE
AC Origins and FFXV not working

### ISSUE THREAD

**Issue by Musashi87** [moonlight-stream/moonlight-android#595]
So here is my problem.

If i try to start AC Origins over any Device (Laptop,Shield Tablet, S7) i get stuck on the loading splash art and nothing happens.

When i start FFXV i just get a black screen and nothing happens aswell.

The only difference is. If i start ac origins on my pc then start it with moonlight i can access it, but if i try the same with FFXV the screen goes grey immediatly, anyone got a idea or encountered something similar?

Thank you for your time

System 4790k with 1080 ti

**Comment by cgutman** [comment]
This is a known issue with GeForce Experience 3.14 - https://forums.geforce.com/default/topic/1054993/gamestream/assassins-creed-origins-gfe-3-14-0-132-stopped-working/

**Comment by Musashi87** [comment]
It fixed both of them, crazy that they didnt fix it yet on the new one. Thanks alot!
