### ISSUE TITLE
Gamepad no longer recognized in Steam Big Picture only

### ISSUE THREAD

**Issue by Rutjan666** [moonlight-stream/moonlight-android#596]
Hello,

I've been enjoying Moonlight for a few months now, and all worked pretty well.

But lately, I've noticed my bluetooth gamepad (ipega PG-9023) no longer works in Steam Big Picture, while it used to work fine in the beginning (no issue with the games, though).
I guess it could be related to Steam itself, but I've tested the new steamlink app and the gamepad works fine in SBP.

I've tried fiddling with the options both in moonlight and steam but ineffectively.

Has anyone encountered this issue?

**Comment by Jorys-Paulin** [comment]
@Rutjan666 Someone else got an issue with his controller. Turned out it was GeForce Experience that updated and killed the support. Might be a bug though.

**Comment by Rutjan666** [comment]
Oh damn, thanks for the feedback.

Doesn't prevent from playing but using the touchscreen for mouse emulation in BP is kind of a hassle.
