### ISSUE TITLE
why is it that streaming is more jittery on 2.4gHz?

### ISSUE THREAD

**Issue by 19clarnoah** [moonlight-stream/moonlight-android#597]
My host is connected to 802.11ac 5gHz wifi that consistently has 200mbps up and down. when my tablet (samsung galaxy tab s3) is on 5G from anywhere, the performance is rock solid with no issues whatsoever. however, even though my mom's 2.4gHz is fast (between 55 and 100 mbps usually), the stream stutters constantly or just totally freezes up. my mom's house is a remote location, about 40 miles from my host. she has 5G and it works just fine, but i'm just wondering, why is the 2.4gHz so unstable? is there any way i can tweak the settings, be it bitrate, resolution, etc to make 2.4 performance solid? i ask this because i know a lot of hotels and condos have 2.4g only.

**Comment by Zod20** [comment]
2.4 Ghz is used by a lot more other services than just wifi such as cellular signal etc. So you have a lot of inference with these other signals causing jittery lag that you noticed. 5 Ghz is not used by many other services (disadvantage is the range is shorter than 2.4 Ghz and it gets blocked more easily by walls/doors) so it is smoother.

**Comment by nk33** [comment]
Hi,

Are you using a Bluetooth controller? 

if so then this is the reason. Most devices have Wifi and BT on same card - not only that BT also works on 2.4ghz - I bet if you play the game with on-screen controls (just for testing) you will see there is little to no lag.

try it and let me know
