### ISSUE TITLE
Failed to start RTSP Handshake over mobile data. Game starts on Host though.

### ISSUE THREAD

**Issue by Musashi87** [moonlight-stream/moonlight-android#598]
Hi i opened all ports with pftest enable tool and can stream over wifi without issues but when i try to start a game over the mobile connection the error failed to start RTSP Handshake comes up, wierdly enough the game still launches on my pc. I try to stream from a 1080 ti to a samsung s7.

**Comment by MagFlux** [comment]
Looks to be related to #528, just thought I'd link the two for convenience.

**Comment by cgutman** [comment]
Duplicate of #528
