### ISSUE TITLE
Ask and suggest some questions about the physical vibration of the game controller and the virtual buttons of the Android version

### ISSUE THREAD

**Issue by shinobiz** [moonlight-stream/moonlight-android#604]
Hello! My English is not good, please bear with me.

Let me talk about the problem of the game controller:
1: When can moonlight stream support game controller vibration? NVIDIA Shield is OK, so there is no problem on the hardware, it should be a problem on the software and the driver.

2.moonlight stream controller does not support some games, some games do not respond. The reason is that he will virtualize a game controller and become P1! That is, you will see 2 controllers in steam, and the game controller that moonlight virtualizes becomes P2! Can refer to the steam link app program, I think that is good!

Let's talk about the virtual button problem:
1. First, the skin of the virtual key is a bit ugly and the setting is not reasonable, and the control is not convenient.

2. Whether you can customize the skin, or provide multiple skin solutions, personally prefer the skin of the PlayStation controller, you can refer to the epsxe skin of the Android version, you can switch the number / analog or both coexist

3. The skin can customize the transparency, color, size, position, and whether to display a button

Come on! good luck!

**Comment by cgutman** [comment]
1. GameStream does support vibration, but we haven't yet implemented that functionality in Moonlight.

2. Do you have a gamepad attached to your gaming PC? Is that one becoming P1?

3. Yep, the on screen control UI is ugly. Adding extra customization options like you've described would help, but I haven't had time to do it.
