### ISSUE TITLE
Forum URL ? Request feature

### ISSUE THREAD

**Issue by magadan** [moonlight-stream/moonlight-android#609]
Hello, im looking for a users forum.

I need to have a MoonLight Server that not depends of GFE to stream desktop.

Its not possible to stream the desktop with ffmpeg or other stream encoder package, and make a fake GFE Service to Moonlight Client ???

thank you

**Comment by thw0rted** [comment]
I don't think a GameStream open-source server exists yet.  There are plenty of other desktop-streaming servers with mobile clients you could use... is there any particular reason you want GameStream / GFE in particular?
