### ISSUE TITLE
Cannot Pair after GeForce update to 2.3.10.17

### ISSUE THREAD

**Issue by krusic22** [moonlight-stream/moonlight-android#61]
I think they broke it with a now account thing.

**Comment by cgutman** [comment]
I just tested it with my machine and was able to pair Limelight Android 3.1.2 with GFE 2.3.10.17. What error are you getting?

**Comment by krusic22** [comment]
I dont get a popup on my pc and the deivce sayes Failed to pair

**Comment by cgutman** [comment]
Try accessing http://127.0.0.1:47989/serverinfo on your GFE PC. It should show some XML if it's working properly. If you do get XML, can you collect a logcat log of you trying to pair? It might have enough details to figure out what's happening. If it doesn't, I'll give you one with debugging enabled on the HTTP requests.

**Comment by krusic22** [comment]
03-07 22:51:02.874: I/com.limelight.LimeLog(10225): Starting fast poll for RA�UNALNIK-PC (/192.168.2.175, /193.77.xx.xxx)
03-07 22:51:02.924: I/com.limelight.LimeLog(10225): Fast poll for RA�UNALNIK-PC returned LOCAL
03-07 22:51:05.815: I/com.limelight.LimeLog(10225): mDNS: Machine appeared: RAȕNALNIK-PC
03-07 22:51:05.826: I/com.limelight.LimeLog(10225): mDNS: Machine resolved: RAȕNALNIK-PC
03-07 22:51:06.060: I/com.limelight.LimeLog(10225): Starting fast poll for RA�UNALNIK-PC (/192.168.2.175, /193.77.xx.xxx)
03-07 22:51:06.081: I/com.limelight.LimeLog(10225): Fast poll for RA�UNALNIK-PC returned LOCAL
03-07 22:51:09.247: I/com.limelight.LimeLog(10225): Starting fast poll for RA�UNALNIK-PC (/192.168.2.175, /193.77.xx.xxx)
03-07 22:51:09.281: I/com.limelight.LimeLog(10225): Fast poll for RA�UNALNIK-PC returned LOCAL
03-07 22:51:12.449: I/com.limelight.LimeLog(10225): Starting fast poll for RA�UNALNIK-PC (/192.168.2.175, /193.77.xx.xxx)
03-07 22:51:12.474: I/com.limelight.LimeLog(10225): Fast poll for RA�UNALNIK-PC returned LOCAL
03-07 22:51:15.611: I/com.limelight.LimeLog(10225): Starting fast poll for RA�UNALNIK-PC (/192.168.2.175, /193.77.xx.xxx)
03-07 22:51:15.637: I/com.limelight.LimeLog(10225): Fast poll for RA�UNALNIK-PC returned LOCAL
03-07 22:51:16.885: I/com.limelight.LimeLog(10225): mDNS: Machine appeared: RAȕNALNIK-PC
03-07 22:51:16.891: I/com.limelight.LimeLog(10225): mDNS: Machine resolved: RAȕNALNIK-PC
03-07 22:51:18.770: I/com.limelight.LimeLog(10225): Starting fast poll for RA�UNALNIK-PC (/192.168.2.175, /193.77.xx.xxx)
03-07 22:51:18.795: I/com.limelight.LimeLog(10225): Fast poll for RA�UNALNIK-PC returned LOCAL
03-07 22:51:21.971: I/com.limelight.LimeLog(10225): Starting fast poll for RA�UNALNIK-PC (/192.168.2.175, /193.77.xx.xxx)
03-07 22:51:21.997: I/com.limelight.LimeLog(10225): Fast poll for RA�UNALNIK-PC returned LOCAL
03-07 22:51:25.145: I/com.limelight.LimeLog(10225): Starting fast poll for RA�UNALNIK-PC (/192.168.2.175, /193.77.xx.xxx)
03-07 22:51:25.173: I/com.limelight.LimeLog(10225): Fast poll for RA�UNALNIK-PC returned LOCAL
03-07 22:51:27.321: I/com.limelight.LimeLog(10225): mDNS: Machine appeared: RAȕNALNIK-PC
03-07 22:51:27.327: I/com.limelight.LimeLog(10225): mDNS: Machine resolved: RAȕNALNIK-PC
03-07 22:51:28.347: I/com.limelight.LimeLog(10225): Starting fast poll for RA�UNALNIK-PC (/192.168.2.175, /193.77.xx.xxx)
03-07 22:51:28.382: I/com.limelight.LimeLog(10225): Fast poll for RA�UNALNIK-PC returned LOCAL
03-07 22:51:31.539: I/com.limelight.LimeLog(10225): Starting fast poll for RA�UNALNIK-PC (/192.168.2.175, /193.77.xx.xxx)
03-07 22:51:31.574: I/com.limelight.LimeLog(10225): Fast poll for RA�UNALNIK-PC returned LOCAL
03-07 22:51:34.769: I/com.limelight.LimeLog(10225): Starting fast poll for RA�UNALNIK-PC (/192.168.2.175, /193.77.xx.xxx)
03-07 22:51:34.797: I/com.limelight.LimeLog(10225): Fast poll for RA�UNALNIK-PC returned LOCAL
03-07 22:51:37.464: I/com.limelight.LimeLog(10225): mDNS: Machine appeared: RAȕNALNIK-PC
03-07 22:51:37.469: I/com.limelight.LimeLog(10225): mDNS: Machine resolved: RAȕNALNIK-PC
03-07 22:51:37.965: I/com.limelight.LimeLog(10225): Starting fast poll for RA�UNALNIK-PC (/192.168.2.175, /193.77.xx.xxx)
03-07 22:51:38.032: I/com.limelight.LimeLog(10225): Fast poll for RA�UNALNIK-PC returned LOCAL
03-07 22:51:50.224: I/com.limelight.LimeLog(10225): Starting fast poll for RA�UNALNIK-PC (/192.168.2.175, /193.77.xx.xxx)
03-07 22:51:50.262: I/com.limelight.LimeLog(10225): Fast poll for RA�UNALNIK-PC returned LOCAL
03-07 22:51:50.688: I/com.limelight.LimeLog(10225): mDNS: Machine appeared: RAȕNALNIK-PC
03-07 22:51:50.692: I/com.limelight.LimeLog(10225): mDNS: Machine resolved: RAȕNALNIK-PC
03-07 22:51:53.361: I/com.limelight.LimeLog(10225): Starting fast poll for RA�UNALNIK-PC (/192.168.2.175, /193.77.xx.xxx)
03-07 22:51:53.382: I/com.limelight.LimeLog(10225): Fast poll for RA�UNALNIK-PC returned LOCAL
03-07 22:51:56.559: I/com.limelight.LimeLog(10225): Starting fast poll for RA�UNALNIK-PC (/192.168.2.175, /193.77.xx.xxx)
03-07 22:51:56.592: I/com.limelight.LimeLog(10225): Fast poll for RA�UNALNIK-PC returned LOCAL
03-07 22:51:59.777: I/com.limelight.LimeLog(10225): Starting fast poll for RA�UNALNIK-PC (/192.168.2.175, /193.77.xx.xxx)
03-07 22:51:59.806: I/com.limelight.LimeLog(10225): Fast poll for RA�UNALNIK-PC returned LOCAL
03-07 22:52:02.042: I/com.limelight.LimeLog(10225): mDNS: Machine appeared: RAȕNALNIK-PC
03-07 22:52:02.052: I/com.limelight.LimeLog(10225): mDNS: Machine resolved: RAȕNALNIK-PC
03-07 22:52:02.961: I/com.limelight.LimeLog(10225): Starting fast poll for RA�UNALNIK-PC (/192.168.2.175, /193.77.xx.xxx)
03-07 22:52:03.000: I/com.limelight.LimeLog(10225): Fast poll for RA�UNALNIK-PC returned LOCAL
03-07 22:52:06.216: I/com.limelight.LimeLog(10225): Starting fast poll for RA�UNALNIK-PC (/192.168.2.175, /193.77.xx.xxx)
03-07 22:52:06.234: I/com.limelight.LimeLog(10225): Fast poll for RA�UNALNIK-PC returned LOCAL
03-07 22:52:09.417: I/com.limelight.LimeLog(10225): Starting fast poll for RA�UNALNIK-PC (/192.168.2.175, /193.77.xx.xxx)
03-07 22:52:09.447: I/com.limelight.LimeLog(10225): Fast poll for RA�UNALNIK-PC returned LOCAL
03-07 22:52:12.187: I/com.limelight.LimeLog(10225): mDNS: Machine appeared: RAȕNALNIK-PC
03-07 22:52:12.204: I/com.limelight.LimeLog(10225): mDNS: Machine resolved: RAȕNALNIK-PC
03-07 22:52:12.640: I/com.limelight.LimeLog(10225): Starting fast poll for RA�UNALNIK-PC (/192.168.2.175, /193.77.xx.xxx)
03-07 22:52:12.672: I/com.limelight.LimeLog(10225): Fast poll for RA�UNALNIK-PC returned LOCAL
03-07 22:52:15.840: I/com.limelight.LimeLog(10225): Starting fast poll for RA�UNALNIK-PC (/192.168.2.175, /193.77.xx.xxx)
03-07 22:52:15.862: I/com.limelight.LimeLog(10225): Fast poll for RA�UNALNIK-PC returned LOCAL
03-07 22:52:19.129: I/com.limelight.LimeLog(10225): Starting fast poll for RA�UNALNIK-PC (/192.168.2.175, /193.77.xx.xxx)
03-07 22:52:19.163: I/com.limelight.LimeLog(10225): Fast poll for RA�UNALNIK-PC returned LOCAL
03-07 22:52:22.298: I/com.limelight.LimeLog(10225): Starting fast poll for RA�UNALNIK-PC (/192.168.2.175, /193.77.xx.xxx)
03-07 22:52:22.329: I/com.limelight.LimeLog(10225): Fast poll for RA�UNALNIK-PC returned LOCAL
03-07 22:52:23.537: I/com.limelight.LimeLog(10225): mDNS: Machine appeared: RAȕNALNIK-PC
03-07 22:52:25.494: I/com.limelight.LimeLog(10225): Starting fast poll for RA�UNALNIK-PC (/192.168.2.175, /193.77.xx.xxx)
03-07 22:52:25.527: I/com.limelight.LimeLog(10225): Fast poll for RA�UNALNIK-PC returned LOCAL
03-07 22:52:28.147: I/com.limelight.LimeLog(10225): mDNS: Retrying service resolution for machine: RAȕNALNIK-PC
03-07 22:52:28.153: I/com.limelight.LimeLog(10225): mDNS: Machine resolved: RAȕNALNIK-PC
03-07 22:52:28.723: I/com.limelight.LimeLog(10225): Starting fast poll for RA�UNALNIK-PC (/192.168.2.175, /193.77.xx.xxx)
03-07 22:52:28.759: I/com.limelight.LimeLog(10225): Fast poll for RA�UNALNIK-PC returned LOCAL
03-07 22:52:31.942: I/com.limelight.LimeLog(10225): Starting fast poll for RA�UNALNIK-PC (/192.168.2.175, /193.77.xx.xxx)
03-07 22:52:31.979: I/com.limelight.LimeLog(10225): Fast poll for RA�UNALNIK-PC returned LOCAL
03-07 22:52:34.601: I/com.limelight.LimeLog(10225): mDNS: Machine appeared: RAȕNALNIK-PC
03-07 22:52:34.608: I/com.limelight.LimeLog(10225): mDNS: Machine resolved: RAȕNALNIK-PC
03-07 22:52:35.173: I/com.limelight.LimeLog(10225): Starting fast poll for RA�UNALNIK-PC (/192.168.2.175, /193.77.xx.xxx)
03-07 22:52:35.205: I/com.limelight.LimeLog(10225): Fast poll for RA�UNALNIK-PC returned LOCAL
03-07 22:52:38.349: I/com.limelight.LimeLog(10225): Starting fast poll for RA�UNALNIK-PC (/192.168.2.175, /193.77.xx.xxx)
03-07 22:52:38.369: I/com.limelight.LimeLog(10225): Fast poll for RA�UNALNIK-PC returned LOCAL
03-07 22:52:41.578: I/com.limelight.LimeLog(10225): Starting fast poll for RA�UNALNIK-PC (/192.168.2.175, /193.77.xx.xxx)
03-07 22:52:41.606: I/com.limelight.LimeLog(10225): Fast poll for RA�UNALNIK-PC returned LOCAL
03-07 22:52:44.759: I/com.limelight.LimeLog(10225): Starting fast poll for RA�UNALNIK-PC (/192.168.2.175, /193.77.xx.xxx)
03-07 22:52:44.793: I/com.limelight.LimeLog(10225): Fast poll for RA�UNALNIK-PC returned LOCAL
03-07 22:52:45.966: I/com.limelight.LimeLog(10225): mDNS: Machine appeared: RAȕNALNIK-PC
03-07 22:52:45.972: I/com.limelight.LimeLog(10225): mDNS: Machine resolved: RAȕNALNIK-PC
03-07 22:52:48.017: I/com.limelight.LimeLog(10225): Starting fast poll for RA�UNALNIK-PC (/192.168.2.175, /193.77.xx.xxx)
03-07 22:52:48.051: I/com.limelight.LimeLog(10225): Fast poll for RA�UNALNIK-PC returned LOCAL
03-07 22:52:51.211: I/com.limelight.LimeLog(10225): Starting fast poll for RA�UNALNIK-PC (/192.168.2.175, /193.77.xx.xxx)
03-07 22:52:51.240: I/com.limelight.LimeLog(10225): Fast poll for RA�UNALNIK-PC returned LOCAL
03-07 22:52:54.395: I/com.limelight.LimeLog(10225): Starting fast poll for RA�UNALNIK-PC (/192.168.2.175, /193.77.xx.xxx)
03-07 22:52:54.442: I/com.limelight.LimeLog(10225): Fast poll for RA�UNALNIK-PC returned LOCAL
03-07 22:52:57.034: I/com.limelight.LimeLog(10225): mDNS: Machine appeared: RAȕNALNIK-PC
03-07 22:52:57.639: I/com.limelight.LimeLog(10225): Starting fast poll for RA�UNALNIK-PC (/192.168.2.175, /193.77.xx.xxx)
03-07 22:52:57.660: I/com.limelight.LimeLog(10225): Fast poll for RA�UNALNIK-PC returned LOCAL
03-07 22:53:00.868: I/com.limelight.LimeLog(10225): Starting fast poll for RA�UNALNIK-PC (/192.168.2.175, /193.77.xx.xxx)
03-07 22:53:00.894: I/com.limelight.LimeLog(10225): Fast poll for RA�UNALNIK-PC returned LOCAL
03-07 22:53:01.851: I/com.limelight.LimeLog(10225): mDNS: Retrying service resolution for machine: RAȕNALNIK-PC
03-07 22:53:01.855: I/com.limelight.LimeLog(10225): mDNS: Machine resolved: RAȕNALNIK-PC
03-07 22:53:04.179: I/com.limelight.LimeLog(10225): Starting fast poll for RA�UNALNIK-PC (/192.168.2.175, /193.77.xx.xxx)
03-07 22:53:04.204: I/com.limelight.LimeLog(10225): Fast poll for RA�UNALNIK-PC returned LOCAL
03-07 22:53:07.345: I/com.limelight.LimeLog(10225): Starting fast poll for RA�UNALNIK-PC (/192.168.2.175, /193.77.xx.xxx)
03-07 22:53:07.368: I/com.limelight.LimeLog(10225): Fast poll for RA�UNALNIK-PC returned LOCAL
03-07 22:53:07.475: I/com.limelight.LimeLog(10225): mDNS: Machine appeared: RAȕNALNIK-PC
03-07 22:53:07.481: I/com.limelight.LimeLog(10225): mDNS: Machine resolved: RAȕNALNIK-PC
03-07 22:53:10.545: I/com.limelight.LimeLog(10225): Starting fast poll for RA�UNALNIK-PC (/192.168.2.175, /193.77.xx.xxx)
03-07 22:53:10.580: I/com.limelight.LimeLog(10225): Fast poll for RA�UNALNIK-PC returned LOCAL
03-07 22:53:13.733: I/com.limelight.LimeLog(10225): Starting fast poll for RA�UNALNIK-PC (/192.168.2.175, /193.77.xx.xxx)
03-07 22:53:13.768: I/com.limelight.LimeLog(10225): Fast poll for RA�UNALNIK-PC returned LOCAL
03-07 22:53:16.978: I/com.limelight.LimeLog(10225): Starting fast poll for RA�UNALNIK-PC (/192.168.2.175, /193.77.xx.xxx)
03-07 22:53:17.007: I/com.limelight.LimeLog(10225): Fast poll for RA�UNALNIK-PC returned LOCAL
03-07 22:53:18.540: I/com.limelight.LimeLog(10225): mDNS: Machine appeared: RAȕNALNIK-PC
03-07 22:53:18.552: I/com.limelight.LimeLog(10225): mDNS: Machine resolved: RAȕNALNIK-PC
03-07 22:53:20.171: I/com.limelight.LimeLog(10225): Starting fast poll for RA�UNALNIK-PC (/192.168.2.175, /193.77.xx.xxx)
03-07 22:53:20.197: I/com.limelight.LimeLog(10225): Fast poll for RA�UNALNIK-PC returned LOCAL
03-07 22:53:23.352: I/com.limelight.LimeLog(10225): Starting fast poll for RA�UNALNIK-PC (/192.168.2.175, /193.77.xx.xxx)
03-07 22:53:23.385: I/com.limelight.LimeLog(10225): Fast poll for RA�UNALNIK-PC returned LOCAL
03-07 22:53:26.528: I/com.limelight.LimeLog(10225): Starting fast poll for RA�UNALNIK-PC (/192.168.2.175, /193.77.xx.xxx)
03-07 22:53:26.565: I/com.limelight.LimeLog(10225): Fast poll for RA�UNALNIK-PC returned LOCAL
03-07 22:53:29.743: I/com.limelight.LimeLog(10225): Starting fast poll for RA�UNALNIK-PC (/192.168.2.175, /193.77.xx.xxx)
03-07 22:53:29.779: I/com.limelight.LimeLog(10225): Fast poll for RA�UNALNIK-PC returned LOCAL
03-07 22:53:29.900: I/com.limelight.LimeLog(10225): mDNS: Machine appeared: RAȕNALNIK-PC
03-07 22:53:29.903: I/com.limelight.LimeLog(10225): mDNS: Machine resolved: RAȕNALNIK-PC
03-07 22:53:32.981: I/com.limelight.LimeLog(10225): Starting fast poll for RA�UNALNIK-PC (/192.168.2.175, /193.77.xx.xxx)
03-07 22:53:33.013: I/com.limelight.LimeLog(10225): Fast poll for RA�UNALNIK-PC returned LOCAL
03-07 22:53:36.203: I/com.limelight.LimeLog(10225): Starting fast poll for RA�UNALNIK-PC (/192.168.2.175, /193.77.xx.xxx)
03-07 22:53:36.242: I/com.limelight.LimeLog(10225): Fast poll for RA�UNALNIK-PC returned LOCAL
03-07 22:53:39.427: I/com.limelight.LimeLog(10225): Starting fast poll for RA�UNALNIK-PC (/192.168.2.175, /193.77.xx.xxx)
03-07 22:53:39.459: I/com.limelight.LimeLog(10225): Fast poll for RA�UNALNIK-PC returned LOCAL
03-07 22:53:42.620: I/com.limelight.LimeLog(10225): Starting fast poll for RA�UNALNIK-PC (/192.168.2.175, /193.77.xx.xxx)
03-07 22:53:42.692: I/com.limelight.LimeLog(10225): Fast poll for RA�UNALNIK-PC returned LOCAL
03-07 22:53:46.141: I/com.limelight.LimeLog(10225): Starting fast poll for RA�UNALNIK-PC (/192.168.2.175, /193.77.xx.xxx)
03-07 22:53:46.170: I/com.limelight.LimeLog(10225): Fast poll for RA�UNALNIK-PC returned LOCAL
03-07 22:53:49.362: I/com.limelight.LimeLog(10225): Starting fast poll for RA�UNALNIK-PC (/192.168.2.175, /193.77.xx.xxx)
03-07 22:53:49.387: I/com.limelight.LimeLog(10225): Fast poll for RA�UNALNIK-PC returned LOCAL
03-07 22:53:52.538: I/com.limelight.LimeLog(10225): Starting fast poll for RA�UNALNIK-PC (/192.168.2.175, /193.77.xx.xxx)
03-07 22:53:52.563: I/com.limelight.LimeLog(10225): Fast poll for RA�UNALNIK-PC returned LOCAL
03-07 22:53:53.241: I/com.limelight.LimeLog(10225): mDNS: Machine appeared: RAȕNALNIK-PC
03-07 22:53:53.250: I/com.limelight.LimeLog(10225): mDNS: Machine resolved: RAȕNALNIK-PC
03-07 22:53:59.375: I/com.limelight.LimeLog(10225): Starting fast poll for RA�UNALNIK-PC (/192.168.2.175, /193.77.xx.xxx)
03-07 22:53:59.432: I/com.limelight.LimeLog(10225): Fast poll for RA�UNALNIK-PC returned LOCAL
03-07 22:53:59.435: I/Timeline(10225): Timeline: Activity_idle id: android.os.BinderProxy@986b0b8 time:59126369
03-07 22:54:02.653: I/com.limelight.LimeLog(10225): Starting fast poll for RA�UNALNIK-PC (/192.168.2.175, /193.77.xx.xxx)
03-07 22:54:02.677: I/com.limelight.LimeLog(10225): Fast poll for RA�UNALNIK-PC returned LOCAL
03-07 22:54:04.609: I/com.limelight.LimeLog(10225): mDNS: Machine appeared: RAȕNALNIK-PC
03-07 22:54:04.619: I/com.limelight.LimeLog(10225): mDNS: Machine resolved: RAȕNALNIK-PC
03-07 22:54:05.785: I/com.limelight.LimeLog(10225): Starting fast poll for RA�UNALNIK-PC (/192.168.2.175, /193.77.xx.xxx)
03-07 22:54:05.812: I/com.limelight.LimeLog(10225): Fast poll for RA�UNALNIK-PC returned LOCAL
03-07 22:54:08.956: I/com.limelight.LimeLog(10225): Starting fast poll for RA�UNALNIK-PC (/192.168.2.175, /193.77.xx.xxx)
03-07 22:54:08.982: I/com.limelight.LimeLog(10225): Fast poll for RA�UNALNIK-PC returned LOCAL
03-07 22:54:09.620: W/art(10225): Long monitor contention event with owner method=void java.lang.Object.wait!(long, int) from Object.java:4294967294 waiters=0 for 10.228s
03-07 22:54:12.188: I/com.limelight.LimeLog(10225): Starting fast poll for RA�UNALNIK-PC (/192.168.2.175, /193.77.xx.xxx)
03-07 22:54:12.226: I/com.limelight.LimeLog(10225): Fast poll for RA�UNALNIK-PC returned LOCAL
03-07 22:54:15.065: I/com.limelight.LimeLog(10225): mDNS: Machine appeared: RAȕNALNIK-PC
03-07 22:54:15.076: I/com.limelight.LimeLog(10225): mDNS: Machine resolved: RAȕNALNIK-PC
03-07 22:54:15.355: I/com.limelight.LimeLog(10225): Starting fast poll for RA�UNALNIK-PC (/192.168.2.175, /193.77.xx.xxx)
03-07 22:54:15.375: I/com.limelight.LimeLog(10225): Fast poll for RA�UNALNIK-PC returned LOCAL
03-07 22:54:18.533: I/com.limelight.LimeLog(10225): Starting fast poll for RA�UNALNIK-PC (/192.168.2.175, /193.77.xx.xxx)
03-07 22:54:18.568: I/com.limelight.LimeLog(10225): Fast poll for RA�UNALNIK-PC returned LOCAL
03-07 22:54:19.874: W/art(10225): Long monitor contention event with owner method=void com.limelight.nvstream.mdns.MdnsDiscoveryAgent$2.run() from MdnsDiscoveryAgent.java:108 waiters=0 for 10.226s
03-07 22:54:21.741: I/com.limelight.LimeLog(10225): Starting fast poll for RA�UNALNIK-PC (/192.168.2.175, /193.77.xx.xxx)
03-07 22:54:21.778: I/com.limelight.LimeLog(10225): Fast poll for RA�UNALNIK-PC returned LOCAL
03-07 22:54:24.963: I/com.limelight.LimeLog(10225): Starting fast poll for RA�UNALNIK-PC (/192.168.2.175, /193.77.xx.xxx)
03-07 22:54:24.998: I/com.limelight.LimeLog(10225): Fast poll for RA�UNALNIK-PC returned LOCAL
03-07 22:54:26.409: I/com.limelight.LimeLog(10225): mDNS: Machine appeared: RAȕNALNIK-PC
03-07 22:54:26.412: I/com.limelight.LimeLog(10225): mDNS: Machine resolved: RAȕNALNIK-PC
03-07 22:54:28.146: I/com.limelight.LimeLog(10225): Starting fast poll for RA�UNALNIK-PC (/192.168.2.175, /193.77.xx.xxx)
03-07 22:54:28.173: I/com.limelight.LimeLog(10225): Fast poll for RA�UNALNIK-PC returned LOCAL
03-07 22:54:31.018: W/art(10225): Long monitor contention event with owner method=void com.limelight.nvstream.mdns.MdnsDiscoveryAgent$2.run() from MdnsDiscoveryAgent.java:108 waiters=0 for 11.144s
03-07 22:54:37.026: W/art(10225): Long monitor contention event with owner method=void com.limelight.nvstream.mdns.MdnsDiscoveryAgent$2.run() from MdnsDiscoveryAgent.java:108 waiters=0 for 6.008s
03-07 22:54:41.367: I/com.limelight.LimeLog(10225): Starting fast poll for RA�UNALNIK-PC (/192.168.2.175, /193.77.xx.xxx)
03-07 22:54:41.396: I/com.limelight.LimeLog(10225): Fast poll for RA�UNALNIK-PC returned LOCAL
03-07 22:54:44.505: I/com.limelight.LimeLog(10225): Starting fast poll for RA�UNALNIK-PC (/192.168.2.175, /193.77.xx.xxx)
03-07 22:54:44.532: I/com.limelight.LimeLog(10225): Fast poll for RA�UNALNIK-PC returned LOCAL
03-07 22:54:47.741: I/com.limelight.LimeLog(10225): Starting fast poll for RA�UNALNIK-PC (/192.168.2.175, /193.77.xx.xxx)
03-07 22:54:47.770: I/com.limelight.LimeLog(10225): Fast poll for RA�UNALNIK-PC returned LOCAL

In the log I only changed last 5 digits of my ip with "x"

**Comment by krusic22** [comment]
I also downgraded GFX and it still didnt work. I checked the ports and switched routers still didnt work. Also tried on my tablet and didnt work. Maybie its a 5.0 problem or something?

**Comment by cgutman** [comment]
Re-open if this is still an issue.
