### ISSUE TITLE
Android keyboard not working properly with controller overlay

### ISSUE THREAD

**Issue by charmon1984** [moonlight-stream/moonlight-android#611]
I posted this almost a year ago with no reply:

"I play Final Fantasy XIV. I am having trouble with the enter and space buttons on the keyboard. When trying to talk to other people online, I can't use the spacebar at all because it turns the controller overlay red. I can hit enter if I use it as soon as I pull up the keyboard, but if I wait more than a few seconds it turns the controller overlay red also. Is there a way to turn this off? The little gear icon on the top left turns the overlay red to adjust also, so why have a keyboard shortcut too? If this could be fixed then moonlight would work perfect for me. Thanks a lot."

Now I can't even hit enter fast enough for it to send my message, it just turns the overlay editor on. I see no reason to have spacebar and enter as toggles for the controller overlay. There is a gear in the top left corner for this. Is there any way to change this?

**Comment by cgutman** [comment]
Sorry that this got missed. It's a bit of a weird scenario using a hardware keyboard with a virtual controller, but I have a fix for it.

**Comment by charmon1984** [comment]
Thank you so much! it works great now.
