### ISSUE TITLE
Input Issues: NVIDIA Shield Controller Right Analog Stick and Right Trigger both "stick"

### ISSUE THREAD

**Issue by redlinejoes** [moonlight-stream/moonlight-android#614]
Server OS: Windows 10 1803
Server GPU: NVIDIA 1080Ti 11GB
NVIDIA GPU Driver: 398.36
NVIDIA GFE Version: 3.14.1.48

Client OS: Android-N and Android-O
Client Moonlight Version: 5.9
Client Device: NVIDIA Shield Table K1 and NVIDIA Shield TV (both old and and new models. 
Client Controller: NVIDIA Shield Controller (both old and new models)
Client Shield controller and Shield device have the latest available FW and software updates.

Issue 1: Using the new model Shield controller, in a FPS game, the view will look up as if I'm pushing the right analog stick up. The right analog stick doesn't need upward input for this issue to occur. It occurs randomly without any physical analog stick input. The game stream will get stuck with the right analog sticking thinking it is being pushed up and I have to physically pull down the right analog stick to stop the "stickiness". The issue randomly occurs, but once it starts, the stream becomes unusable because it repeatedly happens and doesn't need physical input to happen. Only physical input resolves the issue, but that is a temporary fix. 

Issue 2: Using the older model Shield controller, I also have an issue where the right trigger will randomly get stuck. Same input issues as above, just a different button. I have to pull the trigger to get it to stop, but it will randomly start again. No right trigger physical input is required. If I am playing an FPS game, my gun will randomly fire, or repeatedly fire until I physically pull the right trigger to get it to stop.

**Comment by cherryleafroad** [comment]
I have this issue as well, and it makes it unplayable

**Comment by cofinley** [comment]
Same problem but this isn’t a Moonlight issue. Affecting the controller as a whole. 

Forum threads:
[1](https://forums.geforce.com/default/topic/1030793/shield-tv/my-controller-suddenly-has-started-moving-by-itself-)
[2](https://forums.geforce.com/default/topic/1028610/shield-tv/shield-controller-acting-out/1/)

Solution brought up in first thread was to spray canned air and lubricant (caution there) into the stick(s). Others seem to be able to RMA, even past 1yr warranty mark. Also talk of irreversible firmware bug.

Tempted to try to debug with the right diagnostic tools if it’s a software issue.

**Comment by cherryleafroad** [comment]
Mine sticks like this when using on the onscreen overlay. That would be a moonlight problem

**Comment by cofinley** [comment]
@cherryleafroad hmm, if that's the _only_ place it's happening then I can't help you there I'm afraid. I haven't used moonlight in awhile; I jumped on this thread because of the analog stick issue @redlinejoes was having that showed up in a Google search. Given the amount of people having the same problem I assumed it was a problem beyond just moonlight. Hopefully helps some who may come across this though.
