### ISSUE TITLE
Suddenly only streaming black screen?

### ISSUE THREAD

**Issue by Owerlords** [moonlight-stream/moonlight-android#615]
I streamed with my rooted android pad over mobile hotspot wifi and it worked fine but all of a sudden even when not updating anything today, i am streaming black screen and sound only(inputs still works). But when i connect to home wifi witch is the same as the host that i stream, then i get normal screen? i dont know what changed between the sessions to cause this, if i cant stream from away from home its no good :(

**Comment by vatomalo** [comment]
Sure that your computer screen is on? Is it in sleep mode?

I bought an HDMI dummy plug that solved this for me, I can now stream while my screen is off.

**Comment by vatomalo** [comment]
4784-4789 TCP
47995-47996 TCP
47998-48002 UDP
48010 TCP+UDP

Is what I have forwarded

**Comment by vatomalo** [comment]
I'm glad I was able to help,BTW it happens =)

**Comment by Trackhe** [comment]
same problem
