### ISSUE TITLE
[Bug] Mouse pointer offset

### ISSUE THREAD

**Issue by Techamazon404** [moonlight-stream/moonlight-android#617]
When client and host doesn't have matching resolutions you get a right aligned offset which makes anything on the rightest most part screen impossible to click on. And it happens regardless if you stretch the video or not.

Currently using an S9 (18:9) on a host PC that has a 21:9 monitor, which looks okay when stretched. But what I need to do in-game becomes impossible as the things I need to click is all on the right side.

**Comment by cgutman** [comment]
Is your S9 running Android 8.0? Proper mouse capture only works on Oreo and later.

**Comment by Techamazon404** [comment]
8.1 in fact, same issue regardless if I run rooted or the the normal one. I've tried other devices as well (XZ2, S8) with the same issue, both on 8.0.

**Comment by cgutman** [comment]
OK, I'm having trouble visualizing what you're seeing.

Are you seeing 2 mouse cursors on your Android device (both Android and Windows cursors) and the Android one is hitting the edge of the screen? Is part of the screen actually missing in the video on the phone?

**Comment by Techamazon404** [comment]
I'm seeing the cursor as intended but it's offset by like 500%, same if it's mouse (what I use) or the virtual one. Let me see if I can record what I'm trying to explain.

**Comment by Techamazon404** [comment]
Actually wow, sorry to disappoint but seems steam had decided to set default monitor to my other one hence the whole offset issue, mission accomplished once I switched to main. Sorry to bother.
