### ISSUE TITLE
Add custom keyboard keys

### ISSUE THREAD

**Issue by 8116453** [moonlight-stream/moonlight-android#622]
First of all, thanks to the author for developing such a good APP.
If you have time, you can add beautification and customization of the virtual keyboard, or add a custom keyboard button to a gadget. I think this is the APP's weakness.

**Comment by thw0rted** [comment]
What game are you trying to use with a virtual keyboard?  There are a number of ways you can remap gamepad presses to keyboard keys on your PC, if that helps -- then, you'd just have to use the existing on-screen controller customization to put "keys" where you want them.

**Comment by 8116453** [comment]
Thank you for your reply.

'm used to playing some online games with it, but the virtual handle buttons are too few and too big for me to resize. It would be perfect if you could customize adding buttons and resizing them on the desktop. I now have a software that can add buttons, but it doesn't work on moonlight.
Here are some source code, if it can be combined with moonlight, it will be perfect.
https://github.com/lightofrain/GameKeyboard

**Comment by AndnixSH** [comment]
it would be great to have since on-screen controller does not work.
