### ISSUE TITLE
Keyboard WASD movement issue on Android

### ISSUE THREAD

**Issue by Waaaaghhhh** [moonlight-stream/moonlight-android#623]
Previously repored by someone here:
https://github.com/moonlight-stream/moonlight-android/issues/552

I'm having this issue as well. A keyboard hooked up to my Android device via USB OTG or bluetooth does not allow me to use WASD in game. I am able to type on something like Notepad with no issues. Pressing and holding W in Notepad does work and the letter would be entered, followed by a pause, and then repeating.

But in game this does not work. There will be a slight movement of the character followed by nothing. I have tried multiple games including Overwatch, Witcher 3, Warframe, GTA, etc. 

I'm using a Oneplus 6 on Android 8.1 Oreo. 

This issue is not present on the PC Moonlight application. Keyboard and mouse controls work fine.

**Comment by Waaaaghhhh** [comment]
Upon further testing, I'm seeing that while holding down a key like "w" will produce "wwwwwwwwwwww", changing the key does not.

For example, if I long press W and the A to simulate moving forward and to the left in a game. In a Word document, it will show up as "wwwwwwwwwwwaaaaaaaaaaaaaa"

But in the same test but through Moonlight on Android, it will only produce "wwwwwwwwwwa"

So the repeat on the second letter doesn't happen. 

And even though you can get a single letter to repeat, no game seems to pick that ups as the key being held.

**Comment by Waaaaghhhh** [comment]
Found another interesting outcome from fiddling with this. 

By turning on Filter Keys, it prevents repeated key presses and keys held down to register. So using the keyboard attached to my PC with Filter Keys on, pressing W only types one letter instead of repeating W's. It also beeps at you to let you know you're trying to press a key on repeat. 

However, with Filter Keys on and using Moonlight with a OTG keyboard or bluetooth keyboard, it still allows me to repeat the first key pressed. So holding down W shows up as "wwwwwwwwwww"

This doesn't fix the issue though because holding down W and then A only shows up as "wwwwwwwwwa"

**Comment by kedirakevo** [comment]
Hi... Im facing EXACTLY the same issue. PC Moonlight works flawlessly 

Android Moonlight with OTG Keyboard WASD is not moving my character at all but arrow keys work normally. Im playing Warframe on Windows 10... my device is a Xiaomi Mi6 using original ROM

**Comment by Waaaaghhhh** [comment]
Figured out the issue. Don't know if it's really a bug at all. Started a game of Overwatch and initially it didn't work and WASD had the same issues. Then I pressed enter to type a message to a friend in game. After that, WASD started working!

So I pulled out my bluetooth keyboard and WASD started working on that too!

**Comment by Waaaaghhhh** [comment]
This fix seems to be only through Samsung Dex. Going back to the standard screen mirroring breaks the WASD again.

**Comment by kedirakevo** [comment]
> This fix seems to be only through Samsung Dex. Going back to the standard screen mirroring breaks the WASD again.

Sadface... made me happy for nothing. Arrow keys worked fine though, i can move my char as per wasd style but arrow keys are sooo far away from other controls.... Seriously, the devs are awesome for making this moonlight work on android (:D Thanks) but its kinda handicapped if we cant play FPS games as almost all FPS uses WASD which is broken for now...

**Comment by kedirakevo** [comment]
I SOLVED IT ISSUE!!! Somewhat... its more of a workaround.

I flashed a Generic Image System on my Xiaomi Mipad 4 and its working nicely now for WASD. So its highly possible that certain ROMS have something that interferes with the controls, not sure what it is...

**Comment by AngelDevoid** [comment]
I use moonlight with various games and have had to fix many bugs. The fix for this for me was to install an app called external keyboard then change the active keyboard to "external keyboard" all keys now work as if I was playing on a pc.
I use a cheap  USB c hub with an Xperia xz2
A WiFi keyboard and mouse connect via WiFi dingle supplied with the kb and mouse via the hub. Send me a mag if you have any issues or other issues

**Comment by Waaaaghhhh** [comment]
Thank you! Do you have a link to the app? There's multiple apps named External Keyboard

**Comment by AngelDevoid** [comment]
https://play.google.com/store/apps/details?id=com.medion.android.keyboard

Here ya go

Also some people having issues with Wol for remote gaming I can assist with that too have a few options.

Let me know how you get on with the keyboard.

**Comment by Waaaaghhhh** [comment]
It works! Thank you so much? What is Wol?

**Comment by AngelDevoid** [comment]
Wake on lan.

**Comment by Waaaaghhhh** [comment]
Ah ok mine has been fine so far but I leave my pc on 24/7 with ethernet connected. But thank you so much!!! This is amazing

**Comment by AngelDevoid** [comment]
No probs

**Comment by cgutman** [comment]
Can you try with Moonlight v5.9.3? I suspect I may have fixed the issue.

**Comment by AngelDevoid** [comment]
It's already sorted dude @cgutman

**Comment by Waaaaghhhh** [comment]
@cgutman just tested it and yes it's fixed! Thank you so much! No need for third party external keyboard app anymore.

**Comment by AngelDevoid** [comment]
Bonus

**Comment by kedirakevo** [comment]
@cgutman Yo man personally tested this version and it works well!!! 

Now can I present another minor challenge? Is there anyway moonlight can disable mouse acceleration for gaming? Mouse acceleration is screwing up the gaming experience.

**Comment by cgutman** [comment]
Recent GFE versions should disable mouse acceleration on the host-side. Are you seeing mouse acceleration in Android?

**Comment by AngelDevoid** [comment]
I don't seem to see any, however I have a gaming mouse that can have its settings fixed and saved to the mouse on board memory. An old razer taipan.
