### ISSUE TITLE
On Screen Keyboard Not Working

### ISSUE THREAD

**Issue by ski4404** [moonlight-stream/moonlight-android#63]
I'm trying to use the on screen Android keyboard while streaming.  I can bring the keyboard up just fine but I am unable to actually use it.  It seems like as I try to touch the keys, the (mouse) cursor is moving instead - as if the keyboard wasn't there.  This is on Android 4.4.4 Droid Turbo, Limelight 3.1.3.

**Comment by industrai** [comment]
I noticed this issue when using swiftkey keyboard for android.  When I switched to the Samsung keyboard I could use it.  It would be nice to get the swiftkey keyboard working in moonlight.
