### ISSUE TITLE
mouse right click issue

### ISSUE THREAD

**Issue by jw8803** [moonlight-stream/moonlight-android#634]
After updating your app
When you right-click
Reverse is executed.
It worked well in previous versions.
However, it should not be after the update.
What should I do?

Both Moonlight and GeForce are the latest versions.
I am using a Bluetooth mouse and connecting the mouse directly to OTG is the same symptom.

**Comment by cgutman** [comment]
What Android device are you using?

**Comment by jw8803** [comment]
xaomi pad4 and miui 9627 , lastest version

**Comment by cgutman** [comment]
are you seeing that right-click triggers the back function on Android (the Moonlight stream closes) or that it's triggering the back mouse button on the PC?

**Comment by jw8803** [comment]
Yes, pressing the right mouse button or the back button executes the backward function

When i press the first right mouse button, it works properly

However, if pressed one more time, the backward function is executed. This is the same with the mouse back button.
Strangely, the mouse forward button is always working properly.

And this problem occurs in other devices (the same company product, xiaomi RED MI NOTE 5)

**Comment by Sarielyy** [comment]
yes，the same problem on my device, xiaomi MI 8, only first right-click works

**Comment by lateforwork1000** [comment]
I'm having the same problem as well

**Comment by cgutman** [comment]
This should be fixed in v5.9.4. Please try that and confirm if the issue still exists.

**Comment by lateforwork1000** [comment]
Indeed I still have the issue thanks for the update

**Comment by Sarielyy** [comment]
the right_click issue still exists, its not the keycode_back in android, it 's the keycode "ALT+←" in windows, just like return previous page in browser

**Comment by jamest212** [comment]
I may be having a related issue - for me, once  I am in the stream, it is just not acknowledging my mouse clicks. Mouse cursor detection is perfectly fine.

This is on a Note 9 with a wireless USB mouse hooked up via OTG cable.

**Comment by jw8803** [comment]
thank you so much for updating ,however 
right mouse click execute backward function.. it still happens

**Comment by jw8803** [comment]
Thank you very much for the update
 Right button works well

Ya Feel So Gooood !!
