### ISSUE TITLE
Controller Shoulders not working

### ISSUE THREAD

**Issue by joaovittorsc** [moonlight-stream/moonlight-android#635]
Hi, I have a Samsung Gamepad, and everything on the stream side works wonders, but when I try to map the buttons I want on my game/emulator (usually Citra 3DS), I can't map the R and L buttons. Pressing the shoulder buttons seems to not give any kind of response. I don't know if this is an error with the mapping or the driver. BTW I'm using an Android Phone with the controller paired to my it (Samsung SM-G570M) and passing input through the Moonlight app. 
When I connect the controller directly to the computer via bluetooth it works, but than I can only play on my room... Wich pretty much makes it not worth it.

Could someone please help me?

**Comment by thw0rted** [comment]
Can you try launching something with a more robust controller tester and make sure the buttons show up at all?  For example, you could stream the Steam client (in Big Picture Mode), which is pretty good at figuring out controllers, or you could stream `mstsc.exe` (Terminal Services Client) which basically gives you a full remote desktop -- then you could launch the Gamepad control panel and see what it shows up as.

My theory is that your gamepad shoulder buttons could show up as analog (i.e., a "Z axis") which an emulator might not like -- of course, it could also be something with Gamestream, Moonlight, Android, whatever, in which case this won't help.  Still, this would be a good first step in the diagnosis.

**Comment by cgutman** [comment]
Also try Gamepad Tester on the play store and let me know what keycodes it shows for L and R shoulder buttons (and take a screenshot too)
