### ISSUE TITLE
Multiple controller support broken with multiple xbox 360 controllers / wireless receiver

### ISSUE THREAD

**Issue by SolidState214** [moonlight-stream/moonlight-android#64]
Tested using two wireless Xbox 360 controllers and a USB receiver connected to an Amazon Fire TV. Both controllers work and appear as separate controllers in other apps, e.g. Mupen64plus.

Both controllers appear as one in limelight 3.1.4 / GFE 2.2.2 regardless of "multiple controller support" setting. 

FireTV Firmware 51.1.4.1_514013920
(rbox pre-rooted ROM)

**Comment by sylinen** [comment]
Same issue here, but with two wired Xbox 360 controllers. When I have a keyboard plugged in, that can be recognized as a separate controller.

**Comment by cgutman** [comment]
@SolidState214 @d-s-x v3.1.6 includes a fix for your bugs. I confirmed that my Xbox 360 wireless controllers are now recognized independently with the fixed version.

@sylinen Your keyboard bug has been fixed in v3.1.5.

**Comment by yeahman45** [comment]
Is it fixed? Does not seem so for me.
I am using latest version (tried both chrome extension in windows and android app) with 2 xbox360 wired controllers and in Lara Croft and The Guardian of light, only one controller is detected
