### ISSUE TITLE
Request: Whitelist Apps

### ISSUE THREAD

**Issue by sondregronas** [moonlight-stream/moonlight-android#640]
Hey! This is a very specific QOL request, would it be possible to implement a whitelisted apps feature, and if there's only one app on the whitelist it will run directly to that app once you select a device?

I've got Launchbox BigBox on my system which is basically a TV friendly interface for loading games, and would love to not have to scroll down the applist everytime. I guess same would apply for Steam Big Picture. For now I've just renamed it to always be at the top, but would be nice to atleast limit the amount of apps.

PS: I'm also using a HDMI-CEC device to manage the app, which works fine, but in a stream the "OK" button (Xbox-A I guess) doesn't function, while arrows work fine. Not sure if that's only my remote control though, I'm yet to buy a good universal remotecontrol. (Currently using a 2015 Samsung remote)

Cheers

**Comment by isilkin** [comment]
I agree with you. I am also using a big box for my streaming.
