### ISSUE TITLE
No pointer input with latest GFE

### ISSUE THREAD

**Issue by maidik** [moonlight-stream/moonlight-android#642]
I hadn't run moonlight for a while, but running 5.10.1 on my Note 3 (N900V running LineageOS14.1/Nougat), I'm getting zero ability to manipulate the pointer.  Streaming appears to work (quite well), and I can move the pointer from the desktop.  But I can't move it with a phone for anything.

I've tried CTRL-shift-Z with a plugged in keyboard (doesn't work with Hacker's Keyboard).  That allows me to move the native Android cursor without interaction with the remote computer.  If I press it again, I can see the Android cursor stuck in the top left of the display.

I thought it might be an introduced bug, since older versions of Moonlight worked fine, so I grabbed my Note 4 (unofficial LOS15), which has 5.9.3 (non-root) and I get the same.

The only change I've made, that I can think of is a newer version of GeForce Experience.  I'm running GFE 3.15.0.186, which I believe is the latest.  So, broken with latest GFE?

To clarify: no pointer input works at all.  Not with touch, nor with a mouse by OTG cable.  And this all worked fine before, with all the same hardware and software, except GFE version.  I don't have another PC available to test non-Android at the moment, but I will soon.

Lemme know if there's any other information I can provide.

**Comment by maidik** [comment]
Just tried the Moonlight helper for kicks...nothing changed.

**Comment by maidik** [comment]
GFE updated itself to 3.16.0.119, which was also broked.  So, uninstall/reboot/installed latest GFE 3.16.0.122 from Nvidia site and I'm back in business.

Thank you again for this life changing piece of software!

**Comment by cgutman** [comment]
Glad you got it fixed
