### ISSUE TITLE
removing rxinput does not disable controller

### ISSUE THREAD

**Issue by isilkin** [moonlight-stream/moonlight-android#643]
In the latest geforce experience as of November 2018 renaming the 3 dll's no longer disables xinput on my mii android tv box. If I turn on my controllers first and then start moonlight app then i can keep my controller assignments. but if I run the app first and then turn on my controllers then player 2 will be assigned to a virtual controller. Renaming or deleting the xinput dll's does not solve the issue. Is there another dll that geforce experience relies on that steals my controller assignment.

**Comment by cgutman** [comment]
With recent GFE versions, the virtual controller will not appear if you simply don't connect a controller to your client device and ensure "automatic gamepad presence detection"is enabled. The dll hack is no longer required.
