### ISSUE TITLE
Immersive mode status-bar causes mouse input to freeze

### ISSUE THREAD

**Issue by cherryleafroad** [moonlight-stream/moonlight-android#644]
Problem description: When you are streaming a game, immersive mode means that the status bar is shown when you swipe down from the top. this steals mouse focus from the app, causing input to the game to "freeze"

Details: the mouse cursor likely will hit the top of the screen when playing the game, and then the status bar comes down, which stops the app from receiving mouse input, and the mouse on the computer freezes as a result, until the status-bar goes away.

How to fix: This can be easily fixed if the app uses a full screen where the status-bar never shows , or , when the status-bar shows, it doens't steal input from the app (sticky mode may be able to do it, but not sure)

**Comment by cgutman** [comment]
This is a limitation of Android prior to 8.0 Oreo. It sounds like you're running 7.0 Nougat based on the behavior you've described.

The only way to get mouse capture on earlier OSes is to root your device.
