### ISSUE TITLE
Unable mouse move and click on UAC screen

### ISSUE THREAD

**Issue by elestopa** [moonlight-stream/moonlight-android#646]
When I open an application as an administrator, I get a notice of control of user accounts (UAC) and I am locked the mouse (touch) in android, not being able to click

**Comment by cgutman** [comment]
This is a bug in GeForce Experience v3.16. You can help get Nvidia's attention by commented on this forum post: https://forums.geforce.com/default/topic/1082300/gamestream/gfe-3-16-regression-mouse-and-keyboard-doesn-t-work-on-uac-prompts-on-win8-1/

**Comment by cgutman** [comment]
Fixed in GeForce Experience 3.19.0.94 Beta.
