### ISSUE TITLE
Request for additional virtual key functions

### ISSUE THREAD

**Issue by 8116453** [moonlight-stream/moonlight-android#653]
Sorry to disturb you again, but I hope moonlight can be better. I hope you can add a virtual keyboard plug-in to moonlight, which can be integrated on the screen. Clicking on the plug-in can select the full keyboard and virtual handle. Full keyboard like Hacker keyboard, I think it is more useful for some online games. If you don't have time, ask that you replace the virtual handle with the IOS version. I think it's both beautiful and practical. I looked at the replies from many netizens in the Google App Store, hoping to change the style of virtual handles. Thank you very much.

**Comment by cgutman** [comment]
You can open your keyboard by using a 3 finger tap while streaming and select any of your installed keyboards, including Hacker Keyboard.
