### ISSUE TITLE
Properly using Xbox 360 controller with non-steam games

### ISSUE THREAD

**Issue by denisb411** [moonlight-stream/moonlight-android#654]
I have a device that has built-in gamepads (that's the gpd xd) and they work as a xbox 360 controller.

I want to play some WiiU games with cemu.exe but unfortunately moonlight keeps mapping my gamepad with mouse functions, like the left analog moves the mouse and l2/r2 is left/right mouse click.

Is there some way I can deactivate this functions and use the mouse only with the touchscreen? I can't play the games because emulator doesn't properly identify the gamepad.

Note: Games run fine when I use Steam games / Steam Big Picture.

**Comment by cgutman** [comment]
This is almost always caused by Steam controller configuration support. Turn it off and try again.

**Comment by denisb411** [comment]
Thanks a lot. Thought it was a moonlight problem.

The only problem I have now is with the stick sensitivity, but that's another story.
