### ISSUE TITLE
Chromecast Support

### ISSUE THREAD

**Issue by Muda42** [moonlight-stream/moonlight-android#655]
Chromecast Support would be really cool to play the games on a TV. Issue #427 already asked dor this but it got closed for inactivity. The guy on #427 did a schema on how this might work. This would be great if its implemented

**Comment by thw0rted** [comment]
Chromecast really isn't designed for this mode of interaction.  It's a dumb receiver for video (or just audio) streams, that's the only thing it can really do.  As far as I can tell there is no ability to connect any kind of input device, which means (as I commented on that issue) you'd have to provide input via your phone and push the output to the TV.  That means either screen-mirroring your phone, [which you might be able to do already](https://support.google.com/chromecast/answer/6059461?hl=en) or pushing your computer's video to the Chromecast, which is simply not what GameStream / Moonlight is designed to do.

Would it help if Moonlight added a "no video" mode, where the controller inputs are passed through but the video stream is ignored?  Then you could run a second, separate display streaming application to "watch" your PC's video output remotely?
