### ISSUE TITLE
Changing the PC resolution when running msctsc.exe

### ISSUE THREAD

**Issue by denisb411** [moonlight-stream/moonlight-android#657]
My computer is set to my monitor resolution that is 2560x1080 and, different from when I start Steam games or Steam Big Picture, the PC resolution doesnt go down to 720p like my phone is configured.

How can I set the screen resolution when I start streaming the PC?

**Comment by denisb411** [comment]
Well, I don't think this is a solution as you have to manually set the resolution back to the original every time you will close the session.

When you close session using Steam games/Big Picture it works perfectly. It starts with the device's resolution and take back to the original resolution after closing the session.

**Comment by cgutman** [comment]
You have to do it manually. GeForce Experience won't touch your display resolution when streaming the desktop.
