### ISSUE TITLE
cant stream over internet. help me out!

### ISSUE THREAD

**Issue by 7gbman** [moonlight-stream/moonlight-android#658]
Moonlight Internet Streaming Tester v2.1.0.0
GeForce Experience installed and GameStream is enabled
Testing GameStream ports via loopback
Testing TCP 47984...Success
Testing TCP 47989...Success
Testing TCP 48010...Success
Testing UDP 47998...Success
Testing UDP 47999...Success
Testing UDP 48000...Success
Testing UDP 48002...Success
Testing UDP 48010...Unknown (in use)
Finding local IP address...192.168.0.115
Testing GameStream ports via local network
Testing TCP 47984...Success
Testing TCP 47989...Success
Testing TCP 48010...Success
Testing UDP 47998...Success
Testing UDP 47999...Success
Testing UDP 48000...Success
Testing UDP 48002...Success
Testing UDP 48010...Unknown (in use)
Discovered UPnP IGD at: http://192.168.0.1:1900/upnp/control/WANIPConn1
Detecting WAN IP address via UPnP...10.4.1.195
Checking for UPnP port mapping for TCP 47984 -> 192.168.0.115...OK
Checking for UPnP port mapping for TCP 47989 -> 192.168.0.115...OK
Checking for UPnP port mapping for TCP 48010 -> 192.168.0.115...OK
Checking for UPnP port mapping for UDP 47998 -> 192.168.0.115...OK
Checking for UPnP port mapping for UDP 47999 -> 192.168.0.115...OK
Checking for UPnP port mapping for UDP 48000 -> 192.168.0.115...OK
Checking for UPnP port mapping for UDP 48002 -> 192.168.0.115...OK
Checking for UPnP port mapping for UDP 48010 -> 192.168.0.115...OK
Detecting WAN IP address via NAT-PMP...FAILED -5
Detecting WAN IP address via STUN...103.195.0.170
Testing GameStream ports via UPnP/NAT-PMP reported WAN address
Testing TCP 47984...Timeout
Testing TCP 47989...Timeout
Testing TCP 48010...Timeout
Testing UDP 47998...Timeout
Testing UDP 47999...Timeout
Testing UDP 48000...Timeout
Testing UDP 48002...Success
Testing UDP 48010...Unknown (in use)
Detected inconsistency between UPnP/NAT-PMP and STUN reported WAN addresses!
Testing GameStream ports via STUN-reported WAN address
Testing TCP 47984...Timeout
Testing TCP 47989...Timeout
Testing TCP 48010...Timeout
Testing UDP 47998...Timeout
Testing UDP 47999...Timeout
Testing UDP 48000...Timeout
Testing UDP 48002...Timeout
Testing UDP 48010...Unknown (in use)
Your router appears be connected to the Internet through another router. Make sure both routers have UPnP or NAT-PMP enabled, or better yet, switch one of the routers into bridge/AP mode.
--------------- MISS LOG -------------------
Moonlight Internet Streaming Service v2.1.0.0
Woke up for periodic refresh
GameStream is ON!
Finding upstream IPv4 hops via traceroute...
Hop 0: 10.4.1.1
Hop 1: 103.195.0.169
Hop 2: 43.224.113.125
Hop 3: 43.228.208.5
Found 4 hops
Starting port mapping update on default gateway to local machine...
UPnP IPv4 IGD discovery completed with error code: 0
NAT-PMP public address request failed: -5
Found a disconnected UPnP IGD (!)
UPnP IGD WAN address is: 10.4.1.195
Checking for existing UPnP port mapping for TCP 47984 -> 192.168.0.115 7GB-PC...OK (3600 seconds remaining)
Updating UPnP port mapping for TCP 47984 -> 192.168.0.115...OK
Checking for existing UPnP port mapping for TCP 47989 -> 192.168.0.115 7GB-PC...OK (3600 seconds remaining)
Updating UPnP port mapping for TCP 47989 -> 192.168.0.115...OK
Checking for existing UPnP port mapping for TCP 48010 -> 192.168.0.115 7GB-PC...OK (3600 seconds remaining)
Updating UPnP port mapping for TCP 48010 -> 192.168.0.115...OK
Checking for existing UPnP port mapping for UDP 47998 -> 192.168.0.115 7GB-PC...OK (3600 seconds remaining)
Updating UPnP port mapping for UDP 47998 -> 192.168.0.115...OK
Checking for existing UPnP port mapping for UDP 47999 -> 192.168.0.115 7GB-PC...OK (3600 seconds remaining)
Updating UPnP port mapping for UDP 47999 -> 192.168.0.115...OK
Checking for existing UPnP port mapping for UDP 48000 -> 192.168.0.115 7GB-PC...OK (3600 seconds remaining)
Updating UPnP port mapping for UDP 48000 -> 192.168.0.115...OK
Checking for existing UPnP port mapping for UDP 48002 -> 192.168.0.115 7GB-PC...OK (3600 seconds remaining)
Updating UPnP port mapping for UDP 48002 -> 192.168.0.115...OK
Checking for existing UPnP port mapping for UDP 48010 -> 192.168.0.115 7GB-PC...OK (3600 seconds remaining)
Updating UPnP port mapping for UDP 48010 -> 192.168.0.115...OK
Checking for existing UPnP port mapping for UDP 9 -> 192.168.0.255 7GB-PC...OK (Permanent)
Updating UPnP port mapping for UDP 9 -> 192.168.0.255...OK
Updating PCP port mapping for TCP 47984...NO RESPONSE
Updating PCP port mapping for TCP 47989...NO RESPONSE
Updating PCP port mapping for TCP 48010...NO RESPONSE
Updating PCP port mapping for UDP 47998...NO RESPONSE
Updating PCP port mapping for UDP 47999...NO RESPONSE
Updating PCP port mapping for UDP 48000...NO RESPONSE
Updating PCP port mapping for UDP 48002...NO RESPONSE
Updating PCP port mapping for UDP 48010...NO RESPONSE
Using UPnP upstream IPv4 address: 10.4.1.195
Upstream address 10.4.1.195 is likely a NAT
Starting port mapping update on 10.4.1.1 to 10.4.1.195...
NAT-PMP public address request failed: -5
No UPnP device found!
Updating PCP port mapping for TCP 47984...NO RESPONSE
Updating PCP port mapping for TCP 47989...NO RESPONSE
Updating PCP port mapping for TCP 48010...NO RESPONSE
Updating PCP port mapping for UDP 47998...NO RESPONSE
Updating PCP port mapping for UDP 47999...NO RESPONSE
Updating PCP port mapping for UDP 48000...NO RESPONSE
Updating PCP port mapping for UDP 48002...NO RESPONSE
Updating PCP port mapping for UDP 48010...NO RESPONSE
Updating PCP port mapping for UDP 9...NO RESPONSE
No valid upstream IPv4 address found!
Going to sleep...

"this is what troubleshoot log said"

**Comment by thw0rted** [comment]
First, you might want to take your public IP of the log or obfuscate it -- it begins "103.".  Second, tell us about your network connections.  The log says

> Your router appears be connected to the Internet through another router. Make sure both routers have UPnP or NAT-PMP enabled, or better yet, switch one of the routers into bridge/AP mode.

Is that true?  If so, is there any way you can connect your PC directly to the router that's actually on the internet, rather than one that's 2 hops away?  Also, do you know if your ISP provides a single IPv4 address for your connection or if it's shared between several users (via a 6-to-4 tunnel like DSlite)?

**Comment by 7gbman** [comment]
I would not bother taking out the public IP as this is a test computer for
app testing and empty. I think my ipv4 is a shared connection and first
router is in the provider office.

**Comment by thw0rted** [comment]
You are likely in the same situation I am -- provider only gives out IPv6 addresses.  I don't really have occasion to stream outside the home, so I haven't spent much time on it, unfortunately.  Do you know if you have the option to buy an IPv4 address?  I'm told my provider charges a small fee for that but I haven't spent the time to set it up yet.  It might also be possible to stream over IPv6 only but I haven't dug into it.

**Comment by 7gbman** [comment]
So the ipv4 real IP give access to most remote things, as it says in the
internet. I have tried Remotr and similar apps these are not working over
the internet for same reason. Let's me know if you dug into the shared
connection streaming ways.

**Comment by thw0rted** [comment]
That's cool, I hadn't read [the setup guide](https://github.com/moonlight-stream/moonlight-docs/wiki/Setup-Guide#streaming-over-the-internet) in a while, and it has a ton of network troubleshooting info.  It might be worth linking directly to the setup guide page from this project's README?  The current "Usage" section is pretty simplified.
