### ISSUE TITLE
关于远程串流画面闪烁马赛克问题

### ISSUE THREAD

**Issue by Ivanuxan** [moonlight-stream/moonlight-android#662]
您好，
Moonlightmans，我在使用过程中，远程串流时，画面闪烁有马赛克。然而在局域网下完全没问题。

**Comment by 8116453** [comment]
把码率调低一点，移动网络的最后调成3000K

**Comment by Ivanuxan** [comment]
@8116453移动网络调成3000K乃至更低我都试过，有时候第一次进入moonlight清楚，但是切回主菜单在进入串流，就会变得闪烁模糊马赛克。

**Comment by 8116453** [comment]
你把电脑分辨率调成1366   768试试呢？我的没有出现过这种问题，或者取消H.265

**Comment by cgutman** [comment]
Please report bugs in English to ensure other GitHub participants can understand.
