### ISSUE TITLE
Keyboard and mouse connection

### ISSUE THREAD

**Issue by mystic1990** [moonlight-stream/moonlight-android#665]
**Devices:**
- Mi Pad 4 Plus
- Bluetooth Keyboard with keypad
- Usb Type C adapter
- Usb Mouse

**Connection:**
-Wireless Hotspot via 4g from mobile phone

I have used the above devices to connect. All was working fine without moonlight. After connection to moonlight to view my gaming pc, I faced several issues:
1. Movement of the mouse is laggy and slow in response.
2. Switching off the bluetooth keypad disconnect from moonlight
3. Loaded into game(COH2) but no mouse is shown

Please advise for any solutions or alternatives. Thank you and appreciated.

**Comment by cgutman** [comment]
The issue is probably due to Bluetooth interference with your WiFi hotspot causing packet loss. If you configure your hotspot to use a 5 GHz WiFi channel (36 or higher), it might not interfere.
