### ISSUE TITLE
Controllers Vibration can't work yet!?

### ISSUE THREAD

**Issue by ZerOri** [moonlight-stream/moonlight-android#666]
I have successfully paired Xbox One S controllers with my Android TV.
I can play games but I have noticed that the vibration function doesn't work.
Is there any solution?

**Comment by cgutman** [comment]
No, Android does not support vibration with the Xbox One S controller, and Moonlight does not currently support vibration either.

**Comment by cgutman** [comment]
Moonlight for Android v7.0 now supports rumble, however I don't think Android supports rumbling the One S controller.

**Comment by XxPLAYdxX** [comment]
Did anyone notice this is issue 666?
