### ISSUE TITLE
Support for "all in one" VR devices (request)

### ISSUE THREAD

**Issue by tk7018** [moonlight-stream/moonlight-android#669]
Due to an update of niburu os  is not possible to stream to all in one VR devices using the full lcd panel anymore .  is it possible to add a VR/Cardboard options to the android release to circumvent this issue?

Thanks

**Comment by zediiiii** [comment]
This has already been done in various forks, though none of them are updated to work with recent software updates. For example,

https://github.com/monstrobishi/moonlight-android
https://github.com/penkamaster/moonlight-android
https://github.com/MardariG/moonlight-android

I have been unsuccessfully attempting to get these things going for a while, but my lack of understanding of the finer points of gradle and Android NDK hold me back. If anyone does get a build working (or even a workaround going) to enable this, I'd be much obliged for a share. 

I've been trying to get simple streaming in 2D sbs + controller support on my android device for years now - Trinus, Riftcat, Tridef, Vorpx, Perception, Virtual Desktop... At present, none of them allow a standard android phone to use a controller and stream sbs at the same time (that I know of).

**Comment by tk7018** [comment]
Actually i just need to "trick" the Vr unit to display the "raw" video that is received from the pc using the entire LCD surface instead of down scaling it into 2 half sized downscale videos. In the past in order do to that by pressing  "vr" menu button ad deactivating vr mode was enough but with the lastest reelase of nibiru os this is not possible anymore and the device always revert to the 2 screen mode.
Just adding a VR mode (without racking or else ) should be enough.

Is possible to achieve a pretty good angular tracking by using "freepieimu" and connect to freepie, opentrack or riftcat. i played "aliens colonial marines " by programming a freepie script that does mouse emulation and reshade alogng with this shaders [https://github.com/BlueSkyDefender/Depth3D/tree/master/Shaders](url).

**Comment by zediiiii** [comment]
Does the VR unit do the SBS and scaling processing itself, or does it required a converted stream?

**Comment by tk7018** [comment]
Most (if not all) of the VR all in on unit do a simple doubling of the 2d screen when used with moonlight, this means the pc screen is just duplicated with half of the available resolution (downlscaled) for both eyes.
This is not ideal if the stereoscopy is achieved directly on the pc and streamed to the vr unit, in that case the internal adaptation must be turned off..

**Comment by zediiiii** [comment]
Ah! That's useful information - thank you. 
Help me get this right then.

**An ideal solution** would be to have the following changes made to settings:

1-Toggle for Device-based SBS in stream (ie, device moonlight based SBS if on, single screen if off)
2-Toggle for Device-based SBS in menus (ie, local SBS for moonlight menus if on, single screen if off)
3-Allowing Google Cardboard access ([as in this fork](https://github.com/penkamaster/moonlight-android)) so that moonlight doesn't have to deal with the various settings required to get the VR stream to show correctly.
