### ISSUE TITLE
Request- Setting toggle to Quit Session when backing out of Moonlight

### ISSUE THREAD

**Issue by profucius** [moonlight-stream/moonlight-android#670]
I like that Moonlight does not immediately kill the stream/game when you back-out or home-out of Moonlight. However, on one of my android devices, I would like for this to actually kill the stream. I know we can currently hold finger on the computer name and "Quit Session" to manually do this, but I propose a **simple toggle in the app settings that makes it so if you back or home out of Moonlight that it will trigger a Quit Session automatically**.

Use cases: When I'm using Moonlight on my gaming TV, when I back out it is always intentional and I will not be remoting back in. But if I only back/home out, the audio on my desktop is still routing through the stream. I want the session to be quit officially anytime I back/home out on this device, but not on my phone, which a settings toggle would resolve.

**Comment by sondregronas** [comment]
I second this, would be a nice feature for TV users. Would also like to see an option to automatically terminate the app (or go back to previous app) whenever a stream session is terminated intentionally.

**Comment by profucius** [comment]
Bumping for visibility

**Comment by profucius** [comment]
I would still very much like to see this as a feature. Bumping to keep alive.
