### ISSUE TITLE
Can I use touch screen mode instead of touchpad mode?

### ISSUE THREAD

**Issue by shinobiz** [moonlight-stream/moonlight-android#672]
Hello, great engineer！
    Can I use touch screen mode instead of touchpad mode? It’s best to use two fingers to zoom or pan the screen, just like steam link. This is very convenient for playing galgame or Hgame. Thank you！

**Comment by cgutman** [comment]
Unfortunately, that's not possible with GameStream. It only supports relative mouse movement which requires capturing the mouse cursor.

**Comment by parkerlreed** [comment]
Would this be possible with sunshine as the server? The direct input touch already works great. Would be nice for that to actually be touch instead of mouse.

**Comment by ezekiel23533** [comment]
I'd like it too. I use moonlight for various things and using the touch input from the phone would be very useful.

**Comment by bsdayo** [comment]
+1 for this, will significantly improve the touch control experience

**Comment by samkitty** [comment]
+1 Please implement this if possible. It would make moonlight so much easier to use and would feel native.

**Comment by kripikripi** [comment]
+1

**Comment by samkitty** [comment]
I found the solution to this and shared it in a different [thread](https://github.com/moonlight-stream/moonlight-android/issues/1271#issuecomment-2005453444).

**Comment by parkerlreed** [comment]
How is that a solution? Trusting a random build seems a bit much (plus you seem vague about where it even is). Regular user searching from some random Chinese username leads to nothing.

**Comment by samkitty** [comment]
Read the comment I'm replying to for instructions on how to compile it yourself. The native multi-touch functionality is already built into the Moonlight code but is disabled, the Chinese dev only enabled it and added a few quality of life features to make it more convenient. It's up to you whether you want to trust him or not.

Also it's the first result if you search for his username in your search engine of choice, I'm not being "vague", I'm just sharing the temporary solution I found.

**Comment by parkerlreed** [comment]
First results brings me to https://space.bilibili.com/16893379/

What am I supposed to do there? 

But yes thanks it built fine

```
[parker@rogally moonlight-android]$ find . -iname "*apk"
./app/build/outputs/apk
./app/build/outputs/apk/root/release/app-root-release-unsigned.apk
./app/build/outputs/apk/root/debug/app-root-debug.apk
./app/build/outputs/apk/nonRoot/release/app-nonRoot-release-unsigned.apk
./app/build/outputs/apk/nonRoot/debug/app-nonRoot-debug.apk
```

**Comment by parkerlreed** [comment]
Hey nice! This works with the recent native touch and stylus that sunshine implemented on Linux!

**Comment by M0HID** [comment]
Interestingly, the current version of moonlight for ios supports actual touch input if an apple pencil is being used…
