### ISSUE TITLE
Build help

### ISSUE THREAD

**Issue by lateforwork1000** [moonlight-stream/moonlight-android#673]
Hay I'v been trying to had support for other resolutions like 2160x1080, or 2048x1536 so far I haven't been able to get anything to work all the builds seem to crash or "can not support resolution..." I have been able to do this in the pass with no problems. Is there a location in the code where I can manually add these resolutions? 
I do have a older build of moonlight that has these resolutions but i would like to update it. 

Thanks

**Comment by cgutman** [comment]
You can follow my example for adding 480p - https://github.com/moonlight-stream/moonlight-android/commit/f0c69d08b8e8d61416742beb824b483ea19ddd16

**Comment by lateforwork1000** [comment]
alright i gave this a try but i failed here are my changes that i tried to add 


`    private static int getHeightFromResolutionString(String resString) {
        if (resString.equalsIgnoreCase("360p")) {
            return 360;
        }
        else if (resString.equalsIgnoreCase("480p")) {
            return 480;
        }
        else if (resString.equalsIgnoreCase("720p")) {
            return 720;
        }
        else if (resString.equalsIgnoreCase("1080p")) {
            return 1080;
        }
        else if (resString.equalsIgnoreCase("2160p")) {
            return 2160;
        }
        else if (resString.equalsIgnoreCase("1440p")) {
            return 1440;
        }
        else if (resString.equalsIgnoreCase("4K")) {
            return 2160;
        }
        else {
            // Should be unreachable
            return 720;
        }
    }

----

    private static int getWidthFromResolutionString(String resString) {
        int height = getHeightFromResolutionString(resString);
        if (height == 480) {
            return 854;
        }
        else if (height == 1080) {
            return 2160;
        }
            {
            return (height * 16) / 9;
        }
    }



---- i also tried 


   private static int getWidthFromResolutionString(String resString) {
        int height = getHeightFromResolutionString(resString);
            if (height == 1080) {
            return 2160;
        }
            {
            return (height * 2) / 1;
        }
    }


----


    private static String getResolutionString(int width, int height) {
        switch (height) {
            case 360:
                return "360p";
            case 480:
                return "480p";
            default:
            case 720:
                return "720p";
            case 1080:
                return "1080p";
            case 2160:
                return "2160p";
            case 1440:
                return "4K";

        }
    }

----

        if (width * height <= 640 * 360) {
            return (int)(1000 * (fps / 30.0));
        }
        else if (width * height <= 854 * 480) {
            return (int)(1500 * (fps / 30.0));
        }
        else if (width * height <= 1366 * 768) {
            return (int)(5000 * (fps / 30.0));
        }
        else if (width * height <= 1920 * 1200) {
            return (int)(10000 * (fps / 30.0));
        }
        else if (width * height <= 2160 * 1080) {
            return (int)(10000 * (fps / 30.0));
        }
        else if (width * height <= 2560 * 1600) {
            return (int)(20000 * (fps / 30.0));
        }
        else /* if (width * height <= 3840 * 2160) */ {
            return (int)(40000 * (fps / 30.0));
        }
    }


----

    <string-array name="resolution_names">
        <item>360p</item>
        <item>480p</item>
        <item>720p</item>
        <item>1080p</item>
        <item>2160p</item>
        <item>1440p</item>
        <item>4K</item>
    </string-array>
    <string-array name="resolution_values" translatable="false">
        <item>360p</item>
        <item>480p</item>
        <item>720p</item>
        <item>1080p</item>
        <item>2160p</item>
        <item>1440p</item>
        <item>4K</item>
    </string-array>
`
I'm now getting this error " resolution not supported by your device " . 

I'am i doing this right ?

**Comment by cgutman** [comment]
If you're getting the "Video decoder failed to initialize. Your device may not support the selected resolution." error, that means your device's video decoder can't decode the resolution you picked.

**Comment by lateforwork1000** [comment]
I do have a working copy of the older version of moonlight with this resolution it works just fine i can upload it if you want me to. 

I tried deleting the 4k reference it did not work.

**Comment by cgutman** [comment]
Can you confirm that the resolution that's actually getting passed into the MediaCodecDecoderRenderer class is correct? For some reason, your device doesn't like it.

Can you also attach logcat logs?

**Comment by lateforwork1000** [comment]
yeah sure where do i make a log/fine it ?

**Comment by cgutman** [comment]
You use `adb logcat` which is included in Android Studio or the Android SDK. You can make one for both working and non-working builds.

**Comment by lateforwork1000** [comment]
okay ill try and upload as soon as i can, got very sick: dont know when i can see my laptop again

**Comment by cgutman** [comment]
Ok there's no rush

**Comment by lateforwork1000** [comment]
hay I'm not sure when I be back on my pc again but here is the moonlight(the old build) with the working resolutions.


[moonlight018.zip](https://github.com/moonlight-stream/moonlight-android/files/3168740/moonlight018.zip)
