### ISSUE TITLE
[Feature request] Multitouch support (complete passthrough)

### ISSUE THREAD

**Issue by sakishrist** [moonlight-stream/moonlight-android#674]
Hello all,

First of all¸ this is a great project and it works very very smoothly!

Now, on to the question. There are a few (not many by far) games that support touchscreen and multitouch gestures (like Civilization VI). Do you think it is possible for the multitouch of the android device to be passed-through to the host PC and to appear like a real touch device?

Cheers,
Sakis

**Comment by thw0rted** [comment]
Duplicate of #672.

**Comment by sakishrist** [comment]
Oh, I see, my bad. did not see the closed one.
