### ISSUE TITLE
Moonlight disconnect after few minutes of streaming 

### ISSUE THREAD

**Issue by feslgetar** [moonlight-stream/moonlight-android#678]
i'm a new moonlight app user everything works just great but after few minutes of streaming the connection gets terminated and is lost from pc  it connects back when i turn off and on my wifi again on my android phone honor 8x  my gpu is evga gtx 1060 and i have the latest drivers and GFE 
can someone help troubleshoot this issue   sorry for my english

**Comment by 8116453** [comment]
Is it a router problem? What about trying another cell phone? If it weren't, it might be a mobile phone problem. Some mobile phones have WiFi disconnection. If you use a Bluetooth handle, it will conflict with your device network and this will happen.

**Comment by feslgetar** [comment]
Tried it on another phone it still happens I'm guessing it's the router or my wondows 10 firewall
