### ISSUE TITLE
No vibration with the controller of the Nvidia shield

### ISSUE THREAD

**Issue by bubuleur** [moonlight-stream/moonlight-android#680]
Hello,
I come to you for a little problem I have a nvidia shield tv with the latest update and I installed geforce experience on my computer with also the latest update
and I saw that now we can have the vibrations on the controller with your new update but it does not work for me I check the box for this effect on moonlight but I have no vibration
I play at the moment the last crash bandicoot on pc by plugging the controller on the pc it's good it vibrates but when I try with moonlight it does not vibrate anymore
That can come from where?
thank you

**Comment by bubuleur** [comment]
Hello,
I come to you for a little problem I have a nvidia shield tv with the latest update and I installed geforce experience on my computer with also the latest update
and I saw that now we can have the vibrations on the controller with your new update but it does not work for me I check the box for this effect on moonlight but I have no vibration
I play at the moment the last crash bandicoot on pc by plugging the controller on the pc it's good it vibrates but when I try with moonlight it does not vibrate anymore
That can come from where?
thank you

**Comment by cgutman** [comment]
This is a limitation of the Shield TV controller and the Shield TV OS. Even though the gamepad supports rumble, it uses some Nvidia proprietary API rather than the official (though somewhat limited) Android Vibration API. 

You should request that Nvidia implement that functionality if you want rumble to work in 3rd party apps like Moonlight.

**Comment by bubuleur** [comment]
Ok thank you for your answer
I can ask on the forum but I do not know what to say
You have an idea ?
