### ISSUE TITLE
Can you add the option of turning off the screen mouse when opening the virtual controller?

### ISSUE THREAD

**Issue by 8116453** [moonlight-stream/moonlight-android#682]
There are currently conflicts. If you touch the location outside the virtual controller, you will start moving the mouse, which will cause the virtual controller to fail. In some games, the switch between keyboard operation and controller is repeated. If you add a virtual controller to disable the operation of the screen mouse, you can solve the current problem. Please pay attention to this problem. Thank you.

**Comment by 8116453** [comment]
This question is very important. Please pay attention to it.

**Comment by 8116453** [comment]
This question is very important. Please pay attention to it.

**Comment by thw0rted** [comment]
For reference, the Steam Link app shows a prompt when you run a game to pick between mouse, controller, or both.
