### ISSUE TITLE
How to enter the background during the steam game through the gamepad?

### ISSUE THREAD

**Issue by shinobiz** [moonlight-stream/moonlight-android#683]
Before by pressing start+select, now not.

**Comment by cgutman** [comment]
I don't understand what you mean. Can you clarify what you want to happen?

**Comment by shinobiz** [comment]
Sorry, my bad English.

START+SELECT=STEAM Button. Yes before, not now

Do you understand me?

**Comment by thw0rted** [comment]
On a Steam controller, connected directly to the host PC, there are chord commands.  You can use the home/Steam button plus either start or select to emulate alt-tab.  Maybe that's what he means?  Or else, he means that start + select on a regular BT controller (iPega or whatever) emulates a "home" press, which is commonly captured by Steam to either open the Steam client, or, if the client is already showing, launch Big Picture mode.  I don't have Moonlight handy to test that right now.

If it's the latter, I think the question is whether this mapping happens on the controller itself, in the Bluetooth stack somewhere, in Moonlight, in GFE/GameStream, or with some 3rd party software on the host PC.

**Comment by shinobiz** [comment]
I use the XBOX ONE S gamepad. In previous versions
START+SELECT=STEAM Button=ALT+TAB. Not working now
