### ISSUE TITLE
Keep aspect ratio on full screen stretch

### ISSUE THREAD

**Issue by BiatuAutMiahn** [moonlight-stream/moonlight-android#684]
Can you add an option to keep aspect ratio when enabling the stretch to fullscreen option?

**Comment by cgutman** [comment]
That's already what it does if you don't check the box to stretch it. Why did you check that box?

**Comment by BiatuAutMiahn** [comment]
Last time I had used moonlight the aspect ratio was not maintained, the video was stretched to odd proportions.

**Comment by BiatuAutMiahn** [comment]
This is similar to https://github.com/moonlight-stream/moonlight-qt/issues/190
