### ISSUE TITLE
How to close the mouse operation on the screen?

### ISSUE THREAD

**Issue by 8116453** [moonlight-stream/moonlight-android#686]
If the screen mouse is not turned off, there will be conflicts in the use of virtual controllers. The input devices in the game will switch back and forth, which will also lead to the temporary failure of the rocker. When you point outside the virtual controller, if you are operating the rocker, the rocker will stop working and must be Re-touched before it can continue to work. In some games, the experience is very poor. This problem has troubled me for a long time. Please pay attention to it.

**Comment by thw0rted** [comment]
Is this issue any different from #682? If so, please clarify your intent. If not, please close this issue since the requirement is already being tracked.

**Comment by 8116453** [comment]
I've found a solution. There's something wrong with the virtual rocker. I changed its file and now it works.
