### ISSUE TITLE
Gamepad is automatically disconnected

### ISSUE THREAD

**Issue by shinobiz** [moonlight-stream/moonlight-android#690]
I used a 2.4G gamepad. I plugged the adapter into my Android device and checked "Override Android controller support" so I got the vibration of the gamepad.

However, it will be automatically disconnected soon after use. But it is normal for me to insert the 2.4G adapter directly into the PC.

The same situation does not exist under the steam link app.

**Comment by shinobiz** [comment]
There is also a problem, when inserting the usb adapter and checking "Override Android controller support", the window "Used by default for this USB device" will be popped up before each stream, even if "remember" is checked and permissions are given, I will also ask. The action of popping the window will hinder entry into the game, causing various failures.

Can moonlight not pop up the window and automatically authorize? Because this is very important to me, it is a crucial step to use the vibrating gamepad happily.

Thank you very much! ! !

**Comment by cgutman** [comment]
It is not possible to avoid the authorization dialog each time. This is an Android limitation.

I could make the dialog appear earlier though.

**Comment by shinobiz** [comment]
> 每次都无法避免授权对话框。这是Android限制。
> 
> 我可以让对话框显示得更早。

Wow! Great!

As long as the window does not appear at the moment of the start of the stream. That way, the startup process of the stream will not be interrupted.

Thank you!

**Comment by shinobiz** [comment]
But can the 2.4G gamepad be automatically disconnected shortly after entering the game? I found that it was not the disconnect between the gamepad and the adapter, but the disconnect between the adapter and the Android device. This problem is not available on the PC, and the steam link is also normal.

In addition, I also tested the PS3 gamepad and the XBOX ONE S gamepad with the 8Bitdo USB wireless adapter, which works very well and won't break.

**Comment by enginmanap** [comment]
Hi, 

I have the same issue with a bluetooth controller (ipega red knight-9087). Phone is a Oneplus 7 pro with android 9.

It works as expected on other applications, but on moonlight it disconnects after 15 seconds or so. 

Tested with both "Xbox 360/One controller driver" and "Override Android controller support" enabled, only first one enabled, and both disabled. All the tests behave the same.
