### ISSUE TITLE
Can you add a hidden virtual game rocker?

### ISSUE THREAD

**Issue by 8116453** [moonlight-stream/moonlight-android#691]
Now a lot of hand-swimming is using this kind of rocker operation. When you click on the screen, it will appear and stop touching the screen, it will disappear. On the one hand, it can improve the visual space of the screen. On the other hand, it may solve the problem of rocker drift and improve the game experience. Now moonlight supports mobile data connection to play big games anytime and anywhere. I think it would be quite different if I had a game handle in my pocket (although the experience of the handle would be better), but it would be a good decision to update the virtual controller.

**Comment by thw0rted** [comment]
I really like the idea of relative positioning for the analog sticks -- a lot of mobile games have picked this up, and it makes movement a lot more consistent for me.  I think that could probably be considered a separate suggestion from making the analog stick "invisible", but it makes sense to do both at once.

**Comment by 8116453** [comment]
It would be perfect if moonlight could implement a hidden rocker! Hope that great programmers can achieve this function in the future!

**Comment by 8116453** [comment]
https://github.com/QiangZou/Joystick     I have some code for the rocker in the "King's Glory Tour". Are you interested in studying it?

**Comment by 8116453** [comment]
I have some code for the rocker in the "King's Glory Tour". Are you interested in studying it? Here are links

**Comment by 8116453** [comment]
https://github.com/QiangZou/Joystick

**Comment by 8116453** [comment]
In fact, GTA SA mobile version of the control rocker is a good choice, can automatically hide, click will appear, unfortunately I do not have source code!
