### ISSUE TITLE
Mirroring Moonlight

### ISSUE THREAD

**Issue by XFNeo** [moonlight-stream/moonlight-android#692]
Hi all! Is it real to mirror my phone(samsung s6) display with moonlight app to TV?
I used Smart View on my phone, but video and sound started freezing on my phone and TV too.

**Comment by cgutman** [comment]
Moonlight is already a pretty demanding application on your network connection. I believe Smart View uses the wireless connection to stream to your TV, so it could cause enough activity on your network connection to cause Moonlight to start dropping frames.

You could try lowering your bitrate, but it's possible that Smart View just isn't designed to mirror video-heavy apps.
