### ISSUE TITLE
Black Screen - Audio Only

### ISSUE THREAD

**Issue by Kung-Foo-Kamel** [moonlight-stream/moonlight-android#693]
Issue: Black screen with any game audio works fine

Client: Android TV

Connection: Gigabit lan

Note:

Steam Link on same device works fine, I also had an nVidia Shield connected to the same setup and also worked flawlessly, for many years.

PC/Server is connected to a HT receiver and a projector, receiver is on, projector is off, has worked over several years with this configuration on several nVidia Shields throughout my house.

If I turn the projector on, and run a game I still get a black screen, if I switch a game to window mode, with projector on, the game works, but with the windows start bar and other crap over the top of the game, so game is not in focus and thus, still not playable.

Not sure what the difference is with the Shield's client vs Moonlight, but it always worked really great and never had to have a monitor connected or on for that matter.

Funny though, Steam PC to Steam PC streaming in the past always needed the monitor on, or a dummy HDMI dongle connected in order to work, but now Steam Link app does not require any such workaround.

**Comment by Kung-Foo-Kamel** [comment]
To add to this:

I installed teamveiwer and checked out the detected display, and my screen has been detected properly, even when switched off.

But now, after installing teamveiwer, Gamestream is now working fine, still having issues with one game, but all others are working fine, and this is with the display and the HT receiver switched off.

Not sure why it works now after installing teamveiwer, but I was taught to not look a gift horse in the mouth!

**Comment by thw0rted** [comment]
Headless Windows behavior has always been a little crazy. It's good to know about Teamviewer helping -- I don't think they actually install a virtual monitor or anything, or at least I've never seen one show up in the device manager, but it can be an option before people go out and buy a dongle.

**Comment by Kung-Foo-Kamel** [comment]
I spoke to soon, everything is now streaming to my iMac perfectly (wasn't earlier), but alas, not to the Android TV, so the issue is still happening.

**Comment by Kung-Foo-Kamel** [comment]
Just installed the latest android from here and still the same, the latest app on my Mac works perfectly, but not on Android, I might give it a quick go on IOS and see what happens.

**Comment by Kung-Foo-Kamel** [comment]
Ubuntu on an Atom based PC also works, 1080p is as slow as cold molasses, but 720p works perfect

So there must be an issue with the Android client.

Summery with Host PC screen off
iMac works
Macbook works
Ubuntu x86 works
Iphone IOS works
Android fails to stream video

**Comment by schlitzbull** [comment]
I've recently setup moonlight again (not my first time) and having the same issue. I'm able to connect, view my game list, the handshake completes, then black screen. 

Client is a S8+ running Android 9. 

Thanks!

**Comment by PedroC1999** [comment]
I'm also getting this issue and am able to help debug it

**Comment by cvandermeer** [comment]
I have the same issue on a steam link with the latest version. (1.1.1)
