### ISSUE TITLE
Stretch video to 4:3 aspect ratio options? (request)

### ISSUE THREAD

**Issue by blass0009** [moonlight-stream/moonlight-android#694]
I used to play some retro games which has 4:3 aspect ratio,

I try to set desktop resolution to a native 4:3 ratio, and moonlight streaming a nice 4:3 desktop video, but when I press alt + enter to full screen the game, streaming video ratio became 16:9, which my desktop monitor still stay 4:3 ratio.

I noticed there is an option "stretch video to full screen",
 so is there any chance add an option to stretch video to 4:3 aspect ratio?

**Comment by czarekkwasny** [comment]
Yes it's a great feature request. Even if streaming is limited to 16:9 resolutions, "stretching" to 4:3 aspect ratio would allow to play at resolution of say 1440x1080 with black letterbox on sides in full-screen...
