### ISSUE TITLE
Support Steam Controller via Bluetooth Mode

### ISSUE THREAD

**Issue by thw0rted** [moonlight-stream/moonlight-android#696]
## Background

A few months ago, the Steam Link app launched on Android alongside a beta firmware for Steam Controllers that enables a custom Bluetooth mode.  When connected via Bluetooth, the controller defaults to what the community has taken to calling "lizard mode", where it emulates a mouse/keyboard, with the ability to move an onscreen cursor, "click" with it (using the right trigger), or emulate a Back button press (with left trigger), and not much else.  Somehow, the Steam Link app is able to put the controller into "data mode", where it reads inputs and forwards them to the host PC, to be treated as a local Steam Controller.

## Request

I'd like to have Moonlight put the controller in "data mode" and map the relevant inputs to the corresponding 360 gamepad inputs.  The left trackpad should have clicks mapped to the D-pad, the analog stick should pass through as the left stick, the right trackpad should emulate the right stick (might be the hardest part?), and the buttons and triggers should map through 1:1.  Moonlight could offer some customization for how the grip buttons work, or just not support them at all.

As an aside, I don't know how to enter "data mode" but I'm reading about it and will update this thread if I find anything useful.

## Why is this a new issue?

Several previous issues have brought up the Steam Controller, usually from before the Bluetooth firmware launched.  I believe the controller is already usable by either connecting directly to the host PC, or by using something like VirtualHere to relay raw USB data.  I'd like to try to support Bluetooth mode "natively", to the extent that's practical.

**Comment by thw0rted** [comment]
First lead: there's a 3rd party Linux mapping tool that appears to have successfully added BT support.  There are a number of commits connected to [this issue](https://github.com/kozec/sc-controller/issues/365) that include HID write commands to switch modes.  I think that this would be the first case of Moonlight directly sending packets to a BT device, and presumably it's something you'd want to have the hardware in-hand for before you start playing with it.

**Comment by thw0rted** [comment]
I don't have any more time to spend poking at this right now but I'm curious if the C parser module that `sc-controller` includes (for the HID packets) is a) sufficiently abstract that it would compile for Android/ARM without changes, and b) license compatible with Moonlight.  I'm pretty sure (b) is true, and as for (a), if it isn't drop-in ready, @kozec might be willing to help since he appears to be actively working on porting the rest of that project to C.

**Comment by klepp0906** [comment]
has this been looked into any further? just ran up against this wall tonight and found this via google.  I swear.. on one hand, the steam controller is so powerful its insane.   On the other, no controller has ever created more problems.  argh.

**Comment by thw0rted** [comment]
I think the issue is that the Xbox 360 gamepad kind of "won" Windows gaming at least a decade ago, and the Steam controller was the first serious challenge to that.  Various standards have kind of baked-in the idea that a "normal" pad will have two analog sticks, a d-pad, and 12 buttons.  Start adding stuff like touchpads and tilt sensors and you lose the ability to use higher-level APIs; you wind up having to customize for a specific controller.

There's an argument to be made that standardization is a good thing, certainly.  I dimly remember playing games in the mid-90s where instead of having "Gamepad: On/Off" in the settings menu, you had a selection from 4-5 different options -- is it a pad or a stick?  2 buttons, 4, 6, 8?  I don't begrudge developers for defaulting to the standard, I'd just like to at least be able to *emulate* the standard with this fancy new controller.

**Comment by thw0rted** [comment]
Oops, I missed this.  I'd still like to see it supported, if possible.  I don't think I can reopen it but maybe the bot will now that there's activity?

(It's kind of a selfish request -- I have a phone clip for my Steam Controller but not my DS4, so I actually use Steam's streaming more than Moonlight now, just because the controller I attach to my phone works there but not here.)
