### ISSUE TITLE
Error when running the game: GFE error: Cannot launch the game since NVFBC isnot supported. (Error code:529)

### ISSUE THREAD

**Issue by FA9US** [moonlight-stream/moonlight-android#70]
Samsing i9505 lollipop 5.0.1 samsung official. i can see the library. when running the game it says GFE error: Cannot launch the game since NVFBC isnot supported. (Error code:529)

system:
windows 7 64 bit
MSI gtx970 100 me
nvidia driver: 350.12﻿

i can provide logs if anything requested

**Comment by FA9US** [comment]
Update: works with 2.2.2  older versions do not have NVFBC.dll therefore there is no need for this module. confirmed working.

**Comment by niklaskorz** [comment]
Same issue here with the MSI GTX 970 Gaming 4G

**Comment by fredrikmadsen** [comment]
Got the issue too, I can see the list and pair is also good, but some issues with stream

Starting Steam
com.limelight.nvstream.http.GfeHttpResponseException: GFE error: Cannot launch the game since NVFBC is not supported. (Error code: 529)
Connection Error Starting Steam failed

**Comment by fredrikmadsen** [comment]
Never mind, after rebooting my pc it worked.

**Comment by cgutman** [comment]
I've seen this once too. A reboot cleared it up for me too.

**Comment by UrsuGrizzly** [comment]
I am getting this restarted 4 times and didnt solve it :( It works fine without moonlight
