### ISSUE TITLE
Possible commercial fork? (XR Gaming)

### ISSUE THREAD

**Issue by leoleotte** [moonlight-stream/moonlight-android#700]
I've seen an ad for this app that promises VR games using nvidia's streaming, just like moonlight does.. and the settings and buttons are almost the same as moonlight for Android, I was wondering if the license permits this? I looked and haven't seen any mention of this source on the app/website.

Here's the link if anyone is interested in looking: http://www.xralpha.co

If this is all right, please close this ticket.. (I didn't know where to post it, really)

**Comment by irtimmer** [comment]
Thanks for reporting. I can confirm the application contains code from the Moonlight Stream project. While the license (GPL-3) does allow commercial use (even selling the software) it requires to disclose the changed source code and a license and copyright notice. This doesn't seems to be the case.

Therefore as a contributor to the moonlight-common-c code, I have send a DMCA notice to Google to take down the Play Store listing at https://play.google.com/store/apps/details?id=com.realified.xr
