### ISSUE TITLE
M8S Plus with Android 5.1

### ISSUE THREAD

**Issue by BashBoss** [moonlight-stream/moonlight-android#705]
Hey I am using Moonlight and I somehow get 100 ping+ on 720p or even 1080p as well as input lag. I am using 5GHz on host and Android TV box.

**Comment by J4ves** [comment]
Likewise on my Amlogic S905X Small Rocket X2 box, I get 100+ ping on 720p60. 

I think it's an issue with Amlogic Chinese boxes in general?

I was thinking of getting the Mecool KM3 to replace it, which uses an Amlogic S905X2, but if the same problem is going to happen, I won't bother.
