### ISSUE TITLE
Fire TV Stick 4K or Mecool KM3 (Amlogic S905X2) for Moonlight?

### ISSUE THREAD

**Issue by J4ves** [moonlight-stream/moonlight-android#706]
Which of these performs best for Moonlight? (assuming we're using Ethernet for both)

**Comment by MopheusDG** [comment]
Don't get a Fire TV Stick, I tested on Fire TV 4K (big one) and Fire TV Stick not 4K and both have too much delay and I think they were not able to solve it yet. It's amazing the diference with a Raspberry or other devices.... at least for me.

**Comment by brozeki** [comment]
> Don't get a Fire TV Stick, I tested on Fire TV 4K (big one) and Fire TV Stick not 4K and both have too much delay and I think they were not able to solve it yet. It's amazing the diference with a Raspberry or other devices.... at least for me.

What is the delay you get on raspberry pi ?

**Comment by VideoPlayerCode** [comment]
@J4ves Huh, "the delay I am getting is 35mbps" ? That is bandwidth, not delay.

For the record, FireTV Stick 4K is PERFECT with Moonlight. Nothing could be any more perfect! 

My settings: 1080p, 60FPS, HEVC (H. 265), HDR, video bitrate 50000kbps (50 Mbit).

Connection: Wireless AC/N on both the computer and receiver.

Computer Graphics: RTX 2070.

Video quality: Sharp enough to see individual pixels. Zero artifacts. Looks as good as HDMI.

Latency (via Moonlight statistics overlay): 1.4ms per frame (transfer), and then 24ms per frame to decode them on the FireTV.

Assuming that you meant to write 35ms above, we can see that FireTV is 50% lower latency (faster) than Mecool.

Hope this helps.

**Comment by J4ves** [comment]
Nah, the Shield TV is objectively the best method for streaming your PC, better than HDMI in most cases even, and has the best UI for it, that nVidia have properly integrated in to Android TV. Rule of thumb for cord cutters: buy a Shield TV first as your primary media streamer/ emulation box, then buy a Mecool/FireTV as a secondary box for the other room.

Likewise, with the Mecool, Moonlight is well implemented in to the home screen of Android TV, and is a slicker way to launch PC games than with any thing you mentioned with the Fire TV, which is still very dependent on sideloading, and doesn't have official Google Play TV Store like the Mecool. 

I have the Shield TV and the Mecool as a secondary box; the latency of the Mecool compared to the Shield is noticeable, but it's very slight, and really not that bad. I don't play anything competitive through streaming, so it's never a big issue anyway.

**Comment by VideoPlayerCode** [comment]
Well this just shows how misinformed you are about the FireTV.

FireTV has Moonlight on the Amazon App Store. No sideloading is needed. Automatic updates via store. Always latest version automatically.

Furthermore the FireTV has 50% less Moonlight decoder latency than the MeCool. So it's a far better choice for someone who isn't gonna buy a Shield TV.

By the way I have a Shield TV now. And Moonlight is a picture-bar on the Android TV homescreen which lists the last-opened Moonlight games (for me, Steam Big Picture), which saves 1 click. But on FireTV you do 2 clicks (open Moonlight then open Steam Big Picture). Really, it's not worth getting a Shield TV just to save 1 click.

Anyway whatever, happy that you like your device. I'm out of this conversation and have already posted numbers for FireTV latency etc above. I'm done.

**Comment by J4ves** [comment]
No, it's still not. The average latency I'm getting nowadays is around 25-29mbps on the Mecool KM3. And realistically, no one will ever be hooking up their mouse/keyboard to their Fire TV for PC games, so what tiny bit of lag there is, is very unnoticeable when the games are played via a gamepad, from a 10ft TV distance. 

With that out of the way, it all becomes about the experience. 

You were objectively wrong to say Moonlight is a 2 click experience on the Fire TV, if we're talking about navigating to Steam: it's one click to open the app, then another click to select the PC, then further scrolling clicks to navigate to Steam and another click to start it - as opposed to the single 1 click to launch Steam from the recent Moonlight list on Mecool's Android TV homescreen. 

You also have to hook up a ton of extra peripherals to match the KM3, such as a USB hub, Lan adapter, 64GB storage, etc, and it still won't have 4GB ram like the KM3. At that point, you're nearing double the price of the KM3, and you might as well just save a bit more and get a Shield TV, instead.

The Fire TV, even though it's Android based, still feels like a closed platform, with lots of Prime content being shoved down your throat.

You can't get the same emulators and other cool stuff from the Play Store from Amazon's marketplace, either.  

One of the best things about the Mecool, is that it's basically like have a mini/cheaper version of the Shield, and all your paid apps are available across both.  

But yeah, the Mecool KM3 is objectively the all round better experience for streaming your games compared to the Fire TV.
