### ISSUE TITLE
Mouse too fast when using native capture

### ISSUE THREAD

**Issue by ddscentral** [moonlight-stream/moonlight-android#709]
Mouse is way too fast and is hard to control when using native capture driver under Lineage OS 16 (Android 9.0 Pie).
My device is a Lenovo TB-X704L, streaming at 1920x1200 if that matters. Mouse and keyboard are connected via Bluetooth.
Reverting to the old root evdev capture method makes the mouse completely usable.

**Comment by cgutman** [comment]
This was implemented in 81a3bbd5e8ba07990d901c0b6d77276c8ee43b1b. Unfortunately, there is still no API to ask for unaccelerated mouse motion as of Android 13.
