### ISSUE TITLE
No Sound on Chrome and Internet Explorer while using Moonlight as Remote Desktop

### ISSUE THREAD

**Issue by xmassound** [moonlight-stream/moonlight-android#71]
I followed link and has no problem using moonlight as Remote Desktop except sound issue.
https://forums.geforce.com/default/topic/724672/tips-and-tricks/tnt-how-to-play-pc-games-that-don-rsquo-t-have-native-controller-support-/

Any app that I open on windows works great WITH sound(iTunes, Spotify, games etc.) except internet browsers such as Google Chrome or IE. Any web players on chrome has no sound at all. I tried vimeo, and youtube but no luck with sound. Also, I toggled on/off "Play Sound on PC' on basic settings from moonlight. Lastly. I tried all sound settings from "C:\Windows\System32\mstsc.exe" still no luck.

I'm not sure if this is GFE bug or moonlight but still wanted to share if you guys could fix it.
Thank you for great app!

FIRE TV
Windows 8.1
GFE 2.4.121
Monnlight Root Version 3.1.5

**Comment by HeXDeMoN** [comment]
I made a account to just reply to this, I like to stream my pc browser to my firetv to watch content I just can't get to work with a mobile browser.  So add me to the list that would love this fixed /corrected /added. Thanks for your hard work and time.

**Comment by cgutman** [comment]
GFE 2.4 changed the way they're doing audio capture which broke sound over remote desktop. It's a known bug that Shield owners are also experiencing. 
https://forums.geforce.com/default/topic/813691/?comment=4469883
https://forums.geforce.com/default/topic/827837/gamestream/remote-desktop-audio-not-going-to-tablet/

**Comment by xmassound** [comment]
cgutman, thanks for the info. Hopefully, it will get fixed by next GFE update.

**Comment by FA9US** [comment]
@cgutman does GFE 2.4  work with moonlight? i had to downgrade to 2.2.2 to be able to use my android device. on 2.4 i get dll errors in android version of the app
