### ISSUE TITLE
GFE Cannot Configure Streamer (error code: 544)

### ISSUE THREAD

**Issue by BobbyDeity** [moonlight-stream/moonlight-android#710]
When I try to start any game on my smartphone, I get the error code 544.
![image](https://user-images.githubusercontent.com/51509681/59147856-73aa0c00-8a33-11e9-82e8-26241260ab88.png)

I tried using other devices such as my laptop or tablet.
My tablet was the only one able to connect. Edit: Now the tablet does not work too.
My tablet was a Samsung Galaxy Tab 3 (which is very old). I'm using a Samsung Galaxy S8+ to connect via moonlight originally.

Devices: Samsung Galaxy Tab 3, Samsung Galaxy S8
Versions:              4.4.2              ,              9.0

Streaming Device: 
MSI GE62 2QF Apache Pro
GFE: 3.19.0.94
GPU: GTX 970M
Driver Version: 430.86
CPU: i7-5700HQ CPU @ 2.70GHz
Ram: 15.92 GB
Windows 10

Logs:
[NvStreamerCurrent.log](https://github.com/moonlight-stream/moonlight-android/files/3268586/NvStreamerCurrent.log)

Thank You

**Comment by lunalik2** [comment]
How did you fix this?
