### ISSUE TITLE
No mouse cursor in Mass Effect 3

### ISSUE THREAD

**Issue by svaningelgem** [moonlight-stream/moonlight-android#711]
Hello,

I recently saw Moonlight and was very interested in it as an alternative to Steam In-home streaming. My host pc is a gaming rig without a screen, but with a mouse attached via USB (no keyboard attached).
I have enabled mouse keys as an advice to ticket #198, but that didn't seem to do anything (even not after a reboot).
EDIT: I plugged in an USB keyboard, no noticeable changes to any of the following points.

So I will shortly describe my issues:
1. I don't have a mouse cursor in Mass Effect 3. I have a screen and audio which seems correct (resolution is not correct yet, but I can see things). But I don't have the cursor. Moving the mouse seems to work as clicking does, but I don't see the visual aid of where the actual cursor is.
2. Assassin's Creed Oddyssey: screen stays black. No mouse, No screen, just audio.
3. Hitman: same issue as (2).

What information could I deliver so you could help me help you?

Thanks!

**Comment by thw0rted** [comment]
Have you checked [the wiki](https://github.com/moonlight-stream/moonlight-docs/wiki/Troubleshooting#no-video-black-screen)?

**Comment by svaningelgem** [comment]
Yes, I did now :-).

I didn't ask for help yet, but I did order the headless dongle which should arrive tomorrow. That will probably rule out the black screens and even maybe the mouse cursor in ME3 if this is painted a certain way on the screen.

I'll keep this ticket updated with my progress.

**Comment by thw0rted** [comment]
The whole display-detection thing in Windows is pretty weird.  I use Moonlight, Steam Link, and Teamviewer to connect to my media PC which is hooked up to a TV over HDMI as its only display.  It's kind of hit or miss whether I have missing mouse cursor issues, and sometimes it seems to relate to which input was selected on the TV before I turned it off (!!), so I haven't figured it all out yet.  I hope the dongle helps!

**Comment by svaningelgem** [comment]
I can confirm now that with the HDMI dongle I have screen and mouse in Assassin's Creed.
But Mass Effect 3 still has no mouse... Well, it had sort of for a few seconds. 2nd try it had a mouse.

So for people having similar issues: buy a HDMI dongle :-)
