### ISSUE TITLE
can't connect to pc in android over simcard internet

### ISSUE THREAD

**Issue by moseiei132** [moonlight-stream/moonlight-android#719]
I forward all port request and i can connect to pc over internet from another pc but my android can connect only in local wifi I'm try to use 4g internet it's can't connect but I'm share 4g hotspot to my laptop. It's can connect to my pc.

Sorry for bad english.

**Comment by M-R-Z-X** [comment]
I have the same problem as you. I've even turned off Windows's firewall,

**Comment by thw0rted** [comment]
Is it possible that your mobile carrier is blocking the ports in question?  You can check if the ports are accessible using standard network utilities like telnet / netcat (`nc`), but that's outside the scope of this issue tracker.  If you can isolate it to a Moonlight-specific issue, you can comment here about that, but it sounds like it's likely to be a problem at the network level and you'd need to address it yourself.
