### ISSUE TITLE
Bluetooth mouse not capturing properly on Nexus 7 client - supported?

### ISSUE THREAD

**Issue by aserna3** [moonlight-stream/moonlight-android#72]
Hello,

I'm running the latest (play store) client of Moonlight on my 2012 Nexus 7 (4.4.4, SlimROM if relevant)

When trying to use my mouse to click on anything, it doesn't work properly, the actual mouse is very out of sync to where the host's cursor is, if I start steam I can't actually navigate to my library, clicking does nothing (neither does tapping) and in games, the mouse will stop moving the camera if it hits the edge of the display (Which should be hidden anyways).

I understand the wiki doesn't actually mention a keyboard and mouse setup being supported, so am I just to assume that work hasn't really gone into this to support this setup?

Controller support works fine at least.

**Comment by cgutman** [comment]
This is fully supported with the root version of Moonlight. It's on the Play Store as "Moonlight for Rooted Devices".

The clicking bug within Steam is just a bug in Big Picture over GameStream. When you get into a game (or launch a game directly from Moonlight), it should all work fine.

**Comment by aserna3** [comment]
Thanks.
