### ISSUE TITLE
Add an Android TV home screen channel

### ISSUE THREAD

**Issue by 420blazit** [moonlight-stream/moonlight-android#721]
On Android TV, Nvidia's gamestreaming app has a home screen channel with your game library -
https://files.catbox.moe/uwqldp.png (see row 3)

I think this would be a nice addition to Moonlight?

Here's the documentation for home screen channels -
https://developer.android.com/training/tv/discovery/recommendations-channel

**Comment by cgutman** [comment]
Already live in v8.0
