### ISSUE TITLE
Shortcut problem on Nvidia shield tv

### ISSUE THREAD

**Issue by bubuleur** [moonlight-stream/moonlight-android#728]
Hello,
I come to you I have a problem with the shortcut of Moonlight on my nvidia shield tv of 2017 I downloaded the last update of the nvidia and since the update I have the logo which does not have any more yet I uninstall the moonlight application and reinstall the latest version I still have the same problem you know where it can come from?
![Accueil d'Android TV_20190805_235749](https://user-images.githubusercontent.com/21688137/62529461-fafeda80-b83e-11e9-98d2-6d6e05a6bbae.png)

**Comment by cgutman** [comment]
Interesting. The cause was that the Android TV banner drawable was not in the xhdpi folder where it belonged. This has been wrong since the original Android TV work years ago but didn't cause a problem until Pie.

**Comment by bubuleur** [comment]
okay how to fix this problem?

**Comment by bubuleur** [comment]
Up please
