### ISSUE TITLE
Generic gamepad - no input after connected to pc

### ISSUE THREAD

**Issue by Zuboskalik** [moonlight-stream/moonlight-android#729]
Hello. 
I'm using "generic" gamepad Logitech Rumblepad 2
Tablet is Acer A511, Android 4.1.2
PC with Windows 10 64bit, 1809

It works perfect when I connect it directly to PC - Steam BP recognizes it as "Generic Gamepad" and I can play
It works when I connect it to the tablet via cable - it works, I can navigate through menus and play gamepad-supporting games and emulators - even can use moonlight like "select game to launch"

But when Tablet+gamepad are connected to PC via Moonlight Stream - gamepad (in Steam Big Picture) becomes "unregistered: Xbox 360 gamepad" and no input works - only left stick to navigate between buttons - even when I manually entered "remapping" menu and tried to configure gamepad - Steam getting no inputs, like I press nothing

I tried to enable/disable "Override controller" and "Gamepad driver" in Moonlight Settings - no effect
Tried X360 and Generic gamepad checkboxes configuration support in Steam BP settings - no effect

When I tried to use "normal" X360 gamepad - it works w/o any troubles, I just can't get "Generic" gamepad to work with PC when it connected to Tablet + Moonlight streaming

Any advices to get Gamepad to work with Moonlight Streaming?

**Comment by Zuboskalik** [comment]
Update: Same thing, when trying to use gamepad in every else app via Moonlight. In CEMU, when connected via USB to PC, it detected as usual and can be mapped. When connected to tablet with Moonlight - detected as "Xbox 360 gamepad" and detects only sticks and D-Pad input - no buttons

**Comment by elPatrixF** [comment]
Bump, same issue. It would be very convenient if I was able to use a generic USB Gamepad too.

Currently I have no trouble getting a bluetooth controller because it uses the XBOX keycodes (96 through 109) but it would be also convenient if keycodes for generic buttons were also available (It's android keycodes 118 through 203). They could be directly mapped to the windows directinput buttons within the same device?
