### ISSUE TITLE
1440p 60fps in resolution options?

### ISSUE THREAD

**Issue by eligrey** [moonlight-stream/moonlight-android#73]
I'm able to use my GTX 680's hardware encoder with Steam in-home streaming to stream 1440p 60fps GTA V gameplay to my 2015 XPS 13 over wifi without noticeable lag. Is it possible to do the same with Moonlight on Android?

**Comment by cgutman** [comment]
You'll have to stream 1080p60 right now (assuming your network and device can handle it). 1440p will be coming in a future update.

**Comment by eligrey** [comment]
Alright thanks. Good to know that it's planned for an eventual future update.
