### ISSUE TITLE
Failed To Start Control Stream Establishment

### ISSUE THREAD

**Issue by tekcap** [moonlight-stream/moonlight-android#732]
This message appears when I try to open up a game, but only happens when connected remotely through openvpn connection. If I'm on the same wifi network, everything works as expected.

Here is the relevant information from log file on my PC

`#7(I)[2019-08-26 01:07:47,838]=21:07:47={00002080}<Server>           RTSP handshake successfully completed
#8(I)[2019-08-26 01:07:47,838]=21:07:47={00002080}<Server>           Update log level from 1 to 2
#9(I)[2019-08-26 01:07:47,838]=21:07:47={00002080}<Server>           Updated log level to : 2
#0(I)[2019-08-26 01:07:47,838]=21:07:47={00002080}<EtwUtilities>     Closing trace session
#1(I)[2019-08-26 01:07:47,844]=21:07:47={00002080}<Server>           Server trace is stopped
#2(I)[2019-08-26 01:07:47,844]=21:07:47={00002080}<StreamSdkEvents>  Raising event for stream of type NVST_MT_MIC: NvstEventDetail::NVST_ED_CLIENT_CONNECTED, message = 'automode=1,'
#3(I)[2019-08-26 01:07:47,844]=21:07:47={00002080}<StreamSdkEvents>  Raising event for stream of type NVST_MT_AUDIO: NvstEventDetail::NVST_ED_CLIENT_CONNECTED, message = 'automode=1,'
#4(I)[2019-08-26 01:07:47,844]=21:07:47={00002080}<StreamSdkEvents>  Raising event for stream of type NVST_MT_VIDEO: NvstEventDetail::NVST_ED_CLIENT_CONNECTED, message = 'automode=1,'
#5(I)[2019-08-26 01:07:47,844]=21:07:47={00002080}<StreamSdkEvents>  Raising event for stream of type NVST_MT_INPUT: NvstEventDetail::NVST_ED_CLIENT_CONNECTED, message = 'automode=1,'
#6(I)[2019-08-26 01:07:47,844]=21:07:47={00003D9C}<StreamSdkEvents>  Invoking clientEventCallback NvstEventDetail::NVST_ED_CLIENT_CONNECTED: automode=1,
#7(I)[2019-08-26 01:07:47,844]=21:07:47={00002080}<RtspServerObserv> Observer PLAY: result 200
#8(I)[2019-08-26 01:07:47,844]=21:07:47={00003D9C}<SciBase>          Sent event ClientConnected: automode=1,
#9(I)[2019-08-26 01:07:47,844]=21:07:47={00003D9C}<StreamSdkEvents>  Invoking event for stream of type NVST_MT_MIC: NvstEventDetail::NVST_ED_CLIENT_CONNECTED, message = 'automode=1,'
#0(I)[2019-08-26 01:07:47,844]=21:07:47={00003D9C}<NvStreamerContex> StreamEventRaised
#1(I)[2019-08-26 01:07:47,844]=21:07:47={00003D9C}<StreamSdkEvents>  Invoking event for stream of type NVST_MT_AUDIO: NvstEventDetail::NVST_ED_CLIENT_CONNECTED, message = 'automode=1,'
#2(I)[2019-08-26 01:07:47,844]=21:07:47={00003D9C}<NvStreamerContex> StreamEventRaised
#3(I)[2019-08-26 01:07:47,844]=21:07:47={00003D9C}<StreamSdkEvents>  Invoking event for stream of type NVST_MT_VIDEO: NvstEventDetail::NVST_ED_CLIENT_CONNECTED, message = 'automode=1,'
#4(I)[2019-08-26 01:07:47,844]=21:07:47={00003D9C}<NvStreamerContex> StreamEventRaised
#5(I)[2019-08-26 01:07:47,844]=21:07:47={00003D9C}<StreamSdkEvents>  Invoking event for stream of type NVST_MT_INPUT: NvstEventDetail::NVST_ED_CLIENT_CONNECTED, message = 'automode=1,'
#6(I)[2019-08-26 01:07:47,844]=21:07:47={00003D9C}<NvStreamerContex> StreamEventRaised
#7(I)[2019-08-26 01:07:48,006]=21:07:48={00002080}<RtspServerObserv> Observer request data: URL streamid=audio, host 0.0.0.0, client ID 10.8.0.6, CSEQ 8
#8(I)[2019-08-26 01:07:48,006]=21:07:48={00002080}<RtspServerObserv> Observer PLAY: session ID 1566781666
#9(I)[2019-08-26 01:07:48,006]=21:07:48={00002080}<RtspHandshake>    RtspHandshake::onRtspPlay : handling request: 8 1566781666
#0(I)[2019-08-26 01:07:48,006]=21:07:48={00002080}<Server>           RTSP handshake successfully completed
#1(I)[2019-08-26 01:07:48,006]=21:07:48={00002080}<Server>           Update log level from 2 to 2
#2(I)[2019-08-26 01:07:48,006]=21:07:48={00002080}<Server>           Updated log level to : 2
#3(I)[2019-08-26 01:07:48,006]=21:07:48={00002080}<Server>           Server trace is stopped
#4(I)[2019-08-26 01:07:48,006]=21:07:48={00002080}<StreamSdkEvents>  Raising event for stream of type NVST_MT_MIC: NvstEventDetail::NVST_ED_CLIENT_CONNECTED, message = 'automode=1,'
#5(I)[2019-08-26 01:07:48,006]=21:07:48={00002080}<StreamSdkEvents>  Raising event for stream of type NVST_MT_AUDIO: NvstEventDetail::NVST_ED_CLIENT_CONNECTED, message = 'automode=1,'
#6(I)[2019-08-26 01:07:48,006]=21:07:48={00002080}<StreamSdkEvents>  Raising event for stream of type NVST_MT_VIDEO: NvstEventDetail::NVST_ED_CLIENT_CONNECTED, message = 'automode=1,'
#7(I)[2019-08-26 01:07:48,006]=21:07:48={00002080}<StreamSdkEvents>  Raising event for stream of type NVST_MT_INPUT: NvstEventDetail::NVST_ED_CLIENT_CONNECTED, message = 'automode=1,'
#8(I)[2019-08-26 01:07:48,006]=21:07:48={00003D9C}<StreamSdkEvents>  Invoking clientEventCallback NvstEventDetail::NVST_ED_CLIENT_CONNECTED: automode=1,
#9(I)[2019-08-26 01:07:48,006]=21:07:48={00002080}<RtspServerObserv> Observer PLAY: result 200
#0(I)[2019-08-26 01:07:48,006]=21:07:48={00003D9C}<SciBase>          Sent event ClientConnected: automode=1,
#1(I)[2019-08-26 01:07:48,006]=21:07:48={00003D9C}<StreamSdkEvents>  Invoking event for stream of type NVST_MT_MIC: NvstEventDetail::NVST_ED_CLIENT_CONNECTED, message = 'automode=1,'
#2(I)[2019-08-26 01:07:48,006]=21:07:48={00003D9C}<NvStreamerContex> StreamEventRaised
#3(I)[2019-08-26 01:07:48,006]=21:07:48={00003D9C}<StreamSdkEvents>  Invoking event for stream of type NVST_MT_AUDIO: NvstEventDetail::NVST_ED_CLIENT_CONNECTED, message = 'automode=1,'
#4(I)[2019-08-26 01:07:48,006]=21:07:48={00003D9C}<NvStreamerContex> StreamEventRaised
#5(I)[2019-08-26 01:07:48,006]=21:07:48={00003D9C}<StreamSdkEvents>  Invoking event for stream of type NVST_MT_VIDEO: NvstEventDetail::NVST_ED_CLIENT_CONNECTED, message = 'automode=1,'
#6(I)[2019-08-26 01:07:48,006]=21:07:48={00003D9C}<NvStreamerContex> StreamEventRaised
#7(I)[2019-08-26 01:07:48,006]=21:07:48={00003D9C}<StreamSdkEvents>  Invoking event for stream of type NVST_MT_INPUT: NvstEventDetail::NVST_ED_CLIENT_CONNECTED, message = 'automode=1,'
#8(I)[2019-08-26 01:07:48,006]=21:07:48={00003D9C}<NvStreamerContex> StreamEventRaised
#9(I)[2019-08-26 01:07:48,668]=21:07:48={000042C0}<NattHolePunch>    NattHolePunch: Failed to receive ping on port 48000: Timeout.
#0(I)[2019-08-26 01:07:49,668]=21:07:49={000042C0}<NattHolePunch>    NattHolePunch: Failed to receive ping on port 48000: Timeout.
#1(I)[2019-08-26 01:07:50,669]=21:07:50={000042C0}<NattHolePunch>    NattHolePunch: Failed to receive ping on port 48000: Timeout.
#2(I)[2019-08-26 01:07:51,670]=21:07:51={000042C0}<NattHolePunch>    NattHolePunch: Failed to receive ping on port 48000: Timeout.
#3(I)[2019-08-26 01:07:52,670]=21:07:52={000042C0}<NattHolePunch>    NattHolePunch: Failed to receive ping on port 48000: Timeout.
#4(I)[2019-08-26 01:07:53,670]=21:07:53={000042C0}<NattHolePunch>    NattHolePunch: Failed to receive ping on port 48000: Timeout.
#5(I)[2019-08-26 01:07:54,670]=21:07:54={000042C0}<NattHolePunch>    NattHolePunch: Failed to receive ping on port 48000: Timeout.
#6(I)[2019-08-26 01:07:55,670]=21:07:55={000042C0}<NattHolePunch>    NattHolePunch: Failed to receive ping on port 48000: Timeout.
#7(I)[2019-08-26 01:07:56,671]=21:07:56={000042C0}<NattHolePunch>    NattHolePunch: Failed to receive ping on port 48000: Timeout.
#8(I)[2019-08-26 01:07:57,672]=21:07:57={000042C0}<NattHolePunch>    NattHolePunch: Failed to receive ping on port 48000: Timeout.
#9(I)[2019-08-26 01:07:58,672]=21:07:58={000042C0}<NattHolePunch>    NattHolePunch: Failed to receive ping on port 48000: Timeout.
#0(I)[2019-08-26 01:07:59,673]=21:07:59={000042C0}<NattHolePunch>    NattHolePunch: Failed to receive ping on port 48000: Timeout.
#1(I)[2019-08-26 01:08:00,673]=21:08:00={000042C0}<NattHolePunch>    NattHolePunch: Failed to receive ping on port 48000: Timeout.
#2(I)[2019-08-26 01:08:01,674]=21:08:01={000042C0}<NattHolePunch>    NattHolePunch: Failed to receive ping on port 48000: Timeout.
#3(I)[2019-08-26 01:08:02,674]=21:08:02={000042C0}<NattHolePunch>    NattHolePunch: Failed to receive ping on port 48000: Timeout.
#4(I)[2019-08-26 01:08:03,674]=21:08:03={000042C0}<NattHolePunch>    NattHolePunch: Failed to receive ping on port 48000: Timeout.
#5(I)[2019-08-26 01:08:04,675]=21:08:04={000042C0}<NattHolePunch>    NattHolePunch: Failed to receive ping on port 48000: Timeout.
#6(I)[2019-08-26 01:08:05,676]=21:08:05={000042C0}<NattHolePunch>    NattHolePunch: Failed to receive ping on port 48000: Timeout.
#7(I)[2019-08-26 01:08:05,873]=21:08:05={00000F0C}<SciBase>          Received ProcessServerCleanupVirtualHw
#8(I)[2019-08-26 01:08:05,875]=21:08:05={00000F0C}<NvAudCapAudioSou> Stopping audio redirection
#9(I)[2019-08-26 01:08:05,971]=21:08:05={00000F0C}<NvAudCapAudioSou> Closing audio source
#0(I)[2019-08-26 01:08:05,972]=21:08:05={00000F0C}<SciBase>          Received ServerStopStreaming.
#1(I)[2019-08-26 01:08:05,972]=21:08:05={00000F0C}<SciBase>          Termination reason = INTENDED (SRC_Uninitialized)
#2(I)[2019-08-26 01:08:06,677]=21:08:06={000042C0}<NattHolePunch>    NattHolePunch: Failed to receive ping on port 48000: Timeout.
#3(I)[2019-08-26 01:08:06,677]=21:08:06={000042C0}<NattHolePunch>    NattHolePunch: Received abort event on socket. Aborting pinging
#4(E)[2019-08-26 01:08:06,677]=21:08:06={000042C0}<NattHolePunch>    NattHolePunch: Failed to receive hole punching packet
#5(E)[2019-08-26 01:08:06,677]=21:08:06={000042C0}<NvscStreamingSes> Streamer unable to hole-punch audio destination
#6(I)[2019-08-26 01:08:06,677]=21:08:06={000042C0}<NvscStreamingSes> Starting teardown
#7(I)[2019-08-26 01:08:06,677]=21:08:06={000042C0}<NvscStreamingSes> Quit requested, waiting on child threads to quit
#8(I)[2019-08-26 01:08:06,677]=21:08:06={000042C0}<NvscStreamingSes> Termination reasons:
#9(I)[2019-08-26 01:08:06,677]=21:08:06={000042C0}<NvscStreamingSes> - Source 'Server', reason 'Server::setSessionManagerServerTerminationReason', code 0x0100 SERVER_TERMINATED_INTENDED
#0(I)[2019-08-26 01:08:06,677]=21:08:06={000042C0}<NvscStreamingSes> - Source 'Server', reason 'Session ended by main server', code 0x0100 SERVER_TERMINATED_INTENDED
#1(I)[2019-08-26 01:08:06,677]=21:08:06={000042C0}<NvscStreamingSes> - Source 'NvscStreamingSession', reason 'Audio hole punching failed', code 0x8100 SERVER_TERMINATED_UNINTENDED
#2(I)[2019-08-26 01:08:06,677]=21:08:06={000042C0}<ClientControl>    Client control thread terminating
#3(I)[2019-08-26 01:08:06,677]=21:08:06={000042C0}<ClientControl>    Notified the client that the server is terminating with reason 0x8100`

**Comment by cgutman** [comment]
Fixed by c251cd2e8fa1790328182a07f678a2d3f8c84cec
