### ISSUE TITLE
Issue launching applications with an separate launcher, e.g. Minecraft

### ISSUE THREAD

**Issue by PNeigel** [moonlight-stream/moonlight-android#734]
Situation: Minecraft on Windows Laptop, Moonlight on Android device. Minecraft Java Edition is directly recognized by GeForce Experience. When I launch Minecraft over Moonlight, the Minecraft Launcher opens up on my Laptop and the Android device, as it should be. I click on 'launch game' in the launcher and I see the real game start on my laptop, but I just don't see the image on the Android device. The image is stuck with the now closed launcher. Although controls still work (if I touch around in the Android device, it is registered within the game). Any hints on how I can solve this?

Edit: I also tried launching through mstsc.exe, but it's the same problem. I see the launcher on the android device, but not the launched game itself.

**Comment by PNeigel** [comment]
I found out that there is only an issue if minecraft is in fullscreen mode. If it's windows, I see it fine also on the android device. As soon as I go fullscreen, the android device shows whatever is "behind" the fullscreen, e.g. geforce experience

**Comment by stonemandave** [comment]
I have been trying to figure this out as well for Minecraft and Skyrime se
