### ISSUE TITLE
freeze after 20 seconds

### ISSUE THREAD

**Issue by amba5555** [moonlight-stream/moonlight-android#74]
I'm able to connect to my PC and play GTA V but for just 20 seconds then the video feed on my phone will freeze. So, I resume the session and the message "failed to connect to IP 192/168.1.112 port 47984" will pop up. I've already forwarded the port 47894 to my PC IP 192.168.1.112 but nothing has changed.
What should I do?
Phone : Nexus 4 + 150 mbps 2.4ghz wireless
PC : I3-4160 + GTX 960 + 100mbps Ethernet + latest gforce experience

Thank you for helpful ng me out :D

**Comment by cgutman** [comment]
Re-open if this is still an issue.
