### ISSUE TITLE
Can't stream over the internet

### ISSUE THREAD

**Issue by Razio0511** [moonlight-stream/moonlight-android#740]
Moonlight Internet Streaming Tester v4.3.0.0
The current UTC time is: 06:27:47
GeForce Experience installed and GameStream is enabled
AV products:
displayName       

Windows Defender  

Firewall products:
No Instance(s) Available.

Testing GameStream ports via loopback
Testing TCP 47984...Success
Testing TCP 47984 with HTTP traffic...Success
Testing TCP 47989...Success
Testing TCP 47989 with HTTP traffic...Success
Testing TCP 48010...Success
Testing UDP 47998...Success
Testing UDP 47999...Success
Testing UDP 48000...Success
Found ZeroTier installed
ZeroTier appears to be installed on this PC, but it's not connected to a network.

If you are trying to host with ZeroTier, connect to your ZeroTier network and restart this test.

If not, click OK and this test will continue assuming you aren't using ZeroTier.
Finding local IPv4 address...192.168.2.***
Testing GameStream ports via local network
Testing TCP 47984...Success
Testing TCP 47984 with HTTP traffic...Success
Testing TCP 47989...Success
Testing TCP 47989 with HTTP traffic...Success
Testing TCP 48010...Success
Testing UDP 47998...Success
Testing UDP 47999...Success
Testing UDP 48000...Success
Discovered UPnP IGD at: http://192.168.*.***:*****/upnp/control/WANIPConn1
Detecting WAN IP address via UPnP...145.133.***.***
Checking for UPnP port mapping for TCP 47984 -> 192.168.2.***...OK
Checking for UPnP port mapping for TCP 47989 -> 192.168.2.***...OK
Checking for UPnP port mapping for TCP 48010 -> 192.168.2.***...OK
Checking for UPnP port mapping for UDP 47998 -> 192.168.2.***...OK
Checking for UPnP port mapping for UDP 47999 -> 192.168.2.***...OK
Checking for UPnP port mapping for UDP 48000 -> 192.168.2.***...OK
Detecting WAN IP address via NAT-PMP...FAILED -100
Detecting WAN IP address via STUN...145.133.***.***
Testing GameStream ports via STUN-reported WAN address
Testing TCP 47984...Timeout
Testing TCP 47989...Timeout
Testing TCP 48010...Timeout
Testing UDP 47998...Timeout
Testing UDP 47999...Timeout
Testing UDP 48000...Timeout
Testing GameStream ports via IPv4 loopback server
Testing TCP 47984...Success
Testing TCP 47984 with HTTP traffic...Failed
Testing TCP 47989...Success
Testing TCP 47989 with HTTP traffic...Failed: 12031
Testing TCP 48010...Unknown (in use)
Testing UDP 47998...Timeout
Testing UDP 47999...Timeout
Testing UDP 48000...Timeout
Testing TCP 47984...Success
Testing TCP 47984 with HTTP traffic...Failed
Testing TCP 47989...Success
Testing TCP 47989 with HTTP traffic...Failed: 12031
Testing TCP 48010...Unknown (in use)
Testing UDP 47998...Timeout
Testing UDP 47999...Timeout
Testing UDP 48000...Timeout
Testing GameStream ports via IPv6 loopback server
Internet GameStream connectivity check failed.

Check that UPnP is enabled in your router settings. For more information and workarounds, click the Help button.

The following ports were not forwarded properly:
TCP 47984
TCP 47989
TCP 48010
UDP 47998
UDP 47999
UDP 48000

--------------- CURRENT MISS LOG -------------------
Moonlight Internet Streaming Service v4.3.0.0
The current UTC time is: 06:28:41
Woke up for periodic refresh
GameStream is ON!
Finding upstream IPv4 hops via traceroute...
Hop 0: 195.190.228.158
IcmpSendEcho() failed: 11010
Found 1 hops
Starting port mapping update on default gateway to local machine...
UPnP IPv4 IGD discovery completed with error code: 0
NAT-PMP public address request failed: -100
Found a connected UPnP IGD
UPnP IGD WAN address is: 145.133.***.***
Checking for existing UPnP port mapping for TCP 47984 -> 192.168.2.*** DESKTOP-*******...OK (14 seconds remaining)
Updating UPnP port mapping for TCP 47984 -> 192.168.2.***...OK
Checking for existing UPnP port mapping for TCP 47989 -> 192.168.2.*** DESKTOP-*******...OK (13 seconds remaining)
Updating UPnP port mapping for TCP 47989 -> 192.168.2.***...OK
Checking for existing UPnP port mapping for TCP 48010 -> 192.168.2.*** DESKTOP-*******...OK (13 seconds remaining)
Updating UPnP port mapping for TCP 48010 -> 192.168.2.***...OK
Checking for existing UPnP port mapping for UDP 47998 -> 192.168.2.*** DESKTOP-*******...OK (13 seconds remaining)
Updating UPnP port mapping for UDP 47998 -> 192.168.2.***...OK
Checking for existing UPnP port mapping for UDP 47999 -> 192.168.2.*** DESKTOP-*******...OK (13 seconds remaining)
Updating UPnP port mapping for UDP 47999 -> 192.168.2.***...OK
Checking for existing UPnP port mapping for UDP 48000 -> 192.168.2.*** DESKTOP-*******...OK (13 seconds remaining)
Updating UPnP port mapping for UDP 48000 -> 192.168.2.***...OK
Checking for existing UPnP port mapping for UDP 48002 -> 192.168.2.*** DESKTOP-*******...OK (14 seconds remaining)
Updating UPnP port mapping for UDP 48002 -> 192.168.2.***...OK
Checking for existing UPnP port mapping for UDP 48010 -> 192.168.2.*** DESKTOP-*******...OK (13 seconds remaining)
Updating UPnP port mapping for UDP 48010 -> 192.168.2.***...OK
Checking for existing UPnP port mapping for UDP 9 -> 192.168.2.255 DESKTOP-*******...OK (415369 seconds remaining)
Updating UPnP port mapping for UDP 9 -> 192.168.2.255...OK
UPnP IPv4 port mapping successful
Using UPnP upstream IPv4 address: 145.133.***.***
Reached the Internet at hop 0
Going to sleep...

----------------- OLD MISS LOG ---------------------
Moonlight Internet Streaming Service v4.3.0.0
The current UTC time is: 06:26:27
Woke up for periodic refresh
GameStream is ON!
Finding upstream IPv4 hops via traceroute...
Hop 0: 195.190.228.***
Hop 1: 139.156.98.***
Hop 2: 193.239.117.***
Hop 3: 104.27.180.** (error 0)
Found 3 hops
Starting port mapping update on default gateway to local machine...
UPnP IPv4 IGD discovery completed with error code: 0
NAT-PMP public address request failed: -100
Found a connected UPnP IGD
UPnP IGD WAN address is: 145.133.***.***
Checking for existing UPnP port mapping for TCP 47984 -> 192.168.2.*** DESKTOP-*******...OK (151 seconds remaining)
Updating UPnP port mapping for TCP 47984 -> 192.168.2.***...OK
Checking for existing UPnP port mapping for TCP 47989 -> 192.168.2.*** DESKTOP-*******...OK (150 seconds remaining)
Updating UPnP port mapping for TCP 47989 -> 192.168.2.***...OK
Checking for existing UPnP port mapping for TCP 48010 -> 192.168.2.*** DESKTOP-*******...OK (150 seconds remaining)
Updating UPnP port mapping for TCP 48010 -> 192.168.2.***...OK
Checking for existing UPnP port mapping for UDP 47998 -> 192.168.2.*** DESKTOP-*******...OK (150 seconds remaining)
Updating UPnP port mapping for UDP 47998 -> 192.168.2.***...OK
Checking for existing UPnP port mapping for UDP 47999 -> 192.168.2.*** DESKTOP-*******...OK (150 seconds remaining)
Updating UPnP port mapping for UDP 47999 -> 192.168.2.***...OK
Checking for existing UPnP port mapping for UDP 48000 -> 192.168.2.*** DESKTOP-*******...OK (150 seconds remaining)
Updating UPnP port mapping for UDP 48000 -> 192.168.2.***...OK
Checking for existing UPnP port mapping for UDP 48002 -> 192.168.2.*** DESKTOP-*******...OK (151 seconds remaining)
Updating UPnP port mapping for UDP 48002 -> 192.168.2.***...OK
Checking for existing UPnP port mapping for UDP 48010 -> 192.168.2.*** DESKTOP-*******...OK (150 seconds remaining)
Updating UPnP port mapping for UDP 48010 -> 192.168.2.***...OK
Checking for existing UPnP port mapping for UDP 9 -> 192.168.2.255 DESKTOP-*******...OK (415506 seconds remaining)
Updating UPnP port mapping for UDP 9 -> 192.168.2.255...OK
UPnP IPv4 port mapping successful
Using UPnP upstream IPv4 address: 145.133.***.***
Reached the Internet at hop 0
Going to sleep...
--------------- CURRENT GSV6FWD LOG -------------------
IPv6 Forwarder for GameStream v2.3.1.0
The current UTC time is: 06:29:47
UPnP IPv6 IGD discovery completed with error code: 0
No UPnP device found!
Going to sleep...

----------------- OLD GSV6FWD LOG ---------------------
IPv6 Forwarder for GameStream v2.3.1.0
The current UTC time is: 06:27:37
UPnP IPv6 IGD discovery completed with error code: 0
No UPnP device found!
Going to sleep...

**Comment by Hamza141** [comment]
Like it states in the logs
> The following ports were not forwarded properly:
TCP 47984
TCP 47989
TCP 48010
UDP 47998
UDP 47999
UDP 48000

You need to need to forward those ports from your router to your computer
