### ISSUE TITLE
Scale Android Overlay.

### ISSUE THREAD

**Issue by owenwalker92** [moonlight-stream/moonlight-android#741]
Multiple requests for scaling the overlay have already been made but unfortunately went into stale-bot countdown. Currently the only way to scale the overlay is via dragging the elements to the right and bottom side of the screen

 Having the ability to scale it via a percentage in options and/or scaling it via also the left and upper sides of the screen would be a great improvement on functionality.

Another welcome change would be to allow the elements to snap to each other for easier custom placement (mainly on the buttons XYABLbRb etc.)

Also as others have already requested opacity of the buttons would be useful on specific games.

Please see referenced old tickets below
https://github.com/moonlight-stream/moonlight-android/issues/576#
https://github.com/moonlight-stream/moonlight-android/issues/557
https://github.com/moonlight-stream/moonlight-android/issues/712

**Comment by owenwalker92** [comment]
Bump to avoid stale

**Comment by mjk00** [comment]
Being able to hide/disable buttons would be a good option for games that don't need all buttons.

Also a widget style scaling method.

**Comment by cgutman** [comment]
This should be addressed by https://github.com/moonlight-stream/moonlight-android/pull/782
