### ISSUE TITLE
Failed to start RTSP handshake over local WiFi

### ISSUE THREAD

**Issue by Crystalzone** [moonlight-stream/moonlight-android#742]
I can't stream any games. Moonlight connects to GFE just fine and starts games, but as it's trying to start an RTSP handshake it immediately fails. I found some closed issues (namely #528, #589) but even downgrading from GFE 3.20 to GFE 3.13 didn't do anything for me.

**Comment by cgutman** [comment]
Are you running Bitdefender on your host PC?

**Comment by Crystalzone** [comment]
Yes, I do, wouldn't be the first problem related to Bitdefender. What should I do?

**Comment by cgutman** [comment]
There's a note in the troubleshooting page -https://github.com/moonlight-stream/moonlight-docs/wiki/Troubleshooting

Basically just join the Discord server and follow the steps in the #bitdefender-situation channel

**Comment by Crystalzone** [comment]
Thanks, I managed to get it working now, though I am still waiting for a universal solution by Bitdefender as Moonlight is not the only software failing because of this.
