### ISSUE TITLE
Suggestion: Hold Start Button To Go Back To Games List?

### ISSUE THREAD

**Issue by J4ves** [moonlight-stream/moonlight-android#743]
I don't use the mouse emulation feature when you hold the Start button. I was curious, would it be possible to make an option so that when you hold the Start button it takes you back to Moonlight's game list?

I'm using a Mecool KM3 with a 360 controller, and going back to the Games list menu is a messy process that requires pressing the Home button on my 3rd party remote, and then reopening the Moonlight app, to quit the game and launch a new game, etc. 

It would be a more elegant solution if I could just hold the Start button (on my Xbox controller) and it opens Moonlight's game list. Not asking for mouse emulation to be removed, just an option that lets us change the function of holding the start button. 

I'm aware that Android's Back button also does this, but my 3rd party remote doesn't have that button properly mapped, so it doesn't work for me.

Thanks in advance.

**Comment by thw0rted** [comment]
Doesn't it put you back at the games list when you simply quit the game you launched in the first place?

**Comment by J4ves** [comment]
It does, but a lot of my PC games don't have an elegant solution to quitting games. And, in many cases require going through multiple loading screens to get back to the title, to then exit. I use the GameStream/Moonlight Quit game to force close a game, and it always works. 

The feature is already there when you press the Android Back button, I'm simply asking for an option to allow us to map that function to holding Start, instead of holding start being used for mouse emulation.

**Comment by J4ves** [comment]
Found a temporary solution: 

Install Button Mapper for Android TV from Google Play Store, which allowed to map any Android function I wanted to any button. So I have "Android Back" mapped when holding the Back and Xbox Guide button now.

Would be nice if the feature was natively added, but after looking at the state of on screen controls for Moonlight on phones/tablet, it made me realise that Moonlight is probably not being all that actively worked on.
