### ISSUE TITLE
Incompatible with Pixel Slate?

### ISSUE THREAD

**Issue by paulmorabito** [moonlight-stream/moonlight-android#744]
Hi,

I'm unable to install the app via the Play Store on my Pixel Slate ChromeOS device. However, it is compatible with the Pixelbook and other Chrome devices.

Thanks

**Comment by thw0rted** [comment]
I think you want [the ChromeOS version[(https://chrome.google.com/webstore/detail/moonlight-game-streaming/gemamigbbenahjlfnmlfdjhdnkpbkfjj?hl=en)?

**Comment by paulmorabito** [comment]
@thw0rted yes, correct but there is an issue with the Slate that I've [reported ](https://github.com/moonlight-stream/moonlight-chrome/issues/500). In the meantime, I was hoping to see if I could use the Android app instead.

**Comment by paulmorabito** [comment]
@thw0rted I installed this via F-Droid onto the Slate. It works really well with the exception of the trackpad mouse button not working. Any ideas on how I could get this working? Otherwise, it works really well.

**Comment by paulmorabito** [comment]
@thw0rted yes, correct but there is an issue with the Slate that I've [reported ](https://github.com/moonlight-stream/moonlight-chrome/issues/500). In the meantime, I was hoping to see if I could use the Android app instead.

**Comment by cgutman** [comment]
I've re-enabled support for ChromeOS based on user feedback. The mouse issue is tracked as #747 and it's most likely a ChromeOS issue (since it broke without any changes to Moonlight).
