### ISSUE TITLE
Play on HDR TV with no-HDR Monitor

### ISSUE THREAD

**Issue by pfornaro** [moonlight-stream/moonlight-android#745]
Hello guys,

I have a 4K HDR TV and I can stream extremely my games with my GTX 1070ti at that resolution. I also tried to enable the HDR option into the Moonlight menù but it doesn't work. So I was wondering if is there a way to play in HDR with an incompatible monitor, it would be great. Thanks in advance

**Comment by cgutman** [comment]
Unfortunately most games now use OS HDR which GameStream can't emulate today, so those games require an HDR monitor on the host.

**Comment by thw0rted** [comment]
I was going to suggest that you look for an HDR-capable dummy adaptor / monitor emulator, to make the PC think it should be able to render in HDR, but [this thread](https://www.nvidia.com/en-us/geforce/forums/discover/297009/4k-hdr-dummy-plug/) suggests that there aren't any on the market, and I haven't been able to find any myself.

I did find [this EDID override](https://www.amazon.com/gofanco-Prophecy-EDID-Emulator-Programmable/dp/B07SSD8VR8) though.  Maybe with that you could convince your computer that your existing monitor actually supports HDR when it doesn't?  Pretty danged expensive to find out though.

**Comment by Duskfall** [comment]
If I buy the cheapest HDR monitor and plug it as a secondary Windows monitor and gamestream from that monitor, it should work right?
