### ISSUE TITLE
Mouse and keyboard not working correctly on Chromebook (C330 on beta channel)

### ISSUE THREAD

**Issue by flowerdealer** [moonlight-stream/moonlight-android#747]
On the Android app, the pointer can move and scrolling works, but right and left click don't work and the keyboard doesn't work. On the chromebook extension only the keyboard seems to work (get no pointer). This worked fine some time ago.

**Comment by flowerdealer** [comment]
This is fixed with the latest Chrome OS beta channel. However, it still isn't working in the Chrome version.

**Comment by WhiteHalmos** [comment]
@flowerdealer I believe the fix was merged to 79.0.3945.45, and the current version on beta is 79.0.3945.42: https://cros-updates-serving.appspot.com/

**Comment by flowerdealer** [comment]
Yes, saw that. Unfortunately .45 is not on the dev channel yet, so I can't verify it.

**Comment by flowerdealer** [comment]
Fixed in Chrome version too in the latest Beta channel!

**Comment by WhiteHalmos** [comment]
Thank you @flowerdealer for confirming! Looking forward to it coming to stable!

**Comment by cgutman** [comment]
Closing now that ChromeOS 79 is in the stable channel.
