### ISSUE TITLE
Question about MediaCodecHelper and MediaCodecDecoderRenderer

### ISSUE THREAD

**Issue by grill2010** [moonlight-stream/moonlight-android#748]
Hi, first I have to admit that I'm a developer and not a regular user of Moonlight. I recently discovered your project and I was digging through your source code in regard to the MediaCodec logic. I'm developing a h264 live streaming application and on some of my test devices despite huge effort to optimize the code and try to decrease latency I could not figure out why the hell the streaming latency was so high. I started to look on some other projects on github ([ExoPlayer](https://github.com/google/ExoPlayer), [grafika](https://github.com/google/grafika)) to figure out what's the problem with my code. Then I saw your code and it blew my mind, there are specific optimizations for processors and for specific decoders. Even though I have some knowledge of how h264 streaming is working and how hard it is on Android to work with the MediaCodec API because of all the different hardware I was not aware of in what kind of detail you could optimize MediaCodec. I was interested and implemented some of your logic in my code just for testing and what a surprise latency was much better. (

However, your project is licensed under GNU General Public License v3.0. I completely understand the purpose of releasing your code under GPL especially for projects of this kind which requires everyone who would like to use the code to contribute their changes but it is is very restrictive when it comes to closed source projects. Unfortunately the project on which I'm currently working do not apply for GPL and I can't change that. I know this sounds like I'm a complete douchebag and I really hate to ask but would it be possible to somehow extract these two classes from moonlight-android with a more lenient license? If someone is dealing with a raw h264 stream these two classes can became really handy as the logic is so general that almost everyone could use them. In my opinion these two classes should really be implemented directly in the Android API as they are gold worth. If this is not possible then no problem but I think all the logic especially the SPS hacks should be located or documented somewhere outside of moonlight as this information is not dependent on the project itself.

**Comment by cgutman** [comment]
What license did you have in mind?

**Comment by grill2010** [comment]
To be honest I do not have a specific licence in mind. It's your code but maybe MIT or Apache or do you have a suggestion? Again I'm only talk about the specific fixes for the MediaCodec for low latency h264 or h265 streaming so that someone could implement these specific fixes without violating the license of moonlight.
