### ISSUE TITLE
"improve mouse accuracy" keeps getting enabled

### ISSUE THREAD

**Issue by csirketorta** [moonlight-stream/moonlight-android#749]
I have been using Moonlight for a while, but when I use my PC after using Moonlight, my mouse kinda feels weird. It keeps enabling the "Improve mouse accuracy" feature in Windows 10, and I have to disable it (since i'm using it this way) manually. Is there a way to remove this thing or at least make it as a feature? cheers.

**Comment by cgutman** [comment]
Unfortunately, there's no way that we know of to make GeForce Experience stop messing with mouse settings when starting a stream.
