### ISSUE TITLE
Getting strange lag

### ISSUE THREAD

**Issue by timason** [moonlight-stream/moonlight-android#75]
Hey, loving Moonlight so far. I would appreciate if somebody could help me with my issue.
I am using my Nexus 5 to run moonlight and using a wireless ps3 driver. For some reason the stream is very smooth but every once in a while I get a 1-2 second lag where the audio distorts and the video has a sudden fps spike. The game in question (I have not tried other games) is GTA V. I have tried running without my ps3 controller to see if the Bluetooth was interfering but the lag still appears. I run on my 5GHz wifi connection and I am very close to it.
Any ideas why this is happening?
Game is very smooth on my computer (60+ fps on 720p), I have a 3570k + GTX 670 setup.
I will gladly provide any other information.
EDIT: I have tried different settings such as lowering the bitrate and I normally use the 720p60fps config, the lag also happens on 720p30fps.
Timo

**Comment by akanimh** [comment]
Try turning off location settings on your android device while streaming. This has made a huge difference for both Moonlight and PS4 Remote Play as the phone no longer diverts all resources to the location check every 5 minutes or so.

**Comment by timason** [comment]
Will try it out. Thanks!

**Comment by timason** [comment]
This completely fixed it! You guys are great.

**Comment by mr-scrawley** [comment]
> Try turning off location settings on your android device while streaming. This has made a huge difference for both Moonlight and PS4 Remote Play as the phone no longer diverts all resources to the location check every 5 minutes or so.

Sorry to comment on such an old issue, but I just wanted to report that **this seems to have fixed the intermittent network drop spikes (resulting in a few seconds of audio and video stuttering every couple of minutes) for me as well.** 🥳

So android location service apparently can still mess with the stream nowadays.

This is on a Samsung Galaxy S21 Exynos running Android 14 and Moonlight v12.1 connected to a Widows 11 Sunshine 22.0 host via 5 Ghz WIFI.
