### ISSUE TITLE
"Stretch video to full-screen" doesn't work

### ISSUE THREAD

**Issue by endervad** [moonlight-stream/moonlight-android#752]
My phone has a 1080p screen. PC's resolution is also 1080p.
I want to stream a certain game in 720p. So I set in Moonlight video resolution to 720p. However, the stream was in the corner of the screen. I found and enabled an option to stretch the stream to full-screen. Unfortunately, nothing changed. The stream was still in the corner of the screen. There's also no manual zooming as in Steam Link so there's nothing you can do to walk around this issue.
![Screenshot_20191117-022837](https://user-images.githubusercontent.com/10913278/69000519-0b186280-08e2-11ea-8e26-808613551686.png)

**Comment by cgutman** [comment]
You need to change the scaling option in NVIDIA Control Panel to GPU.

![image](https://user-images.githubusercontent.com/2695644/69000564-7a606900-0886-11ea-86de-3a5fead3e42a.png)

**Comment by endervad** [comment]
It didn't help. Also rebooted PC and restarted the stream.
![Screenshot_20191117-023915](https://user-images.githubusercontent.com/10913278/69000626-a100bd00-08e3-11ea-8f28-20a380bbe1dd.png)

**Comment by endervad** [comment]
Reopen the issue please, since it's clearly a bug.

**Comment by cgutman** [comment]
I will reopen but it's not something on our end. We don't control the video stream that GeForce Experience captures. We only display the stream we receive.
