### ISSUE TITLE
Huawei Freebuds 3 Bluetooth headset with high latency

### ISSUE THREAD

**Issue by shinobiz** [moonlight-stream/moonlight-android#756]
My mobile phone is Huawei Mate 30 Pro 5G version. I can synchronize audio and video using the mobile phone speaker. The total delay of Moonlight is below 35ms. However, I use Huawei Freebuds 3 Bluetooth headset with high delay, but there is no obvious delay in playing mobile games.

I answered the above questions to Huawei customer service at the same time. The answer was that they would actively contact the Moonlight app engineers to promote the optimization of software and hardware. At the same time, let me also give feedback to the engineers. I wonder if there is any possibility to optimize the app?

**Comment by zhaohui8969** [comment]
When use Huawei Freebuds 3 Bluetooth headset to play audio from phone, there is a about 150ms latency. This is a Bluetooth headset's problem.

**Comment by thw0rted** [comment]
I had this problem with some other earbuds when watching videos.  The only solution I could find was to delay the video to match the audio (using VLC audio delay settings) or try a different headset.

If the Huawei customer service is offering to put the engineers in touch with the developer, well, the source code is all right here and the dev regularly reads these issues.  Tell them to post here or even fix the code and put in a pull request.
