### ISSUE TITLE
Gamepad vibrates and cannot find PC

### ISSUE THREAD

**Issue by BlessWz** [moonlight-stream/moonlight-android#759]
1. Why can't moonlight search for the PC after using Microsoft Remote Desktop(https://play.google.com/store/apps/details?id=com.microsoft.rdc.android)? I can only fix this problem by restarting the PC.

2. Does moonlight support the gamepad vibration?

**Comment by cgutman** [comment]
1. RDP creates a special virtual GPU and display device which doesn't support Nvidia GameStream since it's not a real GPU nor does it have any capture or encoding hardware. Any other remote desktop solution besides RDP works fine (Chrome Remote Desktop, TeamViewer, LogMeIn, etc)

2. Yes, rumble is supported.

**Comment by BlessWz** [comment]
> 1. RDP creates a special virtual GPU and display device which doesn't support Nvidia GameStream since it's not a real GPU nor does it have any capture or encoding hardware. Any other remote desktop solution besides RDP works fine (Chrome Remote Desktop, TeamViewer, LogMeIn, etc)
> 2. Yes, rumble is supported.

Sorry, I asked a question in the community, but no one answered me. So I want to ask again, why ca n’t my gamepad vibrate (the gamepad is Nvidia Shield TV controller) and my device is Shield TV 2017. When I use the "Nvidia game" that comes with the system for streaming, the gamepad can vibrate.Gamepad doesn't vibrate when I use "moonlight"


![IMG_20191129_113649](https://user-images.githubusercontent.com/30049891/69842056-bccd7100-129c-11ea-88a8-746ddde1eacc.jpg)
