### ISSUE TITLE
Double Input with Moga Pro

### ISSUE THREAD

**Issue by sjonez** [moonlight-stream/moonlight-android#76]
I'm using Moonlight v3.1.6 on android with a Moga Pro controller (in mode B) and when running FIFA 15 the game seems to think there are 2 controllers and so each button press is duplicated making navigating the menus very difficult! (on the player select screen the gamepad icons for both player 1 and 2 move at the same time).

If I connect the Moga directly to the PC and play the game this doesn't happen. It occurs on both my Minix Neo X7 android device and my Galaxy S4.

All my other games are fine, so I'm not sure why just this one is seeing 2 controllers when connected via moonlight/shield...

**Comment by cgutman** [comment]
Can you check if the issue still occurs if you uncheck multiple controller support in Moonlight's settings?

Also check if the issue occurs on v3.1.5 (with multiple controller enabled) - https://github.com/moonlight-stream/moonlight-android/releases/tag/v3.1.5

**Comment by sjonez** [comment]
The issue happens with and without that setting checked (it was actually the first thing I tried). It also still happens on 3.1.5 :-(

Interestingly, googling "fifa double input" seems to show quite a few people with the same problem when using older DirectInput controllers, with the solution being to use x360ce to turn it into an XInput one, however I'm not sure how I can do that as I don't actually have a controller connected to my PC...

**Comment by sjonez** [comment]
FYI I've found a workaround for this. If you place a USB gamepad into the PC (I used an old cheap Logic3 one) then that seems to take on the role of "Controller 1" leaving moonlight to just take up "Controller 2" and no more double inputs...

**Comment by sjonez** [comment]
OK the above was a red herring, it was just a coincidence that i had another gamepad inserted at the time i got it "working".

What I actually need to do is start Fifa manually on the PC BEFORE starting a moonlight session, and then select fifa via moonlight. Moonlight will then connect to the existing fifa session and the Moga will work as a single controller!

Another side effect of this is when connecting to the existing session Fifa will be taken out of fullscreen, requiring me to press Alt+Enter on the PC keyboard to get it back (this becomes a tiresome process when the PC is upstairs and the TV is downstairs!)

I really hope you can fix this! I guess it's something to do with how fifa is detecting the shield controller when it starts up?

Google reveals lots of people playing fifa on their actual shield devices so I'm not sure whether its nvidia, moonlights or EA's problem...

**Comment by tchokido** [comment]
Same problem with a dualshock 4 (wired) on a Lenovo s8 tablet. Actually not only in fifa but for example on mgs ground zeroes. The button scheme is messed  up if no controller is connected to the pc at the same time

**Comment by tchokido** [comment]
It is not a coincidence with a controller on the pc resolving the issue

**Comment by cgutman** [comment]
I think a GFE update fixed this incompatibility with FIFA 15.
