### ISSUE TITLE
Can't turn on gamepad vibration(OTG can turn on vibration, Bluetooth can't turn on vibration)

### ISSUE THREAD

**Issue by BlessWz** [moonlight-stream/moonlight-android#760]
Sorry, I asked a question in the community, but no one answered me. So I want to ask again, why ca n’t my gamepad vibrate (the gamepad is Nvidia Shield TV controller and my device is Shield TV 2017). When I use the "Nvidia game" that comes with the system for streaming, the gamepad can vibrate.Gamepad doesn't vibrate when I use "moonlight"

And when I connect the gamepad and tablet via OTG, the gamepad can vibrate, but when Bluetooth connects the gamepad and tablet, the gamepad cannot vibrate

![IMG_20191129_113649](https://user-images.githubusercontent.com/30049891/69867506-f6749b00-12e1-11ea-876c-353cc4911aa6.jpg)

**Comment by cgutman** [comment]
The Shield TV's gamepad uses a proprietary non-standard vibration API rather than implementing force feedback using the standard Linux APIs. That's why rumble doesn't work in any other app besides the Nvidia Games app.
