### ISSUE TITLE
Please update the Chinese translation in the next version!

### ISSUE THREAD

**Issue by ZerOri** [moonlight-stream/moonlight-android#763]
There are still some setting options that are not translated into Chinese and some translations are outdated. I want to help improve the translation. What should I do?

PS:I have submitted a revised Chinese translation, please update it in next version~

![11](https://user-images.githubusercontent.com/46775615/70208553-d6712b80-1768-11ea-9266-1b6642502a04.jpg)

**Comment by ZerOri** [comment]
I have submitted a revised Chinese translation, please update it in next version~

**Comment by cgutman** [comment]
Thanks, these changes have been merged.
