### ISSUE TITLE
black screen with audio only on fresh host power on

### ISSUE THREAD

**Issue by yeahman45** [moonlight-stream/moonlight-android#767]
Client: Amazon fire tv 4k and android 8.0 (LG v30)
Connection: Gigabit lan
Host : GTX 1070 TI with Geforce Experience 3.20.1.57 (latest version at time of writing) connected to a monitor via displayport.

Ok when I power on my host and I don't use it; i.e I don't turn on monitor or use it at all, when I try to connect to it with moonlight, the screen is black with only audio.

The only solution is to "use" (turn on monitor and turn it off again and move the mouse) the host. After that, moonlight streaming works fine.

Any solution not needing me to manually have to do this on host for moonlight streaming to work? I think this issue has existed for quite a long time now.

**Comment by thw0rted** [comment]
1. Have you tried this from other clients? This sounds more likely to be an Nvidia issue than something Moonlight has control over.

2. I have all kinds of little issues like this with other streaming protocols -- for example, Steam Streaming sometimes doesn't show the mouse cursor, but only when I connect from my smart TV, and only sometimes -- so I use TeamViewer from my phone to work around it.  Have you tried a second remote access setup like TeamViewer, so at least you don't have to get up off the couch?

**Comment by yeahman45** [comment]
I have tried moonlight android on fire tv and my lg v30. I think the issue was always present and could "solve" it by connecting with chrome remote but this does not work anymore. I might try teamviewer but why do you need all this workarounds? After all this time this issue seems ongoing

**Comment by cgutman** [comment]
Streaming with the monitor off is not officially supported by Nvidia.

**Comment by yeahman45** [comment]
> Streaming with the monitor off is not officially supported by Nvidia.

Lol is this a joke? What is the purpose then?

**Comment by cgutman** [comment]
No, NvFBC captures from the display scan-out hardware and you can't scan-out to a display without display connected (and a DP-connected monitor that is turned off is disconnected as far as the GPU is concerned). This will be the case until Nvidia switches to the Desktop Duplication API.

Most people leave their monitors on (and let them sleep using the typical Windows display timeout, then wake when streaming). You can also use a headless HDMI dongle (which I use for my gaming VMs).

**Comment by yeahman45** [comment]
But I don't understand. When my pc boots. I turn on my monitor and turn it off and i streams, it works fine. 

If i turn on my pc and do nothing...streaming does not have video.

Why?

**Comment by cgutman** [comment]
It's probably because the monitor isn't enumerated if it is off during boot. Once you turn it on, then it's enumerated and then streaming works because you have a display.

Why it doesn't get detached again when you turn it off? No clue, possibly depends on your monitor or how it's connected.
