### ISSUE TITLE
[Rooted Version] Double Cursor Issue

### ISSUE THREAD

**Issue by GrowlHowell** [moonlight-stream/moonlight-android#77]
It seems this issue has been previously opened and closed, but I'm currently experiencing it. When in a game (or Steam's Big Picture mode),  the two cursors travels at different speeds, and are limited to my tablet's screen/resolution. Certain games are made unplayable due to this.

**Comment by Selbram** [comment]
I am having this same issue with the Ouya version of moonlight. The cursor for the Ouya and the in-game cursor are not in sync and causes precise mouse movement to be very difficult to accomplish.

**Comment by cgutman** [comment]
@GrowlHowell I assume your device is rooted. Do/did you get a root access prompt? What mouse are you trying to use?

@Selbram Is your Ouya rooted? You'll need the root version of Moonlight for the double cursor issue to go away. Grab one from the releases section.

**Comment by GrowlHowell** [comment]
@cgutman It is, I do/did, and it's the touchpad of the Asus Transformer Prime (TF201). Could it possibly be a ROM-related issue?

**Comment by Selbram** [comment]
@cgutman I have rooted the Ouya. Or at least I think I rooted it. I pulled down the 3.1.6 (rooted) version and installed it. It runs but I still get the double mouse. I have more testing to do I think to assure that I actually rooted the Ouya.

**Comment by Selbram** [comment]
@cgutman So when you root the Ouya *correctly* (I used Kingo), it works perfectly with the rooted apk if you side load it. If it were a little more clear that you really needed to root your android device to use the software in a functional manner I think this would have been less hard. :) Thanks for the assistance.

**Comment by Xiller** [comment]
i use firetv and have same problem. but an idea: could you put in the option "[ ] invisible roundcourser" so you deaktivate this and so you can navigate blind or with keyboard/controller only.

or is this round-cursor from firetv? :(

**Comment by cgutman** [comment]
This issue applies only to rooted devices running the root version of Moonlight. If your Fire TV is rooted and you sideloaded Moonlight for Rooted Devices, open a new issue.
