### ISSUE TITLE
Feature Request - Virtual Keyboard

### ISSUE THREAD

**Issue by Fitipaldi77** [moonlight-stream/moonlight-android#777]
Hi all,

I have a little trouble after awoke my pc with Wake-On-Lan: I can't put my Windows password or pin because there is no option for show or use a virtual keyboard (Like TeamViewer app, for example). 
The only way i can put my password is by using a physical keyboard, but i wished to go out of my home only with a xbox controller or simillary.

Please, can you consider to add a new option to the configuration menu? Something like "Show Virtual Keyboard", and if this option is activated then show a translucid button to open the Google keyboard (Or a left hidden menu that opens with a drag from the edge of the screen, like Gmail, with this you could add more Moonlight options there)

I love this project, keep up the good work!!

Regards,
Fiti.

**Comment by thw0rted** [comment]
Are you using a phone?  If you have a touchscreen you can do a 3-finger tap to open the soft keyboard -- see [this wiki page](https://github.com/moonlight-stream/moonlight-docs/wiki/Setup-Guide#keyboardmousegamepad-input-Options) for more.

If you don't have a touchscreen, there was another issue about adding a keyboard shortcut (I think they were using Android TV?) but it might have been closed.  Anyway, if that's the case you should specify "...on non-touchscreen clients" in your issue / title.

**Comment by thw0rted** [comment]
Also: @cgutman can I suggest updating the "auto-comment" bot response to include a link to the "Setup Guide" and "Troubleshooting" wiki pages?  If the answer to a question is on a wiki page, it's probably one of those two.

**Comment by Fitipaldi77** [comment]
Sorry, i didn't read that section yet. 3-finger tap worked fine, thank you for your attention and sorry for wasting your time.
