### ISSUE TITLE
Does PS4 controllers and Xbox controllers support moonlight vibration?

### ISSUE THREAD

**Issue by BlessWz** [moonlight-stream/moonlight-android#778]

**Comment by cgutman** [comment]
It depends on what your Android OS supports. Most Android devices should at support rumble on Xbox 360 controllers. Recent devices (last 2 years or so) should support rumble on USB Xbox One controllers too.

Bluetooth rumble support is more hit or miss, but I believe devices running the 4.14 Linux kernel should also support rumble on PS4 controllers over Bluetooth.
