### ISSUE TITLE
Ethernet adapter not working properly

### ISSUE THREAD

**Issue by tijmenvn** [moonlight-stream/moonlight-android#78]
I have used moonlight sometime with my nexus player with Android TV, It worked pretty good on 802.11AC 2x2. But I wanted a wired solution for even lower latencies. After buying this adapter with hub: http://www.ianker.com/product/68ANHUB-U3E1A Everything on android was already a lot quicker, however. Gamestream wasn't working as well as i hoped. Anything above 10mbps results in major packet loss and eventually crashing the whole stream. Do you have any idea what is the cause of this?

**Comment by bynar010** [comment]
Sounds like same issue as me, drop your PC ethernet connection to 100MB full and see what happens. I get this when my PC connection is set to gigabit, at 100MB full it works maxed out perfectly

**Comment by cgutman** [comment]
Re-open if this is still an issue.
