### ISSUE TITLE
Samsung Galaxy Tab S6's Proprietary Touchpad Mouse capture does not work

### ISSUE THREAD

**Issue by jinwk00** [moonlight-stream/moonlight-android#781]
Model: SM-T860
Moonlight Version: 8.7, both with and without root
Android Version: 9 (non-root)
Somehow using OTG mouse works but the touchpad does not. Both mouse and touchpad controls the same cursor in the screen.

**Comment by Hazender** [comment]
hello, i have exactly the same problem visibly moonlight does not detect the touchpad of the galaxy tab s6 cover keyboard like a mouse.

**Comment by jakestreet** [comment]
I am experiencing the same issue as well. Bluetooth mouse is working but touchpad does not capture.
