### ISSUE TITLE
redmi k30 “video decoder crashed moonlight has crashed due to an incompatibility with this devices” video decoder。

### ISSUE THREAD

**Issue by Ivanuxan** [moonlight-stream/moonlight-android#783]
![Screenshot_2020-01-21-16-02-18-395_com limelight](https://user-images.githubusercontent.com/46985020/72787011-f94c9600-3c69-11ea-91d8-ad1c8a1124fd.jpg)

redmi k30 “video decoder crashed moonlight has crashed due to an incompatibility with this devices” video decoder。

**Comment by cgutman** [comment]
Did your previous streaming session crash? Does this happen every time you try to stream?

**Comment by Ivanuxan** [comment]
hi！man


&nbsp;&nbsp;Redmi K30 is the latest product. The new mobile phone I just changed has no problem with the old mobile phone streaming. The new mobile phone, redmi K30, has the error report I mentioned.


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Cameron Gutman"<notifications@github.com&gt;;
发送时间:&nbsp;2020年1月26日(星期天) 中午12:35
收件人:&nbsp;"moonlight-stream/moonlight-android"<moonlight-android@noreply.github.com&gt;;
抄送:&nbsp;"1158048772"<1158048772@QQ.COM&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [moonlight-stream/moonlight-android] redmi k30 “video decoder crashed moonlight has crashed due to an incompatibility with this devices” video decoder。 (#783)




Did your previous streaming session crash? Does this happen every time you try to stream?

**Comment by Ivanuxan** [comment]
The new redmi K30 phone will have this problem and cannot stream. The system is Android MIUI 11.0.7

**Comment by Ivanuxan** [comment]
> 您之前的流媒体会话是否崩溃了？每当您尝试流式传输时，都会发生这种情况吗？



> Did your previous streaming session crash? Does this happen every time you try to stream?
hi！man


&nbsp;&nbsp;Redmi K30 is the latest product. The new mobile phone I just changed has no problem with the old mobile phone streaming. The new mobile phone, redmi K30, has the error report I mentioned.
The new redmi K30 phone will have this problem and cannot stream. The system is Android MIUI 11.0.7

**Comment by yorkzhang** [comment]
I have the same problem and the phone model is RedMi k30i, which is a very similar phone. I guess they have the same root cause. Can anyone look into this?
