### ISSUE TITLE
The BACK button doesn't work with the WeChip G20 remote

### ISSUE THREAD

**Issue by Michoko92** [moonlight-stream/moonlight-android#788]
Hi,

When we are in a Gamestream session, we can normally go back to the Moonlight games selection grid by pressing the BACK button. 

I use a WeChip G20 on my Shield TV (which is pretty popular as a replacement for the stock remote). But despite the BACK button is detected everywhere else normally, in a Moonlight Gamestream session, it doesn't seem to be detected. So when we press the BACK button, nothing happens while Gamestreaming (but the BACK button works fine in the Moonlight UI, though). Thank you!

**Comment by cgutman** [comment]
The problem was this virtual mouse device that claims to have an A button like a gamepad.

```
Input Device -3: NVIDIA Virtual Mouse
  Descriptor: 5345c6da1d26ddaf0af78bf97d14a420216933cb
  Generation: 174
  Location: built-in
  Keyboard Type: non-alphabetic
  Has Vibrator: false
  Has mic: false
  Sources: 0x20105 ( keyboard mouse_relative )
    AXIS_X: source=0x20004 min=-1.0 max=1.0 flat=0.0 fuzz=1.0 resolution=0.0
    AXIS_Y: source=0x20004 min=-1.0 max=1.0 flat=0.0 fuzz=1.0 resolution=0.0
    AXIS_PRESSURE: source=0x20004 min=0.0 max=1.0 flat=0.0 fuzz=0.0 resolution=0.0
    AXIS_HSCROLL: source=0x20004 min=-1.0 max=1.0 flat=0.0 fuzz=0.0 resolution=0.0
```
