### ISSUE TITLE
Disable Xbox button

### ISSUE THREAD

**Issue by goldenpipes** [moonlight-stream/moonlight-android#791]
Hi there I've been enjoying moonlight on my xaomi mibox 4 with my Xbox one (bt) controller, but I was wondering if it's possible to disable the Xbox button press from sending me to android home screen. I'd like to use it as the Xbox button if possible but just disabling it would work to I suppose.  If this can't be done in moonlight itself does anyone have an idea if it could be done at the Android level?  Thanks again for this awesome software!

**Comment by cgutman** [comment]
It will have to be done at the Android level by changing the keymap for the controller (which requires root or a custom ROM).

For security reasons, it's not possible for apps to intercept the home button.

**Comment by thw0rted** [comment]
I run several PS4 Remote Play apps on my unrooted phone.  The DS4 home button is captured by these apps and relayed to the PS4.

Do you think that the XB controller uses a different Bluetooth profile, that doesn't allow the Home button to be captured?  Or is it a problem with the XB controller specifically?  Maybe the apps somehow switch the DS4 out of the default (HID gamepad?) profile and into a Sony-specific mode?

**Comment by thw0rted** [comment]
Further to the button mapping thing, [this Chiaki issue](https://github.com/thestr4ng3r/chiaki/issues/127) talks about input mapping and includes a link to [the AOSP button mappings](https://android.googlesource.com/platform/frameworks/base/+/master/data/keyboards) for various controllers.  [The DS4](https://android.googlesource.com/platform/frameworks/base/+/master/data/keyboards/Vendor_054c_Product_05c4.kl), the [Xbox 360 USB pad](https://android.googlesource.com/platform/frameworks/base/+/master/data/keyboards/Vendor_045e_Product_028e.kl), and the [Xbox One USB pad](https://android.googlesource.com/platform/frameworks/base/+/master/data/keyboards/Vendor_045e_Product_02d1.kl) all map the home / logo button as `BUTTON_MODE`.  I'm guessing the reality is more complex than that?
