### ISSUE TITLE
The problem that "RT / LT" button of virtual controller can not be combined with other buttons

### ISSUE THREAD

**Issue by 8116453** [moonlight-stream/moonlight-android#795]
HI cgutman
When I use the virtual controller, when I press and hold the "RB / LB" button and move my finger to the "A / B / X / Y" button, it can be well combined, but the "RT / LT" button can't be so combined, so I have to press two fingers at the same time to combine them, which is very numb in some games that need to use the "RT / LT" button combined with other digital buttons Bother. I hope you can fix this defect. Thank you very much.

**Comment by cgutman** [comment]
You can re-arrange the on-screen control layout to make it fit the way you would like to have them positioned using the gear button in top left corner.
