### ISSUE TITLE
Problems with the detection of the D-pad on powkiddy x18 console

### ISSUE THREAD

**Issue by penkamaster** [moonlight-stream/moonlight-android#796]
While all the other controls work smoothly, the d-pad does not appear to be detected.

These are the records produced by the Android app "Gamepad Tester" when each of direction is clicked.

Button: UP - Scancode: key 103  - Key Code: 19
Button: DOWN - Scancode: key 108  - Key Code: 20
Button: LEFT - Scancode: key 105  - Key Code: 21
Button: RIGHT - Scancode: key 106  - Key Code: 22

Thank you.

**Comment by cgutman** [comment]
Hmm, those key codes correspond to KEYCODE_DPAD_UP, KEYCODE_DPAD_DOWN, KEYCODE_DPAD_LEFT, and KEYCODE_DPAD_RIGHT as expected, and we do cover those (most gamepads use them).

I suspect the gamepad is being detected as a keyboard instead. Do you know how to get a logcat log on Android? If so, can you get a logcat log after attempting to use the d-pad while streaming with Moonlight? If not, I can provide more detailed instructions.

**Comment by penkamaster** [comment]
Hi Cameron,

I couldn't see anything strange in the logs, but I got to see where the problem was.

There is a coment on the code in ControllerHandler.java where you said: "// These are duplicate dpad events for hat input" and then you return a 0 in cases where the KEYCODE corresponds to one of the dpad addresses.

making it to return the event.getKeyCode() in theses cases instead of a 0
solved the problem.

Thank you.

**Comment by penkamaster** [comment]
you can see the commit that fixes the dpad on the powkiddy x18  on my fork 
https://github.com/penkamaster/moonlight-android/commit/83452a7c57338dbc4ef053bd09695ad6f369de65

**Comment by cgutman** [comment]
Thanks, it looks like the problem is that the gamepad claims to have the axes for a hat, but sends d-pad events instead. I've fixed it by only suppressing d-pad key events for a hat axis if we've previous received hat input from it.
