### ISSUE TITLE
Mouse wheel scroll not working

### ISSUE THREAD

**Issue by drseussofporn** [moonlight-stream/moonlight-android#8]
Limelight seems to completely ignore mouse wheel input. I don't see any reference in the code that would even handle this event, but I might not be looking thoroughly enough. Here is some sample code I found on StackOverflow (not sure if it will help):

@Override
public boolean onGenericMotionEvent(MotionEvent event) {
if (0 != (event.getSource() & InputDevice.SOURCE_CLASS_POINTER)) {
switch (event.getAction()) {
case MotionEvent.ACTION_SCROLL:
if (event.getAxisValue(MotionEvent.AXIS_VSCROLL) < 0.0f)
selectNext()
else
selectPrev();
return true;
}
}
return super.onGenericMotionEvent(event);
}

**Comment by ischorr** [comment]
Still an issue in current versions
