### ISSUE TITLE
[Question] Are the Shield Tablet and Shield portable the only devices compatible with the shield controller?

### ISSUE THREAD

**Issue by fran122157** [moonlight-stream/moonlight-android#80]
I was planning to buy a shield controller to use with moonlight but I couldn´t find any information regarding if the shield controller works with any android device through a wired connection.

Thanks in advance and sorry for my english

**Comment by MisterCreative** [comment]
No you sadly can't. http://shield.nvidia.com/support/shield-controller/faq/2 It only works with the shield tablet and shield portable.

**Comment by cgutman** [comment]
The Shield controller does work with most devices wired, but wireless it requires Shield devices.
