### ISSUE TITLE
Holding a key results in multiple times pressing it

### ISSUE THREAD

**Issue by georgyel** [moonlight-stream/moonlight-android#800]
I play ARK: survival evolved where holding a key and pressing it have different actions bound. When i hold a key, it opens the 'press-release' action. Sometimes this works normally but sometimes it works like that.

**Comment by cgutman** [comment]
Thanks for the report.

Please see if this build fixes it: https://drive.google.com/file/d/10BNrcZwgWSTY0Pvv9hj314LE4_4jN1YZ/view?usp=sharing
