### ISSUE TITLE
No 5.1 audio output on android tv box

### ISSUE THREAD

**Issue by dongioia** [moonlight-stream/moonlight-android#804]
Hi,
I can't manage to have a 5.1 audio output from my android box.
My setup is:
Server: laptop connected to my lan by wire, cpu intel core i7 7th gen, geforce gtx 1060 and the latest gaming drivers from nvidia.
Client: android box running lineage 16 android tv 64  bit (android pie), connected by wire and audio output over hdmi connected to an AV receiver.
The android box is fully capable to output 5.1 or 7.1 audio streams (tested with kodi and vlc).
I checked the surround option in the moonlight config panel and enable dolby 5.1 output in my games, but still I got a stereo output.
I tried this setup with Star Wars Jedi Fallen Order.
Except this issue, the gaming experience is great.

**Comment by cgutman** [comment]
Are you expecting LPCM 5.1 or some other format like DTS?

**Comment by dongioia** [comment]
I should get dolby 5.1, as stated in the game settings.
My android box can do audio pasttrough over hdmi.
