### ISSUE TITLE
Image on client no longer fills screen at 720p

### ISSUE THREAD

**Issue by tacticalcraptical** [moonlight-stream/moonlight-android#805]
This only started happening with a recent update of Moonlight. I have a PC I use on a TV from a couch and the resolution works best at 720p for that. However, when using Moonlight to connect to that PC, the image no longer fills the screen with the extra space either being black or an artifact of what was on the screen when the connection was made. Changing the PC resolution to 1080p will make it work properly but that means changing the resolution every time I use Moonlight.

![IMG_20200401_081140](https://user-images.githubusercontent.com/35301481/78150263-48464280-73f4-11ea-935a-3c9d12fa0824.jpg)

**Comment by thomas001** [comment]
The same here, I have a 4K monitor but the windows resolution is set to 1920x1080. Just streaming the desktop (via mstsc) shows me the actual desktop in only the top left quarter of the image and the rest is filled with random garbage (content of the framebuffer before the resolution change or just black if immedately after reboot).

Log: [NvStreamerCurrent.log](https://github.com/moonlight-stream/moonlight-android/files/4667101/NvStreamerCurrent.log)

Image: Note that the browser window actually fills the full screen on the physical pc monitor. The 3/4 showing parts of the background image and parts of the epic launcher is not visible
- Phone: ![Screenshot (22 05 2020 11 06 40)](https://user-images.githubusercontent.com/372086/82651620-acc79600-9c1c-11ea-85b4-77d4c9e0bb7a.png)
- PC Monitor: 
![IMG_20200522_110713](https://user-images.githubusercontent.com/372086/82651833-fb753000-9c1c-11ea-8aab-ca5a6fb66cbf.jpg)

**Comment by cgutman** [comment]
Changing your display resolution with Nvidia Control Panel instead of Windows display settings fixes this. The latter is just enabling scaling which doesn't get captured properly.
