### ISSUE TITLE
Z4 Tablet issue

### ISSUE THREAD

**Issue by speedy0208** [moonlight-stream/moonlight-android#81]
Great app but when using on z4 tablet with Windows 7 with remote desktop mouse cursor does not function.
Works fine on z2 tablet and z ultra.

**Comment by cgutman** [comment]
Please install the linked APK. Open the test app then move your finger around the screen. Screenshot the result and post a link to it.

**Comment by speedy0208** [comment]
There a grey screen and when I move my finger there are no logs. There are only logsnwhen I pish the back button. 
![screenshot_2015-06-20-11-35-13](https://cloud.githubusercontent.com/assets/12875651/8265889/c1631eb0-1740-11e5-87cc-01e427ea3dff.png)

**Comment by flight16** [comment]
Any updates?  I was considering buying the same tablet.

**Comment by cgutman** [comment]
Please check if this build fixes the issue - https://onedrive.live.com/redir?resid=C15BF9770619F56!160581&authkey=!AEPt2nmqcFLH9gs&ithint=file%2capk

**Comment by speedy0208** [comment]
Thank the issue has been resolved sometime back when Sony updated their firmware. It works perfectly now. New update also does not have any problems. So it was a Sony issue and not moonlight.

**Comment by cgutman** [comment]
Thanks for confirming.
