### ISSUE TITLE
setup gamepad feature?

### ISSUE THREAD

**Issue by WaitingKy** [moonlight-stream/moonlight-android#810]
android doesn't support gamepad or some gamepads that don't have full buttons like a real console gamepad. in my case, i'm using rog phone 2 and its kunai gamepad to play moonlight. it's a great experience except my gamepad doesn't have start/select buttons but it has useless m1/m2 buttons (i don't know why asus does that). steam link has setup gamepad feature so i can change m1/m2 as start/select but moonlight doesn't. please add it, that's a good feature which allows us to use any gamepads even a fake one to enjoy game streaming

**Comment by whise** [comment]
This is clearly a feature request. He is requesting that you add a gamepad remap feature to android client
