### ISSUE TITLE
Xbox One BT buttons mapped incorrectly

### ISSUE THREAD

**Issue by ReenigneArcher** [moonlight-stream/moonlight-android#818]
Mapping issue from Android apps (tested on Nvidia Shield TV and Bravia TV). Tried various input settings in the moonlight app.

Start is 6, should be 7
Select is 7, should be 6
Left Trigger is +4, should be +2
Right Trigger is +5, should be -2
Left stick Y+ is -1, should be +1
Left stick Y- is +1, should be -1
Right stick X+ is +2, should be +3
Right stick X- is -2, should be -3
Right stick Y+ is -3, should be +4
Right stick Y- is +3, should be -4

Tested mappings in RetroArch which automatically configures controllers.

Also Steam shows the controller as an Xbox 360 controller instead of Xbox One.

If it helps this behavior does not occur in Nvidia GameStream, or SteamLink.

**Comment by cgutman** [comment]
Update to the firmware of your controller using the Xbox Accessories app on a Windows 10 PC or an Xbox One console.

**Comment by ReenigneArcher** [comment]
Firmware is already the latest

**Comment by cgutman** [comment]
What version?

**Comment by ReenigneArcher** [comment]
4.8.1923.0... app says no update available

**Comment by cgutman** [comment]
Showing up as an Xbox 360 controller is normal. That's what controller model NVIDIA GameStream emulates.

Are you using Bluetooth or USB?

I tried on my NVIDIA Shield TV (SHIELD Experience 8.0.2), Pixel 4 XL (Android 10), and Nexus 9 (Android 7.1.1) and my Xbox One S controller on 4.8.1923.0 is mapped correctly via Bluetooth.

**Comment by ReenigneArcher** [comment]
You are correct on it showing as a 360 controller, my mistake. It is SteamLink that passes it as a XbOne pad.

It's weird it's mapped correctly for you. I posted about this in a Facebook group and 2 out of 4 people said they were using moonlight for streaming but had to connect the controllers directly to the PC because the mappings were incorrect. (One other was using SteamLink but that won't work for me because it doesn't allow you to control a secondary application like RetroArch if you launched from Launchbox... The other was using Parsec, but their Android app is terrible). Nvidia GameStream works perfectly but I don't think it can be installed on non shield devices.

Maybe a controller config could be added to the settings to map the controls?

**Comment by cgutman** [comment]
How are you confirming the mappings are wrong? Are you just using RetroArch? Have you tried anything else?

Is Steam's Controller Configurator enabled?

**Comment by ReenigneArcher** [comment]
I just checked in another game and in Steam. Everything looks good there. Far as I can tell the issue is only in RetroArch. It doesn't seem to matter how it's launched. I launched RetroArch directly from the App, through Steam, or through LaunchBox.

In Steam, I tried with Steam configurations forced off and default (Xbox) with default Gamepad layout. Forced off is the only one that works at all (if I use Steam -> Launchbox -> RetroArch... If I use Xbox config then no controls work in RetroArch). If I bypass Launchbox and go Steam to RetroArch controls do work. But always the mappings are off.

**Comment by ReenigneArcher** [comment]
Okay... I solved this by creating an autoconfig file for retroarch. Even though the app is passing it as a common Xbox 360 controller, the vendor ID and product ID of the virtual controller passed to retroarch didn't match anything in the retroarch database. If the input menu is showing button numbers instead of labels, then there is no autoconfig for that controller. For anyone having a similar problem with other controllers you can create your own autoconfig file. As long as you follow the guidelines here you can also upload the config for everyone to use at this repository. [https://github.com/libretro/retroarch-joypad-autoconfig](url)

Thanks for the support!

**Comment by ReenigneArcher** [comment]
I found out a little bit more information. It appears the Moonlight app is passing the same vendor and product ID as the Nvidia Shield controller. This is what was causing the issue within RetroArch as Nvidia Shield controller already has an autoconfig file in their software.

Does the app always pass the Nvidia Shield controller IDs or is it dependent on the controller in use? (I only have Xbox One BT controllers to test with).

Is it possible for the app to pass the source vendor and product IDs so that RetroArch can correctly identify the controllers? Alternatively could you pass non standard IDs, or allow the option to enter custom IDs from the Moonlight app?

**Comment by cgutman** [comment]
We cannot control what VID and PID that GeForce Experience sets for their virtual controller. We can only specify how many controllers it should emulate.

Your best bet is to create a forum thread detailing the issue for them: https://www.nvidia.com/en-us/geforce/forums/gamestream/19/
