### ISSUE TITLE
Having Issue in android studio

### ISSUE THREAD

**Issue by TaranpreetSinghRayat** [moonlight-stream/moonlight-android#819]
I was trying to compile it using android studio but i am keep getting this error :

ERROR: executing external native build for ndkBuild C:\Users\fear1\AndroidStudioProjects\moonlight\app\src\main\jni\Android.mk

Thank you

**Comment by cgutman** [comment]
If you have the NDK installed, make sure you have created the `local.properties` file as noted in https://github.com/moonlight-stream/moonlight-android#building

If that still doesn't work, ask in the #android-dev channel on the Discord server. These types of questions are more appropriate there.
