### ISSUE TITLE
Kindle HDX 7 lag

### ISSUE THREAD

**Issue by saiotek** [moonlight-stream/moonlight-android#82]
With my Kindle HDX 7 (wifi only / snapdragon 800) i have strange lag. Apart from that no problems but the lag is annoying. In sporadic intervals. 15sec everthing is smooth than 1sec lag, 3 sec later 1sec lag, 10 sec later 1sec lag, 20 sec later 1sec lag, 3 sec later 1sec lag and so on...

bluetooth is off (has no gps, localization services off)
using 5ghz wifi
720p with 30fps or 60fps makes no difference
latency is around 30

With my Nexus 7 2012 / Xperia Z1 everything works without lag (on both i get latency around 20)
same for Fire TV Stick works without problems (but latency around 30)
I'm using latest drivers (2.4.5 / not beta) / moonlight (3.1.6) 

is this a kindle problem?

**Comment by mrb113** [comment]
Closing since this is old and never got any traction - please reopen if you continue to see this
