### ISSUE TITLE
Gap between stylus position and mouse pointer with multiple monitors on host

### ISSUE THREAD

**Issue by CarloDePieri** [moonlight-stream/moonlight-android#821]
I was trying out the stylus (I would really need some sort of absolute mouse control and this would be a way, lacking absolute touch control) and noticed a strange behavior: on the right edge of the screen the pointer and the stylus position are the same, but moving the stylus left the mouse pointer moves faster, incrementing the gap more and more.
This applies also without gradually moving from the right, by the way.
I'm attaching 2 pics to illustrate the problem.

![photo5832173702723253502](https://user-images.githubusercontent.com/5459291/79794935-6e0b9b00-8353-11ea-9f37-13a3d6437855.jpg)

![photo5832173702723253503](https://user-images.githubusercontent.com/5459291/79794934-6c41d780-8353-11ea-86dc-90f141c481d5.jpg)

App version: 9.2
Device: Galaxy Tab S4 (SM-T830)
OS: Android 9
Stylus: SPen

**Comment by cgutman** [comment]
Does your host PC have multiple monitors?

**Comment by CarloDePieri** [comment]
Yep, I thought about that a second too late. I can confirm that's the underlying problem.

Is there a way to go around this without disabling the second monitor?

**Comment by cgutman** [comment]
Nope, it's a bug on Nvidia's end which affects the official Shield clients too.

There are more details in https://github.com/moonlight-stream/moonlight-common-c/issues/49 and in the report on Nvidia's forums: https://www.nvidia.com/en-us/geforce/forums/gamestream/19/370301/bug-report-gamestream-touch-input-broken-with-mult/

**Comment by CarloDePieri** [comment]
I see, I'll have to make do while they fix it!
In the meantime, thank you for you hard work on this project!
