### ISSUE TITLE
Please add support for Side by Side Mode (SBS) in android client

### ISSUE THREAD

**Issue by jphein** [moonlight-stream/moonlight-android#823]
Moonlight offers the best streaming I've found hands down. Please add a SBS mode for cheap VR goggles so we can play all our 2D games in pseudo VR. Even without lens distortion correction, or 3D filters it is a great first step. Coupled with Opentrack, and the FreePIE IMU you can get 3DoF HMD tracking. 

There are currently some commercial packages that off this kind functionality. However, nothing with the quality of moonlight. We be amazing to have a completely open source solution.  

It's been brought up before here: https://github.com/moonlight-stream/moonlight-android/issues/565
There have been a number of people who have forked this project to add SBS mode, but nothing recent. 
https://github.com/monstrobishi/moonlight-android
https://github.com/avtoneru/moonlight-SBS
https://github.com/MardariG/moonlight-android
https://github.com/alandao/moonlight-android

**Comment by zediiiii** [comment]
[The Google Cardboard SDK](https://developers.google.com/cardboard/) could do all the heavy lifting for the SBS implementation, IPD settings, lens distortion, headset/device-specific settings etc.
