### ISSUE TITLE
Optimize button mapping for 8BitDo controllers

### ISSUE THREAD

**Issue by chrisipa** [moonlight-stream/moonlight-android#825]
Hello everyone,

first of all thank you very much for this great piece of software. It really changed the way I'm gaming at home. You can be really proud about what you achieved yet.

I'm currently using 2 different 8 BitDo controllers models (SN30 Pro, SN30 Pro+)  as an input device for my different streaming clients, as they have a great build quality and very low input lag.

On my older 1st gen FireTV boxes they really work great using the MacOS mode (they show up as "Wireless Controllers" in the pairing menu). Here all the buttons are mapped correctly using the standard Microsoft button layout.

On newer devices (e.g. my One Plus 7, FireTV stick 4k) the MacOS mode does not work anymore and you have to connect these controllers using the Android D-Input mode. Here the controllers show up as "8BitDo xxxxx" and the A / B and X / Y buttons are used in the Nintendo layout. So it feels really strange if you play Windows games with the buttons swapped with each other:

![Auswahl_999(963)](https://user-images.githubusercontent.com/7666084/80352307-fae2b700-8873-11ea-9f1a-2f1d63a2eef8.png)

If you have the possibility to root your device, this problem could be easily fixed by providing a key file containing the correct key codes for the swapped buttons. But especially the Amazon devices are pretty hard to root and there this problem cannot be easily tackled.

Would it be possible to change the default mapping for the 8BitDo controllers @cgutman? Or maybe by adding another configuration flag for people which want to swap the buttons?

Best regards
Chris

**Comment by chrisipa** [comment]
I have also prepared an alternative keylayout file for my 8BitDo SN30 Pro+ controller in case anybody has a rooted device and wants to change the mapping of the controller in general:

[Vendor_2dc8_Product_6102.kl.txt](https://github.com/moonlight-stream/moonlight-android/files/4583470/Vendor_2dc8_Product_6102.kl.txt)

You have to follow these steps to get the mapping running:
- Make sure that you have rooted your device and installed something like the **Magisk Manager**
- Open a local terminal on your device (e.g. by using the app **JuiceSSH** or **Android Terminal**)
- Get root permission by entering this command: 
`su - root`
- Mount the system partition in read write mode: 
`mount -o rw,remount /system`
- Copy and rename the attached file to the folder **/system/usr/keylayout**: 
`cp Vendor_2dc8_Product_6102.kl.txt /system/usr/keylayout/Vendor_2dc8_Product_6102.kl`
- Make sure that the keylayout file has the correct file permissions: 
`chmod 644 /system/usr/keylayout/Vendor_2dc8_Product_6102.kl`
- Mount the system partition in read only mode again (or reboot your device): 
`mount -o r,remount /system`

I hope this helps everyone who wants to have a more permanent solution.

**Comment by cgutman** [comment]
@chrisipa can this be closed?

**Comment by chrisipa** [comment]
Yes. Thanks a lot for your support @cgutman
