### ISSUE TITLE
7.1 sound issues

### ISSUE THREAD

**Issue by ReenigneArcher** [moonlight-stream/moonlight-android#827]
7.1 is enabled in the app.

Left, Center, Right channels are all correct.

Sub comes out of R speaker.
Side and Rear channels all come out of C speaker.

![image](https://user-images.githubusercontent.com/42013603/80648399-1c8f9a00-8a3e-11ea-9627-44fcf7ab3761.png)

Client is Nvidia Shield TV 2019.
PC is Win 10, latest build, latest GFE, drivers, etc.

Additionally I must have Elgato Sound Capture closed on PC as when streaming the app tries to change the device NVIDIA HDMI Out, and Elgato Sound Capture tries to retake the control. If I have Elgato open I won't have any sound at all. I would prefer to use Elgato as I can have the sound output to as many devices as I like.

**Comment by cgutman** [comment]
What bitrate are you using to stream (influences some audio before)?

Does 5.1 work properly?

**Comment by ReenigneArcher** [comment]
Where do I find the bitrate? I'm not seeing it the app settings...

No 5.1 is buggy as well.

Left, Center, and Right are all good again.

No sound for Sub.

The rear speakers come out of the correct side, but in the front speakers.

**Comment by ReenigneArcher** [comment]
I'm not seeing any audio bitrate option in the app, but in Windows under NVIDIA HDMI Out Properties, Advanced tab it says 16 bit, 48000 Hz (DVD Quality) and the option cannot be changed.

No 5.1 is buggy as well.

Left, Center, and Right are all good again.

No sound for Sub.

The rear speakers come out of the correct side, but in the front speakers.

**Comment by cgutman** [comment]
Is your receiver set to LPCM mode?

Can you try [this older build](https://github.com/moonlight-stream/moonlight-android/releases/tag/v8.12) to see if this is a regression related to the addition of 7.1 surround sound support?

Does the stock NVIDIA Games app have correct 7.1 audio when streaming?

The bitrate I was talking about is the actually the video bitrate. What value is set for that?

**Comment by ReenigneArcher** [comment]
- I don't believe it uses LPCM. I cannot find any mention of that in the settings or on the product page (https://usa.yamaha.com/products/audio_visual/av_receivers_amps/rx-v677/index.html#product-tabs)
   - For my setup the Shield is connected to a Bravia TV (also Android TV) which is using the ARC hdmi to go back to the receiver. So I believe the Shield is determining the sound mode.
- The older build has the same results for 5.1 audio.
- My results are the same using Nvidia Games... so probably something in GFE.
- And video bitrate was default.

Are there any requirements on the PC end for using 7.1 streaming? I don't have 7.1 audio on the PC. I wouldn't think that matters though as the NVIDIA HDMI Out shows as 7.1 once I connect Moonlight.

**Comment by ReenigneArcher** [comment]
I tried a few more tests. Instead of using ARC I used optical audio from TV to AVR. Results were exactly the same. So ARC is not the issue.

I tested using Moonlight directly on the TV to bypass the Shield. The results are similar but different.

For 7.1...
Sub comes out of center speaker.
Side and rear channels come out of the correct side but in the front speakers.

I will also try connecting the Shield directly to the AVR to see if the results change. Although that is not ideal as the receiver supports 4k pass through, but not HDR pass through.

**Comment by ReenigneArcher** [comment]
Audio is all correct when connecting the Shield directly to the receiver.

Connecting back like the original setup I cannot get audio to work no matter what. I have tried adjusting every possible sound setting that I can find in both the Shield and the TV.

Any idea what settings could cause this on a Bravia XBR65X900F?

**Comment by kentyman23** [comment]
I'm having trouble with my Side and Read channels being swapped: https://github.com/moonlight-stream/moonlight-android/issues/1295#issuecomment-1892820380

**Comment by kentyman23** [comment]
For posterity, this may've been fixed here: https://github.com/LizardByte/Sunshine/pull/694
