### ISSUE TITLE
Moonlight on FireTV - Bluetooth keyboard Windows Key does nothing and alt tab not captured

### ISSUE THREAD

**Issue by isolder** [moonlight-stream/moonlight-android#83]
I have an Apple Wireless Keyboard connected to the Fire TV. It kind of works, but not completely.

I use the Remote Desktop application added through GFE.

If I try to use the Windows Key nothing happens. Just plain doesn't work.

If I try to alt-tab the Fire TV catches it and tries to switch between Android apps instead of in the Remote Desktop.

On top of all this there is massive input lag. Maybe 3-5 seconds before any keypresses are recognized.

**Comment by cgutman** [comment]
I'll have to see if it's possible to capture Alt-Tab in Android. It's possible that the system handles it and there's nothing we can do. I'll also look into the Windows key issue too.

Can you tell if the lag is in the input or the video stream? If you use the keyboard but look at the PC screen, does it still lag?

**Comment by isolder** [comment]
I made a mistake in my title/post. I'm actually using a Fire TV *stick.* After some reading I found that I can only do 720p60fps not 1080p60.

Changing that fixed the input lag. 

The other issues remain, though.

**Comment by Timmy2914** [comment]
Another problem on the Fire TV (not rooted)  is the double mouse cursor, is there any fix for it?

**Comment by Selbram** [comment]
@Timmy2914 The fix is to use the rooted version. I had the same issue with my Ouya.

**Comment by Timmy2914** [comment]
Thanks, but I cant root my Fire TV because the software version is not rootable.

**Comment by cgutman** [comment]
Closing as this is a limitation of the GameStream protocol.
