### ISSUE TITLE
Error 418

### ISSUE THREAD

**Issue by KiriBogach** [moonlight-stream/moonlight-android#831]
I am able to connect and link with my GeForce Experience Account.

However, when I launch a game a get this error:

> Connection Failure:
> Failed launching game (418 error)
> 
> GeForce Experience returned error: Missing audio capture device. REsintall Geforec Experience. (Error code: 418)

I've reinstalled a few times GeForce Experience and I've checked my audio devices and everything seems fine. 

![image](https://user-images.githubusercontent.com/24867662/82061930-a2137b00-96c9-11ea-9807-54d353a8fcc2.png)

_Same error connecting via Windows Devices, either LAN or IP_

![image](https://user-images.githubusercontent.com/24867662/82061867-8f00ab00-96c9-11ea-8145-38b5664b5c99.png)

Can anyone help me?
Thank you in advance.

**Comment by cgutman** [comment]
Try uninstalling RTX Voice.
