### ISSUE TITLE
Moonlight on Fire TV - Bluetooth Mouse not aligned 1:1 with Windows cursor in Remote Desktop

### ISSUE THREAD

**Issue by isolder** [moonlight-stream/moonlight-android#84]
I have an Apple Magic Trackpad connected to the Fire TV.

When I open remote desktop through Moonlight the Android cursor AND the Windows cursor are both visible.

They are not anywhere close in line. The Android Cursor is 1:1 with my movement and the Windows mouse cursor is about 800 pixels to the right and maybe 200 pixels lower. I can't even make the Windows cursor go all the way to the left of the screen because of this. If I try to click something through Remote Desktop the click location is wherever the Windows cursor is so this isn't working quite right...

**Comment by cgutman** [comment]
This is expected unfortunately. It's not possible to do this in Android with the current version of Nvidia's GameStream protocol. There is a rooted version that you can use which can do this, but it requires a rooted device.
