### ISSUE TITLE
Keyboard shift/ctrl/alt state is not captured when using mouse "numpad" buttons

### ISSUE THREAD

**Issue by Ceiyne** [moonlight-stream/moonlight-android#840]
**Describe the bug**
I am using Moonlight on my Android TV, with a bluetooth keyboard and wireless mouse attached.  The mouse is an Razer Naga "mmo" mouse that has a block of 12 buttons that act similar to a numpad.  All keyboard and mouse buttons work as expected, EXCEPT for when trying to use shift/ctrl/alt on the keyboard along with the numpad keys on the mouse.  For example, if I press shift on the keyboard and the 1 button on the mouse, this should produce a keystroke of "shift+1", or "!", depending on what the current application is looking for.  However, the shift/ctrl/alt is not passed along by Moonlight and just the "1" keystroke is sent.

**Steps to reproduce**
1. From the Moonlight client on Android TV, connect to a PC and open an application.  Example: Open Notepad.
2. Hold down shift, ctrl, and/or alt on the bluetooth keyboard connected to the TV.  Example: Hold down shift.
3. Without letting go of the modifier key pressed in step 2, press one of the numpad buttons on the Razer Naga MMO mouse connected to the TV.  Example: Press the 1 key.
EXPECTED RESULTS: The application running on the PC should receive the keyboard modifier state (shift/ctrl/alt) as well as the key pressed on the mouse.  Example: Notepad should display the "!" character (the 1 key on the keyboard becomes ! when shifted).  
** The above expected results are how it works if the same keyboard and mouse are connected directly to the Windows PC, and also how it works if I use the same keyboard, mouse, and Android TV with the Steam Link app for streaming instead of Moonlight.
ACTUAL RESULTS: The application running on the PC only receives the key pressed on the mouse, and the keyboard modifier state is not received.  Example: Notepad displays the "1" character.

**Affected games**
All games/applications

**Moonlight settings (please complete the following information)**
- Have any settings been adjusted from defaults? 
Yes
- If so, which settings have been changed?
Bitrate was increased to 50000Kbps
- Does the problem still occur after reverting settings back to default?
Yes

**Client details (please complete the following information)**
 - OS: Android TV version 8.0.0, kernel version 3.10.79
 - Moonlight Version: The latest version installed via Google Play Store, which appears to be v9.5

**Server PC details (please complete the following information)**
 - OS: Windows 10.0.18363
 - GeForce Experience version: 3.20.3.63
 - Nvidia GPU driver: 445.87

**Additional context**
I am not certain, but I think that the Razer Naga mouse presents itself to the OS as both a mouse (for cursor movement and basic mouse buttons like left or right click) and a keyboard (for the numpad).  Actions like shift+left click work as expected.  It's just that when one of the numpad buttons is pressed on the mouse that Moonlight appears to ignore the bluetooth keyboard shift state.

In case you need to know, I'm trying to play Final Fantasy XIV with Moonlight.  In FFXIV, I have several rows of buttons for actions, and each button is labelled with a number.  The first row is triggered by the keys 1, 2, 3...; the second row is triggered by the key combinations ctrl+1, ctrl+2, ctrl+3...; the third row is triggered by the key combinations alt+1, alt+2, alt+3...  Without these modifiers, I cannot access two-thirds of my skills and the game becomes unplayable.

**Comment by Ceiyne** [comment]
Please do not auto-close this issue.

**Comment by Ceiyne** [comment]
Would it be possible to please get some feedback on whether this issue will be addressed?  I retested it recently and it is still not working.  In my retesting, I found some additional information that may help you when reproducing the issue.

-  The problem does NOT affect the right-Shift and right-Alt keys; only the left-Shift and left-Alt keys.  (Presumably the same is true for Ctrl but I didn't have a spare keyboard with a right-Ctrl key.)  Unfortunately, due to the layout of the game controls, as well as my lack of a right-Ctrl key, this doesn't help to work around the issue.  But hopefully it helps you find the root cause.
- You don't need an "mmo" mouse to make this happen, you can use any two keyboards attached to the same device (e.g., bluetooth keyboard, usb keyboard, "mmo" mouse).
- I examined the keystrokes that were being received on the Windows end.  For example, if I hold down left-Shift on one keyboard and press the number 1 on another, Windows receives the following:
1. Left-Shift key down
2. Left-Shift key up (this happens as soon as I press the 1 key, even though I'm still holding down Shift on the Android side)
3. 1 key down
4. 1 key up (when I release it)
Events 2 and 3 happen at the same time, so it seems like the act of pressing the 1 on a different keyboard is causing Moonlight to prematurely send a "left-Shift key up" event.

On the flip side, if I hold down the right-Shift on one keyboard and press the number 1 on another, Windows receives the following:
1. Right-Shift key down
2. 1 key down
3. 1 key up (when I release it)
4. Right-Shift key up (when I release it)
This is 100% correct behavior.

**Comment by cgutman** [comment]
The problem is that the modifiers attached to each KeyEvent reflect the state of the input device. In other words, Android segregates the state for multiple keyboards rather than having a single global keyboard state like most OSes (iOS, macOS, Windows, etc).

Please try this build which contains the fix - https://drive.google.com/file/d/1JFlYYdZi9BkvzObT2gTbw5WlTdaKg-_7/view?usp=sharing

**Comment by Ceiyne** [comment]
I tried your test build and it worked perfectly... Thanks!  It's no rush, but do you know when this might be rolled into an official Play Store build?

There are two other (regular) mouse issues I'm having, but I have seen similar-sounding issues in your Github before so I wanted to check with you before opening anything else up.  

1. The mouse sensitivity is really high.  It's probably twice as fast as the mouse normally moves when I'm physically at the computer.
2. This seemed like it was only an issue in Final Fantasy XIV: it seemed like the visual of where I saw the mouse cursor was not aligned with where the game thought the mouse was.  For example, if I tried clicking a button, I'd often "miss" and nothing would happen until I moved the mouse down 10-20 pixels below the button.  Then the click would register.  The same thing happened with mouse-over functionality.  

For the second issue above, I think the similar issue I saw on your Github said something about being related to having a second monitor.  I do have a second monitor attached to my PC.

**Comment by cgutman** [comment]
It's coming soon (currently in slow rollout on the Play Store).

1. Yeah, this is an Android limitation. I wrote a bit about it in our FAQ - https://github.com/moonlight-stream/moonlight-docs/wiki/Frequently-Asked-Questions#why-does-my-mouse-move-very-fast-on-android

2. This alignment problem seems to have been introduced in the Nvidia 450 driver series. Not all mouse cursors images start at the top-left corner, but it seems like Nvidia is rendering them that way. This causes the cursor's actual hot spot (where the click actually occurs) not to line up properly with the image. You can try downgrading your GeForce drivers to the 446 series. Some folks on Discord have found that fixes their mouse alignment issues.

**Comment by Ceiyne** [comment]
Thanks for the feedback on the other items and thanks again for fixing this issue.
