### ISSUE TITLE
Feature Request: Shortcuts on main moonlight screen or game pinning

### ISSUE THREAD

**Issue by vertigo220** [moonlight-stream/moonlight-android#841]
I just installed and tested Moonlight for the first time, on a Shield TV, and it's amazing. One issue I have though is that I can't add game shortcuts to the launcher's home screen, so to get to a game, I have to open Moonlight, then the computer, then go through the list of games to find the one I want. And since I imagine that will almost always be Steam, so I can play any game instead of just Gamestream compatible ones, that means scrolling down quite a ways to get to it. It would be nice if I could either add games as shortcuts on the main Moonlight screen, under the computer(s), or at least pin them so they're at the top of the list when I select the computer.

**Comment by cgutman** [comment]
Did you enable the Android TV channel for your PC when Android TV asked? That does exactly what you want. It will place games you play on your home screen.

If you didn't do it when you paired, I think you can still do it later from the home screen's channel settings.

**Comment by vertigo220** [comment]
You're right. It was waaaay down at the bottom, but I moved it up and it does exactly what I want. Thanks!
