### ISSUE TITLE
Magic packet (wake-on-lan) on game launch AndroidTV Channel, Oreo (Feature request!)

### ISSUE THREAD

**Issue by shinshilas** [moonlight-stream/moonlight-android#843]
Hello,
I thought it would be a really cool feature to automatically send a magic packet on game launch in android TV. Something like Steam Link does on Android phone. It makes things run really seamless in my opinion without any extra fiddling. Let me know what you think, thanks!

**Comment by cgutman** [comment]
This is supported in v10.0
