### ISSUE TITLE
I added 1600p and 1536p support.

### ISSUE THREAD

**Issue by lateforwork1000** [moonlight-stream/moonlight-android#856]
hay i add 2560x1600 and 2048x1536(4:3) is there a way to make this into the main build? im asking because i got a new tablet with the resolution of 1600p.

thanks

**Comment by lateforwork1000** [comment]
I'v also updated my xda post with the latest moonlight build but I did remove most of the older resolutions i may end up adding them back.

https://forum.xda-developers.com/nvidia-shield/general/moonlight-custom-resolutions-t3428451

**Comment by ap3nr0ts** [comment]
Can this be added to this build? I've used @lateforwork1000's on my tablet for the last couple of months, but now I can't download it again, since he removed it from his post. 1536p is the ideal resolution for my Nexus 9 that is perfect for streaming.

**Comment by lateforwork1000** [comment]
@ap3nr0ts 
Thanks for taking interest but I have stop adding support for other resolutions for moonlight if you would like other resolutions support please post or ask the developer here.

**Comment by ap3nr0ts** [comment]
No problem man. But can I just have your last build? It worked great.

Op vr 2 okt. 2020 04:14 schreef lateforwork1000 <notifications@github.com>:
