### ISSUE TITLE
Any chance of direct touch mapping?

### ISSUE THREAD

**Issue by mpedrero** [moonlight-stream/moonlight-android#86]
I have a __non-rooted__ Galaxy Tab S, and I am trying to play Civ5 with Moonlight. I can stream the game without issues, but it is difficult to play due to the lack of 1:1 touch mapping. Is there any chance of that feature to be implemented? Is it implemented in the rooted-version? If I root my Tab S, I probably will lost the warranty due to Knox, so I need to be sure.

**Comment by cgutman** [comment]
Unfortunately it's a limitation of Nvidia's protocol right now. It would be possible without root but there's just no way to tell the PC a touch position in absolute coordinates.
