### ISSUE TITLE
Video Decoder Crashed on REDMI K30i

### ISSUE THREAD

**Issue by yorkzhang** [moonlight-stream/moonlight-android#863]
Hi Developers,

I just bought a new phone RedMi K30i 5G and installed the latest version of Moonlight Android. It worked perfectly on my old XIAOMI NOTE 3, but now it displayed error "Moonlight has crashed due to an incompatibility with this device's video decoder. Ensure GeForce Experience is updated to the latest version on your PC. Try adjusting the streaming settings if the crashed continue."

I can see the release note of the latest moonlight says "Fixed decoder-related crashes on Xiaomi Mi 10 Lite 5G devices", and I found #5c6be79 has some code fix for REDMI K30i but the fix does not work on my phone. The OS on my phone is MIUI 12.0.3 with Android 10. Thanks.

**Comment by cgutman** [comment]
Fixed in Moonlight Android v9.7.1.
