### ISSUE TITLE
20:9 resolution support

### ISSUE THREAD

**Issue by xIBlack97** [moonlight-stream/moonlight-android#864]
Most smartphone now have 20:9 or 18:9 display, can you add the support for that kind of display?
For example resolution like 3200x1440 or 2220x1080

**Comment by lateforwork1000** [comment]
iv add those resolutions, not sure if they work don't have anyway to test them.
https://forum.xda-developers.com/nvidia-shield/general/moonlight-custom-resolutions-t3428451/post67954611#post67954611

**Comment by xIBlack97** [comment]
Ok It works, but i need to create a new resolution from the nvidia control panel to match the resolution of the stream
