### ISSUE TITLE
Connection Terminates after several seconds

### ISSUE THREAD

**Issue by ClawmanCat** [moonlight-stream/moonlight-android#87]
I'm using a rooted ZenFone 5 running KitKat 4.4.2.
The PC runs Windows 7 x64 and has an ASUS GTX 650. I'm using driver version 353.38 and GFE version 2.4.5.57.

Whenever I launch a game trough Moonlight, the Nvidia Gamestream logo will appear for a few seconds, and then disconnect with the message "The connection was terminated". The application also exits on the PC.

**Comment by ClawmanCat** [comment]
Launching the Windows Remote Desktop (mstsc.exe) trough Gamestream does work, but the connection still terminates as soon as I launch a Steam game.

**Comment by BenderTarz** [comment]
Hi, were you able to fix this?

**Comment by ClawmanCat** [comment]
No.

**Comment by ClawmanCat** [comment]
No. I tried reinstalling Windows but now I just get error 521.

**Comment by BenderTarz** [comment]
Hmm that sucks, I've the same problem not sure if it's drivers related

**Comment by ClawmanCat** [comment]
Issue was caused by a corrupted Windows install. The install disk I had was corrupted as well, which caused the issue to persist after a fresh install. Getting a new Windows ISO, and doing a fresh install using that fixed the issue for me.
