### ISSUE TITLE
Suggestion - Add Mouse Mode

### ISSUE THREAD

**Issue by erdog** [moonlight-stream/moonlight-android#873]
The moonlight-qt client has the option to toggle the mouse mode. Without this, the android version mouse is stuck with acceleration, which is a bad experience when trying to do regular desktop things.

**Comment by cgutman** [comment]
The problem is that pointer capture is the only way apps can prevent the pointer from interacting with the System UI. There is no way to suppress the appearance of the Navigation Bar or Status Bar when the mouse hovers over it (even just for a split second).

**Comment by erdog** [comment]
So absolute mouse mode isn't possible due to Android itself?

**Comment by lateforwork1000** [comment]
i have the same question, the previous build/really old builds seem to handle the mouse just fine but the new build seem to have add mouse acceleration really annoying and sometimes unusable you can get more mouse option but i think that does come down to more coding/work I'm using samsung dex and i now have alt-tab middle mouse support. (i think something along the lines as Android printer drivers odd still need download them to get it to work.)  Ill see if i can fine one of the older builds. Also why isn't there more to resolutions ? iv been able to customize it but still nothing in the office build.

**Comment by cgutman** [comment]
I think I can emulate it with pointer capture by just maintaining a fake virtual cursor that moves with the relative mouse events from the captured pointer.

@lateforwork1000 Which older Moonlight build behaves better? Pointer capture was implemented in Moonlight over 2 years ago, so it's unlikely that you're actually using a build that old (since it wouldn't work with current GeForce Experience versions).

What is your use case for absolute mouse mode? Remote desktop functionality or games? If games, which games?

GameStream only officially supports 720p, 1080p, or 4K resolutions. Other resolutions don't get configured properly when streaming without manual intervention (host resolution always set to 720p). That is why we don't offer them as official options.

**Comment by lateforwork1000** [comment]
@cgutman I wasn't able to get any of the very older build to work, I use to own a 980ti and a tab s2 and 3 back then the mouse work just like a pc.
Gamestream does not officially support moonlight and moonlight isn't a official release of Nvidia, I think it really comes down to the developer to add the support.( I also couldn't any thing about official resolutions ) 

https://forum.xda-developers.com/nvidia-shield/general/moonlight-custom-resolutions-t3428451/post67954611#post67954611

**Comment by erdog** [comment]
> What is your use case for absolute mouse mode? Remote desktop functionality or games? If games, which games?

Both. I'm using moonlight as my main way to access my windows machine. For games, CSGO and other FPS games. The acceleration makes aiming very difficult.

**Comment by lateforwork1000** [comment]
also why does the pc version support other resolutions ? can you not just copy the code used in the android build?

**Comment by KiralyCraft** [comment]
Most Android decoders get upset when streaming at resolutions different than the pre-defined ones. It's not as easy as copy-pasting the code. If you have a weirder resolution, select the most appropriate one and tick the "strech to fill" option. Your host must have the same aspect ratio

**Comment by jorbig** [comment]
Any updates on the status of this very important feature request?

**Comment by cgutman** [comment]
Implemented in 81a3bbd5e8ba07990d901c0b6d77276c8ee43b1b

**Comment by jorbig** [comment]
I tried the Remote desktop mouse mode in the new beta app, but it doesn't work for me. The mouse cursor is invisible (until I enable 'Mouse keys' in Windows settings, but that shows me the laggy remote cursor, not the faster local one.

**Comment by cgutman** [comment]
That's the intended behavior of the option. This request isn't for client-side cursor support. It's adjusting the way that mouse input is sent to the host to avoid double-acceleration of mouse motion for applications that don't use raw mouse input.

#959 describes the request for client-side cursor support.
