### ISSUE TITLE
Suggestion - Add packet size option

### ISSUE THREAD

**Issue by erdog** [moonlight-stream/moonlight-android#874]
The moonlight-qt version allows you to set the packet size from the command line. I found this to be crucial for lowering my receive time while wired on LAN. The default 1500 is not enough for 1440p 120hz. I crank it up to 20000 and experience consistent rec times of around .10ms. I'm experiencing the same high receive times while using the android app at 1440p at 120hz wired.

Also, is there anything stopping allowing 150mbps? The app is limited to 100. I feel like image quality isn't as great.

**Comment by erdog** [comment]
Looking at StreamConfiguration.java, the packet size option is mostly implemented. The app just needs another option in the GUI to set it.

**Comment by KiralyCraft** [comment]
Could add your suggestion to the unified suggestions place: https://ideas.moonlight-stream.org/
