### ISSUE TITLE
Connection lost issue when laptop is charging!

### ISSUE THREAD

**Issue by Saqo1995s** [moonlight-stream/moonlight-android#876]
Yea that's only an issue :) When I unplug the charging cable everything is working great!
My laptop: MSI GF63 Thin 9RCX.

**Comment by lateforwork1000** [comment]
not trying to be rude but this really isn't moonlight problem, but if i had to guess maybe nvidia optimus? your laptop is probably switching from nvidia to intel graphics?.

**Comment by Saqo1995s** [comment]
> not trying to be rude but this really isn't moonlight problem, but if i had to guess maybe nvidia optimus? your laptop is probably switching from nvidia to intel graphics?.

I know about this Nvidia feature but I am pretty sure that by default (and I am sure that I don't change the setting) games running on the discrete video card! By the way, I will try to play with settings and let you know if an issue in the GPU switching feature!

**Comment by Saqo1995s** [comment]
Nvidia experience update fixed the issue.
