### ISSUE TITLE
华为电视不能用，不能连接，希望开发者解决 HUAWEI TV unable to connect not available

### ISSUE THREAD

**Issue by wtugug** [moonlight-stream/moonlight-android#877]
华为电视不能用，不能连接，希望开发者解决 HUAWEI TV unable to connect not available

**Comment by wtugug** [comment]
HUAWEI TV unable to connect not available   ，HarmonyOS1.0.1.32

**Comment by wtugug** [comment]
Can be installed but not connected

**Comment by wtugug** [comment]
HarmonyOS  The code is open source   https://github.com/Awesome-HarmonyOS/HarmonyOS

**Comment by wtugug** [comment]
steamlink    You can use it but it doesn't work very well

**Comment by wtugug** [comment]
steamlink     can use it but it doesn't work very well

**Comment by cgutman** [comment]
Can you post a screenshot of the error you receive trying to use Moonlight on Harmony OS?

**Comment by wtugug** [comment]
> 您可以发布在尝试在Harmony OS上使用Moonlight时收到的错误的屏幕截图吗？

pc, input digit ,moonlight self-closing，v9.7.3

**Comment by wtugug** [comment]
> 您可以发布在尝试在Harmony OS上使用Moonlight时收到的错误的屏幕截图吗？



> Can you post a screenshot of the error you receive trying to use Moonlight on Harmony OS?
pc, input digit ,moonlight self-closing，v9.7.3

**Comment by wtugug** [comment]
> Can you post a screenshot of the error you receive trying to use Moonlight on Harmony OS?

pc, input digit ,moonlight self-closing，v9.7.3

**Comment by wtugug** [comment]
I recorded a video. How can I send it to you by email？

**Comment by wtugug** [comment]
Open source code, new location https://openharmony.gitee.com/openharmony

**Comment by wtugug** [comment]
> 您可以发布在尝试在Harmony OS上使用Moonlight时收到的错误的屏幕截图吗？



> Can you post a screenshot of the error you receive trying to use Moonlight on Harmony OS?

It wants to support the world's third largest operating system

**Comment by wtugug** [comment]
Development tool download address
https://developer.harmonyos.com/cn/develop/deveco-studio

**Comment by wtugug** [comment]
Is there any progress

**Comment by wtugug** [comment]
hope to get help

**Comment by wtugug** [comment]
![20201109_191949](https://user-images.githubusercontent.com/70991490/98535427-0bfb8e80-22c1-11eb-8386-d069037868dd.jpg)
![20201109_192013](https://user-images.githubusercontent.com/70991490/98535436-1027ac00-22c1-11eb-8150-2f4aeb5a1bdc.jpg)
![20201109_192019](https://user-images.githubusercontent.com/70991490/98535440-13229c80-22c1-11eb-8a78-3077aae04eb6.jpg)


decoder

**Comment by cgutman** [comment]
I think this was fixed several releases ago.
