### ISSUE TITLE
App Intents

### ISSUE THREAD

**Issue by ReenigneArcher** [moonlight-stream/moonlight-android#878]
Not an issue, just a question... Does the app have any intents?

I'd like to use adb to launch moonlight directly to a specific machine and possibly program if it's possible.

**Comment by ReenigneArcher** [comment]
Found two intents using "Package Manager" app.

Looks like com.limelight.PcView and com.limelight.ShortcutTrampoline

First one just takes me to the same as opening the app. Second one errors out with the following.

```
**Connection Error**
Provided PC is not valid
```

my adb command is `adb shell am start -n com.limelight/com.limelight/ShortcutTrampoline`

Anyway to make it connect to a specific machine?

**Comment by profucius** [comment]
Refer to this comment, you may be able to adapt the command to adb for your needs:

https://github.com/moonlight-stream/moonlight-android/pull/603#issuecomment-739050460

**Comment by profucius** [comment]
> 
> 
> Found two intents using "Package Manager" app.
> 
> Looks like com.limelight.PcView and com.limelight.ShortcutTrampoline
> 
> First one just takes me to the same as opening the app. Second one errors out with the following.
> 
> ```
> **Connection Error**
> Provided PC is not valid
> ```
> 
> my adb command is `adb shell am start -n com.limelight/com.limelight/ShortcutTrampoline`
> 
> Anyway to make it connect to a specific machine?

Refer to this comment, you may be able to adapt the command to adb for your needs:

https://github.com/moonlight-stream/moonlight-android/pull/603#issuecomment-739050460

**Comment by ReenigneArcher** [comment]
@profucius thank you for the response... I need to give this a try.

**Comment by ReenigneArcher** [comment]
@profucius That works! Do you know if it's possible to pass arguments to the program?

Say appId if for retroarch and I want to launch it with a specified core and rom?

I'm currently just streaming the desktop and have a second part of my script launch retroarch with arguments... problem is if I end the streaming session retroarch stays open on the host.

**Comment by profucius** [comment]
> 
> 
> @profucius That works! Do you know if it's possible to pass arguments to the program?
> 
> Say appId if for retroarch and I want to launch it with a specified core and rom?
> 
> I'm currently just streaming the desktop and have a second part of my script launch retroarch with arguments... problem is if I end the streaming session retroarch stays open on the host.

That's a great question, one that I think Moonlight dev might be able to speak to?

As far as my experience goes, I haven't yet found a way to pass arguments through shortcuts. The only way I would know how to do it thus far, albeit a bit tedious, is to make a .BAT file for each game you want to launch, put your retroarch cmd + argument inside, save, and then add that .BAT file to the Geforce Experience app manually. It does work, I do this for some of my games that I launch using Autohotkey/WinAutomation for macro purposes. But like I said, a bit more tedious than it may be worth if you have lots of games.

As for the closing afterwards, it seems this is not a Moonlight issue but Geforce Experience. The game will only close after exiting the session if the .EXE matches that which the shortcut points to. But again this may be something the Moonlight dev can speak to.

**Comment by cgutman** [comment]
> @profucius That works! Do you know if it's possible to pass arguments to the program?
> 
Unfortunately, not. You'll have to create a specific shortcut with the arguments included.

> As for the closing afterwards, it seems this is not a Moonlight issue but Geforce Experience. The game will only close after exiting the session if the .EXE matches that which the shortcut points to. But again this may be something the Moonlight dev can speak to. 

Yep, this is accurate.

**Comment by ReenigneArcher** [comment]
> 
> 
> > @profucius That works! Do you know if it's possible to pass arguments to the program?
> 
> Unfortunately, not. You'll have to create a specific shortcut with the arguments included.
>

@cgutman 
Is this a moonlight limitation or Nvidia? Would be very beneficial if we could pass arguments along in my opinion.


>As for the closing afterwards, it seems this is not a Moonlight issue but Geforce Experience. The game will only close after exiting the session if the .EXE matches that which the shortcut points to. But again this may be something the Moonlight dev can speak to. One workaround to this that you might use is a macro tool, I use WinAutomation but you could try others such as EventGhost. Set a trigger for watching nvcontainer.exe (which is what streams games), when it terminates, a macro is run to terminate retroarch.exe as well. You might even be able to use command tools only, there may be a NirCmd method of "if X terminates, do Y". That's the idea anyways.

@profucius 
For me it looks like nvstreamer.exe is what is running when I start a stream session. I have several nvcontaier.exe's running even without streaming anything. I'll just keep my start script running until nvstreamer is terminated after which I'll terminate retroarch. Thanks for the idea!

**Comment by profucius** [comment]
> @profucius 
> For me it looks like nvstreamer.exe is what is running when I start a stream session.

Yes it is nvstreamer, my mistake I was in a rush this morning. Good catch. Good luck to you!

**Comment by ReenigneArcher** [comment]
Possibly found another hacky solution.

The shortcuts are in this directory (on windows). `%localappdata%\NVIDIA Corporation\Shield Apps`

Can just add shortcuts here with my script. Is there an automated way to get the app id's? If not I guess I can just modify an existing shortcut each time.

**Comment by ReenigneArcher** [comment]
It works on my machine... All I have to do is create the shortcut and it immediately shows up in moonlight client apps and GFE... Deleting the shortcuts immediately removes them.

I searched all the files in Nvidia folders and couldn't find any text matching my custom shortcuts. If they're in a database it's encrypted, but it does update instantly.

If you don't add the streaming assets folder it will remove it in GFE when you switch to the shield tab. If the shortcut and assets are there it won't do anything with it.

I discovered the appid changes when the target changes. Doesn't have anything to do with the name or start directory. Not sure how that's generated yet. Until that's figured out, my solution won't work.

**Comment by profucius** [comment]
> It works on my machine... All I have to do is create the shortcut and it immediately shows up in moonlight client apps and GFE... Deleting the shortcuts immediately removes them.
> 
> I searched all the files in Nvidia folders and couldn't find any text matching my custom shortcuts. If they're in a database it's encrypted, but it does update instantly.
> 
> If you don't add the streaming assets folder it will remove it in GFE when you switch to the shield tab. If the shortcut and assets are there it won't do anything with it.

I've tried this myself and you're right, you must have the folder inside Streaming Assets, which is a hidden folder inside Shield Apps folder. I had never found it before because it was hidden. I manually added a link and a folder with a box-art.png file, and it worked fine. This changing my workflow a lot with new games! Did you say you have or are working on a script for adding games? If so, I'd love to take a look at it and tweak it for my purposes a bit. It would save me a lot of time adding new games.

> I discovered the appid changes when the target changes. Doesn't have anything to do with the name or start directory. Not sure how that's generated yet. Until that's figured out, my solution won't work.

I've noticed this too, I had to re-add a game once, and then the launch shortcut I was using on the homescreen of my Shield no longer loaded the game. I wonder if @cgutman knows a better way to grab appid for scripting purposes?

**Comment by ReenigneArcher** [comment]
@profucius I'm working on a script so to say... I'm creating a game streaming launcher / front end. My scripts will scan the rom directories, grab metadata, and watch for events to trigger launching the games. Initially it will utilize moonlight for the client app but not for anything else. For now that's all I can share, but once I get it more ready for prime time I'll definitely be sharing it on github. I'm about 80% of the way complete.

So for me I'm just wanting to replace a single shortcut. (I don't want to create thousands of shortcuts in GFE/moonlight.) Can't do that until I can figure out how the app ID was calculated. I'm assuming it's a type of integer based UUID but couldn't figure it out exactly by looking at the source code... hopefully a dev could assist?

Alternatively if we could launch a shortcut by appName instead of appId that could be even better/easier.

**Comment by cgutman** [comment]
I don’t know how Nvidia generates the app ID. From Moonlight’s perspective, it’s just an opaque integer that GFE gives us and we send back.

**Comment by ReenigneArcher** [comment]
@cgutman oh I see. Could you point me to the part of the code where moonlight receives the app id? Maybe I could replicate that.
