### ISSUE TITLE
Cannot connect to GFE 2.4.5.57

### ISSUE THREAD

**Issue by Xylynx** [moonlight-stream/moonlight-android#88]
Hello, I cannot seem to connect to my PC running GFE 2.4.5.57 either automatically or manually. In this version I also noticed that there is no "Game stream" tab in the preferences page?
Could this have something to do with it?

Regards
Nathan

**Comment by Selbram** [comment]
You might want to try reinstalling GFE and your NVidia drivers. It is normal on my setup.

**Comment by Xylynx** [comment]
Thank you, that's solved the issue
