### ISSUE TITLE
I can't use moonlight with controller anymore

### ISSUE THREAD

**Issue by Adensstuff** [moonlight-stream/moonlight-android#881]
Every single time I open moonlight and press B or Y it exits out of the game I am trying to play. I have had a recent update on my phone and before it worked perfect but now on android 11 I can't seem to use moonlight anymore.

**Comment by danieljrich** [comment]
It appears there is an OS issue with remote controller input and game streaming. I did a bit of Googling, and tested myself, and found that SteamLink doesn't work either since upgrading to Android 11.
Not even onscreen controls work. I'll let you know if I find a workaround, but unfortunately for now, we'll just have to wait, or downgrade to Android 10.

**Comment by danieljrich** [comment]
@Adensstuff I found an app called Rainway that does game streaming. Not as good as Moonlight, but it works. The touch controls at least. Haven't been able to try a bluetooth controller yet.
Might be an OK workaround until this Android 11 issue is resolved.

**Comment by cgutman** [comment]
If the touch controls aren't working either, it's not related to Android 11. It's something wrong with your host.

You should ensure that Steam's custom controller configuration is turned off. If it still happens with it turned off, do a clean install GeForce Experience and your Nvidia driver to reinstall the virtual gamepad drivers. If none of that works, you should join our Discord server for more help

**Comment by danieljrich** [comment]
Sorry, I misspoke. Touch controls do indeed work find. On other streaming apps too. Just external controllers don't work at all on any of them.

**Comment by dkr88** [comment]
Same issue here on Pixel 4 with Android 11. Gamepad inputs do not work in streaming session. B and Y just act as back button and close the session.

**Comment by cgutman** [comment]
Sounds like this Android bug - https://issuetracker.google.com/issues/163120692

Try the suggested workaround and see if that fixes it.

**Comment by dkr88** [comment]
> Sounds like this Android bug - https://issuetracker.google.com/issues/163120692
> 
> Try the suggested workaround and see if that fixes it.

Thanks - disabling the Button Mapper accessibility service fixed it for me.

**Comment by danieljrich** [comment]
Well, what do you know. I disabled some AutoClicker overlay apps in Accessibility Settings, and now the controller is working just fine. Thank you very much for this easy workaround.
