### ISSUE TITLE
Flashing black screen on Shield Pro

### ISSUE THREAD

**Issue by daninthemix** [moonlight-stream/moonlight-android#882]
I've been testing Witcher 3 through Moonlight running on a Shield Pro. When the game is set to fullscreen, I get a black screen flicker every second or so. If I switch the game to borderless fullscreen, the flicker goes away, but streaming performance isn't as good - I get stutter.

Settings: 4k, 60fps, 80Mbps (default), never drop frames = on. H265 is on the default setting.
Host has a 2080Ti. Connections are all gigabit ethernet. Has does have a 4K G-sync screen, and G-sync would only be active in fullscreen (not borderless) so I don't know if that's relevant?

Gamestream through the Nvidia app is perfect.

Just trying to understand the rules around streaming and how to settle on a configuration that gives a good experience.

**Comment by cgutman** [comment]
Please upload your GeForce Experience logs from `C:\ProgramData\NVIDIA Corporation\NvStream` after streaming with the issue.

Does it also happen with Moonlight clients on other devices?

**Comment by daninthemix** [comment]
Thanks for replying. Attached is the log. I don't have any other devices to run Moonlight on.
[NvStreamerCurrent.log](https://github.com/moonlight-stream/moonlight-android/files/5268527/NvStreamerCurrent.log)

**Comment by daninthemix** [comment]
There's a lot in that log - it might also include me streaming using GameStream and / or Steam Link. Not sure. But there's definitely a Moonlight session in there as well.

**Comment by cgutman** [comment]
It looks like the issue may be either the lines with:
```
#0(W)[2020-09-23 07:06:02,584]=08:06:02={12000}<VideoStreamer>    Handling the pre-capture pipeline event took a long time (129ms)!
```
or
```
#6(W)[2020-09-23 07:06:04,701]=08:06:04={1452}<VideoSender>      Skipping FEC: numTotalSrcPackets[147] exceeds m_numMaxSrcPackets[125]
```

Can you attach another log using the official GameStream client so I can compare?

**Comment by daninthemix** [comment]
I may not be able to do that until the weekend. If it's any help this is the other log file that's there: 
[NvStreamerOld.log](https://github.com/moonlight-stream/moonlight-android/files/5268601/NvStreamerOld.log)

**Comment by daninthemix** [comment]
OK I think this is caused by G-Sync. I set the NVCP profile for Witcher 3 to 'fixed refresh rate' so it doesn't use G-Sync - then streamed to Moonlight and the black flickers are gone. I then jacked up the bitrate to 100Mbps and it still worked fine. Attached are 3 logs, in case its of any use to you. 
[Moonlight_Stream_No_Gsync.log](https://github.com/moonlight-stream/moonlight-android/files/5269958/Moonlight_Stream_No_Gsync.log)
[Moonlight_Stream_No_Gsync_100mbps.log](https://github.com/moonlight-stream/moonlight-android/files/5269959/Moonlight_Stream_No_Gsync_100mbps.log)
[Moonlight_Stream_Gsync.log](https://github.com/moonlight-stream/moonlight-android/files/5269960/Moonlight_Stream_Gsync.log)

**Comment by daninthemix** [comment]
Just played a long session. I still get a single flicker every few minutes, which is much much better than every few seconds, which was the case with G-Sync enabled. Not sure if we can get rid of the remaining flickers, but I've attached a large log file from a long play session.
[NvStreamerCurrent.zip](https://github.com/moonlight-stream/moonlight-android/files/5287154/NvStreamerCurrent.zip)

**Comment by daninthemix** [comment]
The remaining flickers are fixed by disabling the second monitor before streaming.
