### ISSUE TITLE
Controller not working on ios.

### ISSUE THREAD

**Issue by Slowkake** [moonlight-stream/moonlight-android#886]
It’s connected via blutooth perfectly....Just when its on moonlight it dosn’t seem to work?Not sure if this is a bug but haven’t had any luck for 2 day’s...anybody have any help?

Make things clear it connects to my iphone perfectly but when moonlight comes up and i go onto a game there is no input or anything.

**Comment by cgutman** [comment]
This is the Android bug tracker. If you're still having this issue and you don't find help on the Discord server, please file a bug on the iOS bug tracker.
