### ISSUE TITLE
Suggestion: 2 small QOL improvements

### ISSUE THREAD

**Issue by Michoko92** [moonlight-stream/moonlight-android#888]
Hi,

Thank you so much for making Moonlight. On my Shield TV, this is a much better alternative for me than the native Nvidia Games app.

I'd have two small QOL suggestions for the grid navigation:
- Make the frame around the selected grid item brighter, so it is easier to see which item is currently selected
- Add some "cycling" feature, i.e. if you reach the right side of the grid, and press right again, the selector then appears on the left of the grid. Same for top / bottom, so you can quickly reach the bottom of the list by pressing up.

Thank you! :)

**Comment by KiralyCraft** [comment]
Feel free to add your suggestion here: https://ideas.moonlight-stream.org/
