### ISSUE TITLE
disable double touch joystick for l3 r3, show l3 r3 and other buttons at the same time please

### ISSUE THREAD

**Issue by littlefunny233** [moonlight-stream/moonlight-android#889]
it effect touch screen control, please improve it up

**Comment by Icing-weaponry** [comment]
i would so be interested in this improvement.
I tend to adjust the camera with the right stick many time cause the frequent clicking to act as a double click.
I did try to compile my own version with these changes (disable double click and seperate l3 and r3 button) but me being very n00b in android building i was unable to.

anywho thanks for taking the time to read and hope you have a good one
keep up the good work!

**Comment by athlan20** [comment]
I have forked a version and added l3 r3 with all buttons, please try if you need :)

[moonlight-android_L3R3](https://github.com/athlan20/moonlight-android-L3R3)
