### ISSUE TITLE
Feature request. Moonlight native oculus quest build with sbs support.

### ISSUE THREAD

**Issue by drowhunter** [moonlight-stream/moonlight-android#890]
This seems like a realistic thing since Quest apps are just android apks. Seeing something official from you guys would be great.

**Comment by KiralyCraft** [comment]
Could add your suggestion in the official place: https://ideas.moonlight-stream.org/

**Comment by drowhunter** [comment]
didn't know that place existed.  
I've added it.

**Comment by KiralyCraft** [comment]
It's only been added recently, and not widely advertised yet
