### ISSUE TITLE
Streaming over LTE doesn't work since v8.10

### ISSUE THREAD

**Issue by lkeya** [moonlight-stream/moonlight-android#892]
Hello, since v8.10, I can't stream over LTE, a "Poor connection to PC" notification shows up, the screen instantly freezes and I just can't do anything, no matter what settings I use. Whereas up to v8.9, there was absolutely no problem.

I'm using a OnePlus 5 phone, currently running Android 10 under the LineageOS 17.1 rom, but that's only since a couple of days, before I was running the stock rom with Android 10 too, if that can help.

**Comment by cgutman** [comment]
Did you test Moonlight Android v9.7.7? It reversed a change to QoS made in v8.10 that broke streaming for another user.

**Comment by lkeya** [comment]
Just tested it, I didn't know it was released as I download the app directly from the github releases, anyway, it did fix the issue, thank you very much.

**Comment by cgutman** [comment]
Yeah sorry, I forgot to release it on GitHub. I will try to remember to do it today.

Thanks for confirming that it fixes the issue.
