### ISSUE TITLE
How to turn off mouse acceleration?

### ISSUE THREAD

**Issue by tenninex** [moonlight-stream/moonlight-android#893]
First , I want to thank you for your hardworking on moonlight. It's a very useful application.

I use otg cable to connect my keyboard and mouse to play pc games on my android phone , but I found that mouse acceleration is enabled(I can feel it while moving my cursor , but I had already turned it off in my windows setting).
It's very difficult for me to play games with mouse acceleration on , and I didn't find any solution in moonlight settings. 
Is there any method to fix this problem?

**Comment by cgutman** [comment]
Unfortunately it is not possible to disable on Android (except on the Nvidia Shield where Nvidia added support to the OS for that). Google will need to implement it in a future version of Android.

**Comment by mirh** [comment]
[Cool](https://github.com/moonlight-stream/moonlight-android/commit/dfbffea0fc2bbc8a45945e5c98ee92a925de6691) (unfortunately nvidia stopped to provide sources for platform_frameworks_base after release 30, aka Experience ~7.2). 
You could point users into voting the right issue though. 
https://issuetracker.google.com/issues/170313462

**Comment by mirh** [comment]
Not fixed, though maybe I found out where it's defined in the OS code
https://github.com/LineageOS/android_frameworks_base/blob/lineage-18.1/libs/input/PointerController.h
https://github.com/LineageOS/android_frameworks_native/blob/lineage-18.1/libs/input/VelocityControl.cpp
https://github.com/LineageOS/android_frameworks_native/blob/lineage-18.1/services/inputflinger/include/InputReaderBase.h#L264

**Comment by mirh** [comment]
Bad bot. 
Btw there's [supposedly](https://android.stackexchange.com/a/244546/167375) a half-assed hack on samsung phones.
