### ISSUE TITLE
Razer Kishi

### ISSUE THREAD

**Issue by PistolPineapple** [moonlight-stream/moonlight-android#895]
I use a razer Kishi controller with a pixel 4 xl. Recently I started to steam a game but once I had to press the B button it exited the game, half of the controller works in game (left half) and the other half controls the phones os. Do you know anyway to fix this? I contacted razer and after my experience with their customer support I will never buy another Razer product. Thank you for any help you can give.

**Comment by robbiered** [comment]
I do not have this issue. Razer Kishi with Samsung S10 5G. In settings do you have use the moonlight driver checked? Might help, unsure.

**Comment by PistolPineapple** [comment]
Sorry but bare with me. What driver do you mean driver in setting? Also it may be a issue with an update I recently installed to my phone.

**Comment by jrwdexter** [comment]
I'm having the same issue — but had successfully done this on my previous Pixel 2 XL.

**Hardware confirmed working**
Controller Device: Razer Kishi
App: Moonlight-android (~2 months ago, unknown version)
Phone: Pixel 2 XL

**Hardware/software confirmed with issues**
Controller: Kishi **or** NVidia Shield Controller
App: Moonlight-android 9.7.7
Phone: Pixel 5

**Faulty Behavior**
Left joystick works. B or Y perform a "Back" function (out of streaming).

**Other Apps Confirmed Working**
[Gamepad Tester](https://play.google.com/store/apps/details?id=ru.elron.gamepadtester&hl=en_US&gl=US): Shows all keycodes operating appropriately
[Valkyrie Profile](https://play.google.com/store/apps/details?id=com.square_enix.android_googleplay.ValkyrieProfilew&hl=en_US&gl=US): All controls work fine.

Based on my tests, I've ruled out the controller (2 controllers known to work tested). Additionally, Steam Link has behavior that's even worse - not even the joystick works.

**Comment by cgutman** [comment]
Should be fixed with the accessibility workaround introduced in v9.8.2
