### ISSUE TITLE
Launch any GFE app instead of Steam only

### ISSUE THREAD

**Issue by s0ckz** [moonlight-stream/moonlight-android#9]
I really enjoyed this app and I would like to contribute making the following feature: "Choose from the list of available games instead of just launching Steam". 
I already made some tests and managed to run Diablo III and GTA IV using Limelight. 
Since I don't have too much experience on Android, I would like to do something simple: a spinner on the main screen and a button to load the apps from the chosen server. The selected app could be stored as the other properties. What do you think?

**Comment by kairukun93** [comment]
can you add list view on the PC client too? it would be great, because I'm having issue with steam app not found in GFE app list! so this is awesome, i use my tablet, works great and I want to try it on my laptop if theirs a app list view on the next limelight pc client update!

**Comment by mathiasuhl** [comment]
+1
