### ISSUE TITLE
Android TV ADT-1 Controller > Map Back button as Start/Menu 

### ISSUE THREAD

**Issue by halfluck** [moonlight-stream/moonlight-android#90]
Hey Guys,

The ADT-1 Android TV Controller which is identical to the Nexus Player controller in every way shape or form, the Back (Start/Menu) does not work because the Device Name for this is "Gamepad" not "ASUS Gamepad" so it just uses defaultContext

Line 289 (devName.contains("ASUS Gamepad"))

http://i.imgur.com/6Tvcrwv.jpg

Cheers Rob.

**Comment by cgutman** [comment]
Fixed by 26a4fc75a5d709c64468cd7892852a68c71adb7f
