### ISSUE TITLE
FireTv black screen

### ISSUE THREAD

**Issue by FROeHlyEisvogel** [moonlight-stream/moonlight-android#900]
Hello everyone,
since a few months I have the issue that I get a black screen when using moolight on fire tv.
Today I did a little bit testing and found out that there is no problem while using it on my mobile phone.

I have now installed the newest version (v9.7.7) on my fire tv.
Tried different settings for resolution and fps and different games.
But there is still the issue that I get a black screen (but sound).

I have two monitors installed, directly connected to the graphics card (GeForce GTX 1060 6GB).

Please let me know if you have an idea how to fix this problem.

**Comment by SnejPro** [comment]
I have the same issue. I tried it with AC III, IV and mstc. Only sometimes a frame of the game menu appeared.

**Comment by cgutman** [comment]
If you disable H.265 in the Advanced Settings section of Moonlight, does it change this behavior?
