### ISSUE TITLE
Feature request: Add "Sleep Host PC" feature

### ISSUE THREAD

**Issue by Jukiro** [moonlight-stream/moonlight-android#901]
I love how you implemented "Wake up Host PC" feature in the app. It makes it very convenient to wake up sleeping host pc but it would be best that you also implement sending a sleep feature in the app. Maybe sending some keystroke combination to the host - or any way, that would be great!

**Comment by mkaflowski** [comment]
I workarounded it with making shortcut to sleeping and adding it manually to library.

**Comment by Jukiro** [comment]
> I workarounded it with making shortcut to sleeping and adding it manually to library.

Yeah, I also did that... I think it would need to be a native feature of NVidia Gamestream to implement it.
