### ISSUE TITLE
Moonlight app shows an error on custom rom flashed on my android

### ISSUE THREAD

**Issue by OrientxPearL** [moonlight-stream/moonlight-android#902]
![Screenshot_20201129-100153](https://user-images.githubusercontent.com/58877971/100533119-b730a100-31f8-11eb-8906-b6597871be12.png)
![Screenshot_20201129-100201](https://user-images.githubusercontent.com/58877971/100533121-bac42800-31f8-11eb-875a-3d4889a135fd.png)
![Screenshot_20201129-122443](https://user-images.githubusercontent.com/58877971/100533335-0aa3ee80-31fb-11eb-81af-c1ce36aea6ab.png)
![Screenshot_20201129-122452](https://user-images.githubusercontent.com/58877971/100533337-0ed00c00-31fb-11eb-966d-0d3122b3fdef.png)

I was able to properly stream on my android before when I still use the stock rom of my phone but after flashing a custom rom I get "This device or ROM doesn't support hardware accelerated H.264 playback" error when starting stream with moonlight. The screenshots is the codecs of my phone and the details of the device I'm using.

**Comment by cgutman** [comment]
It looks like you're missing an AVC (H.264) decoder. I see an AVC _encoder_ in the list, but not a _decoder_. It looks like it should be called `OMX.MTK.VIDEO.DECODER`.

You should ask the ROM developer why the MediaTek video decoder is not present on the custom ROM.

**Comment by OrientxPearL** [comment]
Thanks so much for the reply 
the custom rom for the device that im using has been long abandoned by the rom dev so i'll be reverting back to my stock rom to get moonlight working again.
