### ISSUE TITLE
How to edit controller configuration or customize the controller GUI within the Android project ?

### ISSUE THREAD

**Issue by S4nfs** [moonlight-stream/moonlight-android#906]
How do i edit the on-screen controller GUI or the default values while creating the Apk project file ?

[BUG] Also i am facing some controller issues on 5.0 inch screen sized android devices , However it gets fixed after enabling full screen.

![Screenshot_20201207-010454](https://user-images.githubusercontent.com/75138345/101351083-0ab88400-38b6-11eb-9eba-133863191359.jpg)
![Screenshot_20201207-010826](https://user-images.githubusercontent.com/75138345/101351086-0c824780-38b6-11eb-8149-294bd5978999.jpg)

**Comment by cgutman** [comment]
The controller elements are added in https://github.com/moonlight-stream/moonlight-android/blob/master/app/src/main/java/com/limelight/binding/input/virtual_controller/VirtualControllerConfigurationLoader.java

You can add/remove/move/resize them there. For the on-screen controls rendering issue, please file a new bug for that (including what device you have, what version of Android it is running, and what steps produced the issue).
