### ISSUE TITLE
DS4 always  out of control in Android

### ISSUE THREAD

**Issue by YABIJIU** [moonlight-stream/moonlight-android#908]
Xbox controller is well in Android 11 and iOS 13.
DS4 controller is well in iOS 13,but it's always out of control in Android. We must restart the controller to back normal, but the start button will no reactions.
I have met these things in the game named《天穗之咲稻姬》《血污:夜之仪式》or more.
My phone is OPPO find x2 Pro，moonlight version is 9.7.7.
thanks for your software, it's changed my spare time.

Xbox one controller can't vibrate.DS4 controller can vibrate. 
off auto detecte controller  can solve the problem that start button no reactions, but DS4 controller still out of control occasional.

**Comment by lyndonguitar** [comment]
Same thing is happening to me

Controller: Dualshock 4 Controller through bluetooth
Clients: Both Android 10 Samsung S9+ and Android 11 Samsung Galaxy Tab S6
Server: PC WIndows 10 (RTX 3070)

**Comment by mkaflowski** [comment]
Same here. One plus 6 and ds4 v2. It disconnects when vibrations works. After restarting ds4 it works but vibrations are off. Is there any way to turn vibrations off?

**Comment by mkaflowski** [comment]
I think it is vibrations fault because it stopped disconnecting when I turn off vibrations in game. Is there any way to turn off vibrations for controller in app?

**Comment by lyndonguitar** [comment]
Sad to say but, I still have the same issue when using DS4. it disconnects after a few minutes especially when theres heavy vibrations. One workaround is to disable vibration but moonlight doesn't seem to have that option and Steam's controller settings doesnt seem to work.

**Comment by YABIJIU** [comment]
Android have xinput.dll , so controller can vibrate when use usb cable to link.&nbsp;
now I bought a Bluetooth connection made by 8bitdo, it can link controller wireless,and the vibration is perfect. only 89 Chinese yuan . link the Android phone, you need a typeC-usb cable.













---Original---
From: ***@***.***&gt;
Date: Sun, Mar 28, 2021 11:03 AM
To: ***@***.***&gt;;
Cc: "YABIJIU"<706477720@***@***.***&gt;;
Subject: Re: [moonlight-stream/moonlight-android] DS4 always  out of control in Android (#908)




 
Sad to say but, I still have the same issue when using DS4. it disconnects after a few minutes especially when theres heavy vibrations. One workaround is to disable vibration but moonlight doesn't seem to have that option and Steam's controller settings doesnt seem to work.
