### ISSUE TITLE
CEMU won't close anymore

### ISSUE THREAD

**Issue by Gassgs** [moonlight-stream/moonlight-android#911]
Not a huge deal. But I used to be able to close a game running in CEMU.  It longer does that. It says it sucessfully quit. But when I go back to the computer the game is still running.

**Comment by Gassgs** [comment]
Is it possible to fix this issue?

**Comment by Gassgs** [comment]
Not an easy fix? it used to work

**Comment by cgutman** [comment]
It’s not possible for us to fix. It broke in a GFE update when Nvidia changed the behavior of application lifetime tracking for manually added apps.

**Comment by Gassgs** [comment]
Got it, Thanks for the information!
