### ISSUE TITLE
Gamepads default to Xbox 360. If Possible allow for manual gamepad control selection.

### ISSUE THREAD

**Issue by Concenaros** [moonlight-stream/moonlight-android#912]
Hello,

I recently had a huge issue attempting to figure out how to get moonlight to work properly with my Retroid Pocket 2. 

When attempting to use Moonlight via the android app, the gamepad within the RP2 defaults to an Xbox360 controller with a combined axis. Apparently this was fixed with the inclusion of Xinput/Direct input for Xbox One, but X360 controllers don't have this...meaning that the Right Stick and Triggers share a single Z axis...which is incompatible for mapping on this device. 

I've tried a similar method of streaming to the device with Steam Link and noticed it gives you he option to remap your detected controller within the app before connecting to your Desktop/PC for streaming. 

Having an option like this within the Android App would allow me to properly map each button before connecting to my PC, and would also allow for proper axis implementation since I'd be able to change the controller option to something other the default mapping of a X360 controller. If full remap isn't possible, being able to select either the X360/XOne controller as an option in settings to set a default would probably suffice.

**Comment by cgutman** [comment]
XInput itself was designed for Xbox 360 controllers. This was 7 years before Xbox One controllers even existed, so the idea that XInput only works on Xbox One is simply not true.

What are you using to test on PC that only shows a single Z axis for triggers?

You can see yourself that the controllers that GeForce Experience emulates are fully capable of distinguishing trigger axes by streaming https://html5gamepad.com

**Comment by Concenaros** [comment]
Sorry, I'm not 100% privy on Xinput/Direct, seemed the likely culprit from everything I had read into the issue. 

I'm just looking at the X360 controller properties on Win10. When you first start using Moonlight, the L and R triggers work as intended. But the second I touch the Right stick, it nulls out the Trigger input and will then only use the input assigned to the right stick, which is the erroneous L and R trigger. This only occurs when using Moonlight. Due to the fact that it auto-detects the gamepad as a X360 controller. 

When testing with Steam Link, it allows me to fully remap/assign controls to the gamepad, which default appears as a PS3 controller. The Right stick maps correctly and the Trigger function independently as well.

When doing initial testing on device with gamepad tester, all of the button inputs and codes seem correct and the Right stick axis is correct as well, showing Z and RZ values when it's interacted with.

**Comment by cgutman** [comment]
If you're talking about joy.cpl, you should not use that for checking gamepads. It is a legacy utility stuck with DInput that hasn't been updated for years. You see the unified trigger axis because joy.cpl was never updated to support XInput.

DInput has been deprecated for gamepads for over 10 years (and isn't even available in UWP at all), so checking DInput compatibility doesn't tell you anything about how it will behave in an actual game. You need to try a real game or modern app that implements XInput (like Chrome, Steam Big Picture, or [SDL Gamepad Tool](https://generalarcade.com/gamepadtool/)).

**Comment by Concenaros** [comment]
Sorry, I've just been trying to see wherever I can update/change this weird controller mapping, but I have used the on-device gamepad tester since this is essentially a modified phone with an attached gamepad. 

I have proper keymaps and scancodes from that [Gamepad Tester](https://play.google.com/store/apps/details?id=ru.elron.gamepadtester) and it's reliable.

Everything is detected properly while using that app but when attempting to use the SDL Gamepad Tool while streaming with Moonlight, my R2 and L2 triggers aren't detected and my D-pad doesn't work... tried a few attempts at remapping but no luck.

I've also tried remapping inside of Steam Big Picture. I've successfully been able to do this when using Steam Link directly. Was able to map the gamepad to work for Destiny 2 and Assassin's Creed: Origins. 

It just seems defaults to this weird config when I use Moonlight for some reason.

**Comment by cgutman** [comment]
Do the full set of gamepad controls work when you use the on-screen controls in Moonlight?

**Comment by Concenaros** [comment]
Yes actually. 

I just tested it out with the 'touchscreen/onscreen' controls in touch mode and they work totally fine...

Is there a way to disable touch controls completely within Moonlight? I wonder if it's somehow getting confused between the touchscreen and gamepad.

I'd need to disable the 'touchscreen' since I can't actually use it as a normal touch screen. It's virtual/emulated touch.
