### ISSUE TITLE
Xiaomi Mi Box S

### ISSUE THREAD

**Issue by bodyscape** [moonlight-stream/moonlight-android#914]
Hi,

The box have the Amlogic S905X SoC who support
Video decoding
4Kp60 10-bit H.265
4Kp60 VP9 Profile2 4Kp30 H.264

https://en.wikipedia.org/wiki/Amlogic

I don't know why but i'm stuck to 22ms of decoding time. So about 45 FPS.

Weird because the rendering frame rate is 60 FPS.

![image](https://user-images.githubusercontent.com/30115568/103449471-b915d600-4c76-11eb-8646-058734f30a6d.png)

**Comment by cgutman** [comment]
The decoder is pipelined (more than one frame is processed at a time) so the 22 ms decode time doesn’t mean you’re only getting 45 FPS. The FPS values reported in the overlay are accurate.

The Amlogic decoder is just higher latency than Qualcomm and Samsung. There’s nothing we can do about that.

**Comment by bodyscape** [comment]
Thx for the quick response, so it's normal it doesn't feel like a 60 FPS?

Because on my laptop and my phone work great, clearly 60 FPS

**Comment by cgutman** [comment]
It could be a lot of things. If you're feeling high latency, it could be your TV (check that it's in game mode) or just the extra decoder latency. If it feels choppy, you could try the "Never drop frames" option in settings (though it may make the latency worse).

If you need further help, you should try [our Discord server](https://moonlight-stream.org/discord) which has many more people that can help.
