### ISSUE TITLE
Feature request: use phone gyroscope as mouse.

### ISSUE THREAD

**Issue by delmarlin** [moonlight-stream/moonlight-android#922]
It would be great to have the option to use the phone gyroscope to controll the mouse on the remote PC.
Thanks!

**Comment by iron0rca** [comment]
Just like many mobile fps games, it will greatly improve the aiming experience for those who are not good at using the gamepad.

**Comment by lucasicf** [comment]
I'd really really like this too

**Comment by iron0rca** [comment]
I found that steam link can use phone gyroscope to aim in CSGO, but it is hard to use.
[https://steamcommunity.com/app/353380/discussions/4/1630790987599121171/](url)

**Comment by iron0rca** [comment]
I found that steam link can use phone gyroscope to aim in CSGO, but it is hard to use.
[https://steamcommunity.com/app/353380/discussions/4/1630790987599121171/](https://steamcommunity.com/app/353380/discussions/4/1630790987599121171/)

**Comment by TraceshadowArasa** [comment]
Really hope that phone gyroscope can be indentied as input device!
