### ISSUE TITLE
All gamepad input blocked by Moonlight Android

### ISSUE THREAD

**Issue by WreckWren** [moonlight-stream/moonlight-android#926]
**Describe the bug**
When connecting to any PC from Moonlight Android client, no gamepad button events are sent to host PC.

**Steps to reproduce**
Connect to host PC and attempt to play game with any gamepad. Razer Junglecat & Xbox One controller tested, same results.

**Screenshots**
N/A

**Affected games**
All.

**Other Moonlight clients**
N/A

**Moonlight settings (please complete the following information)**
- Have any settings been adjusted from defaults? =No combination of settings seems to allow gamepad events to be sent to host.
- If so, which settings have been changed? =See above.
- Does the problem still occur after reverting settings back to default? =Yes.

**Client PC details (please complete the following information)**
N/A
Samsung Galaxy S10+, up-to-date.

**Server PC details (please complete the following information)**
 - OS: Windows 10 18363
 - GeForce Experience version: 3.20.5.70
 - Nvidia GPU driver: 460.89

**Moonlight Logs (please attach)**
N/A - Android

**Additional context**
Steam Link app works perfectly - this issue is isolated to the Moonlight Android client. The Moonlight client detects gamepad inputs itself, but will not pass them to the host. On-screen controls are similarly unusable.

EDIT: Apologies, posted under wrong client. Don't know how to move the thread.

**Comment by cgutman** [comment]
It's likely this bug if you're on Android 11 - https://issuetracker.google.com/issues/163120692

Turn off all Accessibility features and it should work again.

**Comment by WreckWren** [comment]
I am on Android 10. Stock ROM.

**Comment by cgutman** [comment]
Do the on-screen controls work?

**Comment by WreckWren** [comment]
Sadly no, as mentioned in OP. Have tried https://gamepad-tester.com/ as well to no avail.

**Comment by WreckWren** [comment]
Additional info:
Have tried several factory resets with no positive result.
Will try rooting device.

**Comment by WreckWren** [comment]
Update:
No luck rooting on either S10 or S7.
Tried MacOS client as well, also no inputs passed to any host exclusively in Moonlight - alternatives work fine.

**Comment by cgutman** [comment]
This sounds like a host-side problem. You probably need to do a clean reinstall of GeForce Experience or something. You should ask for help on the [Discord server](https://moonlight-stream.org/discord).

**Comment by WreckWren** [comment]
> 
> 
> This sounds like a host-side problem. You probably need to do a clean reinstall of GeForce Experience or something. You should ask for help on the [Discord server](https://moonlight-stream.org/discord).

Been down that road as mentioned here:
> 
> Update:
> No luck with rooted S10 or S7.
> Tried MacOS client as well, also no inputs passed to any host exclusively in Moonlight - alternatives work fine.
> It appears to be a host-side issue, but I have tried multiple PCs including a VM with a clean install, all with the same results.

**Comment by cgutman** [comment]
Well, GitHub is not an appropriate medium for troubleshooting issues specific to host-side problems. I can only handle bugs in Moonlight, not issues with GeForce Experience. Although we obviously can't support Nvidia's software for them, there are folks on the Discord that may be able to offer help.

If this were broken in Moonlight itself (or a general incompatibility with GFE or something), there would be many users complaining and that would be appropriate for this bug tracker. That's why it has to be something specific to your setup, maybe a missing driver (Server SKUs don't ship with Xbox drivers, for example), software incompatibility (Steam's controller configurator causes problems sometimes), etc.

In any case, good luck.

**Comment by WreckWren** [comment]
There are multiple people complaining about this on the Discord. Maybe you should read it instead of me?
