### ISSUE TITLE
Lag since Windows 10. Windows 8.1 worked fine.

### ISSUE THREAD

**Issue by btastic** [moonlight-stream/moonlight-android#93]
Hey guys,

awesome app! However, since I upgraded to Windows 10 the stream is lagging. It worked fine on Windows 8.1. I reinstalled drivers, updated everything but it is still lagging every few seconds.  The game runs fine on the computer display.

Thanks in advance

**Comment by scoobyd00** [comment]
Same problem with the raspberry pi build.
The video lags and is unplayable.
Works fine in 8.1 with all the latest drivers but windows 10 breaks the video stream

**Comment by halfluck** [comment]
I'm not seeing that issue here at all no difference in lag, Windows 10 Pro 64x

**Comment by btastic** [comment]
Using Windows 10 Pro 64 aswell. Upgraded it, no clean install.

System specs:
CPU: AMD FX-8320 Vishera
RAM: 2x 4GB DDR3 1333 GSkill
Mainboard: GIGABYTE GA-78LMT-USB3
Graphics Card: NVIDIA GeForce GTX 970

Could it maybe be something about the ethernet Adapter drivers? Glad to See I am not the only one atleast.

**Comment by SovietMarmotte** [comment]
Same problem here since Windows 10.
Tested on two Android devices
With my Shield and official Gamestream all is working fine.

Lags are only with Moonlight. Windows 8.1 worked fine

**Comment by cgutman** [comment]
This is an Ethernet adapter issue. It looks like there's some periodic packet drops with the driver bundled in Win10 for some Ethernet cards. Official GameStream's error correction makes it continue to work well even when the NIC is dropping packets.
