### ISSUE TITLE
Multiplayer

### ISSUE THREAD

**Issue by ReenigneArcher** [moonlight-stream/moonlight-android#931]
Is multiplayer possible?

I tried connecting two xbox one  bluetooth controllers to Nvidia Shield and game streaming to my PC. It appears as the PC sees both pads as the same controller.

Is there an option to adjust this or it's a limitation of GFE?

**Comment by cgutman** [comment]
Multiple controllers are supported (up to 4). Make sure you enable "Automatic controller gamepad presence detection" in Moonlight.
