### ISSUE TITLE
USB controller vibration no longer working

### ISSUE THREAD

**Issue by coopermf** [moonlight-stream/moonlight-android#933]
I used to be able to connect my controllers via usb to my nvidia shield and my android phone and they would get vibration/rumble support but I noticed that now neither my wired xbox 360 controller nor any of my wireless controllers connected to my 8bitdo usb adapter are vibrating when connected to moonlight. Connected to Steam Link they will vibrate so I'm pretty sure this is moonlight's problem not android's.

**Comment by cgutman** [comment]
Try rebooting your host PC. Sometimes the virtual controller on the PC will get into a bad state where rumble doesn’t work again until you reboot.

**Comment by coopermf** [comment]
You're right, rebooting seems to bring it back. Though I have never noticed this problem before and now it seems like I need to have just rebooted my pc for rumble support, it appears way more frequent than I've ever noticed before. Thanks for the help, I wonder if something about my set up is causing issues with the virtual controller? Are there any known compatibility issues with 8bitdo adapter and DualSense controller or maybe with DS4Windows?

**Comment by cgutman** [comment]
Are you forcefully terminating the nvstreamer.exe process? That consistently breaks rumble for me.

**Comment by coopermf** [comment]
Hm, I've been using GameStream Launchpad (https://github.com/cgarst/gamestream_launchpad) with Playnite. Maybe that does it?

**Comment by cgutman** [comment]
Aha, indeed it does right here - https://github.com/cgarst/gamestream_launchpad/blob/master/gamestream_launchpad.py#L192

**Comment by coopermf** [comment]
Got it, that must be the root of the issue. Thanks for sorting that out.

**Comment by igno2k** [comment]
Is there any way to gracefully close nvstreamer.exe? Maybe just leaving out the force ("/f") option?

**Comment by ERamseth** [comment]
No vibration for me on Nvidia Shield with shield controller connected wirelessly to shield tv.

Tried reboot and even on first moonlight session (so first launch of steam and shouldn't have been any force closes of nvstreamer.exe) there is no vibration / rumble.
