### ISSUE TITLE
H.265 compatibility 

### ISSUE THREAD

**Issue by bpvarsity** [moonlight-stream/moonlight-android#935]
I have this chromebook
Samsung - Galaxy 13.3" 4K Ultra HD Touch-Screen Chromebook - Intel Core i5 - 8GB Memory - 256GB SSD - Fiesta Red
Model:XE930QCA-K01US

It has an i5-10210U cpu and Intel UHD Graphics. From what I have read it can do H.265 but when using the android moonlight app it still uses H.264 even when I try to force it.

Is there anything preventing me from using this or will it be supported in the future?

Thanks

**Comment by cgutman** [comment]
Moonlight itself fully supports H.265 on Android devices. The problem on ChromeOS is that the Android Runtime for Chrome doesn’t expose H.265 decoders. That’s not something we’re able to fix, unfortunately.
