### ISSUE TITLE
Sound crackling/choppy when streaming (intermittent, so not always)

### ISSUE THREAD

**Issue by ap3nr0ts** [moonlight-stream/moonlight-android#938]
Hi!

I already talked about this on the #android-help channel of the Discord, but I haven't figured anything out yet. No matter which version of GFE I use, which version of Moonlight (got some old custom builds before device resolutions were standard), I always have some form of crackling or choppiness at times, even though the stream is absolutely beautiful and without any stuttering graphics-wise. The people in the Discord also said it's a weird issue some people have come across recently.

So, let's find a solution together?

**Comment by sheldonl3** [comment]
I have the same problem when using 4G network ,the graphics is great but sound is crackling

**Comment by dazzlejacket** [comment]
I'm in the same boat - was using the latest version of GeForce Experience streamed to the app running on Android 10. Joined the Moonlight beta on Play Store and downgrade GeForce to v3.20.2.63 which worked for a few minutes until the issue came back with a vengeance. Video-wise everything is superb but the audio crackles no matter what I do. I've tried on my home network and outside to see if that fixes things but I have the same results.

**Comment by ap3nr0ts** [comment]
Yep. The video is superb here as well, way better than Steam Link. But no matter which GFE version I use, the audio issue persists.

**Comment by flamepro** [comment]
Same issue here. Super frustrating! Turns an otherwise flawless experience into a soured one. Playing Jedi Fallen Order and it really ruins the immersion :(

**Comment by ap3nr0ts** [comment]
What is your setup? I might try it out on my laptop later, with and without wired. But since I'm on 5GHz and Steam Link goes up to 105Mbps, I'm fairly sure connection isn't it here. I was chatting with another guy, and we kinda think it must be something with the driver or PC-side of things. So hard to troubleshoot, however.

**Comment by flamepro** [comment]
I found an old thread which suggested running LatencyMon. I did this while streaming my game and found I'm getting very high latency from NVIDIA Windows Kernel Mode Driver (1255 µs). I'll have to test it under normal conditions or streaming less demanding games and see what that yields.

My setup is: RTX 3080, AC wi-fi, running Moonlight @4k60.

Wish I could test over ethernet, but bandwidth really doesn't seem to be the issue here.

**Comment by ap3nr0ts** [comment]
My highs are around that as well. Does that tell us anything? If I understand that tool correctly, this should also give me sound issues when not streaming, and that has never been the case.

I've caved on this issue: just bought a 10m USB cable that seems trustworthy enough, and I'll just use a bluetooth headset directly connected to my PC. A bit of a hassle, but better than this crackling.

**Comment by cgutman** [comment]
This should be fixed in Moonlight Android v9.9.5 by the addition of audio FEC support, as long as you are running GeForce Experience 3.19 or later.

**Comment by bennylaws** [comment]
I had annoying sound crackling too until I activated "system equalizer support" in Moonlight's settings (right below the Stereo/5.1/7.1 setting) on my Android device - now it's back to perfect.

Not sure whether or not I did switch it off myself or if it's off by default, but after activating, no crackling/stuttering anymore 👍

**Comment by AnakinShieh** [comment]
Same issues on the latest Mac version of moonlight, and there is no "system equalizer support" option in the mac when connecting to a windows desktop in the same local network.

**Comment by udllpn** [comment]
I am having the same problem described above, but I have not been able to fix it. Enabling "system equalizer support" seems to mitigate the issue sometimes, but it does not go away.

I have tried everything possible in two current phones and tables. I have no issue when streaming to my Chromecast. I am using the v. 11 of the App from the Play Store.

**Comment by normanu** [comment]
I think this is the same as why my 5.1 surround goes to 2.0 after a while and then sometimes bqck to surround.
Read somewhere this might be a buffer issue?

**Comment by normanu** [comment]
> Same issue here, 4G or wifi, doesn't matter.And I think the solution is with setting MTU slightly down, from 1500. And I think to 1492 or something. Because I had issue, and got it fixed, but reinstalled everything, and problem came back..

If you ever find the solution again, I'm very very interested to know the solution :)

**Comment by normanu** [comment]
Tried streaming to another laptop yesterday.
The streaming was actually smoother on the chromecast.
But the laptop did not suffer from the surround audio drops.
So it is something in the android client, not in the host.

**Comment by stefanw1337** [comment]
Ok, so the change I made with MTU nearly worked. It helped alot for me, but now, occasionally, it still happens. Would like a final fix. But it's good enough for me.

**Comment by normanu** [comment]
So your only changing the MTU on the host?
not on the client?

**Comment by stefanw1337** [comment]
Yes, as I don't know how t change it on android. Also I have another issue, everything hard freeze, but I still have sound, I have to reconnect it quick to fix. A problem that can mean life or death in games like Diablo. But never had the issue when playing, just when afking or watching streams.

-Stefan
________________________________

**Comment by LividLiquid** [comment]
C:/> netsh interface ipv4 set subinterface "Ethernet" mtu=1280

Was having this same problem streaming from Windows to Ubuntu. Was fine before a recent update, which broke it, but this fixed the problem entirely. Sounds great now. Thank you.

**Comment by normanu** [comment]
So you do this on the host?

Op za 23 sep. 2023 07:56 schreef LividLiquid ***@***.***>:

**Comment by LividLiquid** [comment]
Correct. I ran said command on the Windows host PC that runs Sunshine.

**Comment by normanu** [comment]
Mm doesn't solve my surround issue.

Op za 23 sep. 2023 08:48 schreef LividLiquid ***@***.***>:

**Comment by normanu** [comment]
Unfortunately does not solve it for me

Op za 23 sep 2023 om 08:48 schreef LividLiquid ***@***.***>:

**Comment by LividLiquid** [comment]
Aw, drag. I'm sorry. I hope you find your answer.

**Comment by Originalimoc** [comment]
Mine working very well for a long time. Latest Google Play release. Post your Setup(Network(WiFi/Router quality)/PC configuration(Bare metal? VM? One GPU? Two GPU? What model?)/Phone model). Lots can go wrong if any does not meet requirement. Have you tried use Sunshine as host tool instead of Game Experience?

**Comment by normanu** [comment]
@Originalimoc I'm playing as a client on a Chromecast Ultra, through Wifi 6 but also tried LAN.
Host is a bare metal Ryzen 3600 with RTX3080.
The issue I am having is that my Chromecast outputs surround sound to my amplifier.
And it keeps going from 7.1 to 2.0CH and back again in periods.
When I changed the MTU to 1280 it became actually much worse, so it does seem to be the same issue with packets not arriving at the correct time or something.

Decode latency is between 12 and 18ms

**Comment by pawelwalat** [comment]
Found to have same issue. 
My setup is:
proxmox with GPU passthrough to w11. I have sunshine on it, streaming to mac with moonlight (same on iphone client, I will try Windows one).
Also, I fried Experience - same issue.
MTU changing on windows doesn't help. Will also try to change MTU on the proxmox host.

**Comment by kentyman23** [comment]
My Fire TV Stick 4K Max 1st Gen (2021) has a lot of static/crackling/popping noises, too.

**Comment by chu-bin** [comment]
I solved this problem by increasing the bitrate, e.g. the default bitrate is 50mbps and when I increase it to 70mbps the popping noises is gone.

**Comment by slovenec88** [comment]
On windows this helped me

running in admin cmd netsh wlan set autoconfig enabled=no interface="Wi-Fi"
interface name is equal to the one in network & internet

I've read it disables scanning of the network etc, not sure how would you run something like this on unrooted android

**Comment by belanyibalazs** [comment]
I had the same problem.
After hours of debugging and a lot of trial and error, I finally found a solution that worked for me. In my last desperate attempt at 3:30 AM, I restarted the Wi-Fi router, and believe it or not, it worked! I can't believe that’s all it took...

I simply use Gamestream and Moonlight.

Solution: Just try to restart your Wi-Fi router!
