### ISSUE TITLE
about desktop more 30fps and double click

### ISSUE THREAD

**Issue by navlgator1** [moonlight-stream/moonlight-android#939]
Hi! I have a few problems with moonlight.
1. Is it possible to run a desktop (mstsc.exe) broadcast at more than 30 fps?
2. Does not work the double-click of the mouse during the broadcast. Files and folders cannot be opened.
Is there a fix?

**Comment by cgutman** [comment]
1. Yes, but you're probably hitting the Optimus bug in GameStream detailed on our [FAQ page](https://github.com/moonlight-stream/moonlight-docs/wiki/Frequently-Asked-Questions#why-is-my-frame-rate-low-when-streaming-my-desktop-on-a-laptop-with-nvidia-optimus). For Optimus laptops, it is not always possible to stream at a high frame rate when not using a full-screen application on the dGPU.

2. I've seen this behavior too on an old installation of Windows on an XPS 15 9570, however it didn't reproduce on a newer fresh installation on the same system. It's probably something to do with the older version of Windows or some installed software, but I never did get to the bottom of it. It only impacted that single installation, and I never saw it again after that.

**Comment by navlgator1** [comment]
Thanks for answer. Really my problems because i have laptop. On PC it is ok!

**Comment by gorfou** [comment]
>     2. I've seen this behavior too on an old installation of Windows 10 1803 on an XPS 15 9570, however it didn't reproduce on a newer fresh installation on the same system. It's probably something to do with the older version of Windows or some installed software, but I never did get to the bottom of it. It only impacted that single installation, and I never saw it again after that.

Searching for why double-clicking is not working and you name my PC almost spot-on.  I use Windows 10 Pro 19044.2130 on a Dell XPS 15 9570.  For those plague with the same issue, you can mitigate with selecting the item and then pressing enter, use Right-Click menu, use window maximize and minimize buttons, etc...

I really wish this would work though. It is really messing the workflow.

**Comment by emoritzx** [comment]
I ran into this as well. My host computer is stuck on Windows 10 because it is too old to upgrade to 11. I have been using the right-click menu as a workaround for everything.
