### ISSUE TITLE
1440p Resolution Broken on MacOS

### ISSUE THREAD

**Issue by BigBoiJeff** [moonlight-stream/moonlight-android#942]
I am running moonlight on a 24 inch 2012 iMac, and for some reason when I try to stream Steam at 1440p, steam and all of my games will be stuck at 720p.
![16138823692086444868903837320246](https://user-images.githubusercontent.com/77512695/108615722-895c9200-73cc-11eb-9b64-bf3c6e94be9e.jpg)
![16138824003794679374178220782852](https://user-images.githubusercontent.com/77512695/108615735-b446e600-73cc-11eb-9b60-2af3f489a1e6.jpg)

**Comment by cgutman** [comment]
We've got an answer to this on our FAQ page - https://github.com/moonlight-stream/moonlight-docs/wiki/Frequently-Asked-Questions#why-does-my-host-pc-resolution-change-to-720p-when-i-start-streaming

BTW, this is the Android bug tracker. For the PC client, [moonlight-qt](https://github.com/moonlight-stream/moonlight-qt) is the right repo for that.
