### ISSUE TITLE
Missing HDR on Samsung Galaxy Tab s5e

### ISSUE THREAD

**Issue by diogosena** [moonlight-stream/moonlight-android#946]
On the Samsung Galaxy Tab s5e the "Enable HDR (Experimental)" option is missing, there's any way to force it?

The tablet has problems (washed out colors) in HDR in many apps like VLC, but MPV-Android ( https://github.com/mpv-android ) have HDR working as it should, and hw dedoded. Maybe it's related.

**Comment by cgutman** [comment]
Is it HEVC Main10 or some other codec like VP9?

**Comment by diogosena** [comment]
Yes, HEVC in an mkv container, if you point me to a sample file i can test for you.
