### ISSUE TITLE
Feature Request: Dragging via tap-and-drag

### ISSUE THREAD

**Issue by haarp** [moonlight-stream/moonlight-android#950]
Hello,

the app is currently missing the ability to do drag movements in trackpad mod. This is not only needed in some games, but also to use any sort of "normal" Windows UI. Think resizing/moving windows, drag'n'dropping files, text selection, etc.

The usual way of doing this on actual trackpads is the [Tap-and-drag](https://wayland.freedesktop.org/libinput/doc/latest/tapping.html#tap-and-drag) movement. Perform a double-tap, but keep the finger pressed after the second tap. Now dragging is possible.

It would be awesome if the app could implement this function, to make working with Windows **a lot** easier.

Thanks!

**Comment by cgutman** [comment]
This is supported via tap and hold, then drag.
