### ISSUE TITLE
Have triple tap also close keyboard

### ISSUE THREAD

**Issue by haarp** [moonlight-stream/moonlight-android#951]
Currently a triple tap opens the keyboard, which is useful. But getting rid of it again is not so easy, as it requires using the system's back button. Especially annoying if you have fullscreen and/or gesture navigation enabled.

Why doesn't a simple triple-tap close the keyboard again? Should be the easiest solution to this problem :)

Cheers!

**Comment by cgutman** [comment]
There is actually not an Android API to detect if the keyboard is being displayed. While we could toggle show/hide, we can become out of sync with the actual state of the keyboard.

Dianne Hackborn of the Android Framework team has responded to a similar question here - https://groups.google.com/g/android-platform/c/FyjybyM0wGA

**Comment by haarp** [comment]
Not stale. [stale bot is](https://blog.benwinding.com/github-stale-bots/) [terrible](https://news.ycombinator.com/item?id=25821092)

**Comment by cgutman** [comment]
Closing this as won't fix due to the issue I mentioned above.
