### ISSUE TITLE
on screen Keyboard with uppercase letter does not work anymore

### ISSUE THREAD

**Issue by apierre55000** [moonlight-stream/moonlight-android#952]
hello !
when i use many fingers to appears on screen keyboard, the uppercase doesn't work anymore 
even if i try multiple keyboards (french, english, us etc...)
but in older versions this feature worked.
could you make anything please ^^
thank you !

**Comment by cgutman** [comment]
Thanks for the report. Fixed in 5843dff2788895ab16ba1a8e752de5be7d6c2350 and 7f24f4797824ead3212a6964f7c685205cc5ea6f.

I will release a new version shortly.
