### ISSUE TITLE
DPC_WATCHDOG_VIOLATION BSOD when using Moonlight

### ISSUE THREAD

**Issue by Nesreteip** [moonlight-stream/moonlight-android#958]
**Describe the bug**
Everytime I open Moonlight and connect to my pc, after 1 minute, my pc freezes and goes into a BSOD with code DPC_WATCHDOG_VIOLATION. This is only happening when using Moonlight for 1 minute. The device I connect with (android, macos, another windows machine) doesn't matter. It happens with all Moonlight versions.

**Steps to reproduce**
I cannot think of one. I'd be able to fix my issue if I knew...

**Screenshots**
I can't take screenshots of BSOD or when my pc freezes.

**Affected games**
Every app I open. I tried opening tskmgr.exe, GTA V, Skyrim, Terraria. Nothing seemed to help.

**Other Moonlight clients**
All clients I've tried: Windows, Android, Macos. All three had the same issue

**Moonlight settings (please complete the following information)**
Tried everything with all settings on default. I even tried setting my BIOS settings to default, alas with no good result.

**Device details (please complete the following information)**
 - Android 10 on OnePlus 7 Pro
 - Macbook pro 13" with Macos 10.15.7

**Server PC details (please complete the following information)**
 - OS: Windows 10 19041.867
 - GeForce Experience version: 3.21.0.36
 - Nvidia GPU driver: 461.92
 - Antivirus and firewall software: Avast

**Additional context**
If you need to know something else, let me know

**Comment by cgutman** [comment]
A DPC_WATCHDOG_VIOLATION error is usually indicative of a buggy driver on your host PC.

Since your GPU driver is up to date, the next place to check is your network adapter driver. Try updating that to the latest version from the NIC manufacturer's website. 

Is your PC overclocked? That can also cause instability.

**Comment by Nesreteip** [comment]
On the blue screen there is no driver listed. The only info I get is the error code (DPC_WATCHDOG_VIOLATION).

After reading your comment, I updated all of my drivers (of all devices listed in device manager), but without result.. Is there something else I can try?

**Comment by cgutman** [comment]
Try updating your GeForce driver to 465.89.

In the [465.89 changelog](https://us.download.nvidia.com/Windows/465.89/465.89-win10-win8-win7-release-notes.pdf), one of the fixes says:
> Blue-screen crash (DPC_WATCHDOGS_VIOLATION) occurs when playing a game and watching YouTube video simultaneously. [3196272]

**Comment by Nesreteip** [comment]
I will try updating my driver today when I get home. I'll let you know the details afterwards.

**Comment by Nesreteip** [comment]
Forgot to mention that updating my drivers didn't result in anything.. I'm starting to think this is an issue with my Windows. I might have to reinstall Windows in order to fix this issue :/
