### ISSUE TITLE
Dolby Digital 5.1 Support Amazon Fire TV

### ISSUE THREAD

**Issue by M-Whitaker** [moonlight-stream/moonlight-android#961]
**Is your feature request related to a problem? Please describe.**
I am trying to get 5.1 Surround sound working on a Amazon Fire TV Stick 4K. If you didn't already know from my research the only 5.1/7.1 surround sound you can get out of a Fire TV is Dolby Digital (AC3), Dolby Digital Plus (EAC3), and Dolby Atmos (atmos). At current this application does not output this (With 5.1 checked in the application settings). And this does work for other media I have encoded with AC3 & of course Netflix, Prime Video, Disney+ etc.

**Describe the solution you'd like**
I believe the reason for this is that you have to implement Dolby Digital in a certain way (or use a certain media player which I assume does not apply here) using this documentation: https://developer.amazon.com/docs/fire-tv/dolby-integration-guidelines.html. I have to confess that I have only skimmed the code to find what I think is the implementation you have for surround sound using the AndroidAudioRenderer class which seems to have no mention to Dolby Digital from my first look.

**Additional context**
I understand that audio codecs are very finicky to implement at the best of times never mind having to deal with game stream and amazons opinion on the matter too. I am wondering if such a feature for the Amazon Fire TV is on the roadmap and if this can be implemented.

**Comment by joitronix** [comment]
I cant get work amazon fire stick tv the screen keep black when y launch the game i can hear it but not see it you do aniting special?

**Comment by M-Whitaker** [comment]
I think you have a separate issue with the GPU not rendering when it is not plugged in.

See https://github.com/moonlight-stream/moonlight-docs/wiki/Troubleshooting#no-video-black-screen

**Comment by toutrob** [comment]
I have exactly the same problem with my TCL C71 TV which according to my research and testing only supports EAC3 for 5.1 on Android TV.
It would be nice to find a solution for these devices ?

**Comment by M-Whitaker** [comment]
Yeah, I did a bit of research myself on this and it seems that encoding PCM 6 Channel to AC3/EAC3 is quite an expensive task both computationally and for the license. The only way I see this happening is with an API in android that supports encoding 😞
