### ISSUE TITLE
 GeForce Experience Beta 3.22.0.28 breaks streaming with error 500

### ISSUE THREAD

**Issue by YABIJIU** [moonlight-stream/moonlight-android#962]
I can connect PC, can boost game ,but cannot steam.

**Comment by YABIJIU** [comment]
![Screenshot_2021-04-08-06-19-15-57_0ff5f4589442642967c97622a25eb61e](https://user-images.githubusercontent.com/62825205/113968375-8840d080-9865-11eb-8be4-1ed20de352c9.jpg)

**Comment by cgutman** [comment]
We're aware of the issue and working on a fix. Nvidia made some change to the core protocol that broke Moonlight.

For now, you can downgrade from the GFE 3.22 Beta back to the official release of GFE 3.21 by uninstalling and reinstalling from Nvidia's website https://www.nvidia.com/en-us/geforce/geforce-experience/

**Comment by YABIJIU** [comment]
I have alresdy back to 3.21.but it update automatically, i stop it and i cannot start fge now.



---Original---
From: "Cameron ***@***.***&gt;
Date: Thu, Apr 8, 2021 20:48 PM
To: ***@***.***&gt;;
Cc: "YABIJIU"<706477720@***@***.***&gt;;
Subject: Re: [moonlight-stream/moonlight-android]  GeForce Experience Beta 3.22.0.28 breaks streaming with error 500 (#962)




 
We're aware of the issue and working on a fix. Nvidia made some change to the core protocol that broke Moonlight.
 
For now, you can downgrade from the GFE 3.22 Beta back to the official release of GFE 3.21 by uninstalling and reinstalling from Nvidia's website https://www.nvidia.com/en-us/geforce/geforce-experience/

**Comment by cgutman** [comment]
Uncheck the "Enable experimental features" checkbox and it won't update to the Beta.

**Comment by YABIJIU** [comment]
ok, Thank u my friend



---Original---
From: "Cameron ***@***.***&gt;
Date: Thu, Apr 8, 2021 21:03 PM
To: ***@***.***&gt;;
Cc: "YABIJIU"<706477720@***@***.***&gt;;
Subject: Re: [moonlight-stream/moonlight-android]  GeForce Experience Beta 3.22.0.28 breaks streaming with error 500 (#962)




 
Uncheck the "Enable experimental features" checkbox and it won't update to the Beta.

**Comment by cgutman** [comment]
Fixed in Moonlight Android v9.8.6. It should be on the Play Store soon, or you can download from the releases page: https://github.com/moonlight-stream/moonlight-android/releases

**Comment by YABIJIU** [comment]
Thank u&nbsp;





---Original---
From: "Cameron ***@***.***&gt;
Date: Sat, Apr 10, 2021 08:44 AM
To: ***@***.***&gt;;
Cc: "YABIJIU"<706477720@***@***.***&gt;;
Subject: Re: [moonlight-stream/moonlight-android]  GeForce Experience Beta 3.22.0.28 breaks streaming with error 500 (#962)




 
Fixed in Moonlight Android v9.8.6. It should be on the Play Store soon, or you can download from the releases page: https://github.com/moonlight-stream/moonlight-android/releases

**Comment by svatwork** [comment]
That's a good point, thank you for that. 

I have a headless setup, so for anyone reading this, a workaround is to use the fix with the desktop client to disable the experimental feature checkbox.
