### ISSUE TITLE
'Native resolution' incorrectly detected

### ISSUE THREAD

**Issue by EmpressFiona** [moonlight-stream/moonlight-android#967]
**Describe the bug**
On my device, the 'native resolution' is incorrectly detected as 2560x1510 (as opposed to my actual resolution of 2560x1600). Everything else works fine, although stretching from that resolution creates glitches (which I assume to not really be a bug).

**Moonlight settings (please complete the following information)**
No settings are changed; installation is entirely stock. I attempted to enable 'Expanded desktop' mode and deleted the app cache, but the incorrect detection persisted; my theory is the app thinks it has to compensate for the top and bottom toolbars, even though the app runs in fullscreen mode.

**Device details (please complete the following information)**
 - Android version: Android 5.1.1 (CyanogenMod)
 - Device model: Kobo arc 10HD, rooted

**Server PC details (please complete the following information)**
 - OS: Windows 10 Pro 21H1
 - GeForce Experience version: 3.22.0.32
 - Nvidia GPU driver: 465.89
 - Antivirus and firewall software: Windows Defender and Windows Firewall

**Additional context**
The issue can be easily worked around through modifying the settings file for Moonlight; it accepts arbitrary resolutions there. Changing that from 2560x1510 to 2560x1600 works with no issues, same as it worked for me prior to this.

I am under the impression, through previous correspondence, that you can add arbitrary resolutions to the settings as well through recompiling the program; this was added based on a previous request of mine over Discord, and a custom version was passed to me allowing for 2560x1600 and other odd resolutions - the only reason I switched to the 'stock' version was because of the GFE update making mine incompatible. I may try compiling for myself again later on, but I don't see a compelling reason to be unable to set one's own arbitrary resolution if they really want to through the program itself, especially with the warning about native resolution already.

There also seems to be some odd decoding glitches with text that weren't present previously, but I believe that's likely a GFE bug or part of the ongoing effort to support GFE 3.22, so I'm not reporting that separately.

**Comment by cgutman** [comment]
Can you run the AIDA64 app and see what it says your screen resolution is?

I'm also curious about the video glitches you've mentioned. Can you file a separate issue about those?

**Comment by EmpressFiona** [comment]
AIDA64 shows 2560x1600, as expected. So it seems like the problem is happening on Moonlight's end somewhere. Maybe it's incorrectly assuming it can't go fullscreen, perhaps due to thinking it's running a version of Android that doesn't support it or glitches with the display notch compensation?

As for the video glitches, they seem to have subsided, which is odd. I was previously experiencing glitches scaling the 2560x1510 image up to full screen, just to confirm that the app was indeed malfunctioning, but I would assume that's more a consequence of scaling up in such an odd way from 1510 to 1600 lines; these glitches are slightly different, but don't seem to be reproducible thus far. Will report if things change.

**Comment by cgutman** [comment]
The problem is that `Display.getWidth()` and `Display.getHeight()` lie to you and don't include space reserved by the system UI. Devices on Lollipop and earlier with on-screen navigation buttons would have incorrect native resolutions prior to this fix.
