### ISSUE TITLE
error -5 on LG G4

### ISSUE THREAD

**Issue by sprenghuhn1** [moonlight-stream/moonlight-android#973]
Stream from Desktop to phone was working flawlessly until last week, but not anymore. Change of res does not help. The phone is untouched since last use. Geforce Exp. and Moonlight updated to latest versions. Another phone (Samsung) is working with host.

**Comment by cgutman** [comment]
I think I fixed the issue. Please try this version and report your results: https://drive.google.com/file/d/1Hypb3DUbkb88kmd52vnUxW3tMd4vssBO/view?usp=sharing

**Comment by sprenghuhn1** [comment]
You got it. I tried several combinations of resolutions, framerates, bitrates with no problems. Thanks for helping out :)
