### ISSUE TITLE
Add support for 8bitdo SN30Pro XCloud

### ISSUE THREAD

**Issue by koshisan** [moonlight-stream/moonlight-android#978]
Hi, it's me again ;)

I skipped through the closed tickets and noticed that there were special button mappings included for some gamepads/controllers in the past.
Are we still doing that?

I recently bought the controller above as I was under the impression that it would behave exactly like an Xbox controller, since it is explicitly for streaming xcloud games on android. 

However, it isn't. Instead it seems to do something fancy to make the two additional, analog triggers work on Android and fails miserably. At least in combination with moonlight.

The right left and right triggers work as the right thumbstick and the right thumbstick causes button presses...

It is recognized as a "8BitDo SN30 Pro for Android"
Vendor 2dc8, Product 2100

The correct axis for the right thumbstick would be 0x0b for left/right and 0x0e for up/down
Left trigger would be 0x0c and right trigger would be 0x0d

All other buttons map exactly like an Xbox controller would and are working just fine as it is.

Thanks again for your help!

**Comment by cgutman** [comment]
Ok, can you try with this build? https://drive.google.com/file/d/1U8s78aKGw6R9U8mgyROB7PYDnhh5PykJ/view?usp=sharing

**Comment by koshisan** [comment]
I am terribly sorry for the extra work, but please revert the changes :(
The manufacturer released a new firmware which does swap the buttons around so they are in the correct order. I did try this before opening the ticket of course, but I did not re-pair the controller, as this wasn't mentioned in the documentation.
It seems that the changes are only activated after re-paring - which I just now and everything works as intentended with the latest release build of moonlight.

Again, sorry for causing extra trouble :(

**Comment by cgutman** [comment]
Heh, don't worry about it. Your prompt response prevented this from rolling out to any users.

If you wanted to be a real pain, you'd not respond for a week then tell me like a day after I shipped it to production that it broke everything 😆

**Comment by cgutman** [comment]
It sounds like you probably need to apply the latest firmware update to your controller and re-pair it to correct the mapping issue per https://github.com/moonlight-stream/moonlight-android/issues/978#issuecomment-833107909

No code changes to Moonlight were made because the manufacturer fixed the issue in firmware (and remapping in Moonlight would break mappings on the new firmware)

**Comment by Dasnap** [comment]
Seems you were right on the money with that one. I didn't even consider controller firmware. 8BitDo provide an updater on their site and and update + re-pair did the trick.
