### ISSUE TITLE
Low FPS but good at  delay.

### ISSUE THREAD

**Issue by BigBuge** [moonlight-stream/moonlight-android#982]
My network environment: Router: Honor router pro gaming; 5Ghz & 153 channel (Channel no blocking).
PC: Hasee Z7M-KP7GT, Wired Gigabit link, Main configuration: CPU:I7 7700HQ GPU:GTX1050TI.
Phone: Huawei Mate30 pro 5G. Upgraded by HarmoneyOS.
The software has started the 60fps setting, and the software bit rate is set at 20MBps.
![78cfe3f81a4c510f67f3a5a87759252dd52aa5dd](https://user-images.githubusercontent.com/84961707/119953741-e752d400-bfd0-11eb-963b-4eb8415b37f7.jpg)
By the way, When steam link and RD client are compared in the same direction, the frame rate of remote PC controlled by moonlight is very low. Steam link has a high frame rate, but there is a problem with the software, and the remote picture jumps; RD client has high frame rate and low latency, but it is greatly affected by network fluctuation during use. Only moonlight has the problem of low frame rate with low delay,

**Comment by cgutman** [comment]
I think you may be encountering [this issue](https://github.com/moonlight-stream/moonlight-docs/wiki/Frequently-Asked-Questions#why-is-my-frame-rate-low-when-streaming-my-desktop-on-a-laptop-with-nvidia-optimus) with NVIDIA GameStream and Optimus.

Does the problem persist in games? If so, which games have you tried?

**Comment by BigBuge** [comment]
> I think you may be encountering [this issue](https://github.com/moonlight-stream/moonlight-docs/wiki/Frequently-Asked-Questions#why-is-my-frame-rate-low-when-streaming-my-desktop-on-a-laptop-with-nvidia-optimus) with NVIDIA GameStream and Optimus.
> 
> Does the problem persist in games? If so, which games have you tried?

Yes, I tried a lot of games, including games made by unity engine, RPGmaker, unreal engine and so on. No game can run at a high frame rate, just like on the desktop.

**Comment by BigBuge** [comment]
> I think you may be encountering [this issue](https://github.com/moonlight-stream/moonlight-docs/wiki/Frequently-Asked-Questions#why-is-my-frame-rate-low-when-streaming-my-desktop-on-a-laptop-with-nvidia-optimus) with NVIDIA GameStream and Optimus.
> 
> Does the problem persist in games? If so, which games have you tried?

And, I think you are right, it is most likely caused by Optimus. But i don`t know how to fix it. Can you give me some suggest?

**Comment by Hellobaka** [comment]
目前发现是高版本的问题，尤其是今年年初更新的那几个版本。建议回退到`3.20.2.34`版本，并且搜一个方法屏蔽掉`Geforce Experience`的自更新

**Comment by ANDYWANGTIANTIAN** [comment]
> 目前发现是高版本的问题，尤其是今年年初更新的那几个版本。建议回退到`3.20.2.34`版本，并且搜一个方法屏蔽掉`Geforce Experience`的自更新，实测在回退版本之后帧数能够上升到设置的值

我也遇到了这个问题，请问`3.20.2.34`版本是指moonlight吗（并没有在release中搜到这个版本），还有nvidia optimus需要关闭吗，我的笔记本电脑的控制台内有显卡切换的选项（rog的armoury crate），是否可以直接用这个选项关闭nvidia optimus呢？

**Comment by Hellobaka** [comment]
@ANDYWANGTIANTIAN 此版本号指的是`Geforce Experience`的版本，独显直连并不需要关
![image](https://user-images.githubusercontent.com/50934714/140515975-8e4082fd-b270-405e-86c9-dc9d28c8dc33.png)

**Comment by ANDYWANGTIANTIAN** [comment]
> @ANDYWANGTIANTIAN 此版本号指的是`Geforce Experience`的版本，独显直连并不需要关 ![image](https://user-images.githubusercontent.com/50934714/140515975-8e4082fd-b270-405e-86c9-dc9d28c8dc33.png)

我已经退回到3.20.2.34版本，但好像这个版本的gfe不让我开启shield串流（我的显卡是3070 laptop），显示显卡不符合要求，请问这个有办法解决吗

**Comment by Hellobaka** [comment]
@ANDYWANGTIANTIAN 抱歉，这部分我就没了解过了。我的显卡是笔记本的2060，串流帧数也正常，或许你可以试试之后的若干个版本。我记着出现帧数不正常是2021年初的几个版本，你可以试试去年的一些版本，比如`3.20.5.70`，这个是去年十月的版本，或许就有用了呢

**Comment by ANDYWANGTIANTIAN** [comment]
> @ANDYWANGTIANTIAN 抱歉，这部分我就没了解过了。我的显卡是笔记本的2060，串流帧数也正常，或许你可以试试之后的若干个版本。我记着出现帧数不正常是2021年初的几个版本，你可以试试去年的一些版本，比如`3.20.5.70`，这个是去年十月的版本，或许就有用了呢

我已经使用显卡欺骗器绕过了这一问题，只需要在笔记本的显示插口上插上显卡欺骗器（我的电脑比较特殊，需要通过type-c接口转接），再在拓展设置中选择“仅第二屏幕”即可（此时电脑会黑屏，使用moonlight连接正常使用）
