### ISSUE TITLE
Question: How do I turn on the virtual KB on moonlight for Android TV?

### ISSUE THREAD

**Issue by sentix001** [moonlight-stream/moonlight-android#983]
On the Android phone, I can turn on the virtual keyboard by touching with three fingers. So how can I turn on the virtual keyboard on the Android TV?

**Comment by chudczan** [comment]
I repeat the question

**Comment by christopher-s** [comment]
I would also like to know how to do this. At this point, the use of Moonlight for Nvidia Shield is more limited as I can't pop open a virtual keyboard with the gamepad.
