### ISSUE TITLE
VirtualBox streaming session closes after reaching the virtual OS desktop

### ISSUE THREAD

**Issue by RaouleMenard** [moonlight-stream/moonlight-android#991]
Hello,

I'm streaming the whole desktop of my server - a Windows 10 PC connected to a TV - to either another Windows 10 PC or an Android 9 phone.

When launching VirtualBox in this stream emulating Windows XP, the boot sequence works normally but as soon as I reach the XP desktop, the streaming session of moonlight closes. The server PC is still running fine - as checked on the TV.

Here's a few more specs:
- Server: Windows 10 x64, Intel i5-10400F, Nvidia RTX 3060 ti, 32 GB RAM, latest drivers. Running Oracle VirtualBox latest stable emulating Windows XP.
- Client A: Windows 10 x64, Intel i7-9700K, Nvidia RTX 3080, 32 GB RAM, latest drivers.
- Client B: Android 9, Sony Xperia XA2 Ultra.

Is there a way to fix this? Thanks!

**Comment by RaouleMenard** [comment]
UPDATE: I've figured out what is causing this issue.

This issue happen when the guest additions are installed, and more specifically when the seamless mouse is active.

Disabling the seamless mouse fixes the issue.

Though, I wonder if it could be fixed including the seamless mouse - as it is a great feature.

**Comment by cgutman** [comment]
The termination must have been triggered by the host. You should be able to see the error if you look at your Nvidia host-side logs in: `C:\ProgramData\NVIDIA Corporation\NvStream`.

`C:\ProgramData` is a hidden folder, so you may need to enable viewing hidden files or type the path into File Explorer manually

**Comment by RaouleMenard** [comment]
> The termination must have been triggered by the host. You should be able to see the error if you look at your Nvidia host-side logs in: `C:\ProgramData\NVIDIA Corporation\NvStream`.

Hi, here's the log attached. Can you tell what is the problem? Thanks!

[nvstream_log.txt](https://github.com/moonlight-stream/moonlight-android/files/6888015/nvstream_log.txt)

**Comment by RaouleMenard** [comment]
Hello, can anyone please help on this? Please check the log file one post above. Thanks.
