### ISSUE TITLE
Game names do not appear on list

### ISSUE THREAD

**Issue by thejavascriptman** [moonlight-stream/moonlight-android#992]
**Describe the bug**
After connecting to my PC over the local network, Moonlight does not show the game titles or the titles start appearing seemly randomly or after some user interaction, and sometimes other titles get hidden. This issue seems to be present on the Asus Zenfone 7 (and maybe others?).

**Steps to reproduce**
* Install Moonlight from Google Play or F-Droid (issue is present on both versions)
* Connect to the streaming PC from Moonlight Android

**Screenshots**
![output](https://user-images.githubusercontent.com/46071365/125168189-20d94a80-e1df-11eb-973a-e5384f135e7f.gif)

**Other Moonlight clients**
- Tested Moonlight on other devices including a Windows PC, iPhone X and an old Android Phone, all of them display the game titles correctly.

**Moonlight settings (please complete the following information)**
- Using default settings, I even stopped Moonlight and cleared the Android cache and storage
- Also tried setting large thumbnails on settings -> no difference
- Also tried rotating the screen to see if the issue was related to the available with -> no difference

**Device details (please complete the following information)**
 - Android version:  Android 11
 - Device model: Asus Zenfone 7

**Server PC details (please complete the following information)**
 - OS: Windows 10 19041
 - GeForce Experience version: 3.23.0.74
 - Nvidia GPU driver: 471.11 
 - Antivirus and firewall software:  using Windows Defender defaults, also checked Firewall advanced settings and made sure that GFE is allowed.

**Comment by cgutman** [comment]
Interesting, I've seen this behavior in the Android emulators, but never on real hardware before now.
